// Auto-generated icon data for local browser
// Created by Igor Djugostran

window.ICON_DATA = [
  {"name": "abacus", "canonical": "abacus", "unicode": "f640", "label": "Abacus", "alias": false},
  {"name": "address-book", "canonical": "address-book", "unicode": "f2b9", "label": "Address Book", "alias": false},
  {"name": "airplay", "canonical": "airplay", "unicode": "e089", "label": "Airplay", "alias": false},
  {"name": "alarm-clock", "canonical": "alarm-clock", "unicode": "f34e", "label": "Alarm Clock", "alias": false},
  {"name": "album", "canonical": "album", "unicode": "f89f", "label": "Album", "alias": false},
  {"name": "anchor", "canonical": "anchor", "unicode": "f13d", "label": "Anchor", "alias": false},
  {"name": "ant", "canonical": "ant", "unicode": "e680", "label": "Ant", "alias": false},
  {"name": "apartment", "canonical": "apartment", "unicode": "e468", "label": "Apartment", "alias": false},
  {"name": "apple-whole", "canonical": "apple-whole", "unicode": "f5d1", "label": "Apple Whole", "alias": false},
  {"name": "avocado", "canonical": "avocado", "unicode": "e0aa", "label": "Avocado", "alias": false},
  {"name": "award", "canonical": "award", "unicode": "f559", "label": "Award", "alias": false},
  {"name": "axe", "canonical": "axe", "unicode": "f6b2", "label": "Axe", "alias": false},
  {"name": "baby", "canonical": "baby", "unicode": "f77c", "label": "Baby", "alias": false},
  {"name": "baby-carriage", "canonical": "baby-carriage", "unicode": "f77d", "label": "Baby Carriage", "alias": false},
  {"name": "backpack", "canonical": "backpack", "unicode": "f5d4", "label": "Backpack", "alias": false},
  {"name": "bacon", "canonical": "bacon", "unicode": "f7e5", "label": "Bacon", "alias": false},
  {"name": "badge-dollar", "canonical": "badge-dollar", "unicode": "f645", "label": "Badge Dollar", "alias": false},
  {"name": "badminton", "canonical": "badminton", "unicode": "e33a", "label": "Badminton", "alias": false},
  {"name": "bag-shopping", "canonical": "bag-shopping", "unicode": "f290", "label": "Bag Shopping", "alias": false},
  {"name": "bagel", "canonical": "bagel", "unicode": "e3d7", "label": "Bagel", "alias": false},
  {"name": "bags-shopping", "canonical": "bags-shopping", "unicode": "f847", "label": "Bags Shopping", "alias": false},
  {"name": "baguette", "canonical": "baguette", "unicode": "e3d8", "label": "Baguette", "alias": false},
  {"name": "baht-sign", "canonical": "baht-sign", "unicode": "e0ac", "label": "Baht Sign", "alias": false},
  {"name": "balloon", "canonical": "balloon", "unicode": "e2e3", "label": "Balloon", "alias": false},
  {"name": "balloons", "canonical": "balloons", "unicode": "e2e4", "label": "Balloons", "alias": false},
  {"name": "banana", "canonical": "banana", "unicode": "e2e5", "label": "Banana", "alias": false},
  {"name": "bandage", "canonical": "bandage", "unicode": "f462", "label": "Bandage", "alias": false},
  {"name": "barcode", "canonical": "barcode", "unicode": "f02a", "label": "Barcode", "alias": false},
  {"name": "baseball", "canonical": "baseball", "unicode": "f433", "label": "Baseball", "alias": false},
  {"name": "baseball-bat", "canonical": "baseball-bat", "unicode": "e7e5", "label": "Baseball Bat", "alias": false},
  {"name": "basket-shopping", "canonical": "basket-shopping", "unicode": "f291", "label": "Basket Shopping", "alias": false},
  {"name": "basketball", "canonical": "basketball", "unicode": "f434", "label": "Basketball", "alias": false},
  {"name": "bat", "canonical": "bat", "unicode": "f6b5", "label": "Bat", "alias": false},
  {"name": "bath", "canonical": "bath", "unicode": "f2cd", "label": "Bath", "alias": false},
  {"name": "battery-bolt", "canonical": "battery-bolt", "unicode": "f376", "label": "Battery Bolt", "alias": false},
  {"name": "bed", "canonical": "bed", "unicode": "f236", "label": "Bed", "alias": false},
  {"name": "bed-bunk", "canonical": "bed-bunk", "unicode": "f8f8", "label": "Bed Bunk", "alias": false},
  {"name": "bell", "canonical": "bell", "unicode": "f0f3", "label": "Bell", "alias": false},
  {"name": "bell-ring", "canonical": "bell-ring", "unicode": "e62c", "label": "Bell Ring", "alias": false},
  {"name": "bell-school", "canonical": "bell-school", "unicode": "f5d5", "label": "Bell School", "alias": false},
  {"name": "bells", "canonical": "bells", "unicode": "f77f", "label": "Bells", "alias": false},
  {"name": "bench-tree", "canonical": "bench-tree", "unicode": "e2e7", "label": "Bench Tree", "alias": false},
  {"name": "bicycle", "canonical": "bicycle", "unicode": "f206", "label": "Bicycle", "alias": false},
  {"name": "billboard", "canonical": "billboard", "unicode": "e5cd", "label": "Billboard", "alias": false},
  {"name": "bin", "canonical": "bin", "unicode": "e763", "label": "Bin", "alias": false},
  {"name": "bin-bottles", "canonical": "bin-bottles", "unicode": "e5f5", "label": "Bin Bottles", "alias": false},
  {"name": "bin-recycle", "canonical": "bin-recycle", "unicode": "e5f7", "label": "Bin Recycle", "alias": false},
  {"name": "binoculars", "canonical": "binoculars", "unicode": "f1e5", "label": "Binoculars", "alias": false},
  {"name": "bird", "canonical": "bird", "unicode": "e469", "label": "Bird", "alias": false},
  {"name": "bitcoin-sign", "canonical": "bitcoin-sign", "unicode": "e0b4", "label": "Bitcoin Sign", "alias": false},
  {"name": "blender", "canonical": "blender", "unicode": "f517", "label": "Blender", "alias": false},
  {"name": "blueberries", "canonical": "blueberries", "unicode": "e2e8", "label": "Blueberries", "alias": false},
  {"name": "bluetooth", "canonical": "bluetooth", "unicode": "f293", "label": "Bluetooth", "alias": false},
  {"name": "bolt", "canonical": "bolt", "unicode": "f0e7", "label": "Bolt", "alias": false},
  {"name": "bolt-lightning", "canonical": "bolt-lightning", "unicode": "e0b7", "label": "Bolt Lightning", "alias": false},
  {"name": "bone", "canonical": "bone", "unicode": "f5d7", "label": "Bone", "alias": false},
  {"name": "book", "canonical": "book", "unicode": "f02d", "label": "Book", "alias": false},
  {"name": "book-bible", "canonical": "book-bible", "unicode": "f647", "label": "Book Bible", "alias": false},
  {"name": "book-medical", "canonical": "book-medical", "unicode": "f7e6", "label": "Book Medical", "alias": false},
  {"name": "book-sparkles", "canonical": "book-sparkles", "unicode": "f6b8", "label": "Book Sparkles", "alias": false},
  {"name": "books", "canonical": "books", "unicode": "f5db", "label": "Books", "alias": false},
  {"name": "boombox", "canonical": "boombox", "unicode": "f8a5", "label": "Boombox", "alias": false},
  {"name": "boot", "canonical": "boot", "unicode": "f782", "label": "Boot", "alias": false},
  {"name": "booth-curtain", "canonical": "booth-curtain", "unicode": "f734", "label": "Booth Curtain", "alias": false},
  {"name": "bottle-water", "canonical": "bottle-water", "unicode": "e4c5", "label": "Bottle Water", "alias": false},
  {"name": "bow-arrow", "canonical": "bow-arrow", "unicode": "f6b9", "label": "Bow Arrow", "alias": false},
  {"name": "bowl-food", "canonical": "bowl-food", "unicode": "e4c6", "label": "Bowl Food", "alias": false},
  {"name": "bowl-rice", "canonical": "bowl-rice", "unicode": "e2eb", "label": "Bowl Rice", "alias": false},
  {"name": "bowling-ball", "canonical": "bowling-ball", "unicode": "f436", "label": "Bowling Ball", "alias": false},
  {"name": "box", "canonical": "box", "unicode": "f466", "label": "Box", "alias": false},
  {"name": "box-open", "canonical": "box-open", "unicode": "f49e", "label": "Box Open", "alias": false},
  {"name": "boxes-packing", "canonical": "boxes-packing", "unicode": "e4c7", "label": "Boxes Packing", "alias": false},
  {"name": "braille", "canonical": "braille", "unicode": "f2a1", "label": "Braille", "alias": false},
  {"name": "brain", "canonical": "brain", "unicode": "f5dc", "label": "Brain", "alias": false},
  {"name": "brain-circuit", "canonical": "brain-circuit", "unicode": "e0c6", "label": "Brain Circuit", "alias": false},
  {"name": "bread-loaf", "canonical": "bread-loaf", "unicode": "f7eb", "label": "Bread Loaf", "alias": false},
  {"name": "bread-slice", "canonical": "bread-slice", "unicode": "f7ec", "label": "Bread Slice", "alias": false},
  {"name": "briefcase", "canonical": "briefcase", "unicode": "f0b1", "label": "Briefcase", "alias": false},
  {"name": "briefcase-medical", "canonical": "briefcase-medical", "unicode": "f469", "label": "Briefcase Medical", "alias": false},
  {"name": "broccoli", "canonical": "broccoli", "unicode": "e3e2", "label": "Broccoli", "alias": false},
  {"name": "broom", "canonical": "broom", "unicode": "f51a", "label": "Broom", "alias": false},
  {"name": "broom-wide", "canonical": "broom-wide", "unicode": "e5d1", "label": "Broom Wide", "alias": false},
  {"name": "browser", "canonical": "browser", "unicode": "f37e", "label": "Browser", "alias": false},
  {"name": "brush", "canonical": "brush", "unicode": "f55d", "label": "Brush", "alias": false},
  {"name": "bucket", "canonical": "bucket", "unicode": "e4cf", "label": "Bucket", "alias": false},
  {"name": "bug", "canonical": "bug", "unicode": "f188", "label": "Bug", "alias": false},
  {"name": "building", "canonical": "building", "unicode": "f1ad", "label": "Building", "alias": false},
  {"name": "buildings", "canonical": "buildings", "unicode": "e0cc", "label": "Buildings", "alias": false},
  {"name": "bullseye", "canonical": "bullseye", "unicode": "f140", "label": "Bullseye", "alias": false},
  {"name": "bullseye-pointer", "canonical": "bullseye-pointer", "unicode": "f649", "label": "Bullseye Pointer", "alias": false},
  {"name": "burger", "canonical": "burger", "unicode": "f805", "label": "Burger", "alias": false},
  {"name": "burger-cheese", "canonical": "burger-cheese", "unicode": "f7f1", "label": "Burger Cheese", "alias": false},
  {"name": "burrito", "canonical": "burrito", "unicode": "f7ed", "label": "Burrito", "alias": false},
  {"name": "bus", "canonical": "bus", "unicode": "f207", "label": "Bus", "alias": false},
  {"name": "butter", "canonical": "butter", "unicode": "e3e4", "label": "Butter", "alias": false},
  {"name": "butterfly", "canonical": "butterfly", "unicode": "e811", "label": "Butterfly", "alias": false},
  {"name": "cabinet-filing", "canonical": "cabinet-filing", "unicode": "f64b", "label": "Cabinet Filing", "alias": false},
  {"name": "cable-car", "canonical": "cable-car", "unicode": "f7da", "label": "Cable Car", "alias": false},
  {"name": "cake-candles", "canonical": "cake-candles", "unicode": "f1fd", "label": "Cake Candles", "alias": false},
  {"name": "cake-slice", "canonical": "cake-slice", "unicode": "e3e5", "label": "Cake Slice", "alias": false},
  {"name": "calculator", "canonical": "calculator", "unicode": "f1ec", "label": "Calculator", "alias": false},
  {"name": "calendar", "canonical": "calendar", "unicode": "f133", "label": "Calendar", "alias": false},
  {"name": "camera", "canonical": "camera", "unicode": "f030", "label": "Camera", "alias": false},
  {"name": "campfire", "canonical": "campfire", "unicode": "f6ba", "label": "Campfire", "alias": false},
  {"name": "can-food", "canonical": "can-food", "unicode": "e3e6", "label": "Can Food", "alias": false},
  {"name": "candy", "canonical": "candy", "unicode": "e3e7", "label": "Candy", "alias": false},
  {"name": "candy-cane", "canonical": "candy-cane", "unicode": "f786", "label": "Candy Cane", "alias": false},
  {"name": "cannon", "canonical": "cannon", "unicode": "e642", "label": "Cannon", "alias": false},
  {"name": "capsule", "canonical": "capsule", "unicode": "e75a", "label": "Capsule", "alias": false},
  {"name": "capsules", "canonical": "capsules", "unicode": "f46b", "label": "Capsules", "alias": false},
  {"name": "car", "canonical": "car", "unicode": "f1b9", "label": "Car", "alias": false},
  {"name": "car-battery", "canonical": "car-battery", "unicode": "f5df", "label": "Car Battery", "alias": false},
  {"name": "car-bolt", "canonical": "car-bolt", "unicode": "e341", "label": "Car Bolt", "alias": false},
  {"name": "car-key", "canonical": "car-key", "unicode": "e7c0", "label": "Car Key", "alias": false},
  {"name": "caravan", "canonical": "caravan", "unicode": "f8ff", "label": "Caravan", "alias": false},
  {"name": "cards-blank", "canonical": "cards-blank", "unicode": "e4df", "label": "Cards Blank", "alias": false},
  {"name": "carpool", "canonical": "carpool", "unicode": "e69c", "label": "Carpool", "alias": false},
  {"name": "carrot", "canonical": "carrot", "unicode": "f787", "label": "Carrot", "alias": false},
  {"name": "cart-flatbed", "canonical": "cart-flatbed", "unicode": "f474", "label": "Cart Flatbed", "alias": false},
  {"name": "cart-shopping", "canonical": "cart-shopping", "unicode": "f07a", "label": "Cart Shopping", "alias": false},
  {"name": "cash-register", "canonical": "cash-register", "unicode": "f788", "label": "Cash Register", "alias": false},
  {"name": "cat", "canonical": "cat", "unicode": "f6be", "label": "Cat", "alias": false},
  {"name": "cauldron", "canonical": "cauldron", "unicode": "f6bf", "label": "Cauldron", "alias": false},
  {"name": "cent-sign", "canonical": "cent-sign", "unicode": "e3f5", "label": "Cent Sign", "alias": false},
  {"name": "chair", "canonical": "chair", "unicode": "f6c0", "label": "Chair", "alias": false},
  {"name": "chair-office", "canonical": "chair-office", "unicode": "f6c1", "label": "Chair Office", "alias": false},
  {"name": "chalkboard", "canonical": "chalkboard", "unicode": "f51b", "label": "Chalkboard", "alias": false},
  {"name": "chalkboard-user", "canonical": "chalkboard-user", "unicode": "f51c", "label": "Chalkboard User", "alias": false},
  {"name": "champagne-glass", "canonical": "champagne-glass", "unicode": "f79e", "label": "Champagne Glass", "alias": false},
  {"name": "champagne-glasses", "canonical": "champagne-glasses", "unicode": "f79f", "label": "Champagne Glasses", "alias": false},
  {"name": "charging-station", "canonical": "charging-station", "unicode": "f5e7", "label": "Charging Station", "alias": false},
  {"name": "chart-gantt", "canonical": "chart-gantt", "unicode": "e0e4", "label": "Chart Gantt", "alias": false},
  {"name": "chart-pie", "canonical": "chart-pie", "unicode": "f200", "label": "Chart Pie", "alias": false},
  {"name": "cheese", "canonical": "cheese", "unicode": "f7ef", "label": "Cheese", "alias": false},
  {"name": "cheese-swiss", "canonical": "cheese-swiss", "unicode": "f7f0", "label": "Cheese Swiss", "alias": false},
  {"name": "cherries", "canonical": "cherries", "unicode": "e0ec", "label": "Cherries", "alias": false},
  {"name": "chess", "canonical": "chess", "unicode": "f439", "label": "Chess", "alias": false},
  {"name": "chess-board", "canonical": "chess-board", "unicode": "f43c", "label": "Chess Board", "alias": false},
  {"name": "chf-sign", "canonical": "chf-sign", "unicode": "e602", "label": "Chf Sign", "alias": false},
  {"name": "child", "canonical": "child", "unicode": "f1ae", "label": "Child", "alias": false},
  {"name": "chimney", "canonical": "chimney", "unicode": "f78b", "label": "Chimney", "alias": false},
  {"name": "chopsticks", "canonical": "chopsticks", "unicode": "e3f7", "label": "Chopsticks", "alias": false},
  {"name": "church", "canonical": "church", "unicode": "f51d", "label": "Church", "alias": false},
  {"name": "citrus", "canonical": "citrus", "unicode": "e2f4", "label": "Citrus", "alias": false},
  {"name": "clapperboard", "canonical": "clapperboard", "unicode": "e131", "label": "Clapperboard", "alias": false},
  {"name": "clipboard-list", "canonical": "clipboard-list", "unicode": "f46d", "label": "Clipboard List", "alias": false},
  {"name": "clock", "canonical": "clock", "unicode": "f017", "label": "Clock", "alias": false},
  {"name": "clothes-hanger", "canonical": "clothes-hanger", "unicode": "e136", "label": "Clothes Hanger", "alias": false},
  {"name": "cloud", "canonical": "cloud", "unicode": "f0c2", "label": "Cloud", "alias": false},
  {"name": "cloud-meatball", "canonical": "cloud-meatball", "unicode": "f73b", "label": "Cloud Meatball", "alias": false},
  {"name": "cloud-music", "canonical": "cloud-music", "unicode": "f8ae", "label": "Cloud Music", "alias": false},
  {"name": "cloud-sun", "canonical": "cloud-sun", "unicode": "f6c4", "label": "Cloud Sun", "alias": false},
  {"name": "clouds-sun", "canonical": "clouds-sun", "unicode": "f746", "label": "Clouds Sun", "alias": false},
  {"name": "code", "canonical": "code", "unicode": "f121", "label": "Code", "alias": false},
  {"name": "coffee-pot", "canonical": "coffee-pot", "unicode": "e002", "label": "Coffee Pot", "alias": false},
  {"name": "coin", "canonical": "coin", "unicode": "f85c", "label": "Coin", "alias": false},
  {"name": "coins", "canonical": "coins", "unicode": "f51e", "label": "Coins", "alias": false},
  {"name": "command", "canonical": "command", "unicode": "e142", "label": "Command", "alias": false},
  {"name": "comment", "canonical": "comment", "unicode": "f075", "label": "Comment", "alias": false},
  {"name": "compact-disc", "canonical": "compact-disc", "unicode": "f51f", "label": "Compact Disc", "alias": false},
  {"name": "compass", "canonical": "compass", "unicode": "f14e", "label": "Compass", "alias": false},
  {"name": "compass-drafting", "canonical": "compass-drafting", "unicode": "f568", "label": "Compass Drafting", "alias": false},
  {"name": "computer", "canonical": "computer", "unicode": "e4e5", "label": "Computer", "alias": false},
  {"name": "computer-mouse", "canonical": "computer-mouse", "unicode": "f8cc", "label": "Computer Mouse", "alias": false},
  {"name": "container-storage", "canonical": "container-storage", "unicode": "f4b7", "label": "Container Storage", "alias": false},
  {"name": "conveyor-belt", "canonical": "conveyor-belt", "unicode": "f46e", "label": "Conveyor Belt", "alias": false},
  {"name": "cookie", "canonical": "cookie", "unicode": "f563", "label": "Cookie", "alias": false},
  {"name": "cookie-bite", "canonical": "cookie-bite", "unicode": "f564", "label": "Cookie Bite", "alias": false},
  {"name": "copy", "canonical": "copy", "unicode": "f0c5", "label": "Copy", "alias": false},
  {"name": "corn", "canonical": "corn", "unicode": "f6c7", "label": "Corn", "alias": false},
  {"name": "couch", "canonical": "couch", "unicode": "f4b8", "label": "Couch", "alias": false},
  {"name": "court-sport", "canonical": "court-sport", "unicode": "e643", "label": "Court Sport", "alias": false},
  {"name": "cow", "canonical": "cow", "unicode": "f6c8", "label": "Cow", "alias": false},
  {"name": "crab", "canonical": "crab", "unicode": "e3ff", "label": "Crab", "alias": false},
  {"name": "credit-card", "canonical": "credit-card", "unicode": "f09d", "label": "Credit Card", "alias": false},
  {"name": "croissant", "canonical": "croissant", "unicode": "f7f6", "label": "Croissant", "alias": false},
  {"name": "crop", "canonical": "crop", "unicode": "f125", "label": "Crop", "alias": false},
  {"name": "cross", "canonical": "cross", "unicode": "f654", "label": "Cross", "alias": false},
  {"name": "crosshairs", "canonical": "crosshairs", "unicode": "f05b", "label": "Crosshairs", "alias": false},
  {"name": "crow", "canonical": "crow", "unicode": "f520", "label": "Crow", "alias": false},
  {"name": "crown", "canonical": "crown", "unicode": "f521", "label": "Crown", "alias": false},
  {"name": "cucumber", "canonical": "cucumber", "unicode": "e401", "label": "Cucumber", "alias": false},
  {"name": "cup-togo", "canonical": "cup-togo", "unicode": "f6c5", "label": "Cup Togo", "alias": false},
  {"name": "cupcake", "canonical": "cupcake", "unicode": "e402", "label": "Cupcake", "alias": false},
  {"name": "curling-stone", "canonical": "curling-stone", "unicode": "f44a", "label": "Curling Stone", "alias": false},
  {"name": "dagger", "canonical": "dagger", "unicode": "f6cb", "label": "Dagger", "alias": false},
  {"name": "database", "canonical": "database", "unicode": "f1c0", "label": "Database", "alias": false},
  {"name": "deer", "canonical": "deer", "unicode": "f78e", "label": "Deer", "alias": false},
  {"name": "desktop", "canonical": "desktop", "unicode": "f390", "label": "Desktop", "alias": false},
  {"name": "diagram-project", "canonical": "diagram-project", "unicode": "f542", "label": "Diagram Project", "alias": false},
  {"name": "diagram-venn", "canonical": "diagram-venn", "unicode": "e15a", "label": "Diagram Venn", "alias": false},
  {"name": "dial", "canonical": "dial", "unicode": "e15b", "label": "Dial", "alias": false},
  {"name": "dice", "canonical": "dice", "unicode": "f522", "label": "Dice", "alias": false},
  {"name": "diploma", "canonical": "diploma", "unicode": "f5ea", "label": "Diploma", "alias": false},
  {"name": "display", "canonical": "display", "unicode": "e163", "label": "Display", "alias": false},
  {"name": "dna", "canonical": "dna", "unicode": "f471", "label": "DNA", "alias": false},
  {"name": "dog", "canonical": "dog", "unicode": "f6d3", "label": "Dog", "alias": false},
  {"name": "dog-leashed", "canonical": "dog-leashed", "unicode": "f6d4", "label": "Dog Leashed", "alias": false},
  {"name": "dollar-sign", "canonical": "dollar-sign", "unicode": "24", "label": "Dollar Sign", "alias": false},
  {"name": "dolly", "canonical": "dolly", "unicode": "f472", "label": "Dolly", "alias": false},
  {"name": "dolphin", "canonical": "dolphin", "unicode": "e168", "label": "Dolphin", "alias": false},
  {"name": "donut", "canonical": "donut", "unicode": "e406", "label": "Donut", "alias": false},
  {"name": "door-closed", "canonical": "door-closed", "unicode": "f52a", "label": "Door Closed", "alias": false},
  {"name": "dove", "canonical": "dove", "unicode": "f4ba", "label": "Dove", "alias": false},
  {"name": "dress", "canonical": "dress", "unicode": "e6d1", "label": "Dress", "alias": false},
  {"name": "drone", "canonical": "drone", "unicode": "f85f", "label": "Drone", "alias": false},
  {"name": "drone-front", "canonical": "drone-front", "unicode": "f860", "label": "Drone Front", "alias": false},
  {"name": "droplet", "canonical": "droplet", "unicode": "f043", "label": "Droplet", "alias": false},
  {"name": "drum", "canonical": "drum", "unicode": "f569", "label": "Drum", "alias": false},
  {"name": "dryer", "canonical": "dryer", "unicode": "f861", "label": "Dryer", "alias": false},
  {"name": "duck", "canonical": "duck", "unicode": "f6d8", "label": "Duck", "alias": false},
  {"name": "dumbbell", "canonical": "dumbbell", "unicode": "f44b", "label": "Dumbbell", "alias": false},
  {"name": "ear", "canonical": "ear", "unicode": "f5f0", "label": "Ear", "alias": false},
  {"name": "egg", "canonical": "egg", "unicode": "f7fb", "label": "Egg", "alias": false},
  {"name": "egg-fried", "canonical": "egg-fried", "unicode": "f7fc", "label": "Egg Fried", "alias": false},
  {"name": "elephant", "canonical": "elephant", "unicode": "f6da", "label": "Elephant", "alias": false},
  {"name": "elevator", "canonical": "elevator", "unicode": "e16d", "label": "Elevator", "alias": false},
  {"name": "engine", "canonical": "engine", "unicode": "e16e", "label": "Engine", "alias": false},
  {"name": "envelope", "canonical": "envelope", "unicode": "f0e0", "label": "Envelope", "alias": false},
  {"name": "eraser", "canonical": "eraser", "unicode": "f12d", "label": "Eraser", "alias": false},
  {"name": "ethernet", "canonical": "ethernet", "unicode": "f796", "label": "Ethernet", "alias": false},
  {"name": "euro-sign", "canonical": "euro-sign", "unicode": "f153", "label": "Euro Sign", "alias": false},
  {"name": "expand", "canonical": "expand", "unicode": "f065", "label": "Expand", "alias": false},
  {"name": "eye", "canonical": "eye", "unicode": "f06e", "label": "Eye", "alias": false},
  {"name": "face-exhaling", "canonical": "face-exhaling", "unicode": "e480", "label": "Face Exhaling", "alias": false},
  {"name": "face-woozy", "canonical": "face-woozy", "unicode": "e3a2", "label": "Face Woozy", "alias": false},
  {"name": "falafel", "canonical": "falafel", "unicode": "e40a", "label": "Falafel", "alias": false},
  {"name": "family", "canonical": "family", "unicode": "e300", "label": "Family", "alias": false},
  {"name": "fan", "canonical": "fan", "unicode": "f863", "label": "Fan", "alias": false},
  {"name": "faucet", "canonical": "faucet", "unicode": "e005", "label": "Faucet", "alias": false},
  {"name": "fax", "canonical": "fax", "unicode": "f1ac", "label": "Fax", "alias": false},
  {"name": "ferris-wheel", "canonical": "ferris-wheel", "unicode": "e174", "label": "Ferris Wheel", "alias": false},
  {"name": "file", "canonical": "file", "unicode": "f15b", "label": "File", "alias": false},
  {"name": "film", "canonical": "film", "unicode": "f008", "label": "Film", "alias": false},
  {"name": "film-canister", "canonical": "film-canister", "unicode": "f8b7", "label": "Film Canister", "alias": false},
  {"name": "fingerprint", "canonical": "fingerprint", "unicode": "f577", "label": "Fingerprint", "alias": false},
  {"name": "fire", "canonical": "fire", "unicode": "f06d", "label": "Fire", "alias": false},
  {"name": "fish", "canonical": "fish", "unicode": "f578", "label": "Fish", "alias": false},
  {"name": "flag", "canonical": "flag", "unicode": "f024", "label": "Flag", "alias": false},
  {"name": "flag-checkered", "canonical": "flag-checkered", "unicode": "f11e", "label": "Flag Checkered", "alias": false},
  {"name": "flashlight", "canonical": "flashlight", "unicode": "f8b8", "label": "Flashlight", "alias": false},
  {"name": "flask", "canonical": "flask", "unicode": "f0c3", "label": "Flask", "alias": false},
  {"name": "flatbread", "canonical": "flatbread", "unicode": "e40b", "label": "Flatbread", "alias": false},
  {"name": "flatbread-stuffed", "canonical": "flatbread-stuffed", "unicode": "e40c", "label": "Flatbread Stuffed", "alias": false},
  {"name": "floppy-disk", "canonical": "floppy-disk", "unicode": "f0c7", "label": "Floppy Disk", "alias": false},
  {"name": "flower", "canonical": "flower", "unicode": "f7ff", "label": "Flower", "alias": false},
  {"name": "football", "canonical": "football", "unicode": "f44e", "label": "Football", "alias": false},
  {"name": "fork", "canonical": "fork", "unicode": "f2e3", "label": "Fork", "alias": false},
  {"name": "fork-knife", "canonical": "fork-knife", "unicode": "f2e6", "label": "Fork Knife", "alias": false},
  {"name": "forklift", "canonical": "forklift", "unicode": "f47a", "label": "Forklift", "alias": false},
  {"name": "frame", "canonical": "frame", "unicode": "e495", "label": "Frame", "alias": false},
  {"name": "french-fries", "canonical": "french-fries", "unicode": "f803", "label": "French Fries", "alias": false},
  {"name": "frog", "canonical": "frog", "unicode": "f52e", "label": "Frog", "alias": false},
  {"name": "futbol", "canonical": "futbol", "unicode": "f1e3", "label": "Futbol", "alias": false},
  {"name": "game-board", "canonical": "game-board", "unicode": "f867", "label": "Game Board", "alias": false},
  {"name": "gamepad", "canonical": "gamepad", "unicode": "f11b", "label": "Gamepad", "alias": false},
  {"name": "garage", "canonical": "garage", "unicode": "e009", "label": "Garage", "alias": false},
  {"name": "gauge", "canonical": "gauge", "unicode": "f624", "label": "Gauge", "alias": false},
  {"name": "gear", "canonical": "gear", "unicode": "f013", "label": "Gear", "alias": false},
  {"name": "gem", "canonical": "gem", "unicode": "f3a5", "label": "Gem", "alias": false},
  {"name": "gif", "canonical": "gif", "unicode": "e190", "label": "Gif", "alias": false},
  {"name": "gift", "canonical": "gift", "unicode": "f06b", "label": "Gift", "alias": false},
  {"name": "gingerbread-man", "canonical": "gingerbread-man", "unicode": "f79d", "label": "Gingerbread Man", "alias": false},
  {"name": "glasses", "canonical": "glasses", "unicode": "f530", "label": "Glasses", "alias": false},
  {"name": "globe", "canonical": "globe", "unicode": "f0ac", "label": "Globe", "alias": false},
  {"name": "globe-pointer", "canonical": "globe-pointer", "unicode": "e60e", "label": "Globe Pointer", "alias": false},
  {"name": "goal-net", "canonical": "goal-net", "unicode": "e3ab", "label": "Goal Net", "alias": false},
  {"name": "golf-club", "canonical": "golf-club", "unicode": "f451", "label": "Golf Club", "alias": false},
  {"name": "grill", "canonical": "grill", "unicode": "e5a3", "label": "Grill", "alias": false},
  {"name": "guitar", "canonical": "guitar", "unicode": "f7a6", "label": "Guitar", "alias": false},
  {"name": "guitar-electric", "canonical": "guitar-electric", "unicode": "f8be", "label": "Guitar Electric", "alias": false},
  {"name": "gun", "canonical": "gun", "unicode": "e19b", "label": "Gun", "alias": false},
  {"name": "hammer", "canonical": "hammer", "unicode": "f6e3", "label": "Hammer", "alias": false},
  {"name": "hammer-brush", "canonical": "hammer-brush", "unicode": "e620", "label": "Hammer Brush", "alias": false},
  {"name": "hand", "canonical": "hand", "unicode": "f256", "label": "Hand", "alias": false},
  {"name": "hand-heart", "canonical": "hand-heart", "unicode": "f4bc", "label": "Hand Heart", "alias": false},
  {"name": "hand-holding", "canonical": "hand-holding", "unicode": "f4bd", "label": "Hand Holding", "alias": false},
  {"name": "hand-pointer", "canonical": "hand-pointer", "unicode": "f25a", "label": "Hand Pointer", "alias": false},
  {"name": "hands", "canonical": "hands", "unicode": "f2a7", "label": "Hands", "alias": false},
  {"name": "hands-bubbles", "canonical": "hands-bubbles", "unicode": "e05e", "label": "Hands Bubbles", "alias": false},
  {"name": "hands-holding", "canonical": "hands-holding", "unicode": "f4c2", "label": "Hands Holding", "alias": false},
  {"name": "handshake", "canonical": "handshake", "unicode": "f2b5", "label": "Handshake", "alias": false},
  {"name": "hard-drive", "canonical": "hard-drive", "unicode": "f0a0", "label": "Hard Drive", "alias": false},
  {"name": "hat-chef", "canonical": "hat-chef", "unicode": "f86b", "label": "Hat Chef", "alias": false},
  {"name": "heading", "canonical": "heading", "unicode": "f1dc", "label": "Heading", "alias": false},
  {"name": "headphones", "canonical": "headphones", "unicode": "f025", "label": "Headphones", "alias": false},
  {"name": "headset", "canonical": "headset", "unicode": "f590", "label": "Headset", "alias": false},
  {"name": "heart", "canonical": "heart", "unicode": "f004", "label": "Heart", "alias": false},
  {"name": "heart-pulse", "canonical": "heart-pulse", "unicode": "f21e", "label": "Heart Pulse", "alias": false},
  {"name": "hearts", "canonical": "hearts", "unicode": "e78f", "label": "Hearts", "alias": false},
  {"name": "heat", "canonical": "heat", "unicode": "e00c", "label": "Heat", "alias": false},
  {"name": "helicopter", "canonical": "helicopter", "unicode": "f533", "label": "Helicopter", "alias": false},
  {"name": "helmet-battle", "canonical": "helmet-battle", "unicode": "f6eb", "label": "Helmet Battle", "alias": false},
  {"name": "hockey-mask", "canonical": "hockey-mask", "unicode": "f6ee", "label": "Hockey Mask", "alias": false},
  {"name": "hockey-puck", "canonical": "hockey-puck", "unicode": "f453", "label": "Hockey Puck", "alias": false},
  {"name": "hockey-stick", "canonical": "hockey-stick", "unicode": "e7e6", "label": "Hockey Stick", "alias": false},
  {"name": "hockey-sticks", "canonical": "hockey-sticks", "unicode": "f454", "label": "Hockey Sticks", "alias": false},
  {"name": "hood-cloak", "canonical": "hood-cloak", "unicode": "f6ef", "label": "Hood Cloak", "alias": false},
  {"name": "horse", "canonical": "horse", "unicode": "f6f0", "label": "Horse", "alias": false},
  {"name": "horse-saddle", "canonical": "horse-saddle", "unicode": "f8c3", "label": "Horse Saddle", "alias": false},
  {"name": "hose-reel", "canonical": "hose-reel", "unicode": "e41a", "label": "Hose Reel", "alias": false},
  {"name": "hospital", "canonical": "hospital", "unicode": "f0f8", "label": "Hospital", "alias": false},
  {"name": "hospital-user", "canonical": "hospital-user", "unicode": "f80d", "label": "Hospital User", "alias": false},
  {"name": "hospitals", "canonical": "hospitals", "unicode": "f80e", "label": "Hospitals", "alias": false},
  {"name": "hotdog", "canonical": "hotdog", "unicode": "f80f", "label": "Hotdog", "alias": false},
  {"name": "hotel", "canonical": "hotel", "unicode": "f594", "label": "Hotel", "alias": false},
  {"name": "hourglass", "canonical": "hourglass", "unicode": "f254", "label": "Hourglass", "alias": false},
  {"name": "house", "canonical": "house", "unicode": "f015", "label": "House", "alias": false},
  {"name": "hryvnia-sign", "canonical": "hryvnia-sign", "unicode": "f6f2", "label": "Hryvnia Sign", "alias": false},
  {"name": "ice-skate", "canonical": "ice-skate", "unicode": "f7ac", "label": "Ice Skate", "alias": false},
  {"name": "image", "canonical": "image", "unicode": "f03e", "label": "Image", "alias": false},
  {"name": "inbox", "canonical": "inbox", "unicode": "f01c", "label": "Inbox", "alias": false},
  {"name": "industry", "canonical": "industry", "unicode": "f275", "label": "Industry", "alias": false},
  {"name": "infinity", "canonical": "infinity", "unicode": "f534", "label": "Infinity", "alias": false},
  {"name": "jar", "canonical": "jar", "unicode": "e516", "label": "Jar", "alias": false},
  {"name": "jar-wheat", "canonical": "jar-wheat", "unicode": "e517", "label": "Jar Wheat", "alias": false},
  {"name": "jeans", "canonical": "jeans", "unicode": "e6d2", "label": "Jeans", "alias": false},
  {"name": "joint", "canonical": "joint", "unicode": "f595", "label": "Joint", "alias": false},
  {"name": "joystick", "canonical": "joystick", "unicode": "f8c5", "label": "Joystick", "alias": false},
  {"name": "jug-bottle", "canonical": "jug-bottle", "unicode": "e5fb", "label": "Jug Bottle", "alias": false},
  {"name": "jug-detergent", "canonical": "jug-detergent", "unicode": "e519", "label": "Jug Detergent", "alias": false},
  {"name": "kazoo", "canonical": "kazoo", "unicode": "f8c7", "label": "Kazoo", "alias": false},
  {"name": "kettlebell", "canonical": "kettlebell", "unicode": "e832", "label": "Kettlebell", "alias": false},
  {"name": "key", "canonical": "key", "unicode": "f084", "label": "Key", "alias": false},
  {"name": "keyboard", "canonical": "keyboard", "unicode": "f11c", "label": "Keyboard", "alias": false},
  {"name": "kit-medical", "canonical": "kit-medical", "unicode": "f479", "label": "Kit Medical", "alias": false},
  {"name": "kitchen-set", "canonical": "kitchen-set", "unicode": "e51a", "label": "Kitchen Set", "alias": false},
  {"name": "knife", "canonical": "knife", "unicode": "f2e4", "label": "Knife", "alias": false},
  {"name": "knife-kitchen", "canonical": "knife-kitchen", "unicode": "f6f5", "label": "Knife Kitchen", "alias": false},
  {"name": "lamp", "canonical": "lamp", "unicode": "f4ca", "label": "Lamp", "alias": false},
  {"name": "lamp-desk", "canonical": "lamp-desk", "unicode": "e014", "label": "Lamp Desk", "alias": false},
  {"name": "language", "canonical": "language", "unicode": "f1ab", "label": "Language", "alias": false},
  {"name": "laptop", "canonical": "laptop", "unicode": "f109", "label": "Laptop", "alias": false},
  {"name": "lasso-sparkles", "canonical": "lasso-sparkles", "unicode": "e1c9", "label": "Lasso Sparkles", "alias": false},
  {"name": "lemon", "canonical": "lemon", "unicode": "f094", "label": "Lemon", "alias": false},
  {"name": "light-ceiling", "canonical": "light-ceiling", "unicode": "e016", "label": "Light Ceiling", "alias": false},
  {"name": "lightbulb", "canonical": "lightbulb", "unicode": "f0eb", "label": "Lightbulb", "alias": false},
  {"name": "lights-holiday", "canonical": "lights-holiday", "unicode": "f7b2", "label": "Lights Holiday", "alias": false},
  {"name": "lips", "canonical": "lips", "unicode": "f600", "label": "Lips", "alias": false},
  {"name": "lira-sign", "canonical": "lira-sign", "unicode": "f195", "label": "Lira Sign", "alias": false},
  {"name": "list-check", "canonical": "list-check", "unicode": "f0ae", "label": "List Check", "alias": false},
  {"name": "litecoin-sign", "canonical": "litecoin-sign", "unicode": "e1d3", "label": "Litecoin Sign", "alias": false},
  {"name": "loader", "canonical": "loader", "unicode": "e1d4", "label": "Loader", "alias": false},
  {"name": "lobster", "canonical": "lobster", "unicode": "e421", "label": "Lobster", "alias": false},
  {"name": "location-crosshairs", "canonical": "location-crosshairs", "unicode": "f601", "label": "Location Crosshairs", "alias": false},
  {"name": "location-dot", "canonical": "location-dot", "unicode": "f3c5", "label": "Location Dot", "alias": false},
  {"name": "lock", "canonical": "lock", "unicode": "f023", "label": "Lock", "alias": false},
  {"name": "lock-open", "canonical": "lock-open", "unicode": "f3c1", "label": "Lock Open", "alias": false},
  {"name": "loveseat", "canonical": "loveseat", "unicode": "f4cc", "label": "Loveseat", "alias": false},
  {"name": "mace", "canonical": "mace", "unicode": "f6f8", "label": "Mace", "alias": false},
  {"name": "magnet", "canonical": "magnet", "unicode": "f076", "label": "Magnet", "alias": false},
  {"name": "magnifying-glass", "canonical": "magnifying-glass", "unicode": "f002", "label": "Magnifying Glass", "alias": false},
  {"name": "mailbox", "canonical": "mailbox", "unicode": "f813", "label": "Mailbox", "alias": false},
  {"name": "mandolin", "canonical": "mandolin", "unicode": "f6f9", "label": "Mandolin", "alias": false},
  {"name": "manhole", "canonical": "manhole", "unicode": "e1d6", "label": "Manhole", "alias": false},
  {"name": "map", "canonical": "map", "unicode": "f279", "label": "Map", "alias": false},
  {"name": "map-location", "canonical": "map-location", "unicode": "f59f", "label": "Map Location", "alias": false},
  {"name": "map-pin", "canonical": "map-pin", "unicode": "f276", "label": "Map Pin", "alias": false},
  {"name": "marker", "canonical": "marker", "unicode": "f5a1", "label": "Marker", "alias": false},
  {"name": "mask", "canonical": "mask", "unicode": "f6fa", "label": "Mask", "alias": false},
  {"name": "mask-ventilator", "canonical": "mask-ventilator", "unicode": "e524", "label": "Mask Ventilator", "alias": false},
  {"name": "masks-theater", "canonical": "masks-theater", "unicode": "f630", "label": "Masks Theater", "alias": false},
  {"name": "maximize", "canonical": "maximize", "unicode": "f31e", "label": "Maximize", "alias": false},
  {"name": "meat", "canonical": "meat", "unicode": "f814", "label": "Meat", "alias": false},
  {"name": "medal", "canonical": "medal", "unicode": "f5a2", "label": "Medal", "alias": false},
  {"name": "memo", "canonical": "memo", "unicode": "e1d8", "label": "Memo", "alias": false},
  {"name": "memory", "canonical": "memory", "unicode": "f538", "label": "Memory", "alias": false},
  {"name": "message", "canonical": "message", "unicode": "f27a", "label": "Message", "alias": false},
  {"name": "meter", "canonical": "meter", "unicode": "e1e8", "label": "Meter", "alias": false},
  {"name": "microchip", "canonical": "microchip", "unicode": "f2db", "label": "Microchip", "alias": false},
  {"name": "microphone", "canonical": "microphone", "unicode": "f130", "label": "Microphone", "alias": false},
  {"name": "microscope", "canonical": "microscope", "unicode": "f610", "label": "Microscope", "alias": false},
  {"name": "minimize", "canonical": "minimize", "unicode": "f78c", "label": "Minimize", "alias": false},
  {"name": "mobile", "canonical": "mobile", "unicode": "f3ce", "label": "Mobile", "alias": false},
  {"name": "money-bill", "canonical": "money-bill", "unicode": "f0d6", "label": "Money Bill", "alias": false},
  {"name": "money-check", "canonical": "money-check", "unicode": "f53c", "label": "Money Check", "alias": false},
  {"name": "monkey", "canonical": "monkey", "unicode": "f6fb", "label": "Monkey", "alias": false},
  {"name": "moon", "canonical": "moon", "unicode": "f186", "label": "Moon", "alias": false},
  {"name": "moped", "canonical": "moped", "unicode": "e3b9", "label": "Moped", "alias": false},
  {"name": "mortar-pestle", "canonical": "mortar-pestle", "unicode": "f5a7", "label": "Mortar Pestle", "alias": false},
  {"name": "mosquito", "canonical": "mosquito", "unicode": "e52b", "label": "Mosquito", "alias": false},
  {"name": "motorcycle", "canonical": "motorcycle", "unicode": "f21c", "label": "Motorcycle", "alias": false},
  {"name": "mountain", "canonical": "mountain", "unicode": "f6fc", "label": "Mountain", "alias": false},
  {"name": "mouse-field", "canonical": "mouse-field", "unicode": "e5a8", "label": "Mouse Field", "alias": false},
  {"name": "mp3-player", "canonical": "mp3-player", "unicode": "f8ce", "label": "Mp3 Player", "alias": false},
  {"name": "mug", "canonical": "mug", "unicode": "f874", "label": "Mug", "alias": false},
  {"name": "mushroom", "canonical": "mushroom", "unicode": "e425", "label": "Mushroom", "alias": false},
  {"name": "music", "canonical": "music", "unicode": "f001", "label": "Music", "alias": false},
  {"name": "music-note", "canonical": "music-note", "unicode": "f8cf", "label": "Music Note", "alias": false},
  {"name": "mustache", "canonical": "mustache", "unicode": "e5bc", "label": "Mustache", "alias": false},
  {"name": "nfc", "canonical": "nfc", "unicode": "e1f7", "label": "Nfc", "alias": false},
  {"name": "nose", "canonical": "nose", "unicode": "e5bd", "label": "Nose", "alias": false},
  {"name": "note-medical", "canonical": "note-medical", "unicode": "e200", "label": "Note Medical", "alias": false},
  {"name": "notebook", "canonical": "notebook", "unicode": "e201", "label": "Notebook", "alias": false},
  {"name": "object-group", "canonical": "object-group", "unicode": "f247", "label": "Object Group", "alias": false},
  {"name": "oil-well", "canonical": "oil-well", "unicode": "e532", "label": "Oil Well", "alias": false},
  {"name": "ornament", "canonical": "ornament", "unicode": "f7b8", "label": "Ornament", "alias": false},
  {"name": "outlet", "canonical": "outlet", "unicode": "e01c", "label": "Outlet", "alias": false},
  {"name": "oven", "canonical": "oven", "unicode": "e01d", "label": "Oven", "alias": false},
  {"name": "paint-roller", "canonical": "paint-roller", "unicode": "f5aa", "label": "Paint Roller", "alias": false},
  {"name": "paintbrush", "canonical": "paintbrush", "unicode": "f1fc", "label": "Paintbrush", "alias": false},
  {"name": "paintbrush-pencil", "canonical": "paintbrush-pencil", "unicode": "e206", "label": "Paintbrush Pencil", "alias": false},
  {"name": "palette", "canonical": "palette", "unicode": "f53f", "label": "Palette", "alias": false},
  {"name": "pallet", "canonical": "pallet", "unicode": "f482", "label": "Pallet", "alias": false},
  {"name": "pallet-box", "canonical": "pallet-box", "unicode": "e208", "label": "Pallet Box", "alias": false},
  {"name": "pan-food", "canonical": "pan-food", "unicode": "e42b", "label": "Pan Food", "alias": false},
  {"name": "pan-frying", "canonical": "pan-frying", "unicode": "e42c", "label": "Pan Frying", "alias": false},
  {"name": "panties", "canonical": "panties", "unicode": "e6d4", "label": "Panties", "alias": false},
  {"name": "pants", "canonical": "pants", "unicode": "e6d5", "label": "Pants", "alias": false},
  {"name": "paper-plane", "canonical": "paper-plane", "unicode": "f1d8", "label": "Paper Plane", "alias": false},
  {"name": "paperclip", "canonical": "paperclip", "unicode": "f0c6", "label": "Paperclip", "alias": false},
  {"name": "paragraph", "canonical": "paragraph", "unicode": "f1dd", "label": "Paragraph", "alias": false},
  {"name": "party-horn", "canonical": "party-horn", "unicode": "e31b", "label": "Party Horn", "alias": false},
  {"name": "passport", "canonical": "passport", "unicode": "f5ab", "label": "Passport", "alias": false},
  {"name": "paste", "canonical": "paste", "unicode": "f0ea", "label": "Paste", "alias": false},
  {"name": "paw", "canonical": "paw", "unicode": "f1b0", "label": "Paw", "alias": false},
  {"name": "peach", "canonical": "peach", "unicode": "e20b", "label": "Peach", "alias": false},
  {"name": "peanut", "canonical": "peanut", "unicode": "e430", "label": "Peanut", "alias": false},
  {"name": "pear", "canonical": "pear", "unicode": "e20c", "label": "Pear", "alias": false},
  {"name": "pedestal", "canonical": "pedestal", "unicode": "e20d", "label": "Pedestal", "alias": false},
  {"name": "pen", "canonical": "pen", "unicode": "f304", "label": "Pen", "alias": false},
  {"name": "pen-paintbrush", "canonical": "pen-paintbrush", "unicode": "f618", "label": "Pen Paintbrush", "alias": false},
  {"name": "pen-ruler", "canonical": "pen-ruler", "unicode": "f5ae", "label": "Pen Ruler", "alias": false},
  {"name": "pencil", "canonical": "pencil", "unicode": "f303", "label": "Pencil", "alias": false},
  {"name": "people", "canonical": "people", "unicode": "e216", "label": "People", "alias": false},
  {"name": "pepper", "canonical": "pepper", "unicode": "e432", "label": "Pepper", "alias": false},
  {"name": "person", "canonical": "person", "unicode": "f183", "label": "Person", "alias": false},
  {"name": "person-hiking", "canonical": "person-hiking", "unicode": "f6ec", "label": "Person Hiking", "alias": false},
  {"name": "person-meditating", "canonical": "person-meditating", "unicode": "e7e1", "label": "Person Meditating", "alias": false},
  {"name": "person-seat", "canonical": "person-seat", "unicode": "e21e", "label": "Person Seat", "alias": false},
  {"name": "person-walking", "canonical": "person-walking", "unicode": "f554", "label": "Person Walking", "alias": false},
  {"name": "peso-sign", "canonical": "peso-sign", "unicode": "e222", "label": "Peso Sign", "alias": false},
  {"name": "phone", "canonical": "phone", "unicode": "f095", "label": "Phone", "alias": false},
  {"name": "piano", "canonical": "piano", "unicode": "f8d4", "label": "Piano", "alias": false},
  {"name": "pickaxe", "canonical": "pickaxe", "unicode": "e5bf", "label": "Pickaxe", "alias": false},
  {"name": "pickleball", "canonical": "pickleball", "unicode": "e435", "label": "Pickleball", "alias": false},
  {"name": "pie", "canonical": "pie", "unicode": "f705", "label": "Pie", "alias": false},
  {"name": "pig", "canonical": "pig", "unicode": "f706", "label": "Pig", "alias": false},
  {"name": "piggy-bank", "canonical": "piggy-bank", "unicode": "f4d3", "label": "Piggy Bank", "alias": false},
  {"name": "pills", "canonical": "pills", "unicode": "f484", "label": "Pills", "alias": false},
  {"name": "pinball", "canonical": "pinball", "unicode": "e229", "label": "Pinball", "alias": false},
  {"name": "pizza", "canonical": "pizza", "unicode": "f817", "label": "Pizza", "alias": false},
  {"name": "plane", "canonical": "plane", "unicode": "f072", "label": "Plane", "alias": false},
  {"name": "plate-utensils", "canonical": "plate-utensils", "unicode": "e43b", "label": "Plate Utensils", "alias": false},
  {"name": "plate-wheat", "canonical": "plate-wheat", "unicode": "e55a", "label": "Plate Wheat", "alias": false},
  {"name": "play", "canonical": "play", "unicode": "f04b", "label": "Play", "alias": false},
  {"name": "plug", "canonical": "plug", "unicode": "f1e6", "label": "Plug", "alias": false},
  {"name": "podcast", "canonical": "podcast", "unicode": "f2ce", "label": "Podcast", "alias": false},
  {"name": "police-box", "canonical": "police-box", "unicode": "e021", "label": "Police Box", "alias": false},
  {"name": "popcorn", "canonical": "popcorn", "unicode": "f819", "label": "Popcorn", "alias": false},
  {"name": "popsicle", "canonical": "popsicle", "unicode": "e43e", "label": "Popsicle", "alias": false},
  {"name": "pot-food", "canonical": "pot-food", "unicode": "e43f", "label": "Pot Food", "alias": false},
  {"name": "potato", "canonical": "potato", "unicode": "e440", "label": "Potato", "alias": false},
  {"name": "power-off", "canonical": "power-off", "unicode": "f011", "label": "Power Off", "alias": false},
  {"name": "print", "canonical": "print", "unicode": "f02f", "label": "Print", "alias": false},
  {"name": "projector", "canonical": "projector", "unicode": "f8d6", "label": "Projector", "alias": false},
  {"name": "pump", "canonical": "pump", "unicode": "e442", "label": "Pump", "alias": false},
  {"name": "pumpkin", "canonical": "pumpkin", "unicode": "f707", "label": "Pumpkin", "alias": false},
  {"name": "puzzle", "canonical": "puzzle", "unicode": "e443", "label": "Puzzle", "alias": false},
  {"name": "qrcode", "canonical": "qrcode", "unicode": "f029", "label": "Qrcode", "alias": false},
  {"name": "rabbit", "canonical": "rabbit", "unicode": "f708", "label": "Rabbit", "alias": false},
  {"name": "raccoon", "canonical": "raccoon", "unicode": "e613", "label": "Raccoon", "alias": false},
  {"name": "racquet", "canonical": "racquet", "unicode": "f45a", "label": "Racquet", "alias": false},
  {"name": "radiation", "canonical": "radiation", "unicode": "f7b9", "label": "Radiation", "alias": false},
  {"name": "radio", "canonical": "radio", "unicode": "f8d7", "label": "Radio", "alias": false},
  {"name": "ramp-loading", "canonical": "ramp-loading", "unicode": "f4d4", "label": "Ramp Loading", "alias": false},
  {"name": "receipt", "canonical": "receipt", "unicode": "f543", "label": "Receipt", "alias": false},
  {"name": "recycle", "canonical": "recycle", "unicode": "f1b8", "label": "Recycle", "alias": false},
  {"name": "reel", "canonical": "reel", "unicode": "e238", "label": "Reel", "alias": false},
  {"name": "reflect-both", "canonical": "reflect-both", "unicode": "e66f", "label": "Reflect Both", "alias": false},
  {"name": "refrigerator", "canonical": "refrigerator", "unicode": "e026", "label": "Refrigerator", "alias": false},
  {"name": "reply", "canonical": "reply", "unicode": "f3e5", "label": "Reply", "alias": false},
  {"name": "road", "canonical": "road", "unicode": "f018", "label": "Road", "alias": false},
  {"name": "robot", "canonical": "robot", "unicode": "f544", "label": "Robot", "alias": false},
  {"name": "route", "canonical": "route", "unicode": "f4d7", "label": "Route", "alias": false},
  {"name": "router", "canonical": "router", "unicode": "f8da", "label": "Router", "alias": false},
  {"name": "rss", "canonical": "rss", "unicode": "f09e", "label": "RSS", "alias": false},
  {"name": "ruble-sign", "canonical": "ruble-sign", "unicode": "f158", "label": "Ruble Sign", "alias": false},
  {"name": "rug", "canonical": "rug", "unicode": "e569", "label": "Rug", "alias": false},
  {"name": "ruler", "canonical": "ruler", "unicode": "f545", "label": "Ruler", "alias": false},
  {"name": "rupee-sign", "canonical": "rupee-sign", "unicode": "f156", "label": "Rupee Sign", "alias": false},
  {"name": "rupiah-sign", "canonical": "rupiah-sign", "unicode": "e23d", "label": "Rupiah Sign", "alias": false},
  {"name": "rv", "canonical": "rv", "unicode": "f7be", "label": "Rv", "alias": false},
  {"name": "sack", "canonical": "sack", "unicode": "f81c", "label": "Sack", "alias": false},
  {"name": "sack-dollar", "canonical": "sack-dollar", "unicode": "f81d", "label": "Sack Dollar", "alias": false},
  {"name": "sailboat", "canonical": "sailboat", "unicode": "e445", "label": "Sailboat", "alias": false},
  {"name": "salad", "canonical": "salad", "unicode": "f81e", "label": "Salad", "alias": false},
  {"name": "sandwich", "canonical": "sandwich", "unicode": "f81f", "label": "Sandwich", "alias": false},
  {"name": "satellite", "canonical": "satellite", "unicode": "f7bf", "label": "Satellite", "alias": false},
  {"name": "satellite-dish", "canonical": "satellite-dish", "unicode": "f7c0", "label": "Satellite Dish", "alias": false},
  {"name": "sausage", "canonical": "sausage", "unicode": "f820", "label": "Sausage", "alias": false},
  {"name": "saxophone", "canonical": "saxophone", "unicode": "f8dc", "label": "Saxophone", "alias": false},
  {"name": "scanner-image", "canonical": "scanner-image", "unicode": "f8f3", "label": "Scanner Image", "alias": false},
  {"name": "scarf", "canonical": "scarf", "unicode": "f7c1", "label": "Scarf", "alias": false},
  {"name": "school", "canonical": "school", "unicode": "f549", "label": "School", "alias": false},
  {"name": "scissors", "canonical": "scissors", "unicode": "f0c4", "label": "Scissors", "alias": false},
  {"name": "scooter", "canonical": "scooter", "unicode": "e7c3", "label": "Scooter", "alias": false},
  {"name": "screencast", "canonical": "screencast", "unicode": "e23e", "label": "Screencast", "alias": false},
  {"name": "screwdriver", "canonical": "screwdriver", "unicode": "f54a", "label": "Screwdriver", "alias": false},
  {"name": "screwdriver-wrench", "canonical": "screwdriver-wrench", "unicode": "f7d9", "label": "Screwdriver Wrench", "alias": false},
  {"name": "scroll", "canonical": "scroll", "unicode": "f70e", "label": "Scroll", "alias": false},
  {"name": "scrubber", "canonical": "scrubber", "unicode": "f2f8", "label": "Scrubber", "alias": false},
  {"name": "sd-card", "canonical": "sd-card", "unicode": "f7c2", "label": "Sd Card", "alias": false},
  {"name": "seat", "canonical": "seat", "unicode": "e764", "label": "Seat", "alias": false},
  {"name": "seedling", "canonical": "seedling", "unicode": "f4d8", "label": "Seedling", "alias": false},
  {"name": "sensor", "canonical": "sensor", "unicode": "e028", "label": "Sensor", "alias": false},
  {"name": "server", "canonical": "server", "unicode": "f233", "label": "Server", "alias": false},
  {"name": "shapes", "canonical": "shapes", "unicode": "f61f", "label": "Shapes", "alias": false},
  {"name": "share-all", "canonical": "share-all", "unicode": "f367", "label": "Share All", "alias": false},
  {"name": "share-nodes", "canonical": "share-nodes", "unicode": "f1e0", "label": "Share Nodes", "alias": false},
  {"name": "sheep", "canonical": "sheep", "unicode": "f711", "label": "Sheep", "alias": false},
  {"name": "sheet-plastic", "canonical": "sheet-plastic", "unicode": "e571", "label": "Sheet Plastic", "alias": false},
  {"name": "shelves", "canonical": "shelves", "unicode": "f480", "label": "Shelves", "alias": false},
  {"name": "shield-cat", "canonical": "shield-cat", "unicode": "e572", "label": "Shield Cat", "alias": false},
  {"name": "shield-dog", "canonical": "shield-dog", "unicode": "e573", "label": "Shield Dog", "alias": false},
  {"name": "ship", "canonical": "ship", "unicode": "f21a", "label": "Ship", "alias": false},
  {"name": "shirt", "canonical": "shirt", "unicode": "f553", "label": "Shirt", "alias": false},
  {"name": "shirt-running", "canonical": "shirt-running", "unicode": "e3c8", "label": "Shirt Running", "alias": false},
  {"name": "shish-kebab", "canonical": "shish-kebab", "unicode": "f821", "label": "Shish Kebab", "alias": false},
  {"name": "shoe", "canonical": "shoe", "unicode": "e6d8", "label": "Shoe", "alias": false},
  {"name": "shop", "canonical": "shop", "unicode": "f54f", "label": "Shop", "alias": false},
  {"name": "shorts", "canonical": "shorts", "unicode": "e6d9", "label": "Shorts", "alias": false},
  {"name": "shovel", "canonical": "shovel", "unicode": "f713", "label": "Shovel", "alias": false},
  {"name": "shower", "canonical": "shower", "unicode": "f2cc", "label": "Shower", "alias": false},
  {"name": "shrimp", "canonical": "shrimp", "unicode": "e448", "label": "Shrimp", "alias": false},
  {"name": "shuffle", "canonical": "shuffle", "unicode": "f074", "label": "Shuffle", "alias": false},
  {"name": "shuttle-space", "canonical": "shuttle-space", "unicode": "f197", "label": "Shuttle Space", "alias": false},
  {"name": "shuttlecock", "canonical": "shuttlecock", "unicode": "f45b", "label": "Shuttlecock", "alias": false},
  {"name": "sickle", "canonical": "sickle", "unicode": "f822", "label": "Sickle", "alias": false},
  {"name": "signal", "canonical": "signal", "unicode": "f012", "label": "Signal", "alias": false},
  {"name": "signature", "canonical": "signature", "unicode": "f5b7", "label": "Signature", "alias": false},
  {"name": "sim-card", "canonical": "sim-card", "unicode": "f7c4", "label": "Sim Card", "alias": false},
  {"name": "sink", "canonical": "sink", "unicode": "e06d", "label": "Sink", "alias": false},
  {"name": "siren", "canonical": "siren", "unicode": "e02d", "label": "Siren", "alias": false},
  {"name": "skull-cow", "canonical": "skull-cow", "unicode": "f8de", "label": "Skull Cow", "alias": false},
  {"name": "sleigh", "canonical": "sleigh", "unicode": "f7cc", "label": "Sleigh", "alias": false},
  {"name": "slider", "canonical": "slider", "unicode": "e252", "label": "Slider", "alias": false},
  {"name": "sliders", "canonical": "sliders", "unicode": "f1de", "label": "Sliders", "alias": false},
  {"name": "slot-machine", "canonical": "slot-machine", "unicode": "e3ce", "label": "Slot Machine", "alias": false},
  {"name": "smoking", "canonical": "smoking", "unicode": "f48d", "label": "Smoking", "alias": false},
  {"name": "snake", "canonical": "snake", "unicode": "f716", "label": "Snake", "alias": false},
  {"name": "sneaker", "canonical": "sneaker", "unicode": "e6da", "label": "Sneaker", "alias": false},
  {"name": "snooze", "canonical": "snooze", "unicode": "f880", "label": "Snooze", "alias": false},
  {"name": "snow-blowing", "canonical": "snow-blowing", "unicode": "f761", "label": "Snow Blowing", "alias": false},
  {"name": "snowman", "canonical": "snowman", "unicode": "f7d0", "label": "Snowman", "alias": false},
  {"name": "soap", "canonical": "soap", "unicode": "e06e", "label": "Soap", "alias": false},
  {"name": "socks", "canonical": "socks", "unicode": "f696", "label": "Socks", "alias": false},
  {"name": "spa", "canonical": "spa", "unicode": "f5bb", "label": "Spa", "alias": false},
  {"name": "sparkles", "canonical": "sparkles", "unicode": "f890", "label": "Sparkles", "alias": false},
  {"name": "speaker", "canonical": "speaker", "unicode": "f8df", "label": "Speaker", "alias": false},
  {"name": "spider", "canonical": "spider", "unicode": "f717", "label": "Spider", "alias": false},
  {"name": "spinner", "canonical": "spinner", "unicode": "f110", "label": "Spinner", "alias": false},
  {"name": "spoon", "canonical": "spoon", "unicode": "f2e5", "label": "Spoon", "alias": false},
  {"name": "sportsball", "canonical": "sportsball", "unicode": "e44b", "label": "Sportsball", "alias": false},
  {"name": "spray-can", "canonical": "spray-can", "unicode": "f5bd", "label": "Spray Can", "alias": false},
  {"name": "sprinkler-ceiling", "canonical": "sprinkler-ceiling", "unicode": "e44c", "label": "Sprinkler Ceiling", "alias": false},
  {"name": "squirrel", "canonical": "squirrel", "unicode": "f71a", "label": "Squirrel", "alias": false},
  {"name": "stairs", "canonical": "stairs", "unicode": "e289", "label": "Stairs", "alias": false},
  {"name": "stamp", "canonical": "stamp", "unicode": "f5bf", "label": "Stamp", "alias": false},
  {"name": "stapler", "canonical": "stapler", "unicode": "e5af", "label": "Stapler", "alias": false},
  {"name": "star-christmas", "canonical": "star-christmas", "unicode": "f7d4", "label": "Star Christmas", "alias": false},
  {"name": "starship", "canonical": "starship", "unicode": "e039", "label": "Starship", "alias": false},
  {"name": "steak", "canonical": "steak", "unicode": "f824", "label": "Steak", "alias": false},
  {"name": "steering-wheel", "canonical": "steering-wheel", "unicode": "f622", "label": "Steering Wheel", "alias": false},
  {"name": "sterling-sign", "canonical": "sterling-sign", "unicode": "f154", "label": "Sterling Sign", "alias": false},
  {"name": "stethoscope", "canonical": "stethoscope", "unicode": "f0f1", "label": "Stethoscope", "alias": false},
  {"name": "stocking", "canonical": "stocking", "unicode": "f7d5", "label": "Stocking", "alias": false},
  {"name": "stomach", "canonical": "stomach", "unicode": "f623", "label": "Stomach", "alias": false},
  {"name": "stopwatch", "canonical": "stopwatch", "unicode": "f2f2", "label": "Stopwatch", "alias": false},
  {"name": "store", "canonical": "store", "unicode": "f54e", "label": "Store", "alias": false},
  {"name": "strawberry", "canonical": "strawberry", "unicode": "e32b", "label": "Strawberry", "alias": false},
  {"name": "street-view", "canonical": "street-view", "unicode": "f21d", "label": "Street View", "alias": false},
  {"name": "stretcher", "canonical": "stretcher", "unicode": "f825", "label": "Stretcher", "alias": false},
  {"name": "stroopwafel", "canonical": "stroopwafel", "unicode": "f551", "label": "Stroopwafel", "alias": false},
  {"name": "subtitles", "canonical": "subtitles", "unicode": "e60f", "label": "Subtitles", "alias": false},
  {"name": "suitcase", "canonical": "suitcase", "unicode": "f0f2", "label": "Suitcase", "alias": false},
  {"name": "sun", "canonical": "sun", "unicode": "f185", "label": "Sun", "alias": false},
  {"name": "sun-cloud", "canonical": "sun-cloud", "unicode": "f763", "label": "Sun Cloud", "alias": false},
  {"name": "sunglasses", "canonical": "sunglasses", "unicode": "f892", "label": "Sunglasses", "alias": false},
  {"name": "sunrise", "canonical": "sunrise", "unicode": "f766", "label": "Sunrise", "alias": false},
  {"name": "sunset", "canonical": "sunset", "unicode": "f767", "label": "Sunset", "alias": false},
  {"name": "sushi", "canonical": "sushi", "unicode": "e48a", "label": "Sushi", "alias": false},
  {"name": "sushi-roll", "canonical": "sushi-roll", "unicode": "e48b", "label": "Sushi Roll", "alias": false},
  {"name": "swap", "canonical": "swap", "unicode": "e609", "label": "Swap", "alias": false},
  {"name": "swatchbook", "canonical": "swatchbook", "unicode": "f5c3", "label": "Swatchbook", "alias": false},
  {"name": "sword", "canonical": "sword", "unicode": "f71c", "label": "Sword", "alias": false},
  {"name": "syringe", "canonical": "syringe", "unicode": "f48e", "label": "Syringe", "alias": false},
  {"name": "table-columns", "canonical": "table-columns", "unicode": "f0db", "label": "Table Columns", "alias": false},
  {"name": "table-rows", "canonical": "table-rows", "unicode": "e292", "label": "Table Rows", "alias": false},
  {"name": "tablet", "canonical": "tablet", "unicode": "f3fb", "label": "Tablet", "alias": false},
  {"name": "tablets", "canonical": "tablets", "unicode": "f490", "label": "Tablets", "alias": false},
  {"name": "taco", "canonical": "taco", "unicode": "f826", "label": "Taco", "alias": false},
  {"name": "tag", "canonical": "tag", "unicode": "f02b", "label": "Tag", "alias": false},
  {"name": "tank-water", "canonical": "tank-water", "unicode": "e452", "label": "Tank Water", "alias": false},
  {"name": "tape", "canonical": "tape", "unicode": "f4db", "label": "Tape", "alias": false},
  {"name": "taxi", "canonical": "taxi", "unicode": "f1ba", "label": "Taxi", "alias": false},
  {"name": "teddy-bear", "canonical": "teddy-bear", "unicode": "e3cf", "label": "Teddy Bear", "alias": false},
  {"name": "teeth", "canonical": "teeth", "unicode": "f62e", "label": "Teeth", "alias": false},
  {"name": "telescope", "canonical": "telescope", "unicode": "e03e", "label": "Telescope", "alias": false},
  {"name": "tennis-ball", "canonical": "tennis-ball", "unicode": "f45e", "label": "Tennis Ball", "alias": false},
  {"name": "tent", "canonical": "tent", "unicode": "e57d", "label": "Tent", "alias": false},
  {"name": "terminal", "canonical": "terminal", "unicode": "f120", "label": "Terminal", "alias": false},
  {"name": "thermometer", "canonical": "thermometer", "unicode": "f491", "label": "Thermometer", "alias": false},
  {"name": "thought-bubble", "canonical": "thought-bubble", "unicode": "e32e", "label": "Thought Bubble", "alias": false},
  {"name": "thumbtack", "canonical": "thumbtack", "unicode": "f08d", "label": "Thumbtack", "alias": false},
  {"name": "ticket", "canonical": "ticket", "unicode": "f145", "label": "Ticket", "alias": false},
  {"name": "ticket-airline", "canonical": "ticket-airline", "unicode": "e29a", "label": "Ticket Airline", "alias": false},
  {"name": "timeline", "canonical": "timeline", "unicode": "e29c", "label": "Timeline", "alias": false},
  {"name": "timer", "canonical": "timer", "unicode": "e29e", "label": "Timer", "alias": false},
  {"name": "tire", "canonical": "tire", "unicode": "f631", "label": "Tire", "alias": false},
  {"name": "tire-rugged", "canonical": "tire-rugged", "unicode": "f634", "label": "Tire Rugged", "alias": false},
  {"name": "toggle-off", "canonical": "toggle-off", "unicode": "f204", "label": "Toggle Off", "alias": false},
  {"name": "toggle-on", "canonical": "toggle-on", "unicode": "f205", "label": "Toggle On", "alias": false},
  {"name": "toilet", "canonical": "toilet", "unicode": "f7d8", "label": "Toilet", "alias": false},
  {"name": "toilet-paper", "canonical": "toilet-paper", "unicode": "f71e", "label": "Toilet Paper", "alias": false},
  {"name": "toilet-portable", "canonical": "toilet-portable", "unicode": "e583", "label": "Toilet Portable", "alias": false},
  {"name": "tomato", "canonical": "tomato", "unicode": "e330", "label": "Tomato", "alias": false},
  {"name": "toolbox", "canonical": "toolbox", "unicode": "f552", "label": "Toolbox", "alias": false},
  {"name": "tooth", "canonical": "tooth", "unicode": "f5c9", "label": "Tooth", "alias": false},
  {"name": "toothbrush", "canonical": "toothbrush", "unicode": "f635", "label": "Toothbrush", "alias": false},
  {"name": "tornado", "canonical": "tornado", "unicode": "f76f", "label": "Tornado", "alias": false},
  {"name": "tower-broadcast", "canonical": "tower-broadcast", "unicode": "f519", "label": "Tower Broadcast", "alias": false},
  {"name": "tower-cell", "canonical": "tower-cell", "unicode": "e585", "label": "Tower Cell", "alias": false},
  {"name": "tractor", "canonical": "tractor", "unicode": "f722", "label": "Tractor", "alias": false},
  {"name": "trademark", "canonical": "trademark", "unicode": "f25c", "label": "Trademark", "alias": false},
  {"name": "traffic-cone", "canonical": "traffic-cone", "unicode": "f636", "label": "Traffic Cone", "alias": false},
  {"name": "traffic-light", "canonical": "traffic-light", "unicode": "f637", "label": "Traffic Light", "alias": false},
  {"name": "trailer", "canonical": "trailer", "unicode": "e041", "label": "Trailer", "alias": false},
  {"name": "train", "canonical": "train", "unicode": "f238", "label": "Train", "alias": false},
  {"name": "train-subway", "canonical": "train-subway", "unicode": "f239", "label": "Train Subway", "alias": false},
  {"name": "train-track", "canonical": "train-track", "unicode": "e453", "label": "Train Track", "alias": false},
  {"name": "transmission", "canonical": "transmission", "unicode": "e802", "label": "Transmission", "alias": false},
  {"name": "transporter", "canonical": "transporter", "unicode": "e042", "label": "Transporter", "alias": false},
  {"name": "trash", "canonical": "trash", "unicode": "f1f8", "label": "Trash", "alias": false},
  {"name": "trash-can", "canonical": "trash-can", "unicode": "f2ed", "label": "Trash Can", "alias": false},
  {"name": "treasure-chest", "canonical": "treasure-chest", "unicode": "f723", "label": "Treasure Chest", "alias": false},
  {"name": "tree", "canonical": "tree", "unicode": "f1bb", "label": "Tree", "alias": false},
  {"name": "tree-city", "canonical": "tree-city", "unicode": "e587", "label": "Tree City", "alias": false},
  {"name": "tricycle-adult", "canonical": "tricycle-adult", "unicode": "e5c4", "label": "Tricycle Adult", "alias": false},
  {"name": "trombone", "canonical": "trombone", "unicode": "e782", "label": "Trombone", "alias": false},
  {"name": "trophy", "canonical": "trophy", "unicode": "f091", "label": "Trophy", "alias": false},
  {"name": "truck", "canonical": "truck", "unicode": "f0d1", "label": "Truck", "alias": false},
  {"name": "truck-moving", "canonical": "truck-moving", "unicode": "f4df", "label": "Truck Moving", "alias": false},
  {"name": "truck-pickup", "canonical": "truck-pickup", "unicode": "f63c", "label": "Truck Pickup", "alias": false},
  {"name": "truck-ramp", "canonical": "truck-ramp", "unicode": "f4e0", "label": "Truck Ramp", "alias": false},
  {"name": "trumpet", "canonical": "trumpet", "unicode": "f8e3", "label": "Trumpet", "alias": false},
  {"name": "turkey", "canonical": "turkey", "unicode": "f725", "label": "Turkey", "alias": false},
  {"name": "turntable", "canonical": "turntable", "unicode": "f8e4", "label": "Turntable", "alias": false},
  {"name": "turtle", "canonical": "turtle", "unicode": "f726", "label": "Turtle", "alias": false},
  {"name": "tv", "canonical": "tv", "unicode": "f26c", "label": "Tv", "alias": false},
  {"name": "umbrella", "canonical": "umbrella", "unicode": "f0e9", "label": "Umbrella", "alias": false},
  {"name": "unlock", "canonical": "unlock", "unicode": "f09c", "label": "Unlock", "alias": false},
  {"name": "usb-drive", "canonical": "usb-drive", "unicode": "f8e9", "label": "Usb Drive", "alias": false},
  {"name": "user", "canonical": "user", "unicode": "f007", "label": "User", "alias": false},
  {"name": "user-doctor", "canonical": "user-doctor", "unicode": "f0f0", "label": "User Doctor", "alias": false},
  {"name": "user-large", "canonical": "user", "unicode": "f007", "label": "User", "alias": true},
  {"name": "user-police", "canonical": "user-police", "unicode": "e333", "label": "User Police", "alias": false},
  {"name": "users", "canonical": "users", "unicode": "f0c0", "label": "Users", "alias": false},
  {"name": "utensils", "canonical": "utensils", "unicode": "f2e7", "label": "Utensils", "alias": false},
  {"name": "utility-pole", "canonical": "utility-pole", "unicode": "e2c3", "label": "Utility Pole", "alias": false},
  {"name": "vacuum", "canonical": "vacuum", "unicode": "e04d", "label": "Vacuum", "alias": false},
  {"name": "vacuum-robot", "canonical": "vacuum-robot", "unicode": "e04e", "label": "Vacuum Robot", "alias": false},
  {"name": "value-absolute", "canonical": "value-absolute", "unicode": "f6a6", "label": "Value Absolute", "alias": false},
  {"name": "van", "canonical": "van", "unicode": "e7c8", "label": "Van", "alias": false},
  {"name": "van-shuttle", "canonical": "van-shuttle", "unicode": "f5b6", "label": "Van Shuttle", "alias": false},
  {"name": "vault", "canonical": "vault", "unicode": "e2c5", "label": "Vault", "alias": false},
  {"name": "vest-patches", "canonical": "vest-patches", "unicode": "e086", "label": "Vest Patches", "alias": false},
  {"name": "vial", "canonical": "vial", "unicode": "f492", "label": "Vial", "alias": false},
  {"name": "vials", "canonical": "vials", "unicode": "f493", "label": "Vials", "alias": false},
  {"name": "video", "canonical": "video", "unicode": "f03d", "label": "Video", "alias": false},
  {"name": "violin", "canonical": "violin", "unicode": "f8ed", "label": "Violin", "alias": false},
  {"name": "virus", "canonical": "virus", "unicode": "e074", "label": "Virus", "alias": false},
  {"name": "volleyball", "canonical": "volleyball", "unicode": "f45f", "label": "Volleyball", "alias": false},
  {"name": "volume", "canonical": "volume", "unicode": "f6a8", "label": "Volume", "alias": false},
  {"name": "walker", "canonical": "walker", "unicode": "f831", "label": "Walker", "alias": false},
  {"name": "walkie-talkie", "canonical": "walkie-talkie", "unicode": "f8ef", "label": "Walkie Talkie", "alias": false},
  {"name": "wallet", "canonical": "wallet", "unicode": "f555", "label": "Wallet", "alias": false},
  {"name": "wand", "canonical": "wand", "unicode": "f72a", "label": "Wand", "alias": false},
  {"name": "wand-magic", "canonical": "wand-magic", "unicode": "f0d0", "label": "Wand Magic", "alias": false},
  {"name": "warehouse", "canonical": "warehouse", "unicode": "f494", "label": "Warehouse", "alias": false},
  {"name": "warehouse-full", "canonical": "warehouse-full", "unicode": "f495", "label": "Warehouse Full", "alias": false},
  {"name": "washing-machine", "canonical": "washing-machine", "unicode": "f898", "label": "Washing Machine", "alias": false},
  {"name": "watch", "canonical": "watch", "unicode": "f2e1", "label": "Watch", "alias": false},
  {"name": "watch-apple", "canonical": "watch-apple", "unicode": "e2cb", "label": "Watch Apple", "alias": false},
  {"name": "watch-fitness", "canonical": "watch-fitness", "unicode": "f63e", "label": "Watch Fitness", "alias": false},
  {"name": "watch-smart", "canonical": "watch-smart", "unicode": "e2cc", "label": "Watch Smart", "alias": false},
  {"name": "water", "canonical": "water", "unicode": "f773", "label": "Water", "alias": false},
  {"name": "wave", "canonical": "wave", "unicode": "e65b", "label": "Wave", "alias": false},
  {"name": "webhook", "canonical": "webhook", "unicode": "e5d5", "label": "Webhook", "alias": false},
  {"name": "weight-scale", "canonical": "weight-scale", "unicode": "f496", "label": "Weight Scale", "alias": false},
  {"name": "wheelchair", "canonical": "wheelchair", "unicode": "f193", "label": "Wheelchair", "alias": false},
  {"name": "wifi", "canonical": "wifi", "unicode": "f1eb", "label": "Wifi", "alias": false},
  {"name": "wind", "canonical": "wind", "unicode": "f72e", "label": "Wind", "alias": false},
  {"name": "window", "canonical": "window", "unicode": "f40e", "label": "Window", "alias": false},
  {"name": "wine-glass", "canonical": "wine-glass", "unicode": "f4e3", "label": "Wine Glass", "alias": false},
  {"name": "wireless", "canonical": "wireless", "unicode": "e7df", "label": "Wireless", "alias": false},
  {"name": "won-sign", "canonical": "won-sign", "unicode": "f159", "label": "Won Sign", "alias": false},
  {"name": "wreath", "canonical": "wreath", "unicode": "f7e2", "label": "Wreath", "alias": false},
  {"name": "wrench", "canonical": "wrench", "unicode": "f0ad", "label": "Wrench", "alias": false},
  {"name": "x-ray", "canonical": "x-ray", "unicode": "f497", "label": "X Ray", "alias": false}
];
