#!/usr/bin/env python3
"""Task-003 part 3: mosque, mountain"""
from gen_icons_task_003_lib import build_icon

# ── mosque ───────────────────────────────────────────────────────────────────
build_icon("mosque",
    keep_en=[
        "islam",
        "landmark",
        "mosque",
        "muslim",
        "mosque crowded during Friday prayer",
        "muslim community gathering at the mosque",
        "local mosque serving the community",
        "mosque with a large doem and minarets",
        "islmaic mosque silouhette at sunset",
        "mosqe icon for the prayer time app",
        "musim community gathering at the mosuqe",
    ],
    new_en=[
        "building",
        "religion",
        "prayer",
        "minaret",
        "dome",
        "Ramadan",
        "Eid",
        "Quran",
        "imam",
        "halal",
        "visit the mosque for Friday prayer",
        "check prayer times at the local mosque",
        "schedule Ramadan iftar at the mosque",
        "attend the Eid celebration at the mosque",
        "donate to the mosque building fund",
        "sign up for Quran study at the mosque",
        "drop off charity at the mosque before Eid",
        "find the nearest mosque for travel prayer",
        "register the kids for mosque summer camp",
        "volunteer for the mosque food drive",
        "plan a visit to the historic mosque downtown",
        "set a reminder for the evening prayer",
        "book the mosque hall for the wedding",
        "pick up iftar meals from the mosque",
        "attend the Friday sermon at the mosque",
        "arrange a mosque tour for the school group",
        "check the mosque calendar for events",
        "confirm the imam's availability for counseling",
        "buy prayer rugs for the mosque donation",
        "join the mosque youth group meeting",
        "RSVP for the mosque open house event",
        "call the mosque about parking for Eid",
        "prepare food for the mosque community dinner",
        "bring shoes bag to the mosque",
        "check mosque renovation schedule",
        "set alarm for fajr prayr",
        "ramdan schedule at the mosque",
        "mosqe community dinner this Friday",
        "eid celebraton at the mosque",
        "mosquee youth group meeting",
        "sign up for Quran class at the mosquee",
        "find halal restaurant near the mosque",
        "mosque open day this weekend",
        "clean the mosque before Friday",
        "arrange carpools to the mosque for Eid",
        "collect zakat donations at the mosque",
        "invite neighbors to mosque open house",
        "help set up Eid decorations at the mosque",
        "bring dates to the mosque for iftar",
    ],
    keep_ru=[
        "ислам",
        "достопримечательность",
        "мечеть",
        "мусульманин",
        "религия",
        "мечеть полна во время пятничной молитвы",
        "мусульманская община собирается в мечети",
        "местная мечеть служит общине",
        "пятничная молитва в мечети",
        "мечеть с большим куполом и минаретами",
    ],
    new_ru=[
        "здание",
        "молитва",
        "минарет",
        "купол",
        "Рамадан",
        "Ураза-байрам",
        "Коран",
        "имам",
        "халяль",
        "намаз",
        "пойти в мечеть на пятничную молитву",
        "проверить время намаза в местной мечети",
        "запланировать ифтар в Рамадан в мечети",
        "пойти на праздник Ураза-байрам в мечети",
        "пожертвовать на строительство мечети",
        "записаться на изучение Корана в мечети",
        "отвезти милостыню в мечеть перед Ураза-байрам",
        "найти ближайшую мечеть для молитвы в дороге",
        "записать детей в летний лагерь при мечети",
        "стать волонтёром на раздаче еды в мечети",
        "запланировать посещение исторической мечети",
        "поставить напоминание на вечернюю молитву",
        "забронировать зал мечети для свадьбы",
        "забрать еду для ифтара из мечети",
        "пойти на пятничную проповедь в мечеть",
        "организовать экскурсию в мечеть для школьников",
        "проверить календарь мероприятий мечети",
        "уточнить доступность имама для консультации",
        "купить молитвенные коврики для пожертвования мечети",
        "присоединиться к молодёжной группе мечети",
        "записаться на день открытых дверей в мечети",
        "позвонить в мечеть насчёт парковки на байрам",
        "приготовить еду для общинного ужина в мечети",
        "взять пакет для обуви в мечеть",
        "узнать расписание ремонта мечети",
        "будильник на утренний намаз",
        "расписание рамадна в мечети",
        "общинный ужин в мечти в пятницу",
        "празднование байрма в мечети",
        "молодёжная группа мечти",
        "записаться на урок Корана в мечти",
        "найти халяльный ресторан рядом с мечетью",
        "день открытых дверей мечети в выходные",
        "убрать мечеть перед пятницей",
        "организовать подвоз в мечеть на байрам",
        "собрать закят в мечети",
        "пригласить соседей на день мечети",
        "помочь украсить мечеть к байраму",
        "принести финики в мечеть для ифтара",
    ],
    de=[
        "Moschee",
        "Islam",
        "Muslim",
        "Gebet",
        "Minarett",
        "Kuppel",
        "Ramadan",
        "Eid",
        "Koran",
        "Imam",
        "Gebetszeit",
        "Religion",
        "Wahrzeichen",
        "Gebäude",
        "Gemeinde",
        "halal",
        "Freitagsgebet",
        "Fastenbrechen",
        "Freitagsgebet in der Moschee besuchen",
        "Gebetszeiten in der Moschee prüfen",
        "Iftar im Ramadan in der Moschee planen",
        "Eid-Feier in der Moschee besuchen",
        "an den Moscheebaufonds spenden",
        "zum Koranunterricht in der Moschee anmelden",
        "Spenden vor Eid in der Moschee abgeben",
        "nächste Moschee für das Reisegebet finden",
        "Kinder für das Moschee-Sommercamp anmelden",
        "bei der Essensausgabe in der Moschee helfen",
        "Besuch der historischen Moschee planen",
        "Erinnerung für das Abendgebet setzen",
        "Moscheesaal für die Hochzeit buchen",
        "Iftar-Essen von der Moschee abholen",
        "Freitagspredigt in der Moschee besuchen",
        "Moscheetour für die Schulgruppe organisieren",
        "Moscheekalender auf Veranstaltungen prüfen",
        "Verfügbarkeit des Imams für Beratung anfragen",
        "Gebetsteppiche für die Moschee kaufen",
        "Jugendgruppe der Moschee beitreten",
        "zum Tag der offenen Moschee anmelden",
        "Moschee wegen Eid-Parkplätzen anrufen",
        "Essen für das Gemeindedinner vorbereiten",
        "Schuhbeutel zur Moschee mitnehmen",
        "Renovierungsplan der Moschee erfragen",
        "Wecker für das Morgengebet stellen",
        "Halal-Restaurant in der Nähe der Moschee finden",
        "Tag der offenen Moschee am Wochenende",
        "Moschee vor Freitag putzen",
        "Fahrgemeinschaft zur Moschee an Eid organisieren",
        "Zakat in der Moschee sammeln",
        "Nachbarn zum offenen Moscheeta einladen",
        "Moschee für Eid dekorieren helfen",
        "Datteln zur Moschee fürs Fastenbrechen bringen",
        "Ramadanplan der Moschee prüfen",
        "Mosche Gemeindedinner am Freitag",
        "Eid Feir in der Moschee",
        "Moschee Jugendgruppe Trefen",
        "Korankurrs in der Moschee",
        "Gebtszeiten prüfen",
    ],
    ja=[
        "モスク",
        "イスラム",
        "ムスリム",
        "礼拝",
        "ミナレット",
        "ドーム",
        "ラマダン",
        "イード",
        "コーラン",
        "イマーム",
        "礼拝時間",
        "宗教",
        "ランドマーク",
        "建物",
        "コミュニティ",
        "ハラール",
        "金曜礼拝",
        "断食明け",
        "金曜礼拝にモスクに行く",
        "地元のモスクで礼拝時間を確認する",
        "ラマダンのイフタールをモスクで計画する",
        "モスクでイードのお祝いに参加する",
        "モスクの建設基金に寄付する",
        "モスクでコーランの勉強に申し込む",
        "イード前にモスクに寄付を届ける",
        "旅行中の礼拝に最寄りのモスクを探す",
        "子供をモスクのサマーキャンプに登録する",
        "モスクの食事配布でボランティアする",
        "歴史的なモスクの訪問を計画する",
        "夕方の礼拝のリマインダーを設定する",
        "結婚式のためにモスクのホールを予約する",
        "モスクからイフタールの食事を受け取る",
        "モスクで金曜の説教に参加する",
        "学校グループのモスク見学を手配する",
        "モスクのカレンダーでイベントを確認する",
        "イマームの相談可能な時間を確認する",
        "モスクへの寄付用に礼拝マットを買う",
        "モスクの青年グループの集まりに参加する",
        "モスクのオープンハウスに参加登録する",
        "イードの駐車場についてモスクに電話する",
        "モスクのコミュニティディナーに料理を準備する",
        "モスクに靴袋を持っていく",
        "モスクの改修スケジュールを確認する",
        "朝の礼拝にアラームをセットする",
        "モスク近くのハラールレストランを探す",
        "今週末モスクのオープンデー",
        "金曜の前にモスクを掃除する",
        "イードのモスクへの相乗りを手配する",
        "モスクでザカートを集める",
        "近所の人をモスクのオープンデーに招待する",
        "モスクのイードの飾り付けを手伝う",
        "イフタール用にデーツをモスクに持っていく",
        "もすく の れいはい",
        "らまだん の よてい",
        "いーど の おいわい",
        "きんよう れいはい に いく",
    ],
    fr=[
        "mosquée",
        "islam",
        "musulman",
        "prière",
        "minaret",
        "dôme",
        "Ramadan",
        "Aïd",
        "Coran",
        "imam",
        "heure de prière",
        "religion",
        "monument",
        "bâtiment",
        "communauté",
        "halal",
        "prière du vendredi",
        "rupture du jeûne",
        "aller à la mosquée pour la prière du vendredi",
        "vérifier les heures de prière à la mosquée locale",
        "planifier l'iftar du Ramadan à la mosquée",
        "assister à la fête de l'Aïd à la mosquée",
        "faire un don au fonds de construction de la mosquée",
        "s'inscrire au cours de Coran à la mosquée",
        "déposer les dons à la mosquée avant l'Aïd",
        "trouver la mosquée la plus proche pour la prière en voyage",
        "inscrire les enfants au camp d'été de la mosquée",
        "aider à la distribution de nourriture à la mosquée",
        "planifier une visite de la mosquée historique",
        "mettre un rappel pour la prière du soir",
        "réserver la salle de la mosquée pour le mariage",
        "récupérer les repas d'iftar à la mosquée",
        "assister au sermon du vendredi à la mosquée",
        "organiser une visite de la mosquée pour l'école",
        "vérifier le calendrier de la mosquée pour les événements",
        "confirmer la disponibilité de l'imam pour le conseil",
        "acheter des tapis de prière pour la mosquée",
        "rejoindre le groupe de jeunes de la mosquée",
        "s'inscrire à la journée portes ouvertes de la mosquée",
        "appeler la mosquée pour le parking de l'Aïd",
        "préparer la nourriture pour le dîner communautaire",
        "apporter un sac à chaussures à la mosquée",
        "se renseigner sur les travaux de la mosquée",
        "mettre le réveil pour la prière du matin",
        "trouver un restaurant halal près de la mosquée",
        "journée portes ouvertes de la mosquée ce weekend",
        "nettoyer la mosquée avant vendredi",
        "organiser le covoiturage vers la mosquée pour l'Aïd",
        "collecter la zakat à la mosquée",
        "inviter les voisins à la journée mosquée",
        "aider à décorer la mosquée pour l'Aïd",
        "apporter des dattes à la mosquée pour l'iftar",
        "plan ramadan de la mosqueé",
        "mosqée dîner communautaire vendredi",
        "fête de l'Aid à la mosquée",
        "mosqué groupe de jeunes",
        "cors de Coran à la mosquée",
    ],
    es=[
        "mezquita",
        "islam",
        "musulmán",
        "oración",
        "minarete",
        "cúpula",
        "Ramadán",
        "Eid",
        "Corán",
        "imán",
        "hora de oración",
        "religión",
        "monumento",
        "edificio",
        "comunidad",
        "halal",
        "oración del viernes",
        "ruptura del ayuno",
        "ir a la mezquita para la oración del viernes",
        "revisar los horarios de oración en la mezquita",
        "planear el iftar de Ramadán en la mezquita",
        "asistir a la celebración de Eid en la mezquita",
        "donar al fondo de construcción de la mezquita",
        "inscribirse en el estudio del Corán en la mezquita",
        "llevar la caridad a la mezquita antes del Eid",
        "encontrar la mezquita más cercana para rezar de viaje",
        "inscribir a los niños en el campamento de la mezquita",
        "ser voluntario en la entrega de comida de la mezquita",
        "planear una visita a la mezquita histórica",
        "poner un recordatorio para la oración de la noche",
        "reservar el salón de la mezquita para la boda",
        "recoger las comidas de iftar de la mezquita",
        "asistir al sermón del viernes en la mezquita",
        "organizar una visita a la mezquita para el grupo escolar",
        "revisar el calendario de la mezquita para eventos",
        "confirmar la disponibilidad del imán para consejería",
        "comprar tapetes de oración para donar a la mezquita",
        "unirse al grupo juvenil de la mezquita",
        "registrarse para el día de puertas abiertas de la mezquita",
        "llamar a la mezquita por el estacionamiento del Eid",
        "preparar comida para la cena comunitaria de la mezquita",
        "llevar bolsa para zapatos a la mezquita",
        "preguntar por el calendario de renovación de la mezquita",
        "poner alarma para la oración de la mañana",
        "encontrar restaurante halal cerca de la mezquita",
        "día de puertas abiertas de la mezquita este fin de semana",
        "limpiar la mezquita antes del viernes",
        "organizar viajes compartidos a la mezquita para Eid",
        "recolectar zakat en la mezquita",
        "invitar a los vecinos al día de la mezquita",
        "ayudar a decorar la mezquita para Eid",
        "llevar dátiles a la mezquita para el iftar",
        "mesquita oración del viernes",
        "horario de ramadán en la mesquita",
        "Eid selebración en la mezquita",
        "mesquita grupo juvenil",
        "cors de Corán en la mezquita",
    ],
)

# ── mountain ─────────────────────────────────────────────────────────────────
build_icon("mountain",
    keep_en=[
        "glacier",
        "hill",
        "landscape",
        "snow-capped mountain",
        "glacier slowly moving down the valley",
        "hiking trail winding up the mountain",
        "hiking boots on a rocky mountain path",
        "rolling hill in the countryside",
        "hill climb route for mountain bikers",
        "mountain range stretching across the horizon",
        "mountain peak covered in white snow",
        "snow covered summit of a tall mountain",
        "fresh snow falling on mountain slopes",
        "snow-capped mountain visible from the valley",
        "iconic snow-capped mountain on a clear day",
        "travel adventure to the mountains this summer",
        "breathtaking view of the mountain summit",
        "hiking trail leading up to a mountain summit",
        "ski resort on a snow-covered mountain slope",
        "rugged rocky mountain rising above the clouds",
        "mountain climbing route for experienced trekkers",
        "misty mountain range at dawn with fog below",
        "mountian peak covered in snow",
        "mountan trail for hiking",
        "moutain range in the distance",
        "mountaim summit with a glacier",
    ],
    new_en=[
        "alpine",
        "climb",
        "hiking",
        "peak",
        "summit",
        "travel",
        "mountain",
        "trek",
        "plan a mountain hike for Saturday",
        "book the alpine cabin for the weekend",
        "check weather at the summit before climbing",
        "pack gear for the mountain trek",
        "buy hiking boots for the mountain trip",
        "drive to the trailhead early morning",
        "register for the mountain marathon",
        "schedule the glacier tour next month",
        "look up elevation gain on the trail map",
        "rent crampons for the glacier hike",
        "photograph the summit at sunrise",
        "reserve camping spot near the peak",
        "train for the mountain climb this spring",
        "download the trail map for the hike",
        "check the avalanche forecast before going",
        "bring extra layers for the alpine cold",
        "pick up trail snacks for the mountain hike",
        "arrange a guide for the summit attempt",
        "charge headlamp for the predawn start",
        "fill water bottles for the long hike",
        "review the mountain route with the group",
        "set an early alarm for the hike",
        "buy trekking poles for the mountain trip",
        "check if the mountain pass is open",
        "plan a scenic drive through the mountains",
    ],
    keep_ru=[
        "ледник",
        "холм",
        "пейзаж",
        "гора",
        "заснеженная гора",
        "ледник медленно сползает в долину",
        "тропа для похода в гору",
        "ботинки на каменистой горной тропе",
        "пологий холм в сельской местности",
        "драматичный горный пейзаж на рассвете",
        "горный хребет тянется до горизонта",
        "вершина горы покрыта белым снегом",
        "снежная вершина высокой горы",
        "свежий снег падает на горные склоны",
        "заснеженная гора видна из долины",
        "знаковая гора со снежной вершиной в ясный день",
        "летнее путешествие в горы",
        "захватывающий вид на горную вершину",
        "тропа ведет к вершине горы",
        "лыжный курорт на снежном горном склоне",
        "суровая каменная гора под облаками",
        "маршрут восхождения для опытных трекеров",
        "туманный горный хребет на рассвете",
        "горная вершина покрыта снегом",
        "горная тропа для похода",
        "горный хребет вдалеке",
        "вершина горы рядом с ледником",
    ],
    new_ru=[
        "альпийский",
        "восхождение",
        "поход",
        "пик",
        "вершина",
        "путешествие",
        "горный",
        "трекинг",
        "запланировать горный поход на субботу",
        "забронировать альпийский домик на выходные",
        "проверить погоду на вершине перед восхождением",
        "собрать снаряжение для горного трекинга",
        "купить ботинки для горного похода",
        "выехать к началу тропы рано утром",
        "зарегистрироваться на горный марафон",
        "запланировать тур к леднику в следующем месяце",
        "узнать набор высоты по карте маршрута",
        "арендовать кошки для похода по леднику",
        "сфотографировать вершину на рассвете",
        "забронировать место для палатки у пика",
        "тренироваться для восхождения этой весной",
        "скачать карту маршрута для похода",
        "проверить лавинный прогноз перед выходом",
        "взять дополнительные слои одежды для холода",
        "купить перекус для горного похода",
        "найти гида для штурма вершины",
        "зарядить налобный фонарь для раннего старта",
        "наполнить бутылки с водой для длинного похода",
        "обсудить горный маршрут с группой",
        "поставить ранний будильник для похода",
        "купить треккинговые палки для горной поездки",
        "проверить открыт ли горный перевал",
        "запланировать живописную поездку через горы",
    ],
    de=[
        "Berg",
        "Gipfel",
        "Wanderung",
        "Alpin",
        "Gletscher",
        "Hügel",
        "Aufstieg",
        "Gipfel",
        "Trekking",
        "Reise",
        "Berggipfel",
        "Schneeberg",
        "Gebirge",
        "Bergsteigen",
        "Bergpass",
        "Wanderweg",
        "Klettern",
        "Bergkette",
        "Bergwanderung für Samstag planen",
        "Almhütte fürs Wochenende buchen",
        "Wetter am Gipfel vor dem Aufstieg prüfen",
        "Ausrüstung für die Bergtour packen",
        "Wanderschuhe für die Bergtour kaufen",
        "früh morgens zum Wanderparkplatz fahren",
        "für den Bergmarathon anmelden",
        "Gletschertour nächsten Monat planen",
        "Höhenmeter auf der Wanderkarte nachschauen",
        "Steigeisen für die Gletscherwanderung mieten",
        "Gipfel bei Sonnenaufgang fotografieren",
        "Zeltplatz in Gipfelnähe reservieren",
        "für den Bergaufstieg im Frühling trainieren",
        "Wanderkarte für die Tour herunterladen",
        "Lawinenvorhersage vor dem Start prüfen",
        "extra Schichten für die Alpenkälte einpacken",
        "Proviant für die Bergwanderung besorgen",
        "Bergführer für den Gipfelversuch organisieren",
        "Stirnlampe für den frühen Start laden",
        "Wasserflaschen für die lange Wanderung füllen",
        "Bergroute mit der Gruppe besprechen",
        "frühen Wecker für die Wanderung stellen",
        "Trekkingstöcke für die Bergtour kaufen",
        "prüfen ob der Bergpass offen ist",
        "Panoramafahrt durch die Berge planen",
        "Schneeketten fürs Auto mitnehmen",
        "Berghütte für die Übernachtung reservieren",
        "Bergrettungsnummer notieren",
        "Bergwanderung für Samstag",
        "Gletshertour nächsten Monat",
        "Wandershcuhe kaufen",
        "Bergmarathon Anmledung",
        "Gipfl bei Sonnenaufgang",
        "Lawinenvohersage prüfen",
    ],
    ja=[
        "山",
        "山頂",
        "ハイキング",
        "アルプス",
        "氷河",
        "丘",
        "登山",
        "ピーク",
        "トレッキング",
        "旅行",
        "山脈",
        "雪山",
        "山岳",
        "岩場",
        "山小屋",
        "登山道",
        "クライミング",
        "山越え",
        "土曜日の登山を計画する",
        "週末にアルプスの山小屋を予約する",
        "登山前に山頂の天気を確認する",
        "山のトレッキング用に装備を準備する",
        "山旅用にハイキングブーツを買う",
        "早朝に登山口まで車で行く",
        "マウンテンマラソンに登録する",
        "来月の氷河ツアーを予約する",
        "トレイルマップで標高差を調べる",
        "氷河ハイキング用にアイゼンをレンタルする",
        "日の出の山頂を撮影する",
        "山頂付近のキャンプ場を予約する",
        "今春の登山に向けてトレーニングする",
        "ハイキング用のトレイルマップをダウンロードする",
        "出発前に雪崩予報を確認する",
        "高山の寒さに備えて重ね着を用意する",
        "山のハイキング用に行動食を買う",
        "山頂アタックのガイドを手配する",
        "早朝出発に備えてヘッドランプを充電する",
        "長いハイキング用に水筒を満たす",
        "グループで登山ルートを確認する",
        "ハイキングのために早いアラームをセットする",
        "山旅用にトレッキングポールを買う",
        "山の峠が開いているか確認する",
        "山を通る絶景ドライブを計画する",
        "山小屋で宿泊の予約をする",
        "登山届を提出する",
        "山の天気予報を毎日チェックする",
        "とざん の じゅんび",
        "やま に のぼる",
        "はいきんぐ の けいかく",
        "さんちょう の てんき",
        "やまごや を よやく",
    ],
    fr=[
        "montagne",
        "sommet",
        "randonnée",
        "alpin",
        "glacier",
        "colline",
        "ascension",
        "pic",
        "trekking",
        "voyage",
        "chaîne de montagnes",
        "montagne enneigée",
        "massif",
        "escalade",
        "col de montagne",
        "sentier",
        "alpinisme",
        "crête",
        "planifier une randonnée en montagne samedi",
        "réserver le chalet alpin pour le weekend",
        "vérifier la météo au sommet avant l'ascension",
        "préparer l'équipement pour le trek en montagne",
        "acheter des chaussures de randonnée pour la montagne",
        "partir tôt le matin vers le départ du sentier",
        "s'inscrire au marathon de montagne",
        "planifier la visite du glacier le mois prochain",
        "vérifier le dénivelé sur la carte du sentier",
        "louer des crampons pour la randonnée glaciaire",
        "photographier le sommet au lever du soleil",
        "réserver un emplacement de camping près du pic",
        "s'entraîner pour l'ascension ce printemps",
        "télécharger la carte du sentier pour la randonnée",
        "vérifier les prévisions d'avalanche avant de partir",
        "emporter des couches supplémentaires pour le froid alpin",
        "acheter des encas pour la randonnée en montagne",
        "organiser un guide pour la tentative de sommet",
        "charger la lampe frontale pour le départ matinal",
        "remplir les bouteilles d'eau pour la longue randonnée",
        "revoir l'itinéraire de montagne avec le groupe",
        "mettre un réveil tôt pour la randonnée",
        "acheter des bâtons de trekking pour la montagne",
        "vérifier si le col de montagne est ouvert",
        "planifier une route panoramique à travers les montagnes",
        "réserver le refuge de montagne pour la nuit",
        "noter le numéro du secours en montagne",
        "vérifier la météo en montagne chaque jour",
        "randonnée en montagne samdi",
        "glacier visite le moi prochain",
        "chaussures de randonnéee acheter",
        "marathon de montange inscription",
        "sommet au levr du soleil",
        "prévisions d'avalanch vérifier",
    ],
    es=[
        "montaña",
        "cumbre",
        "senderismo",
        "alpino",
        "glaciar",
        "colina",
        "ascenso",
        "pico",
        "trekking",
        "viaje",
        "cordillera",
        "montaña nevada",
        "macizo",
        "escalada",
        "paso de montaña",
        "sendero",
        "alpinismo",
        "cresta",
        "planear una caminata de montaña para el sábado",
        "reservar la cabaña alpina para el fin de semana",
        "revisar el clima en la cumbre antes de subir",
        "preparar el equipo para el trek de montaña",
        "comprar botas de senderismo para el viaje a la montaña",
        "salir temprano hacia el inicio del sendero",
        "inscribirse en el maratón de montaña",
        "planear el tour al glaciar el próximo mes",
        "revisar el desnivel en el mapa del sendero",
        "alquilar crampones para la caminata por el glaciar",
        "fotografiar la cumbre al amanecer",
        "reservar un lugar de camping cerca del pico",
        "entrenar para el ascenso de montaña esta primavera",
        "descargar el mapa del sendero para la caminata",
        "revisar el pronóstico de avalanchas antes de salir",
        "llevar capas extras para el frío alpino",
        "comprar bocadillos para la caminata de montaña",
        "contratar un guía para el intento de cumbre",
        "cargar la linterna frontal para la salida temprana",
        "llenar las botellas de agua para la caminata larga",
        "revisar la ruta de montaña con el grupo",
        "poner una alarma temprana para la caminata",
        "comprar bastones de trekking para el viaje a la montaña",
        "revisar si el paso de montaña está abierto",
        "planear un recorrido panorámico por las montañas",
        "reservar el refugio de montaña para la noche",
        "anotar el número de rescate de montaña",
        "revisar el clima de montaña cada día",
        "caminata de montaña el sabádo",
        "glaciar visita el mes procsimo",
        "botas de senderizmo comprar",
        "maratón de montña inscripción",
        "cumbre al amanecr",
        "pronóstico de avalanchs revisar",
    ],
)

print("Part 3 done: mosque, mountain")
