#!/usr/bin/env python3
"""Task-005 part 3: projector, pumpkin"""
from gen_icons_task_005_common import gen

# ── projector ─────────────────────────────────────────────────────────────────
gen("projector",
en=[
    "projector",
    "presentation",
    "slides",
    "movie projector",
    "screen",
    "PowerPoint",
    "Keynote",
    "film projector",
    "conference room projector",
    "home theater projector",
    "slide deck",
    "overhead projector",
    "video projector",
    "portable projector",
    "projector screen",
    "projector bulb",
    "projection",
    "beamer",
    "set up the projector for the meeting",
    "connect the laptop to the projector",
    "replace the projector bulb before the presentation",
    "buy a new projector screen for the office",
    "the projector in the conference room isn't working",
    "set up the home theater projector for movie night",
    "load the slides onto the presentation projector",
    "focus the projector before the keynote starts",
    "bring the portable projector to the client meeting",
    "order a replacement projector cable online",
    "clean the projector lens before the presentation",
    "test the projector connection before the conference",
    "mount the projector on the ceiling in the boardroom",
    "the projector overheated during the long presentation",
    "switch the projector to HDMI input",
    "adjust the projector brightness for the room lighting",
    "return the borrowed projector to the IT department",
    "rent a projector for the outdoor movie night",
    "the projector fan is making a loud noise",
    "update the projector firmware",
    "reserve the conference room with the projector",
    "practice the slides on the projector before the talk",
    "pack the projector for the off-site presentation",
    "the projector remote needs new batteries",
    "check projector availability for the workshop",
    "buy an HDMI adapter for the projector",
    "the projector image is blurry on the screen",
    "set the projector timer to auto-off after an hour",
    "connect the sound system to the projector",
    "the projector screen needs to be pulled down",
    "compare projector models for the new office",
    "need to fix the projector alignment in the meeting room",
    "book the projector for next Tuesday's presentation",
    "proyector for the meeting",
    "presentaiton slides on projector",
    "projcetor bulb replacement",
    "confernce room projector setup",
    "projetor screen blurry",
],
ru=[
    "проектор",
    "презентация",
    "слайды",
    "кинопроектор",
    "экран",
    "PowerPoint",
    "Keynote",
    "кинематографический проектор",
    "проектор для конференц-зала",
    "домашний кинопроектор",
    "набор слайдов",
    "оверхед-проектор",
    "видеопроектор",
    "портативный проектор",
    "экран для проектора",
    "лампа проектора",
    "проецирование",
    "бимер",
    "настроить проектор к совещанию",
    "подключить ноутбук к проектору",
    "заменить лампу проектора до презентации",
    "купить новый экран для проектора в офис",
    "проектор в конференц-зале не работает",
    "настроить домашний кинопроектор на киновечер",
    "загрузить слайды на презентационный проектор",
    "сфокусировать проектор до начала доклада",
    "взять портативный проектор на встречу с клиентом",
    "заказать запасной кабель для проектора онлайн",
    "протереть линзу проектора перед презентацией",
    "проверить подключение проектора до конференции",
    "установить проектор на потолок в переговорной",
    "проектор перегрелся во время длинной презентации",
    "переключить проектор на вход HDMI",
    "настроить яркость проектора под освещение комнаты",
    "вернуть одолженный проектор в IT отдел",
    "арендовать проектор для кино на открытом воздухе",
    "вентилятор проектора сильно шумит",
    "обновить прошивку проектора",
    "забронировать конференц-зал с проектором",
    "прогнать слайды на проекторе перед выступлением",
    "упаковать проектор для выездной презентации",
    "пульт от проектора нуждается в новых батарейках",
    "проверить свободен ли проектор для мастер-класса",
    "купить HDMI-адаптер для проектора",
    "изображение проектора размытое на экране",
    "поставить таймер автовыключения проектора через час",
    "подключить звуковую систему к проектору",
    "экран для проектора нужно опустить",
    "сравнить модели проекторов для нового офиса",
    "нужно поправить выравнивание проектора в переговорной",
    "забронировать проектор на презентацию во вторник",
    "проетор для совещания",
    "презентаця слайдов на проекторе",
    "замна лампы проектора",
    "конфернц-зал настройка проектора",
    "проектро экран размыт",
],
de=[
    "Beamer",
    "Präsentation",
    "Folien",
    "Filmprojektor",
    "Leinwand",
    "PowerPoint",
    "Keynote",
    "Kinoprojektor",
    "Konferenzraum-Beamer",
    "Heimkino-Beamer",
    "Foliensatz",
    "Overheadprojektor",
    "Videoprojektor",
    "tragbarer Beamer",
    "Beamer-Leinwand",
    "Beamerlampe",
    "Projektion",
    "Projektor",
    "den Beamer für das Meeting aufbauen",
    "den Laptop an den Beamer anschließen",
    "die Beamerlampe vor der Präsentation austauschen",
    "eine neue Leinwand für das Büro kaufen",
    "der Beamer im Konferenzraum funktioniert nicht",
    "den Heimkino-Beamer für den Filmabend einrichten",
    "die Folien auf den Präsentationsbeamer laden",
    "den Beamer vor dem Vortrag scharfstellen",
    "den tragbaren Beamer zum Kundentermin mitnehmen",
    "ein Ersatzkabel für den Beamer online bestellen",
    "die Beamerlinse vor der Präsentation reinigen",
    "die Beamerverbindung vor der Konferenz testen",
    "den Beamer an die Decke im Besprechungsraum montieren",
    "der Beamer ist während der langen Präsentation überhitzt",
    "den Beamer auf HDMI-Eingang umschalten",
    "die Beamerhelligkeit an die Raumbeleuchtung anpassen",
    "den geliehenen Beamer an die IT-Abteilung zurückgeben",
    "einen Beamer für den Filmabend draußen mieten",
    "der Beamerlüfter macht laute Geräusche",
    "die Beamer-Firmware aktualisieren",
    "den Konferenzraum mit Beamer reservieren",
    "die Folien vor dem Vortrag am Beamer durchgehen",
    "den Beamer für die externe Präsentation einpacken",
    "die Beamerfernbedienung braucht neue Batterien",
    "Beamerverfügbarkeit für den Workshop prüfen",
    "einen HDMI-Adapter für den Beamer kaufen",
    "das Beamerbild ist unscharf auf der Leinwand",
    "den Beamer-Timer auf automatisches Abschalten einstellen",
    "die Soundanlage an den Beamer anschließen",
    "die Beamer-Leinwand muss heruntergelassen werden",
    "Beamermodelle für das neue Büro vergleichen",
    "muss die Beamerausrichtung im Besprechungsraum korrigieren",
    "den Beamer für die Präsentation am Dienstag reservieren",
    "Bemaer für das Meeting",
    "Präsentaiton Folien am Beamer",
    "Beamelampe austauschen",
    "Konfernzraum Beamer aufbauen",
    "Beamer Bild unscahrf",
],
ja=[
    "プロジェクター",
    "プレゼンテーション",
    "スライド",
    "映画用プロジェクター",
    "スクリーン",
    "パワーポイント",
    "キーノート",
    "フィルムプロジェクター",
    "会議室のプロジェクター",
    "ホームシアタープロジェクター",
    "スライド資料",
    "OHPプロジェクター",
    "ビデオプロジェクター",
    "ポータブルプロジェクター",
    "プロジェクタースクリーン",
    "プロジェクターランプ",
    "投影",
    "ビーマー",
    "会議のためにプロジェクターを準備する",
    "ノートパソコンをプロジェクターに接続する",
    "プレゼンの前にプロジェクターのランプを交換する",
    "オフィス用に新しいプロジェクタースクリーンを買う",
    "会議室のプロジェクターが動かない",
    "映画の夜のためにホームシアタープロジェクターを準備する",
    "プレゼン用プロジェクターにスライドを読み込む",
    "基調講演の前にプロジェクターのピントを合わせる",
    "クライアントとの会議にポータブルプロジェクターを持っていく",
    "プロジェクターの予備ケーブルをオンラインで注文する",
    "プレゼンの前にプロジェクターのレンズを掃除する",
    "会議前にプロジェクターの接続をテストする",
    "会議室の天井にプロジェクターを設置する",
    "長いプレゼン中にプロジェクターが過熱した",
    "プロジェクターをHDMI入力に切り替える",
    "部屋の照明に合わせてプロジェクターの明るさを調整する",
    "借りたプロジェクターをIT部門に返す",
    "屋外映画の夜のためにプロジェクターをレンタルする",
    "プロジェクターのファンがうるさい",
    "プロジェクターのファームウェアを更新する",
    "プロジェクター付きの会議室を予約する",
    "発表前にプロジェクターでスライドを練習する",
    "出張プレゼン用にプロジェクターを梱包する",
    "プロジェクターのリモコンの電池を交換する",
    "ワークショップ用にプロジェクターの空きを確認する",
    "プロジェクター用のHDMIアダプターを買う",
    "プロジェクターの映像がスクリーン上でぼやけている",
    "1時間後に自動オフになるようプロジェクターのタイマーを設定する",
    "音響システムをプロジェクターに接続する",
    "プロジェクタースクリーンを下ろす必要がある",
    "新しいオフィス用にプロジェクターの機種を比較する",
    "会議室のプロジェクターの位置を直す必要がある",
    "火曜日のプレゼン用にプロジェクターを予約する",
    "ぷろじぇくたー会議用",
    "プレゼンテーしょんスライド",
    "プロジェクタのランプ交換",
    "かいぎ室プロジェクター設定",
    "プロジェクタースクリンぼやけ",
],
fr=[
    "vidéoprojecteur",
    "présentation",
    "diapositives",
    "projecteur de cinéma",
    "écran",
    "PowerPoint",
    "Keynote",
    "projecteur de film",
    "vidéoprojecteur de salle de conférence",
    "vidéoprojecteur home cinéma",
    "jeu de diapositives",
    "rétroprojecteur",
    "projecteur vidéo",
    "vidéoprojecteur portable",
    "écran de projection",
    "lampe de vidéoprojecteur",
    "projection",
    "projecteur",
    "installer le vidéoprojecteur pour la réunion",
    "connecter le portable au vidéoprojecteur",
    "remplacer la lampe du vidéoprojecteur avant la présentation",
    "acheter un nouvel écran de projection pour le bureau",
    "le vidéoprojecteur de la salle de conférence ne marche pas",
    "installer le vidéoprojecteur home cinéma pour la soirée film",
    "charger les diapositives sur le vidéoprojecteur",
    "régler la mise au point avant le début de la conférence",
    "apporter le vidéoprojecteur portable chez le client",
    "commander un câble de rechange pour le vidéoprojecteur en ligne",
    "nettoyer l'objectif du vidéoprojecteur avant la présentation",
    "tester la connexion du vidéoprojecteur avant la conférence",
    "fixer le vidéoprojecteur au plafond de la salle de réunion",
    "le vidéoprojecteur a surchauffé pendant la longue présentation",
    "passer le vidéoprojecteur sur l'entrée HDMI",
    "ajuster la luminosité du vidéoprojecteur selon l'éclairage",
    "rendre le vidéoprojecteur emprunté au service informatique",
    "louer un vidéoprojecteur pour le cinéma en plein air",
    "le ventilateur du vidéoprojecteur fait un bruit fort",
    "mettre à jour le firmware du vidéoprojecteur",
    "réserver la salle de conférence avec le vidéoprojecteur",
    "répéter les diapos au vidéoprojecteur avant l'exposé",
    "emballer le vidéoprojecteur pour la présentation hors site",
    "la télécommande du vidéoprojecteur a besoin de piles neuves",
    "vérifier la disponibilité du vidéoprojecteur pour l'atelier",
    "acheter un adaptateur HDMI pour le vidéoprojecteur",
    "l'image du vidéoprojecteur est floue sur l'écran",
    "régler le minuteur d'arrêt automatique du vidéoprojecteur",
    "connecter le système audio au vidéoprojecteur",
    "l'écran de projection doit être déroulé",
    "comparer les modèles de vidéoprojecteurs pour le nouveau bureau",
    "il faut corriger l'alignement du vidéoprojecteur",
    "réserver le vidéoprojecteur pour la présentation de mardi",
    "vidéoprojectuer pour la réunion",
    "présentaiton diapositives vidéoprojecteur",
    "lampe de vidéoprojectuer à remplacer",
    "salle de confrérence vidéoprojecteur",
    "image du vidéoprojecteur floue sur l'écrna",
],
es=[
    "proyector",
    "presentación",
    "diapositivas",
    "proyector de cine",
    "pantalla",
    "PowerPoint",
    "Keynote",
    "proyector de película",
    "proyector de sala de juntas",
    "proyector de cine en casa",
    "juego de diapositivas",
    "retroproyector",
    "videoproyector",
    "proyector portátil",
    "pantalla de proyección",
    "lámpara del proyector",
    "proyección",
    "cañón de proyección",
    "instalar el proyector para la junta",
    "conectar la laptop al proyector",
    "cambiar la lámpara del proyector antes de la presentación",
    "comprar una pantalla de proyección nueva para la oficina",
    "el proyector de la sala de juntas no funciona",
    "configurar el proyector de cine en casa para la noche de película",
    "cargar las diapositivas en el proyector de presentación",
    "enfocar el proyector antes de que empiece la conferencia",
    "llevar el proyector portátil a la reunión con el cliente",
    "pedir un cable de repuesto para el proyector por internet",
    "limpiar el lente del proyector antes de la presentación",
    "probar la conexión del proyector antes de la conferencia",
    "montar el proyector en el techo de la sala de juntas",
    "el proyector se sobrecalentó durante la presentación larga",
    "cambiar el proyector a entrada HDMI",
    "ajustar el brillo del proyector según la luz del salón",
    "devolver el proyector prestado al departamento de TI",
    "rentar un proyector para la noche de cine al aire libre",
    "el ventilador del proyector hace mucho ruido",
    "actualizar el firmware del proyector",
    "reservar la sala de juntas con proyector",
    "ensayar las diapositivas en el proyector antes de la charla",
    "empacar el proyector para la presentación fuera de oficina",
    "el control remoto del proyector necesita pilas nuevas",
    "verificar si el proyector está disponible para el taller",
    "comprar un adaptador HDMI para el proyector",
    "la imagen del proyector se ve borrosa en la pantalla",
    "poner el temporizador del proyector para apagado automático",
    "conectar el sistema de sonido al proyector",
    "hay que bajar la pantalla de proyección",
    "comparar modelos de proyector para la oficina nueva",
    "necesito arreglar la alineación del proyector en la sala",
    "reservar el proyector para la presentación del martes",
    "proyetor para la junta",
    "presentacón diapositivas en proyector",
    "lámpra del proyector cambiar",
    "sala de jnuats proyector instalar",
    "imagen del proyector borrsoa",
])


# ── pumpkin ───────────────────────────────────────────────────────────────────
gen("pumpkin",
en=[
    "pumpkin",
    "Halloween",
    "jack-o-lantern",
    "autumn",
    "fall",
    "harvest",
    "Thanksgiving",
    "squash",
    "pumpkin patch",
    "pumpkin pie",
    "carve pumpkin",
    "October",
    "seasonal",
    "gourd",
    "pumpkin spice",
    "pumpkin seeds",
    "fall decorating",
    "pumpkin soup",
    "buy a pumpkin at the farmers market",
    "carve the pumpkin for Halloween night",
    "bake a pumpkin pie for Thanksgiving dinner",
    "pick pumpkins at the local pumpkin patch",
    "roast the pumpkin seeds for a snack",
    "decorate the porch with pumpkins for fall",
    "buy pumpkin spice for the coffee",
    "make pumpkin soup for dinner tonight",
    "paint the pumpkin instead of carving it",
    "the kids want to pick out their own pumpkins",
    "find a pumpkin pie recipe for the holiday",
    "buy mini pumpkins for the table centerpiece",
    "the pumpkin on the porch is starting to rot",
    "order pumpkin seeds online for planting",
    "make pumpkin bread for the bake sale",
    "get pumpkin puree at the grocery store",
    "set up the jack-o-lantern before trick-or-treaters come",
    "try the pumpkin spice latte at the coffee shop",
    "bring pumpkins to the fall festival booth",
    "cook butternut squash and pumpkin for the harvest dinner",
    "the pumpkin patch is open on weekends in October",
    "buy Halloween pumpkin carving tools",
    "save the pumpkin seeds for roasting later",
    "make pumpkin muffins for breakfast tomorrow",
    "get a big pumpkin for the front porch display",
    "the pumpkin spice season starts in September",
    "donate pumpkins to the community fall event",
    "pumpkin everything at the store right now",
    "compost the old pumpkins after Halloween",
    "buy canned pumpkin for the pie filling",
    "take the kids to the pumpkin patch this weekend",
    "need pumpkin decorations for the fall party",
    "the squash and pumpkin harvest is ready",
    "pumpikn carving for Halloween",
    "pumkin pie at Thanksgiving",
    "pumpkon on the porch",
    "pumpkin seeeds for roasting",
    "hallowen pumpkin decorations",
],
ru=[
    "тыква",
    "Хэллоуин",
    "тыква-фонарь",
    "осень",
    "осенний",
    "урожай",
    "День благодарения",
    "сквош",
    "тыквенное поле",
    "тыквенный пирог",
    "вырезать тыкву",
    "октябрь",
    "сезонный",
    "декоративная тыква",
    "тыквенная приправа",
    "тыквенные семечки",
    "осенний декор",
    "тыквенный суп",
    "купить тыкву на фермерском рынке",
    "вырезать тыкву к ночи Хэллоуина",
    "испечь тыквенный пирог к ужину на День благодарения",
    "набрать тыкв на местном тыквенном поле",
    "поджарить тыквенные семечки на перекус",
    "украсить крыльцо тыквами к осени",
    "купить тыквенную приправу для кофе",
    "сварить тыквенный суп на ужин сегодня",
    "раскрасить тыкву вместо вырезания",
    "дети хотят сами выбрать свои тыквы",
    "найти рецепт тыквенного пирога к празднику",
    "купить маленькие тыквы для украшения стола",
    "тыква на крыльце начинает подгнивать",
    "заказать семена тыквы онлайн для посадки",
    "испечь тыквенный хлеб на благотворительную распродажу",
    "купить тыквенное пюре в продуктовом",
    "поставить тыкву-фонарь до прихода ряженых",
    "попробовать тыквенный латте в кофейне",
    "привезти тыквы на стенд осеннего фестиваля",
    "приготовить баттернат и тыкву к праздничному ужину",
    "тыквенное поле работает по выходным в октябре",
    "купить инструменты для вырезания тыкв на Хэллоуин",
    "сохранить семечки тыквы для запекания позже",
    "сделать тыквенные маффины к завтрашнему завтраку",
    "взять большую тыкву для украшения крыльца",
    "сезон тыквенных специй начинается в сентябре",
    "пожертвовать тыквы на осенний праздник в сообществе",
    "в магазине сейчас всё тыквенное",
    "компостировать старые тыквы после Хэллоуина",
    "купить консервированную тыкву для начинки пирога",
    "отвезти детей на тыквенное поле в эти выходные",
    "нужны тыквенные украшения для осенней вечеринки",
    "урожай тыквы и сквоша готов",
    "вырзание тыквы на Хэллоуин",
    "тыквенны пирог на День благодарения",
    "тыква на крыьце",
    "тыквенные смечки для жарки",
    "хэллоуинские тыквеные украшения",
],
de=[
    "Kürbis",
    "Halloween",
    "Kürbislaterne",
    "Herbst",
    "herbstlich",
    "Ernte",
    "Erntedankfest",
    "Speisekürbis",
    "Kürbisfeld",
    "Kürbiskuchen",
    "Kürbis schnitzen",
    "Oktober",
    "saisonal",
    "Zierkürbis",
    "Kürbisgewürz",
    "Kürbiskerne",
    "Herbstdeko",
    "Kürbissuppe",
    "einen Kürbis auf dem Bauernmarkt kaufen",
    "den Kürbis für Halloween schnitzen",
    "einen Kürbiskuchen zum Erntedankessen backen",
    "Kürbisse auf dem Kürbisfeld pflücken",
    "Kürbiskerne als Snack rösten",
    "die Veranda mit Kürbissen für den Herbst dekorieren",
    "Kürbisgewürz für den Kaffee kaufen",
    "heute Abend Kürbissuppe zum Abendessen kochen",
    "den Kürbis anmalen statt zu schnitzen",
    "die Kinder wollen ihre Kürbisse selbst aussuchen",
    "ein Kürbiskuchen-Rezept für den Feiertag finden",
    "Mini-Kürbisse als Tischdekoration kaufen",
    "der Kürbis auf der Veranda fängt an zu faulen",
    "Kürbissamen online zum Pflanzen bestellen",
    "Kürbisbrot für den Kuchenbasar backen",
    "Kürbispüree im Supermarkt kaufen",
    "die Kürbislaterne aufstellen bevor die Kinder kommen",
    "den Kürbis-Latte im Café probieren",
    "Kürbisse zum Herbstfest-Stand mitbringen",
    "Butternut-Kürbis und Kürbis fürs Ernteessen kochen",
    "das Kürbisfeld hat im Oktober an Wochenenden geöffnet",
    "Schnitzwerkzeuge für Halloween-Kürbisse kaufen",
    "Kürbiskerne zum späteren Rösten aufheben",
    "Kürbismuffins fürs Frühstück morgen machen",
    "einen großen Kürbis für die Veranda-Dekoration holen",
    "die Kürbisgewürz-Saison beginnt im September",
    "Kürbisse für das Herbstfest in der Gemeinde spenden",
    "im Laden ist jetzt alles mit Kürbis",
    "alte Kürbisse nach Halloween kompostieren",
    "Kürbiskonserven für die Kuchenfüllung kaufen",
    "die Kinder am Wochenende zum Kürbisfeld fahren",
    "Kürbis-Deko für die Herbstparty wird gebraucht",
    "die Kürbis- und Speisekürbisernte ist fertig",
    "Kübris schnitzen für Halloween",
    "Kürbiskuhen zum Erntedank",
    "Küribs auf der Veranda",
    "Kürbiskrene zum Rösten",
    "Hallowen Kürbis-Deko",
],
ja=[
    "かぼちゃ",
    "ハロウィン",
    "ジャック・オー・ランタン",
    "秋",
    "秋の",
    "収穫",
    "感謝祭",
    "スクワッシュ",
    "かぼちゃ畑",
    "パンプキンパイ",
    "かぼちゃを彫る",
    "10月",
    "季節の",
    "飾りかぼちゃ",
    "パンプキンスパイス",
    "かぼちゃの種",
    "秋のデコレーション",
    "パンプキンスープ",
    "ファーマーズマーケットでかぼちゃを買う",
    "ハロウィンの夜のためにかぼちゃを彫る",
    "感謝祭のディナーにパンプキンパイを焼く",
    "地元のかぼちゃ畑でかぼちゃを採る",
    "おやつにかぼちゃの種をローストする",
    "秋に向けて玄関をかぼちゃで飾る",
    "コーヒー用にパンプキンスパイスを買う",
    "今夜の夕食にパンプキンスープを作る",
    "彫る代わりにかぼちゃにペイントする",
    "子供たちが自分でかぼちゃを選びたがっている",
    "祝日用のパンプキンパイのレシピを探す",
    "テーブルの飾り用にミニかぼちゃを買う",
    "玄関のかぼちゃが腐り始めている",
    "植え付け用のかぼちゃの種をオンラインで注文する",
    "チャリティーセール用にパンプキンブレッドを焼く",
    "スーパーでかぼちゃのピューレを買う",
    "トリック・オア・トリートの子供たちが来る前にランタンを準備する",
    "カフェでパンプキンスパイスラテを試す",
    "秋祭りのブースにかぼちゃを持っていく",
    "収穫ディナーにバターナッツとかぼちゃを料理する",
    "10月の週末はかぼちゃ畑が開いている",
    "ハロウィン用のかぼちゃ彫りの道具を買う",
    "あとでローストするためにかぼちゃの種を取っておく",
    "明日の朝食にかぼちゃのマフィンを作る",
    "玄関の飾り用に大きなかぼちゃを買う",
    "パンプキンスパイスの季節は9月から始まる",
    "地域の秋祭りにかぼちゃを寄付する",
    "お店に今かぼちゃ関連の商品がたくさんある",
    "ハロウィンの後に古いかぼちゃをコンポストする",
    "パイの中身用に缶入りかぼちゃを買う",
    "今週末子供たちをかぼちゃ畑に連れて行く",
    "秋のパーティー用にかぼちゃの飾りが必要",
    "かぼちゃとスクワッシュの収穫の準備ができた",
    "かぼちゃ彫りはろうぃん",
    "パンプキンぱい感謝祭",
    "かぼちゃ玄関にかざる",
    "かぼちゃのたね焼く",
    "ハロウインかぼちゃ飾り",
],
fr=[
    "citrouille",
    "Halloween",
    "lanterne citrouille",
    "automne",
    "automnal",
    "récolte",
    "Action de grâce",
    "courge",
    "champ de citrouilles",
    "tarte à la citrouille",
    "sculpter une citrouille",
    "octobre",
    "saisonnier",
    "coloquinte",
    "épice citrouille",
    "graines de citrouille",
    "décoration d'automne",
    "soupe de citrouille",
    "acheter une citrouille au marché fermier",
    "sculpter la citrouille pour la nuit d'Halloween",
    "faire une tarte à la citrouille pour le repas de fête",
    "cueillir des citrouilles au champ de citrouilles local",
    "griller les graines de citrouille pour le goûter",
    "décorer le perron avec des citrouilles pour l'automne",
    "acheter de l'épice citrouille pour le café",
    "préparer une soupe de citrouille pour le dîner ce soir",
    "peindre la citrouille au lieu de la sculpter",
    "les enfants veulent choisir leurs propres citrouilles",
    "trouver une recette de tarte à la citrouille pour les fêtes",
    "acheter des mini citrouilles pour le centre de table",
    "la citrouille sur le perron commence à pourrir",
    "commander des graines de citrouille en ligne pour planter",
    "faire du pain à la citrouille pour la vente de gâteaux",
    "acheter de la purée de citrouille au supermarché",
    "installer la lanterne avant l'arrivée des enfants déguisés",
    "essayer le latte à la citrouille au café",
    "apporter des citrouilles au stand du festival d'automne",
    "cuisiner du butternut et de la citrouille pour le dîner de récolte",
    "le champ de citrouilles est ouvert le week-end en octobre",
    "acheter des outils pour sculpter les citrouilles d'Halloween",
    "garder les graines de citrouille pour les griller plus tard",
    "faire des muffins à la citrouille pour le petit-déjeuner demain",
    "prendre une grosse citrouille pour décorer le perron",
    "la saison des épices citrouille commence en septembre",
    "donner des citrouilles à la fête d'automne de la communauté",
    "tout est à la citrouille au magasin en ce moment",
    "composter les vieilles citrouilles après Halloween",
    "acheter de la citrouille en conserve pour la garniture de tarte",
    "emmener les enfants au champ de citrouilles ce week-end",
    "il faut des décorations citrouille pour la fête d'automne",
    "la récolte de courges et citrouilles est prête",
    "scultper la citrouille pour Halloween",
    "tarte à la citrouilel pour la fête",
    "citrouille sur le perorn",
    "graines de citruoille à griller",
    "décortaion d'Halloween citrouille",
],
es=[
    "calabaza",
    "Halloween",
    "linterna de calabaza",
    "otoño",
    "otoñal",
    "cosecha",
    "Día de Acción de Gracias",
    "calabacín",
    "campo de calabazas",
    "pay de calabaza",
    "tallar una calabaza",
    "octubre",
    "de temporada",
    "calabaza decorativa",
    "especia de calabaza",
    "semillas de calabaza",
    "decoración de otoño",
    "sopa de calabaza",
    "comprar una calabaza en el mercado de agricultores",
    "tallar la calabaza para la noche de Halloween",
    "hornear un pay de calabaza para la cena de Acción de Gracias",
    "recoger calabazas en el campo de calabazas local",
    "tostar semillas de calabaza para un snack",
    "decorar el porche con calabazas para el otoño",
    "comprar especia de calabaza para el café",
    "preparar sopa de calabaza para la cena de esta noche",
    "pintar la calabaza en vez de tallarla",
    "los niños quieren elegir sus propias calabazas",
    "buscar una receta de pay de calabaza para las fiestas",
    "comprar calabazas pequeñas para el centro de mesa",
    "la calabaza del porche se está empezando a pudrir",
    "pedir semillas de calabaza por internet para plantar",
    "hacer pan de calabaza para la venta de pasteles",
    "comprar puré de calabaza en el supermercado",
    "poner la linterna de calabaza antes de que lleguen los niños",
    "probar el latte de calabaza en la cafetería",
    "llevar calabazas al puesto del festival de otoño",
    "cocinar calabaza butternut para la cena de cosecha",
    "el campo de calabazas abre los fines de semana en octubre",
    "comprar herramientas para tallar calabazas de Halloween",
    "guardar las semillas de calabaza para tostar después",
    "hacer muffins de calabaza para el desayuno de mañana",
    "conseguir una calabaza grande para decorar el porche",
    "la temporada de especias de calabaza empieza en septiembre",
    "donar calabazas al evento de otoño de la comunidad",
    "todo es de calabaza en la tienda ahorita",
    "compostar las calabazas viejas después de Halloween",
    "comprar calabaza enlatada para el relleno del pay",
    "llevar a los niños al campo de calabazas este fin de semana",
    "necesitamos decoraciones de calabaza para la fiesta de otoño",
    "la cosecha de calabaza y calabacín está lista",
    "talllar la calabaza para Halloween",
    "pay de calabza para Acción de Gracias",
    "calabza en el porche",
    "semillas de calabza para tostar",
    "decoraciones de Hallowen calabaza",
])

print("\n=== Part 3 done (projector, pumpkin) ===")
