#!/usr/bin/env python3
"""Batch task-003a: trademark, train, transmission, tree, tricycle-adult.

60 phrases × 6 languages each. Cleans existing EN/RU, creates DE/JA/FR/ES.
"""

from gen_icons_task_002_util import clean_and_expand

ok = True

# ── 1. trademark ─────────────────────────────────────────────────────────────
ok &= clean_and_expand("trademark",
    remove_en_texts=[
        # visual / devspeak
        "trademark icon for a legal or brand management app",
        "registered trademark R circle on a logo",
        "intellectual property mark on a product label",
        "TM superscript symbol after a brand name",
        "trademark symbol indicating unregistered brand",
        "registered trademark symbol after the brand name",
        "legal symbol appended to a brand name",
        "symbol denoting intellectual property ownership",
        "tm superscript after an unregistered brand",
        "brand name followed by the trademark symbol",
        "trademark symbol printed on packaging",
        "legal mark showing ownership of a brand",
        "copyright notice printed at the bottom of the page",
        "copyright law protecting creative works",
    ],
    remove_ru_texts=[
        # devspeak / visual
        "иконка для прав на бренд",
        "значок для регистрации бренда",
        "зарегистрированный знак рядом с логотипом",
        "отличие TM от ®",
        "брендовый символ на ярлыке",
        "знак бренда в футере",
        "пометка в карточке бренда",
    ],
    new_en=[
        # keywords (~18)
        "brand",
        "register",
        "trademark",
        "brand protection",
        "registered mark",
        "intellectual property",
        "brand identity",
        "brand name",
        "TM filing",
        "brand registration",
        "trademark law",
        "trademark search",
        "brand licensing",
        "trademark renewal",
        # phrases
        "register the trademark before product launch",
        "file a trademark application this week",
        "check if our brand name is already trademarked",
        "renew the trademark registration next month",
        "hire a lawyer for the trademark dispute",
        "search the trademark database for conflicts",
        "submit trademark paperwork to the patent office",
        "protect the brand name with a trademark",
        "get a cease and desist for trademark violation",
        "consult the attorney about trademark infringement",
        "register our logo as a trademark",
        "trademark the new slogan before the campaign",
        "review trademark status for the new brand",
        "update trademark records with the new address",
        "pay the trademark registration fee online",
        "check trademark expiration dates this quarter",
        "brand licensing agreement needs trademark clause",
        "request a trademark certificate from the office",
        "monitor competitors for trademark infringement",
        "file for international trademark protection",
        "the TM on the label needs to be updated",
        "our trademark was approved by the office",
        "schedule a meeting with the trademark attorney",
        "the brand mark is pending registration",
        "cancel the old trademark for the discontinued line",
        "transfer trademark ownership to the new company",
        "run a trademark search before naming the product",
        "legal department is handling the trademark case",
        "need to register TM in three more countries",
        "trademark dispute resolved in our favor",
        "apply for trademark in the EU market",
        "brand name is too generic to trademark",
        "copyright and trademark are different protections",
        "prepare trademark documents for the lawyer",
        # typos
        "file tradmark application this week",
        "regsiter the trademark befroe launch",
        "trademarrk dispute resolved in our fvor",
        "chekc trademark expiration datse",
        "pay the tradmark registrtion fee onlne",
    ],
    new_ru=[
        # keywords (~18)
        "бренд",
        "марка",
        "регистрация",
        "защита бренда",
        "зарегистрированная марка",
        "интеллектуальная собственность",
        "идентичность бренда",
        "название бренда",
        "подача заявки на ТМ",
        "регистрация бренда",
        "закон о товарных знаках",
        "поиск товарного знака",
        "лицензирование бренда",
        "продление товарного знака",
        # phrases
        "зарегистрировать товарный знак до запуска продукта",
        "подать заявку на товарный знак на этой неделе",
        "проверить не занято ли название бренда",
        "продлить регистрацию товарного знака в следующем месяце",
        "нанять юриста для спора по товарному знаку",
        "проверить базу товарных знаков на конфликты",
        "подать документы на товарный знак в патентное бюро",
        "защитить название бренда товарным знаком",
        "отправить предупреждение за нарушение товарного знака",
        "проконсультироваться с юристом о нарушении прав",
        "зарегистрировать логотип как товарный знак",
        "зарегистрировать новый слоган до начала кампании",
        "проверить статус товарного знака для нового бренда",
        "обновить записи товарного знака с новым адресом",
        "оплатить регистрацию товарного знака онлайн",
        "проверить сроки действия товарных знаков в этом квартале",
        "в лицензионное соглашение нужен пункт о товарном знаке",
        "запросить сертификат товарного знака из бюро",
        "следить за конкурентами на предмет нарушений",
        "подать на международную защиту товарного знака",
        "обновить знак ТМ на этикетке",
        "наш товарный знак одобрили в бюро",
        "назначить встречу с юристом по товарным знакам",
        "марка бренда ожидает регистрации",
        "аннулировать старый товарный знак снятой линейки",
        "передать право на товарный знак новой компании",
        "провести поиск товарного знака перед названием продукта",
        "юридический отдел занимается делом о товарном знаке",
        "нужно зарегистрировать ТМ ещё в трёх странах",
        "спор по товарному знаку решился в нашу пользу",
        "подать на товарный знак на рынке ЕС",
        "название слишком общее для регистрации",
        "авторское право и товарный знак это разные вещи",
        "подготовить документы на товарный знак для юриста",
        # typos
        "зарегистрироват товарный знак до запуска",
        "подат заявку на товраный знак",
        "проврить базу товарных знакоа",
        "обновтиь записи товарнго знака",
        "оплатиь регистрацю товарного знака",
    ],
    new_de=[
        # keywords (~18)
        "Marke",
        "Warenzeichen",
        "Registrierung",
        "Symbol",
        "TM",
        "Markenzeichen",
        "Markenschutz",
        "eingetragene Marke",
        "geistiges Eigentum",
        "Markenidentität",
        "Markenname",
        "TM-Anmeldung",
        "Markenregistrierung",
        "Markenrecht",
        "Markenrecherche",
        "Markenlizenzierung",
        "Markenverlängerung",
        "Markenanmeldung",
        # phrases
        "Warenzeichen vor dem Produktstart registrieren",
        "diese Woche die Markenanmeldung einreichen",
        "prüfen ob der Markenname schon vergeben ist",
        "Markenregistrierung nächsten Monat verlängern",
        "Anwalt für den Markenstreit beauftragen",
        "Markendatenbank auf Konflikte durchsuchen",
        "TM-Symbol auf die neue Verpackung setzen",
        "Markenunterlagen beim Patentamt einreichen",
        "Markennamen mit einem Warenzeichen schützen",
        "Abmahnung wegen Markenrechtsverletzung senden",
        "Anwalt wegen Markenrechtsverletzung konsultieren",
        "unser Logo als Marke registrieren",
        "neuen Slogan vor der Kampagne schützen",
        "Markenstatus für die neue Marke prüfen",
        "Markenunterlagen mit neuer Adresse aktualisieren",
        "Markengebühr online bezahlen",
        "Ablaufdaten der Marken dieses Quartal prüfen",
        "Lizenzvertrag braucht Markenklausel",
        "Markenzertifikat beim Amt anfordern",
        "Wettbewerber auf Markenverletzung überwachen",
        "internationalen Markenschutz beantragen",
        "TM-Zeichen auf dem Etikett aktualisieren",
        "unsere Marke wurde vom Amt genehmigt",
        "Termin mit dem Markenanwalt vereinbaren",
        "die Marke wartet auf Registrierung",
        "altes Warenzeichen der eingestellten Linie stornieren",
        "Markenrecht an die neue Firma übertragen",
        "Markenrecherche vor der Produktbenennung durchführen",
        "Rechtsabteilung bearbeitet den Markenfall",
        "TM muss noch in drei Ländern registriert werden",
        "Markenstreit zu unseren Gunsten entschieden",
        "Marke auf dem EU-Markt anmelden",
        "Name ist zu generisch für eine Marke",
        "Urheberrecht und Markenrecht sind verschiedene Schutzrechte",
        "Markenunterlagen für den Anwalt vorbereiten",
        # typos
        "Warenzeichen vor dem Produktstrat registrieren",
        "Markenannmeldung diese Woche einreichen",
        "Markendatenbenk auf Konflikte prüfen",
        "Markenstaus für die neue Marke prüfen",
        "Markengebür online bezahlen",
    ],
    new_ja=[
        # keywords (~18)
        "ブランド",
        "商標",
        "登録",
        "シンボル",
        "TM",
        "トレードマーク",
        "ブランド保護",
        "登録商標",
        "知的財産",
        "ブランドアイデンティティ",
        "ブランド名",
        "TM出願",
        "ブランド登録",
        "商標法",
        "商標調査",
        "ブランドライセンス",
        "商標更新",
        "商標出願",
        # phrases
        "製品発売前に商標を登録する",
        "今週中に商標出願を提出する",
        "ブランド名が既に登録されていないか確認する",
        "来月商標登録を更新する",
        "商標紛争のために弁護士を雇う",
        "商標データベースで競合を調べる",
        "新しいパッケージにTMマークを追加する",
        "特許庁に商標書類を提出する",
        "商標でブランド名を保護する",
        "商標違反で警告書を送る",
        "商標侵害について弁護士に相談する",
        "ロゴを商標として登録する",
        "キャンペーン前に新しいスローガンを商標登録する",
        "新ブランドの商標ステータスを確認する",
        "新しい住所で商標記録を更新する",
        "商標登録料をオンラインで支払う",
        "今四半期の商標期限を確認する",
        "ライセンス契約に商標条項が必要",
        "特許庁から商標証明書を取得する",
        "競合他社の商標侵害を監視する",
        "国際的な商標保護を申請する",
        "ラベルのTMマークを更新する",
        "商標が特許庁に承認された",
        "商標弁護士との会議を予約する",
        "ブランドマークは登録待ち",
        "廃止ラインの古い商標を取り消す",
        "商標権を新会社に移転する",
        "製品命名前に商標調査を行う",
        "法務部が商標訴訟を担当している",
        "あと三か国でTMを登録する必要がある",
        "商標紛争が我々に有利に解決した",
        "EU市場で商標を申請する",
        "名前が一般的すぎて商標登録できない",
        "著作権と商標は異なる保護制度",
        "弁護士用に商標書類を準備する",
        # typos
        "製品発売前にしょうひょうを登録する",
        "商標出願をていしゅつする",
        "ブランド名がとうろくされていないか確認",
        "来月しょうひょう登録を更新する",
        "商標データベースでちょうさする",
    ],
    new_fr=[
        # keywords (~18)
        "marque",
        "signe",
        "enregistrement",
        "symbole",
        "TM",
        "marque déposée",
        "protection de marque",
        "marque enregistrée",
        "propriété intellectuelle",
        "identité de marque",
        "nom de marque",
        "dépôt de marque",
        "enregistrement de marque",
        "droit des marques",
        "recherche de marque",
        "licence de marque",
        "renouvellement de marque",
        "demande de marque",
        # phrases
        "enregistrer la marque avant le lancement du produit",
        "déposer la demande de marque cette semaine",
        "vérifier si le nom de marque est déjà pris",
        "renouveler la marque le mois prochain",
        "engager un avocat pour le litige de marque",
        "chercher dans la base de données des marques",
        "ajouter le symbole TM sur le nouvel emballage",
        "soumettre les documents de marque au bureau des brevets",
        "protéger le nom de marque par un enregistrement",
        "envoyer une mise en demeure pour contrefaçon",
        "consulter un avocat sur la contrefaçon de marque",
        "enregistrer notre logo comme marque déposée",
        "protéger le nouveau slogan avant la campagne",
        "vérifier le statut de la marque pour le nouveau produit",
        "mettre à jour les dossiers de marque avec la nouvelle adresse",
        "payer les frais de dépôt de marque en ligne",
        "vérifier les dates d'expiration des marques ce trimestre",
        "le contrat de licence a besoin d'une clause de marque",
        "demander le certificat de marque au bureau",
        "surveiller les concurrents pour contrefaçon",
        "demander la protection internationale de la marque",
        "mettre à jour le signe TM sur l'étiquette",
        "notre marque a été approuvée par le bureau",
        "prendre rendez-vous avec l'avocat en marques",
        "la marque est en attente d'enregistrement",
        "annuler l'ancienne marque de la gamme arrêtée",
        "transférer le droit de marque à la nouvelle société",
        "faire une recherche de marque avant de nommer le produit",
        "le service juridique gère le dossier de marque",
        "il faut enregistrer la marque dans trois autres pays",
        "le litige de marque a été résolu en notre faveur",
        "déposer la marque sur le marché européen",
        "le nom est trop générique pour être une marque",
        "droit d'auteur et marque sont des protections différentes",
        "préparer les documents de marque pour l'avocat",
        # typos
        "enregistrer la marqeu avant le lancement",
        "déposer la demadne de marque cette semaine",
        "vérifier si le nome de marque est déjà pris",
        "renouvler la marque le mois prochain",
        "consulter un avocta sur la contrefaçon",
    ],
    new_es=[
        # keywords (~18)
        "marca",
        "signo",
        "registro",
        "símbolo",
        "TM",
        "marca registrada",
        "protección de marca",
        "marca inscrita",
        "propiedad intelectual",
        "identidad de marca",
        "nombre de marca",
        "solicitud de marca",
        "registro de marca",
        "ley de marcas",
        "búsqueda de marca",
        "licencia de marca",
        "renovación de marca",
        "trámite de marca",
        # phrases
        "registrar la marca antes del lanzamiento del producto",
        "presentar la solicitud de marca esta semana",
        "comprobar si el nombre de marca ya está registrado",
        "renovar el registro de marca el próximo mes",
        "contratar un abogado para la disputa de marca",
        "buscar en la base de datos de marcas",
        "añadir el símbolo TM al nuevo empaque",
        "enviar los documentos de marca a la oficina de patentes",
        "proteger el nombre de marca con un registro",
        "enviar un aviso por infracción de marca",
        "consultar al abogado sobre la infracción de marca",
        "registrar nuestro logo como marca",
        "registrar el nuevo eslogan antes de la campaña",
        "revisar el estado de la marca del nuevo producto",
        "actualizar los registros de marca con la nueva dirección",
        "pagar la tasa de registro de marca en línea",
        "revisar las fechas de vencimiento de marcas este trimestre",
        "el contrato de licencia necesita cláusula de marca",
        "solicitar el certificado de marca a la oficina",
        "vigilar a los competidores por infracción de marca",
        "solicitar protección internacional de la marca",
        "actualizar el símbolo TM en la etiqueta",
        "nuestra marca fue aprobada por la oficina",
        "agendar cita con el abogado de marcas",
        "la marca está pendiente de registro",
        "cancelar la marca antigua de la línea descontinuada",
        "transferir la titularidad de la marca a la nueva empresa",
        "hacer búsqueda de marca antes de nombrar el producto",
        "el departamento legal lleva el caso de marca",
        "hay que registrar la marca en tres países más",
        "la disputa de marca se resolvió a nuestro favor",
        "solicitar la marca en el mercado europeo",
        "el nombre es demasiado genérico para ser marca",
        "derechos de autor y marca son protecciones distintas",
        "preparar los documentos de marca para el abogado",
        # typos
        "registrar la marce antes del lanzamiento",
        "presentar la solicutud de marca esta semana",
        "comprobar si el nomber de marca ya está registrado",
        "renovar el regsitro de marca el próximo mes",
        "consultar al abogdo sobre la infracción",
    ],
)

# ── 2. train ──────────────────────────────────────────────────────────────────
ok &= clean_and_expand("train",
    remove_en_texts=[
        # visual / devspeak
        "side view of a passenger train with many windows",
        "transit icon for a railway or commuting app",
        "streamlined bullet train on an elevated track",
        "public transport icon for a city navigation app",
        "train engine at the front of a long passenger set",
        "railway schedule icon in a travel planner",
        "steam train with a smoke plume from the funnel",
        "subway map icon for a city transit app",
        "railway map for a transit planning app",
        "bullet train speeding at 300 km per hour",
        "japanese bullet train on the shinkansen",
    ],
    remove_ru_texts=[
        # mixed EN / visual / devspeak / boundary (last ~6)
        "японский bullet train на shinkansen",
        "время commute отмечено в travel app",
        "карта railway для transit planning app",
        "иконка subway map для city transit app",
        "иконка транспорта для railway or commuting app",
        "обтекаемый bullet train на эстакаде",
        "иконка public transport для city navigation app",
        "иконка railway schedule в travel planner",
        "показать поезд для railway schedule feature",
        # boundary: tram/bus (wrong icon)
        "желтый трамвай на городских рельсах",
        "городской трамвай идет по проспекту",
        "двухэтажный автобус на городской дороге",
        "городской автобус подъезжает к остановке",
        # visual
        "вид сбоку на пассажирский поезд с множеством окон",
        "паровоз выпускает дым из трубы",
    ],
    new_en=[
        # keywords (~18)
        "bullet",
        "commuter",
        "locomotive",
        "rail",
        "railway",
        "subway",
        "train",
        "commute",
        "express train",
        "metro",
        "passenger train",
        "freight train",
        "high-speed rail",
        "train station",
        "platform",
        "train schedule",
        "rail pass",
        "train ticket",
        # phrases
        "catch the 8 AM train to the city",
        "buy a monthly train pass online",
        "check the train schedule for delays",
        "the train was 20 minutes late today",
        "take the train instead of driving tomorrow",
        "book a train ticket for the weekend",
        "pick up the kids at the train station",
        "the express train skips three stops",
        "commuter train is packed during rush hour",
        "ride the bullet train from Tokyo to Osaka",
        "freight train blocking the crossing again",
        "wait for the next train on platform two",
        "the subway train comes every five minutes",
        "missed the last train home",
        "new high-speed rail line opens next year",
        "train conductor checked our tickets",
        "transfer to the red line at the next station",
        "the train horn woke me up last night",
        "buy a rail pass for the European trip",
        "the morning commuter train is always crowded",
        "find a seat on the overnight train",
        "train arrives at platform three in ten minutes",
        "locomotive needs maintenance at the depot",
        "the metro train was out of service today",
        "reserve a quiet car on the train",
        "train delay notification came on my phone",
        "return train ticket leaves at six thirty",
        "look up train connections to the airport",
        "they added more cars to the evening train",
        "take the kids to see the steam locomotive",
        "new train route connects the suburbs to downtown",
        # typos
        "chekc the train schedul for delays",
        "comuter train is packd during rush hour",
        "trian delay notificaton came on my phone",
        "lok up train conections to the airport",
        "reserv a queit car on the train",
    ],
    new_ru=[
        # keywords (~18)
        "скоростной",
        "пригородный",
        "локомотив",
        "рельс",
        "железная дорога",
        "метро",
        "поезд",
        "электричка",
        "экспресс",
        "вагон",
        "пассажирский поезд",
        "товарный поезд",
        "высокоскоростная магистраль",
        "вокзал",
        "платформа",
        "расписание поездов",
        "проездной на поезд",
        "билет на поезд",
        # phrases
        "успеть на поезд в восемь утра",
        "купить месячный проездной на поезд",
        "проверить расписание поездов на задержки",
        "поезд опоздал на двадцать минут сегодня",
        "завтра поехать на поезде вместо машины",
        "забронировать билет на поезд на выходные",
        "встретить детей на вокзале",
        "экспресс пропускает три остановки",
        "пригородный поезд переполнен в час пик",
        "прокатиться на скоростном поезде до Казани",
        "товарный поезд снова перегородил переезд",
        "ждать следующий поезд на второй платформе",
        "поезд метро ходит каждые пять минут",
        "опоздал на последний поезд домой",
        "новая высокоскоростная линия откроется в следующем году",
        "проводник проверил наши билеты",
        "пересесть на красную ветку на следующей станции",
        "гудок поезда разбудил меня ночью",
        "купить проездной для поездки по Европе",
        "утренняя электричка всегда переполнена",
        "найти место в ночном поезде",
        "поезд прибывает на третью платформу через десять минут",
        "локомотив нужно обслужить в депо",
        "поезд метро не работал сегодня",
        "забронировать тихий вагон в поезде",
        "уведомление о задержке поезда пришло на телефон",
        "обратный поезд отходит в шесть тридцать",
        "посмотреть расписание поездов до аэропорта",
        "к вечернему поезду добавили вагоны",
        "сводить детей посмотреть на паровоз",
        "новый маршрут соединяет пригород с центром",
        # typos
        "поезд опздал на двадцать минуь",
        "проверит расписние поездов",
        "забронировть билет на поезд",
        "купит месячный проездно на поезд",
        "экспрес пропускает три остановик",
    ],
    new_de=[
        # keywords (~18)
        "Schnellzug",
        "Pendler",
        "Lokomotive",
        "Schiene",
        "Eisenbahn",
        "U-Bahn",
        "Zug",
        "Pendeln",
        "Expresszug",
        "S-Bahn",
        "Personenzug",
        "Güterzug",
        "Hochgeschwindigkeitszug",
        "Bahnhof",
        "Bahnsteig",
        "Zugfahrplan",
        "Bahnpass",
        "Zugticket",
        # phrases
        "den Zug um acht Uhr morgens erwischen",
        "eine Monatskarte für den Zug kaufen",
        "den Zugfahrplan auf Verspätungen prüfen",
        "der Zug hatte heute zwanzig Minuten Verspätung",
        "morgen den Zug statt das Auto nehmen",
        "ein Zugticket für das Wochenende buchen",
        "die Kinder am Bahnhof abholen",
        "der Expresszug überspringt drei Haltestellen",
        "der Pendlerzug ist in der Stoßzeit überfüllt",
        "mit dem Schnellzug von Berlin nach München fahren",
        "Güterzug blockiert wieder den Bahnübergang",
        "auf den nächsten Zug am Bahnsteig zwei warten",
        "die U-Bahn kommt alle fünf Minuten",
        "den letzten Zug nach Hause verpasst",
        "neue Hochgeschwindigkeitsstrecke eröffnet nächstes Jahr",
        "der Schaffner hat unsere Fahrkarten kontrolliert",
        "an der nächsten Station in die rote Linie umsteigen",
        "das Zughorn hat mich letzte Nacht geweckt",
        "einen Bahnpass für die Europareise kaufen",
        "Zug in der Nähe des Hauptbahnhofs entgleist",
        "der morgendliche Pendlerzug ist immer voll",
        "einen Platz im Nachtzug finden",
        "Zug kommt in zehn Minuten auf Gleis drei an",
        "die Lokomotive muss im Depot gewartet werden",
        "die U-Bahn war heute außer Betrieb",
        "einen Ruhewagen im Zug reservieren",
        "Verspätungsmeldung kam auf dem Handy",
        "der Rückzug fährt um halb sieben",
        "Zugverbindungen zum Flughafen nachschauen",
        "zum Abendzug wurden Wagen hinzugefügt",
        "die Kinder die Dampflokomotive anschauen lassen",
        "neue Zugstrecke verbindet Vorort mit Innenstadt",
        # typos
        "den Zug um ahct Uhr erwischen",
        "Zugfahrpaln auf Verspätungen prüfen",
        "ein Zugtikect für das Wochenende buchen",
        "der Pendlerzgu ist überfüllt",
        "Zugverbindunegn zum Flughafen nachschauen",
        "der Schafnfer hat Fahrkarten kontrolliert",
        "die U-Bhan kommt alle fünf Minuten",
        "eine Monatskarte für den Zgu kaufen",
    ],
    new_ja=[
        # keywords (~18)
        "新幹線",
        "通勤",
        "機関車",
        "線路",
        "鉄道",
        "地下鉄",
        "電車",
        "通勤電車",
        "急行",
        "車両",
        "旅客列車",
        "貨物列車",
        "高速鉄道",
        "駅",
        "ホーム",
        "時刻表",
        "鉄道パス",
        "乗車券",
        # phrases
        "朝8時の電車に乗る",
        "月間の電車定期券を買う",
        "電車の遅延を時刻表で確認する",
        "今日電車が20分遅れた",
        "明日は車ではなく電車で行く",
        "週末の電車の切符を予約する",
        "駅で子供たちを迎えに行く",
        "急行電車は三つの駅を飛ばす",
        "通勤電車はラッシュ時に満員だ",
        "新幹線で東京から大阪まで乗る",
        "貨物列車がまた踏切を塞いでいる",
        "2番ホームで次の電車を待つ",
        "地下鉄は5分おきに来る",
        "終電に乗り遅れた",
        "新しい高速鉄道路線が来年開通する",
        "車掌が切符を確認した",
        "次の駅で赤い路線に乗り換える",
        "電車の警笛で昨夜目が覚めた",
        "ヨーロッパ旅行用の鉄道パスを買う",
        "朝の通勤電車はいつも混んでいる",
        "夜行列車で席を見つける",
        "電車が10分後に3番ホームに到着する",
        "機関車を車庫で整備する必要がある",
        "今日は地下鉄が運休だった",
        "電車の静かな車両を予約する",
        "電車遅延の通知がスマホに届いた",
        "帰りの電車は6時半に出る",
        "空港への電車の接続を調べる",
        "夕方の電車に車両が追加された",
        "子供たちを蒸気機関車を見に連れて行く",
        "新しい路線が郊外と都心を結ぶ",
        # typos
        "朝8時のでんしゃに乗る",
        "電車のちえんを確認する",
        "週末の電車のきっぷを予約する",
        "通勤でんしゃはラッシュ時に満員",
        "駅でこどもたちを迎えにいく",
        "終電にのりおくれた",
        "地下鉄は5ふんおきに来る",
        "電車が20ぷん遅れた",
    ],
    new_fr=[
        # keywords (~18)
        "TGV",
        "banlieue",
        "locomotive",
        "rail",
        "chemin de fer",
        "métro",
        "train",
        "navette",
        "express",
        "wagon",
        "train de voyageurs",
        "train de marchandises",
        "grande vitesse",
        "gare",
        "quai",
        "horaire de train",
        "pass ferroviaire",
        "billet de train",
        # phrases
        "attraper le train de huit heures",
        "acheter un abonnement mensuel de train",
        "vérifier les retards sur les horaires de train",
        "le train avait vingt minutes de retard aujourd'hui",
        "prendre le train au lieu de la voiture demain",
        "réserver un billet de train pour le week-end",
        "aller chercher les enfants à la gare",
        "le train express saute trois arrêts",
        "le train de banlieue est bondé aux heures de pointe",
        "prendre le TGV de Paris à Lyon",
        "un train de marchandises bloque le passage à niveau",
        "attendre le prochain train sur le quai deux",
        "le métro passe toutes les cinq minutes",
        "j'ai raté le dernier train pour rentrer",
        "nouvelle ligne à grande vitesse ouvre l'an prochain",
        "le contrôleur a vérifié nos billets",
        "changer pour la ligne rouge à la prochaine station",
        "le klaxon du train m'a réveillé cette nuit",
        "acheter un pass ferroviaire pour le voyage en Europe",
        "le train du matin est toujours bondé",
        "trouver une place dans le train de nuit",
        "le train arrive quai trois dans dix minutes",
        "la locomotive doit être révisée au dépôt",
        "le métro était hors service aujourd'hui",
        "réserver un wagon silencieux dans le train",
        "notification de retard de train sur mon téléphone",
        "le train de retour part à dix-huit heures trente",
        "chercher les correspondances de train pour l'aéroport",
        "des wagons ont été ajoutés au train du soir",
        "emmener les enfants voir la locomotive à vapeur",
        "nouvelle ligne de train relie la banlieue au centre",
        # typos
        "attraper le trian de huit heures",
        "vérifier les retadrs sur les horaires",
        "réserver un bilet de train pour le week-end",
        "le train de banlieue est bodné aux heures de pointe",
        "trouver une palce dans le train de nuit",
        "le contrôluer a vérifié nos billets",
        "acheter un abonnement menusle de train",
        "le klaxon du train m'a révillé cette nuit",
    ],
    new_es=[
        # keywords (~18)
        "tren bala",
        "cercanías",
        "locomotora",
        "riel",
        "ferrocarril",
        "metro",
        "tren",
        "viajero",
        "tren expreso",
        "vagón",
        "tren de pasajeros",
        "tren de carga",
        "alta velocidad",
        "estación",
        "andén",
        "horario de trenes",
        "pase de tren",
        "billete de tren",
        # phrases
        "tomar el tren de las ocho de la mañana",
        "comprar un abono mensual de tren",
        "revisar el horario de trenes por retrasos",
        "el tren llegó veinte minutos tarde hoy",
        "mañana ir en tren en vez de coche",
        "reservar un billete de tren para el fin de semana",
        "recoger a los niños en la estación",
        "el tren expreso se salta tres paradas",
        "el tren de cercanías va lleno en hora punta",
        "viajar en tren bala de Madrid a Barcelona",
        "un tren de carga bloquea el cruce otra vez",
        "esperar el siguiente tren en el andén dos",
        "el metro pasa cada cinco minutos",
        "perdí el último tren a casa",
        "nueva línea de alta velocidad abre el año que viene",
        "el revisor comprobó nuestros billetes",
        "hacer transbordo a la línea roja en la siguiente estación",
        "la bocina del tren me despertó anoche",
        "comprar un pase de tren para el viaje por Europa",
        "el tren de la mañana siempre va lleno",
        "encontrar asiento en el tren nocturno",
        "el tren llega al andén tres en diez minutos",
        "la locomotora necesita mantenimiento en el depósito",
        "el metro estuvo fuera de servicio hoy",
        "reservar un vagón silencioso en el tren",
        "notificación de retraso del tren en mi teléfono",
        "el tren de vuelta sale a las seis y media",
        "buscar conexiones de tren al aeropuerto",
        "se añadieron vagones al tren de la tarde",
        "llevar a los niños a ver la locomotora de vapor",
        "nueva ruta de tren conecta el suburbio con el centro",
        # typos
        "tomar el tren de las ohco de la mañana",
        "reviasr el horario de trenes",
        "reservar un billete de tren para el fni de semana",
        "el tren de cercanísa va lleno",
        "encontrar asient en el tren nocturno",
        "la bocnia del tren me despertó anoche",
        "buscar conecxiones de tren al aeropuerto",
        "comprar un abono menusal de tren",
    ],
)

# ── 3. transmission ──────────────────────────────────────────────────────────
ok &= clean_and_expand("transmission",
    remove_en_texts=[
        # visual / devspeak
        "transmission icon for a car service app",
        "automatic transmission cross-section diagram",
        "transmission fluid service reminder icon",
        "drivetrain diagram showing gearbox and axle",
        "drivetrain diagram for a mechanics course",
        "gear shifter inside the center console",
    ],
    remove_ru_texts=[
        # mixed EN
        "жидкость transmission checked on dipstick",
        "иконка напоминания о сервисе transmission fluid",
        "шестиступенчатая механика в sports car",
        "warning light трансмиссии на приборной панели",
        "механическая transmission включена на вторую передачу",
        "иконка трансмиссии для приложения автосервиса",
        # boundary (not transmission-specific)
        "руль как элемент управления в салоне",
        "двигатель под капотом автомобиля",
        "педаль тормоза для остановки машины",
        "спидометр показывает текущую скорость",
        "гаечный ключ для ремонта у механика",
        "приборная панель автомобиля с датчиками",
        # devspeak
        "схема трансмиссии для курса механики",
        "схема трансмиссии показывает коробку и ось",
    ],
    new_en=[
        # keywords (~18)
        "auto",
        "car",
        "engine",
        "gearbox",
        "manual",
        "shifting",
        "stick shift",
        "transmission",
        "automatic",
        "torque converter",
        "gear ratio",
        "transmission fluid",
        "CVT",
        "differential",
        # phrases
        "take the car to the shop for a transmission check",
        "the transmission is slipping in third gear",
        "change the transmission fluid this weekend",
        "mechanic says the gearbox needs rebuilding",
        "clutch feels spongy when pressing the pedal",
        "manual transmission makes the drive more fun",
        "automatic transmission service is overdue",
        "get a quote for the transmission repair",
        "the car jerks when the transmission shifts",
        "stick shift is hard to move in cold weather",
        "check the transmission dipstick after the oil change",
        "the drivetrain is making a strange noise",
        "replace the torque converter next service visit",
        "CVT transmission whines at low speed",
        "the gear ratio is too high for city driving",
        "transmission warning light came on during the commute",
        "differential fluid needs changing at 60k miles",
        "learn to drive a manual transmission this summer",
        "the shifter cable snapped on the highway",
        "rebuild the transmission or buy a new one",
        "fluid leak under the car from the transmission",
        "schedule transmission service at the dealership",
        "the five-speed manual is more efficient",
        "gear grinding noise when shifting to second",
        "test drove the car and the transmission was smooth",
        "the old truck has a four-speed manual",
        "transmission flush costs more than a fluid change",
        "overdrive gear helps with highway fuel economy",
        "the car needs a new clutch and flywheel",
        "automatic is easier but manual is more engaging",
        "the transmission was the most expensive repair",
        "get the transmission inspected before the road trip",
        # typos
        "transmision fluid needs changin",
        "the clutch feeld spongy when pressing",
        "gearbox needs rebilding says the mechanic",
        "shedule transmission service at dealer",
        "the shiftr cable snappd on the highway",
    ],
    new_ru=[
        # keywords (~18)
        "машина",
        "двигатель",
        "коробка передач",
        "механика",
        "переключение",
        "ручная коробка",
        "трансмиссия",
        "автомат",
        "гидротрансформатор",
        "передаточное число",
        "жидкость трансмиссии",
        "вариатор",
        "дифференциал",
        # phrases
        "отвезти машину на проверку трансмиссии",
        "трансмиссия проскальзывает на третьей передаче",
        "поменять жидкость трансмиссии в эти выходные",
        "механик говорит что коробку нужно перебрать",
        "сцепление стало мягким при нажатии на педаль",
        "на ручной коробке ездить веселее",
        "пора обслужить автоматическую коробку",
        "узнать стоимость ремонта трансмиссии",
        "машина дёргается при переключении передач",
        "ручку передач тяжело двигать в мороз",
        "проверить щуп трансмиссии после замены масла",
        "привод издаёт странный звук",
        "заменить гидротрансформатор на следующем ТО",
        "вариатор гудит на малой скорости",
        "передаточное число слишком высокое для города",
        "загорелась лампа трансмиссии по дороге на работу",
        "жидкость дифференциала нужно менять на 100 тысячах",
        "научиться водить на механике этим летом",
        "трос переключения передач порвался на трассе",
        "перебрать трансмиссию или купить новую",
        "подтёк жидкости под машиной от трансмиссии",
        "записаться на обслуживание трансмиссии в сервис",
        "пятиступенчатая механика экономичнее",
        "скрежет при переключении на вторую передачу",
        "на тест-драйве трансмиссия работала плавно",
        "у старого грузовика четырёхступенчатая механика",
        "промывка трансмиссии дороже замены жидкости",
        "повышенная передача помогает экономить топливо на трассе",
        "машине нужны новое сцепление и маховик",
        "автомат проще но механика интереснее",
        "ремонт трансмиссии оказался самым дорогим",
        "проверить трансмиссию перед дальней поездкой",
        "переключить с паркинга на драйв перед выездом",
        # typos
        "поменят жидкость трансмисии",
        "механик говорти что коробку нужно перебрат",
        "сцепление стлао мягким при нажатии",
        "проверит щуп трнасмиссии после замены",
        "загорелас лампа трансмисии на дороге",
    ],
    new_de=[
        # keywords (~18)
        "Auto",
        "Wagen",
        "Motor",
        "Getriebe",
        "Schaltgetriebe",
        "Schalten",
        "Schaltknüppel",
        "Antriebsstrang",
        "Kupplung",
        "Antrieb",
        "Gang",
        "Schalthebel",
        "Automatik",
        "Drehmomentwandler",
        "Übersetzungsverhältnis",
        "Getriebeöl",
        "CVT",
        "Differential",
        # phrases
        "Auto zur Getriebekontrolle in die Werkstatt bringen",
        "das Getriebe rutscht im dritten Gang",
        "Getriebeöl am Wochenende wechseln",
        "Mechaniker sagt das Getriebe muss überholt werden",
        "die Kupplung fühlt sich schwammig an",
        "Schaltgetriebe macht das Fahren spaßiger",
        "Automatikgetriebe-Service ist überfällig",
        "Angebot für die Getriebereparatur einholen",
        "das Auto ruckt beim Gangwechsel",
        "Schaltknüppel lässt sich bei Kälte schwer bewegen",
        "Getriebe-Ölstand nach dem Ölwechsel prüfen",
        "der Antriebsstrang macht ein seltsames Geräusch",
        "Drehmomentwandler beim nächsten Service ersetzen",
        "CVT-Getriebe heult bei niedriger Geschwindigkeit",
        "Übersetzung zu hoch für den Stadtverkehr",
        "Getriebewarnleuchte ging auf dem Weg zur Arbeit an",
        "Differentialöl bei 100000 km wechseln",
        "diesen Sommer Schaltgetriebe fahren lernen",
        "Schaltzug auf der Autobahn gerissen",
        "Getriebe überholen oder neues kaufen",
        "Flüssigkeitsleck unter dem Auto vom Getriebe",
        "Getriebe-Service beim Händler einplanen",
        "der Fünfgang-Schalter ist effizienter",
        "Schleifgeräusch beim Schalten in den zweiten Gang",
        "Probefahrt gemacht und das Getriebe lief geschmeidig",
        "der alte Lkw hat ein Viergang-Schaltgetriebe",
        "Getriebespülung kostet mehr als Ölwechsel",
        "Overdrive-Gang hilft beim Spritsparen auf der Autobahn",
        "das Auto braucht neue Kupplung und Schwungrad",
        "Automatik ist einfacher aber Schalten macht mehr Spaß",
        "Getriebereparatur war die teuerste Reparatur",
        "Getriebe vor der langen Reise prüfen lassen",
        # typos
        "Getriebeöl am Wochennde wechseln",
        "das Getriebe rutscht im dritten Gng",
        "Schalknüppel lässt sich schwer bewegen",
        "Getriebewarnleuche ging an",
        "Probefahrt gemahct und Getriebe lief gut",
        "Automatikgetriebe-Servie ist überfällig",
        "Angebot für die Getriebereparatru einholen",
        "der Antriebsstrang mahct ein seltsames Geräusch",
    ],
    new_ja=[
        # keywords (~18)
        "車",
        "自動車",
        "エンジン",
        "ギアボックス",
        "マニュアル",
        "シフト",
        "シフトレバー",
        "トランスミッション",
        "クラッチ",
        "駆動系",
        "ギア",
        "変速機",
        "オートマ",
        "トルクコンバーター",
        "ギア比",
        "ミッションオイル",
        "CVT",
        "デフ",
        # phrases
        "トランスミッションの点検に車を持っていく",
        "3速でトランスミッションが滑る",
        "今週末にミッションオイルを交換する",
        "整備士がギアボックスの修理が必要と言った",
        "クラッチペダルがふわふわする",
        "マニュアル車の方が運転が楽しい",
        "オートマのメンテナンス時期が過ぎている",
        "トランスミッション修理の見積もりをもらう",
        "ギアチェンジの時に車がガクガクする",
        "寒いとシフトレバーが硬くなる",
        "オイル交換後にミッションの油量を確認する",
        "駆動系から変な音がする",
        "次の点検でトルクコンバーターを交換する",
        "CVTが低速で唸る",
        "ギア比が街乗りには高すぎる",
        "通勤中にトランスミッション警告灯が点いた",
        "10万キロでデフオイルを交換する",
        "今年の夏にマニュアル車の運転を覚える",
        "高速道路でシフトケーブルが切れた",
        "トランスミッションを修理するか新品を買うか",
        "トランスミッションからオイル漏れがある",
        "ディーラーでトランスミッション整備を予約する",
        "5速マニュアルの方が燃費がいい",
        "2速に入れる時にギアが鳴る",
        "試乗したらトランスミッションがスムーズだった",
        "古いトラックは4速マニュアルだ",
        "ミッションの洗浄はオイル交換より高い",
        "オーバードライブギアで高速の燃費が良くなる",
        "車に新しいクラッチとフライホイールが必要",
        "オートマは楽だがマニュアルは楽しい",
        "トランスミッション修理が一番高かった",
        "遠出の前にトランスミッションを点検してもらう",
        # typos
        "とらんすみっしょんの点検に車を持っていく",
        "3速でぎあが滑る",
        "今週末にみっしょんオイルを交換する",
        "クラッチペダルがふあふあする",
        "通勤中にとらんすみっしょん警告灯が点いた",
        "整備士がぎあぼっくすの修理が必要と言った",
        "しふとレバーが硬くなる",
        "でぃーらーでトランスミッション整備を予約",
    ],
    new_fr=[
        # keywords (~18)
        "auto",
        "voiture",
        "moteur",
        "boîte de vitesses",
        "manuelle",
        "passage de vitesses",
        "levier de vitesses",
        "transmission",
        "embrayage",
        "groupe motopropulseur",
        "vitesse",
        "sélecteur",
        "automatique",
        "convertisseur de couple",
        "rapport de transmission",
        "huile de boîte",
        "CVT",
        "différentiel",
        # phrases
        "amener la voiture au garage pour vérifier la boîte",
        "la transmission patine en troisième",
        "changer l'huile de boîte ce week-end",
        "le mécanicien dit que la boîte doit être refaite",
        "l'embrayage est mou quand on appuie sur la pédale",
        "la boîte manuelle rend la conduite plus amusante",
        "le service de la boîte automatique est en retard",
        "demander un devis pour la réparation de la boîte",
        "la voiture saccade quand la boîte change de vitesse",
        "le levier de vitesses est dur par temps froid",
        "vérifier le niveau d'huile de boîte après la vidange",
        "le groupe motopropulseur fait un bruit étrange",
        "remplacer le convertisseur de couple au prochain service",
        "la boîte CVT gémit à basse vitesse",
        "le rapport est trop élevé pour la ville",
        "le voyant de transmission s'est allumé en route",
        "changer l'huile du différentiel à 100000 km",
        "apprendre à conduire en boîte manuelle cet été",
        "le câble de sélecteur a cassé sur l'autoroute",
        "refaire la boîte ou en acheter une neuve",
        "fuite de liquide sous la voiture venant de la boîte",
        "prendre rendez-vous pour le service de transmission",
        "la boîte cinq vitesses est plus économique",
        "bruit de craquement en passant la deuxième",
        "essai routier et la boîte était souple",
        "le vieux camion a une boîte quatre vitesses",
        "la purge de boîte coûte plus cher que la vidange",
        "le rapport de surmultiplication aide sur autoroute",
        "la voiture a besoin d'un nouvel embrayage et volant moteur",
        "l'automatique est plus simple mais la manuelle plus fun",
        "la réparation de la boîte était la plus chère",
        "faire vérifier la transmission avant le grand voyage",
        # typos
        "changer l'huile de boîte ce week-ned",
        "la transmission paitne en troisième",
        "le levier de vitesses est dru par temps froid",
        "le voyant de transmisson s'est allumé",
        "demander un devsi pour la réparation",
        "l'embrayage est muo quand on appuie",
        "le câble de sélcteur a cassé",
        "la boîte cinq vitsses est plus économique",
    ],
    new_es=[
        # keywords (~18)
        "auto",
        "coche",
        "motor",
        "caja de cambios",
        "manual",
        "cambio de marcha",
        "palanca de cambios",
        "transmisión",
        "embrague",
        "tren motriz",
        "marcha",
        "selector",
        "automático",
        "convertidor de par",
        "relación de transmisión",
        "aceite de transmisión",
        "CVT",
        "diferencial",
        # phrases
        "llevar el coche al taller para revisar la transmisión",
        "la transmisión patina en tercera",
        "cambiar el aceite de transmisión este fin de semana",
        "el mecánico dice que la caja necesita reparación",
        "el embrague se siente esponjoso al pisar el pedal",
        "la caja manual hace la conducción más divertida",
        "el servicio de la caja automática está atrasado",
        "pedir presupuesto para la reparación de transmisión",
        "el coche da tirones al cambiar de marcha",
        "la palanca de cambios cuesta mover con el frío",
        "revisar el nivel de aceite de transmisión tras el cambio",
        "el tren motriz hace un ruido extraño",
        "cambiar el convertidor de par en el próximo servicio",
        "la transmisión CVT zumba a baja velocidad",
        "la relación de marcha es muy alta para la ciudad",
        "se encendió la luz de transmisión camino al trabajo",
        "cambiar el aceite del diferencial a los 100 mil km",
        "aprender a conducir con caja manual este verano",
        "el cable del selector se rompió en la autopista",
        "reparar la transmisión o comprar una nueva",
        "fuga de líquido bajo el coche por la transmisión",
        "agendar servicio de transmisión en el concesionario",
        "la caja de cinco velocidades es más eficiente",
        "ruido de raspado al meter segunda",
        "en la prueba de manejo la transmisión iba suave",
        "la camioneta vieja tiene caja de cuatro velocidades",
        "el lavado de transmisión cuesta más que el cambio de aceite",
        "la sobremarcha ayuda a ahorrar en carretera",
        "el coche necesita embrague y volante de inercia nuevos",
        "el automático es más fácil pero el manual más entretenido",
        "la reparación de la transmisión fue la más cara",
        "revisar la transmisión antes del viaje largo",
        # typos
        "cambiar el aceite de transmisón este fin de semana",
        "la transmisión paitna en tercera",
        "la palanca de camibos cuesta mover",
        "se encendió la lzu de transmisión",
        "pedir presupuetso para la reparación",
        "el mecáncio dice que la caja necesita reparación",
        "el embrague se siente esponjso al pisar",
        "agendar servico de transmisión en el concesionario",
    ],
)

# ── 4. tree ───────────────────────────────────────────────────────────────────
ok &= clean_and_expand("tree",
    remove_en_texts=[
        # visual / devspeak
        "classic evergreen tree silhouette for nature",
        "flora icon for a nature identification app",
        "nature icon featuring a tall green tree",
        "nature walk icon in an outdoor activity app",
        "tree icon for a gardening or plant care app",
        "seasonal nature icon for a calendar app",
        "lone tree on a hilltop at sunset",
        "single tree with a round leafy canopy on top",
        "nature and environment icon for an eco app",
        "park or outdoor icon in a maps or travel app",
        "simple tree silhouette with a triangular crown",
        "green icon representing sustainability in an app",
        "leafy deciduous tree in full summer bloom",
        "tall tree with a full leafy canopy",
        "tall oak tree with a wide spreading canopy",
    ],
    remove_ru_texts=[
        # visual / devspeak / mixed EN
        "классический силуэт evergreen tree для природы",
        "иконка флоры для nature identification app",
        "иконка природы с высоким зеленым деревом",
        "иконка прогулки в outdoor activity app",
        "иконка дерева для gardening or plant care app",
        "иконка сезонной природы для calendar app",
        "одинокое дерево на холме на закате",
        "одиночное дерево с круглой лиственной кроной",
        "иконка природы и экологии для eco app",
        "иконка парка для maps or travel app",
        "простой силуэт дерева с треугольной кроной",
        "зеленая иконка устойчивого развития в приложении",
        "лиственное дерево в полном летнем цвете",
        "высокое дерево с густой кроной",
        "высокий дуб с широкой раскидистой кроной",
        # boundary (bushes, palms - wrong icon)
        "низкий округлый куст в саду",
        "цветущий куст вдоль дорожки",
        "высокая пальма на тропическом пляже",
        "кокосовая пальма склоняется над волнами",
        # visual
        "текстура коры на стволе высокого дуба",
    ],
    new_en=[
        # keywords (~18)
        "bark",
        "fall",
        "flora",
        "forest",
        "nature",
        "oak",
        "seasonal",
        "tree",
        "wood",
        "evergreen",
        "arborist",
        "sapling",
        "roots",
        "canopy",
        "lumber",
        "pine",
        "maple",
        "orchard",
        # phrases
        "plant a tree in the backyard this spring",
        "trim the tree branches before the storm",
        "call the arborist for the sick oak tree",
        "rake the fall leaves from under the tree",
        "buy a Christmas tree this weekend",
        "the tree in the front yard needs watering",
        "check if the tree roots are damaging the sidewalk",
        "plant three new saplings along the driveway",
        "the old tree was struck by lightning last night",
        "schedule tree removal for the dead elm",
        "the forest trail is beautiful in autumn",
        "pick up firewood from the fallen tree",
        "put mulch around the base of the tree",
        "the pine tree drops needles all over the deck",
        "maple tree sap is running in early spring",
        "prune the fruit trees in the orchard",
        "the oak tree is over a hundred years old",
        "plant an evergreen for year-round shade",
        "tree pollen is terrible this allergy season",
        "wrap the tree trunk to protect from deer",
        "the tree canopy blocks too much sunlight",
        "hire someone to cut down the dead tree",
        "water the new tree daily for the first month",
        "buy fertilizer for the fruit trees",
        "the lumber from the fallen tree can be reused",
        "check the bark for signs of disease",
        "tie the sapling to a stake so it grows straight",
        "the tree grew taller than the house",
        "take the kids to the nature trail in the forest",
        "seasonal allergies are worse near the birch trees",
        # typos
        "plnat a tree in the backyard this spring",
        "trmm the tree branches befroe the storm",
        "tre in the front yard needs watring",
        "chekc if the tree rots are damaging the sidewlk",
        "schedule trea removal for the dead elm",
    ],
    new_ru=[
        # keywords (~18)
        "кора",
        "осень",
        "флора",
        "лес",
        "природа",
        "дуб",
        "сезонный",
        "дерево",
        "древесина",
        "хвойное",
        "арборист",
        "саженец",
        "корни",
        "крона",
        "пиломатериалы",
        "сосна",
        "клён",
        "сад",
        # phrases
        "посадить дерево во дворе этой весной",
        "обрезать ветки дерева перед штормом",
        "вызвать арбориста для больного дуба",
        "убрать опавшие листья из-под дерева",
        "купить ёлку на эти выходные",
        "дерево перед домом нужно полить",
        "проверить не повреждают ли корни тротуар",
        "посадить три саженца вдоль подъездной дорожки",
        "старое дерево прошлой ночью ударила молния",
        "запланировать удаление засохшего вяза",
        "лесная тропа особенно красива осенью",
        "набрать дров от упавшего дерева",
        "положить мульчу вокруг ствола дерева",
        "сосна роняет иголки по всей террасе",
        "у клёна начался сокоход ранней весной",
        "обрезать фруктовые деревья в саду",
        "этому дубу больше ста лет",
        "посадить хвойное дерево для круглогодичной тени",
        "пыльца деревьев ужасная в сезон аллергии",
        "обернуть ствол дерева для защиты от оленей",
        "крона дерева блокирует слишком много света",
        "нанять кого-нибудь спилить засохшее дерево",
        "поливать новое дерево каждый день первый месяц",
        "купить удобрение для фруктовых деревьев",
        "древесину от упавшего дерева можно использовать",
        "проверить кору на признаки болезни",
        "привязать саженец к колышку чтобы рос прямо",
        "дерево выросло выше дома",
        "сводить детей на природную тропу в лесу",
        "сезонная аллергия хуже рядом с берёзами",
        # typos
        "посадит дерево во двре этой весной",
        "обрзать ветки дерева перед штормом",
        "дерево перде домом нужно полит",
        "проверит не повреждают ли корни тратуар",
        "купит ёлку на эти выходнеы",
    ],
    new_de=[
        # keywords (~18)
        "Rinde",
        "Herbst",
        "Flora",
        "Wald",
        "Natur",
        "Eiche",
        "saisonal",
        "Baum",
        "Holz",
        "Nadelbaum",
        "Baumpfleger",
        "Setzling",
        "Wurzeln",
        "Baumkrone",
        "Holzfäller",
        "Kiefer",
        "Ahorn",
        "Obstgarten",
        # phrases
        "diesen Frühling einen Baum im Garten pflanzen",
        "Äste vor dem Sturm zurückschneiden",
        "den Baumpfleger für die kranke Eiche rufen",
        "Herbstlaub unter dem Baum zusammenharken",
        "am Wochenende einen Weihnachtsbaum kaufen",
        "der Baum im Vorgarten muss gegossen werden",
        "prüfen ob die Wurzeln den Gehweg beschädigen",
        "drei neue Setzlinge entlang der Einfahrt pflanzen",
        "der alte Baum wurde letzte Nacht vom Blitz getroffen",
        "Baumfällung für die tote Ulme planen",
        "der Waldweg ist im Herbst wunderschön",
        "Brennholz vom umgestürzten Baum sammeln",
        "Mulch um den Baumstamm legen",
        "die Kiefer verliert Nadeln auf der Terrasse",
        "der Ahorn hat im Frühling Saftfluss",
        "Obstbäume im Garten beschneiden",
        "die Eiche ist über hundert Jahre alt",
        "einen Nadelbaum für ganzjährigen Schatten pflanzen",
        "Baumpollen sind schrecklich in der Allergiesaison",
        "den Baumstamm zum Schutz vor Rehen umwickeln",
        "die Baumkrone blockiert zu viel Sonnenlicht",
        "jemanden beauftragen den toten Baum zu fällen",
        "den neuen Baum den ersten Monat täglich gießen",
        "Dünger für die Obstbäume kaufen",
        "das Holz vom umgestürzten Baum wiederverwenden",
        "die Rinde auf Krankheitszeichen untersuchen",
        "den Setzling an einen Pfahl binden",
        "der Baum ist höher als das Haus gewachsen",
        "die Kinder zum Naturpfad im Wald mitnehmen",
        "saisonale Allergien sind bei Birken schlimmer",
        "den morschen Ast vor dem Winter absägen",
        "Baumschule besuchen und neue Setzlinge aussuchen",
        # typos
        "diesen Frühling einen Baum im Graten pflanzen",
        "Äste vor dem Strum zurückschneiden",
        "den Baumpfleger für die krnake Eiche rufen",
        "am Wochennde einen Weihnachtsbaum kaufen",
        "der Baum im Vorgarten muss geogssen werden",
        "Brennholz vom umgestürzten Buam sammeln",
        "Mulch um den Baumstamm lgeen",
        "die Kiefer verliert Nadlen auf der Terrasse",
    ],
    new_ja=[
        # keywords (~18)
        "樹皮",
        "紅葉",
        "植物",
        "森",
        "自然",
        "オーク",
        "季節",
        "木",
        "木材",
        "常緑樹",
        "樹木医",
        "苗木",
        "根",
        "樹冠",
        "材木",
        "松",
        "楓",
        "果樹園",
        # phrases
        "今年の春に庭に木を植える",
        "嵐の前に木の枝を剪定する",
        "病気のオークの木に樹木医を呼ぶ",
        "木の下の落ち葉を掃く",
        "今週末にクリスマスツリーを買う",
        "前庭の木に水をやる必要がある",
        "根が歩道を傷めていないか確認する",
        "私道沿いに苗木を三本植える",
        "昨夜古い木に雷が落ちた",
        "枯れたニレの木の伐採を予約する",
        "秋の森の小道は美しい",
        "倒れた木から薪を集める",
        "木の根元にマルチを敷く",
        "松の木がデッキ中に針を落とす",
        "早春に楓の樹液が流れ始めた",
        "果樹園の果樹を剪定する",
        "あのオークの木は樹齢百年以上だ",
        "一年中日陰のために常緑樹を植える",
        "花粉の季節で木の花粉がひどい",
        "鹿から守るために木の幹を巻く",
        "木の樹冠が日光を遮りすぎている",
        "枯れた木を切り倒す人を雇う",
        "最初の一か月は毎日新しい木に水をやる",
        "果樹用の肥料を買う",
        "倒れた木の材木を再利用できる",
        "樹皮に病気の兆候がないか調べる",
        "苗木を支柱に結んでまっすぐ育てる",
        "木が家より高く育った",
        "子供たちを森の自然散策に連れて行く",
        "白樺の近くでは季節の花粉症がひどい",
        "冬の前に腐った枝を切る",
        "苗木屋を訪れて新しい木を選ぶ",
        # typos
        "今年の春ににわに木を植える",
        "嵐のまえに木のえだを剪定する",
        "前庭のきに水をやる必要がある",
        "枯れたニレのきの伐採を予約する",
        "倒れた木からまきを集める",
        "松のきがデッキ中に針を落とす",
        "果樹園のかじゅを剪定する",
        "あのオークの木はじゅれい百年以上だ",
    ],
    new_fr=[
        # keywords (~18)
        "écorce",
        "automne",
        "flore",
        "forêt",
        "nature",
        "chêne",
        "saisonnier",
        "arbre",
        "bois",
        "conifère",
        "arboriste",
        "jeune plant",
        "racines",
        "canopée",
        "bois de charpente",
        "pin",
        "érable",
        "verger",
        # phrases
        "planter un arbre dans le jardin ce printemps",
        "tailler les branches avant la tempête",
        "appeler l'arboriste pour le chêne malade",
        "ratisser les feuilles mortes sous l'arbre",
        "acheter un sapin de Noël ce week-end",
        "l'arbre devant la maison a besoin d'eau",
        "vérifier si les racines endommagent le trottoir",
        "planter trois jeunes plants le long de l'allée",
        "le vieil arbre a été frappé par la foudre cette nuit",
        "planifier l'abattage de l'orme mort",
        "le sentier forestier est magnifique en automne",
        "ramasser du bois de chauffage de l'arbre tombé",
        "mettre du paillis autour du tronc de l'arbre",
        "le pin laisse tomber des aiguilles sur la terrasse",
        "la sève de l'érable coule au début du printemps",
        "tailler les arbres fruitiers dans le verger",
        "le chêne a plus de cent ans",
        "planter un conifère pour de l'ombre toute l'année",
        "le pollen des arbres est terrible cette saison",
        "envelopper le tronc pour protéger des cerfs",
        "la canopée de l'arbre bloque trop de lumière",
        "engager quelqu'un pour abattre l'arbre mort",
        "arroser le nouvel arbre tous les jours le premier mois",
        "acheter de l'engrais pour les arbres fruitiers",
        "le bois de l'arbre tombé peut être réutilisé",
        "vérifier l'écorce pour des signes de maladie",
        "attacher le jeune plant à un tuteur",
        "l'arbre a poussé plus haut que la maison",
        "emmener les enfants au sentier nature en forêt",
        "les allergies saisonnières sont pires près des bouleaux",
        "scier la branche pourrie avant l'hiver",
        "visiter la pépinière et choisir de nouveaux plants",
        # typos
        "planter un arber dans le jardin ce printemps",
        "tailler les branhces avant la tempête",
        "appeler l'arboriste pour le chêen malade",
        "acheter un sapni de Noël ce week-end",
        "l'arbre devant la maiosn a besoin d'eau",
        "ratisser les feuiles mortes sous l'arbre",
        "le sentier foretsier est magnifique en automne",
        "mettre du paillis autoru du tronc",
    ],
    new_es=[
        # keywords (~18)
        "corteza",
        "otoño",
        "flora",
        "bosque",
        "naturaleza",
        "roble",
        "estacional",
        "árbol",
        "madera",
        "árbol perenne",
        "arborista",
        "plántula",
        "raíces",
        "copa",
        "leña",
        "pino",
        "arce",
        "huerto",
        # phrases
        "plantar un árbol en el jardín esta primavera",
        "podar las ramas del árbol antes de la tormenta",
        "llamar al arborista por el roble enfermo",
        "barrer las hojas caídas debajo del árbol",
        "comprar un árbol de Navidad este fin de semana",
        "el árbol del jardín necesita riego",
        "comprobar si las raíces dañan la acera",
        "plantar tres plántulas a lo largo de la entrada",
        "anoche un rayo cayó sobre el árbol viejo",
        "programar la tala del olmo muerto",
        "el sendero del bosque es hermoso en otoño",
        "recoger leña del árbol caído",
        "poner mantillo alrededor del tronco del árbol",
        "el pino deja caer agujas en la terraza",
        "la savia del arce empieza a correr en primavera",
        "podar los árboles frutales del huerto",
        "ese roble tiene más de cien años",
        "plantar un árbol perenne para sombra todo el año",
        "el polen de los árboles está terrible esta temporada",
        "envolver el tronco para protegerlo de los ciervos",
        "la copa del árbol bloquea demasiada luz",
        "contratar a alguien para cortar el árbol muerto",
        "regar el árbol nuevo todos los días el primer mes",
        "comprar fertilizante para los árboles frutales",
        "la madera del árbol caído se puede reutilizar",
        "revisar la corteza por señales de enfermedad",
        "atar la plántula a una estaca para que crezca recta",
        "el árbol creció más alto que la casa",
        "llevar a los niños al sendero natural del bosque",
        "las alergias estacionales son peores cerca de los abedules",
        "cortar la rama podrida antes del invierno",
        "visitar el vivero y elegir nuevas plántulas",
        # typos
        "plantar un árblo en el jardín esta primavera",
        "podar las ramsa del árbol antes de la tormenta",
        "llamar al arborista por el roble enfemro",
        "comprar un árbol de Naivdad este fin de semana",
        "el árbol del jardín necesita reigo",
        "recoger leñna del árbol caído",
        "poner mantllo alrededor del tronco",
        "el pino deja caer agujas en la terrza",
    ],
)

# ── 5. tricycle-adult ────────────────────────────────────────────────────────
ok &= clean_and_expand("tricycle-adult",
    remove_en_texts=[
        # devspeak
        "show an adult tricycle for the accessible transport",
    ],
    remove_ru_texts=[
        # boundary (wrong icon - not adult tricycle)
        "велосипед двухколёсный стандартный",
        "инвалидная коляска устройство мобильности",
        "электросамокат совместная аренда",
        "детский трёхколёсный велосипед педали",
        "квадрицикл четырёхколёсный педальный",
        "грузовой велосипед с прицепом",
    ],
    new_en=[
        # keywords (~18)
        "adult",
        "bike",
        "mobility",
        "pedal",
        "three-wheel",
        "tricycle",
        "trike",
        "adaptive",
        "cruiser",
        "recumbent",
        "cargo trike",
        "electric trike",
        "three-wheeler",
        "cycling",
        "stability",
        "basket",
        "handbrakes",
        "senior bike",
        # phrases
        "buy an adult tricycle for exercise",
        "ride the tricycle around the neighborhood",
        "the three-wheel bike is great for balance",
        "order a basket for the adult trike",
        "take the tricycle to the farmers market",
        "electric trike makes hills easier for grandma",
        "adult tricycle with rear cargo basket arrived",
        "test ride the recumbent trike at the bike shop",
        "inflate the tires on the adult tricycle",
        "get the adult trike serviced before summer",
        "park the tricycle in the garage",
        "the trike is perfect for grocery runs",
        "research adult tricycles for mobility needs",
        "the pedal assist makes the trike easier to ride",
        "adjust the seat height on the adult tricycle",
        "buy a cover for the tricycle so it stays dry",
        "the foldable trike fits in the car trunk",
        "cruise around the park on the adult trike",
        "replace the brake pads on the three-wheeler",
        "the cargo trike carries all the beach gear",
        "dad loves his new adult tricycle",
        "look for a used adult trike online",
        "adult tricycle is safer than a two-wheeler for her",
        "ride the trike along the bike path",
        "add a bell and mirror to the adult trike",
        "trike rental at the beach boardwalk",
        "the adaptive tricycle helped with rehab exercises",
        # typos
        "buy an adlut tricycle for excercise",
        "ride the triycle around the neighborhood",
        "the thre-wheel bike is great for balacne",
        "inflat the tires on the adult tricylce",
        "repalce the brake pads on the three-wheeller",
    ],
    new_ru=[
        # keywords (~18)
        "взрослый",
        "велосипед",
        "мобильность",
        "педаль",
        "трёхколёсный",
        "трицикл",
        "трайк",
        "адаптивный",
        "круизер",
        "лежачий трайк",
        "грузовой трайк",
        "электротрайк",
        "трёхколёска",
        "катание",
        "устойчивость",
        "корзина",
        "ручные тормоза",
        "велосипед для пожилых",
        # phrases
        "купить взрослый трёхколёсный велосипед для зарядки",
        "покататься на трёхколёсном по району",
        "трёхколёсный велосипед отлично подходит для баланса",
        "заказать корзину для взрослого трайка",
        "поехать на трёхколёсном на фермерский рынок",
        "электротрайк упрощает подъёмы для бабушки",
        "взрослый трёхколёсный с задней грузовой корзиной приехал",
        "попробовать лежачий трайк в веломагазине",
        "накачать шины на взрослом трёхколёсном",
        "обслужить взрослый трайк перед летом",
        "поставить трёхколёсный в гараж",
        "трайк идеально подходит для поездок за продуктами",
        "изучить взрослые трёхколёсные для нужд мобильности",
        "педальный привод облегчает езду на трайке",
        "отрегулировать высоту сиденья на взрослом трёхколёсном",
        "купить чехол для трёхколёсного чтобы не мок",
        "складной трайк помещается в багажник",
        "кататься по парку на взрослом трайке",
        "заменить тормозные колодки на трёхколёске",
        "грузовой трайк увезёт все пляжные вещи",
        "папе нравится его новый взрослый трёхколёсный",
        "поискать подержанный взрослый трайк в интернете",
        "взрослый трёхколёсный безопаснее двухколёсного для неё",
        "ехать на трайке по велодорожке",
        "добавить звонок и зеркало на взрослый трайк",
        "прокат трайков на набережной",
        "адаптивный трёхколёсный помог при реабилитации",
        # typos
        "купит взрослый трёхколёснй велосипед",
        "покататся на трёхколёсном по районну",
        "трайк идеальнo подхдит для поездок",
        "накачат шины на взрслом трёхколёсном",
        "заменит тормозные колдоки на трёхколёске",
    ],
    new_de=[
        # keywords (~18)
        "Erwachsener",
        "Fahrrad",
        "Mobilität",
        "Pedal",
        "Dreirad",
        "Trike",
        "adaptiv",
        "Cruiser",
        "Liegedreirad",
        "Lastendreirad",
        "Elektro-Dreirad",
        "Dreiräder",
        "Radfahren",
        "Stabilität",
        "Korb",
        "Handbremsen",
        "Seniorenfahrrad",
        "Dreirad für Erwachsene",
        # phrases
        "ein Dreirad für Erwachsene zum Training kaufen",
        "mit dem Dreirad durch die Nachbarschaft fahren",
        "das Dreirad ist toll für die Balance",
        "einen Korb für das Erwachsenen-Trike bestellen",
        "mit dem Dreirad zum Wochenmarkt fahren",
        "das Elektro-Dreirad erleichtert Oma die Hügel",
        "Erwachsenen-Dreirad mit hinterem Lastkorb angekommen",
        "das Liegedreirad im Fahrradladen probefahren",
        "die Reifen am Erwachsenen-Dreirad aufpumpen",
        "das Trike vor dem Sommer warten lassen",
        "das Dreirad in der Garage abstellen",
        "das Trike ist perfekt zum Einkaufen",
        "Erwachsenen-Dreiräder für Mobilitätsbedürfnisse recherchieren",
        "die Tretunterstützung macht das Trike leichter zu fahren",
        "die Sitzhöhe am Erwachsenen-Dreirad einstellen",
        "eine Abdeckung fürs Dreirad kaufen",
        "das klappbare Trike passt in den Kofferraum",
        "im Park mit dem Erwachsenen-Trike cruisen",
        "Bremsbeläge am Dreirad wechseln",
        "das Lastendreirad transportiert die ganze Strandausrüstung",
        "Papa liebt sein neues Erwachsenen-Dreirad",
        "online nach einem gebrauchten Trike suchen",
        "das Dreirad ist für sie sicherer als ein Zweirad",
        "mit dem Trike den Radweg entlangfahren",
        "Klingel und Spiegel am Trike anbringen",
        "Trike-Verleih an der Strandpromenade",
        "das adaptive Dreirad half bei der Reha",
        "mit dem Dreirad zum Bäcker fahren",
        "Regenplane für das Trike besorgen",
        "das Dreirad braucht neue Reifen",
        "Dreirad zusammenklappen für die Zugfahrt",
        "den hinteren Korb am Trike reparieren",
        # typos
        "ein Dreirad für Erwachsene zum Traning kaufen",
        "mit dem Dreirad durch die Nachbrschaft fahren",
        "die Reifen am Erwachsenen-Dreirad aufpumepn",
        "das Trike vor dem Somemr warten lassen",
        "Bremsbeläge am Derirad wechseln",
        "online nach einem gebrauchten Tirke suchen",
        "Klingel und Speigel am Trike anbringen",
        "das adaptive Dreirad hfal bei der Reha",
    ],
    new_ja=[
        # keywords (~18)
        "大人用",
        "自転車",
        "モビリティ",
        "ペダル",
        "三輪",
        "三輪車",
        "トライク",
        "アダプティブ",
        "クルーザー",
        "リカンベント",
        "カーゴトライク",
        "電動三輪車",
        "三輪自転車",
        "サイクリング",
        "安定性",
        "バスケット",
        "ハンドブレーキ",
        "シニア用自転車",
        # phrases
        "運動のために大人用三輪車を買う",
        "三輪車で近所を走る",
        "三輪自転車はバランスが良い",
        "大人用トライクにバスケットを注文する",
        "三輪車でファーマーズマーケットに行く",
        "電動三輪車ならおばあちゃんも坂が楽",
        "後ろにカーゴバスケット付きの大人用三輪車が届いた",
        "自転車屋でリカンベントトライクを試乗する",
        "大人用三輪車のタイヤに空気を入れる",
        "夏前に大人用トライクを整備してもらう",
        "三輪車をガレージに停める",
        "トライクは買い物に最適",
        "モビリティのために大人用三輪車を調べる",
        "ペダルアシストでトライクが楽に乗れる",
        "大人用三輪車のシート高さを調整する",
        "三輪車が濡れないようにカバーを買う",
        "折りたたみトライクは車のトランクに入る",
        "公園で大人用トライクに乗る",
        "三輪車のブレーキパッドを交換する",
        "カーゴトライクでビーチ用品を全部運べる",
        "お父さんは新しい大人用三輪車が気に入っている",
        "中古の大人用トライクをネットで探す",
        "彼女には三輪車の方が二輪車より安全",
        "トライクで自転車道を走る",
        "大人用トライクにベルとミラーを付ける",
        "海岸沿いのトライクレンタル",
        "アダプティブ三輪車がリハビリに役立った",
        "三輪車でパン屋まで行く",
        "トライク用のレインカバーを買う",
        "三輪車の新しいタイヤが必要",
        "電車に乗るためにトライクを折りたたむ",
        "トライクの後ろのバスケットを修理する",
        # typos
        "運動のためにおとな用三輪車をかう",
        "三輪車でちかじょを走る",
        "大人用とらいくにバスケットを注文する",
        "三輪車をがれーじに停める",
        "トライクのぶれーきパッドを交換する",
        "中古のおとな用トライクをネットで探す",
        "電動さんりんしゃならおばあちゃんも坂が楽",
        "大人用三輪車のたいやに空気を入れる",
    ],
    new_fr=[
        # keywords (~18)
        "adulte",
        "vélo",
        "mobilité",
        "pédale",
        "trois-roues",
        "tricycle",
        "trike",
        "adaptatif",
        "cruiser",
        "tricycle couché",
        "tricycle cargo",
        "tricycle électrique",
        "triporteur",
        "cyclisme",
        "stabilité",
        "panier",
        "freins à main",
        "vélo senior",
        # phrases
        "acheter un tricycle adulte pour faire de l'exercice",
        "faire un tour en tricycle dans le quartier",
        "le trois-roues est super pour l'équilibre",
        "commander un panier pour le tricycle adulte",
        "aller au marché avec le tricycle",
        "le tricycle électrique facilite les côtes pour mamie",
        "tricycle adulte avec panier cargo arrière livré",
        "essayer le tricycle couché au magasin de vélos",
        "gonfler les pneus du tricycle adulte",
        "faire réviser le trike avant l'été",
        "ranger le tricycle dans le garage",
        "le trike est parfait pour les courses",
        "chercher des tricycles adultes pour la mobilité",
        "l'assistance au pédalage rend le trike plus facile",
        "régler la hauteur de selle du tricycle adulte",
        "acheter une housse pour le tricycle",
        "le trike pliable rentre dans le coffre",
        "se balader dans le parc avec le trike adulte",
        "changer les plaquettes de frein du trois-roues",
        "le tricycle cargo transporte tout le matériel de plage",
        "papa adore son nouveau tricycle adulte",
        "chercher un tricycle adulte d'occasion en ligne",
        "le tricycle est plus sûr qu'un deux-roues pour elle",
        "rouler en trike sur la piste cyclable",
        "ajouter une sonnette et un miroir au trike",
        "location de trikes sur la promenade",
        "le tricycle adaptatif a aidé pour la rééducation",
        "aller à la boulangerie en tricycle",
        "acheter une bâche pour le trike",
        "le tricycle a besoin de nouveaux pneus",
        "plier le trike pour le voyage en train",
        "réparer le panier arrière du trike",
        # typos
        "acheter un tricylce adulte pour l'exercice",
        "faire un tour en tricylce dans le quartier",
        "gonfler les pnues du tricycle adulte",
        "faire révsier le trike avant l'été",
        "changer les plaqeuttes de frein",
        "chercher un tricycle adutle d'occasion",
        "le tricycle électrqiue facilite les côtes",
        "rouler en tirke sur la piste cyclable",
    ],
    new_es=[
        # keywords (~18)
        "adulto",
        "bicicleta",
        "movilidad",
        "pedal",
        "tres ruedas",
        "triciclo",
        "trike",
        "adaptativo",
        "crucero",
        "triciclo reclinado",
        "triciclo de carga",
        "triciclo eléctrico",
        "triciclo para adultos",
        "ciclismo",
        "estabilidad",
        "canasta",
        "frenos de mano",
        "bicicleta para mayores",
        # phrases
        "comprar un triciclo para adultos para hacer ejercicio",
        "pasear en triciclo por el vecindario",
        "el triciclo es genial para el equilibrio",
        "pedir una canasta para el triciclo adulto",
        "ir al mercado con el triciclo",
        "el triciclo eléctrico facilita las cuestas para la abuela",
        "triciclo adulto con canasta de carga trasera llegó",
        "probar el triciclo reclinado en la tienda de bicis",
        "inflar las llantas del triciclo adulto",
        "llevar el trike al servicio antes del verano",
        "guardar el triciclo en el garaje",
        "el trike es perfecto para ir de compras",
        "investigar triciclos adultos para necesidades de movilidad",
        "la asistencia al pedaleo facilita el trike",
        "ajustar la altura del asiento del triciclo adulto",
        "comprar una funda para el triciclo",
        "el trike plegable cabe en la cajuela",
        "pasear por el parque en el trike adulto",
        "cambiar las pastillas de freno del triciclo",
        "el triciclo de carga lleva todo el equipo de playa",
        "a papá le encanta su nuevo triciclo adulto",
        "buscar un triciclo adulto usado en línea",
        "el triciclo es más seguro que una bici de dos ruedas para ella",
        "andar en trike por la ciclovía",
        "agregar timbre y espejo al trike",
        "alquiler de trikes en el paseo marítimo",
        "el triciclo adaptativo ayudó con la rehabilitación",
        "ir a la panadería en triciclo",
        "comprar una lona para el trike",
        "el triciclo necesita llantas nuevas",
        "plegar el trike para el viaje en tren",
        "reparar la canasta trasera del trike",
        # typos
        "comprar un triciclo para adutlos para hacer ejercicio",
        "pasear en tricicol por el vecindario",
        "inflar las llantsa del triciclo adulto",
        "llevar el tirke al servicio antes del verano",
        "cambiar las pastillas de freno del tricicol",
        "buscar un triciclo adulot usado en línea",
        "el triciclo eléctrco facilita las cuestas",
        "agregar tmibre y espejo al trike",
    ],
)

if ok:
    print("\nAll 5 icons OK (task-003a)")
else:
    print("\nSOME ICONS FAILED - check counts above")
