#!/usr/bin/env python3
"""Task-007 part B: spider, squirrel, steak, stocking"""
from gen_icons_task_007_common import build_icon

# ── spider ───────────────────────────────────────────────────────────────────
build_icon("spider", {
    "en": [
        "arachnid", "spider", "crawl", "eight", "charlotte", "web",
        "bug", "insect", "halloween", "tarantula", "cobweb", "pest",
        "creepy crawly", "spider silk", "spider bite", "black widow",
        "venomous", "exterminator",
        "call the exterminator about the spiders in the basement",
        "clean the spider webs from the garage corners",
        "found a spider in the bathtub get rid of it",
        "set up spider decorations for Halloween",
        "buy fake spider webs for the Halloween party",
        "check the attic for spider nests",
        "the kids are scared of the spider on the porch",
        "sweep the cobwebs off the front door",
        "spider crawling on the ceiling need to catch it",
        "read Charlotte's Web to the kids before bed",
        "buy spider traps for the basement",
        "seal the cracks to keep spiders out of the house",
        "the garden spider built a huge web overnight",
        "remove the cobweb from the window frame",
        "spotted a black widow spider call pest control",
        "spider in the kids room need to deal with it",
        "put up Halloween spider lights on the porch",
        "spray for spiders around the foundation",
        "take the kids to the insect exhibit at the museum",
        "spider trap under the bed needs to be checked",
        "hang giant spider decoration on the roof for Halloween",
        "the spider web in the garden is actually pretty cool",
        "make sure no spiders in the camping gear",
        "buy a bug catcher to relocate the spider outside",
        "eight legs spotted on the kitchen wall",
        "get spider repellent for the cabin",
        "research which spiders are harmless in our area",
        "walk into a spider web on the trail gross",
        "Halloween spider craft project with the kids",
        "clean all the cobwebs before the guests arrive",
        "spider season seal the windows and doors",
        "vacuum the spider webs in the garage",
        "teach kids that most spiders are harmless",
        "found a tarantula in the yard leave it alone",
        "the spider web on the porch is covered in morning dew",
        "check shoes for spiders before putting them on",
        "spidre on the ceiling",
        "spoder crawling across the wall",
        "sipder hanging from a web",
        "spiider in the bathtub",
        "cobewb in the corner of the room",
    ],
    "ru": [
        "паук", "паукообразное", "ползти", "восемь", "шарлотта", "паутина",
        "жук", "насекомое", "хэллоуин", "тарантул", "паутинка", "вредитель",
        "ползучая тварь", "паучий шёлк", "укус паука", "чёрная вдова",
        "ядовитый", "дезинсектор",
        "вызвать дезинсектора из-за пауков в подвале",
        "очистить углы гаража от паутины",
        "нашёл паука в ванной надо убрать",
        "повесить пауков-украшения на Хэллоуин",
        "купить искусственную паутину для вечеринки на Хэллоуин",
        "проверить чердак на паучьи гнёзда",
        "дети боятся паука на крыльце",
        "смести паутину с входной двери",
        "паук ползёт по потолку надо поймать",
        "почитать детям Паутину Шарлотты перед сном",
        "купить ловушки для пауков в подвал",
        "заделать щели чтобы пауки не попадали в дом",
        "садовый паук сплёл огромную паутину за ночь",
        "убрать паутину с оконной рамы",
        "заметил чёрную вдову вызвать службу дезинсекции",
        "паук в детской комнате надо разобраться",
        "повесить гирлянду с пауками на крыльце на Хэллоуин",
        "обработать фундамент от пауков",
        "сводить детей на выставку насекомых в музее",
        "проверить ловушку для пауков под кроватью",
        "повесить гигантского паука на крышу на Хэллоуин",
        "паутина в саду на самом деле довольно красивая",
        "убедиться что в походном снаряжении нет пауков",
        "купить ловушку для насекомых чтобы перенести паука на улицу",
        "восемь лап замечены на стене кухни",
        "купить средство от пауков для дачи",
        "узнать какие пауки безвредны в нашем районе",
        "врезался в паутину на тропинке фу",
        "хэллоуин-поделка паук вместе с детьми",
        "убрать всю паутину до прихода гостей",
        "сезон пауков заклеить окна и двери",
        "пропылесосить паутину в гараже",
        "объяснить детям что большинство пауков безвредны",
        "нашёл тарантула во дворе лучше не трогать",
        "паутина на крыльце покрыта утренней росой",
        "проверять обувь на пауков перед тем как обуться",
        "паук на потлоке",
        "паук полёзт по стене",
        "паук висти на паутине",
        "пуак в ванной",
        "паутинна в углу комнаты",
    ],
    "de": [
        "Spinne", "Spinnentier", "krabbeln", "acht", "Charlotte", "Netz",
        "Käfer", "Insekt", "Halloween", "Vogelspinne", "Spinnwebe", "Schädling",
        "Krabbeltier", "Spinnenseide", "Spinnenbiss", "Schwarze Witwe",
        "giftig", "Kammerjäger",
        "den Kammerjäger wegen Spinnen im Keller rufen",
        "Spinnweben in den Garagenecken entfernen",
        "Spinne in der Badewanne gefunden entfernen",
        "Spinnen-Deko für Halloween aufhängen",
        "künstliche Spinnweben für die Halloween-Party kaufen",
        "den Dachboden auf Spinnennester prüfen",
        "die Kinder haben Angst vor der Spinne auf der Veranda",
        "Spinnweben von der Haustür kehren",
        "Spinne krabbelt an der Decke muss gefangen werden",
        "den Kindern Charlottes Netz vorlesen",
        "Spinnenfallen für den Keller kaufen",
        "Ritzen abdichten damit keine Spinnen ins Haus kommen",
        "die Gartenspinne hat über Nacht ein riesiges Netz gebaut",
        "Spinnwebe vom Fensterrahmen entfernen",
        "Schwarze Witwe entdeckt Schädlingsbekämpfung rufen",
        "Spinne im Kinderzimmer muss weg",
        "Halloween-Spinnenlichter auf der Veranda aufhängen",
        "Fundament gegen Spinnen besprühen",
        "mit den Kindern zur Insektenausstellung ins Museum",
        "Spinnenfalle unterm Bett kontrollieren",
        "Riesenspinne als Halloween-Deko aufs Dach hängen",
        "das Spinnennetz im Garten ist eigentlich echt toll",
        "sicherstellen dass keine Spinnen im Campingzeug sind",
        "Insektenfänger kaufen um die Spinne nach draußen zu bringen",
        "acht Beine an der Küchenwand entdeckt",
        "Spinnenspray für die Hütte besorgen",
        "nachforschen welche Spinnen in unserer Gegend harmlos sind",
        "in ein Spinnennetz auf dem Wanderweg gelaufen igitt",
        "Halloween-Bastelarbeit Spinne mit den Kindern",
        "alle Spinnweben vor dem Besuch entfernen",
        "Spinnensaison Fenster und Türen abdichten",
        "Spinnweben im Garage absaugen",
        "Kindern erklären dass die meisten Spinnen harmlos sind",
        "Vogelspinne im Garten gefunden in Ruhe lassen",
        "Spinnennetz auf der Veranda mit Morgentau bedeckt",
        "Schuhe vor dem Anziehen auf Spinnen prüfen",
        "Spinne an der Dekce",
        "Spinne krabblelt über die Wand",
        "Spnine hängt am Netz",
        "Spinne in der Badwanne",
        "Spinnwebe im Eckce des Zimmers",
    ],
    "ja": [
        "クモ", "節足動物", "這う", "八", "シャーロット", "巣",
        "虫", "昆虫", "ハロウィン", "タランチュラ", "クモの巣", "害虫",
        "気持ち悪い虫", "クモの糸", "クモに噛まれた", "クロゴケグモ",
        "毒のある", "害虫駆除業者",
        "地下室のクモについて駆除業者に電話する",
        "ガレージの角のクモの巣を掃除する",
        "お風呂にクモがいた退治する",
        "ハロウィン用にクモの飾りを設置する",
        "ハロウィンパーティー用に偽のクモの巣を買う",
        "屋根裏にクモの巣がないか確認する",
        "子供が玄関のクモを怖がっている",
        "玄関のクモの巣を払う",
        "天井にクモが這っている捕まえないと",
        "寝る前に子供にシャーロットのおくりものを読む",
        "地下室用のクモ取りトラップを買う",
        "クモが入らないように家の隙間を塞ぐ",
        "庭のクモが一晩で巨大な巣を作った",
        "窓枠のクモの巣を取り除く",
        "クロゴケグモを発見した害虫駆除に電話する",
        "子供部屋にクモがいる対処が必要",
        "ハロウィン用にクモのライトを玄関に飾る",
        "基礎周りにクモ除けスプレーをする",
        "博物館の昆虫展に子供を連れていく",
        "ベッドの下のクモ取りトラップを確認する",
        "ハロウィンに屋根に巨大クモの飾りを掛ける",
        "庭のクモの巣が実はかなりきれい",
        "キャンプ用品にクモがいないか確認する",
        "虫取りカゴを買ってクモを外に逃がす",
        "キッチンの壁に八本足を発見",
        "山小屋用にクモよけを買う",
        "この地域で無害なクモを調べる",
        "トレイルでクモの巣に突っ込んだ最悪",
        "ハロウィンのクモの工作を子供とする",
        "お客さんが来る前にクモの巣を全部掃除する",
        "クモのシーズン窓とドアを密閉する",
        "ガレージのクモの巣を掃除機で吸う",
        "ほとんどのクモは無害だと子供に教える",
        "庭でタランチュラを見つけたそっとしておく",
        "玄関のクモの巣が朝露に覆われている",
        "靴を履く前にクモがいないか確認する",
        "天井にクモモがいる",
        "クモが壁をを這っている",
        "クモがが巣からぶら下がっている",
        "お風呂にクモモがいた",
        "部屋の角ににクモの巣",
    ],
    "fr": [
        "araignée", "arachnide", "ramper", "huit", "Charlotte", "toile",
        "insecte", "bestiole", "Halloween", "tarentule", "toile d'araignée",
        "nuisible", "bête rampante", "soie d'araignée", "morsure d'araignée",
        "veuve noire", "venimeux", "exterminateur",
        "appeler l'exterminateur pour les araignées dans la cave",
        "nettoyer les toiles d'araignée dans les coins du garage",
        "trouvé une araignée dans la baignoire s'en débarrasser",
        "installer les décorations d'araignée pour Halloween",
        "acheter de fausses toiles d'araignée pour la fête d'Halloween",
        "vérifier le grenier pour des nids d'araignée",
        "les enfants ont peur de l'araignée sur le porche",
        "balayer les toiles d'araignée de la porte d'entrée",
        "araignée qui rampe au plafond il faut l'attraper",
        "lire La Toile de Charlotte aux enfants le soir",
        "acheter des pièges à araignées pour la cave",
        "colmater les fissures pour empêcher les araignées d'entrer",
        "l'araignée du jardin a tissé une immense toile cette nuit",
        "enlever la toile d'araignée du cadre de fenêtre",
        "veuve noire repérée appeler la désinsectisation",
        "araignée dans la chambre des enfants il faut agir",
        "accrocher des lumières araignée sur le porche pour Halloween",
        "traiter les fondations contre les araignées",
        "emmener les enfants à l'expo insectes au musée",
        "vérifier le piège à araignées sous le lit",
        "suspendre une araignée géante sur le toit pour Halloween",
        "la toile d'araignée dans le jardin est vraiment jolie",
        "vérifier que le matériel de camping ne contient pas d'araignées",
        "acheter un attrape-insectes pour déplacer l'araignée dehors",
        "huit pattes repérées sur le mur de la cuisine",
        "acheter un répulsif araignées pour le chalet",
        "chercher quelles araignées sont inoffensives dans notre région",
        "marché dans une toile d'araignée sur le sentier beurk",
        "activité bricolage araignée pour Halloween avec les enfants",
        "enlever toutes les toiles d'araignée avant l'arrivée des invités",
        "saison des araignées calfeutrer les fenêtres et portes",
        "aspirer les toiles d'araignée dans le garage",
        "expliquer aux enfants que la plupart des araignées sont inoffensives",
        "trouvé une tarentule dans le jardin la laisser tranquille",
        "la toile sur le porche est couverte de rosée du matin",
        "vérifier les chaussures avant de les mettre araignées",
        "araignée au plafnod",
        "aragnée rampe sur le mur",
        "araignéee suspendue à sa toile",
        "ariaignée dans la baignoire",
        "toile d'araignée dans le coni de la pièce",
    ],
    "es": [
        "araña", "arácnido", "arrastrarse", "ocho", "Charlotte", "telaraña",
        "bicho", "insecto", "Halloween", "tarántula", "tela de araña", "plaga",
        "bicho rastrero", "seda de araña", "picadura de araña", "viuda negra",
        "venenoso", "exterminador",
        "llamar al exterminador por las arañas en el sótano",
        "limpiar las telarañas de las esquinas del garaje",
        "encontré una araña en la bañera hay que quitarla",
        "poner decoraciones de araña para Halloween",
        "comprar telarañas falsas para la fiesta de Halloween",
        "revisar el ático por nidos de araña",
        "los niños tienen miedo de la araña en el porche",
        "barrer las telarañas de la puerta principal",
        "araña arrastrándose por el techo hay que atraparla",
        "leerles a los niños La Telaraña de Charlotte antes de dormir",
        "comprar trampas para arañas para el sótano",
        "sellar las grietas para que no entren arañas en la casa",
        "la araña del jardín tejió una red enorme anoche",
        "quitar la telaraña del marco de la ventana",
        "vi una viuda negra llamar al control de plagas",
        "araña en el cuarto de los niños hay que encargarse",
        "colgar luces de araña en el porche para Halloween",
        "fumigar alrededor de los cimientos contra arañas",
        "llevar a los niños a la exhibición de insectos en el museo",
        "revisar la trampa de arañas debajo de la cama",
        "colgar una araña gigante en el techo para Halloween",
        "la telaraña en el jardín en realidad se ve genial",
        "asegurarse de que no haya arañas en el equipo de camping",
        "comprar un atrapa-bichos para sacar la araña afuera",
        "ocho patas vistas en la pared de la cocina",
        "comprar repelente de arañas para la cabaña",
        "investigar qué arañas son inofensivas en nuestra zona",
        "me metí en una telaraña en el sendero qué asco",
        "manualidad de araña de Halloween con los niños",
        "quitar todas las telarañas antes de que lleguen los invitados",
        "temporada de arañas sellar ventanas y puertas",
        "aspirar las telarañas del garaje",
        "enseñar a los niños que la mayoría de arañas son inofensivas",
        "encontré una tarántula en el patio mejor dejarla",
        "la telaraña del porche está cubierta de rocío matutino",
        "revisar los zapatos antes de ponérselos por arañas",
        "araña en el tehco",
        "araña arrastándose por la pared",
        "araña colgadna de su telaraña",
        "araña en la bañrea",
        "telaraña en la esqunia del cuarto",
    ],
})


# ── squirrel ─────────────────────────────────────────────────────────────────
build_icon("squirrel", {
    "en": [
        "squirrel", "acorn", "nut", "tail", "animal", "fauna", "mammal",
        "chipmunk", "rodent", "bushy tail", "tree squirrel", "bird feeder",
        "foraging", "oak tree", "park", "wildlife", "backyard", "nest",
        "put up a squirrel-proof bird feeder",
        "fill the squirrel feeder with peanuts",
        "the squirrel keeps stealing from the bird feeder",
        "watch the squirrels play in the park",
        "squirrel got into the attic need to seal the opening",
        "buy squirrel-proof trash can lids",
        "the squirrel buried acorns all over the yard",
        "take the kids to the park to feed the squirrels",
        "set up a squirrel obstacle course in the yard",
        "squirrel chewed through the porch railing again",
        "call animal control about the squirrel in the walls",
        "plant oak trees so the squirrels have acorns",
        "the squirrels dug up my flower bulbs again",
        "buy peanuts in the shell for the squirrel feeder",
        "the baby squirrel fell out of the nest check on it",
        "squirrel-proof the garden with netting",
        "the dog keeps chasing the squirrel in the backyard",
        "look at that squirrel running across the power line",
        "squirrel nest in the tree outside the bedroom window",
        "set a humane trap for the squirrel in the attic",
        "fix the hole in the roof where squirrels got in",
        "the squirrel is eating the pumpkin on the porch",
        "get the squirrel out of the garage",
        "research how to keep squirrels away from the garden",
        "a squirrel was foraging for nuts in the backyard",
        "the kids love watching the squirrels from the window",
        "order a squirrel baffle for the bird feeder pole",
        "chipmunk digging in the flower bed",
        "replace the bird feeder that the squirrel broke",
        "found acorn stash in the gutter need to clean it",
        "the squirrel is back on the roof again",
        "squirrels running around the oak tree",
        "take a photo of the red squirrel in the garden",
        "build a squirrel nesting box for the yard",
        "the squirrels are extra active before winter",
        "feed the park squirrels on the morning walk",
        "catch the squirrel that got inside the house",
        "squirel keeps stealing bird seed",
        "squrrel in the attic again",
        "sqiurrel burying nuts in the yard",
        "squirell on the bird feeder",
        "acrons all over the yard from squirrels",
    ],
    "ru": [
        "белка", "жёлудь", "орех", "хвост", "животное", "фауна",
        "млекопитающее", "бурундук", "грызун", "пушистый хвост",
        "древесная белка", "кормушка для птиц", "собирательство",
        "дуб", "парк", "дикая природа", "задний двор", "гнездо",
        "повесить кормушку для птиц защищённую от белок",
        "насыпать арахис в кормушку для белок",
        "белка опять ворует из кормушки для птиц",
        "понаблюдать за белками в парке",
        "белка залезла на чердак надо заделать вход",
        "купить крышки на мусорные баки от белок",
        "белка закопала жёлуди по всему двору",
        "сводить детей в парк покормить белок",
        "устроить полосу препятствий для белок во дворе",
        "белка опять прогрызла перила крыльца",
        "позвонить в службу отлова из-за белки в стенах",
        "посадить дубы чтобы белкам хватало желудей",
        "белки опять выкопали мои луковицы цветов",
        "купить арахис в скорлупе для кормушки белок",
        "бельчонок выпал из гнезда надо проверить",
        "защитить сад от белок сеткой",
        "собака гоняет белку по заднему двору",
        "смотри белка бежит по проводу",
        "беличье гнездо на дереве за окном спальни",
        "поставить гуманную ловушку для белки на чердаке",
        "заделать дыру в крыше через которую залезли белки",
        "белка ест тыкву на крыльце",
        "выгнать белку из гаража",
        "узнать как отпугнуть белок от сада",
        "белка собирала орехи на заднем дворе",
        "дети обожают наблюдать за белками из окна",
        "заказать защитный конус для столба кормушки от белок",
        "бурундук роет клумбу",
        "заменить кормушку для птиц которую сломала белка",
        "нашёл тайник с желудями в водостоке надо почистить",
        "белка опять на крыше",
        "белки бегают вокруг дуба",
        "сфотографировать рыжую белку в саду",
        "собрать домик для белки во двор",
        "белки особенно активны перед зимой",
        "покормить белок в парке на утренней прогулке",
        "поймать белку которая забралась в дом",
        "белак опять ворует птичий корм",
        "белка на черадке снова",
        "белка закапыавет орехи во дворе",
        "белак на кормушке для птиц",
        "жёлуид по всему двору от белок",
    ],
    "de": [
        "Eichhörnchen", "Eichel", "Nuss", "Schwanz", "Tier", "Fauna",
        "Säugetier", "Streifenhörnchen", "Nagetier", "buschiger Schwanz",
        "Baumhörnchen", "Vogelfutter", "Futtersuche", "Eiche",
        "Park", "Wildtiere", "Hinterhof", "Nest",
        "ein eichhörnchensicheres Vogelhäuschen aufstellen",
        "das Eichhörnchen-Futterhaus mit Erdnüssen füllen",
        "das Eichhörnchen klaut wieder vom Vogelfutter",
        "den Eichhörnchen im Park beim Spielen zuschauen",
        "Eichhörnchen auf dem Dachboden Eingang abdichten",
        "eichhörnchensichere Mülltonnendeckel kaufen",
        "das Eichhörnchen hat überall im Garten Eicheln vergraben",
        "mit den Kindern in den Park die Eichhörnchen füttern",
        "einen Hindernisparcours für Eichhörnchen im Garten bauen",
        "Eichhörnchen hat wieder das Verandageländer angenagt",
        "Tierkontrolle anrufen wegen Eichhörnchen in der Wand",
        "Eichen pflanzen damit die Eichhörnchen Eicheln haben",
        "die Eichhörnchen haben meine Blumenzwiebeln ausgegraben",
        "Erdnüsse in der Schale für das Eichhörnchen-Futterhaus kaufen",
        "Eichhörnchenbaby aus dem Nest gefallen nachschauen",
        "den Garten mit Netz gegen Eichhörnchen schützen",
        "der Hund jagt das Eichhörnchen im Hinterhof",
        "schau das Eichhörnchen läuft über die Stromleitung",
        "Eichhörnchennest im Baum vor dem Schlafzimmerfenster",
        "eine Lebendfalle für das Eichhörnchen auf dem Dachboden stellen",
        "das Loch im Dach reparieren wo die Eichhörnchen reinkamen",
        "das Eichhörnchen frisst den Kürbis auf der Veranda",
        "das Eichhörnchen aus der Garage vertreiben",
        "recherchieren wie man Eichhörnchen vom Garten fernhält",
        "ein Eichhörnchen suchte Nüsse im Hinterhof",
        "die Kinder lieben es Eichhörnchen vom Fenster zu beobachten",
        "einen Eichhörnchenschutz für die Vogelfutterstange bestellen",
        "Streifenhörnchen gräbt im Blumenbeet",
        "das Vogelhäuschen ersetzen das das Eichhörnchen kaputt gemacht hat",
        "Eichel-Versteck in der Dachrinne gefunden putzen",
        "das Eichhörnchen ist wieder auf dem Dach",
        "Eichhörnchen rennen um die Eiche",
        "ein Foto vom roten Eichhörnchen im Garten machen",
        "einen Eichhörnchen-Nistkasten für den Garten bauen",
        "die Eichhörnchen sind vor dem Winter besonders aktiv",
        "die Eichhörnchen im Park auf dem Morgenspaziergang füttern",
        "das Eichhörnchen fangen das ins Haus gekommen ist",
        "Eichhörnchen klaut weider Vogelfutter",
        "Eichhörcnhen auf dem Dachboden",
        "Echhörnchen vergräbt Nüsse im Garten",
        "Eichhörnchen auf dem Vogelhaus",
        "Eichlen überall im Garten von Eichhörnchen",
    ],
    "ja": [
        "リス", "どんぐり", "ナッツ", "しっぽ", "動物", "野生動物",
        "哺乳類", "シマリス", "げっ歯類", "ふさふさのしっぽ",
        "木リス", "バードフィーダー", "餌探し", "オークの木",
        "公園", "野生生物", "裏庭", "巣",
        "リスよけのバードフィーダーを設置する",
        "リスの餌台にピーナッツを入れる",
        "リスがまたバードフィーダーから盗んでいる",
        "公園でリスが遊んでいるのを見る",
        "リスが屋根裏に入った穴を塞がないと",
        "リスよけのゴミ箱のフタを買う",
        "リスが庭中にどんぐりを埋めた",
        "子供を公園に連れて行ってリスに餌をあげる",
        "庭にリス用の障害物コースを作る",
        "リスがまたポーチの手すりをかじった",
        "壁の中のリスについて動物管理に電話する",
        "リスにどんぐりがあるようにオークの木を植える",
        "リスがまた花の球根を掘り返した",
        "リスの餌台用に殻付きピーナッツを買う",
        "赤ちゃんリスが巣から落ちた様子を見る",
        "ネットで庭をリスから守る",
        "犬が裏庭でリスを追いかけている",
        "あのリスが電線の上を走っている見て",
        "寝室の窓の外の木にリスの巣がある",
        "屋根裏のリスに人道的な罠を仕掛ける",
        "リスが入った屋根の穴を修理する",
        "リスがポーチのカボチャを食べている",
        "ガレージからリスを追い出す",
        "庭からリスを遠ざける方法を調べる",
        "裏庭でリスがナッツを探していた",
        "子供たちが窓からリスを見るのが大好き",
        "バードフィーダーのポール用のリスよけを注文する",
        "シマリスが花壇を掘っている",
        "リスが壊したバードフィーダーを交換する",
        "雨樋にどんぐりの隠し場所を発見掃除する",
        "リスがまた屋根に戻ってきた",
        "オークの木の周りをリスが走り回っている",
        "庭の赤いリスの写真を撮る",
        "庭用のリスの巣箱を作る",
        "リスが冬前に特に活発になっている",
        "朝の散歩で公園のリスに餌をあげる",
        "家に入ったリスを捕まえる",
        "リスがが鳥の餌を盗んでいる",
        "屋根裏にリスがが戻ってきた",
        "リスが庭ににナッツを埋めている",
        "リスがバードフィーダーのの上にいる",
        "庭中にどんぐりりがある",
    ],
    "fr": [
        "écureuil", "gland", "noix", "queue", "animal", "faune",
        "mammifère", "tamia", "rongeur", "queue touffue",
        "écureuil arboricole", "mangeoire à oiseaux", "recherche de nourriture",
        "chêne", "parc", "vie sauvage", "arrière-cour", "nid",
        "installer une mangeoire à oiseaux anti-écureuil",
        "remplir la mangeoire à écureuils avec des cacahuètes",
        "l'écureuil vole encore dans la mangeoire à oiseaux",
        "regarder les écureuils jouer dans le parc",
        "écureuil dans le grenier il faut boucher l'entrée",
        "acheter des couvercles de poubelle anti-écureuil",
        "l'écureuil a enterré des glands partout dans le jardin",
        "emmener les enfants au parc nourrir les écureuils",
        "construire un parcours d'obstacles pour écureuils dans le jardin",
        "l'écureuil a encore rongé la balustrade du porche",
        "appeler le contrôle animal pour l'écureuil dans les murs",
        "planter des chênes pour que les écureuils aient des glands",
        "les écureuils ont encore déterré mes bulbes de fleurs",
        "acheter des cacahuètes en coque pour la mangeoire à écureuils",
        "le bébé écureuil est tombé du nid aller vérifier",
        "protéger le jardin des écureuils avec un filet",
        "le chien court après l'écureuil dans le jardin",
        "regarde cet écureuil qui court sur le fil électrique",
        "nid d'écureuil dans l'arbre devant la fenêtre de la chambre",
        "poser un piège humain pour l'écureuil dans le grenier",
        "réparer le trou dans le toit par où les écureuils entrent",
        "l'écureuil mange la citrouille sur le porche",
        "faire sortir l'écureuil du garage",
        "rechercher comment éloigner les écureuils du jardin",
        "un écureuil cherchait des noix dans l'arrière-cour",
        "les enfants adorent regarder les écureuils depuis la fenêtre",
        "commander un déflecteur anti-écureuil pour le poteau de la mangeoire",
        "tamia qui creuse dans le parterre de fleurs",
        "remplacer la mangeoire que l'écureuil a cassée",
        "trouvé des glands cachés dans la gouttière à nettoyer",
        "l'écureuil est encore sur le toit",
        "écureuils qui courent autour du chêne",
        "prendre une photo de l'écureuil roux dans le jardin",
        "construire un nichoir pour écureuils dans le jardin",
        "les écureuils sont très actifs avant l'hiver",
        "nourrir les écureuils du parc pendant la promenade matinale",
        "attraper l'écureuil qui est entré dans la maison",
        "écureuil vole encroe les graines",
        "écurueil dans le grenier encore",
        "écureuil entere des noix dans le jardin",
        "écureuil sur la mangoire à oiseaux",
        "glnads partout dans le jardin à cause des écureuils",
    ],
    "es": [
        "ardilla", "bellota", "nuez", "cola", "animal", "fauna",
        "mamífero", "ardilla listada", "roedor", "cola peluda",
        "ardilla de árbol", "comedero de pájaros", "forrajeo",
        "roble", "parque", "vida silvestre", "patio trasero", "nido",
        "poner un comedero de pájaros a prueba de ardillas",
        "llenar el comedero de ardillas con cacahuetes",
        "la ardilla sigue robando del comedero de pájaros",
        "ver a las ardillas jugar en el parque",
        "la ardilla se metió en el ático sellar la entrada",
        "comprar tapas de basura a prueba de ardillas",
        "la ardilla enterró bellotas por todo el jardín",
        "llevar a los niños al parque a alimentar a las ardillas",
        "montar un circuito de obstáculos para ardillas en el jardín",
        "la ardilla mordió la baranda del porche otra vez",
        "llamar al control de animales por la ardilla en las paredes",
        "plantar robles para que las ardillas tengan bellotas",
        "las ardillas desenterraron mis bulbos de flores otra vez",
        "comprar cacahuetes con cáscara para el comedero de ardillas",
        "la cría de ardilla se cayó del nido revisarla",
        "proteger el jardín de las ardillas con malla",
        "el perro persigue a la ardilla por el patio trasero",
        "mira esa ardilla corriendo por el cable de luz",
        "nido de ardilla en el árbol frente a la ventana del dormitorio",
        "poner una trampa humanitaria para la ardilla en el ático",
        "reparar el agujero en el techo por donde entraron las ardillas",
        "la ardilla se está comiendo la calabaza del porche",
        "sacar la ardilla del garaje",
        "investigar cómo alejar las ardillas del jardín",
        "una ardilla buscaba nueces en el patio trasero",
        "a los niños les encanta ver a las ardillas desde la ventana",
        "pedir un deflector anti-ardilla para el poste del comedero",
        "ardilla listada escarbando en el macizo de flores",
        "reemplazar el comedero de pájaros que la ardilla rompió",
        "encontré un escondite de bellotas en la canaleta limpiar",
        "la ardilla está de vuelta en el techo",
        "ardillas corriendo alrededor del roble",
        "tomar una foto de la ardilla roja en el jardín",
        "construir una caja nido para ardillas en el jardín",
        "las ardillas están muy activas antes del invierno",
        "alimentar a las ardillas del parque en el paseo matutino",
        "atrapar a la ardilla que entró a la casa",
        "ardila sigue robando semillas de pájaros",
        "ardilla en el átcio otra vez",
        "ardiila enterrando nueces en el jardín",
        "ardilla en el comedro de pájaros",
        "bellotas por todo el jadín por las ardillas",
    ],
})


# ── steak ────────────────────────────────────────────────────────────────────
build_icon("steak", {
    "en": [
        "steak", "beef", "grill", "sirloin", "t-bone", "chop", "dinner",
        "ribeye", "filet", "tenderloin", "medium rare", "well done",
        "barbecue", "marinade", "seasoning", "cast iron", "butcher",
        "rare",
        "grill steaks for dinner tonight",
        "buy two ribeye steaks from the butcher",
        "marinate the steak for at least two hours",
        "season the steak with salt and pepper",
        "preheat the cast iron skillet for the steak",
        "pick up steaks for the weekend barbecue",
        "the steak needs to rest for five minutes after cooking",
        "order a steak dinner at the restaurant",
        "ask the butcher for the best cut of steak",
        "make steak and potatoes for the family dinner",
        "check the grill temperature before putting the steak on",
        "buy a meat thermometer for cooking steak",
        "steak night with the family every Friday",
        "try the new steakhouse downtown",
        "defrost the steaks before dinner",
        "flip the steak only once on the grill",
        "get charcoal for grilling steaks this weekend",
        "the steak was overcooked send it back",
        "learn how to reverse sear a steak",
        "buy dry-aged steak for the anniversary dinner",
        "steak and eggs for a special breakfast",
        "sharpen the steak knives before dinner",
        "pick up steak sauce at the grocery store",
        "make a steak sandwich with the leftovers",
        "the kids want their steak well done",
        "try grilling steak on cedar planks",
        "add garlic butter to the steak",
        "steak on the grill smells amazing",
        "compare prices on sirloin versus ribeye",
        "meal prep steak bowls for the week",
        "the butcher recommended the t-bone today",
        "bring the steak to room temperature first",
        "steak subscription box arrived today",
        "sous vide the steak then finish on the grill",
        "slice the steak thin for fajitas",
        "pan-sear the steak in the cast iron",
        "pick up filet mignon for date night",
        "invite the neighbors over for a steak cookout",
        "steack on the grill",
        "beeef steak dinner",
        "sirolin cut of meat",
        "prok chop for dinner",
        "marinate the staek overnight",
    ],
    "ru": [
        "стейк", "говядина", "гриль", "сирлойн", "ти-бон", "отбивная",
        "ужин", "рибай", "филе", "вырезка", "средняя прожарка",
        "хорошо прожаренный", "барбекю", "маринад", "приправа",
        "чугунная сковорода", "мясник", "слабая прожарка",
        "пожарить стейки на ужин сегодня",
        "купить два рибая у мясника",
        "замариновать стейк минимум на два часа",
        "приправить стейк солью и перцем",
        "разогреть чугунную сковороду для стейка",
        "купить стейки на выходные для барбекю",
        "стейку нужно отдохнуть пять минут после готовки",
        "заказать стейк-ужин в ресторане",
        "спросить мясника какой кусок лучше для стейка",
        "приготовить стейк с картошкой на семейный ужин",
        "проверить температуру гриля перед укладкой стейка",
        "купить термометр для мяса для готовки стейков",
        "стейк-вечер с семьёй каждую пятницу",
        "попробовать новый стейк-хаус в центре",
        "разморозить стейки перед ужином",
        "переворачивать стейк на гриле только один раз",
        "купить уголь для жарки стейков в выходные",
        "стейк пережарили отправить обратно",
        "научиться жарить стейк методом обратного сира",
        "купить стейк сухой выдержки на ужин к годовщине",
        "стейк с яичницей на особый завтрак",
        "заточить ножи для стейков перед ужином",
        "купить соус для стейка в магазине",
        "сделать стейк-сэндвич из остатков",
        "дети хотят стейк хорошей прожарки",
        "попробовать жарить стейк на кедровых дощечках",
        "добавить чесночное масло на стейк",
        "стейк на гриле пахнет потрясающе",
        "сравнить цены на сирлойн и рибай",
        "заготовить стейк-боулы на неделю",
        "мясник сегодня рекомендовал ти-бон",
        "довести стейк до комнатной температуры",
        "подписка на стейки пришла сегодня",
        "приготовить стейк сувид потом обжарить на гриле",
        "нарезать стейк тонко для фахитас",
        "обжарить стейк на чугунной сковороде",
        "купить филе-миньон на романтический ужин",
        "пригласить соседей на стейк-вечеринку",
        "стеек на гриле",
        "говяижй стейк ужин",
        "сирлон кусок мяса",
        "свиная отбивнная на ужин",
        "замариновтаь стейк на ночь",
    ],
    "de": [
        "Steak", "Rindfleisch", "Grill", "Sirloin", "T-Bone", "Kotelett",
        "Abendessen", "Ribeye", "Filet", "Lende", "medium rare",
        "durchgebraten", "Grillparty", "Marinade", "Gewürze",
        "Gusseisenpfanne", "Metzger", "blutig",
        "heute Abend Steaks grillen",
        "zwei Ribeye-Steaks beim Metzger kaufen",
        "das Steak mindestens zwei Stunden marinieren",
        "das Steak mit Salz und Pfeffer würzen",
        "die Gusseisenpfanne für das Steak vorheizen",
        "Steaks für die Grillparty am Wochenende besorgen",
        "das Steak muss fünf Minuten ruhen nach dem Braten",
        "ein Steak-Abendessen im Restaurant bestellen",
        "den Metzger nach dem besten Stück für Steak fragen",
        "Steak mit Kartoffeln fürs Familienessen machen",
        "die Grilltemperatur prüfen bevor das Steak draufkommt",
        "ein Fleischthermometer zum Steakbraten kaufen",
        "jeden Freitag Steak-Abend mit der Familie",
        "das neue Steakhaus in der Innenstadt probieren",
        "die Steaks vor dem Abendessen auftauen",
        "das Steak auf dem Grill nur einmal wenden",
        "Holzkohle zum Steakgrillen am Wochenende kaufen",
        "das Steak war zu durch zurückschicken",
        "lernen wie man ein Steak rückwärts anbrät",
        "dry-aged Steak für das Hochzeitstag-Dinner kaufen",
        "Steak und Eier zum besonderen Frühstück",
        "die Steakmesser vor dem Essen schärfen",
        "Steaksoße im Supermarkt kaufen",
        "aus den Resten ein Steak-Sandwich machen",
        "die Kinder wollen ihr Steak durchgebraten",
        "Steak auf Zedernholz grillen ausprobieren",
        "Knoblauchbutter aufs Steak geben",
        "Steak auf dem Grill riecht fantastisch",
        "Preise vergleichen Sirloin gegen Ribeye",
        "Steak-Bowls für die Woche vorkochen",
        "der Metzger hat heute T-Bone empfohlen",
        "das Steak erst auf Zimmertemperatur bringen",
        "Steak-Abobox ist heute angekommen",
        "Steak sous vide garen dann auf dem Grill finishen",
        "das Steak dünn schneiden für Fajitas",
        "das Steak in der Gusseisenpfanne anbraten",
        "Filet Mignon für den Pärchenabend holen",
        "die Nachbarn zum Steak-Grillabend einladen",
        "Steack auf dem Grill",
        "Rindfliesch-Steak Abendessen",
        "Sirolin Fleischstück",
        "Schweinekoteelt zum Abendessen",
        "das Staek über Nacht marinieren",
    ],
    "ja": [
        "ステーキ", "牛肉", "グリル", "サーロイン", "Tボーン", "チョップ",
        "ディナー", "リブアイ", "フィレ", "テンダーロイン", "ミディアムレア",
        "ウェルダン", "バーベキュー", "マリネ", "調味料",
        "鋳鉄フライパン", "肉屋", "レア",
        "今夜の夕食にステーキを焼く",
        "肉屋でリブアイステーキを2枚買う",
        "ステーキを最低2時間マリネする",
        "ステーキに塩コショウで味付けする",
        "ステーキ用に鋳鉄フライパンを予熱する",
        "週末のバーベキュー用にステーキを買う",
        "ステーキは焼いた後5分休ませる必要がある",
        "レストランでステーキディナーを注文する",
        "ステーキに最適な部位を肉屋に聞く",
        "家族の夕食にステーキとポテトを作る",
        "ステーキを置く前にグリルの温度を確認する",
        "ステーキ調理用に肉の温度計を買う",
        "毎週金曜日は家族でステーキナイト",
        "ダウンタウンの新しいステーキハウスを試す",
        "夕食前にステーキを解凍する",
        "グリルでステーキは一度だけ裏返す",
        "週末のステーキ用に炭を買う",
        "ステーキが焼きすぎだった返してもらう",
        "ステーキのリバースシアの方法を学ぶ",
        "記念日ディナーにドライエイジドステーキを買う",
        "特別な朝食にステーキと卵",
        "夕食前にステーキナイフを研ぐ",
        "スーパーでステーキソースを買う",
        "残り物でステーキサンドイッチを作る",
        "子供たちはウェルダンのステーキがいい",
        "シダーの板でステーキを焼いてみる",
        "ステーキにガーリックバターを添える",
        "グリルのステーキの匂いが最高",
        "サーロインとリブアイの値段を比較する",
        "一週間分のステーキボウルを作り置きする",
        "肉屋が今日はTボーンを勧めてくれた",
        "ステーキをまず常温に戻す",
        "ステーキの定期便が今日届いた",
        "ステーキを低温調理してからグリルで仕上げる",
        "ファヒータ用にステーキを薄く切る",
        "鋳鉄フライパンでステーキを焼く",
        "デートの夜にフィレミニョンを買う",
        "近所の人をステーキパーティーに招待する",
        "グリルでステエキを焼く",
        "牛肉のステーキディナナー",
        "サーロインの肉の切りり身",
        "チョップをを夕食に",
        "ステーキをを一晩マリネする",
    ],
    "fr": [
        "steak", "bœuf", "grill", "faux-filet", "T-bone", "côtelette",
        "dîner", "entrecôte", "filet", "filet mignon", "saignant",
        "bien cuit", "barbecue", "marinade", "assaisonnement",
        "poêle en fonte", "boucher", "bleu",
        "griller des steaks pour le dîner ce soir",
        "acheter deux entrecôtes chez le boucher",
        "faire mariner le steak au moins deux heures",
        "assaisonner le steak avec sel et poivre",
        "préchauffer la poêle en fonte pour le steak",
        "acheter des steaks pour le barbecue du week-end",
        "le steak doit reposer cinq minutes après la cuisson",
        "commander un dîner steak au restaurant",
        "demander au boucher le meilleur morceau pour un steak",
        "préparer un steak frites pour le repas en famille",
        "vérifier la température du grill avant de poser le steak",
        "acheter un thermomètre à viande pour la cuisson du steak",
        "soirée steak en famille chaque vendredi",
        "essayer le nouveau steakhouse en centre-ville",
        "décongeler les steaks avant le dîner",
        "ne retourner le steak qu'une seule fois sur le grill",
        "acheter du charbon pour griller des steaks ce week-end",
        "le steak était trop cuit le renvoyer",
        "apprendre la technique du reverse sear pour le steak",
        "acheter un steak maturé pour le dîner d'anniversaire",
        "steak et œufs pour un petit-déjeuner spécial",
        "aiguiser les couteaux à steak avant le dîner",
        "acheter de la sauce steak à l'épicerie",
        "faire un sandwich au steak avec les restes",
        "les enfants veulent leur steak bien cuit",
        "essayer de griller le steak sur des planches de cèdre",
        "ajouter du beurre à l'ail sur le steak",
        "le steak sur le grill sent incroyablement bon",
        "comparer les prix faux-filet versus entrecôte",
        "préparer des bols de steak pour la semaine",
        "le boucher a recommandé le T-bone aujourd'hui",
        "amener le steak à température ambiante d'abord",
        "la box de steaks par abonnement est arrivée",
        "cuire le steak sous vide puis finir sur le grill",
        "trancher le steak finement pour des fajitas",
        "saisir le steak dans la poêle en fonte",
        "acheter du filet mignon pour la soirée en amoureux",
        "inviter les voisins pour un barbecue steak",
        "steack sur le grill",
        "steak de boeuuf pour le dîner",
        "faux-fielt morceau de viande",
        "côteltte de porc pour le dîner",
        "faire marienr le steak toute la nuit",
    ],
    "es": [
        "bistec", "carne de res", "parrilla", "solomillo", "T-bone",
        "chuleta", "cena", "ribeye", "filete", "lomo", "término medio",
        "bien cocido", "barbacoa", "adobo", "sazonador",
        "sartén de hierro", "carnicero", "poco cocido",
        "asar bistecs para la cena de esta noche",
        "comprar dos ribeyes en la carnicería",
        "marinar el bistec al menos dos horas",
        "sazonar el bistec con sal y pimienta",
        "precalentar la sartén de hierro para el bistec",
        "comprar bistecs para la barbacoa del fin de semana",
        "el bistec necesita reposar cinco minutos después de cocinarse",
        "pedir una cena de bistec en el restaurante",
        "preguntarle al carnicero por el mejor corte de bistec",
        "hacer bistec con papas para la cena familiar",
        "revisar la temperatura de la parrilla antes de poner el bistec",
        "comprar un termómetro de carne para cocinar bistec",
        "noche de bistec con la familia cada viernes",
        "probar el nuevo steakhouse del centro",
        "descongelar los bistecs antes de la cena",
        "voltear el bistec solo una vez en la parrilla",
        "comprar carbón para asar bistecs este fin de semana",
        "el bistec quedó demasiado cocido devolverlo",
        "aprender a hacer reverse sear de un bistec",
        "comprar bistec madurado para la cena de aniversario",
        "bistec con huevos para un desayuno especial",
        "afilar los cuchillos para bistec antes de la cena",
        "comprar salsa para bistec en el supermercado",
        "hacer un sándwich de bistec con las sobras",
        "los niños quieren su bistec bien cocido",
        "probar asar bistec en tablas de cedro",
        "ponerle mantequilla de ajo al bistec",
        "el bistec en la parrilla huele increíble",
        "comparar precios de solomillo contra ribeye",
        "preparar tazones de bistec para la semana",
        "el carnicero recomendó el T-bone hoy",
        "llevar el bistec a temperatura ambiente primero",
        "la caja de suscripción de bistecs llegó hoy",
        "cocinar el bistec a baja temperatura y luego sellar",
        "rebanar el bistec delgado para fajitas",
        "sellar el bistec en la sartén de hierro",
        "comprar filete mignon para la noche de cita",
        "invitar a los vecinos a una parrillada de bistec",
        "bistce en la parrilla",
        "carne de ress para la cena",
        "solomilo corte de carne",
        "chuleta de cerdo para la cnea",
        "marinra el bistec toda la noche",
    ],
})


# ── stocking ─────────────────────────────────────────────────────────────────
build_icon("stocking", {
    "en": [
        "stocking", "christmas", "xmas", "gift", "present", "santa",
        "holiday", "hosiery", "stocking stuffer", "fireplace", "mantle",
        "candy cane", "tradition", "chimney", "felt", "knitted",
        "personalized", "embroidered",
        "hang the stockings on the fireplace mantle",
        "fill the Christmas stockings with small gifts",
        "buy stocking stuffers for the kids",
        "order personalized stockings with everyone's name",
        "sew a new Christmas stocking for the baby",
        "the dog has its own stocking this year",
        "pick up candy canes for the stockings",
        "hang the stockings before Christmas Eve",
        "find the stockings in the holiday decoration box",
        "get matching stockings for the whole family",
        "stuff the stockings after the kids go to bed",
        "buy a stocking holder for the mantle",
        "add an orange and nuts to each stocking",
        "the stocking fell off the mantle need to rehang it",
        "shop for stocking stuffer ideas under ten dollars",
        "knit a Christmas stocking as a homemade gift",
        "write names on the stockings with a marker",
        "buy felt stockings for the classroom party",
        "check what fits inside the stocking before wrapping",
        "the kids are checking their stockings first thing",
        "put chocolate coins in the Christmas stockings",
        "get a stocking for the new family member",
        "stockings lined up on the mantle look so festive",
        "find small toys that fit in the stocking",
        "Santa filled the stockings overnight",
        "wash the stockings after the holiday season",
        "repair the hook on the stocking hanger",
        "buy a jumbo stocking for the gag gift",
        "stockings and hot cocoa by the fire on Christmas morning",
        "the embroidered stocking from grandma is my favorite",
        "take a photo of the stockings on the mantle",
        "find holiday stockings on sale after Christmas",
        "compare stocking stuffer ideas for teens",
        "red and white knitted Christmas stocking tradition",
        "pack away the stockings with the rest of the decorations",
        "make a stocking advent countdown",
        "pick up pet stockings at the store",
        "chrstmas stocking gift",
        "holdiay sock on the mantle",
        "xams stocking hung up",
        "stockign stuffer ideas",
        "stocking on the firepace",
    ],
    "ru": [
        "чулок", "рождество", "новый год", "подарок", "презент", "санта",
        "праздник", "чулочные изделия", "подарок в чулке", "камин",
        "каминная полка", "леденец", "традиция", "дымоход", "фетр",
        "вязаный", "именной", "вышитый",
        "повесить чулки на каминную полку",
        "наполнить рождественские чулки маленькими подарками",
        "купить мелкие подарки в чулки для детей",
        "заказать именные чулки с именами каждого",
        "сшить новый рождественский чулок для малыша",
        "у собаки в этом году свой чулок",
        "купить леденцы для рождественских чулков",
        "повесить чулки до сочельника",
        "найти чулки в коробке с праздничными украшениями",
        "купить одинаковые чулки для всей семьи",
        "наполнить чулки после того как дети уснут",
        "купить подставку для чулков на каминную полку",
        "положить апельсин и орехи в каждый чулок",
        "чулок упал с каминной полки надо повесить снова",
        "найти идеи для подарков в чулки до десяти долларов",
        "связать рождественский чулок в подарок",
        "написать имена на чулках маркером",
        "купить фетровые чулки для школьной вечеринки",
        "проверить что поместится в чулок перед упаковкой",
        "дети первым делом бегут проверять чулки",
        "положить шоколадные монетки в рождественские чулки",
        "купить чулок для нового члена семьи",
        "чулки в ряд на каминной полке выглядят празднично",
        "найти маленькие игрушки которые поместятся в чулок",
        "санта наполнил чулки за ночь",
        "постирать чулки после праздничного сезона",
        "починить крючок на подвесе для чулка",
        "купить гигантский чулок для шуточного подарка",
        "чулки и горячее какао у камина рождественским утром",
        "вышитый чулок от бабушки мой любимый",
        "сфотографировать чулки на каминной полке",
        "купить праздничные чулки на распродаже после рождества",
        "сравнить идеи подарков в чулки для подростков",
        "красно-белый вязаный рождественский чулок традиция",
        "убрать чулки вместе с остальными украшениями",
        "сделать адвент-отсчёт из чулков",
        "купить чулки для питомцев в магазине",
        "рождетвенский чулок подарок",
        "праздничный носк на полке",
        "новогодний чулко повесить",
        "подарки в чулке идеии",
        "чулок на камнной полке",
    ],
    "de": [
        "Strumpf", "Weihnachten", "Xmas", "Geschenk", "Präsent",
        "Weihnachtsmann", "Feiertag", "Strumpfwaren", "Strumpf-Geschenk",
        "Kamin", "Kaminsims", "Zuckerstange", "Tradition", "Schornstein",
        "Filz", "gestrickt", "personalisiert", "bestickt",
        "die Strümpfe am Kaminsims aufhängen",
        "die Weihnachtsstrümpfe mit kleinen Geschenken füllen",
        "Kleinigkeiten für die Strümpfe der Kinder kaufen",
        "personalisierte Strümpfe mit Namen bestellen",
        "einen neuen Weihnachtsstrumpf für das Baby nähen",
        "der Hund hat dieses Jahr seinen eigenen Strumpf",
        "Zuckerstangen für die Strümpfe kaufen",
        "die Strümpfe vor Heiligabend aufhängen",
        "die Strümpfe in der Weihnachtsdeko-Kiste finden",
        "passende Strümpfe für die ganze Familie kaufen",
        "die Strümpfe füllen wenn die Kinder schlafen",
        "einen Strumpfhalter für den Kaminsims kaufen",
        "eine Orange und Nüsse in jeden Strumpf legen",
        "der Strumpf ist vom Kaminsims gefallen wieder aufhängen",
        "Ideen für Strumpf-Geschenke unter zehn Euro suchen",
        "einen Weihnachtsstrumpf als selbstgemachtes Geschenk stricken",
        "Namen auf die Strümpfe mit einem Stift schreiben",
        "Filzstrümpfe für die Schulfeier kaufen",
        "prüfen was in den Strumpf passt vor dem Einpacken",
        "die Kinder schauen zuerst in ihre Strümpfe",
        "Schokoladenmünzen in die Weihnachtsstrümpfe legen",
        "einen Strumpf für das neue Familienmitglied kaufen",
        "Strümpfe aufgereiht am Kaminsims sehen festlich aus",
        "kleine Spielsachen finden die in den Strumpf passen",
        "der Weihnachtsmann hat die Strümpfe über Nacht gefüllt",
        "die Strümpfe nach der Weihnachtszeit waschen",
        "den Haken am Strumpfhalter reparieren",
        "einen Riesenstrumpf für das Scherzgeschenk kaufen",
        "Strümpfe und heiße Schokolade am Kamin am Weihnachtsmorgen",
        "der bestickte Strumpf von Oma ist mein Lieblings",
        "ein Foto von den Strümpfen am Kaminsims machen",
        "Weihnachtsstrümpfe im Schlussverkauf nach Weihnachten kaufen",
        "Ideen für Strumpf-Geschenke für Teenager vergleichen",
        "rot-weißer gestrickter Weihnachtsstrumpf Tradition",
        "die Strümpfe mit der restlichen Deko wegräumen",
        "einen Adventskalender aus Strümpfen basteln",
        "Haustier-Strümpfe im Laden kaufen",
        "Weihnachtsstrmpf Geschenk",
        "Feiertagssocke am Kaminsims",
        "Weihnachtsstrupf aufgehängt",
        "Strumpf-Geschenk Ideen",
        "Strumpf am Kamni",
    ],
    "ja": [
        "クリスマスの靴下", "クリスマス", "ギフト", "プレゼント", "サンタ",
        "ホリデー", "靴下", "小さなプレゼント", "暖炉", "マントルピース",
        "キャンディケイン", "伝統", "煙突", "フェルト", "ニット",
        "名前入り", "刺繍", "クリスマスイブ",
        "暖炉のマントルピースにクリスマスの靴下を掛ける",
        "クリスマスの靴下に小さなプレゼントを詰める",
        "子供用のクリスマスの靴下のプレゼントを買う",
        "みんなの名前入りクリスマス靴下を注文する",
        "赤ちゃん用の新しいクリスマスの靴下を縫う",
        "犬にも今年はクリスマスの靴下がある",
        "クリスマスの靴下用にキャンディケインを買う",
        "クリスマスイブまでに靴下を掛ける",
        "ホリデーの飾りの箱からクリスマスの靴下を見つける",
        "家族全員にお揃いのクリスマスの靴下を買う",
        "子供が寝た後にクリスマスの靴下を詰める",
        "マントルピース用の靴下掛けを買う",
        "各クリスマスの靴下にオレンジとナッツを入れる",
        "クリスマスの靴下がマントルから落ちた掛け直す",
        "10ドル以下のクリスマスの靴下プレゼントを探す",
        "クリスマスの靴下を手編みしてプレゼントにする",
        "クリスマスの靴下にマーカーで名前を書く",
        "学校のパーティー用にフェルトの靴下を買う",
        "包む前にクリスマスの靴下に入るか確認する",
        "子供たちが真っ先にクリスマスの靴下を確認する",
        "クリスマスの靴下にチョコレートコインを入れる",
        "新しい家族のためにクリスマスの靴下を買う",
        "マントルに並んだ靴下がとてもお祝いムード",
        "クリスマスの靴下に入る小さなおもちゃを探す",
        "サンタが一晩で靴下を満たした",
        "ホリデーシーズン後にクリスマスの靴下を洗う",
        "靴下掛けのフックを修理する",
        "ジョーク用に巨大なクリスマスの靴下を買う",
        "クリスマスの朝に暖炉のそばで靴下とココア",
        "おばあちゃんの刺繍の靴下が一番のお気に入り",
        "マントルの靴下の写真を撮る",
        "クリスマス後のセールでホリデーの靴下を探す",
        "ティーン向けのクリスマスの靴下プレゼントを比較",
        "赤と白のニットのクリスマスの靴下の伝統",
        "飾りと一緒にクリスマスの靴下を片付ける",
        "クリスマスの靴下でアドベントカウントダウンを作る",
        "お店でペット用のクリスマスの靴下を買う",
        "クリスマスのの靴下プレゼント",
        "ホリデーの靴下をを棚に",
        "クリスマスす靴下を掛ける",
        "靴下のプレゼントのアイデデア",
        "暖炉のの上の靴下",
    ],
    "fr": [
        "chaussette de Noël", "Noël", "cadeau", "présent", "père Noël",
        "fête", "bas", "petit cadeau", "cheminée", "manteau de cheminée",
        "sucre d'orge", "tradition", "conduit de cheminée", "feutre",
        "tricoté", "personnalisé", "brodé", "réveillon",
        "accrocher les chaussettes de Noël sur la cheminée",
        "remplir les chaussettes de Noël de petits cadeaux",
        "acheter des petits cadeaux pour les chaussettes des enfants",
        "commander des chaussettes personnalisées avec les prénoms",
        "coudre une nouvelle chaussette de Noël pour le bébé",
        "le chien a sa propre chaussette de Noël cette année",
        "acheter des sucres d'orge pour les chaussettes",
        "accrocher les chaussettes avant le réveillon de Noël",
        "trouver les chaussettes dans la boîte de décorations",
        "acheter des chaussettes assorties pour toute la famille",
        "remplir les chaussettes quand les enfants dorment",
        "acheter un support de chaussette pour la cheminée",
        "mettre une orange et des noix dans chaque chaussette",
        "la chaussette est tombée de la cheminée la raccrocher",
        "chercher des idées de petits cadeaux à moins de dix euros",
        "tricoter une chaussette de Noël comme cadeau fait main",
        "écrire les prénoms sur les chaussettes au feutre",
        "acheter des chaussettes en feutre pour la fête de l'école",
        "vérifier ce qui tient dans la chaussette avant d'emballer",
        "les enfants vérifient leurs chaussettes en premier",
        "mettre des pièces en chocolat dans les chaussettes de Noël",
        "acheter une chaussette pour le nouveau membre de la famille",
        "les chaussettes alignées sur la cheminée c'est festif",
        "trouver des petits jouets qui tiennent dans la chaussette",
        "le père Noël a rempli les chaussettes cette nuit",
        "laver les chaussettes après les fêtes",
        "réparer le crochet du support de chaussette",
        "acheter une chaussette géante pour le cadeau gag",
        "chaussettes et chocolat chaud au coin du feu le matin de Noël",
        "la chaussette brodée de mamie est ma préférée",
        "prendre une photo des chaussettes sur la cheminée",
        "acheter des chaussettes de Noël en solde après les fêtes",
        "comparer les idées de petits cadeaux pour ados",
        "chaussette de Noël tricotée rouge et blanche tradition",
        "ranger les chaussettes avec le reste des décorations",
        "faire un calendrier de l'avent avec des chaussettes",
        "acheter des chaussettes de Noël pour les animaux",
        "chaussette de Nöel cadeau",
        "chausette de fête sur la cheminée",
        "chaussette de Noël accrochéee",
        "idées de petits cadeaux pour chausettes",
        "chaussette sur la chemnée",
    ],
    "es": [
        "bota navideña", "Navidad", "regalo", "presente", "Santa",
        "fiesta", "media", "regalito", "chimenea", "repisa de chimenea",
        "bastón de caramelo", "tradición", "conducto", "fieltro",
        "tejido", "personalizado", "bordado", "Nochebuena",
        "colgar las botas navideñas en la repisa de la chimenea",
        "llenar las botas navideñas con regalitos",
        "comprar regalitos para las botas de los niños",
        "pedir botas navideñas personalizadas con los nombres",
        "coser una nueva bota navideña para el bebé",
        "el perro tiene su propia bota navideña este año",
        "comprar bastones de caramelo para las botas navideñas",
        "colgar las botas antes de Nochebuena",
        "buscar las botas en la caja de decoraciones navideñas",
        "comprar botas navideñas iguales para toda la familia",
        "llenar las botas cuando los niños se duerman",
        "comprar un soporte para botas para la repisa",
        "poner una naranja y nueces en cada bota navideña",
        "la bota se cayó de la repisa hay que colgarla otra vez",
        "buscar ideas de regalitos para botas de menos de diez dólares",
        "tejer una bota navideña como regalo hecho a mano",
        "escribir los nombres en las botas con marcador",
        "comprar botas de fieltro para la fiesta de la escuela",
        "revisar qué cabe en la bota antes de envolver",
        "los niños revisan sus botas navideñas primero",
        "poner monedas de chocolate en las botas navideñas",
        "comprar una bota navideña para el nuevo miembro de la familia",
        "las botas alineadas en la repisa se ven muy festivas",
        "buscar juguetes pequeños que quepan en la bota",
        "Santa llenó las botas durante la noche",
        "lavar las botas después de la temporada navideña",
        "arreglar el gancho del colgador de la bota",
        "comprar una bota navideña gigante para el regalo de broma",
        "botas y chocolate caliente junto a la chimenea la mañana de Navidad",
        "la bota bordada de la abuela es mi favorita",
        "tomar una foto de las botas en la repisa",
        "comprar botas navideñas en rebaja después de Navidad",
        "comparar ideas de regalitos en botas para adolescentes",
        "bota navideña tejida roja y blanca tradición",
        "guardar las botas con el resto de las decoraciones",
        "hacer una cuenta regresiva de adviento con botas",
        "comprar botas navideñas para las mascotas",
        "bota navidña regalo",
        "media de fiesta en la repsia",
        "bota navdieña colgada",
        "regalitos para la bota navidña",
        "bota en la chmenea",
    ],
})

print("Part B done: spider, squirrel, steak, stocking")
