#!/usr/bin/env python3
"""Generate English training data for icons 250-279."""
from pathlib import Path
import csv, json

icons_dir = Path("icons")
icons_dir.mkdir(exist_ok=True)

def write_csv(path, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["text", "label"])
        w.writerows(rows)

def process_icon(icon, st_en, pst_en, reg_en, conv_en, typo_en, bnd_en, valid_en, test_en):
    icon_dir = icons_dir / icon
    icon_dir.mkdir(parents=True, exist_ok=True)
    train_en = [(t, icon) for t in st_en + pst_en + reg_en + conv_en + typo_en + bnd_en]
    write_csv(icon_dir / "train_en.csv", train_en)
    write_csv(icon_dir / "valid_en.csv", [(t, icon) for t in valid_en])
    write_csv(icon_dir / "test_en.csv",  [(t, icon) for t in test_en])
    log = {
        "icon": icon, "search_terms": st_en, "phrase_per_search_term": pst_en,
        "regular": reg_en, "conversational": conv_en, "typo": typo_en,
        "boundary": bnd_en, "valid": valid_en, "test": test_en,
    }
    with open(icon_dir / "icon_log.json", "w", encoding="utf-8") as f:
        json.dump(log, f, ensure_ascii=False, indent=2)
    n_st = len(st_en); n_pst = len(pst_en)
    print(f"  {icon}: {len(train_en)} train rows  ({n_st} st + {n_pst} pst + 24)")

process_icon("loader",
    st_en=["loading", "pending", "progress"],
    pst_en=[
        "content loading indicator", "page loading animation",
        "task pending status", "request pending icon",
        "task progress indicator", "showing current progress",
    ],
    reg_en=[
        "waiting for content to appear", "spinning loading wheel",
        "buffering animation", "data loading in background",
        "please wait indicator", "loading screen animation",
        "circular progress spinner", "activity indicator spinning",
        "processing request animation", "loading dots animation",
    ],
    conv_en=[
        "add a loading spinner to my button",
        "I need an icon for when something is loading",
        "show a loading state while fetching data",
        "what icon shows that the app is busy",
    ],
    typo_en=["laoding indicator", "loding spinner", "penidng status", "progres indicator"],
    bnd_en=[
        "spinning circle animation for waiting", "hourglass counting down time",
        "timer animation while waiting", "rotating dots indicating delay",
        "animated waiting symbol", "clock spinning to show time passing",
    ],
    valid_en=["loading animation for app", "pending task symbol", "progress bar animation"],
    test_en=["loading wheel", "pending request indicator", "progress status"],
)

process_icon("location-crosshairs",
    st_en=["address", "coordinate", "direction", "gps", "location", "map", "navigation", "place", "where"],
    pst_en=[
        "street address crosshair targeting", "finding exact address coordinates",
        "precise coordinate crosshair", "crosshair at exact coordinate",
        "direction crosshair targeting point", "aiming crosshairs for direction",
        "GPS crosshairs on map", "GPS crosshair targeting location",
        "crosshair on location", "location crosshair indicator",
        "crosshair on map", "map crosshair targeting spot",
        "navigation crosshair", "crosshair for navigation",
        "crosshair marking a place", "targeting a place with crosshair",
        "where am I crosshair", "crosshair showing where you are",
    ],
    reg_en=[
        "target crosshair locating position", "locate exact position on map",
        "precision location targeting", "crosshairs centered on current location",
        "GPS targeting with crosshairs", "aim crosshairs at destination",
        "precise location finder", "target reticle on map location",
        "crosshair locator symbol", "find exact spot with crosshairs",
    ],
    conv_en=[
        "I want a crosshair icon to show my exact location",
        "add a target icon for GPS positioning",
        "use the crosshairs icon for location targeting",
        "show where I am with a crosshair symbol",
    ],
    typo_en=["locatoin crosshairs", "crosshairs locaiton", "navigaiton crosshair", "coordiante target"],
    bnd_en=[
        "red location pin dropped on map", "map marker pin at destination",
        "location dot indicating position", "pin marker on map showing place",
        "round location dot on screen", "destination pin on navigation map",
    ],
    valid_en=["crosshair targeting GPS location", "precision location crosshairs", "target reticle for navigation"],
    test_en=["crosshairs on map", "GPS crosshair", "location targeting crosshair"],
)

process_icon("location-dot",
    st_en=["address", "coordinates", "destination", "gps", "localize", "location", "map", "navigation", "paper", "pin", "place", "point of interest", "position", "route", "travel"],
    pst_en=[
        "dot showing address location", "address marked with location dot",
        "coordinates shown as location dot", "dot at exact coordinates",
        "destination shown with location dot", "location dot at your destination",
        "GPS dot on map", "location dot for GPS tracking",
        "localize position with a dot", "location dot to localize on map",
        "location dot indicator", "dot showing current location",
        "map with location dot", "dot on map showing position",
        "navigation location dot", "location dot for navigation",
        "paper map with location dot", "dot on paper map",
        "pin dot on map", "location dot like a pin",
        "dot marking a place", "place shown with location dot",
        "point of interest location dot", "location dot for point of interest",
        "dot showing current position", "position dot on map",
        "route starting with location dot", "location dot along route",
        "travel destination dot", "location dot for travel planning",
    ],
    reg_en=[
        "round location indicator on map", "pulsing location dot",
        "blue dot showing current position", "location dot on navigation screen",
        "small dot marking place on map", "GPS position dot",
        "animated location dot pulsing", "solid dot for map location",
        "current location shown as dot", "map position dot indicator",
    ],
    conv_en=[
        "I need an icon showing a round location dot",
        "add a location dot to the map screen",
        "what icon shows a dot on a map",
        "use the round dot for showing position",
    ],
    typo_en=["locaiton dot", "loaction dot", "navigaiton dot", "destionation dot"],
    bnd_en=[
        "crosshair targeting exact location", "map pin marker dropped at destination",
        "precision crosshair locator", "pin marker on map for navigation",
        "red map pin indicating place", "crosshairs centered on position",
    ],
    valid_en=["location dot on map", "GPS position dot", "round location indicator"],
    test_en=["location dot", "position dot on map", "dot showing current location"],
)

process_icon("loveseat",
    st_en=["chair", "couch", "cushion", "furniture", "relax", "sofa"],
    pst_en=[
        "small loveseat chair", "comfortable loveseat chair",
        "loveseat couch for two", "small couch loveseat",
        "cushioned loveseat sofa", "loveseat with soft cushions",
        "living room loveseat furniture", "loveseat furniture piece",
        "relax on loveseat", "cozy loveseat to relax",
        "loveseat sofa for two", "two seater loveseat sofa",
    ],
    reg_en=[
        "two seater small sofa", "compact couch for couples",
        "small upholstered seating", "two person sitting furniture",
        "small sofa for living room", "love seat seating furniture",
        "compact sofa with armrests", "cozy two seater couch",
        "small sectional loveseat", "mini sofa for small space",
    ],
    conv_en=[
        "I need a loveseat icon for my furniture app",
        "show a small couch for two people",
        "add a loveseat icon to the room designer",
        "what icon shows a small two person sofa",
    ],
    typo_en=["lovesaet sofa", "loveset couch", "love seet furniture", "soaf loveseat"],
    bnd_en=[
        "large three seat family sofa", "full size living room couch",
        "single armchair for reading", "recliner chair with footrest",
        "sectional sofa with chaise", "oversized couch with many cushions",
    ],
    valid_en=["loveseat two person sofa", "small couch furniture", "loveseat for couples"],
    test_en=["loveseat", "small sofa for two", "compact loveseat couch"],
)

process_icon("mace",
    st_en=["Dungeons & Dragons", "d&d", "dnd", "fantasy", "melee attack", "weapon", "windu"],
    pst_en=[
        "mace weapon in Dungeons and Dragons", "D&D mace for dungeon adventure",
        "d&d mace weapon", "mace for d&d combat",
        "dnd fantasy mace", "mace in dnd game",
        "fantasy mace weapon", "mace for fantasy game",
        "mace for melee attack", "melee weapon mace",
        "mace as a weapon", "combat weapon mace",
        "Mace Windu style weapon", "named after Mace Windu",
    ],
    reg_en=[
        "spiked medieval club weapon", "heavy war mace for combat",
        "medieval bludgeoning weapon", "club with spiky ball head",
        "knight's mace weapon", "fantasy RPG melee weapon",
        "ancient war weapon mace", "mace used in medieval battle",
        "heavy combat club", "RPG character weapon mace",
    ],
    conv_en=[
        "I need a mace icon for my RPG game",
        "add a fantasy mace weapon icon",
        "show a medieval weapon for the dungeon",
        "use the mace icon for the warrior class",
    ],
    typo_en=["maec weapon", "mace wepaon", "fantsy mace", "medievel mace"],
    bnd_en=[
        "long sword fantasy weapon", "battle axe for medieval combat",
        "knight's sword with handle", "double-headed war axe",
        "fantasy broadsword weapon", "sharp blade sword for RPG",
    ],
    valid_en=["medieval mace weapon", "fantasy mace for RPG", "war mace club weapon"],
    test_en=["mace", "medieval combat mace", "fantasy RPG mace weapon"],
)

process_icon("magnet",
    st_en=["attract", "attraction", "horseshoe", "lodestone", "magnet", "magnetic", "tool"],
    pst_en=[
        "magnet to attract objects", "attracting metal with a magnet",
        "magnet attraction force", "magnetic attraction symbol",
        "horseshoe magnet shape", "horseshoe shaped magnet",
        "lodestone natural magnet", "magnet like a lodestone",
        "magnet icon", "red and blue magnet",
        "magnetic force icon", "magnetic attraction",
        "magnet as a tool", "tool using magnetic force",
    ],
    reg_en=[
        "horseshoe magnet attracting iron", "red and blue poles magnet",
        "magnetic force symbol", "magnet pulling metal objects",
        "north south pole magnet", "classic horseshoe magnet icon",
        "attract objects with magnet", "permanent magnet symbol",
        "magnet for picking up metal", "magnetic field indicator",
    ],
    conv_en=[
        "I need a magnet icon for my science app",
        "add the magnet symbol to show attraction",
        "show a horseshoe magnet for the tool section",
        "use a magnet icon for the download feature",
    ],
    typo_en=["magnett horseshoe", "mangnet attraction", "horesshoe magnet", "maget tool"],
    bnd_en=[
        "paperclip for attaching documents", "chain link connecting items",
        "attachment clip icon", "link symbol connecting two items",
        "binder clip for papers", "chain connecting two rings",
    ],
    valid_en=["horseshoe magnet icon", "magnetic attraction symbol", "magnet tool"],
    test_en=["magnet", "horseshoe magnet", "magnetic force icon"],
)

process_icon("magnifying-glass",
    st_en=["bigger", "enlarge", "equipment", "find", "glass", "inspection", "magnifier", "magnify", "magnifying", "preview", "search", "tool", "zoom"],
    pst_en=[
        "make it bigger with magnifying glass", "magnifying glass to see bigger",
        "enlarge view with magnifying glass", "magnifying glass to enlarge text",
        "magnifying glass equipment", "inspection equipment magnifying glass",
        "find information with magnifying glass", "use magnifying glass to find details",
        "glass lens magnifier", "round glass magnifying lens",
        "inspection with magnifying glass", "magnifying glass for close inspection",
        "magnifier glass icon", "handheld magnifier glass",
        "magnify text with glass", "magnify small details with lens",
        "magnifying lens symbol", "magnifying glass shape",
        "preview content with magnifying glass", "magnifying glass for preview",
        "search icon magnifying glass", "magnifying glass search symbol",
        "magnifying glass tool", "inspection tool magnifying glass",
        "zoom in with magnifying glass", "magnifying glass for zoom",
    ],
    reg_en=[
        "search icon with magnifying glass", "look for items using magnifying glass",
        "detective magnifying glass", "zoom lens for small text",
        "find and search symbol", "glass lens for magnification",
        "handheld magnifying lens", "search feature glass icon",
        "zoom into image with glass", "magnifying glass for reading fine print",
    ],
    conv_en=[
        "I need a search icon with a magnifying glass",
        "add a magnifying glass to the search bar",
        "show the find icon as a magnifying glass",
        "use a magnifying glass icon for the search feature",
    ],
    typo_en=["magnifyin glass", "magnifing glas", "serach magnifying glass", "magniying lens"],
    bnd_en=[
        "binoculars for viewing far distances", "zoom in button with plus sign",
        "binocular lens for distant viewing", "zoom button to enlarge screen",
        "telescope viewing lens", "binoculars for bird watching",
    ],
    valid_en=["magnifying glass search icon", "zoom lens magnifier", "search symbol glass"],
    test_en=["magnifying glass", "search icon", "zoom lens"],
)

process_icon("mailbox",
    st_en=["archive", "closed", "envelope", "letter", "mail", "mailbox", "newsletter", "offer", "post office", "postal", "postbox", "postcard", "send", "stamp", "usps"],
    pst_en=[
        "archive mail in mailbox", "mailbox for archiving mail",
        "closed mailbox door", "mailbox with closed door",
        "envelope in mailbox", "mailbox with envelope inside",
        "letter delivered to mailbox", "mailbox for receiving letters",
        "mail delivered to mailbox", "check the mailbox for mail",
        "mailbox icon", "standard mailbox symbol",
        "newsletter in mailbox", "receive newsletter in mailbox",
        "offer letter in mailbox", "special offer delivered to mailbox",
        "post office mailbox", "mailbox at post office",
        "postal mailbox delivery", "postal service mailbox",
        "postbox for mail", "red postbox for letters",
        "postcard in mailbox", "mailbox with postcard",
        "send letter via mailbox", "mailbox for sending mail",
        "stamped letter in mailbox", "mailbox with stamp",
        "USPS mailbox delivery", "mailbox for USPS service",
    ],
    reg_en=[
        "check the mailbox for letters", "physical mail delivery box",
        "outdoor mailbox for correspondence", "residential mailbox on post",
        "collect mail from mailbox", "daily mail check at mailbox",
        "curbside mailbox for delivery", "metal mailbox for postal mail",
        "street mailbox for receiving letters", "home mailbox for post delivery",
    ],
    conv_en=[
        "I need a mailbox icon for the delivery feature",
        "add a physical mailbox symbol to the app",
        "show the mailbox icon for postal mail",
        "use a mailbox icon for the inbox section",
    ],
    typo_en=["mialbox delivery", "mailboks for letters", "maillbox with flag", "psotal mailbox"],
    bnd_en=[
        "sealed envelope ready to send", "digital email inbox on screen",
        "open envelope with letter inside", "inbox tray with incoming mail",
        "white envelope with address on it", "email inbox with unread messages",
    ],
    valid_en=["mailbox for letters and mail", "physical postal mailbox", "residential mailbox delivery"],
    test_en=["mailbox", "postal mailbox", "home mailbox for mail"],
)

process_icon("mandolin",
    st_en=["Dungeons & Dragons", "bard", "d&d", "dnd", "fantasy", "guitar", "instrument", "lute", "music", "song", "strings"],
    pst_en=[
        "mandolin in Dungeons and Dragons", "D&D bard mandolin instrument",
        "bard playing mandolin", "mandolin for bard character",
        "d&d mandolin music", "mandolin for d&d bard",
        "dnd bard mandolin", "mandolin in dnd game",
        "fantasy mandolin instrument", "mandolin in fantasy world",
        "mandolin similar to guitar", "mandolin guitar-like instrument",
        "mandolin string instrument", "mandolin musical instrument",
        "mandolin like a lute", "lute mandolin shape",
        "mandolin music symbol", "play music with mandolin",
        "song played on mandolin", "mandolin for playing songs",
        "mandolin with four string pairs", "plucked string mandolin",
    ],
    reg_en=[
        "small pear-shaped stringed instrument", "Italian folk music instrument",
        "plucked string instrument mandolin", "bluegrass mandolin music",
        "classical mandolin with resonator", "medieval bard's instrument",
        "acoustic mandolin for folk music", "mandolin for country music",
        "small guitar-like string instrument", "mandolin played with a pick",
    ],
    conv_en=[
        "I need a mandolin icon for my music app",
        "add the mandolin to the bard skill screen",
        "show a mandolin for the folk music section",
        "use the mandolin icon for the instrument list",
    ],
    typo_en=["mandoiln instrument", "mnandolin string", "bard mandollin", "mandloin music"],
    bnd_en=[
        "acoustic six-string guitar", "banjo country music instrument",
        "electric guitar for rock music", "ukulele small four string guitar",
        "classical guitar with nylon strings", "five string banjo for bluegrass",
    ],
    valid_en=["mandolin string instrument", "bard mandolin for fantasy game", "folk music mandolin"],
    test_en=["mandolin", "mandolin instrument", "bard mandolin music"],
)

process_icon("manhole",
    st_en=["grate", "sewer"],
    pst_en=[
        "manhole grate on street", "metal grate manhole cover",
        "sewer manhole cover", "manhole access to sewer",
    ],
    reg_en=[
        "circular metal manhole cover", "street manhole with cover",
        "utility access manhole", "cast iron manhole cover",
        "round manhole in road", "underground access manhole",
        "city street manhole cover", "manhole for utility workers",
        "heavy metal manhole lid", "storm drain manhole cover",
    ],
    conv_en=[
        "I need a manhole icon for the street map",
        "add a manhole cover symbol to the utility app",
        "show a round manhole in the road illustration",
        "use a manhole icon for underground access",
    ],
    typo_en=["manhoel cover", "mnahole grate", "sewar manhole", "manhle street"],
    bnd_en=[
        "floor drain for water drainage", "metal grate over road drain",
        "drainage grate on sidewalk", "storm drain with grate cover",
        "linear floor drain in bathroom", "square drain grate pattern",
    ],
    valid_en=["manhole cover on street", "sewer manhole access", "round manhole cover"],
    test_en=["manhole", "sewer manhole", "street manhole cover"],
)

process_icon("map",
    st_en=["address", "coordinates", "destination", "gps", "localize", "location", "map", "navigation", "paper", "pin", "place", "point of interest", "position", "route", "travel", "world"],
    pst_en=[
        "find address on map", "map showing address location",
        "coordinates on map", "map with coordinate grid",
        "destination on map", "map showing destination",
        "GPS map view", "GPS navigation map",
        "localize on map", "map to localize position",
        "location on map", "map showing current location",
        "paper map icon", "folded map symbol",
        "navigation map", "map for navigation",
        "paper map folded", "physical paper map",
        "pin on map", "map with pin marking place",
        "place on map", "map showing place",
        "point of interest on map", "map with interest points",
        "position on map", "map showing position",
        "route on map", "map with route path",
        "travel map", "map for travel planning",
        "world map", "map of the world",
    ],
    reg_en=[
        "folded road map for navigation", "paper map with routes",
        "road map with directions", "geographic map showing regions",
        "street map for finding places", "tourist map of city",
        "map with roads and landmarks", "printed map for navigation",
        "topographic map of terrain", "map for finding directions",
    ],
    conv_en=[
        "I need a map icon for the navigation screen",
        "add a paper map symbol to the travel section",
        "show a folded map for the directions feature",
        "use the map icon for the geography module",
    ],
    typo_en=["nap navigation map", "mpa of the world", "worl map", "navigaiton mpa"],
    bnd_en=[
        "map with location pin dropped on it", "globe showing continents",
        "map with a destination marker", "3D globe icon for world view",
        "map with GPS pin marker", "rotating globe animation",
    ],
    valid_en=["folded paper map", "navigation map icon", "world map overview"],
    test_en=["map", "paper map", "navigation map"],
)

process_icon("map-location",
    st_en=["address", "coordinates", "destination", "gps", "localize", "location", "map", "navigation", "paper", "pin", "place", "point of interest", "position", "route", "travel"],
    pst_en=[
        "map location showing address", "address marked on map location",
        "map with coordinate location", "map location at coordinates",
        "map location at destination", "destination marked on map",
        "GPS location on map", "map location GPS marker",
        "localize on map with marker", "map location to localize",
        "map showing location marker", "location pin on map",
        "map with location marker", "location marked on map",
        "navigation map with location", "map location for navigation",
        "paper map with location pin", "location marked on paper map",
        "pin on map for location", "map with location pin",
        "place marked on map", "map location for a place",
        "point of interest on map", "map marking point of interest",
        "position marked on map", "map showing current position",
        "route to location on map", "map location along route",
        "travel destination on map", "map location for travel",
    ],
    reg_en=[
        "folded map with pin marker", "map with location dot",
        "navigation map with destination pin", "paper map showing specific place",
        "map with marked location", "map icon with location indicator",
        "geographic map with marker", "city map with location pin",
        "road map with marked destination", "map with position marker",
    ],
    conv_en=[
        "I need a map with a location pin icon",
        "add a map with marker to the navigation screen",
        "show a map icon with a location dot on it",
        "use the map location icon for directions",
    ],
    typo_en=["mpa with locaiton", "map locaiton pin", "locaiotn map marker", "mpa location pin"],
    bnd_en=[
        "plain folded map without any markers", "single location dot on screen",
        "map with no pins or markers", "round dot indicating position",
        "empty road map for navigation", "blue dot for current location",
    ],
    valid_en=["map with location pin", "navigation map with marker", "map showing destination"],
    test_en=["map location", "map with pin", "map location icon"],
)

process_icon("map-pin",
    st_en=["address", "coordinates", "destination", "gps", "localize", "location", "map", "marker", "navigation", "pin", "place", "position", "pushpin", "travel"],
    pst_en=[
        "pin marking address on map", "map pin for address",
        "pin at coordinates", "map pin for coordinates",
        "destination map pin", "pin marking destination",
        "GPS map pin", "pin for GPS location",
        "localize with map pin", "pin to localize position",
        "location pin on map", "map pin showing location",
        "map with drop pin", "drop pin on map",
        "map marker pin", "marker pin for location",
        "navigation map pin", "pin for navigation",
        "map pin symbol", "classic map pin",
        "pin marking a place", "map pin for specific place",
        "map pin at position", "position marker pin",
        "pushpin on map", "round pushpin on paper map",
        "travel pin on map", "map pin for travel destination",
    ],
    reg_en=[
        "red pin dropped on map", "drop a pin at this location",
        "map marker indicating place", "pin to mark meeting point",
        "location pin for restaurant", "place a pin on destination",
        "red teardrop pin marker", "GPS pin on map screen",
        "save location with a pin", "share location with map pin",
    ],
    conv_en=[
        "I need a map pin icon to mark a location",
        "add a drop pin icon to the map feature",
        "show a location pin for the destination",
        "use the map pin icon for saved places",
    ],
    typo_en=["map pni location", "mpa pin marker", "locaiton pin map", "nav pin drpo"],
    bnd_en=[
        "round location dot pulsing on screen", "thumbtack pinning paper to board",
        "circular location indicator dot", "pushpin through document paper",
        "blue circle location dot", "thumbtack attaching note to wall",
    ],
    valid_en=["map pin marker", "drop pin on map", "location pin"],
    test_en=["map pin", "drop pin location", "map pin marker"],
)

process_icon("marker",
    st_en=["design", "edit", "modify", "sharpie", "update", "write"],
    pst_en=[
        "marker for design work", "design with a marker",
        "edit with a marker", "use marker to edit document",
        "modify with marker pen", "marker to modify artwork",
        "sharpie marker pen", "permanent sharpie marker",
        "update notes with marker", "marker to update labels",
        "write with a marker", "marker for writing on whiteboard",
    ],
    reg_en=[
        "thick tip marker pen", "permanent marker for labeling",
        "whiteboard marker for drawing", "felt tip marker pen",
        "color marker for artwork", "marker pen with cap",
        "highlighter marker pen", "black marker for writing",
        "dry erase marker", "thick marker for bold text",
    ],
    conv_en=[
        "I need a marker icon for the drawing tool",
        "add a marker pen symbol for the edit feature",
        "show a thick marker for the annotation tool",
        "use a marker icon for the note-taking feature",
    ],
    typo_en=["markre pen", "merker design", "sharipe marker", "marke write"],
    bnd_en=[
        "ballpoint pen for writing notes", "wooden pencil for drawing",
        "fountain pen for calligraphy", "pencil for sketching designs",
        "gel pen for smooth writing", "mechanical pencil for precision",
    ],
    valid_en=["marker pen icon", "permanent marker", "marker for writing"],
    test_en=["marker", "marker pen", "permanent marker pen"],
)

process_icon("mask-ventilator",
    st_en=["breath", "gas", "mask", "oxygen", "respirator", "ventilator"],
    pst_en=[
        "mask for breathing assistance", "breathing mask ventilator",
        "gas mask for protection", "ventilator gas mask",
        "ventilator mask icon", "medical mask ventilator",
        "oxygen mask ventilator", "oxygen delivery mask",
        "respirator mask ventilator", "respirator for clean air",
        "ventilator mask for ICU", "medical ventilator mask",
    ],
    reg_en=[
        "medical oxygen delivery mask", "hospital ventilator face mask",
        "ICU breathing assistance mask", "anesthesia mask for surgery",
        "respiratory support mask", "emergency oxygen mask",
        "breathing apparatus face mask", "ventilator mask with tubes",
        "clinical respirator mask", "medical grade breathing mask",
    ],
    conv_en=[
        "I need a ventilator mask icon for the medical app",
        "add a breathing mask symbol for the ICU section",
        "show an oxygen mask for the respiratory care feature",
        "use the ventilator mask icon for medical equipment",
    ],
    typo_en=["ventilatro mask", "mask ventiltor", "oxgen mask", "respiratir mask"],
    bnd_en=[
        "disposable surgical face mask flat", "N95 respirator mask rectangle",
        "cloth face mask for pandemic", "medical surgical mask tied behind ear",
        "face covering mask for COVID protection", "flat paper surgical mask folded",
    ],
    valid_en=["ventilator mask for breathing", "oxygen mask medical", "respirator ventilator mask"],
    test_en=["mask ventilator", "medical breathing mask", "oxygen ventilator mask"],
)

process_icon("masks-theater",
    st_en=["art", "comedy", "mask", "perform", "performing", "performing arts", "theater", "theatre", "tragedy"],
    pst_en=[
        "theater arts masks symbol", "performing art masks",
        "comedy theater mask", "comedy and tragedy masks",
        "drama masks symbol", "theater mask pair",
        "perform on stage masks", "masks for stage performance",
        "performing arts masks", "theater masks for performing",
        "performing arts mask symbol", "masks icon for performing arts",
        "theater masks icon", "classic theater masks symbol",
        "theatre drama masks", "theatre comedy tragedy masks",
        "tragedy mask symbol", "comedy and tragedy masks pair",
    ],
    reg_en=[
        "comedy and tragedy theater masks", "two drama masks happy and sad",
        "greek theater mask symbol", "drama club mask icon",
        "smiling and frowning theater masks", "performing arts symbol masks",
        "theater arts icon masks", "happy sad drama masks",
        "theatrical mask pair symbol", "drama mask comedy tragedy",
    ],
    conv_en=[
        "I need the theater masks icon for the arts section",
        "add drama masks for the performing arts feature",
        "show comedy and tragedy masks for the theater app",
        "use the theater masks symbol for the drama club",
    ],
    typo_en=["theather masks", "theatr comedy mask", "tradgedy mask", "comeyd theater mask"],
    bnd_en=[
        "medical oxygen ventilator mask", "decorative masquerade ball mask",
        "breathing apparatus medical mask", "venetian masquerade costume mask",
        "hospital respiratory mask device", "fancy masquerade mask with feathers",
    ],
    valid_en=["theater comedy tragedy masks", "drama masks symbol", "performing arts theater masks"],
    test_en=["theater masks", "comedy tragedy masks", "drama masks"],
)

process_icon("maximize",
    st_en=["arrows", "bigger", "enlarge", "expand", "fullscreen", "maximize", "resize", "scale", "size"],
    pst_en=[
        "arrows pointing outward to maximize", "maximize with outward arrows",
        "make window bigger maximize", "bigger screen maximize button",
        "enlarge window to maximize", "maximize to enlarge view",
        "expand to fullscreen", "expand window with maximize",
        "fullscreen mode maximize", "maximize to fullscreen",
        "maximize window button", "maximize to full size",
        "resize to maximize window", "maximize resize button",
        "scale up to maximize", "maximize and scale window",
        "increase size with maximize", "maximize to full size view",
    ],
    reg_en=[
        "expand window to full screen", "make window as large as possible",
        "fullscreen button icon", "expand arrows pointing outward",
        "enlarge content to fill screen", "maximize button in window corner",
        "full screen mode activation", "resize window to maximum",
        "grow window to fill display", "expand video to full screen",
    ],
    conv_en=[
        "I need a maximize button for the window controls",
        "add the fullscreen maximize icon to the toolbar",
        "show an expand button to enlarge the view",
        "use the maximize icon to fill the screen",
    ],
    typo_en=["maximze button", "fulscreen maximize", "expnad window", "maximise fullscren"],
    bnd_en=[
        "minimize button to shrink window", "collapse arrows pointing inward",
        "shrink window to taskbar icon", "minimize to reduce window size",
        "compress view to smaller size", "collapse panel to hide content",
    ],
    valid_en=["maximize window fullscreen", "expand to full screen", "maximize button icon"],
    test_en=["maximize", "fullscreen maximize", "expand window"],
)

process_icon("meat",
    st_en=["beef", "bone", "ham", "meat", "meat on bone", "mutton", "pork", "veal"],
    pst_en=[
        "beef meat on bone", "beef cut with bone",
        "meat with bone", "bone with meat attached",
        "ham meat on bone", "ham bone icon",
        "meat icon on bone", "grilled meat on bone",
        "classic meat on bone", "cooked meat on bone symbol",
        "mutton leg meat", "mutton on bone",
        "pork rib on bone", "pork meat on bone",
        "veal meat with bone", "veal chop on bone",
    ],
    reg_en=[
        "cooked meat leg on bone", "barbecue meat on a bone",
        "roasted meat haunch", "caveman style meat on bone",
        "grilled drumstick with bone", "meat food icon for restaurant",
        "T-bone steak concept", "roast leg of lamb",
        "grilled meat portion", "meat meal icon on bone",
    ],
    conv_en=[
        "I need a meat icon for the restaurant menu",
        "add a meat on bone symbol to the food section",
        "show a cooked meat icon for the BBQ feature",
        "use a meat icon for the protein food category",
    ],
    typo_en=["maat on bone", "meatr on boen", "beff meat", "prk meat bone"],
    bnd_en=[
        "chicken drumstick leg piece", "raw beef steak on plate",
        "grilled chicken leg quarter", "thick ribeye steak cut",
        "fried chicken drumstick piece", "beef strip loin steak",
    ],
    valid_en=["meat on bone icon", "cooked meat leg", "BBQ meat on bone"],
    test_en=["meat", "meat on bone", "grilled meat icon"],
)

process_icon("memory",
    st_en=["DIMM", "RAM", "hardware", "storage", "technology"],
    pst_en=[
        "DIMM memory module", "DIMM RAM stick",
        "RAM memory stick", "RAM module for computer",
        "memory hardware component", "computer hardware memory",
        "memory storage module", "RAM storage component",
        "memory technology hardware", "computer technology memory",
    ],
    reg_en=[
        "RAM stick for computer", "memory module for laptop",
        "DDR4 memory module", "computer RAM chip",
        "memory upgrade stick", "DIMM slot memory card",
        "server memory module", "computer memory hardware",
        "RAM module icon", "memory stick for PC",
    ],
    conv_en=[
        "I need a RAM icon for the hardware settings",
        "add a memory module symbol to the system info screen",
        "show a RAM stick icon for the memory section",
        "use a memory icon for the computer specs feature",
    ],
    typo_en=["RAM moemry", "memry module", "hardwre memory", "DIMM mmodule"],
    bnd_en=[
        "computer processor microchip", "hard drive for data storage",
        "SSD solid state drive", "CPU chip on motherboard",
        "hard disk drive platter", "processor chip for computer",
    ],
    valid_en=["RAM memory module", "computer memory stick", "DIMM hardware memory"],
    test_en=["memory", "RAM stick", "computer memory module"],
)

process_icon("meter",
    st_en=["electricity", "transmission", "utilities"],
    pst_en=[
        "electricity meter reading", "electric meter for power usage",
        "power transmission meter", "meter for transmission monitoring",
        "utilities meter icon", "meter for utilities tracking",
    ],
    reg_en=[
        "electric meter for measuring power", "utility meter on wall",
        "gas and electric meter", "smart electricity meter",
        "power consumption meter", "home energy meter reading",
        "digital utility meter", "analog electric meter dial",
        "meter for tracking electricity usage", "kilowatt hour meter",
    ],
    conv_en=[
        "I need an electricity meter icon for the energy app",
        "add a utility meter symbol to the home screen",
        "show a power meter icon for tracking consumption",
        "use a meter icon for the utilities section",
    ],
    typo_en=["meterl electricity", "electrcity metter", "eletric meter", "utliities meter"],
    bnd_en=[
        "pressure gauge with dial", "thermometer showing temperature",
        "speedometer gauge reading", "fuel gauge for car",
        "temperature thermometer icon", "analog gauge dial meter",
    ],
    valid_en=["electricity meter reading", "utility meter icon", "power meter"],
    test_en=["meter", "electricity meter", "utility meter"],
)

process_icon("microchip",
    st_en=["cpu", "hardware", "processor", "technology"],
    pst_en=[
        "cpu microchip processor", "microchip for CPU",
        "hardware microchip component", "computer hardware microchip",
        "processor microchip chip", "microchip as processor",
        "technology microchip icon", "microchip technology symbol",
    ],
    reg_en=[
        "integrated circuit chip", "computer processor chip",
        "silicon microchip component", "chip with circuit traces",
        "CPU processor die", "microprocessor chip icon",
        "electronic circuit chip", "semiconductor chip component",
        "computer chip square", "microchip with pins",
    ],
    conv_en=[
        "I need a microchip icon for the processor settings",
        "add a chip symbol to the hardware section",
        "show a processor chip for the tech specs page",
        "use the microchip icon for the AI chip feature",
    ],
    typo_en=["microchpi processor", "microchip prcessor", "cpuu microchip", "hardwre chip"],
    bnd_en=[
        "RAM stick memory module", "circuit board with components",
        "motherboard printed circuit board", "memory DIMM module",
        "PCB with soldered parts", "server motherboard layout",
    ],
    valid_en=["microchip processor icon", "CPU chip hardware", "integrated circuit chip"],
    test_en=["microchip", "processor chip", "CPU microchip"],
)

process_icon("microphone",
    st_en=["address", "audio", "information", "podcast", "public", "record", "sing", "sound", "talking", "voice"],
    pst_en=[
        "microphone for public address", "address system microphone",
        "microphone audio input", "audio recording microphone",
        "information desk microphone", "microphone for announcements",
        "podcast microphone", "microphone for podcast recording",
        "public speaking microphone", "microphone for public events",
        "record with microphone", "microphone for recording voice",
        "microphone for singing", "sing into microphone",
        "microphone for capturing sound", "sound input microphone",
        "talking into microphone", "microphone for talking",
        "voice microphone icon", "microphone for voice input",
    ],
    reg_en=[
        "classic condenser microphone", "handheld microphone for singing",
        "desktop microphone for recording", "podcast recording microphone",
        "stage microphone for performance", "studio microphone icon",
        "standing microphone on stage", "USB microphone for streaming",
        "karaoke microphone icon", "recording studio microphone",
    ],
    conv_en=[
        "I need a microphone icon for the voice input feature",
        "add a microphone symbol for the podcast section",
        "show a mic icon for the recording function",
        "use a microphone icon for the speak button",
    ],
    typo_en=["micropohne recording", "micrphone for singing", "mircophone voice", "microphne podcast"],
    bnd_en=[
        "microphone with sound wave lines", "headset with built-in microphone",
        "microphone with audio levels shown", "headphone and microphone combo",
        "microphone with mute indicator", "gaming headset with microphone arm",
    ],
    valid_en=["microphone for recording", "podcast microphone icon", "voice input microphone"],
    test_en=["microphone", "recording microphone", "mic icon"],
)

process_icon("microscope",
    st_en=["covid-19", "electron", "knowledge", "lens", "microscope", "optics", "science", "shrink", "testing", "tool"],
    pst_en=[
        "microscope for COVID-19 research", "microscope studying covid virus",
        "electron microscope device", "electron microscope for nano viewing",
        "microscope for scientific knowledge", "knowledge gained through microscope",
        "microscope lens for magnification", "objective lens on microscope",
        "microscope icon", "laboratory microscope symbol",
        "optics microscope", "optical microscope for biology",
        "science microscope symbol", "scientific microscope lab icon",
        "microscope to view tiny things", "shrink view with microscope lens",
        "microscope for lab testing", "testing samples with microscope",
        "microscope laboratory tool", "tool for scientific observation",
    ],
    reg_en=[
        "laboratory optical microscope", "biology lab microscope",
        "compound microscope for cells", "medical research microscope",
        "science class microscope", "light microscope for specimens",
        "pathology microscope tool", "microscope for viewing samples",
        "research lab microscope icon", "classroom biology microscope",
    ],
    conv_en=[
        "I need a microscope icon for the science app",
        "add a microscope symbol to the lab section",
        "show a microscope for the biology research feature",
        "use a microscope icon for the testing module",
    ],
    typo_en=["microsocpe lab", "mircroscope science", "microscoep lens", "micrscope tool"],
    bnd_en=[
        "telescope for stargazing at night", "handheld magnifying glass lens",
        "refracting telescope on tripod", "detective magnifying glass icon",
        "astronomical telescope pointing up", "zoom lens magnifying glass",
    ],
    valid_en=["laboratory microscope", "science microscope symbol", "optical microscope icon"],
    test_en=["microscope", "lab microscope", "science microscope"],
)

process_icon("minimize",
    st_en=["collapse", "fullscreen", "minimize", "move", "resize", "shrink", "smaller"],
    pst_en=[
        "collapse to minimize window", "minimize by collapsing panel",
        "exit fullscreen to minimize", "minimize from fullscreen mode",
        "minimize window button", "minimize to taskbar",
        "move and minimize window", "minimize and move window",
        "resize to minimize", "minimize resize control",
        "shrink window to minimize", "minimize to shrink view",
        "make window smaller minimize", "minimize for smaller window",
    ],
    reg_en=[
        "shrink window to taskbar", "minimize button in window bar",
        "collapse content to smaller size", "reduce window to icon",
        "minimize to dock on Mac", "hide window with minimize",
        "compress panel to header", "minimize video player",
        "shrink to thumbnail", "make window small minimize",
    ],
    conv_en=[
        "I need a minimize button for the window controls",
        "add a minimize icon to collapse the panel",
        "show a shrink icon for the video player",
        "use the minimize button to reduce the window",
    ],
    typo_en=["minimze button", "miniimize window", "colapese minimize", "minimise wndow"],
    bnd_en=[
        "maximize button to make window full screen", "expand arrows pointing outward",
        "enlarge window to maximum size", "fullscreen button in corner",
        "expand panel to show more content", "maximize video to fill screen",
    ],
    valid_en=["minimize window button", "collapse to minimize", "shrink window minimize"],
    test_en=["minimize", "minimize window", "shrink minimize"],
)

process_icon("mobile",
    st_en=["android", "call", "cell", "cell phone", "device", "mobile", "mobile phone", "number", "phone", "screen", "telephone", "text"],
    pst_en=[
        "android mobile phone", "mobile phone for android",
        "mobile phone for calling", "call on mobile device",
        "cell phone mobile", "mobile cell phone icon",
        "cell phone device icon", "cell phone mobile symbol",
        "mobile device icon", "mobile phone device",
        "mobile phone icon", "mobile device symbol",
        "mobile phone symbol", "mobile phone icon flat",
        "mobile phone number", "dial a number on mobile",
        "phone mobile icon", "phone icon for mobile",
        "mobile phone screen", "phone screen display",
        "mobile telephone device", "telephone mobile icon",
        "text on mobile phone", "send text with mobile",
    ],
    reg_en=[
        "smartphone mobile device", "touch screen phone",
        "handheld mobile device", "modern smartphone icon",
        "mobile phone with screen", "cell phone for calls and texts",
        "phone device icon", "flat screen smartphone",
        "mobile device for apps", "pocket mobile phone",
    ],
    conv_en=[
        "I need a mobile phone icon for the contact section",
        "add a phone symbol for the call feature",
        "show a smartphone icon for the mobile settings",
        "use a mobile icon for the device screen",
    ],
    typo_en=["moible phone", "moblie device", "cellpohne mobile", "telephoen mobile"],
    bnd_en=[
        "tablet device with large touchscreen", "office landline telephone handset",
        "iPad tablet computer device", "desktop phone with receiver",
        "large screen tablet computer", "corded telephone receiver",
    ],
    valid_en=["mobile phone icon", "smartphone device symbol", "cell phone icon"],
    test_en=["mobile", "mobile phone", "smartphone icon"],
)

process_icon("money-bill",
    st_en=["buy", "cash", "checkout", "coupon", "investment", "money", "payment", "premium", "price", "purchase", "revenue", "salary"],
    pst_en=[
        "money bill to buy items", "use cash bill for buying",
        "cash money bill", "dollar bill cash payment",
        "checkout with money bill", "money bill at checkout",
        "coupon like a money bill", "money bill coupon deal",
        "money bill for investment", "invest with cash money bill",
        "money bill icon", "bill of money symbol",
        "money bill for payment", "pay with a money bill",
        "premium cash money", "money bill for premium service",
        "money bill showing price", "price shown on money bill",
        "purchase with money bill", "money bill for purchase",
        "revenue shown as money bill", "money bill for revenue tracking",
        "salary paid in money bills", "money bill for salary icon",
    ],
    reg_en=[
        "dollar bill currency icon", "paper money banknote",
        "cash payment symbol", "green dollar bill icon",
        "paper currency note", "money bill for transactions",
        "banknote cash symbol", "paper money icon",
        "currency bill icon", "folded dollar bill",
    ],
    conv_en=[
        "I need a money bill icon for the payment section",
        "add a cash icon for the checkout feature",
        "show a dollar bill for the finance module",
        "use a money icon for the salary calculator",
    ],
    typo_en=["mony bill cash", "moeny payment", "cassh bill", "purchse money"],
    bnd_en=[
        "bank check for payment", "credit card for online purchase",
        "payment check with signature line", "debit card payment method",
        "written check from checkbook", "contactless credit card icon",
    ],
    valid_en=["money bill cash icon", "dollar bill payment", "cash money symbol"],
    test_en=["money bill", "cash icon", "dollar bill"],
)

process_icon("money-check",
    st_en=["bank check", "buy", "checkout", "cheque", "money", "payment", "price", "purchase", "salary"],
    pst_en=[
        "bank check for payment", "money check from bank",
        "write a check to buy", "use check for buying",
        "check payment at checkout", "money check for checkout",
        "cheque payment method", "cheque written to payee",
        "money check icon", "check for money transfer",
        "check payment symbol", "pay with a money check",
        "price paid by check", "money check for price payment",
        "purchase with a check", "check for making purchase",
        "salary check payment", "paycheck salary symbol",
    ],
    reg_en=[
        "personal check for payment", "write a check to someone",
        "paycheck with amount and signature", "bank check payment method",
        "paper check for bill payment", "check book payment icon",
        "issued check for services", "cashier's check symbol",
        "paper check payment", "check payment for rent",
    ],
    conv_en=[
        "I need a check payment icon for the finance app",
        "add a bank check symbol for the payment options",
        "show a paycheck icon for the salary feature",
        "use a check icon for the payment method selection",
    ],
    typo_en=["mnoney check", "mony cheque", "paymetn check", "chequue payment"],
    bnd_en=[
        "paper cash dollar bill", "receipt printout after purchase",
        "folded dollar bill currency", "transaction receipt slip",
        "banknote paper money", "purchase receipt with items listed",
    ],
    valid_en=["money check payment", "bank check icon", "paycheck symbol"],
    test_en=["money check", "bank check", "check payment"],
)

process_icon("monkey",
    st_en=["animal", "banana", "fauna", "mammal", "monke", "monkey", "tail"],
    pst_en=[
        "monkey animal icon", "animal monkey symbol",
        "monkey with banana", "monkey eating banana",
        "monkey fauna icon", "monkey in wildlife fauna",
        "monkey mammal animal", "mammal monkey icon",
        "monke funny icon", "monke meme reference",
        "monkey icon", "cartoon monkey symbol",
        "monkey with long tail", "monkey tail hanging",
    ],
    reg_en=[
        "cartoon monkey face", "jungle monkey swinging",
        "cute monkey icon", "monkey hanging from branch",
        "primate monkey symbol", "monkey for zoo icon",
        "playful monkey drawing", "monkey profile icon",
        "chimp-like monkey icon", "small monkey on tree",
    ],
    conv_en=[
        "I need a monkey icon for the animal section",
        "add a monkey symbol to the zoo app",
        "show a monkey for the jungle theme",
        "use a monkey icon for the wildlife feature",
    ],
    typo_en=["monnkey animal", "monky with tail", "mnkey jungle", "mokey banana"],
    bnd_en=[
        "large silverback gorilla silhouette", "chimpanzee sitting in jungle",
        "great ape primate face", "gorilla beating chest icon",
        "chimpanzee with tool use", "enormous gorilla standing upright",
    ],
    valid_en=["monkey animal icon", "cartoon monkey symbol", "monkey with tail"],
    test_en=["monkey", "monkey animal", "cartoon monkey"],
)

process_icon("moped",
    st_en=["delivery", "motorbike", "scooter"],
    pst_en=[
        "moped for delivery service", "delivery moped scooter",
        "moped small motorbike", "motorbike moped style",
        "moped scooter vehicle", "scooter moped icon",
    ],
    reg_en=[
        "small motorized scooter", "two-wheel moped vehicle",
        "moped for city commuting", "delivery food moped",
        "electric moped scooter", "moped with small engine",
        "urban moped transportation", "moped for short trips",
        "moped with step-through frame", "motorized moped bike",
    ],
    conv_en=[
        "I need a moped icon for the delivery app",
        "add a scooter symbol for the vehicle section",
        "show a moped for the urban transport feature",
        "use the moped icon for the delivery method",
    ],
    typo_en=["mopde scooter", "moepd delivery", "scooteer moped", "motrobike moped"],
    bnd_en=[
        "full size motorcycle with engine", "bicycle with pedals and two wheels",
        "heavy motorbike on highway", "road bicycle for cycling",
        "sport motorcycle on road", "city bicycle for commuting",
    ],
    valid_en=["moped delivery scooter", "small motorized moped", "moped vehicle icon"],
    test_en=["moped", "moped scooter", "delivery moped"],
)

process_icon("mortar-pestle",
    st_en=["crush", "culinary", "grind", "medical", "mix", "pharmacy", "prescription", "spices"],
    pst_en=[
        "crush spices in mortar pestle", "mortar pestle to crush herbs",
        "culinary mortar and pestle", "mortar pestle for cooking",
        "grind spices with pestle", "mortar to grind ingredients",
        "medical mortar and pestle", "pharmacy mortar pestle medical",
        "mix ingredients in mortar", "mortar pestle to mix spices",
        "pharmacy mortar and pestle symbol", "pharmacist mortar pestle",
        "prescription mortar pestle", "mortar pestle for prescriptions",
        "grind spices in mortar", "mortar pestle for spices",
    ],
    reg_en=[
        "kitchen mortar and pestle", "grind herbs with mortar pestle",
        "stone mortar bowl with pestle", "spice grinding mortar pestle",
        "pharmacist symbol mortar pestle", "crushing garlic in mortar",
        "ancient cooking tool mortar pestle", "ceramic mortar with pestle",
        "grind peppercorns in mortar", "traditional mortar and pestle",
    ],
    conv_en=[
        "I need a mortar and pestle icon for the recipe app",
        "add the pharmacy symbol mortar pestle to the app",
        "show a grinding bowl icon for the spice section",
        "use a mortar pestle icon for the pharmacy feature",
    ],
    typo_en=["motar pestle", "mortar pestal", "pharamcy mortar", "grind mortir"],
    bnd_en=[
        "ceramic mixing bowl for baking", "glass jar with sealed lid",
        "wooden salad bowl on table", "mason jar with metal lid",
        "large mixing bowl for dough", "storage jar with cork stopper",
    ],
    valid_en=["mortar and pestle icon", "pharmacy mortar pestle symbol", "grind spices mortar pestle"],
    test_en=["mortar pestle", "mortar and pestle", "pharmacy mortar pestle"],
)

print("\nAll 30 icons processed successfully!")
