#!/usr/bin/env python3
"""Expand training data for icons 476-485 (lowest train coverage batch 1)."""
from pathlib import Path
import csv, json

icons_dir = Path("icons")

def append_csv(path, rows):
    with open(path, "a", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerows(rows)

def expand(icon, new_en, new_ru):
    en_path = icons_dir / icon / "train_en.csv"
    ru_path = icons_dir / icon / "train_ru.csv"
    assert len(new_en) == len(new_ru), f"{icon}: EN/RU mismatch {len(new_en)} vs {len(new_ru)}"
    append_csv(en_path, [(t, icon) for t in new_en])
    append_csv(ru_path, [(t, icon) for t in new_ru])
    print(f"  {icon}: +{len(new_en)} rows")

# ── 476: hockey-puck ──────────────────────────────────────────────────────────
expand("hockey-puck",
    new_en=[
        "hockey",
        "ice hockey",
        "puck",
        "hockey puck sliding on ice",
        "hard rubber puck on the rink",
        "puck glides across the ice",
        "ice hockey puck hit with a stick",
        "hockey icon for a sports tracker",
        "rubber puck spinning on the rink",
        "black hockey puck on white ice",
        "pick up the puck off the boards",
        "center ice puck drop to start the game",
        "slap shot sends the puck flying",
        "puck deflects off the goalie pad",
        "puck icon for an NHL fan app",
        "hockey practice drill with the puck",
        "street hockey with a plastic puck",
        "puck smacks the post and bounces away",
        "dribble the puck into the offensive zone",
        "track the puck during a fast break",
        "face-off at center ice tonight",
        "NHL power play this season",
        "join the rec hockey league this winter",
        "hockey score tracker for the season",
        "buy tickets to the NHL game",
        "watch the game on hockey night",
        "I need a puck icon for my hockey app",
        "add a hockey puck to the sports section",
        "show a puck for the ice sports feature",
        "use the hockey icon for the sports tracker",
        "hockye puck on the ice",
        "pukc sliding across the rink",
        "ice hocky practice tonight",
        "nhl plaoffs game",
        "sllapshot on goal",
    ],
    new_ru=[
        "хоккей",
        "хоккей на льду",
        "шайба",
        "хоккейная шайба скользит по льду",
        "резиновая шайба на катке",
        "шайба едет по льду",
        "шайба отбита клюшкой",
        "иконка хоккея для спортивного трекера",
        "резиновая шайба вращается на льду",
        "чёрная шайба на белом льду",
        "подобрать шайбу от борта",
        "вбрасывание шайбы в центре площадки",
        "броском от синей шайба летит в ворота",
        "шайба отскакивает от вратаря",
        "иконка шайбы для приложения НХЛ",
        "тренировочное упражнение с шайбой",
        "уличный хоккей с пластиковой шайбой",
        "шайба попадает в штангу",
        "войти в зону атаки с шайбой",
        "отследить шайбу в быстрой атаке",
        "вбрасывание в центре площадки",
        "большинство в этом матче НХЛ",
        "записаться в любительскую хоккейную лигу",
        "трекер счёта хоккейных матчей",
        "купить билеты на игру НХЛ",
        "смотреть матч в хоккейный вечер",
        "нужна иконка шайбы для хоккейного приложения",
        "добавить шайбу в раздел спорта",
        "показать шайбу для раздела ледовых видов спорта",
        "использовать иконку хоккея для спортивного трекера",
        "хокейная шайба на льду",
        "шайбу скользит по катку",
        "трениовка хокея сегодня вечером",
        "плей-оф НХЛ матч",
        "щелчок по воротам",
    ],
)

# ── 477: inbox ────────────────────────────────────────────────────────────────
expand("inbox",
    new_en=[
        "inbox",
        "messages",
        "unread",
        "new email arrived in the inbox",
        "inbox showing unread message count",
        "inbox tray for incoming mail",
        "email inbox with unread notifications",
        "message waiting in the inbox folder",
        "incoming mail tray icon in an email app",
        "tray icon for received messages",
        "inbox zero goal for the week",
        "empty inbox after clearing all messages",
        "download incoming messages to the inbox",
        "message count badge on the inbox icon",
        "check new messages in the inbox",
        "notification of incoming mail",
        "inbox folder showing latest emails",
        "inbox icon for a mail or messaging app",
        "I need an inbox icon for my mail app",
        "add an inbox symbol to the messages section",
        "show inbox for the email tray feature",
        "use the inbox icon for the notifications screen",
        "inbbox notification badge",
        "unrread mesage in inbox",
        "chek the emial inbox",
        "inobx icon for mail app",
        "new emials in inbox",
    ],
    new_ru=[
        "входящие",
        "сообщения",
        "непрочитанные",
        "новое письмо пришло во входящие",
        "входящие с количеством непрочитанных",
        "лоток входящих сообщений",
        "папка входящих с уведомлениями",
        "сообщение ожидает во входящих",
        "иконка лотка входящей почты",
        "иконка лотка полученных сообщений",
        "нулевой inbox на этой неделе",
        "пустая папка после очистки всех писем",
        "загрузить входящие сообщения",
        "счётчик непрочитанных на иконке входящих",
        "проверить новые сообщения во входящих",
        "уведомление о входящей почте",
        "папка входящих с последними письмами",
        "иконка входящих для почтового приложения",
        "нужна иконка входящих для почтового приложения",
        "добавить символ входящих в раздел сообщений",
        "показать входящие для функции почтового лотка",
        "использовать иконку входящих для экрана уведомлений",
        "значок уведомлений входящих",
        "непрочитанное сообщение во входящих",
        "проверить почту во входящих",
        "иконка входящих для почтового приложения",
        "новые письма во входящих",
    ],
)

# ── 478: jug-bottle ───────────────────────────────────────────────────────────
expand("jug-bottle",
    new_en=[
        "jug",
        "bottle",
        "container",
        "large plastic jug with a handle",
        "gallon jug of water in the fridge",
        "jug icon for a water tracking app",
        "refillable jug at the water dispenser",
        "plastic jug with screw-top lid",
        "bottle and jug for bulk liquid storage",
        "reuse the jug to reduce plastic waste",
        "bulk liquid container for storage",
        "large container icon in a hydration app",
        "pour water from the jug into a glass",
        "jug and bottle icon for a recycling feature",
        "detergent bottle with a handle loop",
        "large jug used to carry juice or water",
        "empty the bottle into the jug",
        "recycled jug for eco-friendly storage",
        "I need a jug icon for my drink tracker app",
        "add a bottle symbol to the containers section",
        "show a jug for the water storage feature",
        "use the jug-bottle icon for the liquid tracker",
        "jug bottel for water stoage",
        "recycle the jugg and botles",
        "fil up the jugg",
        "plasstic jug with a handel",
        "buy a refillable jugg",
    ],
    new_ru=[
        "кувшин",
        "бутылка",
        "контейнер",
        "большой пластиковый кувшин с ручкой",
        "галлонный кувшин с водой в холодильнике",
        "иконка кувшина для приложения учёта воды",
        "многоразовый кувшин у диспенсера",
        "пластиковый кувшин с завинчивающейся крышкой",
        "бутылка и кувшин для хранения жидкостей",
        "использовать кувшин повторно для сокращения пластика",
        "большой контейнер для хранения жидкостей",
        "иконка крупного контейнера в приложении гидратации",
        "перелить воду из кувшина в стакан",
        "иконка кувшина и бутылки для функции переработки",
        "бутылка моющего средства с петлей-ручкой",
        "большой кувшин для сока или воды",
        "перелить содержимое бутылки в кувшин",
        "переработанный кувшин для экологичного хранения",
        "нужна иконка кувшина для трекера напитков",
        "добавить символ бутылки в раздел контейнеров",
        "показать кувшин для функции хранения воды",
        "использовать иконку кувшина для трекера жидкостей",
        "кувшин и бутылка для хранения воды",
        "сдать кувшины и бутылки на переработку",
        "наполнить кувшин",
        "пластиковый кувшин с ручкой",
        "купить многоразовый кувшин",
    ],
)

# ── 479: dolly ────────────────────────────────────────────────────────────────
expand("dolly",
    new_en=[
        "dolly",
        "hand truck",
        "hand truck icon for moving heavy items",
        "two-wheeled dolly for boxes",
        "stack boxes on the hand truck",
        "wheel the dolly down the hallway",
        "hand truck with a vertical steel frame",
        "move appliances with the dolly cart",
        "hand truck icon for a warehouse app",
        "dolly with bungee cord securing boxes",
        "tilt the hand truck back to roll",
        "hand truck wheels on uneven pavement",
        "move the server rack on the dolly",
        "delivery guy with a hand truck at the door",
        "office move with a hand truck and boxes",
        "hand truck folded for storage in the van",
        "mover pushing a loaded dolly to the truck",
        "I need a dolly icon for my warehouse app",
        "add a hand truck symbol to the moving section",
        "show a dolly for the freight feature",
        "use the dolly icon for the moving tools screen",
        "hnad truck for heavy boxes",
        "dolley to move equipmet",
        "hand trkc for moving furnitre",
        "stack boxs on the dolly",
        "wheel the doly to the elevator",
    ],
    new_ru=[
        "тележка",
        "ручная тележка",
        "иконка ручной тележки для переноски тяжестей",
        "двухколёсная тележка для коробок",
        "сложить коробки на ручную тележку",
        "прокатить тележку по коридору",
        "ручная тележка с вертикальной стальной рамой",
        "перевезти технику на тележке",
        "иконка тележки для приложения склада",
        "тележка с резиновым шнуром для фиксации коробок",
        "наклонить тележку для движения",
        "колёса тележки на неровном покрытии",
        "переместить серверную стойку на тележке",
        "курьер с тележкой у двери",
        "переезд офиса с тележкой и коробками",
        "сложить тележку для хранения в фургоне",
        "грузчик катит нагруженную тележку к машине",
        "нужна иконка тележки для складского приложения",
        "добавить символ тележки в раздел переноски",
        "показать тележку для функции перевозки грузов",
        "использовать иконку тележки на экране инструментов переезда",
        "ручная тележка для тяжёлых коробок",
        "тележка для перевозки оборудования",
        "тележка для перемещения мебели",
        "сложить коробки на тележку",
        "прокатить тележку к лифту",
    ],
)

# ── 480: egg-fried ────────────────────────────────────────────────────────────
expand("egg-fried",
    new_en=[
        "fried egg",
        "breakfast",
        "fried egg icon for a breakfast app",
        "egg white set with golden yolk",
        "crack an egg into a hot buttered pan",
        "sizzling egg in the cast iron skillet",
        "over-easy egg flipped once in the pan",
        "sunny-side-up egg with a runny yolk",
        "fried egg on a toasted English muffin",
        "breakfast icon featuring a fried egg",
        "fried egg with crispy edges in the pan",
        "fried egg with salt and pepper on top",
        "greasy spoon diner-style fried egg",
        "fried egg sitting next to toast",
        "egg cooked in olive oil on the stovetop",
        "morning meal icon with a fried egg",
        "fried egg with strips of bacon",
        "restaurant breakfast with fried eggs and hash browns",
        "I need a fried egg icon for my recipe app",
        "add a fried egg symbol to the breakfast section",
        "show a fried egg for the morning meal feature",
        "use the fried egg icon for the breakfast tracker",
        "sunyside up egge",
        "fried eggg in the pan",
        "fry an egg for brekfast",
        "egg sunny sied up",
        "crispy frid egg",
    ],
    new_ru=[
        "яичница",
        "завтрак",
        "иконка яичницы для приложения завтрака",
        "белок застыл, желток золотистый",
        "разбить яйцо на горячую сковороду с маслом",
        "яйцо шипит на чугунной сковороде",
        "яичница «в мешочек» перевёрнутая один раз",
        "яичница «глазунья» с жидким желтком",
        "яичница на поджаренном маффине",
        "иконка завтрака с яичницей",
        "яичница с хрустящими краями",
        "яичница с солью и перцем",
        "яичница в стиле дайнера",
        "яичница рядом с тостом",
        "яйцо жарится в оливковом масле",
        "иконка утреннего приёма пищи с яичницей",
        "яичница с ломтиками бекона",
        "завтрак в ресторане с яичницей и хэш-брауном",
        "нужна иконка яичницы для приложения рецептов",
        "добавить символ яичницы в раздел завтрака",
        "показать яичницу для функции утреннего питания",
        "использовать иконку яичницы для трекера завтрака",
        "яичница глазунья",
        "яичница на сковороде",
        "пожарить яйцо на завтрак",
        "яйцо солнечной стороной вверх",
        "хрустящая яичница",
    ],
)

# ── 481: fork ─────────────────────────────────────────────────────────────────
expand("fork",
    new_en=[
        "fork",
        "cutlery",
        "dining",
        "fork on the left side of the plate",
        "stainless steel dining fork",
        "restaurant icon with a fork",
        "fork and knife table setting",
        "salad fork smaller than the dinner fork",
        "sterling silver fork from the cutlery set",
        "plastic fork in a takeout bag",
        "dessert fork placed above the plate",
        "fork icon for a meal tracking app",
        "fork tines pointing upward in a holder",
        "toss salad with a fork",
        "twirl pasta around the fork",
        "buffet fork beside the serving dish",
        "dishwasher with forks in the utensil basket",
        "buy a fork and spoon set for the kitchen",
        "I need a fork icon for my restaurant app",
        "add a fork symbol to the dining section",
        "show a fork for the meal logging feature",
        "use the fork icon for the eating habits tracker",
        "fork and kinfe set",
        "dinnner frork",
        "frok for the salad",
        "cutrely set for dinner",
        "resturant table with frok and knife",
    ],
    new_ru=[
        "вилка",
        "столовые приборы",
        "ужин",
        "вилка слева от тарелки",
        "обеденная вилка из нержавеющей стали",
        "иконка ресторана с вилкой",
        "сервировка: вилка и нож",
        "салатная вилка меньше обеденной",
        "серебряная вилка из набора столовых приборов",
        "пластиковая вилка в пакете на вынос",
        "вилка для десерта над тарелкой",
        "иконка вилки для приложения учёта питания",
        "зубцы вилки смотрят вверх в стакане",
        "перемешать салат вилкой",
        "накрутить пасту на вилку",
        "вилка для шведского стола у блюда",
        "посудомойка с вилками в лотке",
        "купить набор вилок и ложек для кухни",
        "нужна иконка вилки для приложения ресторана",
        "добавить символ вилки в раздел питания",
        "показать вилку для функции журнала приёмов пищи",
        "использовать иконку вилки для трекера пищевых привычек",
        "набор вилок и ножей",
        "обеденная вилка",
        "вилка для салата",
        "набор столовых приборов",
        "ресторанный стол с вилкой и ножом",
    ],
)

# ── 482: light-ceiling ────────────────────────────────────────────────────────
expand("light-ceiling",
    new_en=[
        "ceiling light",
        "overhead light",
        "light fixture",
        "ceiling light fixture in the living room",
        "flush-mount ceiling light on a white ceiling",
        "round ceiling light casting even glow",
        "recessed ceiling light grid in an office",
        "overhead light switched on in the kitchen",
        "ceiling light icon for a smart home app",
        "LED ceiling panel for energy-efficient lighting",
        "pendant light hanging from the ceiling",
        "dimmer controlling the ceiling light brightness",
        "ceiling light flickering and needs a new bulb",
        "bright ceiling light for the home office",
        "turn off the ceiling light before bed",
        "install a new ceiling light fixture",
        "ceiling light icon for a home automation app",
        "I need a ceiling light icon for my smart home app",
        "add a ceiling light symbol to the lighting section",
        "show a ceiling light for the room control feature",
        "use the light fixture icon for the smart home screen",
        "celing lght fixutre",
        "overhad light in the room",
        "recesed celing lamp",
        "trun on the celing light",
        "instal celing light fixutre",
    ],
    new_ru=[
        "потолочный светильник",
        "верхний свет",
        "светильник",
        "потолочный светильник в гостиной",
        "накладной потолочный светильник на белом потолке",
        "круглый потолочный светильник с равномерным светом",
        "встраиваемые потолочные светильники в офисе",
        "верхний свет включён на кухне",
        "иконка потолочного светильника для умного дома",
        "светодиодная потолочная панель для экономии энергии",
        "подвесной светильник на потолке",
        "диммер регулирует яркость потолочного света",
        "мигает потолочная лампа — нужно заменить",
        "яркий потолочный светильник для домашнего офиса",
        "выключить потолочный свет перед сном",
        "установить новый потолочный светильник",
        "иконка потолочного света для приложения умный дом",
        "нужна иконка потолочного светильника для умного дома",
        "добавить символ потолочного света в раздел освещения",
        "показать потолочный светильник для управления комнатой",
        "использовать иконку светильника на экране умного дома",
        "потолочный светильник",
        "верхний свет в комнате",
        "встраиваемый потолочный светильник",
        "включить верхний свет",
        "установить потолочный светильник",
    ],
)

# ── 483: pallet-box ───────────────────────────────────────────────────────────
expand("pallet-box",
    new_en=[
        "pallet",
        "pallet box",
        "freight pallet",
        "wooden pallet with a sealed cardboard box",
        "pallet wrapped in stretch film for shipping",
        "forklift lifts pallet box in a warehouse",
        "pallet icon for a supply chain app",
        "pallet box scanned at the loading dock",
        "stacked pallet boxes in a distribution center",
        "goods secured to pallet with strapping",
        "pallet manifest printed for customs",
        "pallet box tracked by barcode in WMS",
        "heavy pallet moved by forklift in storage",
        "pallet with multiple boxes bound together",
        "shipping label on pallet box for freight",
        "pallet box icon for inventory management",
        "I need a pallet icon for my logistics app",
        "add a pallet box symbol to the warehouse view",
        "show a pallet for the freight tracking feature",
        "use the pallet-box icon for the shipment screen",
        "palelt box in warehoues",
        "frieght pallett with box",
        "palet scaned at dock",
        "inventroy on palelt",
        "palet bxo for shipping",
    ],
    new_ru=[
        "поддон",
        "коробка на поддоне",
        "грузовой поддон",
        "деревянный поддон с запечатанной картонной коробкой",
        "поддон обёрнут стрейч-плёнкой для отправки",
        "вилочный погрузчик поднимает поддон на складе",
        "иконка поддона для приложения цепочки поставок",
        "коробка на поддоне отсканирована на погрузочном доке",
        "штабель коробок на поддонах в распределительном центре",
        "товары закреплены на поддоне лентой",
        "накладная поддона для таможни",
        "поддон отслеживается по штрихкоду в WMS",
        "тяжёлый поддон перемещает погрузчик",
        "поддон с несколькими скреплёнными коробками",
        "наклейка на коробке поддона для грузовой доставки",
        "иконка поддона для управления запасами",
        "нужна иконка поддона для приложения логистики",
        "добавить символ поддона в вид склада",
        "показать поддон для функции отслеживания груза",
        "использовать иконку поддона на экране отправлений",
        "коробка на поддоне на складе",
        "грузовой поддон с коробкой",
        "поддон отсканирован у дока",
        "инвентарь на поддоне",
        "поддон для отправки товара",
    ],
)

# ── 484: fish ─────────────────────────────────────────────────────────────────
expand("fish",
    new_en=[
        "fish",
        "seafood",
        "aquatic",
        "freshwater fish swimming upstream",
        "saltwater fish darting through the reef",
        "fish icon for a seafood restaurant app",
        "grilled fish fillet with lemon and herbs",
        "fish caught on a fishing trip at the lake",
        "pet fish swimming in a home aquarium",
        "tropical fish with bright stripes",
        "fish tank cleaned every weekend",
        "fish silhouette icon for a marine app",
        "buy fresh fish from the market",
        "fish served whole in a Mediterranean dish",
        "smoked fish on a charcuterie board",
        "tuna fish in a can for a quick salad",
        "aquarium fish feeding time",
        "I need a fish icon for my recipe app",
        "add a fish symbol to the seafood section",
        "show a fish for the aquarium tracker feature",
        "use the fish icon for the seafood category",
        "freesh fish for dinner",
        "fissh swimming in tank",
        "grilled fihs fillet",
        "go fihsing at the lake",
        "peT fish in aquaruim",
    ],
    new_ru=[
        "рыба",
        "морепродукты",
        "водное существо",
        "пресноводная рыба плывёт против течения",
        "морская рыба у рифа",
        "иконка рыбы для приложения рыбного ресторана",
        "жареное рыбное филе с лимоном и зеленью",
        "пойманная рыба на рыбалке у озера",
        "домашняя рыбка в аквариуме",
        "тропическая рыбка с яркими полосами",
        "аквариум чистят каждые выходные",
        "силуэт рыбы для морского приложения",
        "купить свежую рыбу на рынке",
        "рыба подаётся целиком в средиземноморском блюде",
        "копчёная рыба на сырной тарелке",
        "консервированный тунец для быстрого салата",
        "кормление рыбок в аквариуме",
        "нужна иконка рыбы для приложения рецептов",
        "добавить символ рыбы в раздел морепродуктов",
        "показать рыбу для трекера аквариума",
        "использовать иконку рыбы для категории морепродуктов",
        "свежая рыба на ужин",
        "рыбка плавает в аквариуме",
        "жареное рыбное филе",
        "рыбалка на озере",
        "домашняя рыбка в аквариуме",
    ],
)

# ── 485: futbol ───────────────────────────────────────────────────────────────
expand("futbol",
    new_en=[
        "futbol",
        "soccer",
        "football",
        "black and white soccer ball icon",
        "classic soccer ball with pentagon panels",
        "soccer ball kicked during practice",
        "round soccer ball on the grass field",
        "soccer ball bouncing off the crossbar",
        "header with the soccer ball near the goal",
        "penalty kick with the soccer ball",
        "soccer ball icon for a sports app",
        "futbol icon for a South American sports app",
        "soccer ball rolling into the net",
        "celebrate the goal with the soccer ball",
        "dribble the soccer ball past the defender",
        "soccer ball with sponsor logo in a stadium",
        "inflate the soccer ball before the match",
        "I need a soccer ball icon for my sports app",
        "add a futbol symbol to the team sports section",
        "show a soccer ball for the match tracker feature",
        "use the futbol icon for the football category",
        "socer ball on the field",
        "futball icon for sports app",
        "soccerr ball kicked at goal",
        "penalti kick in footbal",
        "footbal rollig into the net",
    ],
    new_ru=[
        "футбол",
        "футбольный мяч",
        "мяч",
        "чёрно-белая иконка футбольного мяча",
        "классический футбольный мяч с пятиугольными панелями",
        "футбольный мяч в ударе на тренировке",
        "круглый футбольный мяч на травяном поле",
        "мяч отскакивает от перекладины",
        "удар головой у ворот",
        "пенальти по футбольному мячу",
        "иконка мяча для спортивного приложения",
        "иконка футбола для южноамериканского спортивного приложения",
        "мяч закатывается в сетку",
        "отпраздновать гол с мячом",
        "обвести защитника с мячом",
        "футбольный мяч с логотипом спонсора на стадионе",
        "накачать мяч перед матчем",
        "нужна иконка мяча для спортивного приложения",
        "добавить символ футбола в раздел командных видов спорта",
        "показать мяч для трекера матчей",
        "использовать иконку футбола для категории футбол",
        "мяч на поле",
        "иконка футбола для спортивного приложения",
        "футбольный мяч в ударе по воротам",
        "пенальти в футболе",
        "мяч закатывается в сетку",
    ],
)

print("Done. Run merge_icon_datasets.py to rebuild.")
