#!/usr/bin/env python3
"""Task-008 Part 2: fire, flag-checkered, flask, floppy-disk, flower"""

from gen_icons_task_008_common import gen

# ── fire ──────────────────────────────────────────────────────────────────────
gen("fire",
    en=[
        "burn",
        "fire",
        "flame",
        "heat",
        "hot",
        "lit",
        "campfire",
        "fireplace",
        "bonfire",
        "fire drill",
        "fire extinguisher",
        "fire safety",
        "wildfire",
        "fire pit",
        "gas stove",
        "firewood",
        "fire alarm",
        "fire hazard",
        "build a campfire at the site",
        "check the fire extinguisher expiration",
        "schedule the fire drill at work",
        "clean the fireplace before winter",
        "buy firewood for the weekend",
        "light the fire pit in the backyard",
        "check fire alarm batteries",
        "review fire safety plan at the office",
        "report the fire hazard to management",
        "put out the campfire before leaving",
        "roast marshmallows over the fire",
        "the fireplace needs cleaning",
        "bonfire night on Saturday",
        "start the fire for the barbecue",
        "replace the fire extinguisher in the kitchen",
        "attend the fire safety training",
        "call the fire department about the smoke",
        "stack firewood in the garage",
        "the fire alarm went off again",
        "keep children away from the fire",
        "fire pit gathering this Friday",
        "turn off the gas stove after cooking",
        "fireplace logs delivered tomorrow",
        "practice the fire escape route",
        "plan the bonfire for the beach party",
        "check the smoke detectors",
        "fire up the grill for dinner",
        "wildfire evacuation plan ready",
        "candle flame too close to the curtain",
        "hot coals still in the fire pit",
        "book the campsite with a fire ring",
        "fire warden check on Thursday",
        "get the chimney cleaned before using the fireplace",
        "gather kindling for the campfire",
        "fire burning in the hearth all evening",
        "bild a campfier at the site",
        "chek fire alarm bateries",
        "clean the firplace before winter",
        "buy firwood for the weekend",
        "roast marshmellows over the fire",
    ],
    ru=[
        "гореть",
        "огонь",
        "пламя",
        "жар",
        "горячий",
        "зажжённый",
        "костёр",
        "камин",
        "костёр на пляже",
        "пожарная тревога",
        "огнетушитель",
        "пожарная безопасность",
        "лесной пожар",
        "кострище",
        "газовая плита",
        "дрова",
        "пожарная сигнализация",
        "пожарная опасность",
        "развести костёр на стоянке",
        "проверить срок годности огнетушителя",
        "назначить пожарную тревогу на работе",
        "почистить камин перед зимой",
        "купить дрова на выходные",
        "разжечь кострище во дворе",
        "проверить батарейки в пожарной сигнализации",
        "пересмотреть план пожарной безопасности в офисе",
        "сообщить руководству о пожарной опасности",
        "потушить костёр перед уходом",
        "жарить зефир на костре",
        "камин нужно почистить",
        "вечер у костра в субботу",
        "разжечь огонь для барбекю",
        "заменить огнетушитель на кухне",
        "пройти обучение по пожарной безопасности",
        "позвонить в пожарную из-за дыма",
        "сложить дрова в гараже",
        "пожарная сигнализация опять сработала",
        "не подпускать детей к огню",
        "посиделки у кострища в пятницу",
        "выключить газовую плиту после готовки",
        "дрова для камина привезут завтра",
        "потренировать маршрут эвакуации при пожаре",
        "запланировать костёр на пляжной вечеринке",
        "проверить датчики дыма",
        "разжечь гриль к ужину",
        "план эвакуации при лесном пожаре готов",
        "пламя свечи слишком близко к шторе",
        "горячие угли ещё в кострище",
        "забронировать кемпинг с костровым кольцом",
        "проверка пожарного инспектора в четверг",
        "прочистить дымоход перед растопкой камина",
        "собрать хворост для костра",
        "огонь горит в камине весь вечер",
        "развести кастёр на стоянке",
        "праверить батарейки в сигнализации",
        "почистть камин перед зимой",
        "купть дрова на выходные",
        "жарить зифир на костре",
    ],
    de=[
        "brennen",
        "Feuer",
        "Flamme",
        "Hitze",
        "heiß",
        "angezündet",
        "Lagerfeuer",
        "Kamin",
        "Feueralarm",
        "Feuerlöscher",
        "Brandsicherheit",
        "Waldbrand",
        "Feuerstelle",
        "Gasherd",
        "Brennholz",
        "Rauchmelder",
        "Brandgefahr",
        "Grillfeuer",
        "ein Lagerfeuer am Platz machen",
        "Ablaufdatum des Feuerlöschers prüfen",
        "Feueralarm bei der Arbeit einplanen",
        "den Kamin vor dem Winter reinigen",
        "Brennholz fürs Wochenende kaufen",
        "die Feuerstelle im Garten anzünden",
        "Batterien im Rauchmelder prüfen",
        "Brandsicherheitsplan im Büro überprüfen",
        "Brandgefahr der Leitung melden",
        "das Lagerfeuer vor dem Gehen löschen",
        "Marshmallows über dem Feuer rösten",
        "der Kamin muss gereinigt werden",
        "Lagerfeuerabend am Samstag",
        "das Feuer für den Grill anzünden",
        "den Feuerlöscher in der Küche austauschen",
        "an der Brandsicherheitsschulung teilnehmen",
        "die Feuerwehr wegen Rauch anrufen",
        "Brennholz in der Garage stapeln",
        "der Rauchmelder ist wieder losgegangen",
        "Kinder vom Feuer fernhalten",
        "Feuerstellen-Treffen am Freitag",
        "den Gasherd nach dem Kochen ausschalten",
        "Kaminholz wird morgen geliefert",
        "den Fluchtweg bei Feuer üben",
        "das Lagerfeuer für die Strandparty planen",
        "die Rauchmelder überprüfen",
        "den Grill zum Abendessen anheizen",
        "Evakuierungsplan für Waldbrand bereit",
        "Kerzenflamme zu nah am Vorhang",
        "heiße Kohlen noch in der Feuerstelle",
        "Campingplatz mit Feuerring buchen",
        "Brandschutz-Kontrolle am Donnerstag",
        "den Schornstein vor der Kaminnutzung reinigen lassen",
        "Anzündholz fürs Lagerfeuer sammeln",
        "Feuer brennt den ganzen Abend im Kamin",
        "ein Lagerfeur am Platz machen",
        "Batterein im Rauchmelder prüfen",
        "den Kamn vor dem Winter reinigen",
        "Brnnholz fürs Wochenende kaufen",
        "Marshmellows über dem Feuer rösten",
    ],
    ja=[
        "燃やす",
        "火",
        "炎",
        "熱",
        "熱い",
        "火がついた",
        "キャンプファイヤー",
        "暖炉",
        "焚き火",
        "火災訓練",
        "消火器",
        "防火",
        "山火事",
        "焚き火台",
        "ガスコンロ",
        "薪",
        "火災報知器",
        "火災の危険",
        "キャンプ場で焚き火をする",
        "消火器の有効期限を確認する",
        "職場の火災訓練を予定する",
        "冬の前に暖炉を掃除する",
        "週末用の薪を買う",
        "裏庭の焚き火台に火をつける",
        "火災報知器の電池を確認する",
        "オフィスの防火計画を見直す",
        "火災の危険を管理者に報告する",
        "帰る前にキャンプファイヤーを消す",
        "焚き火でマシュマロを焼く",
        "暖炉の掃除が必要だ",
        "土曜日に焚き火の夜",
        "バーベキュー用に火をおこす",
        "キッチンの消火器を交換する",
        "防火訓練に参加する",
        "煙について消防署に電話する",
        "ガレージに薪を積む",
        "火災報知器がまた鳴った",
        "子供を火に近づけない",
        "金曜日に焚き火台で集まり",
        "料理の後にガスコンロを消す",
        "暖炉用の薪が明日届く",
        "火災時の避難経路を練習する",
        "ビーチパーティー用の焚き火を計画する",
        "煙感知器を確認する",
        "夕食用にグリルに火を入れる",
        "山火事の避難計画を準備する",
        "ろうそくの炎がカーテンに近すぎる",
        "焚き火台にまだ熱い炭がある",
        "焚き火リング付きのキャンプ場を予約する",
        "木曜日に防火検査がある",
        "暖炉を使う前に煙突を掃除してもらう",
        "キャンプファイヤー用の焚き付けを集める",
        "一晩中暖炉で火が燃えている",
        "キャンプ場でたき火をする",
        "消火器のゆうこう期限を確認する",
        "暖炉をそうじする",
        "しゅうまつ用の薪を買う",
        "焚き火でマシュマロをやく",
    ],
    fr=[
        "brûler",
        "feu",
        "flamme",
        "chaleur",
        "chaud",
        "allumé",
        "feu de camp",
        "cheminée",
        "feu de joie",
        "exercice d'incendie",
        "extincteur",
        "sécurité incendie",
        "feu de forêt",
        "brasero",
        "cuisinière à gaz",
        "bois de chauffage",
        "alarme incendie",
        "risque d'incendie",
        "faire un feu de camp sur le site",
        "vérifier la date d'expiration de l'extincteur",
        "planifier l'exercice d'incendie au travail",
        "nettoyer la cheminée avant l'hiver",
        "acheter du bois de chauffage pour le week-end",
        "allumer le brasero dans le jardin",
        "vérifier les piles de l'alarme incendie",
        "revoir le plan de sécurité incendie au bureau",
        "signaler le risque d'incendie à la direction",
        "éteindre le feu de camp avant de partir",
        "faire griller des guimauves sur le feu",
        "la cheminée doit être nettoyée",
        "soirée feu de joie samedi",
        "allumer le feu pour le barbecue",
        "remplacer l'extincteur dans la cuisine",
        "suivre la formation sécurité incendie",
        "appeler les pompiers à cause de la fumée",
        "empiler le bois de chauffage dans le garage",
        "l'alarme incendie s'est encore déclenchée",
        "éloigner les enfants du feu",
        "rassemblement autour du brasero vendredi",
        "éteindre la cuisinière à gaz après la cuisson",
        "bûches pour la cheminée livrées demain",
        "pratiquer le chemin d'évacuation en cas d'incendie",
        "planifier le feu de joie pour la fête à la plage",
        "vérifier les détecteurs de fumée",
        "allumer le gril pour le dîner",
        "plan d'évacuation en cas de feu de forêt prêt",
        "flamme de la bougie trop près du rideau",
        "braises encore chaudes dans le brasero",
        "réserver le camping avec emplacement feu",
        "inspection sécurité incendie jeudi",
        "faire ramoner la cheminée avant de l'utiliser",
        "ramasser du petit bois pour le feu de camp",
        "feu qui brûle dans la cheminée toute la soirée",
        "faire un feu de campe sur le site",
        "vérifier les pilles de l'alarme",
        "netoyer la cheminée avant l'hiver",
        "acheter du bios de chauffage",
        "faire griler des guimauves sur le feu",
    ],
    es=[
        "quemar",
        "fuego",
        "llama",
        "calor",
        "caliente",
        "encendido",
        "fogata",
        "chimenea",
        "hoguera",
        "simulacro de incendio",
        "extintor",
        "seguridad contra incendios",
        "incendio forestal",
        "brasero",
        "cocina de gas",
        "leña",
        "alarma de incendio",
        "riesgo de incendio",
        "hacer una fogata en el campamento",
        "revisar la fecha de caducidad del extintor",
        "programar el simulacro de incendio en el trabajo",
        "limpiar la chimenea antes del invierno",
        "comprar leña para el fin de semana",
        "encender el brasero en el patio",
        "revisar las pilas de la alarma de incendio",
        "repasar el plan de seguridad contra incendios en la oficina",
        "reportar el riesgo de incendio a la dirección",
        "apagar la fogata antes de irse",
        "asar malvaviscos en el fuego",
        "la chimenea necesita limpieza",
        "noche de hoguera el sábado",
        "encender el fuego para la barbacoa",
        "cambiar el extintor de la cocina",
        "asistir a la formación de seguridad contra incendios",
        "llamar a los bomberos por el humo",
        "apilar la leña en el garaje",
        "la alarma de incendio se disparó otra vez",
        "mantener a los niños lejos del fuego",
        "reunión en el brasero el viernes",
        "apagar la cocina de gas después de cocinar",
        "leña para la chimenea llega mañana",
        "practicar la ruta de evacuación en caso de incendio",
        "planear la hoguera para la fiesta en la playa",
        "revisar los detectores de humo",
        "encender la parrilla para la cena",
        "plan de evacuación por incendio forestal listo",
        "llama de la vela demasiado cerca de la cortina",
        "brasas calientes todavía en el brasero",
        "reservar el camping con zona de fuego",
        "inspección de seguridad contra incendios el jueves",
        "hacer limpiar la chimenea antes de usarla",
        "recoger leña menuda para la fogata",
        "fuego ardiendo en la chimenea toda la noche",
        "hacer una fogta en el campamento",
        "revisar las pilas de la alaram",
        "limpiar la chimenea antes del invieno",
        "comprar leñá para el fin de semana",
        "asar malvviscos en el fuego",
    ],
)

# ── flag-checkered ────────────────────────────────────────────────────────────
gen("flag-checkered",
    en=[
        "finish",
        "finish line",
        "nascar",
        "race",
        "racing",
        "win",
        "checkered flag",
        "go-kart",
        "Formula 1",
        "sprint",
        "victory",
        "marathon",
        "championship",
        "grand prix",
        "lap",
        "podium",
        "rally",
        "race day",
        "wave the checkered flag at the finish",
        "cross the finish line first",
        "watch the Formula 1 race on Sunday",
        "go to the car racing event",
        "celebrate the race victory",
        "watch a NASCAR race this weekend",
        "go to the local go-kart race",
        "complete the marathon run",
        "finish the challenge by Friday",
        "reach the goal before the deadline",
        "attend the grand prix this summer",
        "buy tickets for the race day",
        "cheer for the driver on the last lap",
        "plan the championship watch party",
        "sign up for the 5K race",
        "the race starts at noon",
        "pick up the race bib tomorrow",
        "finish the project before the deadline",
        "rally race tickets sold out fast",
        "watch the podium ceremony",
        "train for the sprint race next month",
        "the car crossed the finish line first",
        "celebrate finishing the project",
        "kids go-kart race on Saturday",
        "complete the final lap",
        "race results are posted online",
        "set a new personal record at the race",
        "register for the charity marathon",
        "book flights to the grand prix",
        "wear team colors on race day",
        "victory lap around the track",
        "meet at the starting line",
        "track day at the local circuit",
        "wach the formula 1 raice",
        "wave the checkerd flag",
        "cross the finsh line",
        "celebarte the race win",
        "finsh the project by Friday",
    ],
    ru=[
        "финиш",
        "финишная черта",
        "наскар",
        "гонка",
        "гоночный",
        "победа",
        "клетчатый флаг",
        "картинг",
        "Формула 1",
        "спринт",
        "триумф",
        "марафон",
        "чемпионат",
        "гран-при",
        "круг",
        "подиум",
        "ралли",
        "день гонок",
        "помахать клетчатым флагом на финише",
        "пересечь финишную черту первым",
        "посмотреть гонку Формулы 1 в воскресенье",
        "сходить на автогоночное мероприятие",
        "отпраздновать победу в гонке",
        "посмотреть гонку NASCAR в эти выходные",
        "сходить на местные гонки на картинге",
        "завершить марафонский забег",
        "завершить испытание к пятнице",
        "достичь цели до дедлайна",
        "посетить гран-при этим летом",
        "купить билеты на день гонок",
        "болеть за гонщика на последнем круге",
        "организовать вечеринку на чемпионат",
        "записаться на забег на 5 км",
        "гонка начинается в полдень",
        "забрать номер участника забега завтра",
        "закончить проект до дедлайна",
        "билеты на ралли быстро раскупили",
        "посмотреть церемонию награждения на подиуме",
        "тренироваться к спринтерской гонке в следующем месяце",
        "машина пересекла финишную черту первой",
        "отпраздновать завершение проекта",
        "детские гонки на картинге в субботу",
        "пройти финальный круг",
        "результаты гонки опубликованы онлайн",
        "установить новый личный рекорд на гонке",
        "зарегистрироваться на благотворительный марафон",
        "забронировать билеты на самолёт к гран-при",
        "надеть цвета команды в день гонок",
        "круг почёта по трассе",
        "встретиться у стартовой линии",
        "трек-день на местном автодроме",
        "посмотерть гонку Формулы 1",
        "помахть клетчатым флагом",
        "пересечь финшную черту",
        "отпразновать победу в гонке",
        "закончть проект до дедлайна",
    ],
    de=[
        "Ziel",
        "Ziellinie",
        "NASCAR",
        "Rennen",
        "Motorsport",
        "Sieg",
        "Zielflagge",
        "Go-Kart",
        "Formel 1",
        "Sprint",
        "Triumph",
        "Marathon",
        "Meisterschaft",
        "Grand Prix",
        "Runde",
        "Podium",
        "Rallye",
        "Renntag",
        "die Zielflagge am Ziel schwenken",
        "als Erster die Ziellinie überqueren",
        "am Sonntag das Formel-1-Rennen schauen",
        "zum Autorennen gehen",
        "den Sieg im Rennen feiern",
        "am Wochenende ein NASCAR-Rennen schauen",
        "zum lokalen Go-Kart-Rennen gehen",
        "den Marathonlauf beenden",
        "die Aufgabe bis Freitag abschließen",
        "das Ziel vor der Deadline erreichen",
        "diesen Sommer den Grand Prix besuchen",
        "Tickets für den Renntag kaufen",
        "den Fahrer in der letzten Runde anfeuern",
        "eine Meisterschafts-Watchparty planen",
        "sich für den 5-km-Lauf anmelden",
        "das Rennen startet um zwölf Uhr mittags",
        "die Startnummer morgen abholen",
        "das Projekt vor der Deadline fertigstellen",
        "Rallye-Tickets waren schnell ausverkauft",
        "die Siegerehrung auf dem Podium anschauen",
        "für das Sprintrennen nächsten Monat trainieren",
        "das Auto überquerte als Erstes die Ziellinie",
        "den Projektabschluss feiern",
        "Kinder-Go-Kart-Rennen am Samstag",
        "die letzte Runde fahren",
        "Rennergebnisse sind online veröffentlicht",
        "einen neuen persönlichen Rekord beim Rennen aufstellen",
        "sich für den Wohltätigkeitsmarathon anmelden",
        "Flüge zum Grand Prix buchen",
        "am Renntag Teamfarben tragen",
        "Ehrenrunde auf der Strecke",
        "an der Startlinie treffen",
        "Track-Tag auf der lokalen Rennstrecke",
        "das Formel-1-Renen schauen",
        "die Zeilflagge schwenken",
        "als Erster die Zilllinie überqueren",
        "den Sig im Rennen feiern",
        "das Projekt bis Freitag feritigstellen",
    ],
    ja=[
        "フィニッシュ",
        "ゴールライン",
        "ナスカー",
        "レース",
        "レーシング",
        "勝利",
        "チェッカーフラッグ",
        "ゴーカート",
        "F1",
        "スプリント",
        "優勝",
        "マラソン",
        "選手権",
        "グランプリ",
        "周回",
        "表彰台",
        "ラリー",
        "レースの日",
        "フィニッシュでチェッカーフラッグを振る",
        "一番にゴールラインを越える",
        "日曜日にF1レースを観る",
        "カーレースのイベントに行く",
        "レースの勝利を祝う",
        "今週末NASCARのレースを観る",
        "地元のゴーカートレースに行く",
        "マラソンを完走する",
        "金曜日までにチャレンジを完了する",
        "締め切りまでに目標を達成する",
        "今年の夏にグランプリに行く",
        "レースの日のチケットを買う",
        "最終周でドライバーを応援する",
        "選手権の観戦パーティーを計画する",
        "5キロレースに申し込む",
        "レースは正午に始まる",
        "明日レースのゼッケンを受け取る",
        "締め切り前にプロジェクトを終わらせる",
        "ラリーのチケットがすぐ売り切れた",
        "表彰台のセレモニーを見る",
        "来月のスプリントレースに向けて練習する",
        "車が一番にゴールラインを越えた",
        "プロジェクト完了を祝う",
        "土曜日に子供のゴーカートレース",
        "最終周を走る",
        "レース結果がオンラインで公開された",
        "レースで自己ベストを更新する",
        "チャリティーマラソンに登録する",
        "グランプリへのフライトを予約する",
        "レースの日にチームカラーを着る",
        "トラックでウイニングラップ",
        "スタートラインで集合する",
        "地元のサーキットでトラックデー",
        "F1レースをみる",
        "チェッカーフラグを振る",
        "ゴールラインをこえる",
        "レースのしょうりを祝う",
        "プロジェクトをおわらせる",
    ],
    fr=[
        "arrivée",
        "ligne d'arrivée",
        "NASCAR",
        "course",
        "courses automobiles",
        "victoire",
        "drapeau à damier",
        "karting",
        "Formule 1",
        "sprint",
        "triomphe",
        "marathon",
        "championnat",
        "grand prix",
        "tour",
        "podium",
        "rallye",
        "jour de course",
        "agiter le drapeau à damier à l'arrivée",
        "franchir la ligne d'arrivée en premier",
        "regarder la course de Formule 1 dimanche",
        "aller à l'événement de courses automobiles",
        "célébrer la victoire de la course",
        "regarder une course NASCAR ce week-end",
        "aller à la course de karting locale",
        "terminer le marathon",
        "terminer le défi avant vendredi",
        "atteindre l'objectif avant la date limite",
        "assister au grand prix cet été",
        "acheter des billets pour le jour de course",
        "encourager le pilote dans le dernier tour",
        "organiser une soirée pour le championnat",
        "s'inscrire à la course de 5 km",
        "la course commence à midi",
        "récupérer le dossard demain",
        "finir le projet avant la date limite",
        "les billets du rallye se sont vendus vite",
        "regarder la cérémonie du podium",
        "s'entraîner pour le sprint le mois prochain",
        "la voiture a franchi la ligne d'arrivée en premier",
        "fêter la fin du projet",
        "course de karting pour enfants samedi",
        "boucler le dernier tour",
        "les résultats de la course sont en ligne",
        "établir un nouveau record personnel à la course",
        "s'inscrire au marathon caritatif",
        "réserver les vols pour le grand prix",
        "porter les couleurs de l'équipe le jour de course",
        "tour d'honneur sur le circuit",
        "se retrouver à la ligne de départ",
        "journée circuit sur la piste locale",
        "regarder la course de Formul 1",
        "agiter le drapau à damier",
        "franchir la lgine d'arrivée",
        "célebrer la victoire de la course",
        "finir le proget avant vendredi",
    ],
    es=[
        "meta",
        "línea de meta",
        "NASCAR",
        "carrera",
        "carreras",
        "victoria",
        "bandera a cuadros",
        "karting",
        "Fórmula 1",
        "sprint",
        "triunfo",
        "maratón",
        "campeonato",
        "gran premio",
        "vuelta",
        "podio",
        "rally",
        "día de carrera",
        "agitar la bandera a cuadros en la meta",
        "cruzar la línea de meta en primer lugar",
        "ver la carrera de Fórmula 1 el domingo",
        "ir al evento de carreras de coches",
        "celebrar la victoria en la carrera",
        "ver una carrera de NASCAR este fin de semana",
        "ir a la carrera de karting local",
        "completar el maratón",
        "terminar el reto antes del viernes",
        "alcanzar el objetivo antes de la fecha límite",
        "asistir al gran premio este verano",
        "comprar entradas para el día de carrera",
        "animar al piloto en la última vuelta",
        "organizar una fiesta para el campeonato",
        "inscribirse en la carrera de 5 km",
        "la carrera empieza al mediodía",
        "recoger el dorsal mañana",
        "terminar el proyecto antes de la fecha límite",
        "las entradas del rally se agotaron rápido",
        "ver la ceremonia del podio",
        "entrenar para la carrera de sprint el mes que viene",
        "el coche cruzó la línea de meta primero",
        "celebrar haber terminado el proyecto",
        "carrera de karting infantil el sábado",
        "completar la última vuelta",
        "los resultados de la carrera están en línea",
        "batir un récord personal en la carrera",
        "inscribirse en el maratón solidario",
        "reservar vuelos al gran premio",
        "llevar los colores del equipo el día de carrera",
        "vuelta de honor por la pista",
        "quedar en la línea de salida",
        "día de pista en el circuito local",
        "ver la carrera de Fórmual 1",
        "agitar la bandra a cuadros",
        "cruzar la línea de mta",
        "celebrar la victora en la carrera",
        "termnar el proyecto antes del viernes",
    ],
)

# ── flask ─────────────────────────────────────────────────────────────────────
gen("flask",
    en=[
        "beaker",
        "chemistry",
        "experiment",
        "lab",
        "potion",
        "science",
        "flask",
        "chemicals",
        "liquid",
        "vial",
        "research",
        "lab equipment",
        "test tube",
        "lab safety",
        "solution",
        "reagent",
        "laboratory",
        "lab coat",
        "run the chemistry experiment",
        "set up the lab for testing",
        "mix chemicals for the experiment",
        "measure liquids in the beaker",
        "follow the lab safety rules",
        "record the results of the experiment",
        "pour the solution into the flask",
        "work on a science project",
        "study chemistry for the exam",
        "visit the science museum",
        "buy lab equipment for the school",
        "label the vial correctly",
        "store the sample in a vial",
        "clean the glass beaker after use",
        "handle chemicals with gloves",
        "prepare the reagent for the test",
        "the lab report is due Monday",
        "order new lab supplies",
        "science fair project due next week",
        "measure pH of the solution",
        "heat the solution in the flask",
        "wear a lab coat in the laboratory",
        "calibrate the lab instruments",
        "complete the lab worksheet",
        "the experiment worked on the second try",
        "research paper for chemistry class",
        "sign up for the science club",
        "finish the lab before lunch",
        "double check the chemical formula",
        "safety goggles for the lab",
        "pick up lab supplies at the store",
        "test the hypothesis in the lab",
        "science project presentation Friday",
        "do a scince experiment",
        "mix the chemiacls",
        "measuer liquids in beakre",
        "folow lab safty rules",
        "pour the soluton into the flask",
    ],
    ru=[
        "колба",
        "химия",
        "эксперимент",
        "лаборатория",
        "зелье",
        "наука",
        "мензурка",
        "химикаты",
        "жидкость",
        "пробирка",
        "исследование",
        "лабораторное оборудование",
        "пипетка",
        "техника безопасности в лаборатории",
        "раствор",
        "реагент",
        "лабораторный халат",
        "научный проект",
        "провести химический эксперимент",
        "подготовить лабораторию к тестам",
        "смешать химикаты для эксперимента",
        "отмерить жидкость в мензурке",
        "соблюдать правила безопасности в лаборатории",
        "записать результаты эксперимента",
        "налить раствор в колбу",
        "работать над научным проектом",
        "учить химию к экзамену",
        "сходить в музей науки",
        "купить лабораторное оборудование для школы",
        "правильно подписать пробирку",
        "хранить образец в пробирке",
        "помыть стеклянную мензурку после использования",
        "работать с химикатами в перчатках",
        "подготовить реагент для теста",
        "отчёт по лабораторной до понедельника",
        "заказать новые лабораторные принадлежности",
        "проект к научной ярмарке на следующей неделе",
        "измерить pH раствора",
        "нагреть раствор в колбе",
        "надеть лабораторный халат в лаборатории",
        "откалибровать лабораторные приборы",
        "заполнить рабочий лист по лабораторной",
        "эксперимент получился со второй попытки",
        "научная работа по химии",
        "записаться в научный кружок",
        "закончить лабораторную до обеда",
        "перепроверить химическую формулу",
        "защитные очки для лаборатории",
        "купить лабораторные принадлежности в магазине",
        "проверить гипотезу в лаборатории",
        "презентация научного проекта в пятницу",
        "провести научный эксперемент",
        "смешть химикаты",
        "отмерть жидкость в мензурке",
        "саблюдать правила безопастности",
        "налть раствор в колбу",
    ],
    de=[
        "Becherglas",
        "Chemie",
        "Experiment",
        "Labor",
        "Trank",
        "Wissenschaft",
        "Kolben",
        "Chemikalien",
        "Flüssigkeit",
        "Reagenzglas",
        "Forschung",
        "Laborausrüstung",
        "Pipette",
        "Laborsicherheit",
        "Lösung",
        "Reagenz",
        "Laborkittel",
        "Wissenschaftsprojekt",
        "das Chemie-Experiment durchführen",
        "das Labor für den Test vorbereiten",
        "Chemikalien für das Experiment mischen",
        "Flüssigkeiten im Becherglas abmessen",
        "die Laborsicherheitsregeln befolgen",
        "die Ergebnisse des Experiments aufschreiben",
        "die Lösung in den Kolben gießen",
        "am Wissenschaftsprojekt arbeiten",
        "Chemie für die Prüfung lernen",
        "das Wissenschaftsmuseum besuchen",
        "Laborausrüstung für die Schule kaufen",
        "das Reagenzglas richtig beschriften",
        "die Probe im Reagenzglas aufbewahren",
        "das Becherglas nach Gebrauch reinigen",
        "Chemikalien mit Handschuhen handhaben",
        "das Reagenz für den Test vorbereiten",
        "der Laborbericht ist am Montag fällig",
        "neue Labormaterialien bestellen",
        "Wissenschaftsmesse-Projekt nächste Woche fällig",
        "den pH-Wert der Lösung messen",
        "die Lösung im Kolben erhitzen",
        "einen Laborkittel im Labor tragen",
        "die Laborgeräte kalibrieren",
        "das Labor-Arbeitsblatt ausfüllen",
        "das Experiment hat beim zweiten Versuch funktioniert",
        "Forschungsarbeit für den Chemieunterricht",
        "sich für den Wissenschaftsclub anmelden",
        "das Labor vor dem Mittagessen fertig haben",
        "die chemische Formel doppelt prüfen",
        "Schutzbrille fürs Labor",
        "Laborbedarf im Laden kaufen",
        "die Hypothese im Labor testen",
        "Präsentation des Wissenschaftsprojekts am Freitag",
        "ein Wissenscahfts-Experiment durchführen",
        "die Chemiklaien mischen",
        "Flüssigkeiten im Bechergals abmessen",
        "die Laborsicherheitsreglen befolgen",
        "die Lösung in den Kolbn gießen",
    ],
    ja=[
        "ビーカー",
        "化学",
        "実験",
        "ラボ",
        "薬",
        "科学",
        "フラスコ",
        "薬品",
        "液体",
        "試験管",
        "研究",
        "実験器具",
        "ピペット",
        "実験室の安全",
        "溶液",
        "試薬",
        "白衣",
        "科学プロジェクト",
        "化学の実験を行う",
        "テスト用にラボを準備する",
        "実験のために薬品を混ぜる",
        "ビーカーで液体を量る",
        "実験室の安全規則を守る",
        "実験の結果を記録する",
        "フラスコに溶液を注ぐ",
        "科学プロジェクトに取り組む",
        "試験のために化学を勉強する",
        "科学博物館に行く",
        "学校用の実験器具を買う",
        "試験管に正しくラベルを貼る",
        "試験管にサンプルを保管する",
        "使用後にガラスのビーカーを洗う",
        "手袋をして薬品を扱う",
        "テスト用の試薬を準備する",
        "実験レポートの締め切りは月曜日",
        "新しい実験用品を注文する",
        "来週が科学フェアのプロジェクト締め切り",
        "溶液のpHを測る",
        "フラスコの中の溶液を加熱する",
        "実験室では白衣を着る",
        "実験器具を校正する",
        "実験のワークシートを完成させる",
        "2回目の試みで実験が成功した",
        "化学の授業の研究論文",
        "科学クラブに入る",
        "昼食前に実験を終わらせる",
        "化学式を再確認する",
        "実験室用の保護メガネ",
        "お店で実験用品を買う",
        "ラボで仮説を検証する",
        "金曜日に科学プロジェクトの発表",
        "科学の実験をおこなう",
        "薬品をまぜる",
        "ビーカーで液体をはかる",
        "実験室のあんぜん規則を守る",
        "フラスコに溶液をそそぐ",
    ],
    fr=[
        "bécher",
        "chimie",
        "expérience",
        "labo",
        "potion",
        "science",
        "fiole",
        "produits chimiques",
        "liquide",
        "éprouvette",
        "recherche",
        "équipement de labo",
        "pipette",
        "sécurité au labo",
        "solution",
        "réactif",
        "blouse de labo",
        "projet scientifique",
        "faire l'expérience de chimie",
        "préparer le labo pour les tests",
        "mélanger les produits chimiques pour l'expérience",
        "mesurer les liquides dans le bécher",
        "suivre les règles de sécurité au labo",
        "noter les résultats de l'expérience",
        "verser la solution dans la fiole",
        "travailler sur le projet scientifique",
        "réviser la chimie pour l'examen",
        "visiter le musée des sciences",
        "acheter de l'équipement de labo pour l'école",
        "étiqueter l'éprouvette correctement",
        "conserver l'échantillon dans l'éprouvette",
        "nettoyer le bécher en verre après utilisation",
        "manipuler les produits chimiques avec des gants",
        "préparer le réactif pour le test",
        "le rapport de labo est à rendre lundi",
        "commander de nouvelles fournitures de labo",
        "projet de foire scientifique à rendre la semaine prochaine",
        "mesurer le pH de la solution",
        "chauffer la solution dans la fiole",
        "porter une blouse de labo au laboratoire",
        "calibrer les instruments du labo",
        "remplir la fiche de travail du labo",
        "l'expérience a marché au deuxième essai",
        "devoir de recherche pour le cours de chimie",
        "s'inscrire au club de sciences",
        "finir le labo avant le déjeuner",
        "vérifier deux fois la formule chimique",
        "lunettes de protection pour le labo",
        "acheter des fournitures de labo au magasin",
        "tester l'hypothèse au labo",
        "présentation du projet scientifique vendredi",
        "faire une expérience de sciance",
        "mélanger les produts chimiques",
        "mesurer les liqudes dans le bécher",
        "suivre les règles de sécurtié au labo",
        "verser la soluton dans la fiole",
    ],
    es=[
        "vaso de precipitados",
        "química",
        "experimento",
        "laboratorio",
        "poción",
        "ciencia",
        "matraz",
        "productos químicos",
        "líquido",
        "tubo de ensayo",
        "investigación",
        "equipo de laboratorio",
        "pipeta",
        "seguridad en el laboratorio",
        "solución",
        "reactivo",
        "bata de laboratorio",
        "proyecto científico",
        "hacer el experimento de química",
        "preparar el laboratorio para las pruebas",
        "mezclar productos químicos para el experimento",
        "medir líquidos en el vaso de precipitados",
        "seguir las normas de seguridad del laboratorio",
        "apuntar los resultados del experimento",
        "verter la solución en el matraz",
        "trabajar en el proyecto científico",
        "estudiar química para el examen",
        "visitar el museo de ciencias",
        "comprar equipo de laboratorio para la escuela",
        "etiquetar el tubo de ensayo correctamente",
        "guardar la muestra en el tubo de ensayo",
        "limpiar el vaso de precipitados después de usar",
        "manejar los productos químicos con guantes",
        "preparar el reactivo para la prueba",
        "el informe de laboratorio es para el lunes",
        "pedir nuevos suministros de laboratorio",
        "proyecto de feria de ciencias para la semana que viene",
        "medir el pH de la solución",
        "calentar la solución en el matraz",
        "ponerse la bata en el laboratorio",
        "calibrar los instrumentos del laboratorio",
        "completar la hoja de trabajo del laboratorio",
        "el experimento funcionó al segundo intento",
        "trabajo de investigación para la clase de química",
        "apuntarse al club de ciencias",
        "terminar el laboratorio antes de comer",
        "comprobar dos veces la fórmula química",
        "gafas de protección para el laboratorio",
        "comprar suministros de laboratorio en la tienda",
        "probar la hipótesis en el laboratorio",
        "presentación del proyecto científico el viernes",
        "hacer un experimento de cienca",
        "mezclar los prodcutos químicos",
        "medir líquidos en el vso de precipitados",
        "seguir las normas de seguirdad del laboratorio",
        "verter la solucion en el matraz",
    ],
)

# ── floppy-disk ───────────────────────────────────────────────────────────────
gen("floppy-disk",
    en=[
        "save",
        "storage",
        "floppy disk",
        "backup",
        "file",
        "document",
        "download",
        "floppy",
        "disk",
        "save file",
        "save as",
        "back up data",
        "data storage",
        "save document",
        "save changes",
        "export file",
        "archive",
        "save progress",
        "save the file on the computer",
        "back up data to the drive",
        "download the file to the device",
        "save the document before closing",
        "click save to keep the changes",
        "back up the project file",
        "download the installer file",
        "save work frequently",
        "download and save the attachment",
        "preserve old computer files",
        "export the spreadsheet to a file",
        "save the presentation before the meeting",
        "archive old project files",
        "save progress on the report",
        "back up photos to the external drive",
        "download the PDF and save it",
        "save the draft before switching apps",
        "remember to save before closing",
        "auto-save is turned off fix it",
        "save a copy of the contract",
        "back up the database nightly",
        "export the data as a CSV file",
        "save the receipt as a PDF",
        "back up the phone before updating",
        "download the software update and save",
        "save the form before submitting",
        "archive completed projects",
        "save the edited photo",
        "back up emails to the cloud",
        "save the budget spreadsheet",
        "download the report from the portal",
        "save the meeting notes",
        "quick save before the deadline",
        "back up all files this weekend",
        "sav the documnet",
        "donwload the flie",
        "backup to a dkis",
        "old floppy diks",
        "save the presntation",
    ],
    ru=[
        "сохранить",
        "хранение",
        "дискета",
        "резервная копия",
        "файл",
        "документ",
        "скачать",
        "диск",
        "накопитель",
        "сохранить файл",
        "сохранить как",
        "резервное копирование",
        "хранение данных",
        "сохранить документ",
        "сохранить изменения",
        "экспортировать файл",
        "архив",
        "сохранить прогресс",
        "сохранить файл на компьютере",
        "сделать резервную копию данных на диск",
        "скачать файл на устройство",
        "сохранить документ перед закрытием",
        "нажать сохранить чтобы сохранить изменения",
        "сделать резервную копию файла проекта",
        "скачать установочный файл",
        "чаще сохранять работу",
        "скачать и сохранить вложение",
        "сохранить старые компьютерные файлы",
        "экспортировать таблицу в файл",
        "сохранить презентацию перед встречей",
        "архивировать старые файлы проектов",
        "сохранить прогресс по отчёту",
        "сделать резервную копию фотографий на внешний диск",
        "скачать PDF и сохранить",
        "сохранить черновик перед переключением приложений",
        "не забыть сохранить перед закрытием",
        "автосохранение выключено нужно включить",
        "сохранить копию контракта",
        "ежедневно делать резервную копию базы данных",
        "экспортировать данные в CSV файл",
        "сохранить чек как PDF",
        "сделать резервную копию телефона перед обновлением",
        "скачать обновление и сохранить",
        "сохранить форму перед отправкой",
        "архивировать завершённые проекты",
        "сохранить отредактированное фото",
        "сделать резервную копию писем в облако",
        "сохранить таблицу бюджета",
        "скачать отчёт с портала",
        "сохранить заметки со встречи",
        "быстро сохранить перед дедлайном",
        "сделать резервную копию всех файлов в выходные",
        "сохраниь документ",
        "скачть файл на устройство",
        "резервная копя данных",
        "сохранть изменения",
        "скачать установчный файл",
    ],
    de=[
        "speichern",
        "Speicher",
        "Diskette",
        "Backup",
        "Datei",
        "Dokument",
        "herunterladen",
        "Laufwerk",
        "Festplatte",
        "Datei speichern",
        "Speichern unter",
        "Daten sichern",
        "Datenspeicher",
        "Dokument speichern",
        "Änderungen speichern",
        "Datei exportieren",
        "Archiv",
        "Fortschritt speichern",
        "die Datei auf dem Computer speichern",
        "Daten auf das Laufwerk sichern",
        "die Datei auf das Gerät herunterladen",
        "das Dokument vor dem Schließen speichern",
        "auf Speichern klicken um Änderungen zu behalten",
        "die Projektdatei sichern",
        "die Installationsdatei herunterladen",
        "die Arbeit regelmäßig speichern",
        "den Anhang herunterladen und speichern",
        "alte Computerdateien aufbewahren",
        "die Tabelle als Datei exportieren",
        "die Präsentation vor dem Meeting speichern",
        "alte Projektdateien archivieren",
        "den Fortschritt beim Bericht speichern",
        "Fotos auf die externe Festplatte sichern",
        "die PDF herunterladen und speichern",
        "den Entwurf speichern bevor man die App wechselt",
        "daran denken vor dem Schließen zu speichern",
        "Autospeichern ist aus das muss gefixt werden",
        "eine Kopie des Vertrags speichern",
        "die Datenbank jede Nacht sichern",
        "die Daten als CSV-Datei exportieren",
        "die Quittung als PDF speichern",
        "das Handy vor dem Update sichern",
        "das Software-Update herunterladen und speichern",
        "das Formular vor dem Absenden speichern",
        "abgeschlossene Projekte archivieren",
        "das bearbeitete Foto speichern",
        "E-Mails in die Cloud sichern",
        "die Budget-Tabelle speichern",
        "den Bericht vom Portal herunterladen",
        "die Meeting-Notizen speichern",
        "schnell speichern vor der Deadline",
        "am Wochenende alle Dateien sichern",
        "das Dokumnet speichern",
        "die Datei herunteladen",
        "Backup auf die Diskete",
        "die Presäntation speichern",
        "Ändeurngen speichern",
    ],
    ja=[
        "保存",
        "ストレージ",
        "フロッピーディスク",
        "バックアップ",
        "ファイル",
        "ドキュメント",
        "ダウンロード",
        "ディスク",
        "ドライブ",
        "ファイル保存",
        "名前を付けて保存",
        "データバックアップ",
        "データ保存",
        "文書を保存",
        "変更を保存",
        "ファイルをエクスポート",
        "アーカイブ",
        "進捗を保存",
        "パソコンにファイルを保存する",
        "ドライブにデータをバックアップする",
        "デバイスにファイルをダウンロードする",
        "閉じる前にドキュメントを保存する",
        "保存をクリックして変更を保持する",
        "プロジェクトファイルをバックアップする",
        "インストーラーファイルをダウンロードする",
        "こまめに作業を保存する",
        "添付ファイルをダウンロードして保存する",
        "古いパソコンのファイルを保存する",
        "スプレッドシートをファイルにエクスポートする",
        "会議前にプレゼンテーションを保存する",
        "古いプロジェクトファイルをアーカイブする",
        "レポートの進捗を保存する",
        "外付けドライブに写真をバックアップする",
        "PDFをダウンロードして保存する",
        "アプリを切り替える前に下書きを保存する",
        "閉じる前に保存を忘れない",
        "自動保存がオフになっているので直す",
        "契約書のコピーを保存する",
        "毎晩データベースをバックアップする",
        "データをCSVファイルにエクスポートする",
        "領収書をPDFで保存する",
        "アップデート前にスマホをバックアップする",
        "ソフトウェアアップデートをダウンロードして保存する",
        "送信前にフォームを保存する",
        "完了したプロジェクトをアーカイブする",
        "編集した写真を保存する",
        "メールをクラウドにバックアップする",
        "予算スプレッドシートを保存する",
        "ポータルからレポートをダウンロードする",
        "会議メモを保存する",
        "締め切り前に急いで保存する",
        "週末にすべてのファイルをバックアップする",
        "ドキュメントをほぞんする",
        "ファイルをダウンロドする",
        "バックアプをとる",
        "変更をほぞんする",
        "プレゼンテーションをほぞんする",
    ],
    fr=[
        "sauvegarder",
        "stockage",
        "disquette",
        "sauvegarde",
        "fichier",
        "document",
        "télécharger",
        "disque",
        "lecteur",
        "enregistrer le fichier",
        "enregistrer sous",
        "sauvegarder les données",
        "stockage de données",
        "enregistrer le document",
        "enregistrer les modifications",
        "exporter le fichier",
        "archiver",
        "sauvegarder la progression",
        "enregistrer le fichier sur l'ordinateur",
        "sauvegarder les données sur le disque",
        "télécharger le fichier sur l'appareil",
        "enregistrer le document avant de fermer",
        "cliquer sur enregistrer pour garder les modifications",
        "sauvegarder le fichier du projet",
        "télécharger le fichier d'installation",
        "enregistrer son travail régulièrement",
        "télécharger et enregistrer la pièce jointe",
        "conserver les anciens fichiers informatiques",
        "exporter le tableur dans un fichier",
        "enregistrer la présentation avant la réunion",
        "archiver les anciens fichiers de projets",
        "sauvegarder la progression du rapport",
        "sauvegarder les photos sur le disque externe",
        "télécharger le PDF et l'enregistrer",
        "enregistrer le brouillon avant de changer d'appli",
        "penser à enregistrer avant de fermer",
        "la sauvegarde automatique est désactivée il faut la remettre",
        "enregistrer une copie du contrat",
        "sauvegarder la base de données chaque nuit",
        "exporter les données en fichier CSV",
        "enregistrer le reçu en PDF",
        "sauvegarder le téléphone avant la mise à jour",
        "télécharger la mise à jour et l'enregistrer",
        "enregistrer le formulaire avant de l'envoyer",
        "archiver les projets terminés",
        "enregistrer la photo retouchée",
        "sauvegarder les e-mails dans le cloud",
        "enregistrer le tableur du budget",
        "télécharger le rapport depuis le portail",
        "enregistrer les notes de réunion",
        "enregistrement rapide avant la date limite",
        "sauvegarder tous les fichiers ce week-end",
        "enregistrer le docuemnt",
        "télecharger le fichier",
        "sauvegader les données",
        "enregistrer les modificatons",
        "enregistrer la présentaion",
    ],
    es=[
        "guardar",
        "almacenamiento",
        "disquete",
        "copia de seguridad",
        "archivo",
        "documento",
        "descargar",
        "disco",
        "unidad",
        "guardar archivo",
        "guardar como",
        "hacer copia de seguridad",
        "almacenamiento de datos",
        "guardar documento",
        "guardar cambios",
        "exportar archivo",
        "archivar",
        "guardar progreso",
        "guardar el archivo en el ordenador",
        "hacer copia de seguridad de los datos en el disco",
        "descargar el archivo al dispositivo",
        "guardar el documento antes de cerrar",
        "hacer clic en guardar para conservar los cambios",
        "hacer copia de seguridad del archivo del proyecto",
        "descargar el archivo de instalación",
        "guardar el trabajo con frecuencia",
        "descargar y guardar el adjunto",
        "conservar los archivos antiguos del ordenador",
        "exportar la hoja de cálculo a un archivo",
        "guardar la presentación antes de la reunión",
        "archivar los archivos de proyectos antiguos",
        "guardar el progreso del informe",
        "hacer copia de seguridad de las fotos en el disco externo",
        "descargar el PDF y guardarlo",
        "guardar el borrador antes de cambiar de app",
        "recordar guardar antes de cerrar",
        "el guardado automático está desactivado hay que arreglarlo",
        "guardar una copia del contrato",
        "hacer copia de seguridad de la base de datos cada noche",
        "exportar los datos como archivo CSV",
        "guardar el recibo como PDF",
        "hacer copia de seguridad del móvil antes de actualizar",
        "descargar la actualización y guardarla",
        "guardar el formulario antes de enviarlo",
        "archivar los proyectos completados",
        "guardar la foto editada",
        "hacer copia de seguridad de los correos en la nube",
        "guardar la hoja de cálculo del presupuesto",
        "descargar el informe del portal",
        "guardar las notas de la reunión",
        "guardar rápido antes de la fecha límite",
        "hacer copia de seguridad de todos los archivos este fin de semana",
        "guaradr el documento",
        "descarger el archivo",
        "copia de segurdiad de los datos",
        "guardra los cambios",
        "guardar la presentcion",
    ],
)

# ── flower ────────────────────────────────────────────────────────────────────
gen("flower",
    en=[
        "bloom",
        "blossom",
        "flora",
        "flower",
        "plant",
        "spring",
        "tulip",
        "bouquet",
        "garden",
        "petal",
        "rose",
        "sunflower",
        "daisy",
        "wildflower",
        "floral",
        "vase",
        "flower shop",
        "flower bed",
        "buy flowers for the table",
        "plant flowers in the garden",
        "water the flowers in the morning",
        "order a bouquet for the birthday",
        "pick wildflowers on the hike",
        "plant tulips in the fall",
        "prune the rose bushes",
        "arrange flowers in a vase",
        "visit the flower shop on the way home",
        "plant sunflowers along the fence",
        "deadhead the flowers for new blooms",
        "send flowers for the anniversary",
        "the tulips are blooming already",
        "bring flowers to the dinner party",
        "put fresh flowers in the living room",
        "flower bed needs weeding",
        "buy seeds for spring planting",
        "pick up a bouquet at the market",
        "the garden is full of daisies",
        "water the flower pots on the balcony",
        "plant perennials in the flower bed",
        "the roses need more sun",
        "gift a plant for Mother's Day",
        "spring flowers are coming up",
        "dried flowers for the shelf",
        "press flowers from the garden",
        "florist delivery for Friday",
        "repot the flower plant",
        "compost for the flower beds",
        "check which flowers are in season",
        "the blossom festival is next week",
        "flower arrangement class on Sunday",
        "wildflower seeds for the meadow",
        "pick up a potted plant for the office",
        "flwer in the garden",
        "blosoom in spring",
        "by a bouqet of flowers",
        "water the flwoers",
        "plant tulps in the fall",
    ],
    ru=[
        "цветение",
        "цвести",
        "флора",
        "цветок",
        "растение",
        "весна",
        "тюльпан",
        "букет",
        "сад",
        "лепесток",
        "роза",
        "подсолнух",
        "ромашка",
        "полевой цветок",
        "цветочный",
        "ваза",
        "цветочный магазин",
        "клумба",
        "купить цветы для стола",
        "посадить цветы в саду",
        "полить цветы утром",
        "заказать букет на день рождения",
        "собрать полевые цветы на прогулке",
        "посадить тюльпаны осенью",
        "обрезать кусты роз",
        "поставить цветы в вазу",
        "зайти в цветочный магазин по дороге домой",
        "посадить подсолнухи вдоль забора",
        "удалить увядшие цветы для новых бутонов",
        "отправить цветы на годовщину",
        "тюльпаны уже распускаются",
        "принести цветы на ужин",
        "поставить свежие цветы в гостиную",
        "клумба нуждается в прополке",
        "купить семена для весенней посадки",
        "купить букет на рынке",
        "сад полон ромашек",
        "полить горшки с цветами на балконе",
        "посадить многолетники на клумбу",
        "розам нужно больше солнца",
        "подарить растение на День матери",
        "весенние цветы начинают всходить",
        "засушенные цветы для полки",
        "засушить цветы из сада",
        "доставка от флориста в пятницу",
        "пересадить цветок в новый горшок",
        "компост для клумб",
        "проверить какие цветы сейчас в сезоне",
        "фестиваль цветения на следующей неделе",
        "мастер-класс по флористике в воскресенье",
        "семена полевых цветов для лужайки",
        "купить горшечное растение для офиса",
        "полть цветы утром",
        "посадть цветы в саду",
        "купть букет на рынке",
        "поставть цветы в вазу",
        "тюльпны уже распускаются",
    ],
    de=[
        "Blüte",
        "blühen",
        "Flora",
        "Blume",
        "Pflanze",
        "Frühling",
        "Tulpe",
        "Strauß",
        "Garten",
        "Blütenblatt",
        "Rose",
        "Sonnenblume",
        "Gänseblümchen",
        "Wildblume",
        "Blumen-",
        "Vase",
        "Blumenladen",
        "Blumenbeet",
        "Blumen für den Tisch kaufen",
        "Blumen im Garten pflanzen",
        "die Blumen morgens gießen",
        "einen Strauß zum Geburtstag bestellen",
        "Wildblumen auf der Wanderung pflücken",
        "Tulpen im Herbst pflanzen",
        "die Rosenbüsche schneiden",
        "Blumen in eine Vase stellen",
        "auf dem Heimweg im Blumenladen vorbeischauen",
        "Sonnenblumen am Zaun pflanzen",
        "verwelkte Blumen entfernen für neue Blüten",
        "Blumen zum Jahrestag schicken",
        "die Tulpen blühen schon",
        "Blumen zur Dinnerparty mitbringen",
        "frische Blumen ins Wohnzimmer stellen",
        "das Blumenbeet muss gejätet werden",
        "Samen für die Frühjahrspflanzung kaufen",
        "einen Strauß auf dem Markt kaufen",
        "der Garten ist voller Gänseblümchen",
        "die Blumentöpfe auf dem Balkon gießen",
        "Stauden ins Blumenbeet pflanzen",
        "die Rosen brauchen mehr Sonne",
        "eine Pflanze zum Muttertag schenken",
        "Frühlingsblumen kommen hoch",
        "Trockenblumen fürs Regal",
        "Blumen aus dem Garten pressen",
        "Florist-Lieferung für Freitag",
        "die Blumenpflanze umtopfen",
        "Kompost für die Blumenbeete",
        "prüfen welche Blumen gerade Saison haben",
        "das Blütenfest ist nächste Woche",
        "Blumenarrangement-Kurs am Sonntag",
        "Wildblumensamen für die Wiese",
        "eine Topfpflanze fürs Büro kaufen",
        "Blumen im Gartn pflanzen",
        "die Blumen morgens gießn",
        "Tulpen im Herbts pflanzen",
        "einen Struaß bestellen",
        "die Rosenbüshe schneiden",
    ],
    ja=[
        "開花",
        "咲く",
        "植物",
        "花",
        "草花",
        "春",
        "チューリップ",
        "花束",
        "庭",
        "花びら",
        "バラ",
        "ひまわり",
        "デイジー",
        "野の花",
        "フラワー",
        "花瓶",
        "花屋",
        "花壇",
        "テーブルに花を買う",
        "庭に花を植える",
        "朝に花に水をやる",
        "誕生日に花束を注文する",
        "ハイキングで野の花を摘む",
        "秋にチューリップを植える",
        "バラの茂みを剪定する",
        "花瓶に花を生ける",
        "帰り道に花屋に寄る",
        "フェンス沿いにひまわりを植える",
        "新しい花が咲くように枯れた花を取る",
        "記念日に花を送る",
        "チューリップがもう咲いている",
        "ディナーパーティーに花を持っていく",
        "リビングに生花を飾る",
        "花壇の草取りが必要",
        "春の植え付け用の種を買う",
        "市場で花束を買う",
        "庭がデイジーでいっぱい",
        "バルコニーの鉢植えの花に水をやる",
        "花壇に多年草を植える",
        "バラにもっと日当たりが必要",
        "母の日に植物をプレゼントする",
        "春の花が芽を出し始めた",
        "棚に飾るドライフラワー",
        "庭の花を押し花にする",
        "金曜日にフローリストから配達",
        "花を新しい鉢に植え替える",
        "花壇用の堆肥",
        "今の季節の花を確認する",
        "花のフェスティバルは来週",
        "日曜日にフラワーアレンジメント教室",
        "草原用の野の花の種",
        "オフィス用の鉢植えを買う",
        "庭にはなを植える",
        "花に水をあげる",
        "チュリップを植える",
        "花たばを注文する",
        "バラのしげみを剪定する",
    ],
    fr=[
        "floraison",
        "fleur",
        "flore",
        "plante",
        "printemps",
        "tulipe",
        "bouquet",
        "jardin",
        "pétale",
        "rose",
        "tournesol",
        "marguerite",
        "fleur sauvage",
        "floral",
        "vase",
        "fleuriste",
        "parterre de fleurs",
        "éclore",
        "acheter des fleurs pour la table",
        "planter des fleurs dans le jardin",
        "arroser les fleurs le matin",
        "commander un bouquet pour l'anniversaire",
        "cueillir des fleurs sauvages en randonnée",
        "planter des tulipes à l'automne",
        "tailler les rosiers",
        "mettre des fleurs dans un vase",
        "passer chez le fleuriste en rentrant",
        "planter des tournesols le long de la clôture",
        "enlever les fleurs fanées pour de nouvelles floraisons",
        "envoyer des fleurs pour l'anniversaire de mariage",
        "les tulipes sont déjà en fleur",
        "apporter des fleurs au dîner",
        "mettre des fleurs fraîches dans le salon",
        "le parterre de fleurs a besoin de désherbage",
        "acheter des graines pour les plantations de printemps",
        "acheter un bouquet au marché",
        "le jardin est plein de marguerites",
        "arroser les pots de fleurs sur le balcon",
        "planter des vivaces dans le parterre",
        "les roses ont besoin de plus de soleil",
        "offrir une plante pour la fête des mères",
        "les fleurs de printemps poussent",
        "fleurs séchées pour l'étagère",
        "faire sécher des fleurs du jardin",
        "livraison du fleuriste vendredi",
        "rempoter la plante fleurie",
        "compost pour les parterres de fleurs",
        "vérifier quelles fleurs sont de saison",
        "le festival des fleurs est la semaine prochaine",
        "cours d'arrangement floral dimanche",
        "graines de fleurs sauvages pour la prairie",
        "acheter une plante en pot pour le bureau",
        "acheter des fleurs pour la tabel",
        "arroser les flurs le matin",
        "plantre des tulipes à l'automne",
        "commander un bouqet pour l'anniversaire",
        "cueillir des fleurs sauvagse en randonnée",
    ],
    es=[
        "floración",
        "flor",
        "flora",
        "planta",
        "primavera",
        "tulipán",
        "ramo",
        "jardín",
        "pétalo",
        "rosa",
        "girasol",
        "margarita",
        "flor silvestre",
        "floral",
        "jarrón",
        "floristería",
        "macizo de flores",
        "florecer",
        "comprar flores para la mesa",
        "plantar flores en el jardín",
        "regar las flores por la mañana",
        "pedir un ramo para el cumpleaños",
        "recoger flores silvestres en la excursión",
        "plantar tulipanes en otoño",
        "podar los rosales",
        "poner flores en un jarrón",
        "pasar por la floristería de camino a casa",
        "plantar girasoles a lo largo de la valla",
        "quitar las flores marchitas para que salgan nuevas",
        "enviar flores por el aniversario",
        "los tulipanes ya están floreciendo",
        "llevar flores a la cena",
        "poner flores frescas en el salón",
        "el macizo de flores necesita desherbar",
        "comprar semillas para la siembra de primavera",
        "comprar un ramo en el mercado",
        "el jardín está lleno de margaritas",
        "regar las macetas del balcón",
        "plantar perennes en el macizo de flores",
        "las rosas necesitan más sol",
        "regalar una planta para el Día de la Madre",
        "las flores de primavera están saliendo",
        "flores secas para la estantería",
        "prensar flores del jardín",
        "entrega del florista el viernes",
        "trasplantar la planta con flor",
        "compost para los macizos de flores",
        "ver qué flores están en temporada",
        "el festival de las flores es la semana que viene",
        "clase de arreglos florales el domingo",
        "semillas de flores silvestres para el prado",
        "comprar una planta en maceta para la oficina",
        "comprar flroes para la mesa",
        "regar las flors por la mañana",
        "plantar tulpanes en otoño",
        "pedir un rmo para el cumpleaños",
        "poner flores en un jarrn",
    ],
)

print("\n--- Part 2 done: fire, flag-checkered, flask, floppy-disk, flower ---")
