#!/usr/bin/env python3
"""Expand training data for icons 486-505 (low-coverage batch 2, 20 icons)."""
from pathlib import Path
import csv, json

icons_dir = Path("icons")

def read_texts(path):
    if not path.exists():
        return set()
    with open(path, encoding="utf-8") as f:
        return {r["text"].strip() for r in csv.DictReader(f)}

def append_csv(path, rows):
    with open(path, "a", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerows(rows)

def remove_rows(path, bad_texts):
    """Remove specific rows by text value."""
    if not path.exists():
        return 0
    with open(path, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    clean = [r for r in rows if r["text"].strip() not in bad_texts]
    removed = len(rows) - len(clean)
    if removed:
        with open(path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=["text", "label"])
            w.writeheader()
            w.writerows(clean)
    return removed

def expand(icon, new_en, new_ru, fix_en=None, fix_ru=None):
    """Append new rows; optionally remove bad rows first."""
    en_path = icons_dir / icon / "train_en.csv"
    ru_path = icons_dir / icon / "train_ru.csv"

    removed_en = removed_ru = 0
    if fix_en:
        removed_en = remove_rows(en_path, fix_en)
    if fix_ru:
        removed_ru = remove_rows(ru_path, fix_ru)

    assert len(new_en) == len(new_ru), \
        f"{icon}: EN/RU mismatch {len(new_en)} vs {len(new_ru)}"

    # Skip rows already in the file
    existing_en = read_texts(en_path)
    existing_ru = read_texts(ru_path)
    add_en = [(t, icon) for t in new_en if t not in existing_en]
    add_ru = [(t, icon) for t in new_ru if t not in existing_ru]

    append_csv(en_path, add_en)
    append_csv(ru_path, add_ru)

    label = f"+{len(add_en)} EN"
    if removed_en:
        label += f" (fixed {removed_en})"
    print(f"  {icon}: {label}")

# ── 486: garage ───────────────────────────────────────────────────────────────
expand("garage",
    new_en=[
        "garage",
        "parking",
        "workshop",
        "car parked safely in the garage overnight",
        "pull the car into the garage",
        "garage door opens automatically for the car",
        "single-car garage attached to the house",
        "two-car garage with storage shelves",
        "garage workshop with tools on the wall",
        "workshop set up in the garage",
        "home gym built in the converted garage",
        "garage icon for a smart home app",
        "garage with a workbench and pegboard",
        "park the bike in the garage",
        "garage sensor alert when door is left open",
        "smart garage door opener on the phone",
        "garage filled with boxes during the move",
        "clear out the garage for the car",
        "garage door remote on the visor",
        "weekend project in the garage workshop",
        "I need a garage icon for my home app",
        "add a garage symbol to the parking section",
        "show a garage for the home storage feature",
        "use the garage icon for the vehicle storage screen",
        "gaage door opening for the car",
        "garaage with a workbench",
        "park in the graage tonight",
        "smart gaarge door",
        "garagge workshop tools",
    ],
    new_ru=[
        "гараж",
        "парковка",
        "мастерская",
        "машина в безопасности в гараже на ночь",
        "загнать машину в гараж",
        "гаражные ворота открываются автоматически",
        "гараж на одну машину при доме",
        "гараж на две машины с полками для хранения",
        "мастерская в гараже с инструментами на стене",
        "обустроить мастерскую в гараже",
        "спортзал в переоборудованном гараже",
        "иконка гаража для приложения умного дома",
        "гараж с верстаком и перфорированной панелью",
        "поставить велосипед в гараж",
        "сигнал датчика гаража когда ворота открыты",
        "умный привод гаражных ворот на телефоне",
        "гараж заставлен коробками при переезде",
        "освободить гараж для машины",
        "пульт от гаражных ворот на козырьке",
        "проект выходного дня в мастерской гаража",
        "нужна иконка гаража для домашнего приложения",
        "добавить символ гаража в раздел парковки",
        "показать гараж для функции домашнего хранения",
        "использовать иконку гаража на экране хранения транспорта",
        "гаражные ворота открываются",
        "гараж с верстаком",
        "поставить машину в гараж на ночь",
        "умные ворота гаража",
        "инструменты в мастерской гаража",
    ],
)

# ── 487: image ────────────────────────────────────────────────────────────────
expand("image",
    new_en=[
        "photo",
        "image",
        "edit a photo before posting",
        "share a photo on social media",
        "upload an image to the profile",
        "crop the image to a square",
        "image placeholder in a content editor",
        "add an image to the blog post",
        "photo icon for a gallery or album app",
        "full-resolution image downloaded from the cloud",
        "image icon in a file manager",
        "press and hold the image to save it",
        "pick an image from the camera roll",
        "set a photo as the home screen wallpaper",
        "thumbnail image in a photo grid",
        "original image vs edited version comparison",
        "compress the image before sending",
        "image file attached to the document",
        "I need an image icon for my photo app",
        "add an image symbol to the media section",
        "show a photo for the gallery feature",
        "use the image icon for the media picker",
        "edti the imge before sharing",
        "upolad a phot to the proifle",
        "cropp the image for the post",
        "compres the image before sending",
        "set a phto as the wallpapper",
    ],
    new_ru=[
        "фото",
        "изображение",
        "отредактировать фото перед публикацией",
        "поделиться фото в соцсетях",
        "загрузить изображение в профиль",
        "обрезать фото до квадрата",
        "заглушка изображения в редакторе контента",
        "добавить картинку в запись блога",
        "иконка фото для галереи или альбома",
        "изображение в полном разрешении скачано из облака",
        "иконка изображения в файловом менеджере",
        "удерживать фото чтобы сохранить",
        "выбрать фото из фотопленки",
        "установить фото в качестве обоев экрана",
        "уменьшенное изображение в фотосетке",
        "сравнить оригинал и отредактированную версию",
        "сжать изображение перед отправкой",
        "файл изображения приложен к документу",
        "нужна иконка фото для фотоприложения",
        "добавить символ изображения в раздел медиа",
        "показать фото для функции галереи",
        "использовать иконку изображения для выбора медиа",
        "отредактировать фото перед отправкой",
        "загрузить фото в профиль",
        "обрезать фото для поста",
        "сжать изображение перед отправкой",
        "установить фото в качестве обоев",
    ],
)

# ── 488: kit-medical ──────────────────────────────────────────────────────────
# Fix: remove generic health phrases not about a first-aid kit
expand("kit-medical",
    fix_en={
        "Maintain good health habits",
        "Go to a health checkup",
    },
    fix_ru={
        "Поддерживайте полезные привычки в отношении здоровья",
        "Сходите на медицинский осмотр",
    },
    new_en=[
        "first aid",
        "first aid kit",
        "medical kit",
        "red cross symbol on the first aid box",
        "first aid kit mounted on the wall",
        "open the first aid kit for the bandages",
        "first aid kit in the car glove box",
        "white box with a red cross first aid kit",
        "kit stocked with bandages and antiseptic",
        "grab the first aid kit for the hike",
        "check the expiry dates in the first aid kit",
        "replace used items in the medical kit",
        "first aid kit in the office break room",
        "compact first aid kit for the travel bag",
        "emergency first aid kit for the campsite",
        "apply a plaster from the first aid kit",
        "treat a cut with the first aid kit",
        "first aid kit icon for a health or safety app",
        "I need a first aid kit icon for my safety app",
        "add a medical kit symbol to the emergency section",
        "show a first aid kit for the health tracker",
        "use the kit-medical icon for the first aid feature",
        "frist aid kit for emergency",
        "medicla kit stocked with bandages",
        "kit-medcial for the hike",
        "first aaid box on the wall",
        "frst aid box with red crross",
    ],
    new_ru=[
        "первая помощь",
        "аптечка",
        "медицинский набор",
        "красный крест на коробке аптечки",
        "аптечка закреплена на стене",
        "открыть аптечку за бинтами",
        "аптечка в бардачке машины",
        "белая коробка с красным крестом",
        "набор укомплектован бинтами и антисептиком",
        "взять аптечку в поход",
        "проверить сроки годности в аптечке",
        "пополнить медицинский набор после использования",
        "аптечка в комнате отдыха офиса",
        "компактная аптечка для дорожной сумки",
        "экстренная аптечка для похода",
        "приложить пластырь из аптечки",
        "обработать порез с помощью аптечки",
        "иконка аптечки для приложения здоровья",
        "нужна иконка аптечки для приложения безопасности",
        "добавить символ медицинского набора в раздел экстренной помощи",
        "показать аптечку для трекера здоровья",
        "использовать иконку аптечки для функции первой помощи",
        "аптечка для экстренной помощи",
        "медицинский набор с бинтами",
        "аптечка для похода",
        "аптечка на стене",
        "белая коробка с красным крестом",
    ],
)

# ── 489: lasso-sparkles ───────────────────────────────────────────────────────
expand("lasso-sparkles",
    new_en=[
        "magic select",
        "ai selection",
        "smart lasso",
        "magic selection tool removes the background",
        "AI-powered lasso selects the subject automatically",
        "smart lasso traces the object outline",
        "one-click subject selection in an editing app",
        "auto-select and remove background in one tap",
        "AI erases the background instantly",
        "subject isolation with smart lasso sparkles",
        "intelligent selection follows the object edge",
        "magic wand selects all similar pixels",
        "automatic subject selection in a photo editor",
        "lasso sparkles icon for AI editing feature",
        "tap to auto-select the foreground subject",
        "smart cutout tool for design apps",
        "highlight the object and remove the background",
        "I need an AI selection icon for my photo app",
        "add a magic select symbol to the editing tools",
        "show AI lasso for the background removal feature",
        "use the lasso-sparkles icon for the smart select tool",
        "auto-selct the subejct",
        "magic wnad background remove",
        "smrat lasso selectoin tool",
        "ai-powred selction",
        "laso sparkles editting",
    ],
    new_ru=[
        "умное выделение",
        "магическое выделение",
        "ИИ-выделение",
        "инструмент умного выбора удаляет фон",
        "ИИ-лассо автоматически выбирает объект",
        "умное лассо обводит контур объекта",
        "выбор объекта одним нажатием в редакторе",
        "автоматически выделить и удалить фон",
        "ИИ мгновенно убирает фон",
        "выделение объекта умным лассо",
        "интеллектуальный выбор по краю объекта",
        "волшебная палочка выбирает похожие пиксели",
        "автоматический выбор объекта в редакторе фото",
        "иконка лассо-искр для функции ИИ-редактирования",
        "нажать чтобы выделить передний план",
        "инструмент умной вырезки для дизайна",
        "выделить объект и удалить фон",
        "нужна иконка ИИ-выбора для фотоприложения",
        "добавить символ умного выделения в инструменты редактирования",
        "показать ИИ-лассо для удаления фона",
        "использовать иконку лассо для умного выбора",
        "автовыделение объекта",
        "волшебная палочка удаление фона",
        "умный инструмент лассо",
        "ИИ-выделение",
        "лассо-искры для редактирования",
    ],
)

# ── 490: pear ─────────────────────────────────────────────────────────────────
expand("pear",
    new_en=[
        "orchard",
        "ripe pear picked from the orchard",
        "Bartlett pear golden yellow and sweet",
        "green Anjou pear in a fruit basket",
        "pear and cheese pairing on a board",
        "pear juice pressed from fresh fruit",
        "dried pear slices in a trail mix",
        "buy pears at the farmers market",
        "pear tart with almond cream filling",
        "fresh pear cut into wedges for a snack",
        "add sliced pear to the spinach salad",
        "pear ripening on the kitchen counter",
        "pear icon for a nutrition or fruit app",
        "pear blossom on the tree in spring",
        "pick ripe pears before the first frost",
        "Asian pear crisp and crunchy texture",
        "pear flavor in a craft cider",
        "I need a pear icon for my recipe app",
        "add a pear symbol to the fruit section",
        "show a pear for the fresh produce category",
        "use the pear icon for the fruit tracker",
        "sweet prear from the market",
        "riipe pear in the fruit basekt",
        "pear nad cheese on a boadr",
        "bartllet pear yellow sweet",
        "pear trat almond filling",
    ],
    new_ru=[
        "сад",
        "спелая груша с сада",
        "золотистая сладкая груша сорта Bartlett",
        "зелёная груша Anjou в корзине с фруктами",
        "груша и сыр на доске",
        "грушевый сок из свежих фруктов",
        "сушёные дольки груши в смеси орехов",
        "купить груши на фермерском рынке",
        "грушевый тарт с миндальным кремом",
        "свежая груша нарезана дольками для перекуса",
        "добавить ломтики груши в шпинатный салат",
        "груша дозревает на кухонном столе",
        "иконка груши для приложения питания",
        "грушевый цвет на дереве весной",
        "собрать спелые груши до первых заморозков",
        "азиатская груша — хрустящая текстура",
        "грушевый вкус в крафтовом сидре",
        "нужна иконка груши для приложения рецептов",
        "добавить символ груши в раздел фруктов",
        "показать грушу для категории свежих продуктов",
        "использовать иконку груши для трекера фруктов",
        "сладкая груша с рынка",
        "спелая груша в корзине",
        "груша и сыр на доске",
        "золотистая сладкая груша",
        "грушевый тарт с начинкой",
    ],
)

# ── 491: pedestal ─────────────────────────────────────────────────────────────
expand("pedestal",
    new_en=[
        "podium",
        "stand",
        "electric pedestal outlet in a marina",
        "power pedestal at the RV park",
        "pedestal power outlet for outdoor events",
        "outdoor electrical pedestal with multiple sockets",
        "pedestal with power and water connections",
        "marina pedestal for boat shore power",
        "exhibition pedestal for sculpture display",
        "museum display pedestal under a spotlight",
        "trophy on a marble pedestal",
        "award pedestal for the winner",
        "speaker standing at the podium",
        "mic stand on a pedestal at the stage",
        "reading stand or lectern for the speaker",
        "information kiosk on a pedestal base",
        "pedestal icon for a venue or event app",
        "I need a pedestal icon for the charging station section",
        "add a pedestal symbol to the utilities feature",
        "show a pedestal for the outdoor power screen",
        "use the pedestal icon for the marina power feature",
        "powre pedestla in marina",
        "eletric pedestal at rv park",
        "pedesatl socket outdorr",
        "museum pesdetal displayy",
        "trophey on pedsetl",
    ],
    new_ru=[
        "подиум",
        "стойка",
        "электрическая колонка в яхтенном порту",
        "силовая колонка на кемпинге",
        "уличная электрическая розетка на стойке",
        "уличная колонка с несколькими розетками",
        "стойка с подключением воды и электричества",
        "причальная колонка для питания яхты",
        "выставочный постамент для скульптуры",
        "постамент в музее под прожектором",
        "кубок на мраморном постаменте",
        "наградной подиум для победителя",
        "докладчик стоит за трибуной",
        "стойка микрофона на подиуме сцены",
        "трибуна для выступающего",
        "информационный киоск на постаменте",
        "иконка постамента для приложения площадки",
        "нужна иконка стойки для раздела зарядной станции",
        "добавить символ постамента в раздел коммуникаций",
        "показать постамент для экрана уличного питания",
        "использовать иконку постамента для питания в марине",
        "силовая стойка в порту",
        "электрическая колонка на кемпинге",
        "уличная розетка на стойке",
        "музейный постамент для экспоната",
        "кубок на постаменте",
    ],
)

# ── 492: route ────────────────────────────────────────────────────────────────
expand("route",
    new_en=[
        "route",
        "directions",
        "navigation",
        "turn-by-turn route on the GPS",
        "plan the driving route before leaving",
        "fastest route to the destination",
        "route overview on the map screen",
        "route with two stops along the way",
        "navigate route in real time",
        "route icon for a maps or GPS app",
        "follow the route to avoid getting lost",
        "route summary with total distance and time",
        "route deviation detected — recalculating",
        "bus route number on the display board",
        "bus route map for the city transit",
        "cycling route avoiding the main road",
        "walking route to the nearest station",
        "delivery route optimized for ten stops",
        "I need a route icon for my maps app",
        "add a route symbol to the navigation section",
        "show a route path for the directions feature",
        "use the route icon for the trip planner screen",
        "GPS routee recalculating",
        "naviagtion rout to destnation",
        "turn-by-trun directions",
        "cyclign rout avoiding cars",
        "delivrey route with ten stosp",
    ],
    new_ru=[
        "маршрут",
        "навигация",
        "направление",
        "пошаговый маршрут на GPS",
        "спланировать маршрут поездки заранее",
        "самый быстрый маршрут до пункта назначения",
        "обзор маршрута на экране карты",
        "маршрут с двумя остановками",
        "следить за маршрутом в реальном времени",
        "иконка маршрута для картографического приложения",
        "следовать маршруту чтобы не заблудиться",
        "итог маршрута: расстояние и время",
        "маршрут отклонился — пересчёт",
        "номер автобусного маршрута на табло",
        "карта автобусного маршрута в городе",
        "велосипедный маршрут в объезд главной дороги",
        "пеший маршрут до ближайшей станции",
        "маршрут доставки оптимизирован на десять остановок",
        "нужна иконка маршрута для картографического приложения",
        "добавить символ маршрута в раздел навигации",
        "показать маршрут для функции прокладки пути",
        "использовать иконку маршрута для планировщика поездок",
        "GPS пересчитывает маршрут",
        "навигационный маршрут до пункта назначения",
        "пошаговая навигация",
        "велосипедный маршрут объезд машин",
        "маршрут доставки с десятью остановками",
    ],
)

# ── 493: sprinkler-ceiling ────────────────────────────────────────────────────
expand("sprinkler-ceiling",
    new_en=[
        "fire sprinkler",
        "sprinkler head",
        "suppression",
        "ceiling sprinkler discharges water over the fire",
        "glass bulb fuse in the sprinkler head",
        "sprinkler system wired to the fire alarm",
        "sprinkler activated by heat not smoke",
        "fire suppression sprinkler cuts off oxygen",
        "building code requires ceiling sprinklers",
        "sprinkler coverage tested annually",
        "wet pipe sprinkler system in the office",
        "dry pipe sprinkler for cold storage",
        "sprinkler system tagged for inspection",
        "retrofit ceiling sprinklers in older buildings",
        "fire sprinkler icon for a safety checklist app",
        "ceiling mount sprinkler head close-up",
        "temperature fusible link inside the sprinkler",
        "I need a sprinkler icon for the fire safety section",
        "add a ceiling sprinkler to the safety checklist",
        "show a sprinkler for the fire suppression feature",
        "use the sprinkler-ceiling icon for building safety",
        "celing sprinkler activtes in fire",
        "sprinkler head with glas bulb",
        "frie suppresion system activating",
        "sprinkler sytems wired to alarm",
        "celing sprinkler inspcetion",
    ],
    new_ru=[
        "пожарный спринклер",
        "распылитель",
        "огнетушение",
        "потолочный спринклер сбрасывает воду на огонь",
        "стеклянная колба в головке спринклера",
        "система спринклеров подключена к пожарной сигнализации",
        "спринклер срабатывает от тепла а не от дыма",
        "система пожаротушения перекрывает кислород",
        "строительные нормы требуют потолочных спринклеров",
        "покрытие спринклерной системы проверяется ежегодно",
        "мокрая спринклерная система в офисе",
        "сухая система для холодного склада",
        "спринклерная система помечена для проверки",
        "дооснастить старые здания потолочными спринклерами",
        "иконка спринклера для приложения пожарной безопасности",
        "спринклерная головка крупным планом",
        "легкоплавкий элемент внутри спринклера",
        "нужна иконка спринклера для раздела пожарной безопасности",
        "добавить потолочный спринклер в список проверки безопасности",
        "показать спринклер для функции пожаротушения",
        "использовать иконку спринклера для безопасности здания",
        "потолочный спринклер срабатывает при пожаре",
        "головка спринклера со стеклянной колбой",
        "система пожаротушения активируется",
        "спринклерная система подключена к сигнализации",
        "проверка потолочных спринклеров",
    ],
)

# ── 494: utility-pole ─────────────────────────────────────────────────────────
expand("utility-pole",
    new_en=[
        "power line",
        "telephone pole",
        "electric pole",
        "wooden utility pole on a residential street",
        "utility pole with transformer box mounted on top",
        "high-voltage power lines on tall metal poles",
        "telephone pole with multiple wires and cables",
        "utility pole knocked over in the storm",
        "crew restoring power at the utility pole",
        "electric pole with insulators on the crossarm",
        "utility pole marking for underground cable below",
        "streetlight mounted on the utility pole",
        "utility pole icon for an infrastructure app",
        "power line poles stretching to the horizon",
        "communication cable attached to the utility pole",
        "replace the old wooden pole with a new one",
        "utility pole near the school zone",
        "I need a utility pole icon for the grid section",
        "add a power pole symbol to the infrastructure map",
        "show a utility pole for the electricity feature",
        "use the pole icon for the power grid screen",
        "utlity pol on residentail streeet",
        "powre line poole in the street",
        "teleohone poole with wires",
        "utlitiy pole knocked over",
        "electic pol crew reparing",
    ],
    new_ru=[
        "линия электропередачи",
        "телефонный столб",
        "электрический столб",
        "деревянный электрический столб на жилой улице",
        "столб с трансформатором наверху",
        "высоковольтные линии на высоких металлических опорах",
        "телефонный столб с несколькими проводами",
        "столб повален штормом",
        "бригада восстанавливает электроснабжение у столба",
        "электрический столб с изоляторами на траверсе",
        "маркировка столба для кабеля под землёй",
        "уличный фонарь закреплён на столбе",
        "иконка опоры для инфраструктурного приложения",
        "столбы ЛЭП уходят за горизонт",
        "кабель связи на электрическом столбе",
        "заменить старый деревянный столб на новый",
        "столб у школьной зоны",
        "нужна иконка опоры для раздела электросети",
        "добавить символ столба ЛЭП на карту инфраструктуры",
        "показать опору для функции электроснабжения",
        "использовать иконку столба на экране энергосети",
        "электрический столб на жилой улице",
        "столб ЛЭП на улице",
        "телефонный столб с проводами",
        "столб повален",
        "бригада ремонтирует электрический столб",
    ],
)

# ── 495: battery-bolt ─────────────────────────────────────────────────────────
expand("battery-bolt",
    new_en=[
        "charge",
        "battery",
        "charging icon for a device tracker",
        "battery with a lightning bolt charging indicator",
        "plug in the device to start charging",
        "low battery warning with the bolt icon",
        "battery-bolt icon shows power is flowing in",
        "phone charging on the wireless pad",
        "charge indicator turns green when full",
        "cable plugged in — charging bolt appears",
        "battery percentage shown with bolt symbol",
        "EV charging station bolt icon on the map",
        "fast charging mode activates the bolt symbol",
        "battery bolt appears when plugged in overnight",
        "charging reminder before leaving the house",
        "battery health check in the device settings",
        "I need a charging icon for my device app",
        "add a battery-bolt symbol to the power section",
        "show a charge icon for the energy tracker",
        "use the battery-bolt icon for the charging screen",
        "baterry bolt low warrning",
        "chargign icon on devce",
        "batetry bolt pluged in",
        "fast chargng mode on",
        "EV chargng staiton bolt",
    ],
    new_ru=[
        "зарядка",
        "аккумулятор",
        "иконка зарядки для трекера устройств",
        "аккумулятор с молнией в индикаторе зарядки",
        "подключить устройство для начала зарядки",
        "предупреждение о низком заряде с иконкой молнии",
        "молния на аккумуляторе означает что идёт зарядка",
        "телефон заряжается на беспроводной подставке",
        "индикатор зеленеет когда аккумулятор заряжен",
        "кабель подключён — появляется молния зарядки",
        "процент заряда с символом молнии",
        "иконка зарядной станции для электромобиля",
        "режим быстрой зарядки активирует символ молнии",
        "молния зарядки горит когда устройство на зарядке ночью",
        "напоминание зарядить устройство перед выходом",
        "проверка состояния аккумулятора в настройках",
        "нужна иконка зарядки для приложения устройств",
        "добавить символ молнии в раздел питания",
        "показать иконку зарядки для трекера энергии",
        "использовать иконку молнии аккумулятора для экрана зарядки",
        "предупреждение о низком заряде аккумулятора",
        "иконка зарядки на устройстве",
        "аккумулятор подключён к зарядке",
        "режим быстрой зарядки включён",
        "иконка зарядной станции для электромобиля",
    ],
)

# ── 496: couch ────────────────────────────────────────────────────────────────
expand("couch",
    new_en=[
        "couch",
        "sofa",
        "living room",
        "three-seater couch in the living room",
        "sink into the soft cushions of the couch",
        "couch with throw pillows and a blanket",
        "sectional sofa filling the corner of the room",
        "leather couch in the modern living room",
        "couch icon for a furniture or home decor app",
        "pull-out sofa bed for overnight guests",
        "binge-watch shows on the couch all weekend",
        "nap on the couch after lunch",
        "move the couch to vacuum underneath",
        "buy a sofa with washable slipcovers",
        "couch delivered and assembled today",
        "pick the right couch fabric for the space",
        "lounge on the couch with a good book",
        "I need a couch icon for my furniture app",
        "add a sofa symbol to the living room section",
        "show a couch for the furniture catalog feature",
        "use the couch icon for the home decor screen",
        "sectinal couch in the corner",
        "couche with throw pillows",
        "relax on the sofa all day",
        "leather couuch in living room",
        "couch deliverd today",
    ],
    new_ru=[
        "диван",
        "кушетка",
        "гостиная",
        "трёхместный диван в гостиной",
        "утонуть в мягких подушках дивана",
        "диван с декоративными подушками и пледом",
        "угловой диван занимает угол комнаты",
        "кожаный диван в современной гостиной",
        "иконка дивана для приложения мебели или декора",
        "раскладной диван-кровать для гостей",
        "смотреть сериалы на диване весь уикенд",
        "вздремнуть на диване после обеда",
        "передвинуть диван чтобы пропылесосить под ним",
        "купить диван со съёмными чехлами",
        "диван доставлен и собран сегодня",
        "выбрать правильную ткань обивки дивана",
        "полежать на диване с хорошей книгой",
        "нужна иконка дивана для приложения мебели",
        "добавить символ дивана в раздел гостиной",
        "показать диван для каталога мебели",
        "использовать иконку дивана для раздела декора дома",
        "угловой диван в углу комнаты",
        "диван с декоративными подушками",
        "расслабиться на диване весь день",
        "кожаный диван в гостиной",
        "диван доставлен сегодня",
    ],
)

# ── 497: dial ─────────────────────────────────────────────────────────────────
expand("dial",
    new_en=[
        "knob",
        "gauge",
        "control",
        "turn the knob to raise the volume",
        "analog dial showing the current reading",
        "pressure gauge dial on the boiler",
        "rotate the dial to the desired setting",
        "oven temperature dial turned to 180 degrees",
        "dial icon for a settings or control panel app",
        "volume control dial on a vintage stereo",
        "speedometer dial reaching the redline",
        "dial calibration for precise measurement",
        "radio tuner dial for FM stations",
        "control dial on the camera body",
        "thermostat dial set to 21 degrees",
        "fuel gauge dial showing the tank level",
        "I need a dial icon for my settings app",
        "add a dial symbol to the control panel section",
        "show a dial for the adjustment feature",
        "use the dial icon for the settings control screen",
        "turn the knob to the right settig",
        "presure gauje dial on the boilre",
        "rotatee dial to desierd setting",
        "volumme contrrol dial",
        "ovne temperatrue dial",
    ],
    new_ru=[
        "ручка регулятора",
        "циферблат",
        "регулятор",
        "повернуть ручку чтобы повысить громкость",
        "аналоговый циферблат показывает текущее значение",
        "манометр котла",
        "повернуть регулятор до нужного положения",
        "переключатель температуры духовки на 180 градусов",
        "иконка циферблата для приложения настроек",
        "ручка громкости на винтажном стерео",
        "стрелка спидометра приближается к красной зоне",
        "калибровка циферблата для точного измерения",
        "тюнер радио для FM-станций",
        "регулятор на корпусе камеры",
        "термостат выставлен на 21 градус",
        "датчик уровня топлива показывает уровень в баке",
        "нужна иконка циферблата для приложения настроек",
        "добавить символ регулятора в раздел панели управления",
        "показать циферблат для функции регулировки",
        "использовать иконку циферблата для экрана управления",
        "повернуть ручку до нужного положения",
        "манометр котла",
        "повернуть регулятор до нужного значения",
        "ручка регулятора громкости",
        "регулятор температуры духовки",
    ],
)

# ── 498: display ──────────────────────────────────────────────────────────────
expand("display",
    new_en=[
        "monitor",
        "screen",
        "computer display",
        "widescreen monitor on the desk",
        "desktop computer with a large display",
        "connect a second monitor to the laptop",
        "display resolution set to 4K",
        "retina display on the iMac",
        "external monitor for the MacBook",
        "display icon for a screen settings app",
        "portrait mode display rotated 90 degrees",
        "ultra-wide curved monitor for gaming",
        "calibrate the display color profile",
        "display brightness set to auto",
        "mirror the screen to the projector",
        "display not detected — check the cable",
        "I need a monitor icon for my workspace app",
        "add a display symbol to the screen settings section",
        "show a monitor for the resolution control feature",
        "use the display icon for the screen setup screen",
        "widescren monitro on the desk",
        "connect a seond monitr to laaptop",
        "displayy resoluton set to 4K",
        "retina dsplay on the imac",
        "clibrate the displaay color",
    ],
    new_ru=[
        "монитор",
        "экран",
        "компьютерный дисплей",
        "широкоформатный монитор на столе",
        "настольный компьютер с большим дисплеем",
        "подключить второй монитор к ноутбуку",
        "разрешение дисплея установлено на 4K",
        "экран Retina на iMac",
        "внешний монитор для MacBook",
        "иконка монитора для приложения настроек экрана",
        "дисплей в вертикальном режиме повёрнут на 90 градусов",
        "ультрашироький изогнутый монитор для игр",
        "калибровка цветового профиля дисплея",
        "яркость экрана в автоматическом режиме",
        "дублировать экран на проектор",
        "дисплей не обнаружен — проверить кабель",
        "нужна иконка монитора для рабочего приложения",
        "добавить символ монитора в раздел настроек экрана",
        "показать монитор для управления разрешением",
        "использовать иконку монитора для настройки экрана",
        "широкоформатный монитор на столе",
        "подключить второй монитор к ноутбуку",
        "разрешение дисплея 4K",
        "экран Retina на iMac",
        "откалибровать цвет дисплея",
    ],
)

# ── 499: door-closed ──────────────────────────────────────────────────────────
expand("door-closed",
    new_en=[
        "closed door",
        "door",
        "shut the door to keep the noise out",
        "closed door icon for a private room",
        "door closed sign on the office meeting room",
        "keep the door closed for quiet study",
        "closed door separating two rooms",
        "door closed at night for safety",
        "front door closed and locked",
        "door icon for a room management app",
        "closed door with a handle on the right side",
        "privacy mode — door stays closed",
        "hotel room door closed — do not disturb",
        "closed door policy during the meeting",
        "fire door stays closed at all times",
        "automatic door closes after entering",
        "I need a closed door icon for my room app",
        "add a door symbol to the access control section",
        "show a closed door for the privacy feature",
        "use the door-closed icon for the room lock screen",
        "keep the door closd to save energie",
        "dor closed fro privacy",
        "fronnt dorr closed and lockd",
        "closed dorr icon for privcy",
        "fire dor closed at all time",
    ],
    new_ru=[
        "закрытая дверь",
        "дверь",
        "закрыть дверь чтобы не мешал шум",
        "иконка закрытой двери для приватного помещения",
        "табличка «закрыто» на двери переговорной",
        "держать дверь закрытой для тихой учёбы",
        "закрытая дверь разделяет два помещения",
        "дверь закрыта на ночь для безопасности",
        "входная дверь закрыта и заперта",
        "иконка двери для приложения управления комнатами",
        "закрытая дверь с ручкой справа",
        "режим приватности — дверь остаётся закрытой",
        "дверь номера закрыта — не беспокоить",
        "политика закрытых дверей на совещании",
        "противопожарная дверь всегда закрыта",
        "автоматическая дверь закрывается после входа",
        "нужна иконка закрытой двери для приложения комнат",
        "добавить символ двери в раздел контроля доступа",
        "показать закрытую дверь для функции приватности",
        "использовать иконку закрытой двери для экрана блокировки",
        "держать дверь закрытой чтобы сохранить тепло",
        "дверь закрыта для приватности",
        "входная дверь закрыта и заперта",
        "иконка закрытой двери для приватности",
        "противопожарная дверь закрыта всегда",
    ],
)

# ── 500: dress ────────────────────────────────────────────────────────────────
expand("dress",
    new_en=[
        "dress",
        "gown",
        "outfit",
        "sundress for a summer picnic",
        "floral dress for a garden party",
        "casual dress with a tied waist belt",
        "mini dress for a night out",
        "midi dress hitting below the knee",
        "wrap dress flattering every body type",
        "dress icon for a fashion or outfit app",
        "pick the right dress for the occasion",
        "cocktail dress for the company event",
        "dress with pockets — finally",
        "vintage dress from the thrift store",
        "bridesmaid dress in matching dusty rose",
        "slip dress layered over a turtleneck",
        "I need a dress icon for my fashion app",
        "add a dress symbol to the clothing section",
        "show a dress for the outfit picker feature",
        "use the dress icon for the wardrobe screen",
        "florall summer drss for garden party",
        "weddign gown with long tarin",
        "litttle black dres for event",
        "minidr ess for night out",
        "wrapp dres flattering",
    ],
    new_ru=[
        "платье",
        "наряд",
        "вечернее платье",
        "сарафан для летнего пикника",
        "цветочное платье на садовую вечеринку",
        "повседневное платье с поясом",
        "мини-платье для выхода вечером",
        "платье миди ниже колена",
        "платье-запах подходит любой фигуре",
        "иконка платья для приложения моды",
        "выбрать правильное платье для случая",
        "коктейльное платье для корпоратива",
        "платье с карманами — наконец-то",
        "винтажное платье из секонд-хенда",
        "платье подружки невесты в пастельно-розовом",
        "платье-комбинация поверх водолазки",
        "нужна иконка платья для модного приложения",
        "добавить символ платья в раздел одежды",
        "показать платье для выбора наряда",
        "использовать иконку платья для экрана гардероба",
        "летнее цветочное платье на вечеринку",
        "свадебное платье с длинным шлейфом",
        "маленькое чёрное платье на мероприятие",
        "мини-платье для вечернего выхода",
        "платье-запах на любую фигуру",
    ],
)

# ── 501: heading ──────────────────────────────────────────────────────────────
expand("heading",
    new_en=[
        "H1",
        "H2",
        "text style",
        "apply H1 to the main title of the page",
        "section heading styled as H2",
        "chapter heading in the document",
        "bold large heading at the top of the article",
        "heading hierarchy H1 H2 H3 in the doc",
        "add a heading to break up the text sections",
        "heading tag used for SEO in the HTML page",
        "change the paragraph to a heading style",
        "heading font size larger than body text",
        "table of contents built from headings",
        "remove heading style and apply normal text",
        "document heading visible in the outline panel",
        "I need a heading icon for my editor app",
        "add a heading symbol to the text formatting toolbar",
        "show a heading for the text style feature",
        "use the heading icon for the document structure screen",
        "aplly H1 to the main ttile",
        "sectoin heaidng as H2",
        "boldd large headng on the page",
        "heading hierrachy in the doc",
        "change parargraph to headng stlye",
    ],
    new_ru=[
        "H1",
        "H2",
        "стиль текста",
        "применить H1 к главному заголовку страницы",
        "заголовок раздела в стиле H2",
        "заголовок главы в документе",
        "жирный крупный заголовок в начале статьи",
        "иерархия заголовков H1 H2 H3 в документе",
        "добавить заголовок чтобы разбить текст на разделы",
        "тег заголовка для SEO на HTML-странице",
        "сменить абзац на стиль заголовка",
        "шрифт заголовка крупнее основного текста",
        "оглавление строится из заголовков",
        "убрать стиль заголовка применить обычный текст",
        "заголовок документа виден на панели структуры",
        "нужна иконка заголовка для редактора",
        "добавить символ заголовка на панель форматирования текста",
        "показать заголовок для функции стилей текста",
        "использовать иконку заголовка для экрана структуры документа",
        "применить H1 к главному заголовку",
        "заголовок раздела H2",
        "жирный крупный заголовок на странице",
        "иерархия заголовков в документе",
        "сменить абзац на стиль заголовка",
    ],
)

# ── 502: hood-cloak ───────────────────────────────────────────────────────────
expand("hood-cloak",
    new_en=[
        "cloak",
        "hood",
        "rogue",
        "hooded figure in a dark cloak",
        "medieval hooded cloak costume",
        "fantasy rogue wearing a hood and cloak",
        "mysterious figure in a long dark cloak",
        "assassin's hood pulled low over the face",
        "druid in a ceremonial cloak",
        "hooded cloak icon for a fantasy RPG app",
        "dark hood obscuring the face in shadows",
        "ranger's traveling cloak in the forest",
        "halloween cloak and hood costume",
        "wizard's robe with a pointed hood",
        "infiltrate the enemy camp in stealth mode",
        "rogue ability: vanish in the shadows",
        "stealth cloak ability unlocked",
        "I need a cloak icon for my RPG game app",
        "add a hood symbol to the character class section",
        "show a cloak for the stealth ability feature",
        "use the hood-cloak icon for the rogue class screen",
        "hoodded figure in a dark clakc",
        "fantsy rogue with hood and cloack",
        "assasins hood low ovr face",
        "stealth clok abiltiy",
        "rogeu class in d&d",
    ],
    new_ru=[
        "плащ",
        "капюшон",
        "разбойник",
        "фигура в капюшоне в тёмном плаще",
        "средневековый костюм плаща с капюшоном",
        "фэнтезийный разбойник в капюшоне и плаще",
        "таинственная фигура в длинном тёмном плаще",
        "капюшон ассасина низко надвинут на лицо",
        "друид в церемониальном плаще",
        "иконка плаща с капюшоном для RPG-приложения",
        "тёмный капюшон скрывает лицо в тени",
        "дорожный плащ рейнджера в лесу",
        "костюм плаща и капюшона на хэллоуин",
        "мантия волшебника с остроконечным капюшоном",
        "проникнуть в лагерь врага в режиме скрытности",
        "способность разбойника: раствориться в тени",
        "разблокирована способность плаща невидимости",
        "нужна иконка плаща для приложения RPG",
        "добавить символ капюшона в раздел классов персонажей",
        "показать плащ для функции скрытности",
        "использовать иконку плаща для экрана класса разбойника",
        "фигура в капюшоне в тёмном плаще",
        "фэнтезийный разбойник в капюшоне",
        "капюшон ассасина низко надвинут",
        "способность плаща невидимости",
        "класс разбойника в D&D",
    ],
)

# ── 503: house ────────────────────────────────────────────────────────────────
# Fix: "building" replaced with "house"
expand("house",
    fix_en={
        "Inspect the building before buying",
        "Maintain the building",
    },
    fix_ru={
        "Осмотр здания перед покупкой",
        "Поддерживать здание",
    },
    new_en=[
        "house",
        "home",
        "inspect the house before buying",
        "single-family house with a front yard",
        "two-storey house in a quiet neighborhood",
        "house icon for a real estate app",
        "go home after a long day at work",
        "smart home controlled from the phone",
        "house with a white picket fence",
        "home address saved in the navigation app",
        "maintain and repair the house over time",
        "house rules posted on the fridge",
        "buy a house in the suburbs this year",
        "house listed for sale on the website",
        "renovate the kitchen in the house",
        "house key on the ring by the door",
        "evening at home relaxing on the porch",
        "I need a house icon for my real estate app",
        "add a home symbol to the navigation section",
        "show a house for the property listing feature",
        "use the house icon for the home screen button",
        "inspct the houes before buying",
        "singlr family house with yard",
        "smrat hoem on the phoen",
        "houes icon real esatate app",
        "go hoem after wrk",
    ],
    new_ru=[
        "дом",
        "жилище",
        "осмотреть дом перед покупкой",
        "отдельно стоящий дом с палисадником",
        "двухэтажный дом в тихом районе",
        "иконка дома для приложения недвижимости",
        "вернуться домой после долгого рабочего дня",
        "умный дом управляется с телефона",
        "дом с белым деревянным забором",
        "домашний адрес сохранён в навигации",
        "обслуживать и ремонтировать дом",
        "правила дома на холодильнике",
        "купить дом в пригороде в этом году",
        "дом выставлен на продажу на сайте",
        "сделать ремонт кухни в доме",
        "ключ от дома на связке у двери",
        "вечер дома на веранде",
        "нужна иконка дома для приложения недвижимости",
        "добавить символ дома в раздел навигации",
        "показать дом для функции списка объектов",
        "использовать иконку дома для кнопки главного экрана",
        "осмотреть дом перед покупкой",
        "отдельный дом с двором",
        "умный дом на телефоне",
        "иконка дома для приложения недвижимости",
        "идти домой после работы",
    ],
)

# ── 504: lamp ─────────────────────────────────────────────────────────────────
expand("lamp",
    new_en=[
        "lamp",
        "floor lamp",
        "table lamp",
        "floor lamp standing in the corner",
        "table lamp with a fabric drum shade",
        "lamp turned on for reading at night",
        "smart lamp changes color with an app",
        "arc lamp curving over the sofa",
        "lamp icon for a smart lighting app",
        "lamp with a white linen shade",
        "bedside lamp on the nightstand",
        "designer lamp as a living room accent",
        "floor lamp with an adjustable arm",
        "lamp that dims to a warm glow",
        "replace the bulb in the floor lamp",
        "lamp casting a soft light on the wall",
        "I need a lamp icon for my home app",
        "add a lamp symbol to the lighting section",
        "show a lamp for the room ambiance feature",
        "use the lamp icon for the lighting control screen",
        "flor lamp in the cornner",
        "tabel lamp witth shade",
        "lamp turnde on for reding",
        "smartt lamp changes collor",
        "bedsdie lamp on nightsatnd",
    ],
    new_ru=[
        "лампа",
        "торшер",
        "настольная лампа",
        "торшер стоит в углу",
        "настольная лампа с тканевым абажуром",
        "лампа включена для чтения ночью",
        "умная лампа меняет цвет через приложение",
        "лампа на длинной дуге над диваном",
        "иконка лампы для приложения умного освещения",
        "лампа с белым льняным абажуром",
        "прикроватная лампа на тумбочке",
        "дизайнерская лампа как акцент в гостиной",
        "торшер с регулируемым кронштейном",
        "лампа приглушается до тёплого свечения",
        "заменить лампочку в торшере",
        "лампа отбрасывает мягкий свет на стену",
        "нужна иконка лампы для домашнего приложения",
        "добавить символ лампы в раздел освещения",
        "показать лампу для функции атмосферы комнаты",
        "использовать иконку лампы для управления освещением",
        "торшер в углу",
        "настольная лампа с абажуром",
        "лампа включена для чтения",
        "умная лампа меняет цвет",
        "прикроватная лампа на тумбочке",
    ],
)

# ── 505: lamp-desk ────────────────────────────────────────────────────────────
expand("lamp-desk",
    new_en=[
        "desk lamp",
        "study light",
        "task light",
        "desk lamp focused beam on the work surface",
        "LED desk lamp with adjustable color temperature",
        "USB-powered desk lamp charging a phone",
        "architect's lamp clamped to the drafting table",
        "desk lamp turned on for late-night reading",
        "swing-arm desk lamp for detailed work",
        "desk lamp icon for a productivity app",
        "clip-on desk lamp attached to the monitor",
        "desk lamp with a built-in wireless charger",
        "energy-saving LED desk lamp for the office",
        "desk lamp that adjusts brightness by touch",
        "pull the desk lamp closer to the textbook",
        "I need a desk lamp icon for my work app",
        "add a desk lamp symbol to the office section",
        "show a desk lamp for the study mode feature",
        "use the lamp-desk icon for the workspace lighting screen",
        "LED dessk lamp adjsutbale colr",
        "desk lmap clmped to the drafting tabel",
        "arcitect lamp on the desk",
        "desk lamp touchh dimmer",
        "studdy light for late-niight work",
    ],
    new_ru=[
        "настольная лампа",
        "рабочий свет",
        "лампа для работы",
        "направленный пучок настольной лампы на рабочую поверхность",
        "светодиодная настольная лампа с регулировкой цветовой температуры",
        "настольная лампа на USB зарядит телефон",
        "лампа архитектора зажата на чертёжной доске",
        "настольная лампа включена для ночного чтения",
        "лампа с поворотным кронштейном для точных работ",
        "иконка настольной лампы для приложения продуктивности",
        "лампа-прищепка на мониторе",
        "настольная лампа со встроенной беспроводной зарядкой",
        "энергосберегающая светодиодная лампа для офиса",
        "настольная лампа регулируется касанием",
        "придвинуть лампу ближе к учебнику",
        "нужна иконка настольной лампы для рабочего приложения",
        "добавить символ лампы в раздел офиса",
        "показать настольную лампу для режима учёбы",
        "использовать иконку лампы для экрана рабочего освещения",
        "светодиодная настольная лампа с регулировкой цвета",
        "лампа архитектора на чертёжном столе",
        "лампа-прищепка на столе",
        "настольная лампа с сенсорным диммером",
        "рабочий свет для ночной работы",
    ],
)

print("Done.")
