#!/usr/bin/env python3
"""Task-007 part C: stomach, store, subtitles"""
from gen_icons_task_007_common import build_icon

# ── stomach ──────────────────────────────────────────────────────────────────
build_icon("stomach", {
    "en": [
        "stomach", "abdomen", "belly", "gut", "tummy", "organ",
        "digestion", "hungry", "intestine", "gastro", "nausea",
        "bloating", "acid reflux", "indigestion", "heartburn",
        "appetite", "cramps", "ulcer",
        "take stomach medicine after dinner",
        "schedule a doctor appointment for stomach pain",
        "my stomach has been upset all day",
        "buy antacids at the pharmacy",
        "the stomach flu is going around be careful",
        "eat smaller meals to help with digestion",
        "drink ginger tea for the upset stomach",
        "stomach cramps after eating dairy again",
        "see a gastro specialist about the stomach issues",
        "take a probiotic for gut health",
        "the baby has a tummy ache give her some water",
        "track what I eat and how my stomach feels",
        "avoid spicy food my stomach can't handle it",
        "stomach is growling need to eat lunch",
        "pick up Pepto-Bismol for the stomach bug",
        "start a diet plan to help with stomach problems",
        "bloating after every meal need to figure out why",
        "acid reflux at night prop up the pillows",
        "my stomach hurts after eating too fast",
        "research foods that are easy on the stomach",
        "the stomach is still sore from yesterday",
        "take digestive enzymes before the big meal",
        "see if the stomach pain goes away by tomorrow",
        "drink warm water on an empty stomach in the morning",
        "the kids have a stomach bug keep them home",
        "make bone broth for the stomach recovery",
        "cut back on coffee the stomach can't take it",
        "stomach feels off after the airplane food",
        "get a heating pad for the stomach cramps",
        "make an appointment for a stomach ultrasound",
        "food poisoning from the restaurant stomach is wrecked",
        "try the BRAT diet for the upset stomach",
        "the nausea won't go away call the doctor",
        "eat yogurt for the gut bacteria",
        "my belly is so bloated after that meal",
        "stomach issues run in the family see a specialist",
        "skip the fried food bad for the stomach",
        "heartburn after the spicy dinner",
        "take the antacid before bed for the stomach",
        "buy a food journal to track stomach reactions",
        "stomache ache after dinner",
        "stomch pain in the morning",
        "stomack growling before lunch",
        "stoamch feels upset today",
        "tummmy ache from eating too much",
    ],
    "ru": [
        "желудок", "живот", "брюхо", "кишки", "животик", "орган",
        "пищеварение", "голодный", "кишечник", "гастро", "тошнота",
        "вздутие", "кислотный рефлюкс", "несварение", "изжога",
        "аппетит", "спазмы", "язва",
        "принять лекарство для желудка после ужина",
        "записаться к врачу из-за боли в желудке",
        "желудок болит весь день",
        "купить антацид в аптеке",
        "кишечный грипп ходит будьте осторожны",
        "есть маленькими порциями для лучшего пищеварения",
        "пить имбирный чай при расстройстве желудка",
        "спазмы в желудке после молочных продуктов опять",
        "сходить к гастроэнтерологу по поводу желудка",
        "начать пить пробиотик для здоровья кишечника",
        "у ребёнка болит животик дать воды",
        "записывать что ем и как чувствует себя желудок",
        "не есть острое желудок не выдерживает",
        "желудок урчит надо пообедать",
        "купить средство от расстройства желудка",
        "начать диету чтобы помочь с проблемами желудка",
        "вздутие после каждого приёма пищи разобраться",
        "кислотный рефлюкс ночью подложить подушки повыше",
        "желудок болит после того как ем слишком быстро",
        "узнать какие продукты щадящие для желудка",
        "желудок до сих пор болит после вчерашнего",
        "принять пищеварительные ферменты перед большой едой",
        "посмотреть пройдёт ли боль в желудке к завтра",
        "пить тёплую воду натощак утром",
        "у детей кишечный вирус оставить дома",
        "сварить костный бульон для восстановления желудка",
        "сократить кофе желудок не справляется",
        "желудок не в порядке после еды в самолёте",
        "купить грелку от спазмов в животе",
        "записаться на УЗИ желудка",
        "отравление в ресторане желудок убит",
        "попробовать диету BRAT при расстройстве желудка",
        "тошнота не проходит позвонить врачу",
        "есть йогурт для бактерий кишечника",
        "живот раздулся после этой еды",
        "проблемы с желудком семейные сходить к специалисту",
        "не есть жареное плохо для желудка",
        "изжога после острого ужина",
        "принять антацид перед сном от желудка",
        "купить дневник питания чтобы отслеживать реакции желудка",
        "болит жлудок после ужина",
        "боль в желдуке утром",
        "желудок урчти перед обедом",
        "желудко плохо сегодня",
        "животик болти от переедания",
    ],
    "de": [
        "Magen", "Bauch", "Unterleib", "Darm", "Bäuchlein", "Organ",
        "Verdauung", "hungrig", "Darm", "Gastro", "Übelkeit",
        "Blähungen", "Sodbrennen", "Magenverstimmung", "saures Aufstoßen",
        "Appetit", "Krämpfe", "Magengeschwür",
        "nach dem Abendessen Magenmedizin nehmen",
        "Arzttermin wegen Magenschmerzen vereinbaren",
        "mein Magen ist den ganzen Tag verstimmt",
        "Antazida in der Apotheke kaufen",
        "Magen-Darm-Grippe geht um aufpassen",
        "kleinere Mahlzeiten für bessere Verdauung essen",
        "Ingwertee gegen den verstimmten Magen trinken",
        "Magenkrämpfe nach Milchprodukten schon wieder",
        "zum Gastroenterologen wegen der Magenprobleme",
        "ein Probiotikum für die Darmgesundheit nehmen",
        "das Baby hat Bauchweh etwas Wasser geben",
        "aufschreiben was ich esse und wie mein Magen sich fühlt",
        "scharfes Essen vermeiden Magen verträgt das nicht",
        "Magen knurrt muss Mittagessen",
        "Mittel gegen Magenverstimmung kaufen",
        "einen Diätplan gegen Magenprobleme starten",
        "Blähungen nach jeder Mahlzeit herausfinden warum",
        "Sodbrennen nachts Kissen höher legen",
        "Magen tut weh nach zu schnellem Essen",
        "recherchieren welche Lebensmittel magenfreundlich sind",
        "Magen ist noch wund von gestern",
        "Verdauungsenzyme vor dem großen Essen nehmen",
        "schauen ob die Magenschmerzen bis morgen weggehen",
        "morgens warmes Wasser auf nüchternen Magen trinken",
        "die Kinder haben einen Magen-Darm-Infekt zu Hause behalten",
        "Knochenbrühe zur Magenerholung kochen",
        "Kaffee reduzieren der Magen verträgt es nicht",
        "Magen fühlt sich komisch an nach dem Flugzeugessen",
        "Wärmflasche gegen die Magenkrämpfe kaufen",
        "Termin für einen Magen-Ultraschall machen",
        "Lebensmittelvergiftung aus dem Restaurant Magen ist kaputt",
        "Schonkost bei Magenverstimmung ausprobieren",
        "die Übelkeit hört nicht auf den Arzt anrufen",
        "Joghurt für die Darmbakterien essen",
        "mein Bauch ist so aufgebläht nach dem Essen",
        "Magenprobleme liegen in der Familie zum Spezialisten gehen",
        "Frittiertes weglassen schlecht für den Magen",
        "Sodbrennen nach dem scharfen Abendessen",
        "Antazida vor dem Schlafen für den Magen nehmen",
        "ein Ernährungstagebuch kaufen um Magenreaktionen zu verfolgen",
        "Magneschmerzen nach dem Abendessen",
        "Magn tut weh am Morgen",
        "Magen knurt vor dem Mittagessen",
        "Magn fühlt sich schlecht an heute",
        "Bauchwhe vom zu viel Essen",
    ],
    "ja": [
        "胃", "腹部", "お腹", "腸", "おなか", "臓器",
        "消化", "空腹", "腸管", "胃腸", "吐き気",
        "膨満感", "逆流性食道炎", "消化不良", "胸焼け",
        "食欲", "痙攣", "潰瘍",
        "夕食後に胃薬を飲む",
        "胃の痛みで医者の予約を取る",
        "一日中胃の調子が悪い",
        "薬局で胃薬を買う",
        "胃腸風邪が流行っている気をつけて",
        "消化を助けるために少量ずつ食べる",
        "胃の不調にジンジャーティーを飲む",
        "乳製品の後にまた胃が痙攣した",
        "胃の問題で消化器専門医に診てもらう",
        "腸の健康のためにプロバイオティクスを飲む",
        "赤ちゃんのおなかが痛いお水をあげる",
        "何を食べて胃がどう感じたか記録する",
        "辛いものを避ける胃が耐えられない",
        "胃が鳴っているお昼を食べないと",
        "胃腸薬を買ってくる",
        "胃の問題に役立つ食事プランを始める",
        "毎食後に膨満感がある原因を調べる",
        "夜の逆流性食道炎枕を高くする",
        "食べるのが早すぎて胃が痛い",
        "胃にやさしい食べ物を調べる",
        "昨日からまだ胃が痛い",
        "大食いの前に消化酵素を飲む",
        "明日までに胃の痛みが治まるか様子を見る",
        "朝の空腹時に白湯を飲む",
        "子供が胃腸風邪にかかった家にいさせる",
        "胃の回復にボーンブロスを作る",
        "コーヒーを減らす胃が持たない",
        "機内食の後に胃の調子がおかしい",
        "胃の痙攣に湯たんぽを買う",
        "胃のエコー検査の予約を入れる",
        "レストランで食中毒胃がやられた",
        "胃の不調にBRAT食を試す",
        "吐き気が治まらない医者に電話する",
        "腸内細菌のためにヨーグルトを食べる",
        "あの食事の後にお腹がすごく張っている",
        "胃の問題は家族性専門医に診てもらう",
        "揚げ物はやめる胃に悪い",
        "辛い夕食の後に胸焼け",
        "寝る前に胃のために制酸剤を飲む",
        "胃の反応を追跡するフードジャーナルを買う",
        "夕食後にい胃が痛い",
        "朝にい痛みがある",
        "昼食前にに胃が鳴る",
        "今日は胃のの調子が悪い",
        "食べすぎでおなかかが痛い",
    ],
    "fr": [
        "estomac", "abdomen", "ventre", "intestin", "bidon", "organe",
        "digestion", "faim", "intestin grêle", "gastro", "nausée",
        "ballonnement", "reflux acide", "indigestion", "brûlures d'estomac",
        "appétit", "crampes", "ulcère",
        "prendre un médicament pour l'estomac après le dîner",
        "prendre rendez-vous chez le médecin pour la douleur d'estomac",
        "mon estomac est dérangé depuis ce matin",
        "acheter des antiacides à la pharmacie",
        "la gastro tourne fais attention",
        "manger de plus petites portions pour faciliter la digestion",
        "boire du thé au gingembre pour l'estomac dérangé",
        "crampes d'estomac après les produits laitiers encore",
        "consulter un gastro-entérologue pour les problèmes d'estomac",
        "prendre un probiotique pour la santé intestinale",
        "le bébé a mal au ventre lui donner de l'eau",
        "noter ce que je mange et comment mon estomac se sent",
        "éviter la nourriture épicée mon estomac ne supporte pas",
        "l'estomac gronde il faut manger",
        "acheter du Smecta pour les problèmes d'estomac",
        "commencer un régime pour aider les problèmes d'estomac",
        "ballonnements après chaque repas comprendre pourquoi",
        "reflux acide la nuit surélever les oreillers",
        "mal à l'estomac après avoir mangé trop vite",
        "chercher les aliments faciles pour l'estomac",
        "l'estomac est encore douloureux depuis hier",
        "prendre des enzymes digestives avant le gros repas",
        "voir si la douleur d'estomac passe d'ici demain",
        "boire de l'eau tiède à jeun le matin",
        "les enfants ont une gastro les garder à la maison",
        "faire du bouillon d'os pour la récupération de l'estomac",
        "réduire le café l'estomac ne supporte plus",
        "estomac bizarre après la nourriture de l'avion",
        "acheter une bouillotte pour les crampes d'estomac",
        "prendre rendez-vous pour une échographie de l'estomac",
        "intoxication alimentaire au restaurant estomac détruit",
        "essayer le régime BRAT pour l'estomac dérangé",
        "la nausée ne part pas appeler le médecin",
        "manger du yaourt pour les bactéries intestinales",
        "mon ventre est tout gonflé après ce repas",
        "les problèmes d'estomac courent dans la famille voir un spécialiste",
        "éviter le frit mauvais pour l'estomac",
        "brûlures d'estomac après le dîner épicé",
        "prendre un antiacide avant de dormir pour l'estomac",
        "acheter un journal alimentaire pour suivre les réactions",
        "mal à l'estomca après le dîner",
        "douleur à l'estomca le matin",
        "l'estomac gronde avant le dèjeuner",
        "l'esotmac va mal aujourd'hui",
        "mal au venrte d'avoir trop mangé",
    ],
    "es": [
        "estómago", "abdomen", "barriga", "tripa", "pancita", "órgano",
        "digestión", "hambriento", "intestino", "gastro", "náusea",
        "hinchazón", "reflujo ácido", "indigestión", "acidez",
        "apetito", "calambres", "úlcera",
        "tomar medicina para el estómago después de cenar",
        "sacar cita con el doctor por el dolor de estómago",
        "el estómago me ha dolido todo el día",
        "comprar antiácidos en la farmacia",
        "anda un virus estomacal ten cuidado",
        "comer porciones más pequeñas para mejor digestión",
        "tomar té de jengibre para el estómago revuelto",
        "calambres de estómago después de lácteos otra vez",
        "ir al gastroenterólogo por los problemas de estómago",
        "empezar a tomar probióticos para la salud intestinal",
        "al bebé le duele la pancita darle agua",
        "registrar qué como y cómo se siente el estómago",
        "evitar comida picante el estómago no la aguanta",
        "el estómago ruge hay que almorzar",
        "comprar algo para el malestar estomacal",
        "empezar un plan de dieta para los problemas del estómago",
        "hinchazón después de cada comida averiguar por qué",
        "reflujo ácido en la noche levantar las almohadas",
        "me duele el estómago de comer tan rápido",
        "investigar alimentos suaves para el estómago",
        "el estómago sigue adolorido desde ayer",
        "tomar enzimas digestivas antes de la comida grande",
        "ver si el dolor de estómago se pasa para mañana",
        "tomar agua tibia en ayunas por la mañana",
        "los niños tienen virus estomacal dejarlos en casa",
        "hacer caldo de hueso para recuperar el estómago",
        "reducir el café el estómago no puede más",
        "el estómago se siente raro después de la comida del avión",
        "comprar una bolsa de agua caliente para los calambres",
        "hacer cita para un ultrasonido del estómago",
        "intoxicación del restaurante el estómago está destrozado",
        "probar la dieta BRAT para el estómago revuelto",
        "la náusea no se va llamar al doctor",
        "comer yogurt por las bacterias intestinales",
        "mi barriga está muy hinchada después de esa comida",
        "los problemas de estómago son de familia ver al especialista",
        "no comer frito es malo para el estómago",
        "acidez después de la cena picante",
        "tomar el antiácido antes de dormir para el estómago",
        "comprar un diario de comidas para rastrear reacciones",
        "dolor de estómgao después de cenar",
        "el estómgao me duele en la mañana",
        "el estómago ruge antse del almuerzo",
        "el estóamgo anda mal hoy",
        "dolor de panctia por comer de más",
    ],
})


# ── store ────────────────────────────────────────────────────────────────────
build_icon("store", {
    "en": [
        "store", "market", "buy", "retail", "building", "brick and mortar",
        "grocery", "mall", "convenience store", "department store",
        "supermarket", "shopping", "checkout", "aisle", "plaza",
        "storefront", "outlet", "boutique",
        "go to the store and pick up milk",
        "the store closes at nine hurry up",
        "check if the store has it in stock",
        "new store opening in the neighborhood",
        "return the shirt to the store this weekend",
        "the grocery store is having a sale on chicken",
        "stop at the convenience store for snacks",
        "compare prices at different stores",
        "the store is out of what I need try another one",
        "get to the store before the rush",
        "find a hardware store near me",
        "go to the pet store for dog food",
        "the store has a buy one get one deal",
        "swing by the store on the way home",
        "store pickup is ready go grab it",
        "the electronics store is having a clearance sale",
        "find the nearest grocery store in the new town",
        "walk to the corner store for bread",
        "the store is crowded on weekends go on Wednesday",
        "make a shopping list before going to the store",
        "the store opens at seven in the morning",
        "check the store website for hours",
        "the dollar store has party supplies",
        "bring reusable bags to the store",
        "park close to the store entrance",
        "the kids want to go to the toy store",
        "gift card for the store as a birthday present",
        "the outlet store has discounted clothes",
        "drive to the store to pick up the online order",
        "ask the store manager about the return policy",
        "try the new organic store downtown",
        "the store is right next to the pharmacy",
        "hit the store after work for groceries",
        "sign up for the store rewards program",
        "store visit to check out the new arrivals",
        "the furniture store delivers free on orders over 500",
        "grcoery store nearby",
        "shoping at the market",
        "purhcase at the store",
        "stoer building on main street",
        "go to the stoer after work",
    ],
    "ru": [
        "магазин", "рынок", "купить", "розница", "здание",
        "обычный магазин", "продуктовый", "торговый центр",
        "круглосуточный магазин", "универмаг", "супермаркет", "шоппинг",
        "касса", "проход", "площадка", "витрина", "аутлет", "бутик",
        "сходить в магазин за молоком",
        "магазин закрывается в девять поторопись",
        "проверить есть ли это в наличии в магазине",
        "новый магазин открывается в районе",
        "вернуть рубашку в магазин в выходные",
        "в продуктовом магазине скидка на курицу",
        "зайти в круглосуточный магазин за перекусом",
        "сравнить цены в разных магазинах",
        "в магазине нет того что нужно попробовать другой",
        "добраться до магазина до наплыва покупателей",
        "найти строительный магазин поблизости",
        "сходить в зоомагазин за собачьим кормом",
        "в магазине акция два по цене одного",
        "заскочить в магазин по дороге домой",
        "заказ готов к выдаче в магазине забрать",
        "в магазине электроники распродажа остатков",
        "найти ближайший продуктовый в новом городе",
        "дойти до углового магазина за хлебом",
        "в магазине толпа по выходным идти в среду",
        "составить список покупок перед походом в магазин",
        "магазин открывается в семь утра",
        "проверить график работы магазина на сайте",
        "в магазине всё по рублю есть товары для праздника",
        "взять многоразовые пакеты в магазин",
        "припарковаться у входа в магазин",
        "дети хотят пойти в магазин игрушек",
        "подарочная карта магазина на день рождения",
        "в аутлете одежда со скидкой",
        "поехать в магазин забрать онлайн-заказ",
        "спросить менеджера магазина о правилах возврата",
        "попробовать новый органический магазин в центре",
        "магазин прямо рядом с аптекой",
        "заехать в магазин после работы за продуктами",
        "зарегистрироваться в программе лояльности магазина",
        "визит в магазин посмотреть новинки",
        "мебельный магазин доставляет бесплатно от 500",
        "продуктовый магзин рядом",
        "шопинг на рнке",
        "покупак в магазине",
        "здание магазна на главной",
        "заехать в магзин после работы",
    ],
    "de": [
        "Geschäft", "Markt", "kaufen", "Einzelhandel", "Gebäude",
        "stationärer Handel", "Lebensmittelgeschäft", "Einkaufszentrum",
        "Kiosk", "Kaufhaus", "Supermarkt", "Einkaufen",
        "Kasse", "Gang", "Einkaufsplatz", "Schaufenster", "Outlet",
        "Boutique",
        "in den Laden gehen und Milch holen",
        "der Laden schließt um neun beeil dich",
        "prüfen ob der Laden es auf Lager hat",
        "neuer Laden eröffnet in der Nachbarschaft",
        "das Hemd am Wochenende im Laden zurückgeben",
        "im Supermarkt gibt es Hähnchen im Angebot",
        "am Kiosk Snacks holen",
        "Preise in verschiedenen Geschäften vergleichen",
        "der Laden hat nicht was ich brauche anderen probieren",
        "vor dem Ansturm im Laden sein",
        "einen Baumarkt in der Nähe finden",
        "in die Zoohandlung für Hundefutter gehen",
        "im Laden gibt es ein Kauf-eins-bekomm-eins Angebot",
        "auf dem Heimweg am Laden vorbeifahren",
        "Abholung im Laden ist bereit hinfahren",
        "der Elektronikladen hat Räumungsverkauf",
        "den nächsten Supermarkt in der neuen Stadt finden",
        "zum Eckladen für Brot laufen",
        "der Laden ist am Wochenende voll Mittwoch hingehen",
        "eine Einkaufsliste schreiben bevor man in den Laden geht",
        "der Laden öffnet um sieben Uhr morgens",
        "die Öffnungszeiten des Ladens auf der Website prüfen",
        "im Euroladen gibt es Partybedarf",
        "wiederverwendbare Tüten in den Laden mitnehmen",
        "nah am Ladeneingang parken",
        "die Kinder wollen in den Spielzeugladen",
        "Geschenkkarte für den Laden als Geburtstagsgeschenk",
        "im Outlet-Store gibt es reduzierte Kleidung",
        "zum Laden fahren die Online-Bestellung abholen",
        "den Filialleiter nach den Rückgaberegeln fragen",
        "den neuen Bio-Laden in der Innenstadt ausprobieren",
        "der Laden ist direkt neben der Apotheke",
        "nach der Arbeit im Laden für Lebensmittel vorbeischauen",
        "sich für das Bonusprogramm des Ladens anmelden",
        "Ladenbesuch um die Neuheiten anzuschauen",
        "der Möbelladen liefert ab 500 Euro kostenlos",
        "Lebensmittelgschäft in der Nähe",
        "Einkaufen auf dem Makrt",
        "Einkuaf im Geschäft",
        "Ladengebäude in der Hauptsrtraße",
        "nach der Arbeit zum Ladn fahren",
    ],
    "ja": [
        "お店", "市場", "買う", "小売", "建物", "実店舗",
        "食料品店", "ショッピングモール", "コンビニ", "デパート",
        "スーパー", "買い物", "レジ", "通路", "商店街",
        "店先", "アウトレット", "ブティック",
        "お店に行って牛乳を買う",
        "お店が9時に閉まる急いで",
        "お店に在庫があるか確認する",
        "近所に新しいお店がオープンする",
        "週末にシャツをお店に返品する",
        "スーパーで鶏肉がセール中",
        "コンビニでお菓子を買う",
        "いろんなお店で値段を比較する",
        "お店に欲しいものがない別のお店を試す",
        "混む前にお店に行く",
        "近くのホームセンターを探す",
        "ペットショップにドッグフードを買いに行く",
        "お店で1つ買うと1つ無料のセール",
        "帰り道にお店に寄る",
        "お店での受け取りが準備できた取りに行く",
        "電器店でクリアランスセール中",
        "新しい街で一番近いスーパーを探す",
        "角のお店までパンを買いに歩く",
        "週末はお店が混んでいる水曜に行く",
        "お店に行く前に買い物リストを作る",
        "お店は朝7時に開く",
        "お店のサイトで営業時間を確認する",
        "百均にパーティー用品がある",
        "お店にエコバッグを持っていく",
        "お店の入り口近くに駐車する",
        "子供がおもちゃ屋に行きたがっている",
        "お店のギフトカードを誕生日プレゼントに",
        "アウトレットで割引の服がある",
        "オンライン注文の受け取りにお店へ車で行く",
        "お店の店長に返品ポリシーを聞く",
        "ダウンタウンの新しいオーガニックストアを試す",
        "お店は薬局のすぐ隣",
        "仕事帰りにお店で食料品を買う",
        "お店のポイントプログラムに登録する",
        "お店を訪れて新商品をチェックする",
        "家具店は500以上で送料無料",
        "近くのスーパパーに行く",
        "市場でで買い物する",
        "お店でで購入する",
        "メイン通りのの店の建物",
        "仕事帰りにに店に寄る",
    ],
    "fr": [
        "magasin", "marché", "acheter", "commerce", "bâtiment",
        "magasin physique", "épicerie", "centre commercial",
        "supérette", "grand magasin", "supermarché", "courses",
        "caisse", "rayon", "place commerciale", "vitrine", "outlet",
        "boutique",
        "aller au magasin acheter du lait",
        "le magasin ferme à neuf heures dépêche-toi",
        "vérifier si le magasin a le produit en stock",
        "nouveau magasin qui ouvre dans le quartier",
        "rapporter la chemise au magasin ce week-end",
        "le supermarché fait une promo sur le poulet",
        "passer à la supérette pour des snacks",
        "comparer les prix dans différents magasins",
        "le magasin n'a pas ce qu'il me faut essayer un autre",
        "arriver au magasin avant la foule",
        "trouver un magasin de bricolage à proximité",
        "aller à l'animalerie pour la nourriture du chien",
        "le magasin fait une offre un acheté un offert",
        "passer au magasin en rentrant à la maison",
        "le retrait en magasin est prêt aller le chercher",
        "le magasin d'électronique fait un déstockage",
        "trouver le supermarché le plus proche dans la nouvelle ville",
        "marcher jusqu'à l'épicerie du coin pour du pain",
        "le magasin est bondé le week-end y aller mercredi",
        "faire une liste de courses avant d'aller au magasin",
        "le magasin ouvre à sept heures du matin",
        "vérifier les horaires du magasin sur le site",
        "le magasin à un euro a des fournitures de fête",
        "apporter des sacs réutilisables au magasin",
        "se garer près de l'entrée du magasin",
        "les enfants veulent aller au magasin de jouets",
        "une carte cadeau du magasin comme cadeau d'anniversaire",
        "le magasin d'usine a des vêtements en solde",
        "aller au magasin récupérer la commande en ligne",
        "demander au gérant du magasin la politique de retour",
        "essayer le nouveau magasin bio en centre-ville",
        "le magasin est juste à côté de la pharmacie",
        "passer au magasin après le travail pour les courses",
        "s'inscrire au programme de fidélité du magasin",
        "visite au magasin pour voir les nouveautés",
        "le magasin de meubles livre gratuitement au-dessus de 500",
        "le supermarché à proximitié",
        "faire les coruses au marché",
        "acaht au magasin",
        "le bâtiment du maagsin dans la rue principale",
        "passer au magaisn après le travail",
    ],
    "es": [
        "tienda", "mercado", "comprar", "comercio", "edificio",
        "tienda física", "supermercado", "centro comercial",
        "tienda de conveniencia", "almacén", "supermercado grande",
        "compras", "caja", "pasillo", "plaza comercial", "vitrina",
        "outlet", "boutique",
        "ir a la tienda a comprar leche",
        "la tienda cierra a las nueve apúrate",
        "revisar si la tienda tiene existencias",
        "nueva tienda abriendo en el barrio",
        "devolver la camisa a la tienda este fin de semana",
        "el súper tiene oferta en pollo",
        "parar en la tienda de conveniencia por botanas",
        "comparar precios en diferentes tiendas",
        "la tienda no tiene lo que necesito probar otra",
        "llegar a la tienda antes de la hora pico",
        "encontrar una ferretería cerca",
        "ir a la tienda de mascotas por alimento para perro",
        "la tienda tiene oferta de dos por uno",
        "pasar por la tienda de camino a casa",
        "el pedido para recoger en tienda está listo ir por él",
        "la tienda de electrónica tiene venta de liquidación",
        "encontrar el súper más cercano en la nueva ciudad",
        "caminar a la tienda de la esquina por pan",
        "la tienda se llena los fines de semana ir el miércoles",
        "hacer una lista de compras antes de ir a la tienda",
        "la tienda abre a las siete de la mañana",
        "revisar el horario de la tienda en la página web",
        "la tienda de todo a un dólar tiene artículos de fiesta",
        "llevar bolsas reutilizables a la tienda",
        "estacionarse cerca de la entrada de la tienda",
        "los niños quieren ir a la juguetería",
        "tarjeta de regalo de la tienda como regalo de cumpleaños",
        "el outlet tiene ropa con descuento",
        "ir en carro a la tienda a recoger el pedido en línea",
        "preguntar al gerente de la tienda sobre la política de devolución",
        "probar la nueva tienda orgánica del centro",
        "la tienda está justo al lado de la farmacia",
        "pasar a la tienda después del trabajo por víveres",
        "inscribirse en el programa de recompensas de la tienda",
        "visitar la tienda para ver las novedades",
        "la mueblería entrega gratis en pedidos de más de 500",
        "supermecrado cerca",
        "compars en el mercado",
        "compra en la tienba",
        "edificio de la tinda en la calle principal",
        "ir a la tienda despuñes del trabajo",
    ],
})


# ── subtitles ────────────────────────────────────────────────────────────────
build_icon("subtitles", {
    "en": [
        "subtitles", "caption", "closed caption", "language", "text",
        "movie", "CC", "accessibility", "translation", "hearing impaired",
        "foreign film", "streaming", "video player", "font size",
        "timing", "speech recognition", "dubbed", "transcript",
        "turn on subtitles for the movie",
        "enable closed captions on the streaming service",
        "change the subtitle language to Spanish",
        "the subtitles are out of sync fix them",
        "adjust the subtitle font size it's too small",
        "download subtitles for the foreign film",
        "watch the movie with English subtitles",
        "the captions are blocking the picture move them",
        "find a movie with French subtitles for practice",
        "auto-generated subtitles are wrong edit them",
        "turn off subtitles they're distracting",
        "subtitle file is missing for this episode",
        "set subtitles to always on for the kids",
        "the subtitle timing is off by two seconds",
        "change subtitle color to yellow for better contrast",
        "stream the show with dual subtitles for language learning",
        "check if the Blu-ray has subtitles in German",
        "enable live captions for the video call",
        "the deaf viewer needs closed captions on",
        "upload a custom subtitle file for the video",
        "subtitles keep disappearing during the movie",
        "switch from dubbed to subtitled version",
        "set default subtitle language for all videos",
        "the subtitle translation is incorrect report it",
        "enable captions on the kids' tablet for cartoons",
        "hard-coded subtitles cannot be turned off",
        "subtitle delay setting in the video player",
        "watch anime with Japanese subtitles",
        "the live caption feature drains the battery fast",
        "search for subtitle files online",
        "increase subtitle background opacity for readability",
        "prefer subtitles over dubbing for foreign movies",
        "the hearing impaired option adds sound descriptions",
        "set up subtitles on the new smart TV",
        "subtitle encoding is wrong characters look weird",
        "slow down the video the subtitles go too fast",
        "movie night with subtitles so we don't wake the baby",
        "subtitels video player",
        "captoin on the movie",
        "translaiton subtitle settings",
        "clossed captions enabled",
        "subtitls for the foreign film",
    ],
    "ru": [
        "субтитры", "подпись", "скрытые субтитры", "язык", "текст",
        "фильм", "CC", "доступность", "перевод", "для слабослышащих",
        "иностранный фильм", "стриминг", "видеоплеер", "размер шрифта",
        "тайминг", "распознавание речи", "дубляж", "транскрипт",
        "включить субтитры к фильму",
        "включить скрытые субтитры на стриминге",
        "сменить язык субтитров на испанский",
        "субтитры не синхронизированы исправить",
        "увеличить шрифт субтитров слишком мелкий",
        "скачать субтитры к иностранному фильму",
        "смотреть фильм с английскими субтитрами",
        "субтитры закрывают картинку передвинуть",
        "найти фильм с французскими субтитрами для практики",
        "автоматические субтитры неправильные исправить",
        "выключить субтитры они отвлекают",
        "файл субтитров отсутствует для этой серии",
        "включить субтитры по умолчанию для детей",
        "тайминг субтитров отстаёт на две секунды",
        "сменить цвет субтитров на жёлтый для контраста",
        "стримить шоу с двойными субтитрами для изучения языка",
        "проверить есть ли на Blu-ray субтитры на немецком",
        "включить живые субтитры для видеозвонка",
        "слабослышащему зрителю нужны скрытые субтитры",
        "загрузить свой файл субтитров к видео",
        "субтитры исчезают во время фильма",
        "переключиться с дубляжа на субтитры",
        "установить язык субтитров по умолчанию для всех видео",
        "перевод субтитров неправильный сообщить",
        "включить субтитры на планшете для мультиков",
        "вшитые субтитры нельзя отключить",
        "настройка задержки субтитров в видеоплеере",
        "смотреть аниме с японскими субтитрами",
        "функция живых субтитров быстро разряжает батарею",
        "найти файлы субтитров онлайн",
        "увеличить непрозрачность фона субтитров для читаемости",
        "предпочитаю субтитры а не дубляж для иностранных фильмов",
        "для слабослышащих добавляется описание звуков",
        "настроить субтитры на новом смарт-ТВ",
        "кодировка субтитров неправильная символы кривые",
        "замедлить видео субтитры слишком быстро идут",
        "киновечер с субтитрами чтобы не разбудить ребёнка",
        "субтитрs видеоплеер",
        "подписи к филму",
        "настройка перевдоа субтитров",
        "скрытые субтитры включёны",
        "субтитры к иностраному фильму",
    ],
    "de": [
        "Untertitel", "Bildunterschrift", "Untertitel für Hörgeschädigte",
        "Sprache", "Text", "Film", "CC", "Barrierefreiheit", "Übersetzung",
        "hörgeschädigt", "ausländischer Film", "Streaming", "Videoplayer",
        "Schriftgröße", "Timing", "Spracherkennung", "synchronisiert",
        "Transkript",
        "Untertitel für den Film einschalten",
        "Untertitel für Hörgeschädigte im Streaming aktivieren",
        "Untertitelsprache auf Spanisch ändern",
        "die Untertitel sind nicht synchron reparieren",
        "Untertitel-Schriftgröße anpassen zu klein",
        "Untertitel für den ausländischen Film herunterladen",
        "den Film mit englischen Untertiteln schauen",
        "die Untertitel verdecken das Bild verschieben",
        "einen Film mit französischen Untertiteln zum Üben finden",
        "automatische Untertitel sind falsch korrigieren",
        "Untertitel ausschalten sie lenken ab",
        "Untertiteldatei fehlt für diese Folge",
        "Untertitel für die Kinder standardmäßig aktivieren",
        "das Timing der Untertitel ist zwei Sekunden daneben",
        "Untertitelfarbe auf Gelb für besseren Kontrast ändern",
        "die Show mit doppelten Untertiteln zum Sprachenlernen streamen",
        "prüfen ob die Blu-ray deutsche Untertitel hat",
        "Live-Untertitel für den Videoanruf aktivieren",
        "der hörgeschädigte Zuschauer braucht Untertitel",
        "eine eigene Untertiteldatei für das Video hochladen",
        "Untertitel verschwinden während des Films",
        "von Synchronisation auf Untertitel umschalten",
        "Standard-Untertitelsprache für alle Videos einstellen",
        "die Untertitel-Übersetzung ist falsch melden",
        "Untertitel auf dem Kinder-Tablet für Cartoons aktivieren",
        "fest eingebrannte Untertitel lassen sich nicht abschalten",
        "Untertitelverzögerung im Videoplayer einstellen",
        "Anime mit japanischen Untertiteln schauen",
        "die Live-Untertitel-Funktion leert den Akku schnell",
        "Untertiteldateien online suchen",
        "Hintergrunddeckkraft der Untertitel für Lesbarkeit erhöhen",
        "Untertitel statt Synchronisation bei ausländischen Filmen",
        "die Option für Hörgeschädigte fügt Tonbeschreibungen hinzu",
        "Untertitel auf dem neuen Smart-TV einrichten",
        "Untertitel-Kodierung ist falsch Zeichen sehen komisch aus",
        "Video verlangsamen die Untertitel gehen zu schnell",
        "Filmabend mit Untertiteln damit das Baby nicht aufwacht",
        "Untertitl Videoplayer",
        "Bilduntershcrift zum Film",
        "Übersetzng Untertitel Einstellungen",
        "Untertitel für Hörgeshcädigte aktiviert",
        "Untertitel für den ausländishcen Film",
    ],
    "ja": [
        "字幕", "キャプション", "クローズドキャプション", "言語", "テキスト",
        "映画", "CC", "アクセシビリティ", "翻訳", "聴覚障害者",
        "外国映画", "ストリーミング", "動画プレーヤー", "フォントサイズ",
        "タイミング", "音声認識", "吹き替え", "文字起こし",
        "映画の字幕をオンにする",
        "ストリーミングサービスでクローズドキャプションを有効にする",
        "字幕の言語をスペイン語に変更する",
        "字幕がずれている直す",
        "字幕のフォントサイズを調整する小さすぎる",
        "外国映画の字幕をダウンロードする",
        "英語字幕で映画を見る",
        "字幕が画面を隠している移動する",
        "練習のためにフランス語字幕の映画を探す",
        "自動生成字幕が間違っている修正する",
        "字幕をオフにする気が散る",
        "このエピソードの字幕ファイルがない",
        "子供用にデフォルトで字幕をオンにする",
        "字幕のタイミングが2秒ずれている",
        "コントラストのために字幕の色を黄色に変える",
        "語学学習のために二か国語字幕でドラマを見る",
        "Blu-rayにドイツ語字幕があるか確認する",
        "ビデオ通話でライブキャプションを有効にする",
        "聴覚障害の視聴者にクローズドキャプションが必要",
        "動画にカスタム字幕ファイルをアップロードする",
        "映画中に字幕が消えてしまう",
        "吹き替えから字幕版に切り替える",
        "すべての動画のデフォルト字幕言語を設定する",
        "字幕の翻訳が間違っている報告する",
        "子供のタブレットでアニメの字幕を有効にする",
        "ハードコード字幕はオフにできない",
        "動画プレーヤーの字幕遅延設定",
        "日本語字幕でアニメを見る",
        "ライブキャプション機能がバッテリーを早く消耗する",
        "字幕ファイルをオンラインで検索する",
        "読みやすさのために字幕の背景の不透明度を上げる",
        "外国映画は吹き替えより字幕が好み",
        "聴覚障害者オプションで音の説明が追加される",
        "新しいスマートTVで字幕を設定する",
        "字幕のエンコーディングがおかしい文字が変",
        "動画を遅くする字幕が速すぎる",
        "赤ちゃんを起こさないように字幕付きで映画鑑賞",
        "字幕す動画プレーヤー",
        "映画にキャプションンを付ける",
        "翻訳やく字幕設定",
        "クローズドキャプションンが有効",
        "外国映画のの字幕",
    ],
    "fr": [
        "sous-titres", "légende", "sous-titres codés", "langue", "texte",
        "film", "CC", "accessibilité", "traduction", "malentendants",
        "film étranger", "streaming", "lecteur vidéo", "taille de police",
        "synchronisation", "reconnaissance vocale", "doublé", "transcription",
        "activer les sous-titres du film",
        "activer les sous-titres codés sur le service de streaming",
        "changer la langue des sous-titres en espagnol",
        "les sous-titres sont décalés les corriger",
        "ajuster la taille de police des sous-titres trop petite",
        "télécharger les sous-titres du film étranger",
        "regarder le film avec des sous-titres en anglais",
        "les sous-titres cachent l'image les déplacer",
        "trouver un film avec des sous-titres en français pour s'exercer",
        "les sous-titres automatiques sont faux les corriger",
        "désactiver les sous-titres ils distraient",
        "le fichier de sous-titres manque pour cet épisode",
        "activer les sous-titres par défaut pour les enfants",
        "le timing des sous-titres est décalé de deux secondes",
        "changer la couleur des sous-titres en jaune pour le contraste",
        "regarder la série avec double sous-titres pour apprendre la langue",
        "vérifier si le Blu-ray a des sous-titres en allemand",
        "activer les sous-titres en direct pour l'appel vidéo",
        "le spectateur malentendant a besoin des sous-titres codés",
        "charger un fichier de sous-titres personnalisé",
        "les sous-titres disparaissent pendant le film",
        "passer de la version doublée à la version sous-titrée",
        "définir la langue des sous-titres par défaut pour toutes les vidéos",
        "la traduction des sous-titres est incorrecte la signaler",
        "activer les sous-titres sur la tablette des enfants pour les dessins animés",
        "les sous-titres incrustés ne peuvent pas être désactivés",
        "réglage du délai des sous-titres dans le lecteur vidéo",
        "regarder un anime avec des sous-titres japonais",
        "la fonction de sous-titres en direct vide la batterie vite",
        "chercher des fichiers de sous-titres en ligne",
        "augmenter l'opacité du fond des sous-titres pour la lisibilité",
        "préférer les sous-titres au doublage pour les films étrangers",
        "l'option malentendants ajoute des descriptions sonores",
        "configurer les sous-titres sur la nouvelle smart TV",
        "l'encodage des sous-titres est mauvais les caractères sont bizarres",
        "ralentir la vidéo les sous-titres vont trop vite",
        "soirée film avec sous-titres pour ne pas réveiller le bébé",
        "sous-titrs dans le lecteur vidéo",
        "légnde sur le film",
        "traductiom des sous-titres",
        "sous-titres codéss activés",
        "sous-titres du flim étranger",
    ],
    "es": [
        "subtítulos", "leyenda", "subtítulos cerrados", "idioma", "texto",
        "película", "CC", "accesibilidad", "traducción",
        "personas con discapacidad auditiva", "película extranjera",
        "streaming", "reproductor de video", "tamaño de fuente",
        "sincronización", "reconocimiento de voz", "doblado",
        "transcripción",
        "activar los subtítulos de la película",
        "habilitar subtítulos cerrados en el servicio de streaming",
        "cambiar el idioma de subtítulos a español",
        "los subtítulos están desfasados arreglarlos",
        "ajustar el tamaño de fuente de subtítulos está muy chico",
        "descargar subtítulos para la película extranjera",
        "ver la película con subtítulos en inglés",
        "los subtítulos tapan la imagen moverlos",
        "buscar una película con subtítulos en francés para practicar",
        "los subtítulos automáticos están mal corregirlos",
        "apagar los subtítulos distraen",
        "falta el archivo de subtítulos para este episodio",
        "poner los subtítulos siempre encendidos para los niños",
        "el timing de los subtítulos está dos segundos desfasado",
        "cambiar el color de los subtítulos a amarillo para mejor contraste",
        "ver la serie con subtítulos dobles para aprender idiomas",
        "verificar si el Blu-ray tiene subtítulos en alemán",
        "activar subtítulos en vivo para la videollamada",
        "el espectador con discapacidad auditiva necesita subtítulos cerrados",
        "subir un archivo de subtítulos personalizado al video",
        "los subtítulos desaparecen durante la película",
        "cambiar de versión doblada a versión subtitulada",
        "establecer idioma de subtítulos predeterminado para todos los videos",
        "la traducción de los subtítulos es incorrecta reportar",
        "habilitar subtítulos en la tablet de los niños para las caricaturas",
        "los subtítulos incrustados no se pueden desactivar",
        "configuración de retraso de subtítulos en el reproductor",
        "ver anime con subtítulos en japonés",
        "la función de subtítulos en vivo gasta la batería rápido",
        "buscar archivos de subtítulos en línea",
        "aumentar la opacidad del fondo de subtítulos para leer mejor",
        "prefiero subtítulos en vez de doblaje para películas extranjeras",
        "la opción para discapacidad auditiva agrega descripciones de sonido",
        "configurar subtítulos en el nuevo smart TV",
        "la codificación de subtítulos está mal los caracteres se ven raros",
        "bajar la velocidad del video los subtítulos van muy rápido",
        "noche de película con subtítulos para no despertar al bebé",
        "subtitulos en el reproductro de video",
        "leyenda en la peliucla",
        "traducicón de subtítulos",
        "subtítulos cerrdaos habilitados",
        "subtítulos de la pelícla extranjera",
    ],
})


print("Part C done: stomach, store, subtitles")
