#!/usr/bin/env python3
"""Batch task-003b: sheep, sheet-plastic, shirt, shirt-running (60 x 6 langs)."""

import csv
from pathlib import Path

icons_dir = Path("icons")


def write_csv(path, texts, label):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["text", "label"])
        for t in texts:
            w.writerow([t, label])


def build(icon, en, ru, de, ja, fr, es):
    for lang, data in [("en", en), ("ru", ru), ("de", de), ("ja", ja), ("fr", fr), ("es", es)]:
        deduped = list(dict.fromkeys(data))
        if len(deduped) != 60:
            raise ValueError(f"{icon} {lang} has {len(deduped)}, need 60")
        write_csv(icons_dir / icon / f"train_{lang}.csv", deduped, icon)
    print(f"  {icon}: EN=60 RU=60 DE=60 JA=60 FR=60 ES=60")


# ── sheep ─────────────────────────────────────────────────────────────────────
build("sheep",
en=[
    "sheep", "lamb", "wool", "ewe", "flock", "fleece",
    "farming", "yarn", "ram", "shepherd", "pasture", "shearing",
    "livestock", "merino", "mutton", "grazing", "herd", "barnyard",
    "agriculture field with grazing sheep",
    "sheep farming on rural pasture",
    "farm animal bleating in field",
    "ewe nursing lamb in spring",
    "mother ewe with newborn lamb",
    "sheep farming on mountain pasture",
    "farming sheep for wool production",
    "fluffy white sheep grazing on green pasture",
    "shepherd herding flock of sheep at sunset",
    "sheep shearing with electric clippers",
    "newborn lamb standing beside mother ewe",
    "black sheep among white flock",
    "wool sweater knitted from sheep fleece",
    "sheep in pen at agricultural fair",
    "merino sheep breed known for fine wool",
    "sheep crossing road sign in rural area",
    "shear the sheep before summer",
    "buy wool yarn for a knitting project",
    "count sheep to fall asleep tonight",
    "visit the sheep farm this weekend",
    "feed the lambs at the petting zoo",
    "knit a scarf from sheep wool",
    "take the kids to see lambs in spring",
    "order lamb chops from the butcher",
    "wash and card raw sheep wool",
    "register sheep for the county fair",
    "check on the pregnant ewe in the barn",
    "build a new fence for the sheep pen",
    "buy sheep feed from the farm supply store",
    "schedule the annual sheep vaccination",
    "plan the lamb roast for Easter dinner",
    "bring the flock down from the hillside",
    "dye wool yarn from the sheared fleece",
    "attend a sheep herding demonstration",
    "flufffy white sheep on green pasture",
    "sheperd herding flock of sheep",
    "newbron lamb beside mother ewe",
    "shep shearing with electric clippers",
    "sheering the sheep before sumer",
],
ru=[
    "овца", "ягнёнок", "шерсть", "овечка", "отара", "руно",
    "фермерство", "пряжа", "баран", "пастух", "пастбище", "стрижка овец",
    "скот", "меринос", "баранина", "выпас", "стадо", "скотный двор",
    "пастбище с пасущимися овцами",
    "овцеводство на сельском лугу",
    "сельскохозяйственное животное блеет в поле",
    "овца кормит ягнёнка весной",
    "овца-мать с новорождённым ягнёнком",
    "овцеводство на горном пастбище",
    "разведение овец для производства шерсти",
    "пушистая белая овца пасётся на зелёном лугу",
    "пастух гонит отару овец на закате",
    "стрижка овцы электрическими ножницами",
    "новорождённый ягнёнок рядом с матерью",
    "чёрная овца среди белой отары",
    "шерстяной свитер из овечьего руна",
    "овца в загоне на сельскохозяйственной выставке",
    "порода мериносовых овец с тонкой шерстью",
    "знак перехода овец в сельской местности",
    "остричь овцу перед летом",
    "купить шерстяную пряжу для вязания",
    "считать овец чтобы заснуть",
    "посетить овечью ферму в выходные",
    "покормить ягнят в контактном зоопарке",
    "связать шарф из овечьей шерсти",
    "свозить детей посмотреть ягнят весной",
    "заказать бараньи отбивные у мясника",
    "промыть и расчесать сырую овечью шерсть",
    "зарегистрировать овец на сельскую ярмарку",
    "проверить беременную овцу в хлеву",
    "построить новый забор для овечьего загона",
    "купить корм для овец в фермерском магазине",
    "запланировать ежегодную вакцинацию овец",
    "спланировать жаркое из баранины на Пасху",
    "согнать отару с холма",
    "покрасить пряжу из стриженого руна",
    "посетить показ пастушьих навыков",
    "пушситая белая овца на лугу",
    "пастух гонит отрау овец",
    "новроождённый ягнёнок рядом с матерью",
    "стрижка овцы электрческими ножницами",
    "остичь овцу перед летом",
],
de=[
    "Schaf", "Lamm", "Wolle", "Mutterschaf", "Herde", "Vlies",
    "Landwirtschaft", "Garn", "Widder", "Schäfer", "Weide", "Schur",
    "Vieh", "Merino", "Hammelfleisch", "Weiden", "Viehzucht", "Bauernhof",
    "Acker mit weidenden Schafen",
    "Schafzucht auf ländlicher Weide",
    "Nutztier blökt auf dem Feld",
    "Mutterschaf säugt Lamm im Frühling",
    "Mutterschaf mit neugeborenem Lamm",
    "Schafzucht auf Bergweide",
    "Schafe für Wollproduktion züchten",
    "flauschiges weißes Schaf auf grüner Weide",
    "Schäfer hütet Herde bei Sonnenuntergang",
    "Schafschur mit elektrischer Schermaschine",
    "neugeborenes Lamm neben Mutterschaf",
    "schwarzes Schaf in weißer Herde",
    "Wollpullover aus Schafvlies gestrickt",
    "Schaf im Gehege auf Landwirtschaftsmesse",
    "Merinoschaf für feine Wolle bekannt",
    "Schafe vor dem Sommer scheren",
    "Wollgarn für Strickprojekt kaufen",
    "Schafe zählen zum Einschlafen",
    "Schaffarm am Wochenende besuchen",
    "Lämmer im Streichelzoo füttern",
    "Schal aus Schafwolle stricken",
    "Kinder zum Lämmergucken mitnehmen",
    "Lammkoteletts beim Metzger bestellen",
    "rohe Schafwolle waschen und kämmen",
    "Schafe für die Kreismesse anmelden",
    "trächtige Mutterschaf im Stall kontrollieren",
    "neuen Zaun für Schafgehege bauen",
    "Schaffutter im Landhandel kaufen",
    "jährliche Impfung der Schafe planen",
    "Lammbraten fürs Osterfest planen",
    "Herde vom Hügel herunterbringen",
    "Garn aus geschorenem Vlies färben",
    "Schafhütevorführung besuchen",
    "Schafwolle zum Filzen vorbereiten",
    "Schafstall vor dem Winter reinigen",
    "flauschiges wießes Schaf auf Weide",
    "Schäfer hüted Herde bei Sonnenuntergang",
    "neugeborenens Lamm neben Mutterschaf",
    "Schafe vor dem Somer scheren",
    "Wollgarn für Strikprojekt kaufen",
],
ja=[
    "羊", "子羊", "ウール", "雌羊", "群れ", "羊毛",
    "牧畜", "毛糸", "雄羊", "羊飼い", "牧草地", "毛刈り",
    "家畜", "メリノ", "マトン", "放牧", "群", "牧場",
    "牧草地で草を食む羊",
    "田舎の牧場での羊の飼育",
    "野原で鳴く家畜の羊",
    "春に子羊に授乳する雌羊",
    "新生児の子羊と母羊",
    "山の牧場での羊の飼育",
    "ウール生産のために羊を飼う",
    "緑の牧草地でふわふわの白い羊が草を食む",
    "夕暮れに群れを追う羊飼い",
    "電動バリカンで羊の毛を刈る",
    "母羊のそばに立つ新生の子羊",
    "白い群れの中の黒い羊",
    "羊の毛で編んだウールセーター",
    "農業フェアの囲いの中の羊",
    "細いウールで知られるメリノ羊",
    "夏前に羊の毛を刈る",
    "編み物用のウール毛糸を買う",
    "今夜は羊を数えて眠る",
    "週末に牧羊場を訪れる",
    "ふれあい動物園で子羊に餌をやる",
    "羊のウールでマフラーを編む",
    "春に子供たちを子羊見学に連れていく",
    "肉屋でラムチョップを注文する",
    "生の羊毛を洗ってカーディングする",
    "郡のフェアに羊を登録する",
    "納屋で妊娠中の雌羊を確認する",
    "羊の囲い用に新しい柵を建てる",
    "農業用品店で羊の飼料を買う",
    "毎年の羊のワクチン接種を計画する",
    "イースターディナーのラムローストを計画する",
    "丘から群れを下ろす",
    "刈った羊毛から毛糸を染める",
    "羊追いのデモンストレーションに参加する",
    "フェルト用に羊毛を準備する",
    "冬前に羊小屋を掃除する",
    "ふわふわの白いひつじが牧草地にいる",
    "ひつじかいが群れを追う",
    "新生のこひつじが母羊のそばに立つ",
    "羊のけを刈る",
    "ウール毛糸をかう",
],
fr=[
    "mouton", "agneau", "laine", "brebis", "troupeau", "toison",
    "élevage", "fil", "bélier", "berger", "pâturage", "tonte",
    "bétail", "mérinos", "viande d'agneau", "paissance", "cheptel", "bergerie",
    "champ avec des moutons qui paissent",
    "élevage de moutons sur un pâturage rural",
    "animal de ferme qui bêle dans le champ",
    "brebis allaitant son agneau au printemps",
    "brebis avec son agneau nouveau-né",
    "élevage de moutons en montagne",
    "élever des moutons pour la laine",
    "mouton blanc et duveteux sur un pâturage vert",
    "berger guidant le troupeau au coucher du soleil",
    "tonte du mouton avec une tondeuse électrique",
    "agneau nouveau-né à côté de sa mère",
    "mouton noir parmi le troupeau blanc",
    "pull en laine tricoté avec de la toison de mouton",
    "mouton dans l'enclos à la foire agricole",
    "mouton mérinos connu pour sa laine fine",
    "tondre les moutons avant l'été",
    "acheter du fil de laine pour un projet de tricot",
    "compter les moutons pour s'endormir",
    "visiter la ferme de moutons ce week-end",
    "nourrir les agneaux au zoo de contact",
    "tricoter une écharpe en laine de mouton",
    "emmener les enfants voir les agneaux au printemps",
    "commander des côtelettes d'agneau chez le boucher",
    "laver et carder la laine brute de mouton",
    "inscrire les moutons à la foire du comté",
    "vérifier la brebis gestante dans l'étable",
    "construire une nouvelle clôture pour l'enclos",
    "acheter de la nourriture pour moutons à la coopérative",
    "planifier la vaccination annuelle des moutons",
    "préparer le gigot d'agneau pour Pâques",
    "ramener le troupeau de la colline",
    "teindre du fil à partir de la toison tondue",
    "assister à une démonstration de conduite de troupeau",
    "mouton blanc et duvteux sur un pâturage",
    "berger guidant le troupeau au couchre du soleil",
    "agneau nouveau-né à coté de sa mère",
    "tondre les moutons avnt l'été",
    "acheter du fil de laine pour un projet de tricto",
],
es=[
    "oveja", "cordero", "lana", "oveja hembra", "rebaño", "vellón",
    "ganadería", "hilo", "carnero", "pastor", "pastizal", "esquila",
    "ganado", "merino", "carne de cordero", "pastoreo", "manada", "corral",
    "campo con ovejas pastando",
    "ganadería ovina en pastizal rural",
    "animal de granja balando en el campo",
    "oveja amamantando cordero en primavera",
    "oveja madre con cordero recién nacido",
    "ganadería ovina en pastizal de montaña",
    "criar ovejas para producir lana",
    "oveja blanca y esponjosa pastando en prado verde",
    "pastor guiando el rebaño al atardecer",
    "esquila de oveja con máquina eléctrica",
    "cordero recién nacido junto a su madre",
    "oveja negra entre el rebaño blanco",
    "suéter de lana tejido con vellón de oveja",
    "oveja en corral en feria agrícola",
    "oveja merino conocida por su lana fina",
    "esquilar las ovejas antes del verano",
    "comprar hilo de lana para un proyecto de tejido",
    "contar ovejas para dormirse",
    "visitar la granja de ovejas este fin de semana",
    "dar de comer a los corderos en el zoológico",
    "tejer una bufanda con lana de oveja",
    "llevar a los niños a ver corderos en primavera",
    "pedir chuletas de cordero al carnicero",
    "lavar y cardar la lana cruda de oveja",
    "inscribir ovejas para la feria del condado",
    "revisar la oveja preñada en el establo",
    "construir una nueva cerca para el corral",
    "comprar alimento para ovejas en la tienda agrícola",
    "planificar la vacunación anual de las ovejas",
    "planificar el asado de cordero para Pascua",
    "bajar el rebaño de la colina",
    "teñir hilo de la lana esquilada",
    "asistir a una demostración de pastoreo",
    "oveja blanca y esponjsa pastando",
    "pastor guiando el rebaño al atardcer",
    "cordero recién nacido juntoa su madre",
    "esquilar las ovjas antes del verano",
    "comprar hilo de lana para un proyeto de tejido",
],
)

# ── sheet-plastic ─────────────────────────────────────────────────────────────
build("sheet-plastic",
en=[
    "plastic", "plastic wrap", "tarp", "tarpaulin", "waterproof",
    "shrink wrap", "cling film", "polyethylene", "plastic sheet", "sheeting",
    "film", "cover", "liner", "wrap", "drop cloth",
    "protective film", "vapor barrier", "plastic cover",
    "plastic wrap covering food bowl",
    "plastic wrap sealing leftovers",
    "protect furniture with plastic sheet",
    "protect floor from paint splatter",
    "blue tarp covering woodpile outside",
    "tarp over camping equipment",
    "tarpaulin covering boat in winter",
    "tarpaulin on construction site",
    "waterproof plastic tarp on roof",
    "waterproof sheet for outdoor storage",
    "greenhouse plastic film on metal frame",
    "plastic sheet lining garden pond",
    "protective plastic sheeting on window",
    "heavy-duty tarp for landscaping project",
    "buy plastic wrap at the grocery store",
    "wrap leftovers in cling film before refrigerating",
    "cover the pool with a tarp for winter",
    "lay down a drop cloth before painting the room",
    "shrink wrap the pallet for shipping",
    "buy a new tarp to cover the firewood",
    "wrap the furniture in plastic for the move",
    "cover the garden bed with plastic sheeting",
    "line the raised bed with plastic liner",
    "put a vapor barrier in the crawl space",
    "stretch cling film over the salad bowl",
    "buy polyethylene sheeting for the greenhouse",
    "tape plastic sheet over the broken window",
    "cover the car with a waterproof tarp",
    "pack fragile items with shrink wrap",
    "lay plastic under the gravel path",
    "replace the worn tarp on the shed roof",
    "cler plastic sheet protecting furniture",
    "blue tarpualin covering equipment",
    "plasirc wrap sealing food container",
    "waterproff tarp over camping tent",
    "buy plastc wrap at the store",
],
ru=[
    "пластик", "пищевая плёнка", "тент", "брезент", "водонепроницаемый",
    "термоусадочная плёнка", "стрейч-плёнка", "полиэтилен", "пластиковый лист", "плёнка",
    "покрытие", "подкладка", "укрывной материал", "обёртка", "защитная плёнка",
    "паробарьер", "пластиковое покрытие", "плёночный материал",
    "пищевая плёнка накрывает миску с едой",
    "пищевая плёнка запечатывает остатки еды",
    "защитить мебель пластиковым листом",
    "защитить пол от брызг краски",
    "синий тент накрывает поленницу на улице",
    "тент над туристическим снаряжением",
    "брезент накрывает лодку зимой",
    "брезент на строительной площадке",
    "водонепроницаемый пластиковый тент на крыше",
    "водонепроницаемый лист для хранения на улице",
    "плёнка теплицы на металлическом каркасе",
    "пластиковый лист выстилает садовый пруд",
    "защитная пластиковая плёнка на окне",
    "прочный брезент для ландшафтного проекта",
    "купить пищевую плёнку в продуктовом магазине",
    "обернуть остатки еды в плёнку перед холодильником",
    "накрыть бассейн тентом на зиму",
    "расстелить защитную плёнку перед покраской комнаты",
    "упаковать паллет в термоусадочную плёнку",
    "купить новый тент для дров",
    "обернуть мебель в пластик для переезда",
    "укрыть садовую грядку пластиковой плёнкой",
    "выстелить приподнятую грядку пластиковой подкладкой",
    "установить паробарьер в подполье",
    "натянуть стрейч-плёнку на миску с салатом",
    "купить полиэтиленовую плёнку для теплицы",
    "заклеить пластиком разбитое окно",
    "накрыть машину водонепроницаемым тентом",
    "упаковать хрупкие вещи в термоусадочную плёнку",
    "постелить пластик под гравийную дорожку",
    "заменить износившийся тент на крыше сарая",
    "прозрачный пластикоый лист защищает мебель",
    "синий брезент накрывает оборудавние",
    "пищевая плёнак запечатывает контейнер",
    "водонепроницаемй тент над палаткой",
    "купить пластковую плёнку в магазине",
],
de=[
    "Plastik", "Frischhaltefolie", "Plane", "Abdeckplane", "wasserdicht",
    "Schrumpffolie", "Klarsichtfolie", "Polyethylen", "Plastikfolie", "Folie",
    "Film", "Abdeckung", "Auskleidung", "Wickelfolie", "Abdecktuch",
    "Schutzfolie", "Dampfsperre", "Plastikabdeckung",
    "Frischhaltefolie über Essensschüssel",
    "Frischhaltefolie versiegelt Reste",
    "Möbel mit Plastikfolie schützen",
    "Boden vor Farbspritzern schützen",
    "blaue Plane deckt Holzstapel ab",
    "Plane über Campingausrüstung",
    "Abdeckplane auf Boot im Winter",
    "Plane auf Baustelle",
    "wasserdichte Plastikplane auf Dach",
    "wasserdichte Folie für Außenlagerung",
    "Gewächshausfolie auf Metallrahmen",
    "Plastikfolie kleidet Gartenteich aus",
    "Schutzfolie auf Fenster",
    "robuste Plane für Landschaftsprojekt",
    "Frischhaltefolie im Supermarkt kaufen",
    "Reste in Klarsichtfolie wickeln vor dem Kühlen",
    "Pool mit Plane für den Winter abdecken",
    "Abdecktuch vor dem Streichen auslegen",
    "Palette mit Schrumpffolie einwickeln",
    "neue Plane für Brennholz kaufen",
    "Möbel für Umzug in Plastik einwickeln",
    "Gartenbeet mit Plastikfolie abdecken",
    "Hochbeet mit Plastikauskleidung auskleiden",
    "Dampfsperre im Kriechkeller einbauen",
    "Klarsichtfolie über Salatschüssel spannen",
    "Polyethylenfolie für Gewächshaus kaufen",
    "Plastikfolie über kaputtes Fenster kleben",
    "Auto mit wasserdichter Plane abdecken",
    "zerbrechliche Sachen mit Schrumpffolie einpacken",
    "Plastik unter Kiesweg verlegen",
    "abgenutzte Plane auf Schuppendach ersetzen",
    "Frishhaltefolie über Essensschüssel",
    "blaue Plne deckt Holzstapel ab",
    "wasserdichter Plastikplane auf Dach",
    "Frischhaltefoile im Supermarkt kaufen",
    "Möbel für Umzg in Plastik einwickeln",
],
ja=[
    "プラスチック", "ラップ", "タープ", "防水シート", "防水",
    "シュリンクラップ", "食品用ラップ", "ポリエチレン", "プラスチックシート", "シート",
    "フィルム", "カバー", "ライナー", "包装", "養生シート",
    "保護フィルム", "防湿シート", "プラスチックカバー",
    "食品ラップでボウルを覆う",
    "残り物をラップで密封する",
    "プラスチックシートで家具を保護する",
    "ペンキの飛び散りから床を守る",
    "青いタープで屋外の薪を覆う",
    "キャンプ用品の上にタープをかける",
    "冬にボートを防水シートで覆う",
    "建設現場の防水シート",
    "屋根の防水プラスチックタープ",
    "屋外保管用の防水シート",
    "金属フレームの温室用プラスチックフィルム",
    "庭の池にプラスチックシートを敷く",
    "窓の保護プラスチックシート",
    "造園プロジェクト用の丈夫なタープ",
    "スーパーで食品用ラップを買う",
    "冷蔵庫に入れる前に残り物をラップで包む",
    "冬にプールをタープで覆う",
    "部屋を塗る前に養生シートを敷く",
    "出荷用パレットをシュリンクラップで包む",
    "薪用の新しいタープを買う",
    "引っ越しのために家具をプラスチックで包む",
    "花壇をプラスチックシートで覆う",
    "レイズドベッドにプラスチックライナーを敷く",
    "床下に防湿シートを設置する",
    "サラダボウルにラップをかける",
    "温室用のポリエチレンシートを買う",
    "割れた窓にプラスチックシートを貼る",
    "車を防水タープで覆う",
    "壊れやすい物をシュリンクラップで包む",
    "砂利道の下にプラスチックを敷く",
    "小屋の屋根の傷んだタープを交換する",
    "食品ラップでぼうるを覆う",
    "青いたーぷで薪を覆う",
    "プラスチクシートで家具を守る",
    "温室用のぽりえちれんシートを買う",
    "ラップでのこりものを包む",
],
fr=[
    "plastique", "film alimentaire", "bâche", "bâche de protection", "imperméable",
    "film rétractable", "film étirable", "polyéthylène", "feuille de plastique", "film",
    "couverture", "revêtement", "doublure", "emballage", "toile de protection",
    "film protecteur", "pare-vapeur", "housse plastique",
    "film alimentaire sur un bol de nourriture",
    "film alimentaire scellant les restes",
    "protéger les meubles avec une feuille de plastique",
    "protéger le sol des éclaboussures de peinture",
    "bâche bleue couvrant le tas de bois",
    "bâche sur le matériel de camping",
    "bâche couvrant le bateau en hiver",
    "bâche sur le chantier de construction",
    "bâche plastique imperméable sur le toit",
    "feuille imperméable pour stockage extérieur",
    "film plastique de serre sur cadre métallique",
    "feuille de plastique tapissant le bassin du jardin",
    "film protecteur sur la fenêtre",
    "bâche robuste pour projet paysager",
    "acheter du film alimentaire au supermarché",
    "emballer les restes dans du film avant de réfrigérer",
    "couvrir la piscine avec une bâche pour l'hiver",
    "étaler la toile de protection avant de peindre",
    "emballer la palette avec du film rétractable",
    "acheter une nouvelle bâche pour le bois de chauffage",
    "emballer les meubles dans du plastique pour le déménagement",
    "couvrir le massif de jardin avec du film plastique",
    "tapisser le bac surélevé avec une doublure plastique",
    "installer un pare-vapeur dans le vide sanitaire",
    "étirer du film sur le saladier",
    "acheter du polyéthylène pour la serre",
    "coller du plastique sur la fenêtre cassée",
    "couvrir la voiture avec une bâche imperméable",
    "emballer les objets fragiles avec du film rétractable",
    "poser du plastique sous le chemin de gravier",
    "remplacer la bâche usée sur le toit de l'abri",
    "film alimentare sur un bol de nourriture",
    "bâche bleu couvrant le tas de bois",
    "protéger les muebles avec du plastique",
    "acheter du film alimentaire au supermarhcé",
    "emballer les meuble dans du plastique",
],
es=[
    "plástico", "film plástico", "lona", "lona protectora", "impermeable",
    "film retráctil", "film adherente", "polietileno", "lámina de plástico", "lámina",
    "película", "cubierta", "revestimiento", "envoltorio", "tela protectora",
    "película protectora", "barrera de vapor", "funda plástica",
    "film plástico cubriendo un bol de comida",
    "film plástico sellando sobras",
    "proteger muebles con lámina de plástico",
    "proteger el suelo de salpicaduras de pintura",
    "lona azul cubriendo la pila de leña",
    "lona sobre el equipo de camping",
    "lona cubriendo el barco en invierno",
    "lona en el sitio de construcción",
    "lona plástica impermeable en el techo",
    "lámina impermeable para almacenamiento exterior",
    "película plástica de invernadero en marco metálico",
    "lámina de plástico en el estanque del jardín",
    "película protectora en la ventana",
    "lona resistente para proyecto de jardinería",
    "comprar film plástico en el supermercado",
    "envolver sobras en film antes de refrigerar",
    "cubrir la piscina con lona para el invierno",
    "extender la tela protectora antes de pintar",
    "envolver el palé con film retráctil",
    "comprar una lona nueva para la leña",
    "envolver los muebles en plástico para la mudanza",
    "cubrir el cantero con lámina de plástico",
    "forrar el cantero elevado con revestimiento plástico",
    "instalar barrera de vapor en el sótano",
    "estirar film adherente sobre la ensaladera",
    "comprar lámina de polietileno para el invernadero",
    "pegar plástico sobre la ventana rota",
    "cubrir el auto con lona impermeable",
    "embalar objetos frágiles con film retráctil",
    "poner plástico bajo el camino de grava",
    "reemplazar la lona desgastada del techo del cobertizo",
    "film plástico cubrendo un bol de comida",
    "lona azul cubrendo la pila de leña",
    "proteger muebles con lámina de plásitco",
    "comprar film plástico en el supermerado",
    "envolver los mubles en plástico",
],
)

# ── shirt ─────────────────────────────────────────────────────────────────────
build("shirt",
en=[
    "garment", "shirt", "short sleeve", "t-shirt", "tshirt",
    "polo", "blouse", "button-down", "dress shirt", "clothing",
    "top", "collar", "henley", "flannel", "oxford",
    "tee", "undershirt", "tunic",
    "folded clothing on store shelf",
    "cotton garment folded in drawer",
    "casual shirt for everyday wear",
    "button-down shirt for smart casual",
    "short sleeve casual top",
    "t-shirt with logo print on chest",
    "plain white t-shirt basic wardrobe",
    "crew neck tshirt in solid color",
    "graphic tee with print on front",
    "polo shirt with collar and buttons",
    "dress shirt with long sleeves and cuffs",
    "vintage band t-shirt from concert",
    "sports jersey shirt for team",
    "linen shirt for beach vacation",
    "shirt folded and packaged for shipping",
    "custom embroidered company shirt",
    "children's school uniform shirt",
    "iron the dress shirt for the meeting",
    "buy a new polo shirt for the weekend",
    "fold the clean shirts and put them away",
    "hang the dress shirt in the closet",
    "pick up shirts from the dry cleaner",
    "sew a missing button on the shirt",
    "order custom t-shirts for the event",
    "pack three shirts for the business trip",
    "return the shirt that doesn't fit",
    "try on the flannel shirt at the store",
    "wash the white shirts separately",
    "donate old shirts to charity",
    "hem the shirt sleeves shorter",
    "remove the stain from the collar",
    "buy a linen shirt for the summer holiday",
    "choose a shirt for the job interview",
    "compare shirt prices online",
    "monogram the dress shirt pocket",
    "plain white t-shrit hanging on hanger",
    "graphci tee with print on front",
    "polo shrit with collar and buttons",
    "vinatge band t-shirt from concert",
    "irn the dress shirt for the meeting",
],
ru=[
    "предмет одежды", "рубашка", "короткий рукав", "футболка", "поло",
    "блузка", "сорочка", "рубашка на пуговицах", "классическая рубашка", "одежда",
    "топ", "воротник", "хенли", "фланелевая рубашка", "оксфордская рубашка",
    "майка", "нательная рубашка", "туника",
    "сложенная одежда на полке магазина",
    "хлопковая вещь сложена в ящике",
    "повседневная рубашка для ежедневной носки",
    "рубашка на пуговицах для стиля смарт-кэжуал",
    "повседневный топ с коротким рукавом",
    "футболка с принтом логотипа на груди",
    "простая белая футболка базовый гардероб",
    "футболка с круглым вырезом однотонная",
    "принтованная футболка с рисунком спереди",
    "поло с воротником и пуговицами",
    "классическая рубашка с длинными рукавами и манжетами",
    "винтажная концертная футболка",
    "спортивная игровая майка команды",
    "льняная рубашка для пляжного отдыха",
    "рубашка сложена и упакована для отправки",
    "корпоративная рубашка с вышивкой на заказ",
    "школьная форменная рубашка",
    "погладить рубашку для совещания",
    "купить новую поло на выходные",
    "сложить чистые рубашки и убрать их",
    "повесить рубашку в шкаф",
    "забрать рубашки из химчистки",
    "пришить недостающую пуговицу на рубашке",
    "заказать именные футболки на мероприятие",
    "собрать три рубашки для командировки",
    "вернуть рубашку которая не подошла",
    "примерить фланелевую рубашку в магазине",
    "стирать белые рубашки отдельно",
    "отдать старые рубашки на благотворительность",
    "укоротить рукава рубашки",
    "вывести пятно с воротника",
    "купить льняную рубашку на летний отпуск",
    "выбрать рубашку для собеседования",
    "сравнить цены на рубашки онлайн",
    "вышить монограмму на кармане рубашки",
    "простая белая фукболка на вешалке",
    "принтованная фулболка с рисунком",
    "поол с воротником и пуговицами",
    "винтажная кончертная футболка",
    "поглдить рубашку для совещания",
],
de=[
    "Kleidungsstück", "Hemd", "Kurzarm", "T-Shirt", "Tshirt",
    "Polo", "Bluse", "Knopfhemd", "Oberhemd", "Kleidung",
    "Oberteil", "Kragen", "Henley", "Flanellhemd", "Oxfordhemd",
    "Tee", "Unterhemd", "Tunika",
    "gefaltete Kleidung im Ladenregal",
    "Baumwollkleidungsstück in Schublade gefaltet",
    "Freizeithemd für den Alltag",
    "Hemd mit Knöpfen für Smart Casual",
    "kurzärmeliges lässiges Oberteil",
    "T-Shirt mit Logodruck auf der Brust",
    "einfaches weißes T-Shirt im Grundgarderobe",
    "Rundhals-T-Shirt in Uni-Farbe",
    "bedrucktes T-Shirt mit Motiv vorne",
    "Polohemd mit Kragen und Knöpfen",
    "Oberhemd mit langen Ärmeln und Manschetten",
    "Vintage-Band-T-Shirt vom Konzert",
    "Sporttrikot für die Mannschaft",
    "Leinenhemd für den Strandurlaub",
    "Hemd gefaltet und verpackt zum Versand",
    "besticktes Firmenhemd nach Maß",
    "Schuluniformhemd für Kinder",
    "Oberhemd für das Meeting bügeln",
    "neues Polohemd fürs Wochenende kaufen",
    "saubere Hemden falten und wegräumen",
    "Oberhemd in den Schrank hängen",
    "Hemden von der Reinigung abholen",
    "fehlenden Knopf am Hemd annähen",
    "individuelle T-Shirts für Veranstaltung bestellen",
    "drei Hemden für die Geschäftsreise einpacken",
    "Hemd zurückgeben das nicht passt",
    "Flanellhemd im Laden anprobieren",
    "weiße Hemden getrennt waschen",
    "alte Hemden an Wohltätigkeit spenden",
    "Hemdärmel kürzen lassen",
    "Fleck am Kragen entfernen",
    "Leinenhemd für den Sommerurlaub kaufen",
    "Hemd für das Vorstellungsgespräch wählen",
    "Hemdpreise online vergleichen",
    "einfaches weißes T-Shrit auf Bügel",
    "bedurcktes T-Shirt mit Motiv vorne",
    "Polohmed mit Kragen und Knöpfen",
    "Obehemd für das Meeting bügeln",
    "Flanellhmed im Laden anprobieren",
],
ja=[
    "衣類", "シャツ", "半袖", "Tシャツ", "ポロシャツ",
    "ブラウス", "ボタンダウン", "ドレスシャツ", "服",
    "トップス", "襟", "ヘンリーネック", "フランネルシャツ", "オックスフォードシャツ",
    "ティーシャツ", "肌着", "チュニック",
    "店の棚に畳まれた服",
    "引き出しに畳まれた綿の衣類",
    "普段着のカジュアルシャツ",
    "スマートカジュアル用のボタンダウンシャツ",
    "半袖のカジュアルトップス",
    "胸にロゴプリントのTシャツ",
    "基本のワードローブの白い無地Tシャツ",
    "無地のクルーネックTシャツ",
    "前面にプリントのグラフィックTシャツ",
    "襟とボタン付きのポロシャツ",
    "長袖カフス付きのドレスシャツ",
    "コンサートのヴィンテージバンドTシャツ",
    "チームのスポーツジャージシャツ",
    "ビーチ休暇用のリネンシャツ",
    "畳んで梱包された出荷用シャツ",
    "オーダー刺繍入り会社シャツ",
    "子供の学校制服シャツ",
    "会議のためにドレスシャツにアイロンをかける",
    "週末用に新しいポロシャツを買う",
    "洗ったシャツを畳んでしまう",
    "ドレスシャツをクローゼットにかける",
    "クリーニング屋からシャツを引き取る",
    "シャツの取れたボタンを縫い付ける",
    "イベント用のオリジナルTシャツを注文する",
    "出張用にシャツを3枚詰める",
    "サイズが合わないシャツを返品する",
    "店でフランネルシャツを試着する",
    "白いシャツは分けて洗う",
    "古いシャツを寄付する",
    "シャツの袖を短くお直しする",
    "襟のシミを落とす",
    "夏休み用にリネンシャツを買う",
    "面接用のシャツを選ぶ",
    "オンラインでシャツの値段を比較する",
    "白いむじTシャツをかける",
    "ぽろシャツを買う",
    "ドレスしゃつにアイロンをかける",
    "シャツのぼたんを縫い付ける",
    "フランネルしゃつを試着する",
],
fr=[
    "vêtement", "chemise", "manche courte", "t-shirt", "polo",
    "blouse", "chemise boutonnée", "chemise habillée", "habillement",
    "haut", "col", "henley", "chemise en flanelle", "chemise oxford",
    "tee-shirt", "maillot de corps", "tunique",
    "vêtement plié sur l'étagère du magasin",
    "vêtement en coton plié dans le tiroir",
    "chemise décontractée pour tous les jours",
    "chemise boutonnée pour un look smart casual",
    "haut décontracté à manches courtes",
    "t-shirt avec logo imprimé sur la poitrine",
    "t-shirt blanc basique de la garde-robe",
    "t-shirt col rond uni",
    "t-shirt graphique avec motif devant",
    "polo avec col et boutons",
    "chemise habillée à manches longues et poignets",
    "t-shirt vintage de concert",
    "maillot de sport pour l'équipe",
    "chemise en lin pour les vacances à la plage",
    "chemise pliée et emballée pour l'expédition",
    "chemise d'entreprise brodée sur mesure",
    "chemise d'uniforme scolaire",
    "repasser la chemise habillée pour la réunion",
    "acheter un nouveau polo pour le week-end",
    "plier les chemises propres et les ranger",
    "accrocher la chemise habillée dans le placard",
    "récupérer les chemises au pressing",
    "recoudre un bouton manquant sur la chemise",
    "commander des t-shirts personnalisés pour l'événement",
    "préparer trois chemises pour le voyage d'affaires",
    "retourner la chemise qui ne va pas",
    "essayer la chemise en flanelle en magasin",
    "laver les chemises blanches séparément",
    "donner les vieilles chemises à une association",
    "raccourcir les manches de la chemise",
    "enlever la tache sur le col",
    "acheter une chemise en lin pour l'été",
    "choisir une chemise pour l'entretien d'embauche",
    "t-shrit blanc basique de la garde-robe",
    "chemise habillé à manches longues",
    "repassr la chemise pour la réunion",
    "acheter un nouvau polo pour le week-end",
    "plier les chemses propres et ranger",
],
es=[
    "prenda", "camisa", "manga corta", "camiseta", "polo",
    "blusa", "camisa abotonada", "camisa de vestir", "ropa",
    "top", "cuello", "henley", "camisa de franela", "camisa oxford",
    "remera", "camiseta interior", "túnica",
    "ropa doblada en el estante de la tienda",
    "prenda de algodón doblada en el cajón",
    "camisa casual para el día a día",
    "camisa abotonada para look smart casual",
    "top casual de manga corta",
    "camiseta con logo estampado en el pecho",
    "camiseta blanca básica del armario",
    "camiseta cuello redondo de color liso",
    "camiseta gráfica con diseño al frente",
    "polo con cuello y botones",
    "camisa de vestir con mangas largas y puños",
    "camiseta vintage de concierto de banda",
    "camiseta deportiva de equipo",
    "camisa de lino para vacaciones de playa",
    "camisa doblada y empacada para envío",
    "camisa de empresa bordada a medida",
    "camisa de uniforme escolar para niños",
    "planchar la camisa de vestir para la reunión",
    "comprar un polo nuevo para el fin de semana",
    "doblar las camisas limpias y guardarlas",
    "colgar la camisa de vestir en el armario",
    "recoger las camisas de la tintorería",
    "coser un botón que falta en la camisa",
    "encargar camisetas personalizadas para el evento",
    "empacar tres camisas para el viaje de negocios",
    "devolver la camisa que no queda bien",
    "probarse la camisa de franela en la tienda",
    "lavar las camisas blancas por separado",
    "donar camisas viejas a la caridad",
    "acortar las mangas de la camisa",
    "quitar la mancha del cuello",
    "comprar una camisa de lino para el verano",
    "elegir una camisa para la entrevista de trabajo",
    "comparar precios de camisas en línea",
    "camiseta blanca básica del armrio",
    "polo con cuello y botonees",
    "planchar la cmaisa de vestir",
    "comprar un plo nuevo para el fin de semana",
    "doblar las camiss limpias y guardarlas",
],
)

# ── shirt-running ─────────────────────────────────────────────────────────────
build("shirt-running",
en=[
    "athletics", "running", "running shirt", "sash", "tank top",
    "jersey", "workout shirt", "sport shirt", "race bib", "singlet",
    "activewear", "marathon shirt", "track shirt", "training top", "gym shirt",
    "compression shirt", "moisture-wicking", "athletic wear",
    "athletics running shirt with number",
    "athletics jersey for track race",
    "running shirt breathable for exercise",
    "running shirt with brand logo",
    "sash across running shirt at finish",
    "numbered sash worn in race",
    "shirt worn in track and field",
    "running shirt with reflective stripe",
    "tank top worn for gym workout",
    "lightweight running vest shirt for marathon",
    "numbered race bib shirt for competition",
    "moisture-wicking athletic running shirt",
    "tank top running shirt in bright color",
    "reflective running shirt for night runs",
    "triathlon running shirt with aerodynamic fit",
    "team running shirt with sponsor logo",
    "compression running shirt for performance",
    "throwaway running shirt for cold start",
    "buy a new running shirt for the half marathon",
    "pack the workout shirt for the gym bag",
    "order matching team jerseys for the relay",
    "replace the worn-out running tank top",
    "choose a lightweight shirt for the summer race",
    "wash the running shirt after the 10K",
    "lay out the race shirt the night before",
    "try on the new athletic top at the store",
    "buy moisture-wicking shirts for training",
    "return the running shirt that's too small",
    "donate the old marathon finisher shirts",
    "hang the race singlet to air dry",
    "compare running shirt fabrics online",
    "pick up the team jersey from the coach",
    "break in the new workout shirt at practice",
    "embroider the club name on the training top",
    "lightwieght running shirt for marathon",
    "nubmered race bib shirt for competition",
    "moisutre-wicking athletic running shirt",
    "reflcetive running shirt for night runs",
    "buy a new runing shirt for the race",
],
ru=[
    "лёгкая атлетика", "бег", "беговая майка", "лента финиша", "топ без рукавов",
    "джерси", "тренировочная майка", "спортивная майка", "стартовый номер", "синглет",
    "спортивная одежда", "марафонская майка", "трековая майка", "тренировочный топ", "майка для зала",
    "компрессионная майка", "влагоотводящая ткань", "спортивная форма",
    "беговая майка с номером в лёгкой атлетике",
    "майка для забега на треке",
    "дышащая беговая майка для тренировок",
    "беговая майка с логотипом бренда",
    "лента через беговую майку на финише",
    "пронумерованная лента в гонке",
    "майка для трека и поля",
    "беговая майка с отражающей полосой",
    "топ без рукавов для тренировки в зале",
    "лёгкая беговая майка для марафона",
    "майка с пронумерованным стартовым номером",
    "влагоотводящая атлетическая беговая майка",
    "топ без рукавов для бега ярких цветов",
    "светоотражающая беговая майка для ночных пробежек",
    "беговая майка для триатлона с аэродинамическим кроем",
    "командная беговая майка с логотипом спонсора",
    "компрессионная беговая майка для производительности",
    "одноразовая беговая майка для старта в холод",
    "купить новую беговую майку для полумарафона",
    "положить тренировочную майку в спортивную сумку",
    "заказать одинаковые командные джерси для эстафеты",
    "заменить износившийся беговой топ",
    "выбрать лёгкую майку для летнего забега",
    "постирать беговую майку после десятки",
    "разложить беговую майку вечером перед гонкой",
    "примерить новый спортивный топ в магазине",
    "купить влагоотводящие майки для тренировок",
    "вернуть беговую майку которая мала",
    "отдать старые финишерские майки",
    "повесить беговой синглет на просушку",
    "сравнить ткани беговых маек онлайн",
    "забрать командную майку у тренера",
    "разносить новую тренировочную майку на практике",
    "вышить название клуба на тренировочном топе",
    "лёгкая бегвоая майка для марафона",
    "майка с пронумерованым стартовым номером",
    "влагоотводяшая беговая майка",
    "светоотражющая майка для ночных пробежек",
    "купить новую бговую майку для гонки",
],
de=[
    "Leichtathletik", "Laufen", "Laufshirt", "Schärpe", "Tanktop",
    "Trikot", "Trainingsshirt", "Sportshirt", "Startnummer", "Singlet",
    "Sportbekleidung", "Marathonshirt", "Bahnshirt", "Trainingstop", "Gym-Shirt",
    "Kompressionsshirt", "feuchtigkeitsableitend", "Sportkleidung",
    "Leichtathletik-Laufshirt mit Nummer",
    "Trikot für Bahnrennen",
    "atmungsaktives Laufshirt für Training",
    "Laufshirt mit Markenlogo",
    "Schärpe über Laufshirt im Ziel",
    "nummerierte Schärpe beim Rennen",
    "Shirt für Leichtathletik",
    "Laufshirt mit reflektierendem Streifen",
    "Tanktop für Gym-Training",
    "leichtes Laufshirt für Marathon",
    "Shirt mit Startnummer für Wettkampf",
    "feuchtigkeitsableitendes Sportlaufshirt",
    "Tanktop-Laufshirt in leuchtender Farbe",
    "reflektierendes Laufshirt für Nachtläufe",
    "Triathlon-Laufshirt mit aerodynamischer Passform",
    "Team-Laufshirt mit Sponsorenlogo",
    "Kompressions-Laufshirt für Leistung",
    "Einweg-Laufshirt für kalten Start",
    "neues Laufshirt für Halbmarathon kaufen",
    "Trainingsshirt in die Sporttasche packen",
    "einheitliche Teamtrikots für Staffel bestellen",
    "abgenutztes Lauf-Tanktop ersetzen",
    "leichtes Shirt für Sommerlauf wählen",
    "Laufshirt nach dem 10-km-Lauf waschen",
    "Rennshirt am Vorabend bereitlegen",
    "neues Sporttop im Laden anprobieren",
    "feuchtigkeitsableitende Shirts fürs Training kaufen",
    "zu kleines Laufshirt zurückgeben",
    "alte Marathon-Finisher-Shirts spenden",
    "Renn-Singlet zum Lufttrocknen aufhängen",
    "Laufshirt-Stoffe online vergleichen",
    "Teamtrikot vom Trainer abholen",
    "neues Trainingsshirt im Training einlaufen",
    "Vereinsnamen auf Trainingstop sticken",
    "leichtes Laufshrit für Marathon",
    "Shirt mit Startnumer für Wettkampf",
    "feuchtigkeitsableitedes Sportlaufshirt",
    "reflektirende Laufshirt für Nachtläufe",
    "neues Laufshirt für Halbmarthon kaufen",
],
ja=[
    "陸上競技", "ランニング", "ランニングシャツ", "たすき", "タンクトップ",
    "ジャージ", "ワークアウトシャツ", "スポーツシャツ", "ゼッケン", "シングレット",
    "アクティブウェア", "マラソンシャツ", "トラックシャツ", "トレーニングトップ", "ジムシャツ",
    "コンプレッションシャツ", "吸汗速乾", "スポーツウェア",
    "ナンバー付きの陸上ランニングシャツ",
    "トラックレース用のジャージ",
    "通気性のある運動用ランニングシャツ",
    "ブランドロゴ入りランニングシャツ",
    "ゴール時にランニングシャツにかかるたすき",
    "レースで着ける番号付きたすき",
    "トラック競技用のシャツ",
    "反射ストライプ付きランニングシャツ",
    "ジムトレーニング用タンクトップ",
    "マラソン用の軽量ランニングシャツ",
    "競技用のゼッケン付きシャツ",
    "吸汗速乾のアスレチックランニングシャツ",
    "明るい色のタンクトップランニングシャツ",
    "夜間ランニング用の反射シャツ",
    "エアロダイナミクスフィットのトライアスロン用シャツ",
    "スポンサーロゴ入りチームランニングシャツ",
    "パフォーマンス用コンプレッションシャツ",
    "寒い朝用の使い捨てランニングシャツ",
    "ハーフマラソン用の新しいランニングシャツを買う",
    "ジムバッグにトレーニングシャツを入れる",
    "リレー用のお揃いチームジャージを注文する",
    "古くなったランニングタンクトップを買い替える",
    "夏のレース用に軽量シャツを選ぶ",
    "10Kの後にランニングシャツを洗う",
    "レース前夜にシャツを準備する",
    "店で新しいスポーツトップを試着する",
    "トレーニング用の吸汗速乾シャツを買う",
    "小さすぎるランニングシャツを返品する",
    "古い完走記念シャツを寄付する",
    "レースシングレットを干して乾かす",
    "ランニングシャツの生地をオンラインで比較する",
    "コーチからチームジャージを受け取る",
    "マラソン用の軽量ランニンングシャツ",
    "競技用のぜっけん付きシャツ",
    "吸汗速乾のらんにんぐシャツ",
    "反射すとらいぷ付きシャツ",
    "新しいらにんぐシャツを買う",
],
fr=[
    "athlétisme", "course", "maillot de course", "écharpe", "débardeur",
    "maillot", "haut d'entraînement", "maillot de sport", "dossard", "singlet",
    "vêtement de sport", "maillot de marathon", "maillot de piste", "top d'entraînement", "maillot de gym",
    "maillot de compression", "évacuation de l'humidité", "tenue de sport",
    "maillot de course avec numéro d'athlétisme",
    "maillot pour course sur piste",
    "maillot de course respirant pour l'exercice",
    "maillot de course avec logo de marque",
    "écharpe sur le maillot à l'arrivée",
    "dossard numéroté porté en course",
    "maillot porté en athlétisme",
    "maillot de course avec bande réfléchissante",
    "débardeur pour entraînement en salle",
    "maillot de course léger pour le marathon",
    "maillot avec dossard numéroté pour la compétition",
    "maillot de course athlétique anti-transpiration",
    "débardeur de course en couleur vive",
    "maillot de course réfléchissant pour la nuit",
    "maillot de triathlon avec coupe aérodynamique",
    "maillot d'équipe avec logo du sponsor",
    "maillot de compression pour la performance",
    "maillot jetable pour départ par temps froid",
    "acheter un nouveau maillot pour le semi-marathon",
    "mettre le maillot d'entraînement dans le sac de sport",
    "commander les maillots d'équipe pour le relais",
    "remplacer le débardeur de course usé",
    "choisir un maillot léger pour la course d'été",
    "laver le maillot de course après le 10 km",
    "préparer le maillot de course la veille",
    "essayer le nouveau haut de sport en magasin",
    "acheter des maillots anti-transpiration pour l'entraînement",
    "retourner le maillot de course trop petit",
    "donner les vieux maillots de finisher",
    "suspendre le singlet pour sécher à l'air",
    "comparer les tissus de maillots en ligne",
    "récupérer le maillot d'équipe auprès de l'entraîneur",
    "maillot de course léger pour le marathn",
    "maillot avec dosard numéroté",
    "maillot de course athlétique anti-transpiraton",
    "acheter un noiveau maillot pour le semi",
    "remplacer le debardeur de course usé",
],
es=[
    "atletismo", "correr", "camiseta de correr", "faja", "camiseta sin mangas",
    "camiseta deportiva", "camiseta de entrenamiento", "camiseta de deporte", "dorsal", "singlet",
    "ropa deportiva", "camiseta de maratón", "camiseta de pista", "top de entrenamiento", "camiseta de gimnasio",
    "camiseta de compresión", "absorción de humedad", "vestimenta atlética",
    "camiseta de atletismo con número",
    "camiseta para carrera en pista",
    "camiseta transpirable para ejercicio",
    "camiseta de correr con logo de marca",
    "faja cruzando la camiseta en la meta",
    "dorsal numerado usado en la carrera",
    "camiseta usada en atletismo",
    "camiseta de correr con franja reflectante",
    "camiseta sin mangas para el gimnasio",
    "camiseta ligera de correr para maratón",
    "camiseta con dorsal numerado para competición",
    "camiseta atlética que absorbe la humedad",
    "camiseta sin mangas de colores vivos para correr",
    "camiseta reflectante para correr de noche",
    "camiseta de triatlón con ajuste aerodinámico",
    "camiseta de equipo con logo del patrocinador",
    "camiseta de compresión para rendimiento",
    "camiseta desechable para arranque en frío",
    "comprar camiseta nueva para el medio maratón",
    "meter la camiseta de entrenamiento en la bolsa",
    "pedir camisetas de equipo iguales para el relevo",
    "reemplazar la camiseta de correr desgastada",
    "elegir una camiseta ligera para la carrera de verano",
    "lavar la camiseta de correr después de los 10K",
    "preparar la camiseta de carrera la noche anterior",
    "probarse el nuevo top deportivo en la tienda",
    "comprar camisetas absorbentes para entrenar",
    "devolver la camiseta de correr que queda chica",
    "donar las viejas camisetas de finisher",
    "colgar el singlet para que se seque al aire",
    "comparar telas de camisetas de correr en línea",
    "recoger la camiseta del equipo con el entrenador",
    "camiseta ligera de corer para maratón",
    "camiseta con dorsl numerado para competición",
    "camiseta atlética que absorve la humedad",
    "comprar camiseta nuva para el medio maratón",
    "reemplazar la camiseta de correr desgstada",
],
)

print("Part 2 done: sheep, sheet-plastic, shirt, shirt-running")
