#!/usr/bin/env python3
"""Generate English training data for icons 319-333."""
from pathlib import Path
import csv, json

icons_dir = Path("icons")
icons_dir.mkdir(exist_ok=True)

def write_csv(path, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["text", "label"])
        w.writerows(rows)

def process_icon(icon, st_en, pst_en, reg_en, conv_en, typo_en, bnd_en, valid_en, test_en):
    icon_dir = icons_dir / icon
    icon_dir.mkdir(parents=True, exist_ok=True)
    train_en = [(t, icon) for t in st_en + pst_en + reg_en + conv_en + typo_en + bnd_en]
    write_csv(icon_dir / "train_en.csv", train_en)
    write_csv(icon_dir / "valid_en.csv", [(t, icon) for t in valid_en])
    write_csv(icon_dir / "test_en.csv",  [(t, icon) for t in test_en])
    log = {
        "icon": icon, "search_terms": st_en, "phrase_per_search_term": pst_en,
        "regular": reg_en, "conversational": conv_en, "typo": typo_en,
        "boundary": bnd_en, "valid": valid_en, "test": test_en,
    }
    with open(icon_dir / "icon_log.json", "w", encoding="utf-8") as f:
        json.dump(log, f, ensure_ascii=False, indent=2)
    n_st = len(st_en); n_pst = len(pst_en)
    print(f"  {icon}: {len(train_en)} train rows  ({n_st} st + {n_pst} pst + 24)")

# 319
process_icon("gem",
    st_en=["diamond", "gem", "gem stone", "jewel", "jewelry", "sapphire", "stone", "treasure"],
    pst_en=[
        "diamond gemstone ring", "faceted diamond gem with brilliant cut",
        "colorful gem in the display case", "gem found in the mine",
        "gem stone polished and cut", "gemstone set in the jewelry",
        "jewel set in the crown", "jewel of the collection",
        "jewelry store gem display", "jewelry with a precious gem",
        "blue sapphire gemstone ring", "sapphire gem in the gold ring",
        "precious stone cut into a gem", "stone polished into a gemstone",
        "treasure chest with gems inside", "rare gem in the treasure",
    ],
    reg_en=[
        "faceted diamond gem with a brilliant cut",
        "precious gemstone in the jewelry display case",
        "blue sapphire gem set in a gold ring",
        "rare gem found deep in the mine",
        "gemstone collection in a museum case",
        "ruby red gem on the crown",
        "in-game gem currency for the mobile game",
        "emerald green gemstone necklace",
        "diamond gem shaped to sparkle",
        "gemstone ring given as a gift",
    ],
    conv_en=[
        "I need a gem icon for the in-game store",
        "add a gemstone symbol to the jewelry section",
        "show a gem for the premium currency",
        "use the diamond gem icon for the rewards page",
    ],
    typo_en=[
        "dimaond gemstone ring",
        "sapphire gme in gold",
        "jewlery gem display",
        "precous stone gem",
    ],
    bnd_en=[
        "clear crystal quartz on the shelf",
        "gold ring with a smooth band",
        "gold coin embossed with a design",
        "diamond necklace hanging on a chain",
        "crown with jewels set in the rim",
        "pearl necklace with a clasp",
    ],
    valid_en=["faceted gem with brilliant cut", "precious gemstone in a ring", "diamond gem icon"],
    test_en=["gem icon", "gemstone symbol", "diamond gem"],
)

# 320
process_icon("gift",
    st_en=["box", "celebration", "christmas", "generosity", "gift", "giving", "holiday", "party", "present", "wrapped", "wrapped gift", "xmas"],
    pst_en=[
        "gift box with a bow on top", "surprise inside the gift box",
        "gift for the celebration event", "gift at the birthday celebration",
        "christmas gift under the tree", "christmas gift wrapped in red paper",
        "act of generosity as a gift", "generosity shown through giving a gift",
        "wrapped gift for the birthday", "gift given to a close friend",
        "giving a gift to loved ones", "giving gifts at the holiday season",
        "holiday gift exchange party", "gift for the holiday season",
        "party gift for the guest", "birthday party gift bag",
        "present wrapped in colorful paper", "surprise present for the event",
        "wrapped gift with colorful ribbon", "beautifully wrapped gift box",
        "wrapped gift ready for the party", "wrapped gift under the christmas tree",
        "xmas gift for the family", "xmas gift wrapped in festive paper",
    ],
    reg_en=[
        "wrapped gift box with a colorful ribbon and bow",
        "birthday gift bag with tissue paper",
        "christmas present under the tree",
        "gift exchange at the office holiday party",
        "surprise gift wrapped for the occasion",
        "gift tag attached to the wrapped box",
        "festive gift basket for the holiday",
        "unwrapping a birthday gift with excitement",
        "gift emoji on the celebration message",
        "generous gift given to a close friend",
    ],
    conv_en=[
        "I need a gift icon for the birthday feature",
        "add a present symbol to the holiday section",
        "show a gift for the reward animation",
        "use the gift icon for the giving feature",
    ],
    typo_en=[
        "birthdya gift wrapped",
        "chrsitmas present under tree",
        "holidy gift exchange",
        "wraped gift box",
    ],
    bnd_en=[
        "birthday cake with candles on top",
        "shopping bag with handles from the store",
        "prize ribbon badge for first place",
        "envelope with a surprise letter inside",
        "balloon tied to a gift bag",
        "treasure chest filled with rewards",
    ],
    valid_en=["wrapped gift box with ribbon", "christmas present under the tree", "birthday gift for a friend"],
    test_en=["gift icon", "wrapped present symbol", "gift for holiday"],
)

# 321
process_icon("globe",
    st_en=["country", "earth", "global", "globe", "internet", "language", "location", "map", "network", "online", "planet", "translate", "travel", "world", "www"],
    pst_en=[
        "country shown on the globe", "country selector on the globe icon",
        "earth globe viewed from space", "globe of the earth",
        "global network on the globe", "global reach shown by the globe",
        "globe with meridian lines", "spinning globe icon",
        "internet globe symbol", "globe for internet connectivity",
        "language selector globe icon", "translate language on the globe",
        "location pinned on the globe", "pinpoint location on the globe",
        "globe showing a world map", "map of the entire globe",
        "global network globe icon", "network connection around the globe",
        "online presence shown by globe", "globe for online service",
        "planet earth globe", "globe of the planet earth",
        "translate language on the globe", "globe translate icon",
        "travel the globe icon", "globe icon for travel app",
        "world globe spinning", "world map on the globe",
        "www globe for website", "internet www globe symbol",
    ],
    reg_en=[
        "globe with meridian lines showing the world",
        "world map on a spinning globe",
        "internet globe icon for a website",
        "globe symbol for international reach",
        "language selector with a globe icon",
        "travel the world globe graphic",
        "blue globe of the earth",
        "network connectivity globe symbol",
        "translate button with a globe icon",
        "global audience shown by a globe",
    ],
    conv_en=[
        "I need a globe icon for the world map feature",
        "add a globe symbol to the language selector",
        "show a globe for the international section",
        "use the globe icon for the website URL",
    ],
    typo_en=[
        "intenet globe icon",
        "glboe with meridians",
        "globl network icon",
        "wrold map on globe",
    ],
    bnd_en=[
        "flat world map pinned to the wall",
        "earth photographed from space",
        "compass rose pointing north",
        "country flag for the location",
        "satellite dish pointing at the sky",
        "map pin dropped on a location",
    ],
    valid_en=["world globe with meridian lines", "globe icon for internet", "travel the globe"],
    test_en=["globe icon", "world globe symbol", "earth globe"],
)

# 322
process_icon("guitar",
    st_en=["acoustic", "instrument", "music", "rock", "rock and roll", "song", "strings"],
    pst_en=[
        "acoustic guitar played at the campfire", "acoustic guitar strumming a melody",
        "guitar as a musical instrument", "string instrument guitar",
        "music played on the guitar", "guitar music at the concert",
        "rock guitar riff on stage", "rock concert electric guitar",
        "rock and roll guitar power chord", "rock and roll band on guitars",
        "song played on the acoustic guitar", "strum a song on the guitar",
        "guitar strings plucked gently", "strings on the guitar neck fret",
    ],
    reg_en=[
        "acoustic guitar with six strings",
        "electric guitar on the concert stage",
        "guitarist strumming chords at the campfire",
        "guitar solo at the rock concert",
        "classical guitar with nylon strings",
        "guitar pick on the fretboard",
        "bass guitar played in the band",
        "guitar chord progression for the song",
        "travel guitar for the musician on the road",
        "guitar tab shown on the music app",
    ],
    conv_en=[
        "I need a guitar icon for the music app",
        "add a guitar symbol to the instruments section",
        "show a guitar for the rock genre category",
        "use the guitar icon for the song playing feature",
    ],
    typo_en=[
        "acoustci guitar strumming",
        "guitr solo on stage",
        "rock conert guitar",
        "musik played on guitar",
    ],
    bnd_en=[
        "ukulele with four strings on the island",
        "violin bow drawn across the strings",
        "banjo played at the bluegrass festival",
        "electric bass guitar in the studio",
        "piano keys in the music studio",
        "drum kit behind the guitar player",
    ],
    valid_en=["acoustic guitar with six strings", "guitar solo at concert", "music guitar instrument"],
    test_en=["guitar icon", "guitar symbol for music", "acoustic guitar"],
)

# 323
process_icon("hand",
    st_en=["backhand", "game", "halt", "palm", "raised", "request", "roshambo", "stop"],
    pst_en=[
        "raised backhand gesture", "backhand of the raised hand",
        "hand gesture in the game", "hand in rock paper scissors game",
        "halt hand signal raised", "hand raised to halt traffic",
        "open palm facing forward", "palm of the hand raised high",
        "raised hand to ask a question", "hand raised in the classroom",
        "hand raised as a request", "request indicated by raised hand",
        "roshambo rock paper scissors hand", "roshambo game hand gesture",
        "stop hand signal raised", "hand raised to stop traffic",
    ],
    reg_en=[
        "open hand with palm facing outward",
        "raised hand to ask a question in class",
        "hand signal to halt or stop",
        "hand gesture in rock paper scissors",
        "high five hand slap celebration",
        "hand wave greeting gesture",
        "hand icon for stop or wait",
        "raised hand emoji for volunteers",
        "palm reading at the carnival",
        "hand scan for biometric authentication",
    ],
    conv_en=[
        "I need a hand icon for the stop gesture",
        "add a raised hand to the volunteer section",
        "show a hand for the pause or halt feature",
        "use the hand icon for the request button",
    ],
    typo_en=[
        "rasied hand gesture",
        "hnad signal stop",
        "paml facing forward",
        "hault traffic signal",
    ],
    bnd_en=[
        "pointing finger directed at the screen",
        "waving hand saying hello",
        "thumbs up approval gesture",
        "clapping hands applauding",
        "fist raised in solidarity",
        "peace sign with two fingers",
    ],
    valid_en=["raised hand gesture symbol", "open palm facing outward", "hand halt signal"],
    test_en=["hand icon", "raised hand symbol", "stop hand gesture"],
)

# 324
process_icon("heart",
    st_en=["ace", "card", "favorite", "game", "heart", "heart suit", "like", "love", "relationship", "valentine", "wishlist"],
    pst_en=[
        "ace of hearts card", "ace heart in the card game",
        "heart card in the deck", "card with a heart suit",
        "heart to mark a favorite", "add to favorites with a heart",
        "heart in the card game", "heart suit for the game",
        "red heart icon", "heart shape symbol",
        "heart suit in playing cards", "hearts suit card game",
        "heart like button on the post", "tap heart to like the post",
        "heart representing love", "love shown with a heart",
        "heart for a relationship", "relationship shown by heart symbol",
        "valentine heart card", "heart for Valentine's Day",
        "heart on the wishlist button", "add to wishlist with a heart",
    ],
    reg_en=[
        "red heart symbol for love",
        "heart icon for the like button",
        "anatomical heart with four chambers",
        "heart emoji on the social post",
        "heart shape cut from red paper",
        "heart symbol on the Valentine's card",
        "heart on the wishlist button",
        "ace of hearts playing card",
        "heart logo for the health app",
        "heart rate shown with a heart icon",
    ],
    conv_en=[
        "I need a heart icon for the like button",
        "add a heart symbol to the favorites section",
        "show a heart for the wishlist feature",
        "use the heart icon for the love reaction",
    ],
    typo_en=[
        "valentien heart card",
        "favortie heart button",
        "hearth rate monitor",
        "wishilst heart button",
    ],
    bnd_en=[
        "cluster of red hearts floating upward",
        "love letter sealed with a kiss",
        "engagement ring with a diamond",
        "red rose bouquet for romance",
        "heart rate graph on a fitness tracker",
        "full suit of hearts playing cards",
    ],
    valid_en=["red heart for like button", "heart on the wishlist", "Valentine's heart symbol"],
    test_en=["heart icon", "heart like symbol", "red heart for love"],
)

# 325
process_icon("hockey-stick",
    st_en=["game", "hockey", "ice", "ice hockey", "nhl", "puck", "sport", "stick"],
    pst_en=[
        "hockey stick used in the game", "ice hockey game with stick and puck",
        "hockey stick used in the rink", "hockey player holding the stick",
        "ice hockey stick on the rink", "stick used on the ice",
        "ice hockey stick and puck", "ice hockey game with the stick",
        "NHL hockey stick for the game", "NHL player swinging the stick",
        "hockey stick hitting the puck", "puck sent by the stick",
        "hockey stick for sport", "sport equipment hockey stick",
        "stick used in hockey", "hockey stick on the ice",
    ],
    reg_en=[
        "hockey stick and puck on the ice rink",
        "player holding a hockey stick at the faceoff",
        "slap shot taken with the hockey stick",
        "NHL player skating with stick and puck",
        "goalie blocking with the stick",
        "hockey stick tape on the blade",
        "ice hockey team with sticks raised",
        "hockey stick leaning against the locker",
        "junior hockey stick for young players",
        "street hockey played with stick and ball",
    ],
    conv_en=[
        "I need a hockey stick icon for the sports app",
        "add a hockey stick to the winter sports section",
        "show a stick and puck for the ice hockey category",
        "use the hockey stick icon for the NHL scores",
    ],
    typo_en=[
        "hocky stick on ice",
        "iceh ockey puck",
        "nhol player stick",
        "hockey sticck blade",
    ],
    bnd_en=[
        "lacrosse stick with a mesh pocket",
        "curling broom sweeping the ice",
        "baseball bat swung at the plate",
        "cricket bat used in the wicket game",
        "golf club iron on the fairway",
        "field hockey stick on the grass",
    ],
    valid_en=["hockey stick and puck on ice", "NHL hockey stick in game", "ice hockey stick"],
    test_en=["hockey stick icon", "hockey stick symbol", "ice hockey stick"],
)

# 326
process_icon("hourglass",
    st_en=["hour", "hourglass", "minute", "sand", "stopwatch", "time", "timer"],
    pst_en=[
        "hour counting down in the hourglass", "hour glass timing one hour",
        "hourglass sand running out", "hourglass counting down",
        "minute countdown on the hourglass", "minute passing through the hourglass",
        "sand falling through the hourglass", "fine sand in the hourglass",
        "stopwatch hourglass timing an event", "hourglass as a stopwatch",
        "time measured by the hourglass", "hourglass symbol for time",
        "timer set with the hourglass", "hourglass countdown timer",
    ],
    reg_en=[
        "sand flowing through the hourglass",
        "hourglass counting down the last minutes",
        "vintage hourglass as a time symbol",
        "hourglass icon for a loading indicator",
        "hourglass timer for the board game",
        "hourglass representing time running out",
        "hourglass on the lock screen",
        "glass hourglass with fine white sand",
        "hourglass tattoo symbolizing time",
        "hourglass flipped to restart the timer",
    ],
    conv_en=[
        "I need an hourglass icon for the countdown timer",
        "add a sand timer to the time tracking feature",
        "show an hourglass for the loading state",
        "use the hourglass icon for the session timeout",
    ],
    typo_en=[
        "hourglsas running out of sand",
        "snda flowing through glass",
        "tiemr countdown hourglass",
        "hourgllass flipped over",
    ],
    bnd_en=[
        "analog clock face with hour and minute hands",
        "digital stopwatch counting milliseconds",
        "circular progress spinner for loading",
        "countdown clock on the scoreboard",
        "alarm clock set for the morning",
        "wristwatch showing the current time",
    ],
    valid_en=["sand flowing through the hourglass", "hourglass countdown timer", "time symbol hourglass"],
    test_en=["hourglass icon", "sand timer symbol", "hourglass for countdown"],
)

# 327
process_icon("joint",
    st_en=["blunt", "cannabis", "doobie", "drugs", "marijuana", "roach", "smoke", "smoking", "spliff"],
    pst_en=[
        "blunt rolled for smoking", "cannabis blunt cigar",
        "cannabis joint rolled", "cannabis smoking joint",
        "doobie joint rolled up", "doobie to smoke",
        "drugs cannabis joint", "drugs rolled as a joint",
        "marijuana joint rolled", "marijuana smoke joint",
        "roach end of the joint", "roach clip for the joint",
        "smoke from the joint", "joint smoke in the air",
        "smoking a joint", "smoking cannabis joint",
        "spliff rolled with tobacco", "spliff joint",
    ],
    reg_en=[
        "hand-rolled cannabis joint",
        "marijuana cigarette rolled in paper",
        "joint with a twisted end",
        "cannabis blunt wrapped in leaf",
        "joint smoke rising in the air",
        "rolling a joint with rolling papers",
        "medical cannabis joint for pain relief",
        "joint icon for dispensary app",
        "spliff blended with tobacco",
        "roach end of a smoked joint",
    ],
    conv_en=[
        "I need a joint icon for the cannabis app",
        "add a marijuana symbol to the dispensary section",
        "show a joint for the smoke category",
        "use the joint icon for the cannabis feature",
    ],
    typo_en=[
        "canabis joint rolled",
        "mariajuana smoke",
        "spliff wiht tobacco",
        "roach clp for joint",
    ],
    bnd_en=[
        "cigarette with a burning tip",
        "smoking pipe with tobacco",
        "cigar rolled from a tobacco leaf",
        "vape pen producing vapor",
        "hookah pipe on the table",
        "electronic cigarette vaping device",
    ],
    valid_en=["cannabis joint rolled in paper", "marijuana smoking joint", "joint for dispensary app"],
    test_en=["joint icon", "cannabis joint symbol", "joint for smoking"],
)

# 328
process_icon("key",
    st_en=["key", "lock", "password", "private", "secret", "unlock"],
    pst_en=[
        "metal key for the door lock", "key to unlock the door",
        "key fitting the lock", "key to open the padlock",
        "key as a password symbol", "password protected by key",
        "key for the private area", "private key for access",
        "secret key revealed", "secret key for the vault",
        "key to unlock the gate", "unlock with the correct key",
    ],
    reg_en=[
        "metal key on a keyring",
        "key turning in the door lock",
        "house key hanging on the hook",
        "password key icon in the login form",
        "skeleton key for the old castle",
        "encryption key for security",
        "car key fob in the pocket",
        "key and padlock for the safe",
        "spare key hidden under the mat",
        "key icon for the password manager",
    ],
    conv_en=[
        "I need a key icon for the login screen",
        "add a key symbol to the security section",
        "show a key for the access control feature",
        "use the key icon for the password manager",
    ],
    typo_en=[
        "kye for the door lock",
        "passowrd key icon",
        "secert key revealed",
        "unlocck with key",
    ],
    bnd_en=[
        "closed padlock on the gate",
        "combination lock with a dial",
        "password text field on the login form",
        "fingerprint scanner for access",
        "access card with magnetic strip",
        "security badge worn on a lanyard",
    ],
    valid_en=["metal key on a keyring", "key icon for login", "encryption key symbol"],
    test_en=["key icon", "key symbol for lock", "key for password"],
)

# 329
process_icon("knife-kitchen",
    st_en=["chef", "cooking", "cut", "equipment", "halloween", "hocho", "kitchen knife", "knife", "sharp", "slice", "tool", "weapon"],
    pst_en=[
        "chef knife in the kitchen", "chef using a knife to chop",
        "cooking knife on the cutting board", "knife for cooking prep",
        "cut vegetables with a kitchen knife", "knife used to cut ingredients",
        "kitchen equipment knife", "knife as cooking equipment",
        "halloween knife prop costume", "knife used in halloween costume",
        "hocho Japanese kitchen knife", "hocho chef knife for sushi",
        "kitchen knife for chopping", "kitchen knife on the magnetic rack",
        "sharp knife on the cutting board", "knife sharpened for the kitchen",
        "sharp kitchen knife blade", "sharp edge on the chef knife",
        "slice bread with the knife", "knife slicing through vegetables",
        "kitchen tool knife", "tool used in cooking",
        "knife used as a weapon", "weapon knife in the halloween costume",
    ],
    reg_en=[
        "sharp chef's knife on the cutting board",
        "kitchen knife chopping vegetables",
        "knife rack mounted on the kitchen wall",
        "slicing bread with a serrated knife",
        "Japanese hocho knife for sushi preparation",
        "knife sharpened before cooking",
        "kitchen knife set stored in a block",
        "chef preparing food with a sharp knife",
        "paring knife for peeling fruit",
        "carving knife at the dinner table",
    ],
    conv_en=[
        "I need a knife icon for the cooking app",
        "add a kitchen knife to the recipe tools section",
        "show a knife for the chef category",
        "use the knife icon for the meal prep feature",
    ],
    typo_en=[
        "chefs knfie in kitchen",
        "kicthen knife cutting",
        "sharpe knife blade",
        "slceing vegetables",
    ],
    bnd_en=[
        "woodcutting axe with a wooden handle",
        "kitchen scissors cutting herbs",
        "meat cleaver on the butcher's block",
        "sword with an ornate hilt",
        "pizza cutter rolling across the dough",
        "peeler stripping the vegetable skin",
    ],
    valid_en=["sharp kitchen knife on cutting board", "chef knife for cooking", "kitchen knife for slicing"],
    test_en=["kitchen knife icon", "knife symbol for cooking", "chef knife"],
)

# 330
process_icon("lips",
    st_en=["fashion", "kiss", "lips", "lipstick", "mouth", "smile"],
    pst_en=[
        "lips as a fashion beauty icon", "fashion lipstick on the lips",
        "lips puckered for a kiss", "kiss lips symbol",
        "red lips icon", "lips with lipstick applied",
        "lipstick on the lips", "lips painted with red lipstick",
        "mouth and lips together", "lips as the mouth symbol",
        "smile on the lips", "lips forming a wide smile",
    ],
    reg_en=[
        "bright red lips with lipstick",
        "lips puckered for a kiss",
        "lip gloss on the full lips",
        "beauty brand lips logo",
        "pink lips in the makeup app",
        "lips emoji for a flirty message",
        "lip print on the love letter",
        "cosmetics ad featuring full red lips",
        "lips forming a wide smile",
        "lip sync performance on the stage",
    ],
    conv_en=[
        "I need a lips icon for the beauty app",
        "add a kiss symbol to the messages feature",
        "show lips for the makeup category",
        "use the lips icon for the lip sync feature",
    ],
    typo_en=[
        "lipsitck on lips",
        "beuaty lips icon",
        "red lps with lipstick",
        "ksis lips symbol",
    ],
    bnd_en=[
        "smiley face emoji with a wide grin",
        "talking mouth in an animation",
        "teeth shown in a smile",
        "speech bubble coming from the mouth",
        "nose above the lips on a face",
        "tongue sticking out in a playful way",
    ],
    valid_en=["red lips with lipstick", "lips puckered for a kiss", "beauty lips icon"],
    test_en=["lips icon", "red lips symbol", "kiss lips"],
)

# 331
process_icon("lock",
    st_en=["admin", "closed", "lock", "locked", "padlock", "password", "privacy", "private", "protect", "security"],
    pst_en=[
        "admin lock for restricted access", "lock for admin only area",
        "lock closed and secured", "closed lock on the door",
        "lock icon for the secure area", "lock the account",
        "locked icon showing secure", "file locked and protected",
        "padlock securing the gate", "padlock on the storage unit",
        "lock for password protected content", "password lock on the account",
        "privacy lock on personal data", "lock for user privacy",
        "private lock on the account", "lock for private content",
        "lock to protect the data", "protect with a lock",
        "security lock on the door", "lock for system security",
    ],
    reg_en=[
        "closed padlock indicating a secure area",
        "lock icon on the HTTPS website",
        "password protected by a lock symbol",
        "privacy lock on the settings page",
        "lock securing the storage locker",
        "locked file icon in the document list",
        "lock screen on the mobile phone",
        "admin lock for restricted system access",
        "lock symbol for private content",
        "combination lock on the school locker",
    ],
    conv_en=[
        "I need a lock icon for the security feature",
        "add a padlock symbol to the privacy settings",
        "show a lock for the password protected section",
        "use the lock icon for the secure area",
    ],
    typo_en=[
        "secruity lock on door",
        "padlokc on the gate",
        "prviacy lock settings",
        "lockd account icon",
    ],
    bnd_en=[
        "unlocked open padlock with shackle raised",
        "metal key for the door lock",
        "door handle with a built-in lock",
        "combination safe with a dial",
        "fingerprint unlock scanner",
        "chain with a lock holding the gate",
    ],
    valid_en=["closed padlock for secure area", "lock icon for privacy", "password lock symbol"],
    test_en=["lock icon", "padlock symbol", "lock for security"],
)

# 332
process_icon("lock-open",
    st_en=["admin", "lock", "open", "padlock", "password", "privacy", "private", "protect", "security", "unlock"],
    pst_en=[
        "admin can unlock the content", "open lock for admin access",
        "lock in open state", "open padlock not locked",
        "lock open and unlocked", "open padlock with shackle raised",
        "padlock open and unlocked", "open padlock on the gate",
        "password revealed open lock", "open lock after password entered",
        "privacy lock opened for access", "open lock for privacy settings",
        "private lock opened", "private content open lock",
        "protection removed open lock", "open lock not protecting",
        "security lock in open state", "open lock security warning",
        "unlock with open padlock", "unlock the door open lock",
    ],
    reg_en=[
        "open padlock with the shackle raised",
        "unlocked icon after a successful login",
        "open lock symbol for accessible content",
        "padlock opened after entering the password",
        "unlocked account on the dashboard",
        "open lock on the shared document",
        "security warning showing lock is open",
        "admin has unlocked the restricted area",
        "open padlock on the storage unit",
        "unlock the phone with the open lock",
    ],
    conv_en=[
        "I need an open lock icon for the unlocked state",
        "add an unlock symbol to the access granted screen",
        "show an open padlock when login succeeds",
        "use the open lock for the public content section",
    ],
    typo_en=[
        "unlocekd padlock",
        "opne lock symbol",
        "padlokc open",
        "secruity open lock",
    ],
    bnd_en=[
        "closed padlock securing the gate",
        "metal key inserted in the keyhole",
        "open door with the handle down",
        "combination safe with the door open",
        "biometric scan unlocking the device",
        "access badge shown for entry",
    ],
    valid_en=["open padlock with shackle raised", "unlocked icon after login", "open lock for access"],
    test_en=["lock-open icon", "unlocked padlock symbol", "open lock"],
)

# 333
process_icon("mask",
    st_en=["carnivale", "costume", "disguise", "halloween", "secret", "super hero"],
    pst_en=[
        "carnivale mask for the festival", "ornate carnivale mask with feathers",
        "mask worn with a costume", "costume mask for the party",
        "mask for a disguise", "disguise yourself with a mask",
        "halloween mask for trick or treat", "scary halloween mask",
        "mask hiding a secret identity", "secret identity behind the mask",
        "super hero mask on the face", "superhero mask costume",
    ],
    reg_en=[
        "ornate masquerade mask for the ball",
        "halloween scary mask for trick or treat",
        "superhero mask covering the eyes",
        "carnival mask decorated with feathers",
        "mystery character behind the mask",
        "costume mask for the fancy dress party",
        "theater mask used in the performance",
        "ninja disguise mask in black",
        "masquerade party with elaborate masks",
        "mask revealing a secret identity",
    ],
    conv_en=[
        "I need a mask icon for the Halloween feature",
        "add a masquerade mask to the costume section",
        "show a mask for the superhero category",
        "use the mask icon for the disguise feature",
    ],
    typo_en=[
        "halowween mask",
        "superehro mask",
        "carnivle mask",
        "disgiuse mask costume",
    ],
    bnd_en=[
        "surgical face mask worn at the hospital",
        "gas mask with filter for toxic air",
        "face paint applied for the performance",
        "knight helmet visor on the armor",
        "ski goggles covering the eyes on the slope",
        "party sunglasses worn as a costume prop",
    ],
    valid_en=["masquerade mask for the ball", "halloween mask costume", "superhero mask icon"],
    test_en=["mask icon", "costume mask symbol", "halloween mask"],
)
