#!/usr/bin/env python3
"""Generate English training data for icons 292-306."""
from pathlib import Path
import csv, json

icons_dir = Path("icons")
icons_dir.mkdir(exist_ok=True)

def write_csv(path, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["text", "label"])
        w.writerows(rows)

def process_icon(icon, st_en, pst_en, reg_en, conv_en, typo_en, bnd_en, valid_en, test_en):
    icon_dir = icons_dir / icon
    icon_dir.mkdir(parents=True, exist_ok=True)
    train_en = [(t, icon) for t in st_en + pst_en + reg_en + conv_en + typo_en + bnd_en]
    write_csv(icon_dir / "train_en.csv", train_en)
    write_csv(icon_dir / "valid_en.csv", [(t, icon) for t in valid_en])
    write_csv(icon_dir / "test_en.csv",  [(t, icon) for t in test_en])
    log = {
        "icon": icon, "search_terms": st_en, "phrase_per_search_term": pst_en,
        "regular": reg_en, "conversational": conv_en, "typo": typo_en,
        "boundary": bnd_en, "valid": valid_en, "test": test_en,
    }
    with open(icon_dir / "icon_log.json", "w", encoding="utf-8") as f:
        json.dump(log, f, ensure_ascii=False, indent=2)
    n_st = len(st_en); n_pst = len(pst_en)
    print(f"  {icon}: {len(train_en)} train rows  ({n_st} st + {n_pst} pst + 24)")

# 292
process_icon("baseball-bat",
    st_en=["bat", "league", "mlb", "slugger", "softball", "sport"],
    pst_en=[
        "wooden baseball bat in the dugout", "aluminum bat for little league",
        "little league baseball game", "major league baseball season",
        "MLB World Series playoff", "MLB team roster update",
        "home run slugger at the plate", "slugger swinging hard at the pitch",
        "softball bat for the weekend game", "softball team practice with bats",
        "sport equipment including baseball bat", "bat as sport equipment",
    ],
    reg_en=[
        "wooden baseball bat leaning on the dugout wall",
        "batter holding the bat at home plate",
        "aluminum little league bat in the equipment bag",
        "baseball bat and ball ready for the game",
        "player swinging the bat at a fastball",
        "bat cracking against the baseball with a loud pop",
        "MLB slugger warming up in the on-deck circle",
        "bat signed by the home run champion",
        "softball game played with aluminum bats",
        "children practicing batting at the park",
    ],
    conv_en=[
        "I need a baseball bat icon for my sports app",
        "add a bat symbol to the baseball stats section",
        "show a bat icon for the slugger leaderboard",
        "use the baseball bat for the sports equipment category",
    ],
    typo_en=[
        "basball bat at home plate",
        "sluger swinging at the pitch",
        "softbal bat for the game",
        "basebal leageu season",
    ],
    bnd_en=[
        "flat cricket bat used in the wicket game",
        "hockey stick gliding across the ice",
        "golf club hitting the ball on the fairway",
        "tennis racket swinging at the serve",
        "pool cue resting on the billiard table",
        "badminton racket for the backyard game",
    ],
    valid_en=["wooden baseball bat for the game", "MLB slugger at the plate", "softball bat in the bag"],
    test_en=["baseball bat icon", "slugger bat symbol", "bat for sport"],
)

# 293
process_icon("bin",
    st_en=["collect", "container", "jug", "plastics", "recycle"],
    pst_en=[
        "collect recyclables in the bin", "collection bin at the entrance",
        "plastic container for sorting waste", "container for recycling materials",
        "plastic jug in the recycling bin", "jug recycling at the depot",
        "plastics sorted into the recycling bin", "recycle plastics at the depot",
        "recycle bin placed at the curb", "put the bottles in the recycle bin",
    ],
    reg_en=[
        "blue recycling bin with recycle symbol on the lid",
        "sorting bottles and cans into the recycle bin",
        "plastic container at the recycling depot",
        "bring plastics to the collection bin",
        "curbside recycle bin on pickup day",
        "sorted recycling in blue and green bins",
        "recycling symbol on the plastic container",
        "take out the recycling bin on Monday morning",
        "plastic bottles and cans in the recycle bin",
        "recycle jug at the grocery store entrance",
    ],
    conv_en=[
        "I need a bin icon for the waste sorting feature",
        "add a recycle bin symbol to the eco section",
        "show a container for the recycling reminder",
        "use the bin icon for the collection schedule page",
    ],
    typo_en=[
        "recyle bin at the curb",
        "plastcis container for sorting",
        "colect the recyclables today",
        "recycl jug at the depot",
    ],
    bnd_en=[
        "black trash can at the curb on pickup day",
        "office wastebasket overflowing with paper",
        "large dumpster behind the restaurant",
        "shopping basket at the grocery store",
        "laundry basket full of clothes",
        "compost bin for food scraps",
    ],
    valid_en=["blue recycle bin for plastics", "recycling container at the depot", "collect recyclables in the bin"],
    test_en=["recycle bin symbol", "plastic recycling container", "bin for sorting waste"],
)

# 294
process_icon("books",
    st_en=["book", "books", "diary", "documentation", "journal", "knowledge", "library", "read", "research", "scholar"],
    pst_en=[
        "stack of books on the reading desk", "books neatly arranged on shelf",
        "pile of books for the course", "books from the library collection",
        "diary and journal books together", "books including a personal diary",
        "documentation books for the developer", "technical books for API documentation",
        "academic journal books on the shelf", "research journal books in the library",
        "books filled with knowledge", "knowledge gained from reading books",
        "library shelf full of books", "library books available to borrow",
        "read multiple books this month", "books to read on the weekend",
        "research books for the thesis", "books used in academic research",
        "scholar surrounded by stacks of books", "scholarly books for academic study",
    ],
    reg_en=[
        "multiple books stacked on a reading desk",
        "colorful row of books on the library shelf",
        "student surrounded by stacks of textbooks",
        "pile of books ready for the course",
        "books from different genres on the nightstand",
        "academic books for thesis research",
        "library catalog for browsing book collections",
        "books on finance and self-improvement",
        "three leather-bound books in a row",
        "reading several books at the same time",
    ],
    conv_en=[
        "I need a books icon for the reading list feature",
        "add a stack of books to the library section",
        "show books for the knowledge base category",
        "use the books icon for the curriculum page",
    ],
    typo_en=[
        "stck of books on the desk",
        "librarey books to borrow",
        "resaerch books for study",
        "knoweldge books on the shelf",
    ],
    bnd_en=[
        "single hardcover book with a decorative cover",
        "leather bookmark with a tassel in the novel",
        "built-in bookshelf covering the entire wall",
        "open book with pages spread wide",
        "e-reader device loaded with digital titles",
        "ancient scroll with wax seal",
    ],
    valid_en=["stack of books for the library", "multiple books for research", "knowledge books on the shelf"],
    test_en=["books icon for reading", "library books collection", "books for study"],
)

# 295
process_icon("butterfly",
    st_en=["bug", "butterfly", "delicate", "flutter", "flying", "garden", "insect", "moth", "nature", "wings"],
    pst_en=[
        "delicate bug with colorful wings", "butterfly bug in the garden",
        "butterfly landing on a flower petal", "monarch butterfly in the meadow",
        "delicate butterfly wings pattern", "delicate insect resting on a petal",
        "butterfly flutter in the breeze", "flutter of wings in the garden",
        "butterfly flying from flower to flower", "flying butterfly in the morning sun",
        "butterfly in the summer garden", "garden butterfly visiting the roses",
        "beautiful winged insect on a leaf", "insect with colorful patterned wings",
        "moth or butterfly at the window light", "moth with large dusty wings",
        "nature butterfly in the meadow", "butterfly as a nature symbol",
        "butterfly wings with colorful patterns", "wings spread wide on the branch",
    ],
    reg_en=[
        "monarch butterfly with orange and black wings",
        "butterfly landing gently on a flower petal",
        "delicate butterfly wings in the garden",
        "colorful butterfly fluttering in the meadow",
        "butterfly on a nature walk trail",
        "blue morpho butterfly with iridescent wings",
        "butterfly lifecycle from caterpillar to adult",
        "spring butterfly emerging from the chrysalis",
        "butterfly as a symbol of transformation",
        "butterfly garden at the botanical museum",
    ],
    conv_en=[
        "I need a butterfly icon for the nature app",
        "add a butterfly to the garden section",
        "show a butterfly for the transformation feature",
        "use the butterfly icon for the spring theme",
    ],
    typo_en=[
        "butterfyl wings open wide",
        "monrach butterfly in meadow",
        "gardn butterfly on flowers",
        "fluttring wings in the breeze",
    ],
    bnd_en=[
        "moth attracted to the porch light at night",
        "dragonfly hovering over the pond surface",
        "honeybee landing on the lavender flowers",
        "ladybug on a green leaf in the garden",
        "grasshopper in the summer grass",
        "firefly glowing in the evening yard",
    ],
    valid_en=["butterfly with colorful wings", "butterfly in the garden", "monarch butterfly symbol"],
    test_en=["butterfly icon for nature", "butterfly wings fluttering", "garden butterfly"],
)

# 296
process_icon("campfire",
    st_en=["Dungeons & Dragons", "caliente", "campaign", "camping", "d&d", "dnd", "fall", "fire", "flame", "gathering", "heat", "hot", "meeting", "outdoors", "seasonal", "tent", "wilderness"],
    pst_en=[
        "Dungeons and Dragons adventurers around the campfire", "D&D campaign scene with fire",
        "caliente campfire in the desert heat", "caliente fire keeping the group warm",
        "campaign planning session around the campfire", "campaign meeting gathered by the fire",
        "camping campfire at the site", "camping night by the glowing fire",
        "d&d game played by the campfire light", "d&d session with campfire ambiance",
        "dnd dungeon master narrating by the fire", "dnd campaign fire scene",
        "fall campfire with autumn leaves around", "fall evening campfire gathering",
        "fire burning at the campsite", "campfire fire crackling in the night",
        "flame of the campfire dancing at night", "campfire flame glowing orange",
        "gathering around the campfire circle", "friends gathering by the fire",
        "heat from the campfire on a cold night", "campfire heat warming the group",
        "sit close to the hot campfire", "hot campfire on the beach",
        "meeting point set by the campfire", "meeting friends at the campfire",
        "outdoors campfire under the stars", "campfire in the outdoors",
        "seasonal campfire gathering in autumn", "seasonal fire pit on the patio",
        "tent pitched next to the campfire", "campfire beside the camping tent",
        "wilderness campfire for survival warmth", "campfire deep in the wilderness",
    ],
    reg_en=[
        "crackling campfire with glowing orange embers",
        "friends gathered around the campfire at night",
        "roasting marshmallows over the open campfire",
        "campfire glowing under a starry sky",
        "wilderness survival campfire in the forest",
        "fall camping night with a warm fire",
        "campfire circle for an outdoor gathering",
        "D&D tabletop session played by firelight",
        "smoke rising from the campfire into the night",
        "tent pitched near a crackling campfire",
    ],
    conv_en=[
        "I need a campfire icon for the camping app",
        "add a fire icon for the gathering feature",
        "show a campfire for the outdoor activities section",
        "use the campfire for the wilderness survival mode",
    ],
    typo_en=[
        "campfier burning at the site",
        "wildernes campfire survival",
        "campig fire at night",
        "gathring around the campfire",
    ],
    bnd_en=[
        "large bonfire at the beach celebration",
        "stone fireplace with burning logs inside",
        "candle flame on the dinner table",
        "flaming torch mounted on the castle wall",
        "fire pit in the backyard patio",
        "burning lantern on the camping trail",
    ],
    valid_en=["campfire glowing at the campsite", "friends gathered around the campfire", "outdoor fire for camping night"],
    test_en=["campfire icon", "fire gathering outdoors", "wilderness campfire"],
)

# 297
process_icon("chess",
    st_en=["board", "castle", "checkmate", "game", "king", "rook", "strategy", "tournament"],
    pst_en=[
        "chess board with pieces set in position", "board game of chess between players",
        "castle piece moved to safety on the board", "chess castle rook protecting the king",
        "checkmate move that wins the game", "checkmate delivered in three moves",
        "chess game between two players", "classic board game of chess",
        "protect the chess king from attack", "chess king placed in check",
        "rook moved across the open file", "chess rook positioned in the corner",
        "strategy of the chess opening move", "chess strategy and tactical planning",
        "chess tournament at the local club", "tournament chess player ranking list",
    ],
    reg_en=[
        "chess board with black and white pieces arranged",
        "chess king in a checkmate position",
        "rook positioned at the corner of the board",
        "grandmaster planning the next chess move",
        "chess tournament with serious competitors",
        "opening strategy in the chess game",
        "chess knight making an L-shaped jump",
        "chess clock ticking during a competitive game",
        "outdoor chess set in the city park",
        "online chess game played on the mobile app",
    ],
    conv_en=[
        "I need a chess icon for the strategy games section",
        "add a chess piece to the board games category",
        "show a chess symbol for the tournament feature",
        "use the chess icon for the strategy challenge",
    ],
    typo_en=[
        "chekmate delivered in three moves",
        "ches tournament at the club",
        "startegy game of chess",
        "chees board with pieces",
    ],
    bnd_en=[
        "checkers board with red and black pieces",
        "dice rolled for the board game",
        "jigsaw puzzle piece on the table",
        "backgammon board with pieces in play",
        "playing cards shuffled for the card game",
        "domino pieces arranged in a long line",
    ],
    valid_en=["chess board with pieces", "checkmate in chess game", "chess strategy tournament"],
    test_en=["chess icon for games", "chess king symbol", "chess board game"],
)

# 298
process_icon("cloud",
    st_en=["atmosphere", "cloud", "fog", "overcast", "save", "upload", "weather"],
    pst_en=[
        "cloud floating in the earth's atmosphere", "atmosphere layer with white clouds",
        "fluffy white cloud in the sky", "cloud passing slowly overhead",
        "morning fog and low cloud cover", "foggy cloud at dawn",
        "overcast sky with dark clouds all day", "overcast cloud cover blocking the sun",
        "save your files to the cloud", "save to cloud storage automatically",
        "upload photos to cloud storage", "cloud upload in progress",
        "cloud weather forecast icon", "weather app showing cloudy skies",
    ],
    reg_en=[
        "fluffy white cloud floating in the blue sky",
        "dark storm cloud building on the horizon",
        "cloud storage icon for saving files",
        "upload data to the cloud service",
        "overcast sky covered with gray clouds",
        "morning fog with low cloud cover",
        "single cloud passing over the bright sun",
        "cloud computing server symbol",
        "weather forecast showing cloudy conditions",
        "cloud syncing data across all devices",
    ],
    conv_en=[
        "I need a cloud icon for the file storage feature",
        "add a cloud symbol to the upload button",
        "show a cloud for the weather section",
        "use the cloud icon for the sync status",
    ],
    typo_en=[
        "clod storage upload",
        "overacst sky today",
        "uploaed photos to cloud",
        "weatehr showing cloud",
    ],
    bnd_en=[
        "storm cloud with a lightning bolt striking",
        "rain cloud with drops falling below",
        "bright sun with radiating yellow rays",
        "smoke rising from the chimney",
        "fog rolling in from the sea",
        "cloud with snowflakes falling underneath",
    ],
    valid_en=["white cloud in the sky", "cloud storage for saving files", "overcast weather cloud"],
    test_en=["cloud icon for weather", "upload to cloud storage", "fluffy cloud symbol"],
)

# 299
process_icon("credit-card",
    st_en=["buy", "card", "checkout", "credit", "credit card", "debit", "money", "payment", "purchase"],
    pst_en=[
        "buy online with a credit card", "buy now using card payment",
        "swipe the card at checkout", "tap card to pay at terminal",
        "checkout with credit card payment", "checkout payment by card",
        "available credit on the account", "credit account for purchases",
        "credit card payment accepted here", "use credit card for the booking",
        "debit card for daily purchases", "pay with debit card at the store",
        "money charged to the credit card", "pay with card instead of cash",
        "payment by credit card processed", "card payment confirmed successfully",
        "purchase confirmed with credit card", "purchase with card at the register",
    ],
    reg_en=[
        "credit card with chip and magnetic stripe",
        "tap to pay with a contactless credit card",
        "enter card number at the checkout form",
        "payment declined notification on the card",
        "add credit card to the mobile wallet",
        "credit card statement showing recent purchases",
        "secure online payment with card details",
        "debit card linked to the bank account",
        "swipe card at the point of sale terminal",
        "credit card limit reached for the month",
    ],
    conv_en=[
        "I need a credit card icon for the payments page",
        "add a card symbol to the checkout flow",
        "show a credit card for the billing section",
        "use the card icon for the payment method settings",
    ],
    typo_en=[
        "crdit card payment failed",
        "chekcout with card",
        "purchaes by card",
        "payemnt declined",
    ],
    bnd_en=[
        "gift card with ribbon and bow design",
        "photo ID card with name and badge number",
        "business card with contact information",
        "loyalty card for the coffee shop rewards",
        "membership card with barcode on the back",
        "transit card for the subway system",
    ],
    valid_en=["credit card for payment", "checkout with card payment", "debit card for purchases"],
    test_en=["credit card symbol", "payment by card icon", "card checkout"],
)

# 300
process_icon("cross",
    st_en=["Christian", "catholicism", "christianity", "church", "cross", "jesus", "latin cross", "religion"],
    pst_en=[
        "Christian cross symbol of faith", "Christian faith represented by the cross",
        "catholicism cross at the altar", "catholic cross on the chapel wall",
        "christianity cross on the church building", "christianity symbol the cross",
        "church cross on the steeple", "cross on top of the church tower",
        "wooden cross on the hill", "cross carved from stone",
        "cross where Jesus was crucified", "Jesus on the cross depiction",
        "latin cross with a longer lower arm", "traditional latin cross shape",
        "cross as a religion symbol", "religion icon of the cross",
    ],
    reg_en=[
        "wooden cross on top of the church steeple",
        "gold cross pendant on a necklace",
        "latin cross carved in stone",
        "cross symbol at the altar during mass",
        "roadside memorial cross with flowers",
        "cross used in a Christian baptism ceremony",
        "cemetery cross marking the grave",
        "simple wooden cross for a religious service",
        "church stained glass window with a cross",
        "cross emblem on the bishop's vestment",
    ],
    conv_en=[
        "I need a cross icon for the church app",
        "add a Christian cross to the religion section",
        "show a cross symbol for the faith category",
        "use the latin cross for the religious event page",
    ],
    typo_en=[
        "cristian cross symbol",
        "catholicisim cross at altar",
        "chruch cross on steeple",
        "religin cross symbol",
    ],
    bnd_en=[
        "green medical cross on a hospital sign",
        "checkmark confirming a completed task",
        "plus sign for adding an item to the list",
        "red cross of the first aid kit",
        "star of David Jewish religious symbol",
        "crescent moon and star Islamic symbol",
    ],
    valid_en=["Christian cross symbol", "cross on the church steeple", "latin cross religion icon"],
    test_en=["cross symbol for faith", "church cross icon", "Christian religion cross"],
)

# 301
process_icon("crown",
    st_en=["award", "clothing", "crown", "favorite", "king", "queen", "royal", "tiara", "vip"],
    pst_en=[
        "award crown for the champion", "crown given as an award for excellence",
        "crown as a royal clothing accessory", "crown worn as a clothing item",
        "gold crown worn by the king", "jeweled crown on museum display",
        "crown the favorite item in the list", "crown symbol for a favorite choice",
        "king's crown with jewels on the rim", "king wearing the crown on the throne",
        "queen's crown at the coronation", "crown placed on the queen's head",
        "royal crown symbol for the monarchy", "royal crown worn by the monarch",
        "sparkling tiara crown at the pageant", "tiara crown for the princess",
        "VIP crown for premium members", "crown symbol for VIP status",
    ],
    reg_en=[
        "gold crown with red jewels on the rim",
        "king wearing a royal crown on the throne",
        "queen's crown displayed at the coronation ceremony",
        "crown symbol for the top-rated item",
        "jeweled tiara worn at the beauty pageant",
        "crown badge for the best review on the platform",
        "paper crown from the birthday party",
        "VIP badge with a crown for premium users",
        "royal crown displayed in the history museum",
        "three-pointed crown as a royal symbol",
    ],
    conv_en=[
        "I need a crown icon for the premium user tier",
        "add a crown symbol to the leaderboard top position",
        "show a crown for the VIP section",
        "use the king's crown for the royal category",
    ],
    typo_en=[
        "kigns crown on the throne",
        "royyal crown symbol",
        "jewled tiara crown",
        "queeen's crown",
    ],
    bnd_en=[
        "gold medal hanging from a ribbon at the olympics",
        "golden trophy cup for the tournament champion",
        "award ribbon badge for first place at the fair",
        "party hat with polka dots at the birthday",
        "wizard hat with stars and a wide brim",
        "graduation cap tossed in the air",
    ],
    valid_en=["gold crown for the king", "royal crown symbol", "VIP crown for premium users"],
    test_en=["crown icon", "king queen crown symbol", "jeweled royal crown"],
)

# 302
process_icon("dress",
    st_en=["gown", "skirt"],
    pst_en=[
        "formal gown for the evening event", "wedding gown worn by the bride",
        "dress skirt flaring at the hem", "summer dress with a flowing skirt",
    ],
    reg_en=[
        "elegant evening dress on the mannequin",
        "floral summer dress for warm days",
        "wedding dress with a long train",
        "party dress for the celebration",
        "little black dress for the cocktail event",
        "casual day dress with a belt",
        "dress hanging on the closet rack",
        "child's princess dress for the pageant",
        "maxi dress for the beach vacation",
        "red dress for the formal dinner",
    ],
    conv_en=[
        "I need a dress icon for the fashion app",
        "add a gown symbol to the clothing category",
        "show a dress for the wardrobe section",
        "use the dress icon for the event outfit picker",
    ],
    typo_en=[
        "evenig dress for the gala",
        "weding gown on the bride",
        "summre dress for the beach",
        "cocktial dress event",
    ],
    bnd_en=[
        "button-up shirt hanging on the hanger",
        "pleated skirt for the school uniform",
        "winter coat with a wool lining",
        "jeans laid out on the bed",
        "formal suit jacket for the interview",
        "blouse with a floral pattern for spring",
    ],
    valid_en=["elegant dress for a formal event", "summer dress for the party", "wedding gown dress"],
    test_en=["dress icon for fashion", "gown symbol for clothing", "party dress"],
)

# 303
process_icon("flag",
    st_en=["black flag", "country", "notice", "notification", "notify", "pole", "report", "symbol", "waving"],
    pst_en=[
        "black flag symbol on the post", "black flag pirate ship theme",
        "country flag waving on the pole", "national flag of the country",
        "notice flagged for review", "flag a notice for attention",
        "flag notification for the item", "notification flag on the post",
        "notify with a flag marker", "flagged to notify the team",
        "flag on a tall metal pole", "pole with flag at the entrance",
        "report flagged for moderation", "flag a report for review",
        "flag as a symbol for the country", "symbol displayed on the flag",
        "waving flag in the breeze", "flag waving in the wind",
    ],
    reg_en=[
        "national flag waving on a tall pole",
        "red flag marker indicating a problem",
        "flag planted at the summit of the mountain",
        "checkered flag at the finish line of the race",
        "flag icon for marking important content",
        "pirate black flag on the ship mast",
        "country flag in the hotel lobby",
        "flag report to notify the admin",
        "small flag on the golf course hole marker",
        "UN flag flying outside headquarters",
    ],
    conv_en=[
        "I need a flag icon for the report button",
        "add a flag symbol to the notification system",
        "show a flag for the country selector",
        "use the flag icon to mark important items",
    ],
    typo_en=[
        "coutry flag waving in wind",
        "flagged notifcation item",
        "reprot flagged for review",
        "wavig flag on the pole",
    ],
    bnd_en=[
        "sports pennant hanging on the wall",
        "wide banner hanging across the street",
        "bookmark sticking out of the novel",
        "finish line tape stretched across the track",
        "signal flag waved by a race official",
        "tag label attached to the product",
    ],
    valid_en=["national flag on the pole", "flag symbol for the country", "flag notification marker"],
    test_en=["flag icon", "waving flag symbol", "country flag"],
)

# 304
process_icon("flower",
    st_en=["blossom", "daffodil", "flower", "nature", "spring", "summer"],
    pst_en=[
        "cherry blossom in spring", "blossom opening on the flower tree",
        "yellow daffodil in the spring garden", "daffodil blooming after winter",
        "flower blooming in the garden", "single flower with colorful petals",
        "flower in the nature meadow", "nature flower growing wild",
        "spring flower garden in full bloom", "flower garden in spring",
        "summer flower field in full bloom", "summer sunflower in the garden",
    ],
    reg_en=[
        "single flower with colorful petals",
        "spring flower garden in full bloom",
        "yellow daffodil nodding in the breeze",
        "bouquet of mixed flowers for the occasion",
        "wild flower growing by the meadow path",
        "flower petal falling in the summer breeze",
        "flower planted in the window box",
        "flower pressed between the book pages",
        "sunflower facing toward the morning light",
        "cherry blossom flower on the tree branch",
    ],
    conv_en=[
        "I need a flower icon for the garden app",
        "add a flower symbol to the spring section",
        "show a flower for the nature category",
        "use the flower icon for the florist feature",
    ],
    typo_en=[
        "flwer in the garden",
        "blosoom in spring",
        "daffodil blooming in summre",
        "gardn flower growing wild",
    ],
    bnd_en=[
        "green leaf on the tree branch",
        "potted plant on the windowsill",
        "thorny rose on the Valentine's stem",
        "tulip opening in the spring garden",
        "daisy with white petals and yellow center",
        "lotus flower floating on the pond",
    ],
    valid_en=["flower with petals in the garden", "spring flower blooming symbol", "daffodil flower icon"],
    test_en=["flower icon for nature", "flower symbol for spring", "blooming flower"],
)

# 305
process_icon("medal",
    st_en=["award", "guarantee", "medal", "quality", "ribbon", "sports medal", "star", "trophy", "warranty"],
    pst_en=[
        "medal awarded to the champion", "sports award medal ceremony",
        "quality guarantee medal seal", "medal as a guarantee of quality",
        "gold medal on a ribbon lanyard", "medal placed around the winner's neck",
        "quality medal certified by the lab", "quality assurance medal on packaging",
        "medal hanging on a ribbon lanyard", "ribbon and medal at the award ceremony",
        "sports medal from the marathon race", "sports medal for the competition",
        "star on the medal for excellence", "star-shaped medal for achievement",
        "medal and trophy at the award night", "trophy and medal for the winner",
        "warranty medal seal on packaging", "quality warranty medal logo",
    ],
    reg_en=[
        "gold medal hanging from a red and blue ribbon",
        "olympic medal placed around the athlete's neck",
        "marathon finisher medal at the finish line",
        "quality assurance medal on the product label",
        "military medal pinned to the uniform",
        "podium ceremony with medal presentation",
        "silver medal for the second-place finisher",
        "star-shaped achievement medal on a lanyard",
        "school medal for academic excellence",
        "bronze medal at the international competition",
    ],
    conv_en=[
        "I need a medal icon for the achievement system",
        "add a sports medal to the competition results",
        "show a medal for the challenge completion screen",
        "use the medal icon for the awards ceremony page",
    ],
    typo_en=[
        "olmpic medal ceremony",
        "qualiy guarantee medal",
        "achevement medal earned",
        "ribon hanging medal",
    ],
    bnd_en=[
        "ribbon badge pinned to the jacket for first place",
        "golden trophy cup for the tournament champion",
        "graduation certificate with official seal",
        "star sticker badge for excellent work",
        "number-one ranked badge on the leaderboard",
        "competition podium with three numbered places",
    ],
    valid_en=["gold medal on a ribbon", "sports medal for the competition", "quality medal award"],
    test_en=["medal icon", "olympic medal symbol", "sports medal achievement"],
)

# 306
process_icon("person-meditating",
    st_en=["calm", "contemplate", "meditate", "peace", "relax", "yoga"],
    pst_en=[
        "calm person meditating quietly", "find calm through daily meditation",
        "contemplate in a seated meditation pose", "quiet contemplation in meditation",
        "meditate in the lotus position", "meditating person with eyes closed",
        "peace found through daily meditation", "meditate for inner peace",
        "relax and meditate before bed", "meditation to relax the mind",
        "yoga meditation in a seated pose", "yoga and meditation practice",
    ],
    reg_en=[
        "person sitting cross-legged in meditation",
        "meditating figure in the lotus position",
        "yoga practitioner in silent meditation",
        "morning meditation for mental clarity",
        "person breathing deeply in a calm pose",
        "mindfulness meditation session at sunrise",
        "meditation app icon with a seated figure",
        "calm and centered meditation practice",
        "stress relief through guided meditation",
        "person meditating on a yoga mat",
    ],
    conv_en=[
        "I need a meditation icon for the wellness app",
        "add a yoga pose to the mindfulness section",
        "show a meditating figure for the calm feature",
        "use the meditation icon for the relaxation timer",
    ],
    typo_en=[
        "mediatte in lotus position",
        "yoag meditation pose",
        "contmeplate in silence",
        "mintfulness meditation",
    ],
    bnd_en=[
        "person doing push-ups on the exercise mat",
        "person stretching hamstrings before a run",
        "person seated and working at a desk",
        "person doing a warrior yoga pose standing",
        "person lying down for a nap",
        "person praying with hands clasped together",
    ],
    valid_en=["person meditating in lotus position", "yoga meditation seated pose", "calm meditation figure"],
    test_en=["meditation icon", "meditating person symbol", "yoga meditation pose"],
)
