#!/usr/bin/env python3
"""Task-005 part 2: popcorn, popsicle, power-off"""
from gen_icons_task_005_common import gen

# ── popcorn ───────────────────────────────────────────────────────────────────
gen("popcorn",
en=[
    "popcorn",
    "buttered popcorn",
    "movie snack",
    "kettle corn",
    "movie theater",
    "cinema snack",
    "corn kernels",
    "microwave popcorn",
    "caramel popcorn",
    "popcorn bucket",
    "movie night",
    "snack",
    "theater concessions",
    "popcorn machine",
    "salted popcorn",
    "popcorn bag",
    "cheese popcorn",
    "popcorn seasoning",
    "buy microwave popcorn for movie night",
    "make popcorn before the movie starts",
    "grab a large popcorn at the theater",
    "the popcorn machine needs new kernels",
    "add extra butter to the popcorn",
    "pick up caramel popcorn at the store",
    "bring popcorn for the school movie day",
    "try the new cheddar popcorn flavor",
    "pop a bag of popcorn for the kids",
    "the popcorn burned in the microwave again",
    "buy popcorn seasoning from the grocery store",
    "share a bucket of popcorn at the movies",
    "make kettle corn for the party",
    "stock up on microwave popcorn for the week",
    "clean the popcorn machine after the event",
    "order gourmet popcorn as a gift",
    "sneak popcorn into the movie theater",
    "the popcorn kernels are in the pantry",
    "salt the popcorn while it's still hot",
    "buy a bag of movie theater butter popcorn",
    "set a timer so the popcorn doesn't burn",
    "pour melted butter over the fresh popcorn",
    "throw away the unpopped kernels at the bottom",
    "try making popcorn on the stovetop tonight",
    "get popcorn and candy for the family movie",
    "the theater popcorn smells amazing",
    "refill the popcorn bucket during the previews",
    "make a popcorn bar for the birthday party",
    "buy organic popcorn kernels online",
    "season the popcorn with garlic powder",
    "bring a bowl for the homemade popcorn",
    "popcorn is the best snack for binge-watching",
    "need to restock the popcorn supply at home",
    "munch on popcorn while studying",
    "the caramel popcorn from that shop is addictive",
    "make chocolate drizzle popcorn for dessert",
    "popocorn for movie night",
    "popcron at the theater",
    "buttreed popcorn snack",
    "micowave popcorn bag",
    "kernal popcorn stovetop",
],
ru=[
    "попкорн",
    "попкорн с маслом",
    "закуска для кино",
    "карамельный попкорн",
    "кинотеатр",
    "кинозакуска",
    "кукурузные зёрна",
    "попкорн для микроволновки",
    "солёный попкорн",
    "ведро попкорна",
    "киновечер",
    "перекус",
    "буфет кинотеатра",
    "аппарат для попкорна",
    "попкорн в пакете",
    "сырный попкорн",
    "приправа для попкорна",
    "кеттл-корн",
    "купить попкорн для микроволновки на киновечер",
    "сделать попкорн до начала фильма",
    "взять большой попкорн в кинотеатре",
    "в аппарат для попкорна нужны новые зёрна",
    "добавить побольше масла в попкорн",
    "купить карамельный попкорн в магазине",
    "принести попкорн на школьный киносеанс",
    "попробовать новый попкорн со вкусом чеддера",
    "приготовить пакет попкорна для детей",
    "попкорн опять подгорел в микроволновке",
    "купить приправу для попкорна в продуктовом",
    "разделить ведро попкорна на сеансе",
    "приготовить кеттл-корн для вечеринки",
    "запастись попкорном для микроволновки на неделю",
    "почистить аппарат для попкорна после мероприятия",
    "заказать гурманский попкорн в подарок",
    "пронести попкорн в кинозал",
    "зёрна для попкорна в кладовке",
    "посолить попкорн пока он ещё горячий",
    "купить пакет попкорна со вкусом кинотеатра",
    "поставить таймер чтобы попкорн не подгорел",
    "полить свежий попкорн растопленным маслом",
    "выбросить невзорвавшиеся зёрна со дна",
    "попробовать приготовить попкорн на плите сегодня",
    "купить попкорн и конфеты для семейного кино",
    "попкорн в кинотеатре пахнет потрясающе",
    "досыпать ведро попкорна во время рекламы",
    "сделать попкорн-бар на день рождения",
    "заказать органические зёрна для попкорна онлайн",
    "приправить попкорн чесночным порошком",
    "взять миску для домашнего попкорна",
    "попкорн лучшая закуска для марафона сериалов",
    "надо пополнить запасы попкорна дома",
    "хрустеть попкорном во время учёбы",
    "карамельный попкорн из того магазина вызывает привыкание",
    "сделать попкорн с шоколадной глазурью на десерт",
    "пакеты попкорна на распродаже в супермаркете",
    "попокорн для киновечера",
    "попкрон в кинотеатре",
    "масляный попкрн на вечере",
    "микровлновый попкорн",
    "зёнра попкорна в кладовке",
],
de=[
    "Popcorn",
    "Butterpopcorn",
    "Kinosnack",
    "Karamellpopcorn",
    "Kino",
    "Filmsnack",
    "Maiskörner",
    "Mikrowellenpopcorn",
    "Salzpopcorn",
    "Popcorneimer",
    "Filmabend",
    "Snack",
    "Kinoimbiss",
    "Popcornmaschine",
    "Popcorntüte",
    "Käsepopcorn",
    "Popcorngewürz",
    "Kettle Corn",
    "Mikrowellenpopcorn für den Filmabend kaufen",
    "Popcorn machen bevor der Film anfängt",
    "großes Popcorn im Kino holen",
    "die Popcornmaschine braucht neue Körner",
    "extra Butter auf das Popcorn geben",
    "Karamellpopcorn im Laden kaufen",
    "Popcorn für den Schul-Kinotag mitbringen",
    "die neue Cheddar-Popcorn-Sorte probieren",
    "eine Tüte Popcorn für die Kinder machen",
    "das Popcorn ist wieder in der Mikrowelle verbrannt",
    "Popcorngewürz im Supermarkt kaufen",
    "einen Eimer Popcorn im Kino teilen",
    "Kettle Corn für die Party machen",
    "Mikrowellenpopcorn für die Woche eindecken",
    "Popcornmaschine nach dem Event reinigen",
    "Gourmet-Popcorn als Geschenk bestellen",
    "Popcorn ins Kino schmuggeln",
    "die Popcornkörner sind in der Speisekammer",
    "das Popcorn salzen solange es noch heiß ist",
    "eine Tüte Kino-Butterpopcorn kaufen",
    "einen Timer stellen damit das Popcorn nicht anbrennt",
    "geschmolzene Butter über das frische Popcorn gießen",
    "die ungeplatzten Körner am Boden wegwerfen",
    "heute Abend Popcorn auf dem Herd machen",
    "Popcorn und Süßigkeiten für den Familienfilm holen",
    "das Kinopopcorn riecht fantastisch",
    "den Popcorneimer in der Werbepause nachfüllen",
    "eine Popcorn-Bar für die Geburtstagsparty machen",
    "Bio-Popcornkörner online bestellen",
    "das Popcorn mit Knoblauchpulver würzen",
    "eine Schüssel für das selbstgemachte Popcorn holen",
    "Popcorn ist der beste Snack zum Serienschauen",
    "muss den Popcornvorrat zu Hause auffüllen",
    "beim Lernen Popcorn knabbern",
    "das Karamellpopcorn aus dem Laden macht süchtig",
    "Popcorn mit Schokoladenglasur als Nachtisch machen",
    "Popocorn für den Filmabend",
    "Popcron im Kino holen",
    "Buttrepopcorn Snack",
    "Mirkowellenpopcorn Tüte",
    "Maiskörner für Popcron",
],
ja=[
    "ポップコーン",
    "バターポップコーン",
    "映画のお菓子",
    "キャラメルポップコーン",
    "映画館",
    "シネマスナック",
    "コーンの粒",
    "電子レンジポップコーン",
    "塩ポップコーン",
    "ポップコーンバケツ",
    "映画の夜",
    "スナック",
    "映画館の売店",
    "ポップコーンマシン",
    "ポップコーンの袋",
    "チーズポップコーン",
    "ポップコーンの味付け",
    "ケトルコーン",
    "映画の夜のために電子レンジポップコーンを買う",
    "映画が始まる前にポップコーンを作る",
    "映画館で大きいポップコーンを買う",
    "ポップコーンマシンに新しい粒が必要",
    "ポップコーンにバターを多めにかける",
    "お店でキャラメルポップコーンを買ってくる",
    "学校の映画鑑賞日にポップコーンを持っていく",
    "新しいチェダー味のポップコーンを試す",
    "子供たちのためにポップコーンを作る",
    "ポップコーンがまた電子レンジで焦げた",
    "スーパーでポップコーンの調味料を買う",
    "映画館でポップコーンのバケツをシェアする",
    "パーティー用にケトルコーンを作る",
    "一週間分の電子レンジポップコーンを買いだめする",
    "イベント後にポップコーンマシンを掃除する",
    "グルメポップコーンをプレゼントに注文する",
    "映画館にポップコーンをこっそり持ち込む",
    "ポップコーンの粒はパントリーにある",
    "ポップコーンが熱いうちに塩をかける",
    "映画館バター味のポップコーンを一袋買う",
    "ポップコーンが焦げないようにタイマーをセットする",
    "できたてのポップコーンに溶かしバターをかける",
    "底に残ったはじけてない粒を捨てる",
    "今夜はコンロでポップコーンを作ってみる",
    "家族映画用にポップコーンとお菓子を買う",
    "映画館のポップコーンのにおいがすごくいい",
    "予告編の間にポップコーンをおかわりする",
    "誕生日パーティーにポップコーンバーを作る",
    "オーガニックポップコーンの粒をネットで注文する",
    "ガーリックパウダーでポップコーンに味をつける",
    "手作りポップコーン用のボウルを持ってくる",
    "一気見するならポップコーンが最高のお菓子",
    "家のポップコーンを補充しなきゃ",
    "勉強しながらポップコーンをつまむ",
    "あのお店のキャラメルポップコーンはやみつきになる",
    "デザートにチョコがけポップコーンを作る",
    "スーパーでポップコーンの袋がセール中",
    "ぽっぷこーん映画の夜",
    "ポプコーン映画館で",
    "ばたーポップコーン",
    "でんしレンジポップコーン",
    "キャラメルぽっぷこーん",
],
fr=[
    "popcorn",
    "popcorn au beurre",
    "snack de cinéma",
    "popcorn au caramel",
    "cinéma",
    "en-cas de film",
    "grains de maïs",
    "popcorn micro-ondes",
    "popcorn salé",
    "seau de popcorn",
    "soirée cinéma",
    "snack",
    "confiserie du cinéma",
    "machine à popcorn",
    "sachet de popcorn",
    "popcorn au fromage",
    "assaisonnement à popcorn",
    "maïs soufflé",
    "acheter du popcorn micro-ondes pour la soirée cinéma",
    "faire du popcorn avant que le film commence",
    "prendre un grand popcorn au cinéma",
    "la machine à popcorn a besoin de nouveaux grains",
    "mettre plus de beurre sur le popcorn",
    "acheter du popcorn au caramel au magasin",
    "apporter du popcorn pour la journée cinéma à l'école",
    "essayer le nouveau popcorn saveur cheddar",
    "faire un sachet de popcorn pour les enfants",
    "le popcorn a encore brûlé au micro-ondes",
    "acheter de l'assaisonnement à popcorn au supermarché",
    "partager un seau de popcorn au cinéma",
    "préparer du kettle corn pour la fête",
    "faire le plein de popcorn micro-ondes pour la semaine",
    "nettoyer la machine à popcorn après l'événement",
    "commander du popcorn gourmet en cadeau",
    "glisser du popcorn dans le cinéma en douce",
    "les grains de popcorn sont dans le garde-manger",
    "saler le popcorn tant qu'il est encore chaud",
    "acheter un sachet de popcorn au beurre façon cinéma",
    "mettre un minuteur pour ne pas brûler le popcorn",
    "verser du beurre fondu sur le popcorn frais",
    "jeter les grains non éclatés au fond",
    "essayer de faire du popcorn à la casserole ce soir",
    "acheter du popcorn et des bonbons pour le film en famille",
    "le popcorn du cinéma sent incroyablement bon",
    "remplir le seau de popcorn pendant les bandes-annonces",
    "faire un bar à popcorn pour la fête d'anniversaire",
    "commander des grains de popcorn bio en ligne",
    "assaisonner le popcorn avec de la poudre d'ail",
    "prendre un bol pour le popcorn maison",
    "le popcorn est le meilleur snack pour les marathons séries",
    "il faut refaire le stock de popcorn à la maison",
    "grignoter du popcorn en étudiant",
    "le popcorn au caramel de cette boutique rend accro",
    "faire du popcorn nappé de chocolat pour le dessert",
    "les sachets de popcorn sont en promo au supermarché",
    "popocorn pour la soirée",
    "popcron au cinéma",
    "popcorn au buerre",
    "mirco-ondes popcorn",
    "graisn de maïs pour popcorn",
],
es=[
    "palomitas",
    "palomitas con mantequilla",
    "snack de cine",
    "palomitas de caramelo",
    "cine",
    "botana de película",
    "granos de maíz",
    "palomitas de microondas",
    "palomitas saladas",
    "bote de palomitas",
    "noche de película",
    "botana",
    "dulcería del cine",
    "máquina de palomitas",
    "bolsa de palomitas",
    "palomitas con queso",
    "sazonador de palomitas",
    "maíz reventado",
    "comprar palomitas de microondas para la noche de película",
    "hacer palomitas antes de que empiece la película",
    "comprar unas palomitas grandes en el cine",
    "la máquina de palomitas necesita más granos",
    "ponerle más mantequilla a las palomitas",
    "comprar palomitas de caramelo en la tienda",
    "llevar palomitas al día de cine en la escuela",
    "probar las nuevas palomitas sabor cheddar",
    "hacer una bolsa de palomitas para los niños",
    "las palomitas se quemaron otra vez en el microondas",
    "comprar sazonador de palomitas en el supermercado",
    "compartir un bote de palomitas en el cine",
    "preparar kettle corn para la fiesta",
    "abastecer palomitas de microondas para la semana",
    "limpiar la máquina de palomitas después del evento",
    "pedir palomitas gourmet como regalo",
    "meter palomitas al cine a escondidas",
    "los granos de palomitas están en la despensa",
    "echar sal a las palomitas mientras están calientes",
    "comprar una bolsa de palomitas con sabor a cine",
    "poner un temporizador para que no se quemen las palomitas",
    "verter mantequilla derretida sobre las palomitas frescas",
    "tirar los granos que no reventaron del fondo",
    "intentar hacer palomitas en la estufa esta noche",
    "comprar palomitas y dulces para la película en familia",
    "las palomitas del cine huelen increíble",
    "rellenar el bote de palomitas durante los tráileres",
    "hacer un bar de palomitas para la fiesta de cumpleaños",
    "pedir granos orgánicos para palomitas por internet",
    "sazonar las palomitas con ajo en polvo",
    "traer un tazón para las palomitas caseras",
    "las palomitas son el mejor snack para maratones de series",
    "necesito reabastecer las palomitas en casa",
    "comer palomitas mientras estudio",
    "las palomitas de caramelo de esa tienda son adictivas",
    "hacer palomitas con chocolate derretido de postre",
    "las bolsas de palomitas están de oferta en el súper",
    "palomoitas para la noche de cine",
    "palomtas en el cine",
    "mantquilla en las palomitas",
    "micorondas palomitas",
    "garanos de maíz para palomitas",
])


# ── popsicle ──────────────────────────────────────────────────────────────────
gen("popsicle",
en=[
    "popsicle",
    "ice pop",
    "frozen treat",
    "ice cream bar",
    "summer treat",
    "frozen dessert",
    "fruit bar",
    "ice lolly",
    "popsicle stick",
    "frozen fruit pop",
    "fudge bar",
    "creamsicle",
    "freeze pop",
    "sherbet bar",
    "frozen snack",
    "twin pop",
    "fruit popsicle",
    "homemade popsicle",
    "buy popsicles for the kids at the store",
    "make homemade popsicles with fresh fruit",
    "the popsicles are melting in the freezer bag",
    "stock the freezer with popsicles for summer",
    "try the new mango popsicle flavor",
    "grab a popsicle from the freezer after lunch",
    "bring popsicles to the pool party",
    "the kids want popsicles after soccer practice",
    "buy popsicle molds for homemade ice pops",
    "freeze the leftover juice into popsicles",
    "pick up a box of fudge bars at the grocery store",
    "the ice cream truck has the best popsicles",
    "make coconut milk popsicles for the dairy-free guests",
    "popsicle sticks for the craft project at school",
    "the strawberry popsicles sold out at the store",
    "put the popsicles back before they melt",
    "try making yogurt popsicles with berries",
    "buy sugar-free popsicles for the diet",
    "the popsicle dripped all over my shirt",
    "order popsicle molds online",
    "freeze the smoothie into popsicle shapes",
    "bring frozen treats to the summer barbecue",
    "the grape popsicle stained the tablecloth",
    "stock up on creamsicles for the weekend",
    "need popsicles for the kids' birthday party",
    "make watermelon popsicles for the Fourth of July",
    "the frozen fruit bars are in the bottom drawer",
    "get popsicles from the corner store on the way home",
    "popsicles are the best treat on a hot day",
    "blend fresh mango and freeze it into popsicles",
    "the kids ate all the popsicles already",
    "buy a variety pack of ice pops for the summer",
    "make chocolate-dipped popsicles for dessert",
    "popsicle melitng in summer heat",
    "forzen treat on a stick",
    "frozn fruit bar from the store",
    "popsicl molds for homemade",
    "ice crem bar for kids",
],
ru=[
    "эскимо",
    "фруктовый лёд",
    "замороженное лакомство",
    "мороженое на палочке",
    "летнее угощение",
    "замороженный десерт",
    "фруктовый батончик",
    "ледяная конфета",
    "палочка от мороженого",
    "фруктовое мороженое",
    "шоколадный батончик",
    "пломбир на палочке",
    "ледяной поп",
    "щербет на палочке",
    "замороженная закуска",
    "двойное мороженое",
    "фруктовое эскимо",
    "домашнее мороженое на палочке",
    "купить мороженое на палочке детям в магазине",
    "сделать домашнее мороженое из свежих фруктов",
    "мороженое тает в сумке-холодильнике",
    "заполнить морозилку мороженым на лето",
    "попробовать новый манговый вкус эскимо",
    "взять мороженое из морозилки после обеда",
    "принести мороженое на вечеринку у бассейна",
    "дети хотят мороженое после футбольной тренировки",
    "купить формочки для домашнего фруктового льда",
    "заморозить оставшийся сок в формочках для эскимо",
    "купить коробку шоколадных батончиков в продуктовом",
    "у фургона мороженщика самое вкусное эскимо",
    "сделать кокосовое мороженое для тех кто без лактозы",
    "палочки от мороженого для поделок в школе",
    "клубничное мороженое раскупили в магазине",
    "убрать мороженое обратно пока не растаяло",
    "попробовать сделать йогуртовое мороженое с ягодами",
    "купить мороженое без сахара для диеты",
    "мороженое капнуло на всю рубашку",
    "заказать формочки для мороженого онлайн",
    "заморозить смузи в форме эскимо",
    "принести замороженные угощения на летний барбекю",
    "виноградное эскимо оставило пятно на скатерти",
    "запастись пломбиром на выходные",
    "нужно мороженое на детский день рождения",
    "сделать арбузное мороженое на День независимости",
    "фруктовые батончики в нижнем ящике морозилки",
    "купить мороженое в магазине на углу по дороге домой",
    "эскимо лучшее лакомство в жаркий день",
    "взбить свежее манго и заморозить в формочках",
    "дети уже съели всё мороженое",
    "купить набор разных эскимо на лето",
    "сделать мороженое в шоколаде на десерт",
    "эскмио тает на летнем солнце",
    "замрозженное лакомство на палочке",
    "фрутковый лёд из магазина",
    "формчоки для домашнего мороженого",
    "морожное на палочке для детей",
],
de=[
    "Eis am Stiel",
    "Fruchteis",
    "gefrorenes Leckerli",
    "Eiscreme-Riegel",
    "Sommergenuss",
    "gefrorenes Dessert",
    "Fruchtriegel",
    "Wassereis",
    "Holzstiel vom Eis",
    "gefrorenes Fruchteis",
    "Schokoeis am Stiel",
    "Sahneeis am Stiel",
    "Eislutscher",
    "Sorbet am Stiel",
    "gefrorener Snack",
    "Doppeleis am Stiel",
    "Frucht-Popsicle",
    "selbstgemachtes Eis am Stiel",
    "Eis am Stiel für die Kinder im Laden kaufen",
    "selbstgemachtes Eis mit frischem Obst machen",
    "das Eis schmilzt in der Kühltasche",
    "den Gefrierschrank mit Eis am Stiel für den Sommer füllen",
    "die neue Mango-Eis-Sorte probieren",
    "nach dem Mittagessen ein Eis aus dem Gefrierschrank holen",
    "Eis am Stiel zur Pool-Party mitbringen",
    "die Kinder wollen Eis nach dem Fußballtraining",
    "Eisformen für selbstgemachtes Fruchteis kaufen",
    "den übrigen Saft zu Eis am Stiel einfrieren",
    "eine Packung Schokoeis-Riegel im Supermarkt kaufen",
    "der Eiswagen hat das beste Eis am Stiel",
    "Kokosmilch-Eis für laktosefreie Gäste machen",
    "Holzstiele für das Bastelprojekt in der Schule",
    "das Erdbeereis war im Laden ausverkauft",
    "das Eis wieder zurücklegen bevor es schmilzt",
    "Joghurt-Eis mit Beeren ausprobieren",
    "zuckerfreies Eis am Stiel für die Diät kaufen",
    "das Eis hat auf mein ganzes Hemd getropft",
    "Eisformen online bestellen",
    "den Smoothie in Eisform einfrieren",
    "gefrorene Leckereien zum Sommer-Grillfest mitbringen",
    "das Traubeneis hat Flecken auf der Tischdecke hinterlassen",
    "Sahneeis für das Wochenende eindecken",
    "brauche Eis am Stiel für den Kindergeburtstag",
    "Wassermeloneneis zum Nationalfeiertag machen",
    "die Fruchtriegel sind in der unteren Schublade",
    "auf dem Heimweg Eis am Kiosk holen",
    "Eis am Stiel ist das beste an heißen Tagen",
    "frische Mango pürieren und zu Eis einfrieren",
    "die Kinder haben schon alles Eis aufgegessen",
    "eine Mischpackung Eis am Stiel für den Sommer kaufen",
    "Eis mit Schokoüberzug als Nachtisch machen",
    "Eis am Steil schmilzt in der Hitze",
    "geforenes Leckerli am Stiel",
    "Fruchties aus dem Laden",
    "Eisfomen für selbstgemachtes",
    "Eiscrem-Riegel für Kinder",
],
ja=[
    "アイスキャンディー",
    "アイスバー",
    "冷たいおやつ",
    "アイスクリームバー",
    "夏のおやつ",
    "フローズンデザート",
    "フルーツバー",
    "アイスポップ",
    "アイスの棒",
    "フローズンフルーツバー",
    "チョコバー",
    "クリームアイスバー",
    "フリーズポップ",
    "シャーベットバー",
    "冷凍スナック",
    "ツインアイス",
    "フルーツアイスキャンディー",
    "手作りアイスキャンディー",
    "子供用にお店でアイスキャンディーを買う",
    "新鮮なフルーツで手作りアイスキャンディーを作る",
    "保冷バッグの中でアイスが溶けている",
    "夏に向けて冷凍庫をアイスキャンディーでいっぱいにする",
    "新しいマンゴー味のアイスバーを試す",
    "お昼の後に冷凍庫からアイスを取る",
    "プールパーティーにアイスキャンディーを持っていく",
    "子供たちがサッカーの練習後にアイスを欲しがる",
    "手作りフルーツアイス用の型を買う",
    "残ったジュースをアイスキャンディーの型で凍らせる",
    "スーパーでチョコバーを一箱買う",
    "アイスクリームの移動販売車のアイスが一番おいしい",
    "乳製品が食べられないゲスト用にココナッツアイスを作る",
    "学校の工作用にアイスの棒を使う",
    "いちごのアイスキャンディーがお店で売り切れだった",
    "溶ける前にアイスを冷凍庫に戻す",
    "ベリー入りヨーグルトアイスを作ってみる",
    "ダイエット用に砂糖なしのアイスバーを買う",
    "アイスがシャツ全体にたれた",
    "アイスキャンディーの型をオンラインで注文する",
    "スムージーをアイスの形に凍らせる",
    "夏のバーベキューに冷凍おやつを持っていく",
    "ぶどうアイスがテーブルクロスにシミをつけた",
    "週末用にクリームバーを買いだめする",
    "子供の誕生日パーティーにアイスが必要",
    "独立記念日にスイカアイスを作る",
    "フルーツバーは冷凍庫の下の引き出しにある",
    "帰り道に角のお店でアイスを買う",
    "暑い日にはアイスキャンディーが一番",
    "新鮮なマンゴーをミキサーにかけて凍らせる",
    "子供たちがもうアイスを全部食べてしまった",
    "夏用にアイスバーのバラエティパックを買う",
    "デザートにチョコがけアイスキャンディーを作る",
    "アイスキャンデーが夏の暑さで溶ける",
    "れいとうおやつ棒つき",
    "フルーツばー店で買う",
    "アイスのかた手作り用",
    "アイスくりーむバー子供用",
    "てづくりアイスキャンディ",
],
fr=[
    "esquimau",
    "sucette glacée",
    "gourmandise glacée",
    "barre de glace",
    "friandise d'été",
    "dessert glacé",
    "barre fruitée",
    "glace à l'eau",
    "bâtonnet de glace",
    "glace aux fruits",
    "barre au chocolat glacée",
    "crème glacée en bâtonnet",
    "glace en tube",
    "sorbet en bâtonnet",
    "snack glacé",
    "glace double bâtonnet",
    "esquimau aux fruits",
    "glace maison en bâtonnet",
    "acheter des esquimaux pour les enfants au magasin",
    "faire des glaces maison avec des fruits frais",
    "les glaces fondent dans le sac isotherme",
    "remplir le congélateur de glaces pour l'été",
    "essayer le nouveau parfum mangue en esquimau",
    "prendre une glace dans le congélateur après le déjeuner",
    "apporter des esquimaux à la fête de la piscine",
    "les enfants veulent des glaces après le foot",
    "acheter des moules à esquimaux pour la glace maison",
    "congeler le jus restant en esquimaux",
    "acheter une boîte de barres chocolatées au supermarché",
    "le camion de glaces a les meilleurs esquimaux",
    "faire des glaces au lait de coco pour les invités sans lactose",
    "bâtonnets de glace pour le projet de bricolage à l'école",
    "les esquimaux à la fraise étaient en rupture de stock",
    "remettre les glaces avant qu'elles ne fondent",
    "essayer de faire des glaces au yaourt avec des baies",
    "acheter des esquimaux sans sucre pour le régime",
    "la glace a coulé partout sur ma chemise",
    "commander des moules à esquimaux en ligne",
    "congeler le smoothie en forme d'esquimaux",
    "apporter des friandises glacées au barbecue d'été",
    "l'esquimau au raisin a taché la nappe",
    "faire le plein de crèmes glacées pour le week-end",
    "il faut des esquimaux pour l'anniversaire des enfants",
    "faire des glaces à la pastèque pour le 14 juillet",
    "les barres fruitées sont dans le tiroir du bas",
    "acheter des glaces à l'épicerie en rentrant",
    "les esquimaux sont le meilleur régal par temps chaud",
    "mixer de la mangue fraîche et la congeler en esquimaux",
    "les enfants ont déjà mangé toutes les glaces",
    "acheter un assortiment de glaces pour l'été",
    "faire des esquimaux enrobés de chocolat pour le dessert",
    "esquimau fondant sous la chaluer d'été",
    "gourmandise glacé sur un bâton",
    "barre frutée du magasin",
    "moules à esqimaux maison",
    "barre de glace pour enfnats",
],
es=[
    "paleta helada",
    "paleta de hielo",
    "golosina congelada",
    "barra de helado",
    "antojo de verano",
    "postre congelado",
    "barra de fruta congelada",
    "helado de agua",
    "palito de paleta",
    "paleta de fruta",
    "paleta de chocolate",
    "paleta de crema",
    "bolis helado",
    "paleta de sorbete",
    "snack congelado",
    "paleta doble",
    "paleta frutal",
    "paleta casera",
    "comprar paletas heladas para los niños en la tienda",
    "hacer paletas caseras con fruta fresca",
    "las paletas se están derritiendo en la bolsa térmica",
    "llenar el congelador de paletas para el verano",
    "probar el nuevo sabor de paleta de mango",
    "sacar una paleta del congelador después del almuerzo",
    "llevar paletas heladas a la fiesta en la alberca",
    "los niños quieren paletas después del entrenamiento de fútbol",
    "comprar moldes para paletas caseras de fruta",
    "congelar el jugo sobrante en forma de paletas",
    "comprar una caja de barras de chocolate helado en el súper",
    "el carrito de helados tiene las mejores paletas",
    "hacer paletas de leche de coco para los intolerantes a la lactosa",
    "palitos de paleta para el proyecto de manualidades en la escuela",
    "las paletas de fresa se agotaron en la tienda",
    "regresar las paletas al congelador antes de que se derritan",
    "intentar hacer paletas de yogur con fresas",
    "comprar paletas sin azúcar para la dieta",
    "la paleta se derritió por toda mi camisa",
    "pedir moldes para paletas por internet",
    "congelar el smoothie en forma de paletas",
    "llevar golosinas congeladas a la carne asada de verano",
    "la paleta de uva manchó el mantel",
    "comprar paletas de crema para el fin de semana",
    "necesitamos paletas para la fiesta de cumpleaños de los niños",
    "hacer paletas de sandía para las fiestas patrias",
    "las barras de fruta están en el cajón de abajo del congelador",
    "comprar paletas en la tiendita de camino a casa",
    "las paletas heladas son lo mejor en un día caluroso",
    "licuar mango fresco y congelarlo en moldes de paleta",
    "los niños ya se comieron todas las paletas",
    "comprar un paquete variado de paletas para el verano",
    "hacer paletas cubiertas de chocolate de postre",
    "paleta derrtiéndose en el calor",
    "golosnia congelada en palito",
    "barra de fruta congealda",
    "moleds para paletas caseras",
    "helado de aua para niños",
])


# ── power-off ─────────────────────────────────────────────────────────────────
gen("power-off",
en=[
    "power off",
    "shut down",
    "turn off",
    "restart",
    "reboot",
    "power button",
    "off switch",
    "close",
    "exit",
    "log off",
    "sleep mode",
    "hibernate",
    "force quit",
    "power cycle",
    "standby",
    "shutdown timer",
    "turn off computer",
    "restart device",
    "shut down the computer before leaving the office",
    "power off the monitor when done for the day",
    "restart the laptop to install the updates",
    "reboot the router if the internet is slow",
    "turn off the TV before going to bed",
    "force quit the app that keeps freezing",
    "set the computer to sleep mode during lunch",
    "shut down all devices before the power outage",
    "power off the printer when not in use",
    "restart the phone to fix the glitch",
    "turn off the lights when leaving the room",
    "close all programs before shutting down",
    "the computer needs to restart after the update",
    "hold the power button to force restart",
    "exit the app and turn off the tablet",
    "power cycle the modem to fix connectivity",
    "set a shutdown timer for the kids' computer",
    "log off and shut down the work laptop",
    "hibernate the laptop to save battery",
    "turn off the gaming console after playing",
    "reboot the server during the maintenance window",
    "the computer froze so I need to force restart",
    "shut down the desktop before the weekend",
    "turn off the smart speaker at night",
    "power off the projector after the presentation",
    "restart the app to clear the error",
    "close the laptop lid to put it to sleep",
    "switch off the office lights before locking up",
    "the phone won't power off properly",
    "schedule a restart for the server tonight",
    "turn off notifications before the meeting",
    "shut down the old computer and pack it up",
    "power off the external hard drive safely",
    "need to restart the WiFi router again",
    "the tablet won't turn off with the button",
    "powr off the computer",
    "shutdwon and restart",
    "restat the router",
    "trun off the monitor",
    "reeboot the server",
],
ru=[
    "выключить",
    "завершение работы",
    "отключить",
    "перезагрузка",
    "перезапуск",
    "кнопка питания",
    "выключатель",
    "закрыть",
    "выйти",
    "выход из системы",
    "режим сна",
    "гибернация",
    "принудительное завершение",
    "перезагрузка питания",
    "режим ожидания",
    "таймер выключения",
    "выключить компьютер",
    "перезагрузить устройство",
    "выключить компьютер перед уходом из офиса",
    "выключить монитор по окончании рабочего дня",
    "перезагрузить ноутбук для установки обновлений",
    "перезагрузить роутер если интернет медленный",
    "выключить телевизор перед сном",
    "принудительно закрыть зависшее приложение",
    "перевести компьютер в режим сна на обед",
    "выключить все устройства перед отключением электричества",
    "выключить принтер когда не используется",
    "перезагрузить телефон чтобы исправить сбой",
    "выключить свет уходя из комнаты",
    "закрыть все программы перед выключением",
    "компьютер нужно перезагрузить после обновления",
    "удерживать кнопку питания для принудительной перезагрузки",
    "выйти из приложения и выключить планшет",
    "перезагрузить модем для исправления связи",
    "поставить таймер выключения на детском компьютере",
    "выйти из системы и выключить рабочий ноутбук",
    "перевести ноутбук в гибернацию для экономии батареи",
    "выключить игровую приставку после игры",
    "перезагрузить сервер в окне обслуживания",
    "компьютер завис нужно принудительно перезагрузить",
    "выключить настольный компьютер перед выходными",
    "выключить умную колонку на ночь",
    "выключить проектор после презентации",
    "перезапустить приложение чтобы убрать ошибку",
    "закрыть крышку ноутбука чтобы усыпить его",
    "выключить свет в офисе перед уходом",
    "телефон не выключается нормально",
    "запланировать перезагрузку сервера на сегодня ночью",
    "отключить уведомления перед совещанием",
    "выключить старый компьютер и упаковать",
    "безопасно извлечь внешний жёсткий диск",
    "опять надо перезагрузить WiFi роутер",
    "планшет не выключается кнопкой",
    "выклчюить компьютер",
    "завершние работы и перезагрузка",
    "перезгарузить роутер",
    "отклчюить монитор",
    "перезпуск сервера",
],
de=[
    "ausschalten",
    "herunterfahren",
    "abschalten",
    "Neustart",
    "neu starten",
    "Ein-Aus-Taste",
    "Ausschalter",
    "schließen",
    "beenden",
    "abmelden",
    "Ruhemodus",
    "Ruhezustand",
    "erzwungenes Beenden",
    "Stromzyklus",
    "Standby",
    "Abschalttimer",
    "Computer ausschalten",
    "Gerät neu starten",
    "den Computer vor dem Verlassen des Büros herunterfahren",
    "den Monitor am Ende des Tages ausschalten",
    "den Laptop neu starten um Updates zu installieren",
    "den Router neu starten wenn das Internet langsam ist",
    "den Fernseher vor dem Schlafengehen ausschalten",
    "die eingefrorene App erzwungen beenden",
    "den Computer in der Mittagspause in den Ruhemodus setzen",
    "alle Geräte vor dem Stromausfall ausschalten",
    "den Drucker ausschalten wenn er nicht benutzt wird",
    "das Handy neu starten um den Fehler zu beheben",
    "das Licht beim Verlassen des Raumes ausschalten",
    "alle Programme vor dem Herunterfahren schließen",
    "der Computer muss nach dem Update neu starten",
    "die Ein-Aus-Taste gedrückt halten für erzwungenen Neustart",
    "die App beenden und das Tablet ausschalten",
    "das Modem aus- und einschalten um die Verbindung zu reparieren",
    "einen Abschalttimer für den Kindercomputer einstellen",
    "sich abmelden und den Arbeitslaptop herunterfahren",
    "den Laptop in den Ruhezustand versetzen um Akku zu sparen",
    "die Spielkonsole nach dem Spielen ausschalten",
    "den Server im Wartungsfenster neu starten",
    "der Computer ist eingefroren ich muss neu starten erzwingen",
    "den Desktop vor dem Wochenende herunterfahren",
    "den Smart-Lautsprecher nachts ausschalten",
    "den Beamer nach der Präsentation ausschalten",
    "die App neu starten um den Fehler zu beheben",
    "den Laptopdeckel schließen um ihn in den Ruhemodus zu setzen",
    "das Bürolicht vor dem Abschließen ausschalten",
    "das Handy lässt sich nicht richtig ausschalten",
    "einen Neustart für den Server heute Nacht planen",
    "Benachrichtigungen vor dem Meeting ausschalten",
    "den alten Computer ausschalten und einpacken",
    "die externe Festplatte sicher auswerfen",
    "muss den WLAN-Router wieder neu starten",
    "das Tablet lässt sich mit dem Knopf nicht ausschalten",
    "Compter ausschalten",
    "herunterfahen und Neustart",
    "Routr neu starten",
    "Monitr ausschalten",
    "Sever neu starten",
],
ja=[
    "電源を切る",
    "シャットダウン",
    "オフにする",
    "再起動",
    "リブート",
    "電源ボタン",
    "オフスイッチ",
    "閉じる",
    "終了する",
    "ログオフ",
    "スリープモード",
    "休止状態",
    "強制終了",
    "電源サイクル",
    "スタンバイ",
    "シャットダウンタイマー",
    "パソコンの電源を切る",
    "デバイスを再起動する",
    "退社前にパソコンをシャットダウンする",
    "仕事が終わったらモニターの電源を切る",
    "アップデートをインストールするためにノートパソコンを再起動する",
    "ネットが遅いならルーターを再起動する",
    "寝る前にテレビを消す",
    "フリーズしたアプリを強制終了する",
    "昼休みにパソコンをスリープモードにする",
    "停電前にすべてのデバイスの電源を切る",
    "使わないときはプリンターの電源を切る",
    "不具合を直すためにスマホを再起動する",
    "部屋を出るときに電気を消す",
    "シャットダウンの前にすべてのプログラムを閉じる",
    "アップデート後にパソコンの再起動が必要",
    "電源ボタンを長押しして強制再起動する",
    "アプリを終了してタブレットの電源を切る",
    "接続を直すためにモデムの電源を入れ直す",
    "子供のパソコンにシャットダウンタイマーを設定する",
    "ログオフして仕事用ノートパソコンをシャットダウンする",
    "バッテリー節約のためにノートパソコンを休止状態にする",
    "遊び終わったらゲーム機の電源を切る",
    "メンテナンス時間中にサーバーを再起動する",
    "パソコンがフリーズしたので強制再起動が必要",
    "週末前にデスクトップをシャットダウンする",
    "夜はスマートスピーカーの電源を切る",
    "プレゼンの後にプロジェクターの電源を切る",
    "エラーを消すためにアプリを再起動する",
    "ノートパソコンの蓋を閉じてスリープにする",
    "鍵をかける前にオフィスの電気を消す",
    "スマホが正常に電源オフできない",
    "今夜サーバーの再起動をスケジュールする",
    "会議の前に通知をオフにする",
    "古いパソコンの電源を切って梱包する",
    "外付けハードドライブを安全に取り外す",
    "またWiFiルーターを再起動しなきゃ",
    "タブレットがボタンで電源オフできない",
    "でんげんを切る",
    "しゃっとだうんと再起動",
    "るーたーを再起動",
    "もにたーの電源オフ",
    "さーばー再起動",
],
fr=[
    "éteindre",
    "arrêter",
    "couper",
    "redémarrer",
    "redémarrage",
    "bouton d'alimentation",
    "interrupteur",
    "fermer",
    "quitter",
    "se déconnecter",
    "mode veille",
    "hibernation",
    "forcer la fermeture",
    "cycle d'alimentation",
    "mise en veille",
    "minuterie d'arrêt",
    "éteindre l'ordinateur",
    "redémarrer l'appareil",
    "éteindre l'ordinateur avant de quitter le bureau",
    "éteindre l'écran à la fin de la journée",
    "redémarrer le portable pour installer les mises à jour",
    "redémarrer le routeur si internet est lent",
    "éteindre la télé avant d'aller au lit",
    "forcer la fermeture de l'appli qui plante",
    "mettre l'ordinateur en veille pendant la pause déjeuner",
    "éteindre tous les appareils avant la coupure de courant",
    "éteindre l'imprimante quand elle ne sert pas",
    "redémarrer le téléphone pour corriger le bug",
    "éteindre la lumière en quittant la pièce",
    "fermer tous les programmes avant d'éteindre",
    "l'ordinateur doit redémarrer après la mise à jour",
    "maintenir le bouton d'alimentation pour forcer le redémarrage",
    "quitter l'appli et éteindre la tablette",
    "redémarrer le modem pour résoudre le problème de connexion",
    "programmer une minuterie d'arrêt sur l'ordinateur des enfants",
    "se déconnecter et éteindre le portable de travail",
    "mettre le portable en hibernation pour économiser la batterie",
    "éteindre la console de jeux après avoir joué",
    "redémarrer le serveur pendant la fenêtre de maintenance",
    "l'ordinateur a planté je dois forcer le redémarrage",
    "éteindre le PC de bureau avant le week-end",
    "éteindre l'enceinte connectée la nuit",
    "éteindre le vidéoprojecteur après la présentation",
    "redémarrer l'appli pour effacer l'erreur",
    "fermer le capot du portable pour le mettre en veille",
    "éteindre les lumières du bureau avant de verrouiller",
    "le téléphone ne s'éteint pas correctement",
    "planifier un redémarrage du serveur pour ce soir",
    "couper les notifications avant la réunion",
    "éteindre le vieil ordinateur et le ranger",
    "éjecter le disque dur externe en toute sécurité",
    "il faut encore redémarrer le routeur WiFi",
    "la tablette ne s'éteint pas avec le bouton",
    "étiendre l'ordinateur",
    "arrêtr et redémarrer",
    "redémarrer le routuer",
    "éteindre le monituer",
    "redémarrge du serveur",
],
es=[
    "apagar",
    "cerrar sesión",
    "apagar el equipo",
    "reiniciar",
    "reinicio",
    "botón de encendido",
    "interruptor",
    "cerrar",
    "salir",
    "cerrar sesión",
    "modo suspensión",
    "hibernación",
    "forzar cierre",
    "ciclo de encendido",
    "modo espera",
    "temporizador de apagado",
    "apagar la computadora",
    "reiniciar el dispositivo",
    "apagar la computadora antes de salir de la oficina",
    "apagar el monitor al terminar el día",
    "reiniciar la laptop para instalar las actualizaciones",
    "reiniciar el router si el internet está lento",
    "apagar la tele antes de acostarse",
    "forzar el cierre de la app que se congela",
    "poner la computadora en modo suspensión durante el almuerzo",
    "apagar todos los dispositivos antes del apagón",
    "apagar la impresora cuando no se esté usando",
    "reiniciar el celular para arreglar la falla",
    "apagar las luces al salir del cuarto",
    "cerrar todos los programas antes de apagar",
    "la computadora necesita reiniciarse después de la actualización",
    "mantener presionado el botón de encendido para forzar reinicio",
    "salir de la app y apagar la tableta",
    "reiniciar el módem para arreglar la conexión",
    "poner un temporizador de apagado en la computadora de los niños",
    "cerrar sesión y apagar la laptop del trabajo",
    "poner la laptop en hibernación para ahorrar batería",
    "apagar la consola de juegos después de jugar",
    "reiniciar el servidor durante la ventana de mantenimiento",
    "la computadora se congeló y necesito forzar el reinicio",
    "apagar la computadora de escritorio antes del fin de semana",
    "apagar la bocina inteligente en la noche",
    "apagar el proyector después de la presentación",
    "reiniciar la app para quitar el error",
    "cerrar la tapa de la laptop para ponerla a dormir",
    "apagar las luces de la oficina antes de cerrar con llave",
    "el celular no se apaga correctamente",
    "programar un reinicio del servidor para esta noche",
    "desactivar las notificaciones antes de la junta",
    "apagar la computadora vieja y guardarla",
    "extraer de forma segura el disco duro externo",
    "otra vez hay que reiniciar el router WiFi",
    "la tableta no se apaga con el botón",
    "aapgar la computadora",
    "apagar y reinciar",
    "reinicar el router",
    "apaagr el monitor",
    "reincio del servidor",
])

print("\n=== Part 2 done (popcorn, popsicle, power-off) ===")
