#!/usr/bin/env python3
"""Task-003 part C: piano, pickaxe, pig."""

from gen_icons_task_006_common import build_icon

# ── PIANO ────────────────────────────────────────────────────────────────────
build_icon("piano", {
    "en": [
        "piano", "keyboard", "keys", "music", "instrument",
        "play piano", "grand piano", "upright piano", "digital piano",
        "piano lesson", "piano practice", "recital", "sheet music",
        "piano teacher", "piano tuner", "concert piano",
        "MIDI keyboard", "piano keys",
        "practice piano for thirty minutes",
        "schedule a piano lesson for Tuesday",
        "buy sheet music for the piano recital",
        "tune the piano before the concert",
        "learn a new song on the piano",
        "set up the digital piano in the room",
        "play piano after dinner",
        "sign up for piano lessons this month",
        "find a piano teacher for the kids",
        "move the upright piano to the living room",
        "record a piano piece on my phone",
        "buy a piano bench for the new keyboard",
        "practice scales on the piano every day",
        "attend the piano recital at the school",
        "fix the broken piano key",
        "order a piano tuning appointment",
        "download piano sheet music online",
        "clean the piano keys with a soft cloth",
        "choose a piano song for the talent show",
        "play the piano at the community center",
        "save up to buy a grand piano",
        "install the piano app on the tablet",
        "review the piano lesson notes before practice",
        "accompany the singer on the piano",
        "warm up with finger exercises on the piano",
        "bring the keyboard to the rehearsal",
        "replace the worn piano pedal",
        "listen to a piano concert recording",
        "register for the piano competition",
        "set a daily reminder to practice piano",
        "study music theory for piano class",
        "connect the MIDI keyboard to the computer",
        "decorate the piano room for the recital",
        "give a piano performance at the party",
        "adjust the piano stool height",
        "paino practice after school",
        "keybord instrument lessons",
        "pian music for the recital",
        "practce scales on the piano",
        "piano tunning appointment",
    ],
    "ru": [
        "фортепиано", "клавиатура", "клавиши", "музыка", "инструмент",
        "играть на пианино", "рояль", "вертикальное пианино", "цифровое пианино",
        "урок фортепиано", "практика на пианино", "концерт", "ноты",
        "учитель фортепиано", "настройщик пианино", "концертный рояль",
        "MIDI-клавиатура", "клавиши пианино",
        "практиковаться на пианино тридцать минут",
        "назначить урок фортепиано на вторник",
        "купить ноты для концерта на пианино",
        "настроить пианино перед концертом",
        "выучить новую песню на пианино",
        "установить цифровое пианино в комнате",
        "поиграть на пианино после ужина",
        "записаться на уроки фортепиано в этом месяце",
        "найти учителя фортепиано для детей",
        "перенести пианино в гостиную",
        "записать фортепианную пьесу на телефон",
        "купить банкетку для нового пианино",
        "ежедневно практиковать гаммы на пианино",
        "посетить концерт фортепиано в школе",
        "починить сломанную клавишу пианино",
        "записаться на настройку пианино",
        "скачать ноты для пианино онлайн",
        "протереть клавиши пианино мягкой тканью",
        "выбрать пьесу для пианино на конкурс талантов",
        "поиграть на пианино в общественном центре",
        "накопить на покупку рояля",
        "установить приложение для пианино на планшет",
        "повторить конспект урока фортепиано перед практикой",
        "аккомпанировать певцу на пианино",
        "размять пальцы упражнениями на пианино",
        "принести клавиатуру на репетицию",
        "заменить изношенную педаль пианино",
        "послушать запись фортепианного концерта",
        "зарегистрироваться на конкурс фортепиано",
        "поставить ежедневное напоминание практиковаться на пианино",
        "изучать теорию музыки для урока фортепиано",
        "подключить MIDI-клавиатуру к компьютеру",
        "украсить комнату с пианино к концерту",
        "сыграть на пианино на вечеринке",
        "отрегулировать высоту стула у пианино",
        "практика на пинаио после школы",
        "уроки клваишных инструментов",
        "фортепинано музыка для концерта",
        "гамы на пианино практика",
        "настойка пианино запись",
    ],
    "de": [
        "Klavier", "Tastatur", "Tasten", "Musik", "Instrument",
        "Klavier spielen", "Flügel", "Klavier aufrecht", "Digitalpiano",
        "Klavierstunde", "Klavierübung", "Konzert", "Noten",
        "Klavierlehrer", "Klavierstimmer", "Konzertflügel",
        "MIDI-Keyboard", "Klaviertasten",
        "dreißig Minuten Klavier üben",
        "eine Klavierstunde für Dienstag planen",
        "Noten für das Klavierkonzert kaufen",
        "das Klavier vor dem Konzert stimmen lassen",
        "ein neues Lied auf dem Klavier lernen",
        "das Digitalpiano im Zimmer aufstellen",
        "nach dem Abendessen Klavier spielen",
        "sich diesen Monat für Klavierstunden anmelden",
        "einen Klavierlehrer für die Kinder finden",
        "das Klavier ins Wohnzimmer stellen",
        "ein Klavierstück auf dem Handy aufnehmen",
        "eine Klavierbank für das neue Keyboard kaufen",
        "jeden Tag Tonleitern auf dem Klavier üben",
        "das Klavierkonzert in der Schule besuchen",
        "die kaputte Klaviertaste reparieren",
        "einen Termin zum Klavierstimmen vereinbaren",
        "Klaviernoten online herunterladen",
        "die Klaviertasten mit einem weichen Tuch reinigen",
        "ein Klavierstück für die Talentshow wählen",
        "im Gemeindezentrum Klavier spielen",
        "auf einen Flügel sparen",
        "die Klavier-App auf dem Tablet installieren",
        "die Notizen der Klavierstunde vor dem Üben durchgehen",
        "den Sänger am Klavier begleiten",
        "mit Fingerübungen am Klavier aufwärmen",
        "das Keyboard zur Probe mitbringen",
        "das abgenutzte Klavierpedal ersetzen",
        "eine Aufnahme eines Klavierkonzerts anhören",
        "sich für den Klavierwettbewerb anmelden",
        "eine tägliche Erinnerung zum Klavierüben stellen",
        "Musiktheorie für den Klavierunterricht lernen",
        "das MIDI-Keyboard mit dem Computer verbinden",
        "das Klavierzimmer für das Konzert dekorieren",
        "auf der Party Klavier vorspielen",
        "die Höhe des Klavierhockers einstellen",
        "Klavir üben nach der Schule",
        "Tastatru Instrument Unterricht",
        "Klaveir Musik für das Konzert",
        "Tonleitrn auf dem Klavier üben",
        "Klavierstimmung Termni",
    ],
    "ja": [
        "ピアノ", "鍵盤", "鍵", "音楽", "楽器",
        "ピアノを弾く", "グランドピアノ", "アップライトピアノ", "電子ピアノ",
        "ピアノレッスン", "ピアノの練習", "リサイタル", "楽譜",
        "ピアノの先生", "ピアノの調律師", "コンサートピアノ",
        "MIDIキーボード", "ピアノの鍵盤",
        "ピアノを三十分練習する",
        "火曜日にピアノレッスンを予約する",
        "ピアノリサイタル用の楽譜を買う",
        "コンサート前にピアノを調律する",
        "ピアノで新しい曲を覚える",
        "部屋に電子ピアノを設置する",
        "夕食後にピアノを弾く",
        "今月ピアノレッスンに申し込む",
        "子供のためにピアノの先生を探す",
        "リビングにアップライトピアノを移動する",
        "スマホでピアノの演奏を録音する",
        "新しいキーボード用のピアノ椅子を買う",
        "毎日ピアノで音階練習をする",
        "学校のピアノリサイタルに参加する",
        "壊れたピアノの鍵を修理する",
        "ピアノの調律の予約を入れる",
        "ピアノの楽譜をオンラインでダウンロードする",
        "柔らかい布でピアノの鍵盤を拭く",
        "タレントショー用のピアノ曲を選ぶ",
        "コミュニティセンターでピアノを弾く",
        "グランドピアノを買うために貯金する",
        "タブレットにピアノアプリをインストールする",
        "練習前にピアノレッスンのノートを復習する",
        "歌手のピアノ伴奏をする",
        "ピアノで指のウォーミングアップをする",
        "リハーサルにキーボードを持っていく",
        "すり減ったピアノのペダルを交換する",
        "ピアノコンサートの録音を聴く",
        "ピアノコンクールに登録する",
        "ピアノの練習の毎日リマインダーを設定する",
        "ピアノの授業のために音楽理論を勉強する",
        "MIDIキーボードをパソコンに接続する",
        "リサイタルのためにピアノの部屋を飾る",
        "パーティーでピアノを演奏する",
        "ピアノの椅子の高さを調整する",
        "ぴあの練習を放課後にする",
        "けんばん楽器のレッスン",
        "ピアの音楽リサイタル用",
        "音階れんしゅうをピアノで",
        "ピアノの調律よやく",
    ],
    "fr": [
        "piano", "clavier", "touches", "musique", "instrument",
        "jouer du piano", "piano à queue", "piano droit", "piano numérique",
        "leçon de piano", "pratique du piano", "récital", "partition",
        "professeur de piano", "accordeur de piano", "piano de concert",
        "clavier MIDI", "touches du piano",
        "pratiquer le piano pendant trente minutes",
        "planifier une leçon de piano pour mardi",
        "acheter des partitions pour le récital de piano",
        "accorder le piano avant le concert",
        "apprendre un nouveau morceau au piano",
        "installer le piano numérique dans la pièce",
        "jouer du piano après le dîner",
        "s'inscrire à des cours de piano ce mois-ci",
        "trouver un professeur de piano pour les enfants",
        "déplacer le piano droit dans le salon",
        "enregistrer un morceau de piano sur mon téléphone",
        "acheter un banc de piano pour le nouveau clavier",
        "pratiquer les gammes au piano chaque jour",
        "assister au récital de piano à l'école",
        "réparer la touche de piano cassée",
        "prendre rendez-vous pour accorder le piano",
        "télécharger des partitions de piano en ligne",
        "nettoyer les touches du piano avec un chiffon doux",
        "choisir un morceau de piano pour le spectacle de talents",
        "jouer du piano au centre communautaire",
        "économiser pour acheter un piano à queue",
        "installer l'appli de piano sur la tablette",
        "revoir les notes de la leçon de piano avant de pratiquer",
        "accompagner le chanteur au piano",
        "s'échauffer avec des exercices de doigts au piano",
        "apporter le clavier à la répétition",
        "remplacer la pédale de piano usée",
        "écouter un enregistrement de concert de piano",
        "s'inscrire au concours de piano",
        "mettre un rappel quotidien pour pratiquer le piano",
        "étudier le solfège pour le cours de piano",
        "connecter le clavier MIDI à l'ordinateur",
        "décorer la salle de piano pour le récital",
        "jouer du piano à la fête",
        "ajuster la hauteur du tabouret de piano",
        "paino pratique après l'école",
        "clavire instrument leçons",
        "pian musique pour le récital",
        "gammes au paino pratiquer",
        "accordage du pano rendez-vous",
    ],
    "es": [
        "piano", "teclado", "teclas", "música", "instrumento",
        "tocar el piano", "piano de cola", "piano vertical", "piano digital",
        "lección de piano", "práctica de piano", "recital", "partitura",
        "profesor de piano", "afinador de piano", "piano de concierto",
        "teclado MIDI", "teclas del piano",
        "practicar piano durante treinta minutos",
        "programar una lección de piano para el martes",
        "comprar partituras para el recital de piano",
        "afinar el piano antes del concierto",
        "aprender una nueva canción en el piano",
        "instalar el piano digital en la habitación",
        "tocar el piano después de cenar",
        "inscribirse en clases de piano este mes",
        "encontrar un profesor de piano para los niños",
        "mover el piano vertical a la sala",
        "grabar una pieza de piano en mi teléfono",
        "comprar un banco de piano para el nuevo teclado",
        "practicar escalas en el piano todos los días",
        "asistir al recital de piano en la escuela",
        "reparar la tecla rota del piano",
        "pedir una cita para afinar el piano",
        "descargar partituras de piano en línea",
        "limpiar las teclas del piano con un paño suave",
        "elegir una pieza de piano para el show de talentos",
        "tocar el piano en el centro comunitario",
        "ahorrar para comprar un piano de cola",
        "instalar la app de piano en la tableta",
        "repasar las notas de la lección de piano antes de practicar",
        "acompañar al cantante en el piano",
        "calentar con ejercicios de dedos en el piano",
        "llevar el teclado al ensayo",
        "reemplazar el pedal gastado del piano",
        "escuchar una grabación de concierto de piano",
        "registrarse en el concurso de piano",
        "poner un recordatorio diario para practicar piano",
        "estudiar teoría musical para la clase de piano",
        "conectar el teclado MIDI a la computadora",
        "decorar la sala del piano para el recital",
        "tocar el piano en la fiesta",
        "ajustar la altura del banquillo del piano",
        "paino práctica después de la escuela",
        "tecldo instrumento lecciones",
        "pian música para el recital",
        "escalas en el paino practicar",
        "afinción del piano cita",
    ],
})


# ── PICKAXE ──────────────────────────────────────────────────────────────────
build_icon("pickaxe", {
    "en": [
        "pickaxe", "pick", "mine", "mining", "dig",
        "axe", "construction", "tool", "ore", "quarry",
        "Minecraft", "excavation", "rock", "geology",
        "gold mining", "coal mine", "pickaxe handle",
        "ice pick",
        "grab the pickaxe for the digging project",
        "buy a new pickaxe at the hardware store",
        "mine ore with a pickaxe underground",
        "use a pickaxe to break up the rock",
        "sharpen the pickaxe before the job",
        "dig a trench with the pickaxe",
        "bring the pickaxe to the construction site",
        "replace the worn pickaxe handle",
        "swing the pickaxe to split the boulder",
        "rent a pickaxe for the demolition project",
        "store the pickaxe in the tool shed",
        "carry the pickaxe to the mine entrance",
        "use a pickaxe to remove old concrete",
        "clean the pickaxe after digging",
        "craft a diamond pickaxe in Minecraft",
        "find gold nuggets while mining with a pickaxe",
        "dig for rock samples with a geology pickaxe",
        "pack the pickaxe for the camping trip",
        "haul the pickaxe up the mountain",
        "fix the loose pickaxe head",
        "order a heavy-duty pickaxe online",
        "use a pickaxe to loosen the frozen ground",
        "break the pavement with a pickaxe",
        "pick up the pickaxe from the garage",
        "lend the pickaxe to the neighbor",
        "upgrade the pickaxe in the adventure game",
        "work the quarry with a steel pickaxe",
        "practice swinging the pickaxe safely",
        "check the pickaxe blade for damage",
        "hang the pickaxe on the wall mount",
        "use a mini pickaxe for the garden bed",
        "take the pickaxe to the job site tomorrow",
        "chip away at the stone wall with a pickaxe",
        "collect ore using a pickaxe in the game",
        "remove tree roots with a pickaxe",
        "picaxe for mining",
        "pikaxe rock breaking",
        "minning with a pickaxe",
        "iice axe for climbing",
        "pickaxe hadnle replacement",
    ],
    "ru": [
        "кирка", "кайло", "шахта", "горнодобыча", "копать",
        "топор", "строительство", "инструмент", "руда", "карьер",
        "Майнкрафт", "раскопки", "скала", "геология",
        "золотодобыча", "угольная шахта", "рукоятка кирки",
        "ледоруб",
        "взять кирку для проекта по копке",
        "купить новую кирку в строительном магазине",
        "добывать руду киркой под землёй",
        "разбить камень киркой",
        "заточить кирку перед работой",
        "выкопать траншею киркой",
        "принести кирку на стройплощадку",
        "заменить изношенную рукоятку кирки",
        "размахнуться киркой чтобы расколоть валун",
        "арендовать кирку для проекта сноса",
        "убрать кирку в сарай для инструментов",
        "нести кирку ко входу в шахту",
        "удалить старый бетон киркой",
        "почистить кирку после копки",
        "сделать алмазную кирку в Майнкрафте",
        "найти золотые самородки при добыче киркой",
        "копать образцы пород геологической киркой",
        "взять кирку в поход",
        "тащить кирку в гору",
        "закрепить расшатанную головку кирки",
        "заказать тяжёлую кирку онлайн",
        "разрыхлить замёрзшую землю киркой",
        "сломать тротуар киркой",
        "взять кирку из гаража",
        "одолжить кирку соседу",
        "улучшить кирку в приключенческой игре",
        "работать в карьере стальной киркой",
        "тренировать безопасный замах киркой",
        "проверить лезвие кирки на повреждения",
        "повесить кирку на крепление на стене",
        "использовать мини-кирку для грядки",
        "взять кирку на работу завтра",
        "откалывать куски от каменной стены киркой",
        "собирать руду киркой в игре",
        "удалить корни деревьев киркой",
        "кирак для добычи",
        "кирка разбивка скал",
        "добча киркой",
        "ледруб для подъёма",
        "замена рукояти кирки",
    ],
    "de": [
        "Spitzhacke", "Pickel", "Mine", "Bergbau", "graben",
        "Axt", "Bau", "Werkzeug", "Erz", "Steinbruch",
        "Minecraft", "Ausgrabung", "Fels", "Geologie",
        "Goldbergbau", "Kohlemine", "Spitzhackengriff",
        "Eispickel",
        "die Spitzhacke für das Grabprojekt holen",
        "eine neue Spitzhacke im Baumarkt kaufen",
        "Erz unter Tage mit der Spitzhacke abbauen",
        "den Fels mit der Spitzhacke aufbrechen",
        "die Spitzhacke vor der Arbeit schärfen",
        "einen Graben mit der Spitzhacke ausheben",
        "die Spitzhacke zur Baustelle bringen",
        "den abgenutzten Spitzhackengriff ersetzen",
        "die Spitzhacke schwingen um den Felsen zu spalten",
        "eine Spitzhacke für das Abrissprojekt mieten",
        "die Spitzhacke im Werkzeugschuppen verstauen",
        "die Spitzhacke zum Mineneingang tragen",
        "alten Beton mit der Spitzhacke entfernen",
        "die Spitzhacke nach dem Graben reinigen",
        "eine Diamant-Spitzhacke in Minecraft herstellen",
        "Goldnuggets beim Abbau mit der Spitzhacke finden",
        "Gesteinsproben mit der Geologie-Spitzhacke graben",
        "die Spitzhacke für den Campingausflug einpacken",
        "die Spitzhacke den Berg hochtragen",
        "den lockeren Spitzhackenkopf befestigen",
        "eine robuste Spitzhacke online bestellen",
        "den gefrorenen Boden mit der Spitzhacke lockern",
        "den Gehweg mit der Spitzhacke aufbrechen",
        "die Spitzhacke aus der Garage holen",
        "dem Nachbarn die Spitzhacke leihen",
        "die Spitzhacke im Abenteuerspiel verbessern",
        "mit einer Stahlspitzhacke im Steinbruch arbeiten",
        "das sichere Schwingen der Spitzhacke üben",
        "die Klinge der Spitzhacke auf Schäden prüfen",
        "die Spitzhacke an die Wandhalterung hängen",
        "eine Mini-Spitzhacke für das Gartenbeet benutzen",
        "morgen die Spitzhacke zur Baustelle mitnehmen",
        "mit der Spitzhacke an der Steinmauer meißeln",
        "im Spiel Erz mit der Spitzhacke sammeln",
        "Baumwurzeln mit der Spitzhacke entfernen",
        "Spitzhake für Bergbau",
        "Spitzhacke Felsn brechen",
        "Bergbua mit der Spitzhacke",
        "Eispickle zum Klettern",
        "Spitzhackengrif Ersatz",
    ],
    "ja": [
        "つるはし", "ピック", "鉱山", "採掘", "掘る",
        "斧", "建設", "工具", "鉱石", "採石場",
        "マインクラフト", "発掘", "岩", "地質学",
        "金の採掘", "炭鉱", "つるはしの柄",
        "アイスピック",
        "掘削プロジェクトのためにつるはしを取る",
        "ホームセンターで新しいつるはしを買う",
        "地下でつるはしを使って鉱石を掘る",
        "つるはしで岩を砕く",
        "仕事の前につるはしを研ぐ",
        "つるはしで溝を掘る",
        "つるはしを建設現場に持っていく",
        "すり減ったつるはしの柄を交換する",
        "つるはしを振って岩を割る",
        "解体プロジェクトのためにつるはしをレンタルする",
        "つるはしを道具小屋にしまう",
        "つるはしを鉱山の入り口に運ぶ",
        "つるはしで古いコンクリートを撤去する",
        "掘った後につるはしをきれいにする",
        "マインクラフトでダイヤモンドのつるはしを作る",
        "つるはしで採掘中に金塊を見つける",
        "地質学用のつるはしで岩石サンプルを掘る",
        "キャンプ旅行につるはしを持っていく",
        "つるはしを山に運ぶ",
        "緩んだつるはしの頭を直す",
        "ヘビーデューティーのつるはしをオンラインで注文する",
        "つるはしで凍った地面をほぐす",
        "つるはしで舗装を壊す",
        "ガレージからつるはしを取ってくる",
        "つるはしを隣人に貸す",
        "冒険ゲームでつるはしをアップグレードする",
        "鋼のつるはしで採石場で作業する",
        "つるはしの安全な振り方を練習する",
        "つるはしの刃の損傷を確認する",
        "つるはしを壁掛けにかける",
        "庭の花壇用のミニつるはしを使う",
        "明日仕事場につるはしを持っていく",
        "つるはしで石壁を削る",
        "ゲームでつるはしを使って鉱石を集める",
        "つるはしで木の根を取り除く",
        "つるはしで採くつする",
        "つるはしで岩をくだく",
        "採くつ作業につるはし",
        "アイスピクで登山する",
        "つるはしの柄のこうかん",
    ],
    "fr": [
        "pioche", "pic", "mine", "exploitation minière", "creuser",
        "hache", "construction", "outil", "minerai", "carrière",
        "Minecraft", "excavation", "roche", "géologie",
        "exploitation de l'or", "mine de charbon", "manche de pioche",
        "piolet",
        "prendre la pioche pour le projet de creusage",
        "acheter une nouvelle pioche au magasin de bricolage",
        "extraire du minerai à la pioche sous terre",
        "casser la roche avec la pioche",
        "aiguiser la pioche avant le travail",
        "creuser une tranchée avec la pioche",
        "apporter la pioche au chantier",
        "remplacer le manche de pioche usé",
        "balancer la pioche pour fendre le rocher",
        "louer une pioche pour le projet de démolition",
        "ranger la pioche dans l'abri à outils",
        "porter la pioche jusqu'à l'entrée de la mine",
        "enlever le vieux béton avec la pioche",
        "nettoyer la pioche après avoir creusé",
        "fabriquer une pioche en diamant dans Minecraft",
        "trouver des pépites d'or en minant avec une pioche",
        "creuser des échantillons de roche avec une pioche de géologue",
        "emporter la pioche pour le voyage en camping",
        "hisser la pioche en haut de la montagne",
        "fixer la tête de pioche desserrée",
        "commander une pioche résistante en ligne",
        "dégeler le sol gelé avec la pioche",
        "casser le trottoir avec une pioche",
        "prendre la pioche dans le garage",
        "prêter la pioche au voisin",
        "améliorer la pioche dans le jeu d'aventure",
        "travailler la carrière avec une pioche en acier",
        "s'entraîner à manier la pioche en toute sécurité",
        "vérifier la lame de la pioche pour des dégâts",
        "accrocher la pioche au support mural",
        "utiliser une mini pioche pour le parterre de jardin",
        "emmener la pioche sur le chantier demain",
        "tailler la pierre du mur avec une pioche",
        "collecter du minerai à la pioche dans le jeu",
        "arracher les racines d'arbre avec une pioche",
        "piohce pour le minage",
        "pioche casasge de roche",
        "minagee avec une pioche",
        "pioelt pour l'escalade",
        "remplacement du manche de piohe",
    ],
    "es": [
        "pico", "piqueta", "mina", "minería", "cavar",
        "hacha", "construcción", "herramienta", "mineral", "cantera",
        "Minecraft", "excavación", "roca", "geología",
        "minería de oro", "mina de carbón", "mango del pico",
        "piolet",
        "tomar el pico para el proyecto de excavación",
        "comprar un pico nuevo en la ferretería",
        "extraer mineral con un pico bajo tierra",
        "romper la roca con el pico",
        "afilar el pico antes del trabajo",
        "cavar una zanja con el pico",
        "llevar el pico al sitio de construcción",
        "reemplazar el mango gastado del pico",
        "balancear el pico para partir la roca",
        "alquilar un pico para el proyecto de demolición",
        "guardar el pico en el cobertizo de herramientas",
        "cargar el pico hasta la entrada de la mina",
        "quitar el concreto viejo con el pico",
        "limpiar el pico después de cavar",
        "fabricar un pico de diamante en Minecraft",
        "encontrar pepitas de oro minando con un pico",
        "cavar muestras de roca con un pico de geología",
        "empacar el pico para el viaje de camping",
        "subir el pico a la montaña",
        "arreglar la cabeza suelta del pico",
        "pedir un pico resistente en línea",
        "aflojar el suelo congelado con el pico",
        "romper el pavimento con un pico",
        "sacar el pico del garaje",
        "prestarle el pico al vecino",
        "mejorar el pico en el juego de aventura",
        "trabajar en la cantera con un pico de acero",
        "practicar el manejo seguro del pico",
        "revisar la hoja del pico por daños",
        "colgar el pico en el soporte de la pared",
        "usar un mini pico para el jardín",
        "llevar el pico al sitio de trabajo mañana",
        "picar la pared de piedra con un pico",
        "recolectar mineral usando un pico en el juego",
        "quitar raíces de árboles con un pico",
        "pcio para la minería",
        "pico rpmper rocas",
        "mineía con un pico",
        "pioelt para escalar",
        "reempalzo del mango del pico",
    ],
})


# ── PIG ──────────────────────────────────────────────────────────────────────
build_icon("pig", {
    "en": [
        "pig", "pork", "bacon", "ham", "oink",
        "farm", "piglet", "sow", "livestock", "animal",
        "mammal", "fauna", "swine", "barnyard",
        "pig farm", "pork chop", "pig pen",
        "farm animal",
        "feed the pigs on the farm",
        "visit the pig farm this weekend",
        "buy pork chops at the butcher",
        "cook bacon for breakfast",
        "prepare ham for the holiday dinner",
        "clean the pig pen today",
        "check on the piglets in the barn",
        "order pork from the local farm",
        "take the kids to see the pigs at the fair",
        "schedule a vet visit for the pig",
        "buy pig feed from the supply store",
        "research pig breeds for the farm",
        "build a new pig pen on the property",
        "sell pigs at the livestock market",
        "cook a pork roast for Sunday dinner",
        "make a ham sandwich for lunch",
        "fry bacon and eggs in the morning",
        "adopt a mini pig as a pet",
        "read about pig care and nutrition",
        "vaccinate the pigs on the farm",
        "prepare pulled pork for the barbecue",
        "watch a documentary about pig farming",
        "save the pork leftovers in the fridge",
        "enter the pig in the county fair contest",
        "teach the kids about farm animals like pigs",
        "marinate the pork overnight",
        "get the pig pen ready for winter",
        "weigh the pig before selling",
        "pick up pork sausages from the shop",
        "compost the pig pen waste",
        "set up a mud area for the pigs",
        "bring water to the pig trough",
        "grill pork ribs for the cookout",
        "add pork to the grocery list",
        "plan a trip to the petting farm to see pigs",
        "pgi farm visit this weekend",
        "fmarm pig feeding time",
        "animla pig care guide",
        "bcon and eggs for breakfast",
        "pigg sow and piglets",
    ],
    "ru": [
        "свинья", "свинина", "бекон", "ветчина", "хрюканье",
        "ферма", "поросёнок", "свиноматка", "скот", "животное",
        "млекопитающее", "фауна", "свиньи", "скотный двор",
        "свиноферма", "свиная отбивная", "свинарник",
        "сельскохозяйственное животное",
        "покормить свиней на ферме",
        "посетить свиноферму на выходных",
        "купить свиные отбивные у мясника",
        "приготовить бекон на завтрак",
        "приготовить ветчину к праздничному ужину",
        "почистить свинарник сегодня",
        "проверить поросят в амбаре",
        "заказать свинину с местной фермы",
        "сводить детей посмотреть на свиней на ярмарке",
        "записать свинью к ветеринару",
        "купить корм для свиней в магазине",
        "изучить породы свиней для фермы",
        "построить новый свинарник на участке",
        "продать свиней на рынке скота",
        "приготовить свиное жаркое на воскресный ужин",
        "сделать бутерброд с ветчиной на обед",
        "пожарить бекон с яйцами утром",
        "завести мини-свинью как питомца",
        "прочитать об уходе и питании свиней",
        "вакцинировать свиней на ферме",
        "приготовить рваную свинину для барбекю",
        "посмотреть документальный фильм о свиноводстве",
        "сохранить остатки свинины в холодильнике",
        "записать свинью на конкурс на ярмарке",
        "рассказать детям о фермерских животных вроде свиней",
        "замариновать свинину на ночь",
        "подготовить свинарник к зиме",
        "взвесить свинью перед продажей",
        "купить свиные колбаски в магазине",
        "компостировать отходы из свинарника",
        "обустроить грязевую зону для свиней",
        "принести воду к свиному корыту",
        "пожарить свиные рёбрышки на гриле",
        "добавить свинину в список продуктов",
        "запланировать поездку на ферму посмотреть на свиней",
        "свинфоерма посещение на выходных",
        "фрема свиней кормление",
        "животне свинья уход",
        "бекн и яйца на завтрак",
        "свинматка и поросята",
    ],
    "de": [
        "Schwein", "Schweinefleisch", "Speck", "Schinken", "Grunzen",
        "Bauernhof", "Ferkel", "Sau", "Vieh", "Tier",
        "Säugetier", "Fauna", "Schweine", "Hof",
        "Schweinefarm", "Schweinekotelett", "Schweinestall",
        "Bauernhoftier",
        "die Schweine auf dem Hof füttern",
        "die Schweinefarm am Wochenende besuchen",
        "Schweinekoteletts beim Metzger kaufen",
        "Speck zum Frühstück braten",
        "Schinken für das Feiertagsessen vorbereiten",
        "den Schweinestall heute reinigen",
        "nach den Ferkeln im Stall schauen",
        "Schweinefleisch vom lokalen Bauernhof bestellen",
        "mit den Kindern auf der Messe die Schweine sehen",
        "einen Tierarztbesuch für das Schwein planen",
        "Schweinefutter im Laden kaufen",
        "Schweinerassen für den Hof recherchieren",
        "einen neuen Schweinestall auf dem Grundstück bauen",
        "Schweine auf dem Viehmarkt verkaufen",
        "einen Schweinebraten für das Sonntagsessen kochen",
        "ein Schinkenbrot zum Mittagessen machen",
        "morgens Speck und Eier braten",
        "ein Minischwein als Haustier adoptieren",
        "über Schweinepflege und Ernährung lesen",
        "die Schweine auf dem Hof impfen",
        "Pulled Pork für das Grillfest vorbereiten",
        "eine Dokumentation über Schweinezucht schauen",
        "die Schweinefleischreste im Kühlschrank aufbewahren",
        "das Schwein zum Wettbewerb auf der Messe anmelden",
        "den Kindern Bauernhoftiere wie Schweine erklären",
        "das Schweinefleisch über Nacht marinieren",
        "den Schweinestall winterfest machen",
        "das Schwein vor dem Verkauf wiegen",
        "Schweinebratwürste im Laden holen",
        "den Mist aus dem Schweinestall kompostieren",
        "einen Matschbereich für die Schweine einrichten",
        "Wasser zum Schweinetrog bringen",
        "Schweinerippchen für das Grillen grillen",
        "Schweinefleisch auf die Einkaufsliste setzen",
        "einen Ausflug zum Streichelhof mit Schweinen planen",
        "Schweinefram Besuch am Wochenende",
        "Buaernhof Schweine Fütterung",
        "Tier Schwein Pfelge",
        "Speeck und Eier zum Frühstück",
        "Sau und Ferkal",
    ],
    "ja": [
        "豚", "豚肉", "ベーコン", "ハム", "ブーブー",
        "農場", "子豚", "雌豚", "家畜", "動物",
        "哺乳類", "ファウナ", "豚たち", "畜舎",
        "養豚場", "ポークチョップ", "豚小屋",
        "家畜の動物",
        "農場で豚にエサをやる",
        "週末に養豚場を訪れる",
        "肉屋でポークチョップを買う",
        "朝食にベーコンを焼く",
        "休日のディナーにハムを準備する",
        "今日豚小屋を掃除する",
        "納屋の子豚を確認する",
        "地元の農場から豚肉を注文する",
        "子供たちをフェアで豚を見に連れて行く",
        "豚の獣医の予約をする",
        "飼料店で豚のエサを買う",
        "農場用の豚の品種を調べる",
        "敷地に新しい豚小屋を建てる",
        "家畜市場で豚を売る",
        "日曜のディナーにポークローストを作る",
        "昼食にハムサンドイッチを作る",
        "朝にベーコンエッグを焼く",
        "ミニ豚をペットとして飼う",
        "豚の飼育と栄養について読む",
        "農場の豚にワクチンを打つ",
        "バーベキュー用にプルドポークを作る",
        "養豚についてのドキュメンタリーを観る",
        "豚肉の残りを冷蔵庫に保存する",
        "フェアのコンテストに豚をエントリーする",
        "子供に豚のような農場の動物について教える",
        "一晩豚肉をマリネする",
        "冬に向けて豚小屋を準備する",
        "売る前に豚の体重を量る",
        "お店で豚肉ソーセージを買う",
        "豚小屋の廃棄物を堆肥にする",
        "豚のために泥場を作る",
        "豚のトラフに水を運ぶ",
        "ポークリブをバーベキューで焼く",
        "買い物リストに豚肉を追加する",
        "ふれあい農場に豚を見に行く計画を立てる",
        "ようとん場を訪れる週末",
        "農場のぶた餌やり",
        "どうぶつ豚の世話",
        "ベーコンとたまご朝食",
        "めすぶたと子豚たち",
    ],
    "fr": [
        "cochon", "porc", "bacon", "jambon", "grognement",
        "ferme", "porcelet", "truie", "bétail", "animal",
        "mammifère", "faune", "cochons", "basse-cour",
        "élevage de cochons", "côtelette de porc", "enclos à cochons",
        "animal de ferme",
        "nourrir les cochons à la ferme",
        "visiter la ferme de cochons ce week-end",
        "acheter des côtelettes de porc chez le boucher",
        "cuire du bacon pour le petit-déjeuner",
        "préparer du jambon pour le dîner de fête",
        "nettoyer l'enclos des cochons aujourd'hui",
        "vérifier les porcelets dans la grange",
        "commander du porc de la ferme locale",
        "emmener les enfants voir les cochons à la foire",
        "prendre rendez-vous chez le vétérinaire pour le cochon",
        "acheter de la nourriture pour cochons au magasin",
        "rechercher des races de cochons pour la ferme",
        "construire un nouvel enclos à cochons sur le terrain",
        "vendre des cochons au marché aux bestiaux",
        "préparer un rôti de porc pour le dîner du dimanche",
        "faire un sandwich au jambon pour le déjeuner",
        "faire frire du bacon et des oeufs le matin",
        "adopter un mini cochon comme animal de compagnie",
        "lire sur les soins et la nutrition des cochons",
        "vacciner les cochons de la ferme",
        "préparer du porc effiloché pour le barbecue",
        "regarder un documentaire sur l'élevage porcin",
        "garder les restes de porc au réfrigérateur",
        "inscrire le cochon au concours de la foire",
        "expliquer aux enfants les animaux de ferme comme les cochons",
        "faire mariner le porc pendant la nuit",
        "préparer l'enclos des cochons pour l'hiver",
        "peser le cochon avant de le vendre",
        "acheter des saucisses de porc au magasin",
        "composter les déchets de l'enclos à cochons",
        "aménager une zone de boue pour les cochons",
        "apporter de l'eau à l'auge des cochons",
        "griller des côtes de porc pour le barbecue",
        "ajouter du porc à la liste de courses",
        "planifier une visite à la ferme pour voir des cochons",
        "cohcon ferme visite ce week-end",
        "nourrir les cohcons à la ferme",
        "aniaml cochon soins",
        "bcon et oeufs pour le petit-déjeuner",
        "truei et porcelets",
    ],
    "es": [
        "cerdo", "carne de cerdo", "tocino", "jamón", "gruñido",
        "granja", "lechón", "cerda", "ganado", "animal",
        "mamífero", "fauna", "cerdos", "corral",
        "granja de cerdos", "chuleta de cerdo", "pocilga",
        "animal de granja",
        "alimentar a los cerdos en la granja",
        "visitar la granja de cerdos este fin de semana",
        "comprar chuletas de cerdo en la carnicería",
        "cocinar tocino para el desayuno",
        "preparar jamón para la cena festiva",
        "limpiar la pocilga hoy",
        "revisar los lechones en el granero",
        "pedir carne de cerdo de la granja local",
        "llevar a los niños a ver los cerdos en la feria",
        "programar una visita al veterinario para el cerdo",
        "comprar alimento para cerdos en la tienda",
        "investigar razas de cerdos para la granja",
        "construir una nueva pocilga en la propiedad",
        "vender cerdos en el mercado ganadero",
        "cocinar un asado de cerdo para la cena del domingo",
        "hacer un sándwich de jamón para el almuerzo",
        "freír tocino y huevos por la mañana",
        "adoptar un mini cerdo como mascota",
        "leer sobre el cuidado y nutrición de cerdos",
        "vacunar a los cerdos de la granja",
        "preparar cerdo desmenuzado para la parrillada",
        "ver un documental sobre la cría de cerdos",
        "guardar las sobras de cerdo en el refrigerador",
        "inscribir al cerdo en el concurso de la feria",
        "enseñar a los niños sobre animales de granja como cerdos",
        "marinar la carne de cerdo durante la noche",
        "preparar la pocilga para el invierno",
        "pesar al cerdo antes de venderlo",
        "comprar salchichas de cerdo en la tienda",
        "hacer composta con los desechos de la pocilga",
        "preparar una zona de lodo para los cerdos",
        "llevar agua al comedero de los cerdos",
        "asar costillas de cerdo en la parrilla",
        "agregar carne de cerdo a la lista de compras",
        "planear una visita a la granja para ver cerdos",
        "granja de credos visita este fin de semana",
        "alimentr a los cerdos en la granja",
        "aniaml cerdo cuidado",
        "tocnio y huevos para el desayuno",
        "creda y lechones",
    ],
})


print("Part C (piano, pickaxe, pig) done.")
