#!/usr/bin/env python3
"""Batch 3/4/5: Generate training data for 89 icons across 6 languages.

Cleans existing EN/RU (devspeak, visual, boundary, mixed-lang),
tops up to 60, creates DE/JA/FR/ES with 60 each.
"""

import csv, re, os
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ICONS_DIR = ROOT / "icons"

# ── Cleaning patterns ────────────────────────────────────────────────────────

BAD_EN = [
    re.compile(r"\bicon\b", re.I),
    re.compile(r"\bsymbol\b.*\b(app|section|screen|feature|ui|interface|page|platform)\b", re.I),
    re.compile(r"\b(app|ui|interface|screen|platform|feature|section)\b.*\b(icon|symbol)\b", re.I),
    re.compile(r"I need a .+ (icon|symbol)", re.I),
    re.compile(r"add a .+ (symbol|icon) to", re.I),
    re.compile(r"show a .+ for the", re.I),
    re.compile(r"use the .+ (icon|symbol) for", re.I),
    re.compile(r"^icon for ", re.I),
    re.compile(r"\bsilhouette\b", re.I),
    re.compile(r"\bemoji\b", re.I),
    re.compile(r"\bclip.?art\b", re.I),
]

BAD_RU = [
    re.compile(r"\bиконк[аиуеой]\b", re.I),
    re.compile(r"\bзначо?к\b.*\b(для|в|на)\b.*\b(приложени|интерфейс|экран|раздел|функци|страниц|платформ)", re.I),
    re.compile(r"\bсимвол\b.*\b(приложени|интерфейс|экран)", re.I),
    re.compile(r"\bсилуэт\b", re.I),
    re.compile(r"\bэмодзи\b", re.I),
    re.compile(r"\b(app|screen|ui|interface|platform|feature)\b", re.I),
]

VISUAL_PATTERNS = [
    re.compile(r"\b(glowing|shimmering|sparkling|bright|vivid|colorful)\b.*\b(light|color|image|picture|illustration)\b", re.I),
    re.compile(r"\billustration\b", re.I),
    re.compile(r"\bclip.?art\b", re.I),
]


def is_bad_en(text):
    return any(p.search(text) for p in BAD_EN) or any(p.search(text) for p in VISUAL_PATTERNS)

def is_bad_ru(text):
    return any(p.search(text) for p in BAD_RU) or any(p.search(text) for p in VISUAL_PATTERNS)


def read_csv(path):
    if not path.exists():
        return []
    with path.open(encoding="utf-8", newline="") as f:
        return [r["text"].strip() for r in csv.DictReader(f)]


def write_csv(path, texts, label):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["text", "label"])
        for t in texts:
            w.writerow([t, label])


# ── Per-icon phrase data ─────────────────────────────────────────────────────
# Each icon gets a dict with keys: en, ru, de, ja, fr, es
# Each list has 60 phrases. For icons that already have >=60 EN/RU,
# we only provide de/ja/fr/es.

ICONS = {}

# Helper to register icon data
def icon(name, **langs):
    ICONS[name] = langs

# ============================================================================
# BATCH 3: Icons with 40-49 EN rows (need topping up EN/RU + new DE/JA/FR/ES)
# ============================================================================

icon("sterling-sign",
    en=[
        # keywords (~18)
        "british pound", "pound sterling", "sterling", "gbp",
        "uk currency", "pounds", "quid", "bob",
        "pence", "price in pounds", "currency exchange",
        "forex gbp", "london money", "bank of england",
        "pound note", "british money", "sterling rate", "gbp usd",
        # phrases (~37)
        "convert dollars to pounds before the trip",
        "check the gbp exchange rate today",
        "pay the invoice in british pounds",
        "send money in pounds to the uk account",
        "salary paid in pounds sterling",
        "budget the london trip in gbp",
        "compare sterling against the euro",
        "track the pound exchange rate this week",
        "buy pounds at the airport currency desk",
        "settle the hotel bill in pounds",
        "price the product in gbp for uk customers",
        "convert usd to gbp for the transfer",
        "exchange euros for pounds at the bank",
        "travel budget needs to be in pounds",
        "set the checkout currency to pounds",
        "payroll processed in british pounds",
        "need pounds before the flight to london",
        "the pound dropped against the dollar today",
        "shopping in london so need some quid",
        "change leftover euros to pounds",
        "gbp rate alert for the morning",
        "transfer savings to a pound account",
        "withdraw pounds from the atm in heathrow",
        "invoice total converted to sterling",
        "receipt shows the amount in pounds",
        "tip the cabbie ten quid",
        "save fifty pounds a month for the holiday",
        "rent is two thousand pounds a month",
        "tuition fees listed in gbp",
        "donate twenty pounds to the charity",
        "the antique cost three hundred pounds",
        "insurance premium quoted in sterling",
        "mortgage payment in pounds due friday",
        "cash in pounds for the market stall",
        "refund processed in gbp",
        "stock listed on the london exchange in pounds",
        "pension payout in british pounds",
        # typos (5)
        "conver dollars to pouds",
        "chekc the gbp exchagne rate",
        "pay invoce in brittish pounds",
        "buget the londn trip in gbp",
        "buy poudns at the ariport",
    ],
    ru=[
        # keywords (~18)
        "британский фунт", "фунт стерлингов", "стерлинг", "gbp",
        "валюта великобритании", "фунты", "пенсы", "курс фунта",
        "банк англии", "обмен валют", "лондонские деньги", "фунт",
        "британские деньги", "курс gbp", "фунтовая купюра",
        "обменный курс", "forex gbp", "gbp usd",
        # phrases (~37)
        "обменять доллары на фунты перед поездкой",
        "проверить курс gbp сегодня",
        "оплатить счёт в британских фунтах",
        "отправить деньги в фунтах на счёт в великобритании",
        "зарплата начисляется в фунтах стерлингов",
        "рассчитать бюджет поездки в лондон в gbp",
        "сравнить стерлинг с евро",
        "отслеживать курс фунта на этой неделе",
        "купить фунты в обменнике аэропорта",
        "оплатить счёт в гостинице в фунтах",
        "установить цену товара в gbp для клиентов из великобритании",
        "перевести usd в gbp для трансфера",
        "обменять евро на фунты в банке",
        "бюджет поездки нужен в фунтах",
        "поставить валюту оплаты в фунты",
        "зарплатная ведомость в британских фунтах",
        "нужны фунты перед вылетом в лондон",
        "фунт упал к доллару сегодня",
        "покупки в лондоне нужны наличные фунты",
        "поменять оставшиеся евро на фунты",
        "уведомление о курсе gbp с утра",
        "перевести сбережения на фунтовый счёт",
        "снять фунты в банкомате в хитроу",
        "итог счёта пересчитан в стерлинги",
        "чек показывает сумму в фунтах",
        "дать таксисту десять фунтов чаевых",
        "откладывать пятьдесят фунтов в месяц на отпуск",
        "аренда две тысячи фунтов в месяц",
        "стоимость обучения указана в gbp",
        "пожертвовать двадцать фунтов на благотворительность",
        "антиквариат стоит триста фунтов",
        "страховая премия указана в стерлингах",
        "ипотечный платёж в фунтах до пятницы",
        "наличные в фунтах для торговли на рынке",
        "возврат средств обработан в gbp",
        "акции на лондонской бирже котируются в фунтах",
        "пенсия выплачивается в британских фунтах",
        # typos (5)
        "обменять долары на футы",
        "проверть курс gbp сегдня",
        "оплтить счёт в британскх фунтах",
        "бюджт поездки в лондн в gbp",
        "купть фунты в аэрпорту",
    ],
    de=[
        # keywords (~18)
        "Britisches Pfund", "Pfund Sterling", "Sterling", "GBP",
        "UK-Währung", "Pfund", "Pence", "Pfundkurs",
        "Bank of England", "Devisenkurs", "Londoner Geld", "Wechselkurs",
        "britisches Geld", "GBP-Kurs", "Pfundnote",
        "Währungsumtausch", "Forex GBP", "GBP USD",
        # phrases (~37)
        "Dollar in Pfund umtauschen vor der Reise",
        "den GBP-Wechselkurs heute prüfen",
        "die Rechnung in britischen Pfund bezahlen",
        "Geld in Pfund auf das UK-Konto überweisen",
        "Gehalt wird in Pfund Sterling ausgezahlt",
        "Reisebudget für London in GBP berechnen",
        "Sterling mit dem Euro vergleichen",
        "den Pfundkurs diese Woche verfolgen",
        "Pfund am Flughafen-Wechselschalter kaufen",
        "die Hotelrechnung in Pfund begleichen",
        "den Produktpreis in GBP für UK-Kunden festlegen",
        "USD in GBP für die Überweisung umrechnen",
        "Euro in Pfund bei der Bank tauschen",
        "Reisebudget muss in Pfund sein",
        "Checkout-Währung auf Pfund einstellen",
        "Gehaltsabrechnung in britischen Pfund",
        "vor dem Flug nach London Pfund besorgen",
        "das Pfund ist heute zum Dollar gefallen",
        "Shopping in London brauche etwas Pfund",
        "übrige Euro in Pfund wechseln",
        "GBP-Kurswarnung für den Morgen",
        "Ersparnisse auf ein Pfund-Konto überweisen",
        "Pfund am Geldautomaten in Heathrow abheben",
        "Rechnungssumme in Sterling umgerechnet",
        "Quittung zeigt den Betrag in Pfund",
        "dem Taxifahrer zehn Pfund Trinkgeld geben",
        "fünfzig Pfund im Monat für den Urlaub sparen",
        "Miete beträgt zweitausend Pfund im Monat",
        "Studiengebühren in GBP angegeben",
        "zwanzig Pfund an die Wohltätigkeit spenden",
        "die Antiquität kostet dreihundert Pfund",
        "Versicherungsprämie in Sterling angegeben",
        "Hypothekenzahlung in Pfund bis Freitag",
        "Bargeld in Pfund für den Marktstand",
        "Rückerstattung in GBP bearbeitet",
        "Aktie an der Londoner Börse in Pfund notiert",
        "Rente wird in britischen Pfund ausgezahlt",
        # typos (5)
        "Doller in Pfnud umtauschen",
        "den GBP-Wchselkurs heute prüfne",
        "Rechung in britischn Pfund bezahlen",
        "Reiesbudget für Londn in GBP",
        "Pfnud am Flughaen kaufen",
    ],
    ja=[
        "英ポンド", "ポンド・スターリング", "スターリング", "GBP",
        "イギリス通貨", "ポンド", "ペンス", "ポンド為替",
        "イングランド銀行", "外貨両替", "ロンドンの通貨", "為替レート",
        "英国のお金", "GBPレート", "ポンド紙幣",
        "通貨換算", "フォレックスGBP", "GBP USD",
        "旅行前にドルをポンドに両替する",
        "今日のGBP為替レートを確認する",
        "請求書を英ポンドで支払う",
        "英国口座にポンドで送金する",
        "給与がポンド・スターリングで支払われる",
        "ロンドン旅行の予算をGBPで計算する",
        "スターリングとユーロを比較する",
        "今週のポンド為替レートを追跡する",
        "空港の両替所でポンドを購入する",
        "ホテルの請求をポンドで精算する",
        "UK顧客向けに商品価格をGBPで設定する",
        "送金のためにUSDをGBPに換算する",
        "銀行でユーロをポンドに両替する",
        "旅行予算はポンドで必要",
        "決済通貨をポンドに設定する",
        "給与明細が英ポンド建て",
        "ロンドン行きの前にポンドを用意する",
        "今日ポンドが対ドルで下落した",
        "ロンドンで買い物するのでポンドが要る",
        "残りのユーロをポンドに替える",
        "朝のGBPレートアラート",
        "貯金をポンド口座に移す",
        "ヒースローのATMでポンドを下ろす",
        "請求合計をスターリングに換算",
        "領収書にポンドで金額が記載",
        "タクシー運転手に十ポンドのチップ",
        "毎月五十ポンドを休暇用に貯金する",
        "家賃は月二千ポンド",
        "授業料がGBPで記載されている",
        "二十ポンドを慈善団体に寄付する",
        "骨董品が三百ポンドだった",
        "保険料がスターリングで提示されている",
        "金曜までにポンドで住宅ローンを支払う",
        "市場の屋台用にポンドの現金",
        "GBPで返金処理済み",
        "ロンドン証券取引所でポンド建ての株",
        "年金が英ポンドで支給される",
        "ドルをポドンに両替する",
        "今日のGBP為替レートを確にんする",
        "請求しょをポンドで支はらう",
        "ポンドを空港のりょう替所で買う",
        "ロンドン旅こうの予算をGBPで計算",
    ],
    fr=[
        "livre sterling", "livre britannique", "sterling", "GBP",
        "monnaie britannique", "livres", "pence", "taux de la livre",
        "Banque d'Angleterre", "change de devises", "argent londonien", "taux de change",
        "argent britannique", "taux GBP", "billet en livres",
        "conversion de monnaie", "forex GBP", "GBP USD",
        "convertir des dollars en livres avant le voyage",
        "vérifier le taux de change GBP aujourd'hui",
        "payer la facture en livres sterling",
        "envoyer de l'argent en livres sur le compte britannique",
        "salaire versé en livres sterling",
        "calculer le budget du voyage à Londres en GBP",
        "comparer le sterling avec l'euro",
        "suivre le taux de la livre cette semaine",
        "acheter des livres au bureau de change de l'aéroport",
        "régler la note d'hôtel en livres",
        "fixer le prix du produit en GBP pour les clients britanniques",
        "convertir les USD en GBP pour le virement",
        "échanger des euros contre des livres à la banque",
        "le budget de voyage doit être en livres",
        "régler la devise de paiement en livres",
        "fiche de paie en livres sterling",
        "prendre des livres avant le vol vers Londres",
        "la livre a chuté face au dollar aujourd'hui",
        "shopping à Londres il faut des livres",
        "changer les euros restants en livres",
        "alerte taux GBP le matin",
        "transférer les économies sur un compte en livres",
        "retirer des livres au distributeur à Heathrow",
        "total de la facture converti en sterling",
        "le reçu indique le montant en livres",
        "donner dix livres de pourboire au chauffeur",
        "économiser cinquante livres par mois pour les vacances",
        "le loyer est de deux mille livres par mois",
        "frais de scolarité indiqués en GBP",
        "faire un don de vingt livres à l'association",
        "l'antiquité coûte trois cents livres",
        "prime d'assurance indiquée en sterling",
        "paiement hypothécaire en livres pour vendredi",
        "espèces en livres pour le stand du marché",
        "remboursement traité en GBP",
        "action cotée à la Bourse de Londres en livres",
        "la pension est versée en livres sterling",
        "convertir dolar en livrs",
        "vérifer le taux de chnage GBP",
        "payer la factur en livres sterlig",
        "achter des livres à l'aéroprt",
        "budjet du voyage à Londre en GBP",
    ],
    es=[
        "libra esterlina", "libra británica", "esterlina", "GBP",
        "moneda británica", "libras", "peniques", "tipo de cambio de la libra",
        "Banco de Inglaterra", "cambio de divisas", "dinero londinense", "tipo de cambio",
        "dinero británico", "tasa GBP", "billete de libras",
        "conversión de moneda", "forex GBP", "GBP USD",
        "cambiar dólares a libras antes del viaje",
        "revisar el tipo de cambio GBP hoy",
        "pagar la factura en libras esterlinas",
        "enviar dinero en libras a la cuenta británica",
        "salario pagado en libras esterlinas",
        "calcular el presupuesto del viaje a Londres en GBP",
        "comparar la esterlina con el euro",
        "seguir el tipo de cambio de la libra esta semana",
        "comprar libras en la casa de cambio del aeropuerto",
        "pagar la cuenta del hotel en libras",
        "fijar el precio del producto en GBP para clientes británicos",
        "convertir USD a GBP para la transferencia",
        "cambiar euros por libras en el banco",
        "el presupuesto de viaje debe estar en libras",
        "poner la moneda de pago en libras",
        "nómina en libras esterlinas",
        "conseguir libras antes del vuelo a Londres",
        "la libra cayó frente al dólar hoy",
        "compras en Londres necesito libras",
        "cambiar los euros sobrantes a libras",
        "alerta de tasa GBP por la mañana",
        "transferir ahorros a una cuenta en libras",
        "sacar libras del cajero en Heathrow",
        "total de la factura convertido a esterlinas",
        "el recibo muestra el monto en libras",
        "darle diez libras de propina al taxista",
        "ahorrar cincuenta libras al mes para las vacaciones",
        "el alquiler son dos mil libras al mes",
        "matrícula indicada en GBP",
        "donar veinte libras a la organización benéfica",
        "la antigüedad cuesta trescientas libras",
        "prima de seguro indicada en esterlinas",
        "pago de hipoteca en libras para el viernes",
        "efectivo en libras para el puesto del mercado",
        "reembolso procesado en GBP",
        "acción cotizada en la Bolsa de Londres en libras",
        "la pensión se paga en libras esterlinas",
        "cambair dólares a librsa",
        "revsar el tipo de camboi GBP",
        "pagar la factrua en libras esterilnas",
        "comprar libars en el aeropuerto",
        "presupuetso del viaje a Londrs en GBP",
    ],
)

icon("stethoscope",
    en=[
        "stethoscope", "diagnosis", "general practitioner", "heart checkup",
        "outpatient", "physical exam", "lungs", "heartbeat",
        "doctor visit", "clinical exam", "blood pressure", "chest exam",
        "nurse", "physician", "pediatrician", "cardiologist",
        "checkup", "auscultation",
        "schedule a checkup with the doctor",
        "listen to the heart with a stethoscope",
        "general practitioner visit at the family clinic",
        "doctor checking the patient's lungs",
        "annual physical exam at the clinic",
        "nurse taking blood pressure during rounds",
        "pediatrician listening to the baby's chest",
        "heart rate check during the physical",
        "outpatient visit for a routine checkup",
        "bring the stethoscope for the home visit",
        "cardiologist listening to the heartbeat",
        "the doctor will check your breathing",
        "chest exam before surgery",
        "auscultation revealed an irregular heartbeat",
        "book an appointment with the physician",
        "clinical exam scheduled for tuesday",
        "doctor used the stethoscope on my back",
        "need a checkup after the cold",
        "nurse practitioner checking vitals",
        "take the kids to the pediatrician",
        "heart murmur found during the exam",
        "blood pressure reading at the pharmacy",
        "follow-up visit with the general practitioner",
        "the doctor listened to my lungs twice",
        "routine checkup every six months",
        "stethoscope in the doctor's coat pocket",
        "prenatal checkup with the obstetrician",
        "lung sounds clear on auscultation",
        "urgent care visit for chest pain",
        "the physician checked my heart rhythm",
        "stethoscope exam during the sports physical",
        "listen to bowel sounds with the stethoscope",
        "clinical rounds with the stethoscope",
        "stethocope used by the nurse",
        "schdule a checkup with the doctr",
        "listn to the hart with a stethoscope",
        "annul physical exm at the clinic",
        "chekup after the cold",
    ],
    ru=[
        "стетоскоп", "диагноз", "терапевт", "осмотр сердца",
        "амбулатория", "медосмотр", "лёгкие", "сердцебиение",
        "визит к врачу", "клинический осмотр", "давление", "осмотр грудной клетки",
        "медсестра", "врач", "педиатр", "кардиолог",
        "обследование", "аускультация",
        "записаться на приём к врачу",
        "послушать сердце стетоскопом",
        "приём терапевта в семейной клинике",
        "врач слушает лёгкие пациента",
        "ежегодный медосмотр в поликлинике",
        "медсестра измеряет давление на обходе",
        "педиатр слушает грудь малыша",
        "проверка пульса во время осмотра",
        "амбулаторный визит для планового обследования",
        "взять стетоскоп для визита на дому",
        "кардиолог слушает сердцебиение",
        "врач проверит ваше дыхание",
        "осмотр грудной клетки перед операцией",
        "аускультация выявила нерегулярный ритм сердца",
        "записаться на приём к терапевту",
        "клинический осмотр назначен на вторник",
        "врач приложил стетоскоп к спине",
        "нужно обследование после простуды",
        "медсестра проверяет показатели",
        "отвести детей к педиатру",
        "шум в сердце обнаружен на осмотре",
        "измерение давления в аптеке",
        "повторный визит к терапевту",
        "врач дважды послушал мои лёгкие",
        "плановый осмотр каждые полгода",
        "стетоскоп в кармане халата врача",
        "пренатальный осмотр у акушера",
        "лёгочные звуки чистые при аускультации",
        "срочный визит из-за боли в груди",
        "врач проверил ритм сердца",
        "осмотр стетоскопом на спортивной медкомиссии",
        "прослушать кишечник стетоскопом",
        "клинический обход со стетоскопом",
        "стетоскоп использует медсетра",
        "записатся на приём к врачу",
        "послшать сердце стетоскпом",
        "ежегодый медосмтр в поликлинке",
        "обследование после простды",
    ],
    de=[
        "Stethoskop", "Diagnose", "Hausarzt", "Herzuntersuchung",
        "ambulant", "körperliche Untersuchung", "Lunge", "Herzschlag",
        "Arztbesuch", "klinische Untersuchung", "Blutdruck", "Brustuntersuchung",
        "Krankenschwester", "Arzt", "Kinderarzt", "Kardiologe",
        "Vorsorgeuntersuchung", "Auskultation",
        "einen Termin beim Arzt vereinbaren",
        "das Herz mit dem Stethoskop abhören",
        "Hausarztbesuch in der Familienpraxis",
        "der Arzt hört die Lunge des Patienten ab",
        "jährliche Vorsorgeuntersuchung in der Praxis",
        "Krankenschwester misst den Blutdruck bei der Visite",
        "Kinderarzt hört die Brust des Babys ab",
        "Pulskontrolle während der Untersuchung",
        "ambulanter Besuch zur Routineuntersuchung",
        "Stethoskop für den Hausbesuch mitbringen",
        "Kardiologe hört den Herzschlag ab",
        "der Arzt wird Ihre Atmung überprüfen",
        "Brustuntersuchung vor der Operation",
        "Auskultation ergab einen unregelmäßigen Herzschlag",
        "einen Termin beim Arzt buchen",
        "klinische Untersuchung für Dienstag geplant",
        "der Arzt hat das Stethoskop auf meinen Rücken gelegt",
        "brauche eine Untersuchung nach der Erkältung",
        "Krankenpflegerin prüft die Vitalzeichen",
        "die Kinder zum Kinderarzt bringen",
        "Herzgeräusch bei der Untersuchung entdeckt",
        "Blutdruckmessung in der Apotheke",
        "Nachuntersuchung beim Hausarzt",
        "der Arzt hat meine Lunge zweimal abgehört",
        "Routineuntersuchung alle sechs Monate",
        "Stethoskop in der Kitteltasche des Arztes",
        "Schwangerschaftsvorsorge beim Frauenarzt",
        "Lungengeräusche bei Auskultation unauffällig",
        "Notaufnahme wegen Brustschmerzen",
        "der Arzt hat meinen Herzrhythmus geprüft",
        "Stethoskop-Untersuchung bei der Sportuntersuchung",
        "Darmgeräusche mit dem Stethoskop abhören",
        "klinische Visite mit dem Stethoskop",
        "Stethokop vom Arzt benutzt",
        "Termin beim Arzt vereibaren",
        "das Herz mit dem Stethoskp abhörn",
        "jährlche Vorsorgeuntersuchng in der Praxis",
        "Untersuchng nach der Erkältug",
    ],
    ja=[
        "聴診器", "診断", "かかりつけ医", "心臓検査",
        "外来", "健康診断", "肺", "心拍",
        "診察", "臨床検査", "血圧", "胸部検査",
        "看護師", "医師", "小児科医", "心臓専門医",
        "検診", "聴診",
        "医者に検診の予約を入れる",
        "聴診器で心臓を聴く",
        "かかりつけ医の診察を受ける",
        "医師が患者の肺を聴診する",
        "年に一度の健康診断を受ける",
        "看護師が回診で血圧を測る",
        "小児科医が赤ちゃんの胸を聴く",
        "診察中に脈拍を確認する",
        "定期検診のための外来受診",
        "往診用に聴診器を持参する",
        "心臓専門医が心拍を聴く",
        "医師が呼吸を確認する",
        "手術前の胸部検査",
        "聴診で不整脈が見つかった",
        "医師の予約を取る",
        "火曜日に臨床検査の予定",
        "医師が背中に聴診器を当てた",
        "風邪のあとに検診が必要",
        "看護師がバイタルを確認する",
        "子どもを小児科医に連れて行く",
        "検査で心雑音が見つかった",
        "薬局で血圧を測る",
        "かかりつけ医の再診",
        "医師が肺を二回聴診した",
        "半年ごとの定期検診",
        "医師の白衣のポケットに聴診器",
        "産婦人科で妊婦健診",
        "聴診で肺音はクリア",
        "胸の痛みで急患受診",
        "医師が心拍リズムを確認した",
        "スポーツ検診で聴診器検査",
        "聴診器で腸の音を聴く",
        "聴診器を持って回診する",
        "聴診器を使って看ご師が確認",
        "けんしんの予約を入れる",
        "聴診器でしんぞうを聴く",
        "年に一度のけんこう診断を受ける",
        "風邪のあとにけんしんが必用",
    ],
    fr=[
        "stéthoscope", "diagnostic", "médecin généraliste", "examen cardiaque",
        "consultation externe", "examen physique", "poumons", "battement de cœur",
        "visite chez le médecin", "examen clinique", "tension artérielle", "examen thoracique",
        "infirmière", "médecin", "pédiatre", "cardiologue",
        "bilan de santé", "auscultation",
        "prendre rendez-vous chez le médecin",
        "écouter le cœur avec le stéthoscope",
        "consultation chez le médecin généraliste",
        "le médecin ausculte les poumons du patient",
        "examen médical annuel à la clinique",
        "l'infirmière prend la tension pendant la tournée",
        "le pédiatre ausculte la poitrine du bébé",
        "vérification du pouls pendant l'examen",
        "consultation externe pour un bilan de routine",
        "apporter le stéthoscope pour la visite à domicile",
        "le cardiologue écoute les battements du cœur",
        "le médecin va vérifier votre respiration",
        "examen thoracique avant l'opération",
        "l'auscultation a révélé un rythme cardiaque irrégulier",
        "prendre rendez-vous chez le médecin",
        "examen clinique prévu pour mardi",
        "le médecin a posé le stéthoscope sur mon dos",
        "besoin d'un bilan après le rhume",
        "l'infirmière vérifie les constantes",
        "emmener les enfants chez le pédiatre",
        "souffle au cœur détecté lors de l'examen",
        "prise de tension à la pharmacie",
        "visite de suivi chez le généraliste",
        "le médecin a écouté mes poumons deux fois",
        "bilan de santé tous les six mois",
        "stéthoscope dans la poche de la blouse du médecin",
        "examen prénatal chez l'obstétricien",
        "bruits pulmonaires normaux à l'auscultation",
        "urgences pour douleurs thoraciques",
        "le médecin a vérifié mon rythme cardiaque",
        "examen au stéthoscope pour la visite sportive",
        "écouter les bruits intestinaux avec le stéthoscope",
        "tournée clinique avec le stéthoscope",
        "stéthoscpe utilisé par le médecin",
        "prednre rendez-vous chez le médcin",
        "écoutr le cœur avec le stéthoscope",
        "examn médical annuel à la clinque",
        "besion d'un bilan aprés le rhume",
    ],
    es=[
        "estetoscopio", "diagnóstico", "médico general", "chequeo cardíaco",
        "consulta externa", "examen físico", "pulmones", "latido del corazón",
        "visita al médico", "examen clínico", "presión arterial", "examen de pecho",
        "enfermera", "médico", "pediatra", "cardiólogo",
        "revisión médica", "auscultación",
        "pedir cita con el médico",
        "escuchar el corazón con el estetoscopio",
        "consulta con el médico general",
        "el médico ausculta los pulmones del paciente",
        "examen médico anual en la clínica",
        "la enfermera toma la presión durante la ronda",
        "el pediatra ausculta el pecho del bebé",
        "control del pulso durante el examen",
        "consulta externa para un chequeo de rutina",
        "llevar el estetoscopio para la visita a domicilio",
        "el cardiólogo escucha los latidos del corazón",
        "el médico revisará tu respiración",
        "examen de pecho antes de la cirugía",
        "la auscultación reveló un ritmo cardíaco irregular",
        "reservar cita con el médico",
        "examen clínico programado para el martes",
        "el médico puso el estetoscopio en mi espalda",
        "necesito un chequeo después del resfriado",
        "la enfermera revisa los signos vitales",
        "llevar a los niños al pediatra",
        "soplo cardíaco detectado en el examen",
        "toma de presión en la farmacia",
        "visita de seguimiento con el médico general",
        "el médico escuchó mis pulmones dos veces",
        "revisión médica cada seis meses",
        "estetoscopio en el bolsillo de la bata del médico",
        "control prenatal con el obstetra",
        "sonidos pulmonares claros en la auscultación",
        "urgencias por dolor en el pecho",
        "el médico verificó mi ritmo cardíaco",
        "examen con estetoscopio en el chequeo deportivo",
        "escuchar los sonidos intestinales con el estetoscopio",
        "ronda clínica con el estetoscopio",
        "estetoscoipo usado por el médico",
        "pedir cita con el médco",
        "escuchar el corazón con el etstetoscopio",
        "examne médico anual en la clínca",
        "necesito un cheqeuo después del resfriado",
    ],
)

icon("sun",
    en=[
        "sun", "sunshine", "solar", "sunlight", "sunrise",
        "sunset", "daylight", "sunny", "UV", "sunburn",
        "sunscreen", "morning sun", "afternoon sun", "heat",
        "summer", "bright day", "clear sky", "tan",
        "put on sunscreen before going outside",
        "check the UV index for today",
        "sunrise hike scheduled for saturday",
        "close the blinds the sun is too bright",
        "water the plants before the sun gets too hot",
        "sunset picnic at the beach",
        "solar panel installation on the roof",
        "sunny day perfect for a barbecue",
        "the sunburn from yesterday still hurts",
        "buy sunscreen for the vacation",
        "morning sun coming through the kitchen window",
        "afternoon sun is heating up the office",
        "summer sun makes the garden grow fast",
        "wear a hat in the strong sun",
        "the sun is out lets go for a walk",
        "dry the laundry in the sun",
        "sit in the sunshine during lunch break",
        "solar charger for the camping trip",
        "plant the tomatoes where they get full sun",
        "daylight saving time starts next week",
        "tan lines from the beach day",
        "need sunglasses for the drive home",
        "sun coming out after the rain",
        "too much sun on the balcony plants",
        "heat wave expected this weekend",
        "enjoy the sunshine while it lasts",
        "bright day for the outdoor market",
        "clear sky and warm sun today",
        "open the curtains to let the sun in",
        "the garden needs more sunlight",
        "watch the sunset from the rooftop",
        "early sunrise means longer days",
        "solar panels generating good energy today",
        "avoid the midday sun when running",
        "sun is setting earlier now in autumn",
        "sunlit terrace for the morning coffee",
        "put on sunscren before the beach",
        "chekc the UV indx for today",
        "surnise hike scheduld for saturday",
        "close the blnds the sun is to bright",
        "buy sunsceen for the vacaton",
    ],
    ru=[
        "солнце", "солнечный свет", "солнечный", "солнечные лучи", "рассвет",
        "закат", "дневной свет", "солнечно", "ультрафиолет", "солнечный ожог",
        "солнцезащитный крем", "утреннее солнце", "послеобеденное солнце", "жара",
        "лето", "ясный день", "чистое небо", "загар",
        "нанести солнцезащитный крем перед выходом",
        "проверить индекс ультрафиолета на сегодня",
        "поход на рассвете запланирован на субботу",
        "закрыть жалюзи солнце слишком яркое",
        "полить растения пока солнце не стало жарким",
        "пикник на закате на пляже",
        "установка солнечных панелей на крыше",
        "солнечный день отлично для барбекю",
        "солнечный ожог со вчерашнего дня ещё болит",
        "купить солнцезащитный крем для отпуска",
        "утреннее солнце светит в кухонное окно",
        "послеобеденное солнце нагревает офис",
        "летнее солнце ускоряет рост в саду",
        "надеть шляпу на сильном солнце",
        "солнце вышло пойдём на прогулку",
        "высушить бельё на солнце",
        "посидеть на солнышке в обеденный перерыв",
        "солнечная зарядка для похода",
        "посадить помидоры где много солнца",
        "переход на летнее время на следующей неделе",
        "следы загара после дня на пляже",
        "нужны солнечные очки для дороги домой",
        "солнце выходит после дождя",
        "слишком много солнца на балконных растениях",
        "ожидается жара на выходных",
        "наслаждаться солнцем пока оно есть",
        "ясный день для уличного рынка",
        "чистое небо и тёплое солнце сегодня",
        "раздвинуть шторы чтобы впустить солнце",
        "саду нужно больше солнечного света",
        "смотреть закат с крыши",
        "ранний рассвет значит длинные дни",
        "солнечные панели хорошо вырабатывают энергию",
        "избегать полуденного солнца при беге",
        "солнце садится раньше осенью",
        "солнечная терраса для утреннего кофе",
        "нанети солнцезащитный крем перед пляжем",
        "проверть индекс ультрафиолта на сегодня",
        "поход на расвете заплнирован на субботу",
        "закрть жалюзи солце слишком яркое",
        "купть солнцезщитный крем для отпска",
    ],
    de=[
        "Sonne", "Sonnenschein", "Solar", "Sonnenlicht", "Sonnenaufgang",
        "Sonnenuntergang", "Tageslicht", "sonnig", "UV", "Sonnenbrand",
        "Sonnencreme", "Morgensonne", "Nachmittagssonne", "Hitze",
        "Sommer", "heller Tag", "klarer Himmel", "Bräune",
        "Sonnencreme auftragen bevor man rausgeht",
        "den UV-Index für heute prüfen",
        "Sonnenaufgangswanderung am Samstag geplant",
        "Jalousien schließen die Sonne ist zu hell",
        "Pflanzen gießen bevor die Sonne zu heiß wird",
        "Picknick zum Sonnenuntergang am Strand",
        "Solaranlage auf dem Dach installieren",
        "sonniger Tag perfekt für ein Grillfest",
        "der Sonnenbrand von gestern tut noch weh",
        "Sonnencreme für den Urlaub kaufen",
        "Morgensonne scheint ins Küchenfenster",
        "Nachmittagssonne heizt das Büro auf",
        "Sommersonne lässt den Garten schnell wachsen",
        "in der starken Sonne einen Hut tragen",
        "die Sonne scheint lass uns spazieren gehen",
        "Wäsche in der Sonne trocknen",
        "in der Mittagspause in der Sonne sitzen",
        "Solarladegerät für den Campingausflug",
        "Tomaten pflanzen wo sie volle Sonne bekommen",
        "Sommerzeit beginnt nächste Woche",
        "Bräunungsstreifen vom Strandtag",
        "Sonnenbrille für die Heimfahrt nötig",
        "Sonne kommt nach dem Regen raus",
        "zu viel Sonne auf den Balkonpflanzen",
        "Hitzewelle am Wochenende erwartet",
        "den Sonnenschein genießen solange er da ist",
        "heller Tag für den Freiluftmarkt",
        "klarer Himmel und warme Sonne heute",
        "Vorhänge aufziehen um die Sonne reinzulassen",
        "der Garten braucht mehr Sonnenlicht",
        "Sonnenuntergang vom Dach aus beobachten",
        "früher Sonnenaufgang bedeutet längere Tage",
        "Solarmodule erzeugen heute gut Strom",
        "die Mittagssonne beim Laufen meiden",
        "Sonne geht im Herbst früher unter",
        "sonnige Terrasse für den Morgenkaffee",
        "Sonencreme auftragen vor dem Strand",
        "den UV-Indx für heute prüfn",
        "Sonnenaufgangswanderung am Samstg geplant",
        "Jalousien schleißen die Sonne ist zu hel",
        "Sonencreme für den Urlaub kaufn",
    ],
    ja=[
        "太陽", "日差し", "ソーラー", "日光", "日の出",
        "日の入り", "昼光", "晴れ", "紫外線", "日焼け",
        "日焼け止め", "朝日", "午後の日差し", "暑さ",
        "夏", "快晴", "青空", "日焼け跡",
        "外出前に日焼け止めを塗る",
        "今日の紫外線指数を確認する",
        "土曜日に日の出ハイキングの予定",
        "ブラインドを閉めて太陽がまぶしい",
        "太陽が暑くなる前に植物に水をやる",
        "ビーチで夕日のピクニック",
        "屋根にソーラーパネルを設置する",
        "晴れの日はバーベキューに最適",
        "昨日の日焼けがまだ痛い",
        "休暇用に日焼け止めを買う",
        "朝日がキッチンの窓から差し込む",
        "午後の日差しがオフィスを暑くする",
        "夏の太陽で庭がよく育つ",
        "強い日差しには帽子をかぶる",
        "太陽が出たから散歩に行こう",
        "洗濯物を日光で乾かす",
        "昼休みに日なたで座る",
        "キャンプ用のソーラー充電器",
        "日当たりの良い場所にトマトを植える",
        "来週からサマータイム開始",
        "ビーチの日焼け跡",
        "帰りの運転にサングラスが必要",
        "雨上がりに太陽が出てきた",
        "バルコニーの植物に日差しが強すぎる",
        "週末に猛暑が予想される",
        "晴れているうちに日光を楽しむ",
        "屋外マーケットにちょうどいい天気",
        "青空と暖かい太陽の一日",
        "カーテンを開けて日光を入れる",
        "庭にもっと日光が必要",
        "屋上から夕日を見る",
        "日の出が早まり日が長くなる",
        "ソーラーパネルが今日はよく発電している",
        "ランニング中は真昼の日差しを避ける",
        "秋になり太陽が早く沈む",
        "朝のコーヒーに日当たりのいいテラス",
        "外出前に日やけ止めを塗る",
        "今日の紫外せん指数を確にんする",
        "土曜日に日のでハイキングの予てい",
        "ブラインドを閉めて太よがまぶしい",
        "休暇用に日やけ止めをかう",
    ],
    fr=[
        "soleil", "ensoleillement", "solaire", "lumière du soleil", "lever de soleil",
        "coucher de soleil", "lumière du jour", "ensoleillé", "UV", "coup de soleil",
        "crème solaire", "soleil du matin", "soleil de l'après-midi", "chaleur",
        "été", "journée lumineuse", "ciel dégagé", "bronzage",
        "mettre de la crème solaire avant de sortir",
        "vérifier l'indice UV pour aujourd'hui",
        "randonnée au lever du soleil samedi",
        "fermer les stores le soleil est trop fort",
        "arroser les plantes avant que le soleil tape",
        "pique-nique au coucher du soleil sur la plage",
        "installation de panneaux solaires sur le toit",
        "journée ensoleillée parfaite pour un barbecue",
        "le coup de soleil d'hier fait encore mal",
        "acheter de la crème solaire pour les vacances",
        "le soleil du matin entre par la fenêtre de la cuisine",
        "le soleil de l'après-midi chauffe le bureau",
        "le soleil d'été fait pousser le jardin vite",
        "porter un chapeau sous le soleil fort",
        "le soleil est sorti allons nous promener",
        "faire sécher le linge au soleil",
        "s'asseoir au soleil pendant la pause déjeuner",
        "chargeur solaire pour le camping",
        "planter les tomates là où il y a plein soleil",
        "passage à l'heure d'été la semaine prochaine",
        "marques de bronzage après la journée plage",
        "besoin de lunettes de soleil pour rentrer",
        "le soleil revient après la pluie",
        "trop de soleil sur les plantes du balcon",
        "canicule prévue ce week-end",
        "profiter du soleil tant qu'il est là",
        "journée lumineuse pour le marché en plein air",
        "ciel dégagé et soleil chaud aujourd'hui",
        "ouvrir les rideaux pour laisser entrer le soleil",
        "le jardin a besoin de plus de lumière",
        "regarder le coucher de soleil depuis le toit",
        "lever de soleil tôt signifie journées plus longues",
        "les panneaux solaires produisent bien aujourd'hui",
        "éviter le soleil de midi en courant",
        "le soleil se couche plus tôt en automne",
        "terrasse ensoleillée pour le café du matin",
        "mettre de la crème soalire avant la plage",
        "vérifir l'indice UV pour aujoud'hui",
        "randonnée au lever du soliel samdi",
        "fermre les stores le soleil est trop frot",
        "achter de la crème solaire pour les vacnces",
    ],
    es=[
        "sol", "luz del sol", "solar", "rayos de sol", "amanecer",
        "atardecer", "luz del día", "soleado", "UV", "quemadura solar",
        "protector solar", "sol de la mañana", "sol de la tarde", "calor",
        "verano", "día brillante", "cielo despejado", "bronceado",
        "ponerse protector solar antes de salir",
        "revisar el índice UV para hoy",
        "caminata al amanecer programada para el sábado",
        "cerrar las persianas el sol es muy fuerte",
        "regar las plantas antes de que el sol caliente mucho",
        "picnic al atardecer en la playa",
        "instalación de paneles solares en el techo",
        "día soleado perfecto para una parrillada",
        "la quemadura solar de ayer todavía duele",
        "comprar protector solar para las vacaciones",
        "sol de la mañana entra por la ventana de la cocina",
        "el sol de la tarde calienta la oficina",
        "el sol de verano hace crecer rápido el jardín",
        "usar sombrero bajo el sol fuerte",
        "salió el sol vamos a caminar",
        "secar la ropa al sol",
        "sentarse al sol en la pausa del almuerzo",
        "cargador solar para el viaje de camping",
        "plantar los tomates donde les dé sol pleno",
        "cambio de horario de verano la próxima semana",
        "marcas de bronceado del día de playa",
        "necesito gafas de sol para volver a casa",
        "el sol sale después de la lluvia",
        "demasiado sol en las plantas del balcón",
        "ola de calor esperada este fin de semana",
        "disfrutar del sol mientras dure",
        "día brillante para el mercado al aire libre",
        "cielo despejado y sol cálido hoy",
        "abrir las cortinas para dejar entrar el sol",
        "el jardín necesita más luz solar",
        "ver el atardecer desde la azotea",
        "amanecer temprano significa días más largos",
        "los paneles solares generan buena energía hoy",
        "evitar el sol del mediodía al correr",
        "el sol se pone más temprano en otoño",
        "terraza soleada para el café de la mañana",
        "ponrse protector solar antes de la playa",
        "revsar el índice UV para hyo",
        "caminata al amanecr programada para el sábdao",
        "cerrar las persinas el sol es muy fuetre",
        "comprar protecor solar para las vacacones",
    ],
)

icon("syringe",
    en=[
        "syringe", "injection", "vaccine", "shot", "needle",
        "flu shot", "booster", "immunization", "jab", "insulin",
        "blood draw", "vaccination", "inoculation", "dose",
        "intramuscular", "subcutaneous", "IV", "serum",
        "get the flu shot before winter",
        "schedule the booster vaccine appointment",
        "insulin injection before meals",
        "blood draw at the lab this morning",
        "the nurse gave me the vaccine in the arm",
        "need to get the kids vaccinated",
        "tetanus shot after stepping on a nail",
        "covid booster available at the pharmacy",
        "allergy shots every two weeks",
        "bring the insulin syringe on the trip",
        "immunization records for school enrollment",
        "the doctor recommended a vitamin B12 shot",
        "subcutaneous injection in the abdomen",
        "flu season means time for the jab",
        "epinephrine injection for the allergic reaction",
        "the syringe was disposed in the sharps bin",
        "draw blood for the cholesterol test",
        "travel vaccines required for the visa",
        "annual flu vaccination at the office",
        "new needle for the insulin pen",
        "cortisone shot for the knee pain",
        "the nurse prepared the syringe and dose",
        "vaccination card updated after the booster",
        "second dose of the vaccine next month",
        "hep B immunization at the health center",
        "the pediatrician gave the baby the shots",
        "fill the syringe with the right dosage",
        "rabies vaccine after the animal bite",
        "iron infusion via IV at the clinic",
        "bring immunization records to the appointment",
        "get the shingles shot at the pharmacy",
        "the blood draw took only a minute",
        "local anesthetic injection before the procedure",
        "spring allergy shots start next week",
        "syrigne prepared by the nurse",
        "schedlue the booster vacine appointment",
        "insuiln injection befroe meals",
        "flu sht before winter",
        "vacination card updated after booster",
    ],
    ru=[
        "шприц", "инъекция", "вакцина", "укол", "игла",
        "прививка от гриппа", "бустер", "иммунизация", "прививка", "инсулин",
        "забор крови", "вакцинация", "прививочная доза", "доза",
        "внутримышечно", "подкожно", "капельница", "сыворотка",
        "сделать прививку от гриппа до зимы",
        "записаться на бустерную вакцинацию",
        "инъекция инсулина перед едой",
        "забор крови в лаборатории сегодня утром",
        "медсестра сделала мне укол в руку",
        "нужно привить детей",
        "укол от столбняка после наступил на гвоздь",
        "бустер от ковида доступен в аптеке",
        "уколы от аллергии каждые две недели",
        "взять шприц с инсулином в поездку",
        "прививочные записи для поступления в школу",
        "врач рекомендовал укол витамина B12",
        "подкожная инъекция в живот",
        "сезон гриппа значит пора делать прививку",
        "инъекция адреналина при аллергической реакции",
        "шприц утилизирован в контейнер для острых предметов",
        "взять кровь на анализ холестерина",
        "прививки для путешествий нужны для визы",
        "ежегодная вакцинация от гриппа на работе",
        "новая игла для инсулиновой ручки",
        "укол кортизона от боли в колене",
        "медсестра подготовила шприц и дозу",
        "прививочный сертификат обновлён после бустера",
        "вторая доза вакцины в следующем месяце",
        "прививка от гепатита B в поликлинике",
        "педиатр сделал малышу прививки",
        "наполнить шприц правильной дозировкой",
        "вакцина от бешенства после укуса животного",
        "капельница с железом в клинике",
        "принести прививочные записи на приём",
        "сделать прививку от опоясывающего лишая в аптеке",
        "забор крови занял всего минуту",
        "укол местной анестезии перед процедурой",
        "весенние уколы от аллергии начинаются на следующей неделе",
        "шприц подготволен медсестрой",
        "записатся на бустерную вакцинцию",
        "инъекця инсулина пред едой",
        "прививка от грипа до зимы",
        "прививочный сертифкат обновлён после бустра",
    ],
    de=[
        "Spritze", "Injektion", "Impfstoff", "Impfung", "Nadel",
        "Grippeimpfung", "Auffrischung", "Immunisierung", "Piks", "Insulin",
        "Blutentnahme", "Impfung", "Schutzimpfung", "Dosis",
        "intramuskulär", "subkutan", "Infusion", "Serum",
        "die Grippeimpfung vor dem Winter holen",
        "Termin für die Auffrischungsimpfung vereinbaren",
        "Insulinspritze vor den Mahlzeiten",
        "Blutentnahme im Labor heute Morgen",
        "die Krankenschwester hat mir den Impfstoff in den Arm gespritzt",
        "die Kinder müssen geimpft werden",
        "Tetanusspritze nach dem Tritt auf einen Nagel",
        "Covid-Auffrischung in der Apotheke verfügbar",
        "Allergiespritze alle zwei Wochen",
        "die Insulinspritze auf die Reise mitnehmen",
        "Impfpass für die Schulanmeldung",
        "der Arzt empfahl eine Vitamin-B12-Spritze",
        "subkutane Injektion in den Bauch",
        "Grippesaison heißt Zeit für die Impfung",
        "Adrenalinspritze bei allergischer Reaktion",
        "die Spritze wurde im Abwurfbehälter entsorgt",
        "Blut für den Cholesterintest abnehmen",
        "Reiseimpfungen für das Visum erforderlich",
        "jährliche Grippeimpfung im Büro",
        "neue Nadel für den Insulinpen",
        "Kortisonspritze gegen die Knieschmerzen",
        "die Krankenschwester hat Spritze und Dosis vorbereitet",
        "Impfpass nach der Auffrischung aktualisiert",
        "zweite Dosis des Impfstoffs nächsten Monat",
        "Hepatitis-B-Impfung im Gesundheitszentrum",
        "der Kinderarzt hat dem Baby die Impfungen gegeben",
        "die Spritze mit der richtigen Dosierung füllen",
        "Tollwutimpfung nach dem Tierbiss",
        "Eiseninfusion per IV in der Klinik",
        "Impfunterlagen zum Termin mitbringen",
        "Gürtelroseimpfung in der Apotheke holen",
        "die Blutentnahme dauerte nur eine Minute",
        "örtliche Betäubung per Spritze vor dem Eingriff",
        "Allergiespritze im Frühling beginnt nächste Woche",
        "Spritze von der Krankenschewster vorbereitet",
        "Termin für die Auffrischungsipmfung vereinbaren",
        "Insulinsprtze vor den Mahlzeien",
        "Grippeimpfug vor dem Wintr holen",
        "Impfpas nach der Auffrischng aktualisiert",
    ],
    ja=[
        "注射器", "注射", "ワクチン", "予防接種", "針",
        "インフルエンザ予防接種", "ブースター", "免疫", "接種", "インスリン",
        "採血", "ワクチン接種", "予防注射", "投与量",
        "筋肉注射", "皮下注射", "点滴", "血清",
        "冬前にインフルエンザの予防接種を受ける",
        "ブースターワクチンの予約を入れる",
        "食前にインスリン注射をする",
        "今朝ラボで採血する",
        "看護師が腕にワクチンを打ってくれた",
        "子どもたちの予防接種が必要",
        "釘を踏んだので破傷風の注射",
        "薬局でコロナブースター接種可能",
        "二週間ごとのアレルギー注射",
        "旅行にインスリン注射器を持っていく",
        "入学用の予防接種記録",
        "医師がビタミンB12注射を勧めた",
        "お腹への皮下注射",
        "インフルエンザの季節なので接種の時期",
        "アレルギー反応にエピネフリン注射",
        "注射器は専用容器に廃棄された",
        "コレステロール検査のために採血する",
        "ビザに必要な渡航ワクチン",
        "職場での年次インフルエンザ接種",
        "インスリンペンの新しい針",
        "膝の痛みにコルチゾン注射",
        "看護師が注射器と投与量を準備した",
        "ブースター後に接種証明書を更新",
        "来月ワクチンの二回目接種",
        "保健センターでB型肝炎の予防接種",
        "小児科医が赤ちゃんに予防接種をした",
        "注射器に正しい量を充填する",
        "動物に噛まれて狂犬病ワクチン",
        "クリニックで鉄剤の点滴",
        "予約に予防接種記録を持参する",
        "薬局で帯状疱疹ワクチンを受ける",
        "採血は一分で終わった",
        "処置前に局所麻酔の注射",
        "春のアレルギー注射が来週から開始",
        "注しゃ器を看護師が準備した",
        "ブースターワクチンの予やくを入れる",
        "食前にインスリンちゅうしゃをする",
        "冬まえにインフルエンザの予防せっしゅ",
        "せっしゅ証明書をブースター後に更新",
    ],
    fr=[
        "seringue", "injection", "vaccin", "piqûre", "aiguille",
        "vaccin contre la grippe", "rappel", "immunisation", "injection", "insuline",
        "prise de sang", "vaccination", "inoculation", "dose",
        "intramusculaire", "sous-cutané", "perfusion", "sérum",
        "se faire vacciner contre la grippe avant l'hiver",
        "prendre rendez-vous pour le rappel vaccinal",
        "injection d'insuline avant les repas",
        "prise de sang au labo ce matin",
        "l'infirmière m'a fait le vaccin dans le bras",
        "il faut faire vacciner les enfants",
        "piqûre antitétanique après avoir marché sur un clou",
        "rappel covid disponible à la pharmacie",
        "injections contre les allergies toutes les deux semaines",
        "prendre la seringue d'insuline pour le voyage",
        "carnet de vaccination pour l'inscription scolaire",
        "le médecin a recommandé une injection de vitamine B12",
        "injection sous-cutanée dans l'abdomen",
        "saison de la grippe il est temps de se faire piquer",
        "injection d'épinéphrine pour la réaction allergique",
        "la seringue a été jetée dans le conteneur à aiguilles",
        "faire une prise de sang pour le test de cholestérol",
        "vaccins de voyage nécessaires pour le visa",
        "vaccination annuelle contre la grippe au bureau",
        "nouvelle aiguille pour le stylo à insuline",
        "injection de cortisone pour la douleur au genou",
        "l'infirmière a préparé la seringue et la dose",
        "carnet de vaccination mis à jour après le rappel",
        "deuxième dose du vaccin le mois prochain",
        "vaccination hépatite B au centre de santé",
        "le pédiatre a fait les vaccins au bébé",
        "remplir la seringue avec le bon dosage",
        "vaccin antirabique après la morsure d'animal",
        "perfusion de fer en clinique",
        "apporter le carnet de vaccination au rendez-vous",
        "se faire vacciner contre le zona à la pharmacie",
        "la prise de sang n'a duré qu'une minute",
        "anesthésie locale par injection avant l'intervention",
        "injections contre les allergies de printemps la semaine prochaine",
        "seringue prépareé par l'infirmière",
        "prednre rendez-vous pour le rappel vaccinl",
        "injeciton d'insuline avant les repsa",
        "vaccin contre la grippe avnt l'hivr",
        "carnet de vaccinaton mis à jour après le rappl",
    ],
    es=[
        "jeringa", "inyección", "vacuna", "pinchazo", "aguja",
        "vacuna contra la gripe", "refuerzo", "inmunización", "vacuna", "insulina",
        "extracción de sangre", "vacunación", "inoculación", "dosis",
        "intramuscular", "subcutáneo", "suero intravenoso", "suero",
        "ponerse la vacuna de la gripe antes del invierno",
        "pedir cita para la vacuna de refuerzo",
        "inyección de insulina antes de las comidas",
        "extracción de sangre en el laboratorio esta mañana",
        "la enfermera me puso la vacuna en el brazo",
        "hay que vacunar a los niños",
        "vacuna antitetánica después de pisar un clavo",
        "refuerzo de covid disponible en la farmacia",
        "inyecciones para las alergias cada dos semanas",
        "llevar la jeringa de insulina en el viaje",
        "cartilla de vacunación para la inscripción escolar",
        "el médico recomendó una inyección de vitamina B12",
        "inyección subcutánea en el abdomen",
        "temporada de gripe hora de ponerse la vacuna",
        "inyección de epinefrina por la reacción alérgica",
        "la jeringa fue desechada en el contenedor de punzantes",
        "sacar sangre para el análisis de colesterol",
        "vacunas de viaje necesarias para el visado",
        "vacunación anual contra la gripe en la oficina",
        "aguja nueva para el bolígrafo de insulina",
        "inyección de cortisona para el dolor de rodilla",
        "la enfermera preparó la jeringa y la dosis",
        "cartilla de vacunación actualizada tras el refuerzo",
        "segunda dosis de la vacuna el mes que viene",
        "vacuna de hepatitis B en el centro de salud",
        "el pediatra le puso las vacunas al bebé",
        "llenar la jeringa con la dosis correcta",
        "vacuna antirrábica después de la mordedura de animal",
        "infusión de hierro por vía intravenosa en la clínica",
        "llevar la cartilla de vacunación a la cita",
        "ponerse la vacuna del herpes zóster en la farmacia",
        "la extracción de sangre duró solo un minuto",
        "anestesia local por inyección antes del procedimiento",
        "inyecciones de alergia de primavera empiezan la próxima semana",
        "jeringa preparada por la enferemra",
        "pedir ctia para la vacuna de refuezro",
        "inyeccón de insulina antes de las comids",
        "vacuna de la gripe anets del invierno",
        "cartilla de vacunción actualizada tras el refeurzo",
    ],
)

icon("taxi",
    en=[
        "taxi", "cab", "ride", "fare", "meter",
        "Uber", "Lyft", "rideshare", "pickup", "drop-off",
        "cabbie", "dispatch", "hail", "taxi stand",
        "yellow cab", "taxi rank", "transfer", "chauffeur",
        "call a taxi to the airport",
        "book a cab for the morning flight",
        "the taxi fare was thirty dollars",
        "hail a cab on the street corner",
        "Uber ride to the restaurant tonight",
        "Lyft pickup at the hotel lobby",
        "wait at the taxi stand outside the station",
        "split the cab fare with friends",
        "taxi meter running during the traffic jam",
        "the cabbie knows a shortcut to downtown",
        "schedule a rideshare for the concert",
        "drop-off at the office entrance",
        "taxi dispatch sent the car in five minutes",
        "need a ride home after the party",
        "yellow cab stuck in midtown traffic",
        "airport transfer booked for six am",
        "tip the taxi driver ten percent",
        "ride to the hospital was quick",
        "compare Uber and Lyft prices",
        "taxi reservation for the business meeting",
        "the driver arrived at the pickup spot",
        "shared ride to save money on the fare",
        "request a larger cab for the luggage",
        "the taxi dropped us at the wrong address",
        "late night cab home from the bar",
        "set pickup location in the ride app",
        "the fare includes a toll charge",
        "book a return taxi from the venue",
        "cab rank at the train station",
        "chauffeur service for the wedding day",
        "taxi voucher from the company",
        "rate the driver after the ride",
        "taxi to the conference center please",
        "pre-book a cab for the early morning",
        "call a taxi for the guest arriving at noon",
        "taksi to the airport please",
        "book a cab for the mornig flight",
        "the taxi fair was thirty dolars",
        "haul a cab on the stret corner",
        "Uber rdie to the resturant tonight",
    ],
    ru=[
        "такси", "кэб", "поездка", "тариф", "счётчик",
        "убер", "лифт", "райдшеринг", "посадка", "высадка",
        "таксист", "диспетчер", "поймать такси", "стоянка такси",
        "жёлтое такси", "такси-стоянка", "трансфер", "водитель",
        "вызвать такси в аэропорт",
        "заказать такси на утренний рейс",
        "поездка на такси стоила тридцать долларов",
        "поймать такси на углу улицы",
        "убер до ресторана сегодня вечером",
        "посадка в лифт у входа в отель",
        "ждать на стоянке такси у вокзала",
        "разделить стоимость такси с друзьями",
        "счётчик такси работает пока стоим в пробке",
        "таксист знает короткую дорогу в центр",
        "заказать райдшеринг на концерт",
        "высадка у входа в офис",
        "диспетчер такси прислал машину за пять минут",
        "нужна поездка домой после вечеринки",
        "жёлтое такси застряло в пробке в центре",
        "трансфер в аэропорт заказан на шесть утра",
        "дать таксисту десять процентов чаевых",
        "поездка в больницу была быстрой",
        "сравнить цены убера и лифта",
        "бронь такси на деловую встречу",
        "водитель приехал к месту посадки",
        "совместная поездка чтобы сэкономить",
        "заказать машину побольше для багажа",
        "такси высадило нас не по тому адресу",
        "ночное такси домой из бара",
        "указать место посадки в приложении",
        "тариф включает плату за проезд по платной дороге",
        "заказать обратное такси от места проведения",
        "стоянка такси у вокзала",
        "услуга водителя на свадьбу",
        "ваучер на такси от компании",
        "оценить водителя после поездки",
        "такси до конференц-центра пожалуйста",
        "заранее заказать такси на раннее утро",
        "вызвать такси для гостя прибывающего в полдень",
        "вызвть такси в аэропрт",
        "заказть такси на утрений рейс",
        "поймть такси на углу улцы",
        "убер до ресторна сегодня вечром",
        "бронь таски на деловую встречу",
    ],
    de=[
        "Taxi", "Fahrt", "Fahrpreis", "Taxameter", "Uber",
        "Lyft", "Mitfahrgelegenheit", "Abholung", "Absetzpunkt", "Taxifahrer",
        "Funkzentrale", "Taxi rufen", "Taxistand", "gelbes Taxi",
        "Taxireihe", "Transfer", "Chauffeur", "Fahrdienst",
        "ein Taxi zum Flughafen rufen",
        "ein Taxi für den Morgenflug buchen",
        "die Taxifahrt kostete dreißig Dollar",
        "ein Taxi an der Straßenecke heranwinken",
        "Uber zum Restaurant heute Abend",
        "Lyft-Abholung in der Hotellobby",
        "am Taxistand vor dem Bahnhof warten",
        "den Fahrpreis mit Freunden teilen",
        "Taxameter läuft während des Staus",
        "der Taxifahrer kennt eine Abkürzung ins Zentrum",
        "Mitfahrgelegenheit für das Konzert buchen",
        "Absetzpunkt am Büroeingang",
        "Funkzentrale schickte das Taxi in fünf Minuten",
        "brauche eine Fahrt nach Hause nach der Party",
        "gelbes Taxi steckt im Stadtverkehr fest",
        "Flughafentransfer für sechs Uhr morgens gebucht",
        "dem Taxifahrer zehn Prozent Trinkgeld geben",
        "Fahrt zum Krankenhaus war schnell",
        "Uber- und Lyft-Preise vergleichen",
        "Taxireservierung für das Geschäftstreffen",
        "der Fahrer kam am Abholpunkt an",
        "geteilte Fahrt um beim Fahrpreis zu sparen",
        "ein größeres Taxi für das Gepäck anfordern",
        "das Taxi hat uns an der falschen Adresse abgesetzt",
        "spätes Taxi nach Hause aus der Bar",
        "Abholort in der Fahr-App einstellen",
        "der Fahrpreis enthält eine Mautgebühr",
        "Rücktaxi vom Veranstaltungsort buchen",
        "Taxireihe am Bahnhof",
        "Chauffeurservice für den Hochzeitstag",
        "Taxigutschein von der Firma",
        "den Fahrer nach der Fahrt bewerten",
        "Taxi zum Kongresszentrum bitte",
        "Taxi für den frühen Morgen vorbuchen",
        "ein Taxi für den Gast bestellen der mittags ankommt",
        "ein Taksi zum Flughafen rufn",
        "Taxi für den Morgenflg buchen",
        "die Taxifahrt kostete driessig Dollar",
        "ein Taxi an der Strassenecke hernawinken",
        "Uber zum Resturant heute Abend",
    ],
    ja=[
        "タクシー", "乗車", "運賃", "メーター", "ウーバー",
        "リフト", "相乗り", "乗車場所", "降車場所", "タクシー運転手",
        "配車", "タクシーを呼ぶ", "タクシー乗り場", "イエローキャブ",
        "タクシー待ち", "送迎", "運転手", "ライドシェア",
        "空港までタクシーを呼ぶ",
        "朝のフライトにタクシーを予約する",
        "タクシー代は三十ドルだった",
        "通りの角でタクシーを拾う",
        "今夜レストランまでウーバーで行く",
        "ホテルのロビーでリフトに乗る",
        "駅前のタクシー乗り場で待つ",
        "タクシー代を友達と割り勘にする",
        "渋滞中にタクシーのメーターが回っている",
        "運転手が中心街への近道を知っている",
        "コンサートに相乗りを手配する",
        "オフィスの入口で降車",
        "配車センターが五分で車を送ってくれた",
        "パーティーの後に帰りの車が必要",
        "イエローキャブが市街地の渋滞にはまっている",
        "朝六時に空港送迎を予約済み",
        "タクシー運転手に十パーセントのチップを渡す",
        "病院までの乗車は早かった",
        "ウーバーとリフトの料金を比べる",
        "ビジネスミーティング用にタクシーを予約",
        "運転手が乗車場所に到着した",
        "運賃節約のため相乗りする",
        "荷物が多いので大きい車を頼む",
        "タクシーが間違った住所で降ろした",
        "バーから深夜タクシーで帰る",
        "アプリで乗車場所を設定する",
        "運賃に通行料が含まれている",
        "会場から帰りのタクシーを予約する",
        "駅のタクシー乗り場",
        "結婚式にハイヤーサービス",
        "会社からのタクシーチケット",
        "乗車後に運転手を評価する",
        "会議場までタクシーお願いします",
        "早朝のタクシーを事前予約する",
        "昼に到着するゲスト用にタクシーを手配",
        "空港までタクシーをよぶ",
        "朝のフライトにタクシーをよやくする",
        "タクシー台は三十ドルだた",
        "通りの角でタクシーをひろう",
        "今夜レストランまでウーバーでいく",
    ],
    fr=[
        "taxi", "course", "tarif", "compteur", "Uber",
        "Lyft", "covoiturage", "prise en charge", "dépose", "chauffeur de taxi",
        "central", "héler un taxi", "station de taxi", "taxi jaune",
        "file de taxis", "transfert", "chauffeur", "VTC",
        "appeler un taxi pour l'aéroport",
        "réserver un taxi pour le vol du matin",
        "la course en taxi a coûté trente dollars",
        "héler un taxi au coin de la rue",
        "Uber jusqu'au restaurant ce soir",
        "Lyft prise en charge dans le hall de l'hôtel",
        "attendre à la station de taxi devant la gare",
        "partager le prix de la course entre amis",
        "compteur du taxi qui tourne dans les embouteillages",
        "le chauffeur connaît un raccourci vers le centre",
        "réserver un covoiturage pour le concert",
        "dépose à l'entrée du bureau",
        "le central a envoyé le taxi en cinq minutes",
        "besoin d'une course pour rentrer après la fête",
        "taxi jaune coincé dans la circulation du centre",
        "transfert aéroport réservé pour six heures du matin",
        "donner dix pour cent de pourboire au chauffeur",
        "la course à l'hôpital a été rapide",
        "comparer les prix Uber et Lyft",
        "réservation de taxi pour la réunion d'affaires",
        "le chauffeur est arrivé au point de prise en charge",
        "course partagée pour économiser sur le tarif",
        "demander un taxi plus grand pour les bagages",
        "le taxi nous a déposés à la mauvaise adresse",
        "taxi de nuit pour rentrer du bar",
        "définir le lieu de prise en charge dans l'appli",
        "le tarif inclut un péage",
        "réserver un taxi retour depuis le lieu de l'événement",
        "file de taxis à la gare",
        "service de chauffeur pour le mariage",
        "bon de taxi de l'entreprise",
        "noter le chauffeur après la course",
        "taxi jusqu'au palais des congrès s'il vous plaît",
        "réserver un taxi à l'avance pour tôt le matin",
        "appeler un taxi pour l'invité qui arrive à midi",
        "appeler un taksi pour l'aéroprt",
        "réservr un taxi pour le vol du matin",
        "la course en taxi a cûoté trente dolars",
        "héler un taxi au coin de la ru",
        "Uber jusq'au restaurant ce soir",
    ],
    es=[
        "taxi", "viaje", "tarifa", "taxímetro", "Uber",
        "Lyft", "viaje compartido", "recogida", "punto de bajada", "taxista",
        "central de taxis", "parar un taxi", "parada de taxis", "taxi amarillo",
        "fila de taxis", "traslado", "chófer", "servicio de transporte",
        "llamar un taxi al aeropuerto",
        "reservar un taxi para el vuelo de la mañana",
        "el viaje en taxi costó treinta dólares",
        "parar un taxi en la esquina de la calle",
        "Uber al restaurante esta noche",
        "Lyft recogida en el lobby del hotel",
        "esperar en la parada de taxis fuera de la estación",
        "dividir la tarifa del taxi con los amigos",
        "taxímetro corriendo durante el embotellamiento",
        "el taxista conoce un atajo al centro",
        "reservar un viaje compartido para el concierto",
        "punto de bajada en la entrada de la oficina",
        "la central envió el taxi en cinco minutos",
        "necesito un viaje a casa después de la fiesta",
        "taxi amarillo atascado en el tráfico del centro",
        "traslado al aeropuerto reservado para las seis de la mañana",
        "darle diez por ciento de propina al taxista",
        "el viaje al hospital fue rápido",
        "comparar precios de Uber y Lyft",
        "reserva de taxi para la reunión de negocios",
        "el conductor llegó al punto de recogida",
        "viaje compartido para ahorrar en la tarifa",
        "pedir un taxi más grande para el equipaje",
        "el taxi nos dejó en la dirección equivocada",
        "taxi nocturno a casa desde el bar",
        "fijar el punto de recogida en la app",
        "la tarifa incluye un cargo por peaje",
        "reservar un taxi de vuelta desde el evento",
        "fila de taxis en la estación de tren",
        "servicio de chófer para el día de la boda",
        "vale de taxi de la empresa",
        "calificar al conductor después del viaje",
        "taxi al centro de convenciones por favor",
        "reservar un taxi con antelación para temprano",
        "pedir un taxi para el invitado que llega al mediodía",
        "llamar un taksi al aeropuerto",
        "reservar un taxi para el vuleo de la mañana",
        "el viaje en taxi costó trenta dólares",
        "parar un taxi en la esqunia de la calle",
        "Uber al resturante esta noche",
    ],
)

# I'll continue with the remaining icons in subsequent parts of the script.
# For now, let me write the execution logic and add more icons.

icon("telescope",
    en=[
        "telescope", "stargazing", "astronomy", "observatory", "celestial",
        "constellation", "moon", "planet", "comet", "galaxy",
        "nebula", "lens", "magnification", "night sky", "star",
        "optics", "astro", "Hubble",
        "set up the telescope for stargazing tonight",
        "take the kids to the observatory this weekend",
        "the telescope needs a new lens",
        "check the astronomy calendar for meteor showers",
        "can see Jupiter through the telescope",
        "star party at the local astronomy club",
        "adjust the telescope magnification for the moon",
        "spot the constellation Orion tonight",
        "the comet is visible with a small telescope",
        "buy a beginner telescope for my son",
        "galaxy photos from the backyard telescope",
        "nebula visible this month with a good scope",
        "clean the telescope lens before the trip",
        "align the telescope to the north star",
        "celestial event happening next week",
        "night sky is perfect for viewing tonight",
        "bring the telescope to the camping trip",
        "planet Mars is closest to Earth this month",
        "astronomy class uses the rooftop telescope",
        "new optics for the old telescope",
        "Hubble images of distant galaxies",
        "moon crater details through the telescope",
        "track the ISS with the telescope",
        "stargazing blanket and the telescope packed",
        "the telescope mount needs tightening",
        "solar filter for daytime telescope use",
        "book the observatory tour for saturday",
        "watch the lunar eclipse with the telescope",
        "deep sky objects through the reflector telescope",
        "repair the telescope tripod leg",
        "first time using a telescope was amazing",
        "astrophotography setup with the new telescope",
        "point the telescope at Saturn's rings",
        "telescope on the balcony for city stargazing",
        "telescop needs a new lens",
        "stargazig at the observatory this weekend",
        "chekc the astronomy calndar for meteors",
        "byu a beginner telescpe for my son",
        "celestail event happenig next week",
    ],
    ru=[
        "телескоп", "наблюдение за звёздами", "астрономия", "обсерватория", "небесный",
        "созвездие", "луна", "планета", "комета", "галактика",
        "туманность", "линза", "увеличение", "ночное небо", "звезда",
        "оптика", "астро", "хаббл",
        "поставить телескоп для наблюдения за звёздами вечером",
        "сводить детей в обсерваторию на выходных",
        "телескопу нужна новая линза",
        "проверить астрономический календарь на метеорные потоки",
        "юпитер виден через телескоп",
        "звёздная вечеринка в местном клубе астрономии",
        "настроить увеличение телескопа для луны",
        "найти созвездие ориона сегодня ночью",
        "комета видна в маленький телескоп",
        "купить начальный телескоп для сына",
        "фото галактик с дворового телескопа",
        "туманность видна в этом месяце с хорошим телескопом",
        "протереть линзу телескопа перед поездкой",
        "навести телескоп на полярную звезду",
        "небесное событие на следующей неделе",
        "ночное небо идеально для наблюдения сегодня",
        "взять телескоп в поход",
        "марс ближе всего к земле в этом месяце",
        "занятия астрономией на крыше с телескопом",
        "новая оптика для старого телескопа",
        "снимки хаббла далёких галактик",
        "детали кратеров луны через телескоп",
        "отслеживать мкс через телескоп",
        "плед для наблюдений и телескоп собраны",
        "крепление телескопа нужно подтянуть",
        "солнечный фильтр для дневного использования телескопа",
        "забронировать экскурсию в обсерваторию на субботу",
        "наблюдать лунное затмение через телескоп",
        "далёкие объекты через зеркальный телескоп",
        "починить ножку штатива телескопа",
        "первое использование телескопа было потрясающе",
        "астрофотография с новым телескопом",
        "навести телескоп на кольца сатурна",
        "телескоп на балконе для городских наблюдений",
        "телескпу нужна новая линза",
        "наблюдние за звёздами в обсерватории",
        "проверть астрономический калндарь",
        "купть начальный телескоп для сна",
        "небесное собтие на следующей неделе",
    ],
    de=[
        "Teleskop", "Sternbeobachtung", "Astronomie", "Sternwarte", "himmlisch",
        "Sternbild", "Mond", "Planet", "Komet", "Galaxie",
        "Nebel", "Linse", "Vergrößerung", "Nachthimmel", "Stern",
        "Optik", "Astro", "Hubble",
        "das Teleskop für die Sternbeobachtung heute Abend aufbauen",
        "die Kinder am Wochenende in die Sternwarte bringen",
        "das Teleskop braucht eine neue Linse",
        "den Astronomiekalender auf Meteorschauer prüfen",
        "Jupiter durch das Teleskop sehen",
        "Sternparty im lokalen Astronomieverein",
        "Teleskopvergrößerung für den Mond einstellen",
        "heute Nacht das Sternbild Orion finden",
        "der Komet ist mit einem kleinen Teleskop sichtbar",
        "ein Anfängerteleskop für meinen Sohn kaufen",
        "Galaxiefotos vom Gartenteleskop",
        "Nebel diesen Monat mit einem guten Teleskop sichtbar",
        "die Teleskoplinse vor der Reise reinigen",
        "das Teleskop auf den Polarstern ausrichten",
        "himmlisches Ereignis nächste Woche",
        "Nachthimmel ist perfekt für Beobachtung heute",
        "Teleskop zum Campingausflug mitnehmen",
        "Mars ist diesen Monat der Erde am nächsten",
        "Astronomieunterricht nutzt das Dachteleskop",
        "neue Optik für das alte Teleskop",
        "Hubble-Bilder entfernter Galaxien",
        "Mondkraterdetails durch das Teleskop",
        "die ISS mit dem Teleskop verfolgen",
        "Decke und Teleskop zum Sternegucken eingepackt",
        "Teleskopmontierung muss festgezogen werden",
        "Sonnenfilter für Teleskopnutzung am Tag",
        "Sternwartenführung für Samstag buchen",
        "Mondfinsternis mit dem Teleskop beobachten",
        "Deep-Sky-Objekte durch das Spiegelteleskop",
        "Stativbein des Teleskops reparieren",
        "erstes Mal mit einem Teleskop war erstaunlich",
        "Astrofotografie-Setup mit dem neuen Teleskop",
        "Teleskop auf die Saturnringe richten",
        "Teleskop auf dem Balkon für Stadtbeobachtung",
        "Teleskop bruacht eine neue Linse",
        "Sternbeobachtng in der Sternwarte",
        "den Astronomieklender auf Meteore prüfne",
        "ein Anfängertelskop für meinen Sohn kaufn",
        "himmlishces Ereignis nächste Woche",
    ],
    ja=[
        "望遠鏡", "天体観測", "天文学", "天文台", "天体",
        "星座", "月", "惑星", "彗星", "銀河",
        "星雲", "レンズ", "倍率", "夜空", "星",
        "光学", "アストロ", "ハッブル",
        "今夜天体観測のために望遠鏡を設置する",
        "週末に子どもたちを天文台に連れて行く",
        "望遠鏡に新しいレンズが必要",
        "流星群の天文カレンダーを確認する",
        "望遠鏡で木星が見える",
        "地元の天文クラブで星を見る会",
        "月用に望遠鏡の倍率を調整する",
        "今夜オリオン座を見つける",
        "小さい望遠鏡で彗星が見える",
        "息子に初心者用の望遠鏡を買う",
        "庭の望遠鏡で撮った銀河の写真",
        "今月は良い望遠鏡で星雲が見える",
        "旅行前に望遠鏡のレンズを拭く",
        "望遠鏡を北極星に合わせる",
        "来週天体イベントがある",
        "今夜は観測に最高の夜空",
        "キャンプに望遠鏡を持って行く",
        "今月は火星が地球に最も近い",
        "天文学の授業で屋上の望遠鏡を使う",
        "古い望遠鏡に新しい光学部品",
        "ハッブルが撮影した遠い銀河の画像",
        "望遠鏡で月のクレーターの詳細",
        "望遠鏡でISSを追跡する",
        "観測用ブランケットと望遠鏡を準備した",
        "望遠鏡のマウントを締め直す必要がある",
        "日中の望遠鏡使用にソーラーフィルター",
        "土曜日に天文台ツアーを予約する",
        "望遠鏡で月食を見る",
        "反射望遠鏡でディープスカイ天体",
        "望遠鏡の三脚の脚を修理する",
        "初めて望遠鏡を使って感動した",
        "新しい望遠鏡で天体写真のセットアップ",
        "望遠鏡を土星の輪に向ける",
        "バルコニーの望遠鏡で都市部の天体観測",
        "望遠きょうに新しいレンズが必要",
        "天文台で天たい観測をする",
        "流星群のてんもんカレンダーを確認",
        "息子に初心しゃ用の望遠鏡を買う",
        "来週てんたいイベントがある",
    ],
    fr=[
        "télescope", "observation des étoiles", "astronomie", "observatoire", "céleste",
        "constellation", "lune", "planète", "comète", "galaxie",
        "nébuleuse", "lentille", "grossissement", "ciel nocturne", "étoile",
        "optique", "astro", "Hubble",
        "installer le télescope pour observer les étoiles ce soir",
        "emmener les enfants à l'observatoire ce week-end",
        "le télescope a besoin d'une nouvelle lentille",
        "vérifier le calendrier astronomique pour les pluies de météores",
        "on voit Jupiter avec le télescope",
        "soirée étoiles au club d'astronomie local",
        "régler le grossissement du télescope pour la lune",
        "repérer la constellation d'Orion ce soir",
        "la comète est visible avec un petit télescope",
        "acheter un télescope débutant pour mon fils",
        "photos de galaxies avec le télescope du jardin",
        "nébuleuse visible ce mois-ci avec un bon télescope",
        "nettoyer la lentille du télescope avant le voyage",
        "aligner le télescope sur l'étoile polaire",
        "événement céleste la semaine prochaine",
        "le ciel nocturne est parfait pour observer ce soir",
        "apporter le télescope au camping",
        "Mars est au plus près de la Terre ce mois-ci",
        "cours d'astronomie avec le télescope sur le toit",
        "nouvelle optique pour le vieux télescope",
        "images Hubble de galaxies lointaines",
        "détails des cratères lunaires au télescope",
        "suivre l'ISS avec le télescope",
        "couverture et télescope prêts pour les étoiles",
        "la monture du télescope doit être resserrée",
        "filtre solaire pour utiliser le télescope de jour",
        "réserver la visite de l'observatoire pour samedi",
        "observer l'éclipse lunaire avec le télescope",
        "objets du ciel profond au télescope réflecteur",
        "réparer le pied du trépied du télescope",
        "la première fois avec un télescope était incroyable",
        "astrophotographie avec le nouveau télescope",
        "pointer le télescope vers les anneaux de Saturne",
        "télescope sur le balcon pour observer en ville",
        "téléscope a besoin d'une nouvell lentille",
        "observaton des étoiles à l'observatoire",
        "vérifer le calendrier astronmique pour les météors",
        "achteer un télescope débutnt pour mon fils",
        "événemnt céleste la semaine prochiane",
    ],
    es=[
        "telescopio", "observación de estrellas", "astronomía", "observatorio", "celeste",
        "constelación", "luna", "planeta", "cometa", "galaxia",
        "nebulosa", "lente", "aumento", "cielo nocturno", "estrella",
        "óptica", "astro", "Hubble",
        "montar el telescopio para ver estrellas esta noche",
        "llevar a los niños al observatorio este fin de semana",
        "el telescopio necesita una lente nueva",
        "revisar el calendario astronómico para lluvias de meteoros",
        "se ve Júpiter por el telescopio",
        "noche de estrellas en el club de astronomía local",
        "ajustar el aumento del telescopio para la luna",
        "encontrar la constelación de Orión esta noche",
        "el cometa se ve con un telescopio pequeño",
        "comprar un telescopio para principiantes para mi hijo",
        "fotos de galaxias con el telescopio del jardín",
        "nebulosa visible este mes con un buen telescopio",
        "limpiar la lente del telescopio antes del viaje",
        "alinear el telescopio con la estrella polar",
        "evento celeste la próxima semana",
        "el cielo nocturno es perfecto para observar hoy",
        "llevar el telescopio al campamento",
        "Marte está más cerca de la Tierra este mes",
        "clase de astronomía usa el telescopio de la azotea",
        "nueva óptica para el telescopio viejo",
        "imágenes del Hubble de galaxias lejanas",
        "detalles de cráteres lunares por el telescopio",
        "rastrear la EEI con el telescopio",
        "manta y telescopio listos para las estrellas",
        "la montura del telescopio necesita ajuste",
        "filtro solar para usar el telescopio de día",
        "reservar el tour del observatorio para el sábado",
        "ver el eclipse lunar con el telescopio",
        "objetos de cielo profundo con el telescopio reflector",
        "reparar la pata del trípode del telescopio",
        "la primera vez con un telescopio fue increíble",
        "astrofotografía con el telescopio nuevo",
        "apuntar el telescopio a los anillos de Saturno",
        "telescopio en el balcón para observar en la ciudad",
        "telescoipo necesita una lente neuva",
        "observación de estrelals en el observatorio",
        "revsar el calendario astronómco para meteoros",
        "comprar un telescoipo para principiantes",
        "evento celste la próxima semna",
    ],
)

# ============================================================================
# EXECUTION LOGIC
# ============================================================================

def clean_en(texts, icon_name):
    """Remove devspeak, visual, and obvious boundary phrases from EN."""
    cleaned = []
    for t in texts:
        if is_bad_en(t):
            continue
        cleaned.append(t)
    return cleaned

def clean_ru(texts, icon_name):
    """Remove devspeak, visual, boundary (last ~6), and mixed English from RU."""
    cleaned = []
    for t in texts:
        if is_bad_ru(t):
            continue
        cleaned.append(t)
    return cleaned

def process_icon(icon_name, data):
    """Process a single icon: clean existing, merge new, write all 6 languages."""
    icon_dir = ICONS_DIR / icon_name
    results = {}

    for lang in ["en", "ru", "de", "ja", "fr", "es"]:
        csv_path = icon_dir / f"train_{lang}.csv"
        existing = read_csv(csv_path)

        if lang in data:
            new_phrases = data[lang]
        else:
            new_phrases = []

        # Clean existing EN/RU
        if lang == "en":
            existing = clean_en(existing, icon_name)
        elif lang == "ru":
            existing = clean_ru(existing, icon_name)

        # Merge: existing + new (dedup)
        seen = set()
        merged = []
        for t in existing:
            t_lower = t.strip().lower()
            if t_lower not in seen and t.strip():
                seen.add(t_lower)
                merged.append(t.strip())
        for t in new_phrases:
            t_lower = t.strip().lower()
            if t_lower not in seen and t.strip():
                seen.add(t_lower)
                merged.append(t.strip())

        # Trim to 60 if over
        if len(merged) > 60:
            merged = merged[:60]

        results[lang] = merged

        # Write
        write_csv(csv_path, merged, icon_name)

    return {lang: len(v) for lang, v in results.items()}


def main():
    print(f"Processing {len(ICONS)} icons...\n")
    issues = []
    for icon_name in sorted(ICONS.keys()):
        data = ICONS[icon_name]
        counts = process_icon(icon_name, data)
        status = " ".join(f"{l}={c}" for l, c in counts.items())
        ok = all(c == 60 for c in counts.values())
        flag = "" if ok else " *** NEEDS FIX ***"
        print(f"  {icon_name}: {status}{flag}")
        if not ok:
            issues.append((icon_name, counts))

    print(f"\nDone. {len(ICONS)} icons processed.")
    if issues:
        print(f"\n{len(issues)} icons need fixing:")
        for name, counts in issues:
            print(f"  {name}: {counts}")
    else:
        print("All icons have exactly 60 phrases per language.")


if __name__ == "__main__":
    main()
