#!/usr/bin/env python3
"""Task-007 part A: snowman, socks, speaker"""
from gen_icons_task_007_common import build_icon

# ── snowman ──────────────────────────────────────────────────────────────────
build_icon("snowman", {
    "en": [
        # keywords (~18)
        "snowman",
        "frosty",
        "frost",
        "snow",
        "winter",
        "decoration",
        "snow day",
        "winter fun",
        "snowball",
        "carrot nose",
        "top hat",
        "scarf",
        "coal buttons",
        "stick arms",
        "snow fort",
        "ice",
        "frozen",
        "cold weather",
        # phrases (~37)
        "build a snowman with the kids after school",
        "build a snowman after a heavy snowfall",
        "children rolling snowballs to build a snowman",
        "make a snowman in the front yard this weekend",
        "buy a carrot for the snowman nose",
        "find sticks for snowman arms",
        "get coal for the snowman buttons",
        "put the top hat on the snowman",
        "wrap the scarf around the snowman",
        "take a photo of the snowman before it melts",
        "snowman melted overnight need to rebuild",
        "plan a snowman building contest for the kids",
        "check the weather for snowman building conditions",
        "shovel the driveway and then build a snowman",
        "get the kids bundled up for snowman time",
        "buy decorations for the yard snowman",
        "snowman competition at the neighborhood party",
        "winter break activity build a giant snowman",
        "dress the snowman with dad's old hat",
        "set up a snowman decoration on the porch",
        "the kids want to build a snowman tomorrow",
        "pack snowballs tight so the snowman stands up",
        "add a scarf and mittens to the snowman",
        "need more snow before we can build a snowman",
        "frosty morning perfect for a snowman",
        "cold enough to build a snowman finally",
        "bring extra carrots for the snowman nose",
        "snowman building supplies from the garage",
        "rake leaves then build a snow fort and snowman",
        "winter activity list snowman and snow angels",
        "plan the snow day schedule with the family",
        "frost on the ground after the snowstorm",
        "buy winter decorations for the front yard",
        "put up the inflatable snowman decoration",
        "order a snowman ornament for the tree",
        "pick up a snowman cookie cutter for baking",
        "the snowman lost its nose overnight find another carrot",
        # typos (5)
        "buidl a snowman with the kids",
        "snowmaan wearing a top hat",
        "snoman standing in the yard",
        "snowamn built in the yard",
        "snoaman with a carrot nose",
    ],
    "ru": [
        # keywords (~18)
        "снеговик",
        "морозный",
        "изморозь",
        "снег",
        "зима",
        "украшение",
        "снежный день",
        "зимние забавы",
        "снежок",
        "морковный нос",
        "цилиндр",
        "шарф",
        "угольные пуговицы",
        "руки-палки",
        "снежная крепость",
        "лёд",
        "замёрзший",
        "холодная погода",
        # phrases (~37)
        "слепить снеговика с детьми после школы",
        "слепить снеговика после сильного снегопада",
        "дети катают снежные шары для снеговика",
        "сделать снеговика во дворе в выходные",
        "купить морковку для носа снеговика",
        "найти палки для рук снеговика",
        "достать уголь для пуговиц снеговика",
        "надеть цилиндр на снеговика",
        "обернуть шарф вокруг снеговика",
        "сфотографировать снеговика пока не растаял",
        "снеговик растаял за ночь надо слепить нового",
        "устроить конкурс снеговиков для детей",
        "проверить погоду для лепки снеговика",
        "расчистить дорожку и слепить снеговика",
        "одеть детей потеплее для лепки снеговика",
        "купить украшения для снеговика во дворе",
        "конкурс снеговиков на соседском празднике",
        "на каникулах слепить огромного снеговика",
        "нарядить снеговика в старую шляпу папы",
        "поставить снеговика-украшение на крыльцо",
        "дети хотят слепить снеговика завтра",
        "плотно утрамбовать снежки чтобы снеговик стоял",
        "добавить шарф и варежки снеговику",
        "нужно больше снега чтобы слепить снеговика",
        "морозное утро отлично для снеговика",
        "наконец достаточно холодно для снеговика",
        "взять запасные морковки для носа снеговика",
        "достать из гаража всё для снеговика",
        "сгрести листья потом слепить крепость и снеговика",
        "зимний список дел снеговик и снежные ангелы",
        "спланировать снежный день с семьёй",
        "иней на земле после снегопада",
        "купить зимние украшения для двора",
        "поставить надувного снеговика во дворе",
        "заказать ёлочную игрушку в виде снеговика",
        "купить формочку для печенья в виде снеговика",
        "снеговик потерял нос за ночь найти другую морковку",
        # typos (5)
        "слеипть снеговика с детьми",
        "снеговик в цилинрде",
        "снеговик стоит во двроре",
        "снеговик слеплне во дворе",
        "снеговик с моркоывным носом",
    ],
    "de": [
        # keywords (~18)
        "Schneemann",
        "frostig",
        "Frost",
        "Schnee",
        "Winter",
        "Dekoration",
        "Schneetag",
        "Winterspaß",
        "Schneeball",
        "Karottennase",
        "Zylinder",
        "Schal",
        "Kohleknöpfe",
        "Stockarme",
        "Schneeburg",
        "Eis",
        "gefroren",
        "kaltes Wetter",
        # phrases (~37)
        "Schneemann bauen mit den Kindern nach der Schule",
        "nach starkem Schneefall einen Schneemann bauen",
        "Kinder rollen Schneebälle für den Schneemann",
        "am Wochenende einen Schneemann im Garten bauen",
        "Karotte für die Schneemann-Nase kaufen",
        "Stöcke für die Schneemann-Arme suchen",
        "Kohle für die Schneemann-Knöpfe holen",
        "dem Schneemann den Zylinder aufsetzen",
        "den Schal um den Schneemann wickeln",
        "Foto vom Schneemann machen bevor er schmilzt",
        "Schneemann über Nacht geschmolzen neu bauen",
        "Schneemann-Wettbewerb für die Kinder planen",
        "Wetter prüfen ob man einen Schneemann bauen kann",
        "Einfahrt räumen und dann Schneemann bauen",
        "Kinder warm anziehen für den Schneemann",
        "Deko für den Schneemann im Garten kaufen",
        "Schneemann-Wettbewerb auf der Nachbarschaftsfeier",
        "in den Winterferien einen riesigen Schneemann bauen",
        "Schneemann mit Papas altem Hut dekorieren",
        "Schneemann-Deko auf der Veranda aufstellen",
        "die Kinder wollen morgen einen Schneemann bauen",
        "Schneebälle fest packen damit der Schneemann steht",
        "Schal und Handschuhe an den Schneemann hängen",
        "mehr Schnee nötig bevor wir den Schneemann bauen",
        "frostiger Morgen perfekt für einen Schneemann",
        "endlich kalt genug für einen Schneemann",
        "Ersatzkarotten für die Schneemann-Nase mitnehmen",
        "Schneemann-Zubehör aus der Garage holen",
        "Laub harken dann Schneeburg und Schneemann bauen",
        "Winterliste Schneemann und Schneeengel",
        "Schneetag mit der Familie planen",
        "Frost auf dem Boden nach dem Schneesturm",
        "Winterdeko für den Vorgarten kaufen",
        "aufblasbaren Schneemann im Garten aufstellen",
        "Schneemann-Christbaumkugel bestellen",
        "Schneemann-Ausstechform zum Backen besorgen",
        "der Schneemann hat über Nacht die Nase verloren",
        # typos (5)
        "Schneemann baeun mit den Kindern",
        "Schneemnn im Garten aufstellen",
        "Schnemann mit Schal dekorieren",
        "Schneemaan steht im Vorgarten",
        "Schenemann-Nase ist eine Karotte",
    ],
    "ja": [
        # keywords (~18)
        "雪だるま",
        "霜",
        "雪",
        "冬",
        "飾り",
        "雪の日",
        "冬の遊び",
        "雪玉",
        "にんじんの鼻",
        "シルクハット",
        "マフラー",
        "石炭のボタン",
        "枝の腕",
        "雪の要塞",
        "氷",
        "凍った",
        "寒い天気",
        "雪景色",
        # phrases (~37)
        "放課後に子供と雪だるまを作る",
        "大雪の後に雪だるまを作る",
        "子供たちが雪だるま用の雪玉を転がしている",
        "週末に庭で雪だるまを作る",
        "雪だるまの鼻用ににんじんを買う",
        "雪だるまの腕用の枝を探す",
        "雪だるまのボタン用の石炭を用意する",
        "雪だるまにシルクハットをかぶせる",
        "雪だるまにマフラーを巻く",
        "溶ける前に雪だるまの写真を撮る",
        "雪だるまが夜中に溶けたので作り直す",
        "子供向けの雪だるまコンテストを企画する",
        "雪だるま作りに適した天気か確認する",
        "車道を雪かきしてから雪だるまを作る",
        "雪だるま作りのために子供に暖かい服を着せる",
        "庭の雪だるま用の飾りを買う",
        "近所のパーティーで雪だるまコンテスト",
        "冬休みに巨大な雪だるまを作る",
        "パパの古い帽子で雪だるまを飾る",
        "玄関に雪だるまの飾りを置く",
        "子供たちが明日雪だるまを作りたがっている",
        "雪玉をしっかり固めて雪だるまを立たせる",
        "雪だるまにマフラーと手袋をつける",
        "雪だるまを作るにはもっと雪が必要",
        "霜の朝は雪だるま作りにぴったり",
        "やっと雪だるまを作れるくらい寒くなった",
        "雪だるまの鼻用に予備のにんじんを持っていく",
        "ガレージから雪だるまの道具を出す",
        "落ち葉を集めてから雪の要塞と雪だるまを作る",
        "冬のやることリスト雪だるまと雪の天使",
        "家族で雪の日の予定を立てる",
        "吹雪の後に地面に霜が降りた",
        "庭の冬の飾りを買う",
        "膨らむ雪だるまの飾りを庭に置く",
        "雪だるまのオーナメントを注文する",
        "雪だるまのクッキー型を買う",
        "雪だるまが夜のうちに鼻をなくしたにんじんを探す",
        # typos (5)
        "雪だるまをつくるる",
        "雪だるまのの鼻ににんじん",
        "雪だるまをを作り直す",
        "子供とと雪だるまを作る",
        "庭でで雪だるまを飾る",
    ],
    "fr": [
        # keywords (~18)
        "bonhomme de neige",
        "givré",
        "givre",
        "neige",
        "hiver",
        "décoration",
        "jour de neige",
        "amusement d'hiver",
        "boule de neige",
        "nez en carotte",
        "chapeau haut de forme",
        "écharpe",
        "boutons en charbon",
        "bras en bâtons",
        "fort de neige",
        "glace",
        "gelé",
        "temps froid",
        # phrases (~37)
        "construire un bonhomme de neige avec les enfants après l'école",
        "faire un bonhomme de neige après une grosse chute de neige",
        "les enfants roulent des boules pour le bonhomme de neige",
        "faire un bonhomme de neige dans le jardin ce week-end",
        "acheter une carotte pour le nez du bonhomme de neige",
        "chercher des bâtons pour les bras du bonhomme de neige",
        "trouver du charbon pour les boutons du bonhomme de neige",
        "mettre le chapeau sur le bonhomme de neige",
        "enrouler l'écharpe autour du bonhomme de neige",
        "prendre une photo du bonhomme de neige avant qu'il fonde",
        "le bonhomme de neige a fondu cette nuit il faut le refaire",
        "organiser un concours de bonhommes de neige pour les enfants",
        "vérifier la météo pour construire un bonhomme de neige",
        "déneiger l'allée puis construire un bonhomme de neige",
        "habiller les enfants chaudement pour le bonhomme de neige",
        "acheter des décorations pour le bonhomme de neige du jardin",
        "concours de bonhommes de neige à la fête du quartier",
        "pendant les vacances d'hiver construire un énorme bonhomme de neige",
        "décorer le bonhomme de neige avec le vieux chapeau de papa",
        "installer un bonhomme de neige décoratif sur le porche",
        "les enfants veulent faire un bonhomme de neige demain",
        "bien tasser les boules pour que le bonhomme de neige tienne",
        "ajouter écharpe et moufles au bonhomme de neige",
        "il faut plus de neige pour construire un bonhomme de neige",
        "matin givré parfait pour un bonhomme de neige",
        "enfin assez froid pour un bonhomme de neige",
        "prendre des carottes de rechange pour le nez du bonhomme",
        "sortir le matériel pour bonhomme de neige du garage",
        "ratisser les feuilles puis construire un fort et un bonhomme",
        "liste d'hiver bonhomme de neige et anges de neige",
        "planifier la journée neige avec la famille",
        "givre au sol après la tempête de neige",
        "acheter des décorations d'hiver pour le jardin",
        "installer le bonhomme de neige gonflable dans le jardin",
        "commander une boule de Noël bonhomme de neige",
        "acheter un emporte-pièce bonhomme de neige",
        "le bonhomme de neige a perdu son nez trouver une carotte",
        # typos (5)
        "construrie un bonhomme de neige avec les enfants",
        "bonhomem de neige dans le jardin",
        "bonhomme de neige fonud cette nuit",
        "bonhomme de neieg avec chapeau",
        "bonhomme de neige décoré avce écharpe",
    ],
    "es": [
        # keywords (~18)
        "muñeco de nieve",
        "helado",
        "escarcha",
        "nieve",
        "invierno",
        "decoración",
        "día de nieve",
        "diversión invernal",
        "bola de nieve",
        "nariz de zanahoria",
        "sombrero de copa",
        "bufanda",
        "botones de carbón",
        "brazos de palo",
        "fuerte de nieve",
        "hielo",
        "congelado",
        "clima frío",
        # phrases (~37)
        "hacer un muñeco de nieve con los niños después de la escuela",
        "construir un muñeco de nieve después de una gran nevada",
        "los niños hacen bolas de nieve para el muñeco",
        "hacer un muñeco de nieve en el jardín este fin de semana",
        "comprar una zanahoria para la nariz del muñeco de nieve",
        "buscar palos para los brazos del muñeco de nieve",
        "conseguir carbón para los botones del muñeco de nieve",
        "ponerle el sombrero de copa al muñeco de nieve",
        "enrollar la bufanda al muñeco de nieve",
        "tomar una foto del muñeco antes de que se derrita",
        "el muñeco de nieve se derritió anoche hay que rehacerlo",
        "organizar un concurso de muñecos de nieve para los niños",
        "revisar el clima para hacer un muñeco de nieve",
        "limpiar la entrada y luego hacer un muñeco de nieve",
        "abrigar a los niños para hacer el muñeco de nieve",
        "comprar adornos para el muñeco de nieve del jardín",
        "concurso de muñecos de nieve en la fiesta del barrio",
        "en vacaciones de invierno hacer un muñeco de nieve gigante",
        "decorar el muñeco con el sombrero viejo de papá",
        "poner un muñeco de nieve decorativo en el porche",
        "los niños quieren hacer un muñeco de nieve mañana",
        "apretar bien las bolas para que el muñeco se sostenga",
        "añadir bufanda y guantes al muñeco de nieve",
        "necesitamos más nieve para hacer un muñeco",
        "mañana helada perfecta para un muñeco de nieve",
        "por fin hace suficiente frío para un muñeco de nieve",
        "llevar zanahorias de repuesto para la nariz del muñeco",
        "sacar lo necesario del garaje para el muñeco de nieve",
        "rastrillar hojas y luego hacer un fuerte y un muñeco",
        "lista de invierno muñeco de nieve y ángeles de nieve",
        "planificar el día de nieve con la familia",
        "escarcha en el suelo después de la tormenta de nieve",
        "comprar decoraciones de invierno para el jardín",
        "poner el muñeco de nieve inflable en el jardín",
        "pedir un adorno navideño de muñeco de nieve",
        "comprar un molde de galleta de muñeco de nieve",
        "el muñeco perdió la nariz buscar otra zanahoria",
        # typos (5)
        "hacer un muñeco de neive con los niños",
        "muñeco de nieve en el jadín",
        "muñeco de nieve se derritó anoche",
        "muñeco de nieve con bufnada",
        "muñeco de neive decorado con sombrero",
    ],
})


# ── socks ────────────────────────────────────────────────────────────────────
build_icon("socks", {
    "en": [
        # keywords (~18)
        "socks",
        "pair",
        "hosiery",
        "feet",
        "warm",
        "winter",
        "clothing",
        "ankle socks",
        "wool socks",
        "dress socks",
        "athletic socks",
        "compression socks",
        "crew socks",
        "no-show socks",
        "fuzzy socks",
        "sock drawer",
        "mismatched socks",
        "toe socks",
        # phrases (~37)
        "buy new socks at the store",
        "organize the sock drawer this weekend",
        "throw out socks with holes in them",
        "pack extra socks for the camping trip",
        "pick up warm wool socks for winter",
        "match all the clean socks from the laundry",
        "buy compression socks for the long flight",
        "grab a pair of socks before leaving the house",
        "order fun patterned socks online",
        "the dryer keeps eating my socks",
        "need to buy dress socks for the interview",
        "find matching socks for the kids in the morning",
        "put on thick socks before going outside",
        "pick up socks for the whole family",
        "Christmas stocking stuffed with new socks",
        "donate old socks to the clothing drive",
        "warm socks and hot chocolate on a cold night",
        "my feet are cold I need thicker socks",
        "sort the laundry and pair up all the socks",
        "buy non-slip socks for the hospital visit",
        "hang socks to dry instead of using the dryer",
        "remind the kids to change their socks daily",
        "running low on clean socks do laundry tonight",
        "buy athletic socks for the gym",
        "new hiking socks for the trail",
        "bamboo socks are supposed to be really comfy",
        "socks keep sliding down in my boots",
        "get holiday themed socks as gifts",
        "merino wool socks for cold weather",
        "seamless socks for sensitive feet",
        "the baby pulled off both socks again",
        "stock up on socks during the sale",
        "cozy socks for movie night",
        "socks as a stocking stuffer gift idea",
        "put wet socks by the heater to dry",
        "darning the hole in my favorite socks",
        "need waterproof socks for the hike",
        # typos (5)
        "buy new scoks at the store",
        "orgnaize the sock drawer",
        "piar of warm socks for winter",
        "sock darwer organized by color",
        "compresion socks for travel",
    ],
    "ru": [
        # keywords (~18)
        "носки",
        "пара",
        "чулочные изделия",
        "ноги",
        "тёплые",
        "зима",
        "одежда",
        "носки по щиколотку",
        "шерстяные носки",
        "нарядные носки",
        "спортивные носки",
        "компрессионные носки",
        "носки средней длины",
        "невидимые носки",
        "пушистые носки",
        "ящик для носков",
        "непарные носки",
        "носки с пальцами",
        # phrases (~37)
        "купить новые носки в магазине",
        "разобрать ящик с носками в выходные",
        "выбросить носки с дырками",
        "взять запасные носки в поход",
        "купить тёплые шерстяные носки на зиму",
        "разобрать чистые носки по парам после стирки",
        "купить компрессионные носки для перелёта",
        "взять пару носков перед выходом из дома",
        "заказать весёлые носки с узором онлайн",
        "сушилка опять съела один носок",
        "нужны нарядные носки для собеседования",
        "утром найти парные носки для детей",
        "надеть толстые носки перед выходом на улицу",
        "купить носки для всей семьи",
        "рождественский чулок с новыми носками внутри",
        "отдать старые носки на благотворительность",
        "тёплые носки и горячий шоколад холодным вечером",
        "ноги мёрзнут нужны носки потолще",
        "разобрать бельё и подобрать пары носков",
        "купить нескользящие носки для больницы",
        "повесить носки сушиться вместо сушилки",
        "напомнить детям менять носки каждый день",
        "чистые носки заканчиваются постирать вечером",
        "купить спортивные носки для зала",
        "новые треккинговые носки для похода",
        "бамбуковые носки говорят очень удобные",
        "носки сползают в ботинках",
        "купить праздничные носки в подарок",
        "носки из мериноса для холодной погоды",
        "бесшовные носки для чувствительных ног",
        "малыш опять стянул оба носка",
        "затариться носками пока распродажа",
        "уютные носки для вечера кино",
        "носки как подарок в рождественский чулок",
        "положить мокрые носки к батарее сушиться",
        "заштопать дырку в любимых носках",
        "нужны водонепроницаемые носки для похода",
        # typos (5)
        "купить новые нокси в магазине",
        "разобрать ящки с носками",
        "пара тёплых ноосков на зиму",
        "ящик носоков разложен по цвету",
        "компресионные носки для путешествий",
    ],
    "de": [
        # keywords (~18)
        "Socken",
        "Paar",
        "Strumpfwaren",
        "Füße",
        "warm",
        "Winter",
        "Kleidung",
        "Knöchelsocken",
        "Wollsocken",
        "Anzugsocken",
        "Sportsocken",
        "Kompressionsstrümpfe",
        "Crew-Socken",
        "Sneakersocken",
        "Kuschelsocken",
        "Sockenschublade",
        "verschiedene Socken",
        "Zehensocken",
        # phrases (~37)
        "neue Socken im Laden kaufen",
        "die Sockenschublade am Wochenende sortieren",
        "Socken mit Löchern wegwerfen",
        "Ersatzsocken für den Campingtrip einpacken",
        "warme Wollsocken für den Winter besorgen",
        "saubere Socken nach dem Waschen zuordnen",
        "Kompressionsstrümpfe für den langen Flug kaufen",
        "ein Paar Socken vor dem Rausgehen einpacken",
        "lustige gemusterte Socken online bestellen",
        "der Trockner frisst ständig meine Socken",
        "Anzugsocken für das Vorstellungsgespräch kaufen",
        "morgens passende Socken für die Kinder finden",
        "dicke Socken anziehen bevor man rausgeht",
        "Socken für die ganze Familie besorgen",
        "Weihnachtsstrumpf gefüllt mit neuen Socken",
        "alte Socken für die Kleidersammlung spenden",
        "warme Socken und heiße Schokolade an einem kalten Abend",
        "meine Füße frieren ich brauche dickere Socken",
        "Wäsche sortieren und alle Socken zusammenlegen",
        "rutschfeste Socken für den Krankenhausbesuch kaufen",
        "Socken aufhängen statt den Trockner benutzen",
        "die Kinder daran erinnern täglich Socken zu wechseln",
        "saubere Socken gehen aus heute Abend waschen",
        "Sportsocken für das Fitnessstudio kaufen",
        "neue Wandersocken für die Tour",
        "Bambussocken sollen sehr bequem sein",
        "Socken rutschen ständig in den Stiefeln runter",
        "Socken mit Feiertagsmotiv als Geschenk",
        "Merinosocken für kaltes Wetter",
        "nahtlose Socken für empfindliche Füße",
        "das Baby hat wieder beide Socken ausgezogen",
        "Socken im Sale auf Vorrat kaufen",
        "gemütliche Socken für den Filmabend",
        "Socken als kleines Geschenk im Strumpf",
        "nasse Socken an die Heizung zum Trocknen legen",
        "das Loch in meinen Lieblingssocken stopfen",
        "wasserdichte Socken für die Wanderung",
        # typos (5)
        "neue Socekn im Laden kaufen",
        "Sockenschulade am Wochenende sortieren",
        "Paar warme Scoken für den Winter",
        "Socekn mit Löchern entsorgen",
        "Kompresionsstrümpfe für den Flug",
    ],
    "ja": [
        # keywords (~18)
        "靴下",
        "ペア",
        "レッグウェア",
        "足",
        "暖かい",
        "冬",
        "衣類",
        "くるぶしソックス",
        "ウール靴下",
        "ドレスソックス",
        "スポーツソックス",
        "着圧ソックス",
        "クルーソックス",
        "フットカバー",
        "もこもこ靴下",
        "靴下の引き出し",
        "左右バラバラの靴下",
        "五本指ソックス",
        # phrases (~37)
        "お店で新しい靴下を買う",
        "週末に靴下の引き出しを整理する",
        "穴の開いた靴下を捨てる",
        "キャンプに予備の靴下を持っていく",
        "冬用に暖かいウール靴下を買う",
        "洗濯物の靴下をペアにまとめる",
        "長時間フライト用に着圧ソックスを買う",
        "出かける前に靴下を一足取る",
        "面白い柄の靴下をネットで注文する",
        "乾燥機がまた靴下を食べた",
        "面接用にドレスソックスが必要",
        "朝子供たちの揃いの靴下を探す",
        "外出前に厚い靴下を履く",
        "家族全員分の靴下を買う",
        "クリスマスの靴下に新しい靴下を入れる",
        "古い靴下を寄付する",
        "寒い夜に暖かい靴下とホットチョコレート",
        "足が冷たいもっと厚い靴下が必要",
        "洗濯物を分けて靴下をペアにする",
        "入院用に滑り止め靴下を買う",
        "乾燥機を使わず靴下を干す",
        "毎日靴下を替えるよう子供に言う",
        "きれいな靴下が足りない今夜洗濯する",
        "ジム用にスポーツソックスを買う",
        "トレッキング用の新しい靴下",
        "竹素材の靴下はとても快適らしい",
        "ブーツの中で靴下がずり落ちる",
        "ホリデー柄の靴下をプレゼント用に買う",
        "寒い日にメリノウール靴下",
        "敏感肌用の縫い目なし靴下",
        "赤ちゃんがまた両方の靴下を脱いだ",
        "セール中に靴下をまとめ買いする",
        "映画の夜用にふわふわ靴下",
        "クリスマスの小さなプレゼントに靴下",
        "濡れた靴下をヒーターの前に置いて乾かす",
        "お気に入りの靴下の穴を繕う",
        "ハイキング用の防水靴下が必要",
        # typos (5)
        "新しいい靴下を買う",
        "靴下のの引き出しを整理する",
        "暖かいいウール靴下",
        "靴下をペアにににする",
        "着圧ソッックスを買う",
    ],
    "fr": [
        # keywords (~18)
        "chaussettes",
        "paire",
        "bonneterie",
        "pieds",
        "chaud",
        "hiver",
        "vêtement",
        "socquettes",
        "chaussettes en laine",
        "chaussettes habillées",
        "chaussettes de sport",
        "chaussettes de compression",
        "chaussettes mi-mollet",
        "chaussettes invisibles",
        "chaussettes douillettes",
        "tiroir à chaussettes",
        "chaussettes dépareillées",
        "chaussettes à orteils",
        # phrases (~37)
        "acheter de nouvelles chaussettes au magasin",
        "ranger le tiroir à chaussettes ce week-end",
        "jeter les chaussettes trouées",
        "prendre des chaussettes de rechange pour le camping",
        "acheter des chaussettes en laine chaudes pour l'hiver",
        "assortir les chaussettes propres après la lessive",
        "acheter des chaussettes de compression pour le vol",
        "prendre une paire de chaussettes avant de sortir",
        "commander des chaussettes à motifs rigolos en ligne",
        "le sèche-linge mange encore mes chaussettes",
        "il me faut des chaussettes habillées pour l'entretien",
        "trouver des chaussettes assorties pour les enfants le matin",
        "mettre des chaussettes épaisses avant de sortir",
        "acheter des chaussettes pour toute la famille",
        "chaussette de Noël remplie de nouvelles chaussettes",
        "donner les vieilles chaussettes à la collecte de vêtements",
        "chaussettes chaudes et chocolat chaud un soir froid",
        "j'ai froid aux pieds il me faut des chaussettes plus épaisses",
        "trier le linge et apparier toutes les chaussettes",
        "acheter des chaussettes antidérapantes pour l'hôpital",
        "suspendre les chaussettes pour les sécher",
        "rappeler aux enfants de changer de chaussettes chaque jour",
        "plus de chaussettes propres faire la lessive ce soir",
        "acheter des chaussettes de sport pour la salle",
        "nouvelles chaussettes de randonnée pour le sentier",
        "les chaussettes en bambou seraient très confortables",
        "les chaussettes glissent dans les bottes",
        "acheter des chaussettes de fêtes comme cadeaux",
        "chaussettes en laine mérinos pour le froid",
        "chaussettes sans couture pour pieds sensibles",
        "le bébé a encore enlevé ses deux chaussettes",
        "faire le plein de chaussettes pendant les soldes",
        "chaussettes douillettes pour la soirée film",
        "des chaussettes comme petit cadeau de Noël",
        "poser les chaussettes mouillées près du radiateur",
        "repriser le trou de mes chaussettes préférées",
        "il faut des chaussettes imperméables pour la rando",
        # typos (5)
        "acheter des chuassettes au magasin",
        "tirroir à chaussettes à ranger",
        "paire de chausettes en laine",
        "chausettes de compresion pour le vol",
        "chaussetes dépareillées dans le tiroir",
    ],
    "es": [
        # keywords (~18)
        "calcetines",
        "par",
        "medias",
        "pies",
        "caliente",
        "invierno",
        "ropa",
        "calcetines tobilleros",
        "calcetines de lana",
        "calcetines de vestir",
        "calcetines deportivos",
        "calcetines de compresión",
        "calcetines largos",
        "calcetines invisibles",
        "calcetines peludos",
        "cajón de calcetines",
        "calcetines disparejos",
        "calcetines de dedos",
        # phrases (~37)
        "comprar calcetines nuevos en la tienda",
        "ordenar el cajón de calcetines este fin de semana",
        "tirar los calcetines con agujeros",
        "llevar calcetines extras para el campamento",
        "comprar calcetines de lana abrigados para el invierno",
        "emparejar los calcetines limpios después de lavar",
        "comprar calcetines de compresión para el vuelo largo",
        "tomar un par de calcetines antes de salir",
        "pedir calcetines con diseños divertidos por internet",
        "la secadora se sigue comiendo mis calcetines",
        "necesito calcetines de vestir para la entrevista",
        "encontrar calcetines que combinen para los niños",
        "ponerse calcetines gruesos antes de salir",
        "comprar calcetines para toda la familia",
        "media navideña llena de calcetines nuevos",
        "donar calcetines viejos a la colecta de ropa",
        "calcetines calientes y chocolate caliente en noche fría",
        "tengo los pies fríos necesito calcetines más gruesos",
        "separar la ropa y emparejar todos los calcetines",
        "comprar calcetines antideslizantes para el hospital",
        "colgar los calcetines para que se sequen",
        "recordar a los niños cambiarse los calcetines cada día",
        "se acabaron los calcetines limpios lavar esta noche",
        "comprar calcetines deportivos para el gimnasio",
        "nuevos calcetines de senderismo para la ruta",
        "los calcetines de bambú dicen que son muy cómodos",
        "los calcetines se me bajan dentro de las botas",
        "comprar calcetines navideños como regalo",
        "calcetines de lana merino para el frío",
        "calcetines sin costuras para pies sensibles",
        "el bebé se volvió a quitar los dos calcetines",
        "aprovechar las rebajas para comprar calcetines",
        "calcetines acogedores para la noche de películas",
        "calcetines como regalito en la media navideña",
        "poner los calcetines mojados junto al radiador",
        "remendar el agujero en mis calcetines favoritos",
        "necesito calcetines impermeables para la caminata",
        # typos (5)
        "comprar calectines nuevos en la tienda",
        "ordenar el cajón de calectines",
        "par de calsetines de lana",
        "calsetines de compresón para el vuelo",
        "calcetines deparejados en el cajón",
    ],
})


# ── speaker ──────────────────────────────────────────────────────────────────
build_icon("speaker", {
    "en": [
        "speaker", "audio", "amplifier", "sound", "loud", "music",
        "subwoofer", "tweeter", "bluetooth speaker", "wireless speaker",
        "bookshelf speaker", "portable speaker", "surround sound", "bass",
        "treble", "stereo", "home theater", "soundbar",
        "buy a new bluetooth speaker for the patio",
        "set up the surround sound speakers in the living room",
        "test the speaker connections before the party",
        "pair the bluetooth speaker with my phone",
        "the speaker is making a buzzing noise fix it",
        "order replacement speaker wire online",
        "move the speaker to the other side of the room",
        "turn down the speaker the neighbors are complaining",
        "connect the soundbar to the TV",
        "buy a portable speaker for the beach trip",
        "the left speaker stopped working need to check it",
        "mount the speakers on the wall this weekend",
        "charge the portable speaker before the picnic",
        "compare bookshelf speakers at the electronics store",
        "return the defective speaker to the store",
        "set up speakers for the backyard barbecue",
        "the speaker battery dies too fast",
        "clean the dust off the speaker grille",
        "bring the speaker to the campsite",
        "hook up the amplifier to the speakers",
        "upgrade the home theater speaker system",
        "speaker placement guide for best sound",
        "get a waterproof speaker for the shower",
        "adjust the bass and treble on the speaker",
        "the kids broke the speaker again",
        "need a louder speaker for the garage",
        "check if the speaker is still under warranty",
        "new speaker setup for the office",
        "speaker wire hidden behind the wall",
        "the speaker keeps disconnecting from bluetooth",
        "find a speaker stand that fits the bookshelf pair",
        "speaker on sale at the electronics store",
        "bring the speaker to the tailgate party",
        "ask for a speaker recommendation for the living room",
        "multi-room audio speaker setup",
        "test the new speaker with different music genres",
        "the old speaker finally gave out need a new one",
        "buy a new bluetooh speaker",
        "spekaer connected to the amp",
        "speeaker on the bookshelf",
        "speakre playing music outdoors",
        "conect the soundbar to the TV",
    ],
    "ru": [
        "колонка", "аудио", "усилитель", "звук", "громкий", "музыка",
        "сабвуфер", "твитер", "bluetooth колонка", "беспроводная колонка",
        "полочная колонка", "портативная колонка", "объёмный звук", "бас",
        "высокие частоты", "стерео", "домашний кинотеатр", "саундбар",
        "купить новую bluetooth колонку для террасы",
        "настроить объёмный звук колонок в гостиной",
        "проверить подключение колонок перед вечеринкой",
        "подключить bluetooth колонку к телефону",
        "колонка издаёт жужжание надо починить",
        "заказать провод для колонки онлайн",
        "переставить колонку на другую сторону комнаты",
        "убавить колонку соседи жалуются",
        "подключить саундбар к телевизору",
        "купить портативную колонку для поездки на пляж",
        "левая колонка перестала работать надо проверить",
        "повесить колонки на стену в выходные",
        "зарядить портативную колонку перед пикником",
        "сравнить полочные колонки в магазине электроники",
        "вернуть бракованную колонку в магазин",
        "поставить колонки для барбекю во дворе",
        "аккумулятор колонки слишком быстро садится",
        "протереть пыль с решётки колонки",
        "взять колонку на природу",
        "подключить усилитель к колонкам",
        "обновить акустику домашнего кинотеатра",
        "расстановка колонок для лучшего звука",
        "купить водонепроницаемую колонку для душа",
        "настроить бас и высокие на колонке",
        "дети опять сломали колонку",
        "нужна колонка погромче для гаража",
        "проверить гарантию на колонку",
        "новая колонка для офиса",
        "спрятать провод от колонки за стену",
        "колонка постоянно отключается от bluetooth",
        "найти стойку для полочных колонок",
        "колонка по скидке в магазине электроники",
        "взять колонку на вечеринку у машины",
        "спросить совет какую колонку купить в гостиную",
        "мультирум аудиосистема настройка",
        "проверить новую колонку на разных жанрах",
        "старая колонка наконец сломалась нужна новая",
        "купить новую bluetooh колноку",
        "динамик подклчён к усилителю",
        "колнока стоит на книжной полке",
        "динамик игарет музыку на улице",
        "подклчить саундбар к телевизру",
    ],
    "de": [
        "Lautsprecher", "Audio", "Verstärker", "Klang", "laut", "Musik",
        "Subwoofer", "Hochtöner", "Bluetooth-Lautsprecher",
        "kabelloser Lautsprecher", "Regallautsprecher", "tragbarer Lautsprecher",
        "Surround-Sound", "Bass", "Höhen", "Stereo", "Heimkino", "Soundbar",
        "neuen Bluetooth-Lautsprecher für die Terrasse kaufen",
        "Surround-Sound-Lautsprecher im Wohnzimmer aufstellen",
        "Lautsprecheranschlüsse vor der Party prüfen",
        "Bluetooth-Lautsprecher mit dem Handy koppeln",
        "der Lautsprecher brummt das muss repariert werden",
        "Lautsprecherkabel online nachbestellen",
        "den Lautsprecher auf die andere Seite stellen",
        "Lautsprecher leiser drehen die Nachbarn beschweren sich",
        "Soundbar an den Fernseher anschließen",
        "tragbaren Lautsprecher für den Strandausflug kaufen",
        "der linke Lautsprecher geht nicht mehr prüfen",
        "Lautsprecher am Wochenende an die Wand montieren",
        "tragbaren Lautsprecher vor dem Picknick laden",
        "Regallautsprecher im Elektronikladen vergleichen",
        "defekten Lautsprecher im Laden zurückgeben",
        "Lautsprecher für die Gartenparty aufstellen",
        "der Akku vom Lautsprecher hält nicht lange",
        "Staub vom Lautsprechergitter wischen",
        "Lautsprecher zum Campingplatz mitnehmen",
        "Verstärker an die Lautsprecher anschließen",
        "Heimkino-Lautsprechersystem aufrüsten",
        "Lautsprecher-Aufstellungsanleitung für besten Klang",
        "wasserdichten Lautsprecher für die Dusche kaufen",
        "Bass und Höhen am Lautsprecher einstellen",
        "die Kinder haben den Lautsprecher wieder kaputt gemacht",
        "lauterer Lautsprecher für die Garage nötig",
        "prüfen ob der Lautsprecher noch Garantie hat",
        "neuer Lautsprecher für das Büro",
        "Lautsprecherkabel hinter der Wand verstecken",
        "der Lautsprecher trennt ständig die Bluetooth-Verbindung",
        "Lautsprecherständer für die Regallautsprecher finden",
        "Lautsprecher im Angebot im Elektronikladen",
        "Lautsprecher zur Grillparty mitbringen",
        "nach einer Lautsprecherempfehlung fürs Wohnzimmer fragen",
        "Multiroom-Audio-Lautsprecher einrichten",
        "neuen Lautsprecher mit verschiedenen Genres testen",
        "der alte Lautsprecher ist kaputt neuen kaufen",
        "neuen Bluetooh-Lautsprecher kaufen",
        "Lautsprecher an den Verstärker anschlißen",
        "Lautsprcher auf dem Regal",
        "Lautsprecher spielt Muisk draußen",
        "Soundbar an den Fernsehr anschließen",
    ],
    "ja": [
        "スピーカー", "オーディオ", "アンプ", "音", "大音量", "音楽",
        "サブウーファー", "ツイーター", "Bluetoothスピーカー",
        "ワイヤレススピーカー", "ブックシェルフスピーカー",
        "ポータブルスピーカー", "サラウンドサウンド", "低音", "高音",
        "ステレオ", "ホームシアター", "サウンドバー",
        "テラス用に新しいBluetoothスピーカーを買う",
        "リビングにサラウンドスピーカーを設置する",
        "パーティー前にスピーカーの接続を確認する",
        "Bluetoothスピーカーをスマホにペアリングする",
        "スピーカーからブーンという音がする修理する",
        "スピーカーケーブルをネットで注文する",
        "スピーカーを部屋の反対側に移動する",
        "スピーカーの音量を下げる近所迷惑になる",
        "サウンドバーをテレビに接続する",
        "ビーチ用にポータブルスピーカーを買う",
        "左のスピーカーが動かなくなった確認する",
        "週末にスピーカーを壁に取り付ける",
        "ピクニック前にポータブルスピーカーを充電する",
        "電器店でブックシェルフスピーカーを比較する",
        "不良品のスピーカーを店に返品する",
        "裏庭バーベキュー用にスピーカーを設置する",
        "スピーカーのバッテリーがすぐ切れる",
        "スピーカーのグリルのほこりを拭く",
        "キャンプにスピーカーを持っていく",
        "アンプをスピーカーに接続する",
        "ホームシアターのスピーカーをアップグレードする",
        "最適な音のためのスピーカー配置ガイド",
        "シャワー用に防水スピーカーを買う",
        "スピーカーの低音と高音を調整する",
        "子供がまたスピーカーを壊した",
        "ガレージ用にもっと大きなスピーカーが必要",
        "スピーカーの保証がまだ有効か確認する",
        "オフィス用の新しいスピーカー",
        "スピーカーケーブルを壁の裏に隠す",
        "スピーカーがBluetoothから切断され続ける",
        "ブックシェルフスピーカー用のスタンドを探す",
        "電器店でスピーカーがセール中",
        "テールゲートパーティーにスピーカーを持参する",
        "リビング用スピーカーのおすすめを聞く",
        "マルチルームオーディオスピーカーの設定",
        "新しいスピーカーを色々なジャンルでテストする",
        "古いスピーカーがついに壊れた新しいのが必要",
        "新しいBluetoohスピーカーを買う",
        "スピーカーーをアンプに接続する",
        "スピーカーが棚のの上にある",
        "スピーカーで外でで音楽を流す",
        "サウンドバーをテレビにに接続する",
    ],
    "fr": [
        "enceinte", "audio", "amplificateur", "son", "fort", "musique",
        "caisson de basses", "tweeter", "enceinte Bluetooth",
        "enceinte sans fil", "enceinte bibliothèque", "enceinte portable",
        "son surround", "basses", "aigus", "stéréo", "home cinéma",
        "barre de son",
        "acheter une nouvelle enceinte Bluetooth pour la terrasse",
        "installer les enceintes surround dans le salon",
        "vérifier les branchements des enceintes avant la fête",
        "appairer l'enceinte Bluetooth avec mon téléphone",
        "l'enceinte fait un bourdonnement il faut la réparer",
        "commander du câble pour enceinte en ligne",
        "déplacer l'enceinte de l'autre côté de la pièce",
        "baisser l'enceinte les voisins se plaignent",
        "brancher la barre de son sur la télé",
        "acheter une enceinte portable pour la plage",
        "l'enceinte gauche ne marche plus vérifier",
        "fixer les enceintes au mur ce week-end",
        "charger l'enceinte portable avant le pique-nique",
        "comparer les enceintes bibliothèque au magasin",
        "rapporter l'enceinte défectueuse au magasin",
        "installer les enceintes pour le barbecue",
        "la batterie de l'enceinte ne tient pas longtemps",
        "nettoyer la poussière de la grille de l'enceinte",
        "emmener l'enceinte au camping",
        "brancher l'amplificateur aux enceintes",
        "améliorer le système d'enceintes du home cinéma",
        "guide de placement des enceintes pour le meilleur son",
        "acheter une enceinte étanche pour la douche",
        "régler les basses et les aigus de l'enceinte",
        "les enfants ont encore cassé l'enceinte",
        "besoin d'une enceinte plus puissante pour le garage",
        "vérifier si l'enceinte est encore sous garantie",
        "nouvelle enceinte pour le bureau",
        "cacher le câble de l'enceinte derrière le mur",
        "l'enceinte se déconnecte sans cesse du Bluetooth",
        "trouver un support pour les enceintes bibliothèque",
        "enceinte en promotion au magasin d'électronique",
        "apporter l'enceinte à la soirée barbecue",
        "demander une recommandation d'enceinte pour le salon",
        "installation enceintes audio multiroom",
        "tester la nouvelle enceinte avec différents genres",
        "la vieille enceinte a lâché il en faut une nouvelle",
        "acheter une nouvelle enecinte Bluetooth",
        "enciente branchée à l'ampli",
        "enceinte sur l'étargère",
        "ecneinte joue de la musique dehors",
        "barncher la barre de son à la télé",
    ],
    "es": [
        "altavoz", "audio", "amplificador", "sonido", "fuerte", "música",
        "subwoofer", "tweeter", "altavoz Bluetooth", "altavoz inalámbrico",
        "altavoz de estantería", "altavoz portátil", "sonido envolvente",
        "graves", "agudos", "estéreo", "cine en casa", "barra de sonido",
        "comprar un nuevo altavoz Bluetooth para la terraza",
        "instalar los altavoces envolventes en la sala",
        "revisar las conexiones de los altavoces antes de la fiesta",
        "emparejar el altavoz Bluetooth con el teléfono",
        "el altavoz hace un zumbido hay que arreglarlo",
        "pedir cable de altavoz por internet",
        "mover el altavoz al otro lado de la habitación",
        "bajar el altavoz los vecinos se quejan",
        "conectar la barra de sonido al televisor",
        "comprar un altavoz portátil para la playa",
        "el altavoz izquierdo dejó de funcionar revisar",
        "montar los altavoces en la pared este fin de semana",
        "cargar el altavoz portátil antes del picnic",
        "comparar altavoces de estantería en la tienda",
        "devolver el altavoz defectuoso a la tienda",
        "poner altavoces para la barbacoa del jardín",
        "la batería del altavoz se acaba muy rápido",
        "limpiar el polvo de la rejilla del altavoz",
        "llevar el altavoz al campamento",
        "conectar el amplificador a los altavoces",
        "mejorar el sistema de altavoces del cine en casa",
        "guía de colocación de altavoces para mejor sonido",
        "comprar un altavoz resistente al agua para la ducha",
        "ajustar los graves y agudos del altavoz",
        "los niños rompieron el altavoz otra vez",
        "necesito un altavoz más potente para el garaje",
        "verificar si el altavoz aún tiene garantía",
        "nuevo altavoz para la oficina",
        "esconder el cable del altavoz detrás de la pared",
        "el altavoz se desconecta constantemente del Bluetooth",
        "buscar un soporte para los altavoces de estantería",
        "altavoz en oferta en la tienda de electrónica",
        "llevar el altavoz a la parrillada",
        "pedir recomendación de altavoz para la sala",
        "configuración de altavoces multiroom",
        "probar el nuevo altavoz con diferentes géneros",
        "el viejo altavoz se rompió necesito uno nuevo",
        "comprar un nuevo altavos Bluetooth",
        "altavoz concetado al amplificador",
        "altvaoz en la estantería",
        "altavoz reporduce música afuera",
        "conctar la barra de sonido al TV",
    ],
})

print("Part A done: snowman, socks, speaker")
