#!/usr/bin/env python3
"""Task-003 part 1: money-check, monkey"""
from gen_icons_task_003_lib import build_icon

# ── money-check ──────────────────────────────────────────────────────────────
build_icon("money-check",
    keep_en=[
        "bank check",
        "cheque",
        "write a bank check to landlord",
        "buy with a personal check",
        "buy goods using a cheque",
        "checkout with a paper check",
        "checkout payment via check",
        "cheque written for full amount",
        "cheque payment to service provider",
        "money check written out",
        "money payment via paper check",
        "payment by check to vendor",
        "check payment for invoice",
        "price on check for service",
        "check amount for final price",
        "purchase with personal check",
        "purchase order with check",
        "salary check cashed at bank",
        "paycheck signed and cashed",
        "personal check written to pay rent",
        "payroll check from employer",
        "bank-issued cashier's check",
        "writing a check for utility bills",
        "check cashing at the bank teller",
        "voided check for direct deposit setup",
        "corporate check for vendor payment",
        "signed check as payment proof",
        "pay the landlord with a check",
        "write a check for the invoice",
        "deposit the paycheck at the bank",
        "sign the check before mailing it",
        "bank chekc payment",
        "cheuqe for salary",
        "chekout with check",
        "pruchase by check",
    ],
    new_en=[
        "finance",
        "invoice",
        "payment",
        "money",
        "deposit check at the ATM",
        "mail a check to the insurance company",
        "order new checks from the bank",
        "write a check for the contractor",
        "cash the check on payday",
        "endorse the back of the check",
        "balance the checkbook this weekend",
        "pay rent by check this month",
        "send a check for the membership fee",
        "pick up the cashier's check tomorrow",
        "tear out a check from the checkbook",
        "fill in the check amount carefully",
        "stop payment on the lost check",
        "verify the check cleared the account",
        "bring a voided check to HR",
        "request a refund check from the store",
        "pay tuition with a bank check",
        "reorder checks before they run out",
        "cheque for the electrician",
        "paychek deposited",
        "invoce payment by check",
    ],
    keep_ru=[
        "банковский чек",
        "чек",
        "написать банковский чек арендодателю",
        "купить по личному чеку",
        "купить товары по чеку",
        "оплата на кассе бумажным чеком",
        "оплата через кассу по чеку",
        "чек выписанный на полную сумму",
        "чек оплаты поставщику услуг",
        "денежный чек выписанный",
        "денежная оплата бумажным чеком",
        "оплата чеком поставщику",
        "оплата счёта чеком",
        "цена в чеке за услугу",
        "сумма чека за итоговую цену",
        "покупка личным чеком",
        "заказ на покупку с чеком",
        "зарплатный чек обналиченный в банке",
        "подписанный и обналиченный чек",
        "личный чек выписанный для оплаты аренды",
        "зарплатный чек от работодателя",
        "кассирский чек выданный банком",
        "написание чека для оплаты коммунальных услуг",
        "обналичивание чека у банковского кассира",
        "аннулированный чек для настройки прямого депозита",
        "корпоративный чек для оплаты поставщику",
        "подписанный чек как подтверждение оплаты",
        "оплатить аренду банковским чеком",
        "выписать чек на оплату счета",
        "внести зарплатный чек в банк",
        "подписать чек перед отправкой",
        "банковски чек оплата",
        "зарплтаный чек",
        "оплатаа чеком",
        "покупка по чеку",
    ],
    new_ru=[
        "финансы",
        "счёт-фактура",
        "платёж",
        "деньги",
        "внести чек через банкомат",
        "отправить чек в страховую компанию",
        "заказать новые чеки в банке",
        "выписать чек для подрядчика",
        "обналичить чек в день зарплаты",
        "подписать оборот чека",
        "сверить чековую книжку на выходных",
        "оплатить аренду чеком в этом месяце",
        "отправить чек за членский взнос",
        "забрать кассирский чек завтра",
        "вырвать чек из чековой книжки",
        "аккуратно заполнить сумму в чеке",
        "отменить платёж по утерянному чеку",
        "проверить прошёл ли чек по счёту",
        "принести аннулированный чек в отдел кадров",
        "попросить возврат чеком в магазине",
        "оплатить обучение банковским чеком",
        "перезаказать чеки пока не закончились",
        "чек для электрика",
        "зарплтный чек внесён",
        "оплата счёта чекм",
    ],
    de=[
        "Bankscheck",
        "Scheck",
        "Zahlung",
        "Finanzen",
        "Rechnung",
        "Geld",
        "Gehaltsscheck",
        "Verrechnungsscheck",
        "Scheckzahlung",
        "Kassenscheck",
        "Scheckbuch",
        "Bankeinzahlung",
        "Scheckeinlösung",
        "Zahlungsanweisung",
        "Lohnscheck",
        "Firmenscheck",
        "Blankoscheck",
        "Scheckheft",
        "Scheck beim Vermieter einreichen",
        "Scheck für die Rechnung ausstellen",
        "Gehaltsscheck bei der Bank einlösen",
        "Scheck unterschreiben und abschicken",
        "neuen Scheck für den Handwerker ausfüllen",
        "Scheck per Post an die Versicherung senden",
        "neue Schecks bei der Bank bestellen",
        "Scheck am Zahltag einlösen",
        "Rückseite des Schecks unterschreiben",
        "Scheckbuch am Wochenende abgleichen",
        "Miete diesen Monat per Scheck zahlen",
        "Scheck für den Mitgliedsbeitrag schicken",
        "Kassenscheck morgen abholen",
        "Scheck aus dem Scheckbuch abreißen",
        "Betrag im Scheck sorgfältig eintragen",
        "Zahlung für verlorenen Scheck sperren",
        "prüfen ob der Scheck eingelöst wurde",
        "stornierten Scheck zur Personalabteilung bringen",
        "Rückerstattung per Scheck vom Laden anfordern",
        "Studiengebühren mit Bankscheck bezahlen",
        "Schecks nachbestellen bevor sie ausgehen",
        "Scheck für den Elektriker ausstellen",
        "Gehalt per Scheck erhalten",
        "Rechnung mit Scheck begleichen",
        "Scheck zur Bank bringen",
        "Kaution per Scheck zahlen",
        "Anzahlung per Scheck leisten",
        "Arztrechnung per Scheck bezahlen",
        "Scheck für die Autoreparatur schreiben",
        "Kontostand nach Scheckzahlung prüfen",
        "Scheck für Spende ausstellen",
        "Verrechnungsscheck an Lieferanten senden",
        "Firmenscheck für Büromaterial ausstellen",
        "Mietkaution per Scheck überweisen",
        "Scheck für Versicherungsprämie ausfüllen",
        "Bankgebühren für Scheckeinlösung prüfen",
        "Scheck für Nachhilfe ausstellen",
        "Schek für Rechnung",
        "Gehaltsscheck einlöhsen",
        "Schecj unterschreiben",
        "Zahlug per Scheck",
        "Scheckbuch bestelen",
    ],
    ja=[
        "小切手",
        "銀行小切手",
        "支払い",
        "金融",
        "請求書",
        "お金",
        "給与小切手",
        "現金化",
        "小切手帳",
        "振出",
        "決済",
        "手形",
        "送金",
        "経理",
        "家賃",
        "振込",
        "精算",
        "領収書",
        "家賃の小切手を大家に書く",
        "請求書の小切手を切る",
        "給与小切手を銀行に預ける",
        "小切手に署名してから郵送する",
        "業者への小切手を書く",
        "保険会社に小切手を郵送する",
        "銀行で新しい小切手を注文する",
        "給料日に小切手を現金化する",
        "小切手の裏に裏書きする",
        "週末に小切手帳を確認する",
        "今月は小切手で家賃を払う",
        "会費の小切手を送る",
        "明日キャッシャーズチェックを受け取る",
        "小切手帳から小切手を切り取る",
        "小切手の金額を慎重に記入する",
        "紛失した小切手の支払いを止める",
        "小切手が決済されたか確認する",
        "無効小切手を人事部に持っていく",
        "店で返金小切手を依頼する",
        "学費を銀行小切手で支払う",
        "小切手がなくなる前に再注文する",
        "電気屋さんへの小切手",
        "給与小切手を入金した",
        "光熱費を小切手で払う",
        "修理代の小切手を用意する",
        "小切手で寄付金を送る",
        "仕入先への小切手を準備する",
        "保証金を小切手で支払う",
        "医療費の小切手を書く",
        "車の修理代を小切手で払う",
        "小切手の残高を確認する",
        "授業料の小切手を準備する",
        "小切手帳を再注文する",
        "取引先に小切手を郵送する",
        "月末の支払い小切手を準備する",
        "税金を小切手で納付する",
        "会計に小切手の控えを渡す",
        "定期支払いの小切手を書く",
        "こぎって を銀行にもっていく",
        "しはらい の小切手",
        "きゅうよ こぎって",
        "せいきゅうしょ のしはらい",
    ],
    fr=[
        "chèque",
        "chèque bancaire",
        "paiement",
        "finances",
        "facture",
        "argent",
        "chèque de paie",
        "encaissement",
        "carnet de chèques",
        "chéquier",
        "règlement",
        "versement",
        "virement",
        "solde",
        "traite",
        "mandat",
        "acompte",
        "prélèvement",
        "écrire un chèque au propriétaire",
        "rédiger un chèque pour la facture",
        "déposer le chèque de paie à la banque",
        "signer le chèque avant de l'envoyer",
        "faire un chèque pour l'artisan",
        "envoyer un chèque à l'assurance",
        "commander de nouveaux chèques à la banque",
        "encaisser le chèque le jour de paie",
        "endosser le dos du chèque",
        "vérifier le carnet de chèques ce weekend",
        "payer le loyer par chèque ce mois-ci",
        "envoyer un chèque pour la cotisation",
        "récupérer le chèque de banque demain",
        "détacher un chèque du carnet",
        "remplir le montant du chèque soigneusement",
        "faire opposition sur le chèque perdu",
        "vérifier que le chèque a été encaissé",
        "apporter un chèque annulé aux ressources humaines",
        "demander un remboursement par chèque au magasin",
        "payer les frais de scolarité par chèque bancaire",
        "recommander des chèques avant qu'ils ne s'épuisent",
        "chèque pour l'électricien",
        "chèque de salaire déposé",
        "régler la facture par chèque",
        "apporter le chèque à la banque",
        "payer la caution par chèque",
        "verser un acompte par chèque",
        "payer la facture du médecin par chèque",
        "faire un chèque pour la réparation auto",
        "vérifier le solde après paiement par chèque",
        "faire un chèque pour un don",
        "envoyer le chèque au fournisseur",
        "préparer le chèque de fin de mois",
        "régler les impôts par chèque",
        "remettre le talon de chèque à la comptabilité",
        "rédiger un chèque pour le paiement régulier",
        "payer l'abonnement par chèque",
        "chèqe pour la facture",
        "chèque de pai déposé",
        "paiemnt par chèque",
        "chéqier à commander",
        "encaisement du chèque",
    ],
    es=[
        "cheque",
        "cheque bancario",
        "pago",
        "finanzas",
        "factura",
        "dinero",
        "cheque de nómina",
        "cobro",
        "chequera",
        "talonario",
        "abono",
        "giro",
        "transferencia",
        "saldo",
        "letra",
        "pagaré",
        "anticipo",
        "ingreso",
        "escribir un cheque al casero",
        "hacer un cheque para la factura",
        "depositar el cheque de nómina en el banco",
        "firmar el cheque antes de enviarlo",
        "hacer un cheque para el contratista",
        "enviar un cheque a la aseguradora",
        "pedir cheques nuevos al banco",
        "cobrar el cheque el día de pago",
        "endosar el reverso del cheque",
        "cuadrar la chequera este fin de semana",
        "pagar el alquiler con cheque este mes",
        "enviar un cheque por la cuota de membresía",
        "recoger el cheque de caja mañana",
        "arrancar un cheque de la chequera",
        "rellenar el monto del cheque con cuidado",
        "cancelar el pago del cheque perdido",
        "verificar que el cheque fue cobrado",
        "llevar un cheque anulado a recursos humanos",
        "pedir un reembolso con cheque en la tienda",
        "pagar la matrícula con cheque bancario",
        "pedir más cheques antes de que se acaben",
        "cheque para el electricista",
        "cheque de sueldo depositado",
        "pagar la factura con cheque",
        "llevar el cheque al banco",
        "pagar la fianza con cheque",
        "dar un anticipo con cheque",
        "pagar la cuenta del médico con cheque",
        "hacer un cheque para la reparación del auto",
        "revisar el saldo tras el pago con cheque",
        "hacer un cheque para una donación",
        "enviar cheque al proveedor",
        "preparar el cheque de fin de mes",
        "pagar impuestos con cheque",
        "entregar el talón de cheque a contabilidad",
        "hacer un cheque para el pago periódico",
        "pagar la suscripción con cheque",
        "cheke para la factura",
        "cheqe de nómina",
        "pago con chque",
        "chequra por pedir",
        "cobrar el cheuqe",
    ],
)

# ── monkey ───────────────────────────────────────────────────────────────────
build_icon("monkey",
    keep_en=[
        "banana",
        "monkey",
        "primate",
        "mammal",
        "animal",
        "fauna",
        "mokey animal",
        "bananaa monkey",
        "primte swinging",
        "monky tail",
    ],
    new_en=[
        "monke",
        "zoo",
        "jungle",
        "wildlife",
        "chimpanzee",
        "gorilla",
        "capuchin",
        "ape",
        "visit the monkey exhibit at the zoo",
        "plan a trip to the primate sanctuary",
        "buy tickets for the monkey house",
        "watch the monkey feeding at noon",
        "take the kids to see the monkeys",
        "volunteer at the primate rescue center",
        "book a jungle tour to see wild monkeys",
        "read about primate behavior for class",
        "donate to the monkey conservation fund",
        "buy a monkey-themed birthday gift",
        "photograph monkeys at the wildlife park",
        "check the zoo schedule for monkey talk",
        "bring bananas for the monkey encounter",
        "watch a documentary about primates",
        "sign up for the monkey adoption program",
        "pack snacks for the zoo trip",
        "research capuchin monkeys for the report",
        "buy a stuffed monkey toy for the baby",
        "plan a wildlife safari to see monkeys",
        "attend the primate lecture at the museum",
        "schedule a trip to the monkey island",
        "pick up monkey stickers for the kids",
        "feed the monkeys at the petting zoo",
        "learn about endangered primate species",
        "look up monkey facts for the school project",
        "get the monkey puzzle game for game night",
        "visit the chimp enclosure after lunch",
        "renew the zoo membership for monkey visits",
        "order a banana cake for the monkey party",
        "set a reminder for the monkey show at three",
        "buy monkey pajamas for the toddler",
        "check if the monkey trail is open today",
        "call the zoo about the monkey tour",
        "reserve spots for the primate workshop",
        "grab the monkey backpack for school",
        "print monkey coloring pages for the kids",
        "monkye exhibit at the zoo",
        "priamte sanctuary visit",
        "banannas for the monkeys",
        "monky birthday gift",
        "zoo tript to see monkeys",
        "pick up the monkey costume for Halloween",
    ],
    keep_ru=[
        "банан",
        "обезьяна",
        "примат",
        "млекопитающее",
        "животное",
        "фауна",
        "обезяна животное",
        "банна обезьяна",
    ],
    new_ru=[
        "зоопарк",
        "джунгли",
        "дикая природа",
        "шимпанзе",
        "горилла",
        "капуцин",
        "мартышка",
        "макака",
        "посетить вольер с обезьянами в зоопарке",
        "запланировать поездку в заповедник приматов",
        "купить билеты в обезьянник",
        "посмотреть кормление обезьян в полдень",
        "сводить детей посмотреть на обезьян",
        "стать волонтёром в центре спасения приматов",
        "забронировать тур в джунгли к диким обезьянам",
        "прочитать о поведении приматов для учёбы",
        "пожертвовать в фонд охраны обезьян",
        "купить подарок на день рождения с обезьяной",
        "фотографировать обезьян в парке дикой природы",
        "проверить расписание зоопарка для шоу обезьян",
        "взять бананы для встречи с обезьянами",
        "посмотреть документальный фильм о приматах",
        "записаться в программу опеки обезьяны",
        "собрать перекус для поездки в зоопарк",
        "написать доклад про обезьян капуцинов",
        "купить плюшевую обезьяну для малыша",
        "запланировать сафари чтобы увидеть обезьян",
        "сходить на лекцию о приматах в музее",
        "запланировать поездку на остров обезьян",
        "купить наклейки с обезьянами для детей",
        "покормить обезьян в контактном зоопарке",
        "узнать о вымирающих видах приматов",
        "найти факты об обезьянах для школьного проекта",
        "взять игру с обезьянами на вечер",
        "сходить к шимпанзе после обеда",
        "продлить абонемент в зоопарк для обезьян",
        "заказать банановый торт для обезьяньей вечеринки",
        "поставить напоминание на шоу обезьян в три",
        "купить пижаму с обезьянами для малыша",
        "проверить открыта ли тропа обезьян сегодня",
        "позвонить в зоопарк насчёт тура к обезьянам",
        "забронировать места на мастер-класс о приматах",
        "взять рюкзак с обезьяной в школу",
        "распечатать раскраски с обезьянами для детей",
        "обезьяний вольер в зоопарке",
        "заповедник примтаов поездка",
        "бананы для обезьн",
        "подарок с обезьякой",
        "поездка в заопарк к обезьянам",
        "взять костюм обезьяны на Хэллоуин",
        "прмиат деревья",
        "хвос обезьяны",
    ],
    de=[
        "Affe",
        "Banane",
        "Primat",
        "Säugetier",
        "Tier",
        "Fauna",
        "Dschungel",
        "Zoo",
        "Wildtier",
        "Schimpanse",
        "Gorilla",
        "Kapuzineraffe",
        "Menschenaffe",
        "Makake",
        "Pavian",
        "Äffchen",
        "Tierpark",
        "Wildpark",
        "Affengehege im Zoo besuchen",
        "Ausflug zum Primatenreservat planen",
        "Tickets für das Affenhaus kaufen",
        "Affenfütterung um zwölf anschauen",
        "Kinder zum Affengehege mitnehmen",
        "als Freiwilliger im Primatenzentrum helfen",
        "Dschungeltour buchen um wilde Affen zu sehen",
        "über Primatenverhalten für die Schule lesen",
        "an den Affenschutzfonds spenden",
        "Geschenk mit Affenmotiv zum Geburtstag kaufen",
        "Affen im Wildpark fotografieren",
        "Zooplan für die Affenshow prüfen",
        "Bananen für das Affentreffen mitbringen",
        "Dokumentation über Primaten anschauen",
        "beim Affenpatenschaftsprogramm mitmachen",
        "Snacks für den Zooausflug einpacken",
        "Referat über Kapuzineraffen vorbereiten",
        "Plüschaffe für das Baby kaufen",
        "Wildsafari planen um Affen zu sehen",
        "Vortrag über Primaten im Museum besuchen",
        "Reise zur Affeninsel planen",
        "Affensticker für die Kinder kaufen",
        "Affen im Streichelzoo füttern",
        "bedrohte Primatenarten recherchieren",
        "Affenfakten für das Schulprojekt suchen",
        "Affenpuzzle für den Spieleabend besorgen",
        "nach dem Mittagessen zu den Schimpansen gehen",
        "Zoo-Jahreskarte für Affenbesuche verlängern",
        "Bananenkuchen für die Affenparty bestellen",
        "Erinnerung für die Affenshow um drei setzen",
        "Affenpyjama für das Kleinkind kaufen",
        "prüfen ob der Affenpfad heute offen ist",
        "Zoo wegen der Affentour anrufen",
        "Plätze für den Primatenworkshop reservieren",
        "Affenrucksack für die Schule mitnehmen",
        "Ausmalbilder mit Affen für die Kinder drucken",
        "Afengehege im Zoo",
        "Primaten Ressevat besuchen",
        "Banannen für die Affen",
        "Afengeschenk zum Geburtstag",
        "Zooausfluug zu den Affen",
        "Affenkostüm für Halloween holen",
    ],
    ja=[
        "猿",
        "バナナ",
        "霊長類",
        "哺乳類",
        "動物",
        "野生動物",
        "ジャングル",
        "動物園",
        "チンパンジー",
        "ゴリラ",
        "オマキザル",
        "ニホンザル",
        "マカク",
        "類人猿",
        "サル",
        "野生",
        "動物園でサルの展示を見る",
        "霊長類保護区への旅行を計画する",
        "サルの館のチケットを買う",
        "正午のサルの餌やりを見る",
        "子供たちをサルに会いに連れていく",
        "霊長類救助センターでボランティアする",
        "野生の猿を見るジャングルツアーを予約する",
        "授業のために霊長類の行動について読む",
        "猿の保護基金に寄付する",
        "猿がテーマの誕生日プレゼントを買う",
        "野生動物公園で猿を撮影する",
        "動物園のサルのショーの時間を確認する",
        "サルとの触れ合いにバナナを持っていく",
        "霊長類のドキュメンタリーを見る",
        "サルの里親プログラムに申し込む",
        "動物園の遠足用にお菓子を用意する",
        "レポートのためにオマキザルを調べる",
        "赤ちゃんにぬいぐるみの猿を買う",
        "猿を見るために野生動物サファリを計画する",
        "博物館の霊長類の講演に参加する",
        "猿の島への旅行を計画する",
        "子供にサルのシールを買う",
        "ふれあい動物園でサルに餌をあげる",
        "絶滅危惧の霊長類について学ぶ",
        "学校のプロジェクト用にサルの情報を調べる",
        "ゲームナイト用にサルのパズルを手に入れる",
        "昼食後にチンパンジーの所に行く",
        "サル観覧用の動物園年間パスを更新する",
        "猿のパーティー用にバナナケーキを注文する",
        "三時のサルのショーのリマインダーを設定する",
        "幼児にサルのパジャマを買う",
        "今日サルの散歩道が開いているか確認する",
        "動物園にサルのツアーについて電話する",
        "霊長類ワークショップの席を予約する",
        "学校にサルのリュックを持っていく",
        "子供にサルのぬりえを印刷する",
        "ハロウィン用にサルの衣装を取りに行く",
        "どうぶつえん の さる",
        "ばなな を かう",
        "さる の ぬいぐるみ",
        "おさる の しょー",
        "さる を みに いく",
    ],
    fr=[
        "singe",
        "banane",
        "primate",
        "mammifère",
        "animal",
        "faune",
        "jungle",
        "zoo",
        "chimpanzé",
        "gorille",
        "capucin",
        "macaque",
        "babouin",
        "guenon",
        "ouistiti",
        "parc animalier",
        "visiter l'enclos des singes au zoo",
        "planifier une visite au sanctuaire de primates",
        "acheter des billets pour la maison des singes",
        "regarder le nourrissage des singes à midi",
        "emmener les enfants voir les singes",
        "faire du bénévolat au centre de primates",
        "réserver un tour dans la jungle pour voir les singes",
        "lire sur le comportement des primates pour les cours",
        "faire un don au fonds de protection des singes",
        "acheter un cadeau d'anniversaire sur le thème des singes",
        "photographier les singes au parc animalier",
        "vérifier les horaires du spectacle de singes au zoo",
        "apporter des bananes pour la rencontre avec les singes",
        "regarder un documentaire sur les primates",
        "s'inscrire au programme de parrainage de singes",
        "préparer des goûters pour la sortie au zoo",
        "préparer un exposé sur les capucins",
        "acheter un singe en peluche pour le bébé",
        "planifier un safari pour voir des singes",
        "assister à la conférence sur les primates au musée",
        "planifier un voyage à l'île aux singes",
        "acheter des autocollants de singes pour les enfants",
        "nourrir les singes au zoo de contact",
        "apprendre sur les espèces de primates en danger",
        "chercher des infos sur les singes pour le projet scolaire",
        "prendre le jeu de puzzle singes pour la soirée jeux",
        "aller voir les chimpanzés après le déjeuner",
        "renouveler l'abonnement zoo pour les visites aux singes",
        "commander un gâteau banane pour la fête des singes",
        "mettre un rappel pour le spectacle de singes à trois heures",
        "acheter un pyjama singe pour le petit",
        "vérifier si le sentier des singes est ouvert aujourd'hui",
        "appeler le zoo pour le tour des singes",
        "réserver des places pour l'atelier primates",
        "prendre le sac à dos singe pour l'école",
        "imprimer des coloriages de singes pour les enfants",
        "récupérer le costume de singe pour Halloween",
        "signe au zoo",
        "primats sanctuaire visite",
        "bananes pour le singes",
        "sinqe cadeau anniversaire",
        "exursion au zoo pour les singes",
        "déguisement de signe pour Halloween",
    ],
    es=[
        "mono",
        "banana",
        "primate",
        "mamífero",
        "animal",
        "fauna",
        "selva",
        "zoológico",
        "chimpancé",
        "gorila",
        "capuchino",
        "macaco",
        "mandril",
        "tití",
        "simio",
        "parque de fauna",
        "visitar el recinto de monos en el zoo",
        "planear una visita al santuario de primates",
        "comprar entradas para la casa de los monos",
        "ver la alimentación de los monos al mediodía",
        "llevar a los niños a ver los monos",
        "ser voluntario en el centro de rescate de primates",
        "reservar un tour por la selva para ver monos salvajes",
        "leer sobre el comportamiento de los primates para clase",
        "donar al fondo de conservación de monos",
        "comprar un regalo de cumpleaños con tema de mono",
        "fotografiar monos en el parque de fauna",
        "revisar el horario del show de monos en el zoo",
        "llevar bananas para el encuentro con monos",
        "ver un documental sobre primates",
        "inscribirse en el programa de apadrinamiento de monos",
        "preparar bocadillos para la excursión al zoo",
        "investigar sobre monos capuchinos para el informe",
        "comprar un mono de peluche para el bebé",
        "planear un safari para ver monos",
        "asistir a la charla de primates en el museo",
        "planear un viaje a la isla de los monos",
        "comprar calcomanías de monos para los niños",
        "dar de comer a los monos en el zoo interactivo",
        "aprender sobre especies de primates en peligro",
        "buscar datos de monos para el proyecto escolar",
        "conseguir el rompecabezas de monos para la noche de juegos",
        "ir a ver a los chimpancés después del almuerzo",
        "renovar la membresía del zoo para visitar monos",
        "pedir un pastel de banana para la fiesta de monos",
        "poner un recordatorio para el show de monos a las tres",
        "comprar pijama de monos para el pequeño",
        "revisar si el sendero de monos está abierto hoy",
        "llamar al zoo por el tour de monos",
        "reservar lugares para el taller de primates",
        "llevar la mochila de mono a la escuela",
        "imprimir dibujos de monos para colorear",
        "recoger el disfraz de mono para Halloween",
        "mono en el soológico",
        "primate santurio visita",
        "bannas para los monos",
        "mono de peluce para el bebé",
        "excurción al zoo para los monos",
        "disfras de mono para Halloween",
    ],
)

print("Part 1 done: money-check, monkey")
