#!/usr/bin/env python3
"""Generate English training data for icons 307-318."""
from pathlib import Path
import csv, json

icons_dir = Path("icons")
icons_dir.mkdir(exist_ok=True)

def write_csv(path, rows):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["text", "label"])
        w.writerows(rows)

def process_icon(icon, st_en, pst_en, reg_en, conv_en, typo_en, bnd_en, valid_en, test_en):
    icon_dir = icons_dir / icon
    icon_dir.mkdir(parents=True, exist_ok=True)
    train_en = [(t, icon) for t in st_en + pst_en + reg_en + conv_en + typo_en + bnd_en]
    write_csv(icon_dir / "train_en.csv", train_en)
    write_csv(icon_dir / "valid_en.csv", [(t, icon) for t in valid_en])
    write_csv(icon_dir / "test_en.csv",  [(t, icon) for t in test_en])
    log = {
        "icon": icon, "search_terms": st_en, "phrase_per_search_term": pst_en,
        "regular": reg_en, "conversational": conv_en, "typo": typo_en,
        "boundary": bnd_en, "valid": valid_en, "test": test_en,
    }
    with open(icon_dir / "icon_log.json", "w", encoding="utf-8") as f:
        json.dump(log, f, ensure_ascii=False, indent=2)
    n_st = len(st_en); n_pst = len(pst_en)
    print(f"  {icon}: {len(train_en)} train rows  ({n_st} st + {n_pst} pst + 24)")

# 307
process_icon("anchor",
    st_en=["anchor", "berth", "boat", "dock", "embed", "link", "maritime", "moor", "port", "secure", "ship", "tool"],
    pst_en=[
        "drop anchor in the harbor", "ship anchor holding the vessel steady",
        "berth in the marina for the boat", "anchor at the berth overnight",
        "boat secured with an anchor", "anchor for the sailing boat",
        "anchor the boat at the dock", "dock the vessel with the anchor down",
        "embed an anchor element in HTML", "anchor tag embedded in the webpage",
        "anchor link jumping to a section", "HTML anchor link tag",
        "maritime anchor symbol on the badge", "anchor used in maritime operations",
        "moor the boat with an anchor", "anchor to moor in the bay",
        "anchor dropped at the port entrance", "port anchor for the vessel",
        "anchor to secure the boat in place", "secure the vessel with an anchor",
        "ship anchor dropped to hold position", "anchor on the ship's bow",
        "anchor as a nautical tool", "anchor tool for the seafarer",
    ],
    reg_en=[
        "heavy iron anchor dropped to the sea floor",
        "anchor symbol on the sailor's tattoo",
        "ship anchor with chain on the dock",
        "anchor holding the vessel steady in the storm",
        "HTML anchor tag linking to another section",
        "anchor icon for a navigation link element",
        "maritime anchor on the navy uniform badge",
        "anchor emoji used in a sailing context",
        "small boat anchor at the lakeside pier",
        "anchor secured to the dock cleat",
    ],
    conv_en=[
        "I need an anchor icon for the maritime app",
        "add an anchor symbol to the navigation section",
        "show an anchor for the link element",
        "use the anchor icon for the dock booking feature",
    ],
    typo_en=[
        "ankhor dropped in harbor",
        "ancor symbol on uniform",
        "maritme anchor chain",
        "moor the baot with anchor",
    ],
    bnd_en=[
        "fishing hook with a sharp barbed tip",
        "thick chain holding the gate closed",
        "orange buoy floating on the water surface",
        "rope coiled on the boat deck",
        "compass rose showing navigation directions",
        "life ring preserver mounted on the vessel wall",
    ],
    valid_en=["ship anchor dropped in the harbor", "anchor symbol for maritime", "anchor link in HTML"],
    test_en=["anchor icon", "boat anchor symbol", "anchor for navigation"],
)

# 308
process_icon("child",
    st_en=["boy", "girl", "kid", "toddler", "young", "youth"],
    pst_en=[
        "young boy playing outside", "boy running in the park",
        "little girl with a colorful backpack", "girl playing with toys",
        "kid on the playground slide", "child kid at the school yard",
        "toddler taking first steps", "toddler playing with building blocks",
        "young child learning to read", "young kid at the playground",
        "youth program for children", "youth activities at the community center",
    ],
    reg_en=[
        "small child playing at the playground",
        "child holding a parent's hand while crossing",
        "toddler running on the grass",
        "young girl reading a picture book",
        "child waving with a big smile",
        "kid on the school playground",
        "child icon for parental controls",
        "young boy kicking a ball",
        "child safety feature indicator",
        "group of children playing together",
    ],
    conv_en=[
        "I need a child icon for the parental control section",
        "add a kid symbol to the family app",
        "show a child for the children's mode feature",
        "use the child icon for the youth category",
    ],
    typo_en=[
        "toddler takng first steps",
        "yonung child playing outside",
        "kdi on the playground",
        "chid safety feature",
    ],
    bnd_en=[
        "baby lying in a crib",
        "adult person standing upright",
        "family group with parents and children",
        "stroller with a baby inside",
        "teenager with a school backpack",
        "elderly person with a walking cane",
    ],
    valid_en=["child playing at the playground", "kid with a backpack", "toddler taking first steps"],
    test_en=["child icon", "kid symbol for family", "young child figure"],
)

# 309
process_icon("church",
    st_en=["Christian", "building", "cathedral", "chapel", "church", "community", "cross", "religion"],
    pst_en=[
        "Christian church building in the neighborhood", "Christian community gathering at church",
        "church building with a steeple", "historic building used for worship",
        "cathedral with gothic arched windows", "cathedral in the city center",
        "small chapel in the countryside", "chapel for quiet prayer",
        "church on Sunday morning", "attend church service on the weekend",
        "church community gathering for events", "community center in the church hall",
        "church with a cross on top", "cross on top of the church steeple",
        "religion building of worship", "church as a religion landmark",
    ],
    reg_en=[
        "church building with a tall steeple and cross",
        "stone cathedral with gothic arched windows",
        "small white chapel in the countryside",
        "Sunday church service for the community",
        "church bells ringing on a Sunday morning",
        "wedding ceremony held in the historic church",
        "stained glass windows of the cathedral",
        "church community gathering for holiday events",
        "historic old church in the town square",
        "church spire visible above the rooftops",
    ],
    conv_en=[
        "I need a church icon for the religious events section",
        "add a chapel symbol to the places of worship map",
        "show a church for the community events page",
        "use the cathedral icon for the religious site map",
    ],
    typo_en=[
        "cathdral gothic windows",
        "chruch service on Sunday",
        "chapell in the countryside",
        "comunity church event",
    ],
    bnd_en=[
        "mosque with a crescent moon and minaret",
        "Hindu temple with an ornate carved spire",
        "synagogue with a Star of David",
        "Buddhist temple with a curved roof",
        "monastery on the hilltop",
        "prayer hall interior with an altar",
    ],
    valid_en=["church with steeple and cross", "cathedral in the city", "chapel for Sunday service"],
    test_en=["church icon", "church building symbol", "chapel for worship"],
)

# 310
process_icon("coin",
    st_en=["coin", "dime", "gold", "metal", "money", "nickel", "penny", "premium", "quarter", "silver", "treasure"],
    pst_en=[
        "gold coin on the table", "coin flipped to decide",
        "shiny dime worth ten cents", "dime coin for the vending machine",
        "gold coin from the treasure chest", "gold coin reward in the game",
        "metal coin from the mint", "shiny metal coin in the palm",
        "coin as money for the piggy bank", "money coin for the vending machine",
        "nickel coin worth five cents", "nickel in the jar",
        "penny tossed in the fountain", "shiny penny for good luck",
        "premium coin for the subscription", "premium gold coin reward",
        "quarter coin for the parking meter", "quarter worth twenty-five cents",
        "silver coin from the collection", "silver coin minted in the treasury",
        "treasure chest full of gold coins", "treasure coin found in the ruins",
    ],
    reg_en=[
        "shiny gold coin with an embossed design",
        "coin tossed in the air for a decision",
        "pile of coins in the piggy bank",
        "gold coin reward in the mobile game",
        "ancient coin found on an archaeological dig",
        "coin collection displayed in a glass case",
        "vending machine accepting coin payment",
        "coin flip to decide the starting team",
        "silver coin minted with the national emblem",
        "treasure chest full of golden coins",
    ],
    conv_en=[
        "I need a coin icon for the in-game currency",
        "add a gold coin to the rewards section",
        "show a coin for the payment feature",
        "use the coin icon for the premium currency",
    ],
    typo_en=[
        "goid coin reward",
        "tresuare chest of coins",
        "silvr coin collection",
        "premuim coin earned",
    ],
    bnd_en=[
        "paper dollar bill in the wallet",
        "credit card swiped at the terminal",
        "gold bar stacked in the vault",
        "piggy bank for saving spare change",
        "stack of poker chips on the table",
        "gem or diamond for in-game currency",
    ],
    valid_en=["gold coin for in-game currency", "shiny coin with embossed design", "coin tossed for a decision"],
    test_en=["coin icon", "gold coin symbol", "coin for payment"],
)

# 311
process_icon("comment",
    st_en=["answer", "bubble", "chat", "commenting", "conversation", "discussion", "feedback", "message", "note", "notification", "sms", "speech", "talk", "talking", "texting"],
    pst_en=[
        "answer in the comment section", "reply with an answer comment",
        "speech bubble for the comment", "chat bubble showing a reply",
        "chat comment in the thread", "open chat to comment on post",
        "commenting on the post", "leave a commenting reply",
        "conversation in the comment thread", "start a conversation with a comment",
        "discussion in the comment section", "open discussion with a comment",
        "leave feedback in the comment box", "feedback comment on the post",
        "message in a comment box", "leave a message comment",
        "note left as a comment", "note in the feedback comment box",
        "comment notification badge", "notification for a new comment",
        "sms-style comment bubble", "short comment like an sms message",
        "speech comment in conversation", "speech bubble for the reply",
        "talk in the comment thread", "talk through a comment reply",
        "talking comment bubble icon", "talking through comments on the post",
        "texting-style comment interface", "comment like texting a message",
    ],
    reg_en=[
        "speech bubble with a text comment",
        "comment notification on the social post",
        "reply comment in the thread",
        "add a comment to the discussion",
        "feedback comment box on the article",
        "chat bubble showing a new message",
        "comment count displayed on the post",
        "leave a note in the comment section",
        "inline comment on the shared document",
        "conversation thread with multiple comments",
    ],
    conv_en=[
        "I need a comment icon for the social feed",
        "add a speech bubble to the feedback section",
        "show a comment bubble on the post card",
        "use the comment icon for the discussion thread",
    ],
    typo_en=[
        "coment on the post",
        "feeback comment box",
        "discusion thread",
        "notificaiton for new comment",
    ],
    bnd_en=[
        "direct message envelope in the inbox",
        "notification bell with badge count",
        "thumbs-up like on the social post",
        "email message with unread indicator",
        "quote block for the cited text",
        "mention tag with at-sign symbol",
    ],
    valid_en=["comment speech bubble on post", "feedback comment in the thread", "new comment notification"],
    test_en=["comment icon", "comment bubble symbol", "speech bubble comment"],
)

# 312
process_icon("cupcake",
    st_en=["birthday", "dessert", "frosting", "sweet"],
    pst_en=[
        "birthday cupcake with a candle", "cupcake for the birthday celebration",
        "cupcake as a dessert treat", "dessert cupcake from the bakery",
        "cupcake with colorful frosting on top", "frosting swirled on top of cupcake",
        "sweet cupcake treat for kids", "sweet frosted cupcake from the shop",
    ],
    reg_en=[
        "cupcake with pink frosting and a birthday candle",
        "birthday cupcake with colorful sprinkles",
        "chocolate cupcake from the bakery",
        "cupcake with cream cheese frosting",
        "homemade cupcake for the school bake sale",
        "cupcake display at the dessert table",
        "vanilla cupcake with swirled frosting",
        "mini cupcake served as a party favor",
        "cupcake icon for the bakery menu",
        "cupcake decorated with fondant flowers",
    ],
    conv_en=[
        "I need a cupcake icon for the bakery app",
        "add a cupcake symbol to the birthday feature",
        "show a cupcake for the desserts category",
        "use the cupcake icon for the sweet treats section",
    ],
    typo_en=[
        "cupcke with frosting",
        "birthdya cupcake candle",
        "frostng on the cupcake",
        "swet cupcake treat",
    ],
    bnd_en=[
        "muffin with blueberries on top",
        "birthday cake with multiple lit candles",
        "glazed donut with colorful sprinkles",
        "chocolate chip cookie on a plate",
        "ice cream cone with two scoops",
        "macaroon with cream filling",
    ],
    valid_en=["cupcake with frosting and candle", "birthday cupcake with sprinkles", "sweet cupcake from bakery"],
    test_en=["cupcake icon", "frosted cupcake symbol", "birthday cupcake"],
)

# 313
process_icon("drum",
    st_en=["drum", "drumsticks", "instrument", "music", "percussion", "snare", "sound"],
    pst_en=[
        "beat the drum in the band", "drum set in the recording studio",
        "drumsticks striking the snare", "pair of drumsticks on the kit",
        "drum as a musical instrument", "instrument played in the band",
        "music played on the drum", "drum music in the rhythm section",
        "percussion drum in the orchestra", "percussion section of the band",
        "snare drum roll at the parade", "tight snare drum sound",
        "sound of the drum beat", "deep bass drum sound",
    ],
    reg_en=[
        "drum kit in the recording studio",
        "drummer playing snare drum on stage",
        "African djembe drum played by hand",
        "marching band bass drum at the parade",
        "drumsticks resting on the snare drum",
        "steel drum played at a Caribbean festival",
        "drum solo at the rock concert",
        "bongo drums for rhythm practice",
        "drum machine producing beats in the studio",
        "parade drummer keeping the marching tempo",
    ],
    conv_en=[
        "I need a drum icon for the music app",
        "add a drum symbol to the percussion section",
        "show a drum for the band instruments category",
        "use the drum icon for the rhythm game",
    ],
    typo_en=[
        "snare durm roll",
        "drumstciks on kit",
        "percusion drum",
        "musci played on drum",
    ],
    bnd_en=[
        "electric guitar on the concert stage",
        "grand piano in the concert hall",
        "brass trumpet playing a fanfare",
        "tambourine shaken in the rhythm section",
        "violin bow drawn across the strings",
        "bass guitar played in the band",
    ],
    valid_en=["drum kit in the studio", "snare drum roll", "percussion drum instrument"],
    test_en=["drum icon", "drum symbol for music", "snare drum beat"],
)

# 314
process_icon("eye",
    st_en=["body", "eye", "look", "optic", "see", "seen", "show", "sight", "views", "visible"],
    pst_en=[
        "eye as a body part", "body eye anatomy diagram",
        "human eye looking forward", "eye icon for visibility",
        "look with the eye icon", "eye look at the screen",
        "optic nerve in the human eye", "optic lens of the eye",
        "see the world through your eyes", "eye used to see",
        "seen indicator in the chat", "message seen by the eye icon",
        "show or hide password with eye icon", "show password eye toggle button",
        "sight through the eye", "eye for sight and health",
        "views counted with the eye icon", "eye views on the post",
        "visible toggle eye icon", "make content visible with the eye",
    ],
    reg_en=[
        "human eye with iris and pupil",
        "eye icon for show or hide password",
        "view count shown with an eye icon",
        "eye anatomy diagram showing the retina",
        "watchful eye symbol for surveillance",
        "evil eye protection amulet",
        "eye drops for dry eye relief",
        "eye exam chart at the optometrist",
        "seen indicator showing the message was read",
        "eye tracking cursor movement on screen",
    ],
    conv_en=[
        "I need an eye icon for the visibility toggle",
        "add an eye symbol to the view count",
        "show an eye for the watch list feature",
        "use the eye icon for the show password button",
    ],
    typo_en=[
        "visiblity toggle eye",
        "eye seeen indicator",
        "shwo password eye",
        "veiwed by eye icon",
    ],
    bnd_en=[
        "eyeglasses with round frames",
        "binoculars for bird watching",
        "telescope pointed at the night sky",
        "camera lens focused on the subject",
        "magnifying glass for close inspection",
        "spotlight shining on the stage",
    ],
    valid_en=["eye icon for visibility", "human eye with iris and pupil", "view count eye symbol"],
    test_en=["eye icon", "eye symbol for sight", "show hide eye toggle"],
)

# 315
process_icon("hearts",
    st_en=["favorite", "hearts", "love", "valentine"],
    pst_en=[
        "hearts marking a favorite item", "add to favorites with hearts",
        "multiple hearts for the reaction", "hearts floating up on a live stream",
        "hearts expressing love", "love shown with hearts",
        "valentine hearts for February", "hearts for the Valentine's Day card",
    ],
    reg_en=[
        "multiple red hearts floating upward",
        "hearts reaction on the social post",
        "Valentine's Day card filled with hearts",
        "hearts emoji for expressing love",
        "heart confetti scattered for the celebration",
        "double heart symbol for a strong bond",
        "hearts pattern for the love theme",
        "hearts on the dating app profile",
        "animated hearts floating in the live stream",
        "colorful hearts for the greeting card",
    ],
    conv_en=[
        "I need a hearts icon for the love feature",
        "add hearts to the Valentine's Day section",
        "show hearts for the favorites reaction",
        "use the hearts icon for the like animation",
    ],
    typo_en=[
        "valentien hearts card",
        "favoirite hearts",
        "hearst floating up",
        "lve hearts reaction",
    ],
    bnd_en=[
        "single red heart for the like button",
        "gold star for a favorite rating",
        "thumbs up like on the social post",
        "diamond ring for engagement",
        "rose bouquet for romance",
        "smiley face emoji for happiness",
    ],
    valid_en=["multiple hearts for Valentine's Day", "hearts reaction on the post", "love hearts symbol"],
    test_en=["hearts icon", "hearts for love", "valentine hearts symbol"],
)

# 316
process_icon("heat",
    st_en=["ac", "air conditioner", "boiler", "heating", "hot", "sauna", "spa", "summer", "temperature"],
    pst_en=[
        "AC unit set to heat mode", "AC heating the room in winter",
        "air conditioner in heating mode", "air conditioner warming the house",
        "boiler heating the hot water", "boiler system for home heat",
        "heating turned on in winter", "home heating system running",
        "hot temperature warning symbol", "hot heat from the heating vent",
        "sauna heat set to high temperature", "dry heat session in the sauna",
        "spa heated pool with warmth", "spa heat for relaxation",
        "summer heat symbol for the season", "summer heat wave warning",
        "temperature rising heat indicator", "set the heat temperature on the dial",
    ],
    reg_en=[
        "heat waves rising from the hot surface",
        "home heating system turned on in winter",
        "sauna temperature set to high heat",
        "heat wave warning for the summer day",
        "boiler providing heat to the radiator",
        "warm air flowing from the heating vent",
        "temperature gauge showing the hot setting",
        "spa heated pool with steam rising",
        "heat map showing temperature zones",
        "radiant heat from the fireplace",
    ],
    conv_en=[
        "I need a heat icon for the thermostat app",
        "add a heating symbol to the home controls",
        "show a heat warning for high temperature",
        "use the heat icon for the sauna mode",
    ],
    typo_en=[
        "heatng turned on in winter",
        "temerature rising fast",
        "sauna het session",
        "boielr heating system",
    ],
    bnd_en=[
        "orange flame burning in the fireplace",
        "bright sun radiating heat in summer",
        "thermometer showing high temperature",
        "snowflake symbol for cold temperature",
        "air conditioning snowflake cool mode",
        "steam cloud rising from the hot cup",
    ],
    valid_en=["home heating in winter", "sauna heat temperature", "heat wave summer warning"],
    test_en=["heat icon", "heating symbol for thermostat", "heat temperature warning"],
)

# 317
process_icon("helicopter",
    st_en=["airwolf", "apache", "chopper", "flight", "fly", "helicopter", "travel", "vehicle"],
    pst_en=[
        "airwolf helicopter from the TV show", "airwolf attack helicopter in action",
        "apache military helicopter in flight", "Apache attack helicopter hovering",
        "news chopper overhead at the scene", "police chopper searching the area",
        "helicopter flight over the city", "short flight by helicopter to the island",
        "fly by helicopter to the resort", "helicopter fly low over the valley",
        "helicopter hovering in the air", "helicopter landing on the helipad",
        "travel by helicopter to the resort", "helicopter travel for VIP guests",
        "helicopter as a vehicle for air transport", "rotary vehicle helicopter",
    ],
    reg_en=[
        "helicopter hovering above the city skyline",
        "medical rescue helicopter landing on rooftop",
        "news helicopter circling overhead",
        "military Apache attack helicopter",
        "helicopter tour over the mountain range",
        "police helicopter searching at night",
        "helicopter landing on an offshore platform",
        "private helicopter for VIP transport",
        "helicopter blades spinning at full speed",
        "coast guard rescue helicopter in action",
    ],
    conv_en=[
        "I need a helicopter icon for the air transport section",
        "add a chopper symbol to the flight tracker",
        "show a helicopter for the rescue operations feature",
        "use the helicopter icon for the aerial tour booking",
    ],
    typo_en=[
        "helicotper hovering",
        "choppr circling overhead",
        "militray helicopter",
        "hleicopter landing pad",
    ],
    bnd_en=[
        "commercial airplane flying at cruising altitude",
        "quadcopter drone with camera hovering",
        "hot air balloon floating over the valley",
        "rocket ship launching into space",
        "small propeller plane on the runway",
        "paraglider soaring on the thermal updraft",
    ],
    valid_en=["helicopter hovering in the air", "rescue helicopter on rooftop pad", "military helicopter in flight"],
    test_en=["helicopter icon", "chopper symbol for flight", "helicopter air transport"],
)

# 318
process_icon("infinity",
    st_en=["eternity", "forever", "infinity", "math", "unbounded", "universal"],
    pst_en=[
        "eternity symbol of infinity", "eternity ring with infinity shape",
        "forever represented by the infinity loop", "love that lasts forever infinity symbol",
        "infinity sign looping endlessly", "infinity symbol for endless possibilities",
        "math infinity symbol in calculus", "infinity notation in mathematics",
        "unbounded set infinity in math", "infinite unbounded growth symbol",
        "universal set symbol in mathematics", "universal infinity for all things",
    ],
    reg_en=[
        "infinity loop symbol representing endlessness",
        "infinity sign used in mathematics notation",
        "gold infinity necklace as a gift",
        "infinity symbol for an unlimited subscription",
        "infinity loop in a loading animation",
        "infinity tattoo on the wrist",
        "infinite loop symbol in software design",
        "eternity ring with an infinity design",
        "infinity symbol used in a brand logo",
        "lemniscate infinity shape in calculus",
    ],
    conv_en=[
        "I need an infinity icon for the unlimited plan",
        "add an infinity symbol to the eternity feature",
        "show an infinity loop for the unlimited tier",
        "use the infinity icon for the forever subscription",
    ],
    typo_en=[
        "infintiy symbol loop",
        "enternity ring design",
        "forevr infinity loop",
        "maths infniity notation",
    ],
    bnd_en=[
        "figure eight shape lying on its side",
        "recycling loop arrows symbol",
        "ouroboros snake eating its own tail",
        "circular arrow indicating repeat or refresh",
        "chain link forming a connected loop",
        "zero or oval shape in the number system",
    ],
    valid_en=["infinity symbol for unlimited", "infinity loop in mathematics", "eternity infinity design"],
    test_en=["infinity icon", "infinity symbol math", "endless loop infinity"],
)
