#!/usr/bin/env python3
"""Task-003 part 2: moon, mortar-pestle"""
from gen_icons_task_003_lib import build_icon

# ── moon ─────────────────────────────────────────────────────────────────────
build_icon("moon",
    keep_en=[
        "contrast",
        "crescent",
        "crescent moon",
        "dark",
        "lunar",
        "moon",
        "night",
        "crescent moon rising over the horizon",
        "crescent moon phase during a clear night",
        "dark sky at midnight with stars visible",
        "lunar calendar showing moon phases",
        "lunar orbit around the earth",
        "full moon glowing in the night sky",
        "moon phase tracker for astronomy",
        "night mode enabled at sunset automatically",
        "quiet night with a bright crescent moon",
        "moom phase tonight",
        "mooon rising over the hills",
        "cresent moon in the evening",
        "luanr calendar for moon phases",
    ],
    new_en=[
        "Waning Crescent Moon",
        "nighttime",
        "moonlight",
        "stargazing",
        "eclipse",
        "waxing",
        "waning",
        "new moon",
        "full moon",
        "moonrise",
        "check the moon phase tonight",
        "set alarm for moonrise",
        "plan a moonlight hike this weekend",
        "look up tonight's lunar eclipse time",
        "mark the full moon on the calendar",
        "schedule stargazing for the new moon",
        "check the lunar calendar for planting",
        "watch the crescent moon after sunset",
        "set the night mode before bed",
        "adjust screen contrast for nighttime",
        "track the moon cycle this month",
        "photograph the moon tonight",
        "read about the lunar landing anniversary",
        "plan a night walk under the full moon",
        "note the moonset time for tomorrow",
        "switch to dark mode in the evening",
        "buy a telescope to watch the moon",
        "check the tide chart linked to moon phase",
        "attend the lunar eclipse viewing event",
        "download a moon phase app",
        "remind me to watch the supermoon Friday",
        "set nighttime do-not-disturb mode",
        "look at the waning crescent tonight",
        "mark the new moon date for meditation",
        "turn on night shift on the phone",
        "research lunar phases for science class",
        "book a night sky photography tour",
        "moonligt hike on Saturday",
        "luanr eclipse tonight",
        "nigt mode before bed",
    ],
    keep_ru=[
        "контраст",
        "полумесяц",
        "луна серп",
        "темный",
        "лунный",
        "луна",
        "ночь",
        "светло-темный контраст в настройках экрана",
        "полумесяц поднимается над горизонтом",
        "фаза полумесяца ясной ночью",
        "темное небо в полночь со звездами",
        "лунный календарь показывает фазы",
        "лунная орбита вокруг земли",
        "полная луна светится в ночном небе",
        "трекер фаз луны для астрономии",
        "ночной режим включается на закате",
        "тихая ночь с ярким серпом луны",
        "фаза луны сегодня ночью",
        "луна поднимается над холмами",
        "полумесяц вечером",
        "лунный календарь фаз луны",
    ],
    new_ru=[
        "убывающий серп луны",
        "ночное время",
        "лунный свет",
        "наблюдение за звёздами",
        "затмение",
        "растущая луна",
        "убывающая луна",
        "новолуние",
        "полнолуние",
        "восход луны",
        "проверить фазу луны сегодня",
        "поставить будильник на восход луны",
        "запланировать ночную прогулку в лунном свете",
        "узнать время лунного затмения",
        "отметить полнолуние в календаре",
        "запланировать наблюдение звёзд на новолуние",
        "проверить лунный посевной календарь",
        "наблюдать за полумесяцем после заката",
        "включить ночной режим перед сном",
        "настроить контрастность экрана для ночи",
        "отслеживать лунный цикл в этом месяце",
        "сфотографировать луну сегодня",
        "прочитать о годовщине высадки на Луну",
        "запланировать ночную прогулку в полнолуние",
        "записать время захода луны на завтра",
        "переключить на тёмный режим вечером",
        "купить телескоп чтобы наблюдать за луной",
        "проверить таблицу приливов по фазе луны",
        "пойти на наблюдение лунного затмения",
        "скачать приложение с фазами луны",
        "напомни посмотреть суперлуние в пятницу",
        "включить режим не беспокоить на ночь",
        "посмотреть на убывающий серп сегодня",
        "отметить новолуние для медитации",
        "включить ночной режим на телефоне",
        "изучить фазы луны для урока",
        "забронировать тур ночной фотосъёмки неба",
        "лунная прогулка в суббту",
        "лунное затмние сегодня",
    ],
    de=[
        "Mond",
        "Halbmond",
        "Mondsichel",
        "dunkel",
        "Nacht",
        "Mondphase",
        "Vollmond",
        "Neumond",
        "Mondlicht",
        "Mondfinsternis",
        "Nachtmodus",
        "Kontrast",
        "Sternbeobachtung",
        "Mondkalender",
        "Mondzyklus",
        "zunehmend",
        "abnehmend",
        "Dämmerung",
        "Mondphase heute Nacht prüfen",
        "Wecker für den Mondaufgang stellen",
        "Mondlichtwanderung am Wochenende planen",
        "Zeit der Mondfinsternis nachschlagen",
        "Vollmond im Kalender markieren",
        "Sternbeobachtung bei Neumond planen",
        "Mondkalender zum Pflanzen prüfen",
        "nach Sonnenuntergang den Halbmond beobachten",
        "Nachtmodus vor dem Schlafen einschalten",
        "Bildschirmkontrast für die Nacht anpassen",
        "Mondzyklus diesen Monat verfolgen",
        "Mond heute Nacht fotografieren",
        "über die Mondlandung lesen",
        "Nachtwanderung bei Vollmond planen",
        "Monduntergangszeit für morgen notieren",
        "abends in den Dunkelmodus wechseln",
        "Teleskop kaufen um den Mond zu beobachten",
        "Gezeitentabelle nach Mondphase prüfen",
        "Mondfinsternis-Beobachtung besuchen",
        "Mondphasen-App herunterladen",
        "an den Supermond am Freitag erinnern",
        "Nachtruhe-Modus einschalten",
        "abnehmenden Halbmond heute anschauen",
        "Neumond-Termin für Meditation notieren",
        "Nachtmodus auf dem Handy einschalten",
        "Mondphasen für den Unterricht lernen",
        "Nachthimmel-Fototour buchen",
        "Mondkalender für den Garten prüfen",
        "abendlichen Spaziergang bei Mondschein machen",
        "Mondaufgangszeit für heute nachschauen",
        "Mondlicht-Picknick am See planen",
        "Kindern die Mondphasen erklären",
        "Mondbeobachtung mit dem Fernglas",
        "Sonnenfinsternis und Mondfinsternis vergleichen",
        "Mondscheinwanderung organisieren",
        "Nachtfotografie bei Vollmond planen",
        "Monlicht Wanderung am Samstag",
        "Mondfinsternus heute Nacht",
        "Nachmodous einschalten",
        "Mondpahse prüfen",
        "Vollmon am Freitag",
        "Mondkalendr für den Garten",
    ],
    ja=[
        "月",
        "三日月",
        "暗い",
        "夜",
        "月の満ち欠け",
        "満月",
        "新月",
        "月光",
        "月食",
        "ナイトモード",
        "コントラスト",
        "星空観察",
        "月暦",
        "月齢",
        "上弦の月",
        "下弦の月",
        "夕暮れ",
        "月の出",
        "今夜の月の満ち欠けを確認する",
        "月の出にアラームをセットする",
        "週末に月明かりハイキングを計画する",
        "月食の時間を調べる",
        "カレンダーに満月を記入する",
        "新月に星空観察を計画する",
        "植え付け用の月暦を確認する",
        "日没後に三日月を観察する",
        "寝る前にナイトモードをオンにする",
        "夜間用に画面のコントラストを調整する",
        "今月の月の周期を追跡する",
        "今夜月を撮影する",
        "月面着陸の記念日について読む",
        "満月の夜に散歩を計画する",
        "明日の月の入り時刻をメモする",
        "夕方にダークモードに切り替える",
        "月を観察するために望遠鏡を買う",
        "月の満ち欠けに連動した潮見表を確認する",
        "月食の観察イベントに参加する",
        "月の満ち欠けアプリをダウンロードする",
        "金曜のスーパームーンを見るリマインダーを設定する",
        "夜間おやすみモードを設定する",
        "今夜下弦の月を見る",
        "瞑想のために新月の日を記録する",
        "スマホのナイトシフトをオンにする",
        "理科の授業で月の満ち欠けを調べる",
        "夜空の撮影ツアーを予約する",
        "月の暦で庭仕事を確認する",
        "夕方に月明かりで散歩する",
        "月の出の時刻を調べる",
        "湖畔で月光ピクニックを計画する",
        "子供に月の満ち欠けを説明する",
        "双眼鏡で月を観察する",
        "日食と月食を比べる",
        "満月の夜に写真を撮る",
        "月明かりハイキングを企画する",
        "げつしょく の じかん",
        "つき を みる",
        "よぞら の さんぽ",
        "なんげつ を かくにん",
        "まんげつ の よる",
    ],
    fr=[
        "lune",
        "croissant",
        "nuit",
        "sombre",
        "lunaire",
        "phase lunaire",
        "pleine lune",
        "nouvelle lune",
        "clair de lune",
        "éclipse lunaire",
        "mode nuit",
        "contraste",
        "observation des étoiles",
        "calendrier lunaire",
        "cycle lunaire",
        "croissant de lune",
        "décroissant",
        "crépuscule",
        "vérifier la phase de la lune ce soir",
        "mettre une alarme pour le lever de lune",
        "planifier une randonnée au clair de lune ce weekend",
        "chercher l'heure de l'éclipse lunaire",
        "marquer la pleine lune sur le calendrier",
        "planifier une observation des étoiles à la nouvelle lune",
        "consulter le calendrier lunaire pour les plantations",
        "observer le croissant de lune après le coucher du soleil",
        "activer le mode nuit avant de dormir",
        "ajuster le contraste de l'écran pour la nuit",
        "suivre le cycle lunaire ce mois-ci",
        "photographier la lune ce soir",
        "lire sur l'anniversaire de l'alunissage",
        "planifier une promenade nocturne sous la pleine lune",
        "noter l'heure du coucher de lune pour demain",
        "passer en mode sombre le soir",
        "acheter un télescope pour observer la lune",
        "vérifier la table des marées liée à la phase lunaire",
        "assister à l'observation de l'éclipse lunaire",
        "télécharger une application de phases lunaires",
        "rappel pour la super lune vendredi",
        "activer le mode ne pas déranger la nuit",
        "regarder le croissant décroissant ce soir",
        "noter la date de la nouvelle lune pour méditer",
        "activer le mode nuit sur le téléphone",
        "étudier les phases lunaires pour le cours de sciences",
        "réserver un tour photo du ciel nocturne",
        "consulter le calendrier lunaire pour le jardin",
        "promenade du soir au clair de lune",
        "pique-nique au clair de lune au bord du lac",
        "expliquer les phases de la lune aux enfants",
        "observer la lune avec des jumelles",
        "comparer éclipse solaire et éclipse lunaire",
        "organiser une randonnée au clair de lune",
        "photographier la pleine lune ce soir",
        "clair de luen randonnée samedi",
        "éclipse lunare ce soir",
        "mode nui activé",
        "phaze lunaire à vérifier",
        "plene lune vendredi",
        "calendrer lunaire pour le jardin",
    ],
    es=[
        "luna",
        "creciente",
        "noche",
        "oscuro",
        "lunar",
        "fase lunar",
        "luna llena",
        "luna nueva",
        "luz de luna",
        "eclipse lunar",
        "modo nocturno",
        "contraste",
        "observación de estrellas",
        "calendario lunar",
        "ciclo lunar",
        "cuarto creciente",
        "cuarto menguante",
        "crepúsculo",
        "revisar la fase lunar esta noche",
        "poner alarma para la salida de la luna",
        "planear una caminata a la luz de la luna este fin de semana",
        "buscar la hora del eclipse lunar",
        "marcar la luna llena en el calendario",
        "planear observación de estrellas en luna nueva",
        "consultar el calendario lunar para siembra",
        "observar el creciente lunar después del atardecer",
        "activar el modo nocturno antes de dormir",
        "ajustar el contraste de pantalla para la noche",
        "seguir el ciclo lunar este mes",
        "fotografiar la luna esta noche",
        "leer sobre el aniversario del alunizaje",
        "planear una caminata nocturna bajo la luna llena",
        "anotar la hora de puesta de luna para mañana",
        "cambiar a modo oscuro en la noche",
        "comprar un telescopio para observar la luna",
        "revisar la tabla de mareas según la fase lunar",
        "asistir al evento de observación del eclipse lunar",
        "descargar una app de fases lunares",
        "recordatorio para ver la superluna el viernes",
        "activar modo no molestar en la noche",
        "mirar el cuarto menguante esta noche",
        "anotar la fecha de luna nueva para meditar",
        "activar el turno de noche en el teléfono",
        "estudiar las fases lunares para la clase de ciencias",
        "reservar un tour de fotografía del cielo nocturno",
        "consultar el calendario lunar para el jardín",
        "paseo nocturno a la luz de la luna",
        "picnic a la luz de la luna junto al lago",
        "explicar las fases de la luna a los niños",
        "observar la luna con binoculares",
        "comparar eclipse solar y eclipse lunar",
        "organizar caminata bajo la luna llena",
        "fotografiar la luna llena esta noche",
        "lus de luna caminata el sábado",
        "eclise lunar esta noche",
        "modo noctuno activado",
        "faze lunar a revisar",
        "luna yena el viernes",
        "calendaro lunar para el jardín",
    ],
)

# ── mortar-pestle ────────────────────────────────────────────────────────────
build_icon("mortar-pestle",
    keep_en=[
        "crush",
        "culinary",
        "grind",
        "mix",
        "pharmacy",
        "spices",
        "crush garlic in mortar and pestle",
        "crush herbs to extract oils",
        "culinary tool for grinding spices",
        "culinary preparation with mortar",
        "grind peppercorns in stone bowl",
        "grind spices for cooking",
        "medical compounding pharmacy tool",
        "medical preparation grinding",
        "mix ingredients in mortar bowl",
        "mix herbs and spices together",
        "pharmacy symbol mortar and pestle",
        "pharmacy counter symbol",
        "prescription compounding with mortar",
        "prescription drug preparation",
        "grind fresh spices for flavor",
        "spice blend using mortar",
        "chef grinding spices in a kitchen mortar",
        "traditional medicine preparation with mortar",
        "guacamole made with molcajete mortar",
        "apothecary symbol for dispensing",
        "herbal medicine crushing and mixing",
        "crushing tablets or pills in a mortar",
        "cooking with freshly ground spice blend",
        "mortar and pstle",
        "grind spces",
        "pharmcy symbol",
        "culinayr tool",
    ],
    new_en=[
        "medicine",
        "prescription",
        "spice",
        "mortar",
        "pestle",
        "compounding",
        "herb",
        "grind cumin seeds for the curry",
        "crush peppercorns for the steak rub",
        "pick up the prescription at the pharmacy",
        "make a spice mix for the marinade",
        "prepare herbal remedy in the mortar",
        "refill the prescription this week",
        "grind cinnamon sticks for the recipe",
        "buy a mortar and pestle at the kitchen store",
        "crush dried chili flakes for the salsa",
        "mix the pharmacy compound for the ointment",
        "grind cardamom pods for the chai",
        "prepare the spice paste with the pestle",
        "check pharmacy hours for the prescription",
        "crush rock salt in the mortar",
        "make curry powder from whole spices",
        "call the pharmacy about the compounded cream",
        "grind sesame seeds for tahini",
        "prepare the herb blend for the tea",
        "crush garlic and ginger for the stir fry",
        "grind cloves for the pumpkin pie spice",
        "order refill of compounded medication",
        "crush almonds for the dessert topping",
        "make homemade garam masala in the mortar",
        "pestle and morter for the kitchen",
        "grnd the spices finer",
        "prescrption refill at the pharmcy",
    ],
    keep_ru=[
        "растирать",
        "кулинарный",
        "молоть",
        "смешивать",
        "аптека",
        "специи",
        "растереть чеснок в ступке с пестиком",
        "растереть травы для извлечения масел",
        "кулинарный инструмент для измельчения специй",
        "кулинарная подготовка со ступкой",
        "измельчить горошины перца в каменной чаше",
        "молоть специи для приготовления",
        "инструмент для приготовления лекарств в аптеке",
        "медицинская подготовка измельчение",
        "смешать ингредиенты в ступке",
        "смешать травы и специи",
        "символ аптеки ступка и пестик",
        "символ аптечного прилавка",
        "приготовление лекарств по рецепту в ступке",
        "подготовка лекарств по рецепту",
        "молоть свежие специи для вкуса",
        "смесь специй с ступкой",
        "шеф-повар молет специи в кухонной ступке",
        "традиционное приготовление лекарств со ступкой",
        "гуакамоле приготовленный в ступке молькахете",
        "символ аптекаря для раздачи",
        "измельчение и смешивание травяных лекарств",
        "дробление таблеток или пилюль в ступке",
        "приготовление со свежемолотой смесью специй",
        "ступка и пестки",
        "молоть специас",
        "аптека симовл",
        "кулинрный инструмент",
    ],
    new_ru=[
        "лекарство",
        "рецепт",
        "пряность",
        "ступка",
        "пестик",
        "фармацевт",
        "трава",
        "измельчить зиру для карри",
        "растереть перец для натирки стейка",
        "забрать рецепт в аптеке",
        "сделать смесь специй для маринада",
        "приготовить травяное средство в ступке",
        "продлить рецепт на этой неделе",
        "измельчить палочки корицы для рецепта",
        "купить ступку и пестик в кухонном магазине",
        "растереть сушёные хлопья чили для сальсы",
        "смешать аптечный состав для мази",
        "измельчить кардамон для чая",
        "приготовить пасту из специй пестиком",
        "уточнить часы работы аптеки для рецепта",
        "растереть каменную соль в ступке",
        "сделать порошок карри из целых специй",
        "позвонить в аптеку насчёт крема по рецепту",
        "измельчить кунжут для тахини",
        "приготовить травяной сбор для чая",
        "растереть чеснок и имбирь для жарки",
        "измелчить гвоздику для тыквеной смеси",
    ],
    de=[
        "Mörser",
        "Stößel",
        "Gewürz",
        "Apotheke",
        "mahlen",
        "zerkleinern",
        "mischen",
        "Rezept",
        "Medikament",
        "Kräuter",
        "Pharmazie",
        "Heilmittel",
        "Gewürzmischung",
        "Pfeffer",
        "Kompositum",
        "Arznei",
        "Heilkunde",
        "Küchenutensil",
        "Kreuzkümmel im Mörser für das Curry mahlen",
        "Pfefferkörner für die Steakwürzung zerstoßen",
        "Rezept in der Apotheke abholen",
        "Gewürzmischung für die Marinade machen",
        "Kräuterheilmittel im Mörser zubereiten",
        "Rezept diese Woche verlängern",
        "Zimtstangen für das Rezept mahlen",
        "Mörser und Stößel im Küchengeschäft kaufen",
        "getrocknete Chiliflocken für die Salsa zerkleinern",
        "Apothekenmischung für die Salbe anrühren",
        "Kardamomkapseln für den Chai mahlen",
        "Gewürzpaste mit dem Stößel zubereiten",
        "Apothekenöffnungszeiten für das Rezept prüfen",
        "Steinsalz im Mörser zerkleinern",
        "Currypulver aus ganzen Gewürzen herstellen",
        "Apotheke wegen der Rezeptcreme anrufen",
        "Sesamsamen für Tahini mahlen",
        "Kräutermischung für den Tee vorbereiten",
        "Knoblauch und Ingwer für den Wok zerkleinern",
        "Nelken für die Kürbiskuchengewürz mahlen",
        "Nachbestellung des Rezeptmedikaments",
        "Mandeln für den Dessertbelag zerkleinern",
        "hausgemachtes Garam Masala im Mörser machen",
        "frische Gewürze im Mörser zerreiben",
        "Kräutertee mit frisch gemörserten Zutaten",
        "Gewürze für die Suppe im Mörser mahlen",
        "Apotheke wegen Medikament anrufen",
        "Gewürzmischung für den Grill vorbereiten",
        "Kräutersalz im Mörser herstellen",
        "Möser und Stößel kaufen",
        "Gewürz mahln",
        "Apothke Rezept abholen",
        "Kräutr mischen",
        "Pfeferkörner zerstoßen",
        "Medikamnt in der Apotheke",
    ],
    ja=[
        "すり鉢",
        "すりこぎ",
        "香辛料",
        "薬局",
        "すりつぶす",
        "混ぜる",
        "調合",
        "処方箋",
        "薬",
        "ハーブ",
        "スパイス",
        "漢方",
        "製薬",
        "調剤",
        "粉砕",
        "薬味",
        "乳鉢",
        "調味料",
        "カレー用にクミンをすり鉢で挽く",
        "ステーキ用に胡椒をすりつぶす",
        "薬局で処方箋を受け取る",
        "マリネ用にスパイスミックスを作る",
        "すり鉢でハーブの薬を準備する",
        "今週中に処方箋を更新する",
        "レシピ用にシナモンスティックを挽く",
        "キッチン用品店ですり鉢を買う",
        "サルサ用に乾燥チリフレークをすりつぶす",
        "軟膏用に薬局の調合薬を混ぜる",
        "チャイ用にカルダモンを挽く",
        "すりこぎでスパイスペーストを作る",
        "処方箋のために薬局の営業時間を確認する",
        "すり鉢で岩塩をすりつぶす",
        "ホールスパイスからカレー粉を作る",
        "調合クリームについて薬局に電話する",
        "タヒニ用にごまを挽く",
        "お茶用のハーブブレンドを準備する",
        "炒め物用ににんにくと生姜をすりつぶす",
        "パンプキンパイスパイス用にクローブを挽く",
        "調合薬の補充を注文する",
        "デザートのトッピング用にアーモンドを砕く",
        "すり鉢で自家製ガラムマサラを作る",
        "すり鉢で新鮮なスパイスをすりつぶす",
        "すりこぎで七味を作る",
        "スープ用のスパイスを挽く",
        "薬局に薬について電話する",
        "バーベキュー用のスパイスミックスを準備する",
        "すり鉢でハーブソルトを作る",
        "すりばち を かう",
        "やっきょく で くすり",
        "スパイス を する",
        "しょほうせん を もらう",
        "ハーブ を まぜる",
    ],
    fr=[
        "mortier",
        "pilon",
        "épice",
        "pharmacie",
        "broyer",
        "moudre",
        "mélanger",
        "ordonnance",
        "médicament",
        "herbe",
        "préparation",
        "remède",
        "mélange d'épices",
        "poivre",
        "composition",
        "apothicaire",
        "phytothérapie",
        "ustensile de cuisine",
        "moudre le cumin dans le mortier pour le curry",
        "écraser les grains de poivre pour le steak",
        "récupérer l'ordonnance à la pharmacie",
        "préparer un mélange d'épices pour la marinade",
        "préparer un remède à base de plantes dans le mortier",
        "renouveler l'ordonnance cette semaine",
        "moudre des bâtons de cannelle pour la recette",
        "acheter un mortier et pilon au magasin de cuisine",
        "écraser des flocons de piment séché pour la salsa",
        "mélanger la préparation en pharmacie pour la pommade",
        "moudre les gousses de cardamome pour le chai",
        "préparer la pâte d'épices avec le pilon",
        "vérifier les horaires de la pharmacie pour l'ordonnance",
        "écraser du gros sel dans le mortier",
        "faire de la poudre de curry avec des épices entières",
        "appeler la pharmacie pour la crème préparée",
        "moudre des graines de sésame pour le tahini",
        "préparer le mélange d'herbes pour le thé",
        "écraser l'ail et le gingembre pour le sauté",
        "moudre les clous de girofle pour l'épice à citrouille",
        "commander le renouvellement du médicament préparé",
        "écraser des amandes pour la garniture du dessert",
        "faire du garam masala maison dans le mortier",
        "broyer des épices fraîches dans le mortier",
        "préparer du thé aux herbes fraîchement pilées",
        "écraser les épices pour la soupe",
        "appeler la pharmacie pour le médicament",
        "préparer le mélange d'épices pour le barbecue",
        "faire du sel aux herbes dans le mortier",
        "morter et pilon à acheter",
        "épicess à moudre",
        "pharmcie ordonnance récupérer",
        "herbes mélangr",
        "poivr écraser dans le mortier",
    ],
    es=[
        "mortero",
        "maja",
        "especia",
        "farmacia",
        "triturar",
        "moler",
        "mezclar",
        "receta",
        "medicamento",
        "hierba",
        "preparación",
        "remedio",
        "mezcla de especias",
        "pimienta",
        "compuesto",
        "boticario",
        "herbolario",
        "utensilio de cocina",
        "moler comino en el mortero para el curry",
        "triturar granos de pimienta para el bistec",
        "recoger la receta en la farmacia",
        "hacer una mezcla de especias para el adobo",
        "preparar remedio herbal en el mortero",
        "renovar la receta esta semana",
        "moler palitos de canela para la receta",
        "comprar un mortero y maja en la tienda de cocina",
        "triturar hojuelas de chile seco para la salsa",
        "mezclar el compuesto de farmacia para el ungüento",
        "moler vainas de cardamomo para el chai",
        "preparar la pasta de especias con la maja",
        "revisar el horario de la farmacia para la receta",
        "triturar sal gruesa en el mortero",
        "hacer polvo de curry con especias enteras",
        "llamar a la farmacia por la crema compuesta",
        "moler semillas de sésamo para el tahini",
        "preparar la mezcla de hierbas para el té",
        "triturar ajo y jengibre para el salteado",
        "moler clavos para la especia de pastel de calabaza",
        "pedir la recarga del medicamento compuesto",
        "triturar almendras para el topping del postre",
        "hacer garam masala casero en el mortero",
        "moler especias frescas en el mortero",
        "preparar té de hierbas recién molidas",
        "triturar especias para la sopa",
        "llamar a la farmacia por el medicamento",
        "preparar mezcla de especias para la parrilla",
        "hacer sal de hierbas en el mortero",
        "mortreo y maja comprar",
        "especas moler",
        "farmcia receta recoger",
        "hierbas mesclr",
        "pimienta trituar en el mortero",
    ],
)

print("Part 2 done: moon, mortar-pestle")
