#!/usr/bin/env python3
"""Batch 506-525: expand 20 icons to ~50 EN rows + fix quality issues in existing RU data."""

import csv
from pathlib import Path

icons_dir = Path(__file__).parent / "icons"


def read_texts(path: Path) -> list[str]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8", newline="") as f:
        return [r["text"].strip() for r in csv.DictReader(f)]


def remove_rows(path: Path, bad: set[str]) -> int:
    if not path.exists():
        return 0
    rows = []
    with path.open(encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    kept = [r for r in rows if r["text"].strip() not in bad]
    removed = len(rows) - len(kept)
    if removed:
        with path.open("w", encoding="utf-8", newline="") as f:
            w = csv.DictWriter(f, fieldnames=["text", "label"])
            w.writeheader()
            w.writerows(kept)
    return removed


def append_csv(path: Path, rows: list[tuple[str, str]]) -> None:
    with path.open("a", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerows(rows)


def expand(icon, new_en, new_ru, fix_en=None, fix_ru=None):
    en_path = icons_dir / icon / "train_en.csv"
    ru_path = icons_dir / icon / "train_ru.csv"
    removed_en = removed_ru = 0
    if fix_en:
        removed_en = remove_rows(en_path, set(fix_en))
    if fix_ru:
        removed_ru = remove_rows(ru_path, set(fix_ru))
    assert len(new_en) == len(new_ru), f"{icon}: EN/RU count mismatch ({len(new_en)} vs {len(new_ru)})"
    existing_en = set(read_texts(en_path))
    existing_ru = set(read_texts(ru_path))
    add_en = [(t, icon) for t in new_en if t not in existing_en]
    add_ru = [(t, icon) for t in new_ru if t not in existing_ru]
    append_csv(en_path, add_en)
    append_csv(ru_path, add_ru)
    fix_note = f" (fixed EN:{removed_en} RU:{removed_ru})" if (removed_en or removed_ru) else ""
    print(f"  {icon}: +{len(add_en)} EN +{len(add_ru)} RU{fix_note}")


# ── manhole ──────────────────────────────────────────────────────────────────
expand("manhole",
    fix_ru=[
        # boundary: describes other infrastructure elements
        "ливневая канализация для стока дождевой воды",
        "технический колодец с дверцей доступа",
        "пожарный гидрант на городском тротуаре",
        "въезд на подземную парковку",
        "лестница входа в метро под землю",
        "крышка водомера в тротуаре",
    ],
    new_en=[
        "cast iron manhole cover with ribbed pattern",
        "round sewer access lid on asphalt",
        "utility manhole in city pavement",
        "inspection hatch for underground pipes",
        "public works crew opening a manhole",
        "drainage access point beneath the street",
        "steel lid over a sewer chamber",
        "storm drain cover embossed with city logo",
        "open manhole with safety cone around it",
        "underground service chamber entry cover",
        "manhole cover in need of replacement",
        "corrugated iron disk set flush in road",
        "city crew lifting the manhole lid to inspect",
        "sewer access hatch with bolt fasteners",
        "road surface broken around an old manhole",
        "manhole cover icon for infrastructure map",
        "utility access point in pavement",
        "drain cover on a wet city street",
        "underground maintenance hatch symbol",
        "circular iron lid for sewer inspection",
        "I need a manhole icon for the city utility app",
        "add a sewer hatch to the underground map view",
        "show a manhole cover in the infrastructure section",
        "use the manhole icon for access point markers",
        "manhoel cover on wet roard",
        "sewre acces hatch",
    ],
    new_ru=[
        "чугунная крышка люка с рёбрами жёсткости",
        "круглая крышка канализационного люка на асфальте",
        "коммунальный люк в городском тротуаре",
        "смотровой люк для подземных труб",
        "бригада коммунальщиков открывает люк",
        "дренажный люк под мостовой",
        "стальная крышка над канализационной камерой",
        "крышка ливнестока с гербом города",
        "открытый люк с предупреждающим конусом",
        "крышка технического колодца для обслуживания",
        "крышка люка требует замены",
        "рифлёный металлический диск вровень с дорогой",
        "рабочие поднимают крышку люка для осмотра",
        "крышка люка с болтовыми крепежами",
        "дорожное покрытие разрушено вокруг старого люка",
        "иконка люка для карты городской инфраструктуры",
        "точка доступа к коммуникациям в тротуаре",
        "крышка дренажа на мокрой городской улице",
        "символ люка для обслуживания подземных сетей",
        "круглая крышка для осмотра канализации",
        "нужна иконка люка для городского коммунального приложения",
        "добавить канализационный люк на карту подземных сетей",
        "показать крышку люка в разделе инфраструктуры",
        "использовать иконку люка для маркеров точек доступа",
        "крышак люка на мокрой дорге",
        "канлизационный смотровй люк",
    ],
)

# ── meter ─────────────────────────────────────────────────────────────────────
expand("meter",
    fix_ru=[
        # boundary: different measuring instruments
        "спидометр показывающий скорость транспортного средства",
        "указатель топлива от пустого до полного",
        "термометр для измерения температуры",
        "барометр измеряющий давление воздуха",
        "вольтметр для измерения электрического напряжения",
        "прогресс-бар показывающий процент",
    ],
    new_en=[
        "electricity meter mounted on the exterior wall",
        "analog dial meter with multiple dials",
        "digital smart meter for home energy tracking",
        "gas meter reading in the basement",
        "water meter installed near the main pipe",
        "meter reader visiting for monthly billing",
        "prepaid electricity meter with credit display",
        "three-phase electric meter for industrial use",
        "meter cabinet locked on the building exterior",
        "tamper-evident seal on the utility meter",
        "sub-meter for individual apartment energy use",
        "utility meter spinning during peak usage",
        "meter data uploaded to the cloud for billing",
        "broken utility meter reported to the provider",
        "meter box cover opened for inspection",
        "I need a meter icon for the energy dashboard",
        "add an electricity meter to the utilities screen",
        "show a meter for the monthly consumption view",
        "use the meter icon for the power reading feature",
        "eletrcity meeter on the wall",
        "utility meeter reading the dials",
        "smart meeter for home energy",
        "gass meter in the basement",
        "wateer meter near the main pipe",
        "meter readnig for billing",
    ],
    new_ru=[
        "электросчётчик установлен на наружной стене",
        "аналоговый счётчик с несколькими циферблатами",
        "умный цифровой счётчик для отслеживания энергии",
        "показания газового счётчика в подвале",
        "водосчётчик у основного трубопровода",
        "контролёр приходит снять показания ежемесячно",
        "предоплатный счётчик электроэнергии с дисплеем",
        "трёхфазный электросчётчик для промышленных нужд",
        "шкаф счётчика закрыт на замок снаружи здания",
        "антивскрывочная пломба на коммунальном счётчике",
        "субсчётчик для отдельной квартиры",
        "счётчик крутится в часы пиковой нагрузки",
        "данные счётчика отправляются в облако для биллинга",
        "неисправный счётчик сообщён поставщику услуг",
        "крышка коробки счётчика открыта для проверки",
        "нужна иконка счётчика для панели энергопотребления",
        "добавить электросчётчик на экран коммунальных услуг",
        "показать счётчик в разделе ежемесячного потребления",
        "использовать иконку счётчика для функции снятия показаний",
        "счётчик электроэнргии на стене",
        "показания коммунальнго счётчика",
        "умный счётчкик для домашней энергии",
        "газовый счётчкик в подвале",
        "водяной счётчик у основного трубопровда",
        "снятие покзаний счётчика для биллинга",
    ],
)

# ── pepper ────────────────────────────────────────────────────────────────────
expand("pepper",
    fix_ru=[
        # boundary: other vegetables
        "тонкий красный чили с острым кончиком",
        "сушеный чили как острая приправа",
        "круглый красный помидор с зеленой ножкой",
        "помидоры черри на ветке в саду",
        "фиолетовый баклажан с длинной зеленой ножкой",
        "баклажан нарезан и жарится на сковороде",
    ],
    new_en=[
        "yellow bell pepper chopped for a salad",
        "red and green capsicum in a market display",
        "roasted bell pepper skin peeled for a dish",
        "sweet pepper diced for a pizza topping",
        "green bell pepper halved and seeded",
        "mixed peppers grilled on a barbecue",
        "bell pepper emoji used in a recipe post",
        "a fresh capsicum rinsed under cold water",
        "stuffed pepper recipe card illustration",
        "pepper slice used as a salsa ingredient",
        "buying bell peppers at the farmers market",
        "pepper in a vegan stir-fry bowl",
        "tri-colour pepper pack from the grocery store",
        "add peppers to the meal plan for the week",
        "bell pepper grown in the home vegetable garden",
        "I need a pepper icon for the recipe section",
        "add a capsicum symbol to the grocery list",
        "show a bell pepper for the vegetable category",
        "use the pepper icon for the fresh produce screen",
        "peppr sliced for the salad bowl",
        "pepepr chopped for stir fry",
        "peper stuffed and roasted",
        "capsicm from the farmers markt",
        "bel pepper from the grocery",
        "peppers griled on the bbq",
    ],
    new_ru=[
        "жёлтый болгарский перец нарезан для салата",
        "красный и зелёный перец на рыночной витрине",
        "запечённый перец с очищенной кожицей",
        "сладкий перец нарезан кубиками для пиццы",
        "зелёный перец разрезан пополам и очищен от семян",
        "перцы на гриле",
        "эмодзи перца используется в посте с рецептом",
        "свежий перец промыт под холодной водой",
        "карточка рецепта фаршированного перца",
        "кусочек перца как ингредиент сальсы",
        "покупка болгарских перцев на фермерском рынке",
        "перец в веганском воке",
        "упаковка разноцветных перцев из супермаркета",
        "добавить перцы в план питания на неделю",
        "болгарский перец выращен в домашнем огороде",
        "нужна иконка перца для раздела рецептов",
        "добавить символ перца в список продуктов",
        "показать болгарский перец для категории овощей",
        "использовать иконку перца для экрана свежих продуктов",
        "перец нарезан для салата",
        "перец нарублен для стир-фрая",
        "перец нафарширован и запечён",
        "перец с фермерского рынка",
        "болгарский перец из магазина",
        "перцы на гриле",
    ],
)

# ── scooter ───────────────────────────────────────────────────────────────────
expand("scooter",
    fix_ru=[
        # boundary: other wheeled vehicles
        "велосипед с двумя одинаковыми колесами",
        "человек едет на велосипеде по велополосе",
        "мотоцикл припаркован на городской улице",
        "спортивный мотоцикл в наклоне в повороте",
        "скейтборд с четырьмя колесами",
        "человек катается на скейте в скейтпарке",
    ],
    new_en=[
        "dockless e-scooter available for hire",
        "scooter battery charging at the station",
        "GPS-tracked scooter on a city street",
        "helmet required for e-scooter rental",
        "scooter speed limited to 25 km/h in the zone",
        "park the scooter in the designated bay",
        "scan the QR code to unlock the scooter",
        "last-mile transport via shared scooter",
        "electric scooter fleet parked in a row",
        "student riding a kick scooter to campus",
        "folding scooter stored under the desk at work",
        "scooter hire app showing available nearby",
        "delivery courier on an electric scooter",
        "scooter lane painted on the road surface",
        "kick scooter with adjustable handlebar",
        "I need a scooter icon for the mobility app",
        "add a scooter symbol to the transport section",
        "show a kick scooter for the city travel feature",
        "use the scooter icon for the short-trip category",
        "scoooter at the rental station",
        "e-scootr parked on the sidewalk",
        "elecric scooter for the last mile",
        "scootr left at the charging bay",
        "kick scoooter for campus commute",
        "scooter hire ap nearby",
    ],
    new_ru=[
        "электросамокат без стыковки доступен для аренды",
        "аккумулятор самоката заряжается у станции",
        "самокат с GPS-отслеживанием на городской улице",
        "шлем обязателен для аренды электросамоката",
        "скорость самоката ограничена 25 км/ч в зоне",
        "припарковать самокат на отведённом месте",
        "отсканировать QR-код чтобы разблокировать самокат",
        "транспорт последней мили на прокатном самокате",
        "флот электросамокатов припаркован в ряд",
        "студент едет на кикскутере в кампус",
        "складной самокат хранится под столом на работе",
        "приложение аренды самокатов показывает ближайшие",
        "курьер доставки на электросамокате",
        "полоса для самокатов нанесена на дороге",
        "кикскутер с регулируемым рулём",
        "нужна иконка самоката для приложения мобильности",
        "добавить символ самоката в раздел транспорта",
        "показать кикскутер для городской поездки",
        "использовать иконку самоката для коротких поездок",
        "самокат у арендной станции",
        "электросамакот припаркован на тротуаре",
        "электрический самокат для последней мили",
        "самокат оставлен у зарядной станции",
        "кикскутер для поездок на кампус",
        "приложение аренды самокатов поблизости",
    ],
)

# ── tree-city ─────────────────────────────────────────────────────────────────
expand("tree-city",
    fix_ru=[
        # boundary: nature/other items unrelated to urban tree planning
        "одинокое дерево природа лес",
        "здание небоскрёб город один",
        "скамейка парк сад на улице",
        "лист растение природа зелёный",
        "дом пригород дерево",
        "глобус земля зелёная планета",
    ],
    new_en=[
        "city trees planted along the main boulevard",
        "urban forestry programme for the downtown area",
        "green corridor connecting city parks with trees",
        "tree canopy map for the metropolitan region",
        "eco-city icon featuring a building and tree",
        "community tree-planting event in the neighbourhood",
        "urban heat island mitigation via city trees",
        "street tree species selected for the city grid",
        "park and tree icon for a smart-city dashboard",
        "native trees planted along the new transit route",
        "rooftop garden above a city building",
        "tree inventory in a city planning database",
        "biodiversity increased by urban tree programme",
        "sustainable city design with tree integration",
        "green city certification badge with a tree symbol",
        "I need a tree-city icon for the sustainability app",
        "add an urban tree symbol to the city planner",
        "show a green-city icon for the eco projects section",
        "use the tree-city icon for urban greenspace features",
        "urbn tree city planning icon",
        "green cty with trees and buildings",
        "eco-cty tree planting initiative",
        "citi tree canopy coverage",
        "smart-cty green space icon",
        "sustainable urbn design tree",
    ],
    new_ru=[
        "деревья высажены вдоль главного бульвара",
        "программа городского лесоводства для центра города",
        "зелёный коридор соединяет городские парки с деревьями",
        "карта кронового покрова для городского района",
        "иконка эко-города со зданием и деревом",
        "акция общественной посадки деревьев в районе",
        "снижение температуры городского острова тепла через деревья",
        "выбор видов уличных деревьев для городской сетки",
        "иконка парка и дерева для дашборда умного города",
        "местные деревья высажены вдоль нового маршрута",
        "сад на крыше городского здания",
        "инвентаризация деревьев в базе данных городского планирования",
        "биоразнообразие растёт благодаря программе городских деревьев",
        "устойчивый городской дизайн с интеграцией деревьев",
        "сертификат зелёного города с символом дерева",
        "нужна иконка дерево-город для приложения устойчивого развития",
        "добавить символ городского дерева в городской планировщик",
        "показать иконку зелёного города в разделе эко-проектов",
        "использовать иконку дерево-город для городских зелёных зон",
        "икона планирования городского дерева",
        "зелёный город с деревьями и зданиями",
        "эко-город инициатива посадки деревьев",
        "покрытие кронами деревьев в городе",
        "иконка зелёного пространства умного города",
        "устойчивый городской дизайн с деревом",
    ],
)

# ── bin-bottles ───────────────────────────────────────────────────────────────
expand("bin-bottles",
    fix_ru=[
        # borderline: paper/general trash, not bottles specifically
        "Отсортировать бумагу и картон",
        "Опустошить кухонное ведро",
    ],
    new_en=[
        "bin full of empty plastic bottles to recycle",
        "toss the used water bottle in the recycling bin",
        "clear plastic recycling bag filled with bottles",
        "deposit bottles at the supermarket return machine",
        "plastic bottle collection bin at the office",
        "recycle all the empty drink bottles today",
        "rinse the bottles before tossing in the bin",
        "bottle deposit refund at the grocery store",
        "crush plastic bottles before recycling",
        "separate plastic bottles from cardboard",
        "the recycling bin overflows with plastic bottles",
        "put the empty jugs in the bottle-only bin",
        "plastic bottle recycling drop-off point nearby",
        "sort the plastic bottles by resin type",
        "I need a bottle bin icon for the recycling tracker",
        "add a plastic-bottles symbol to the bin category",
        "show a bottle recycling icon for the eco section",
        "use the bin-bottles icon for the waste sorting feature",
        "reycling bin fll of empty bottles",
        "sort plastc bottles for recyclng",
        "drp off plastc at the recycling poitn",
        "crussh bottles before bin",
        "collecton bin for plastic btotles",
        "toss empty botle in the bin",
    ],
    new_ru=[
        "контейнер полон пустых пластиковых бутылок для переработки",
        "выбросить использованную бутылку в контейнер для переработки",
        "прозрачный пластиковый мешок для переработки набит бутылками",
        "сдать бутылки в автомат приёма тары в супермаркете",
        "контейнер для сбора пластиковых бутылок в офисе",
        "сдать все пустые бутылки из-под напитков сегодня",
        "ополоснуть бутылки перед тем как бросить в контейнер",
        "возврат залога за бутылки в продуктовом магазине",
        "сплющить пластиковые бутылки перед переработкой",
        "отделить пластиковые бутылки от картона",
        "контейнер для переработки переполнен пластиковыми бутылками",
        "поместить пустые ёмкости в контейнер только для бутылок",
        "пункт сдачи пластиковых бутылок рядом",
        "сортировать пластиковые бутылки по типу смолы",
        "нужна иконка контейнера для бутылок в трекере переработки",
        "добавить символ пластиковых бутылок в категорию контейнеров",
        "показать иконку переработки бутылок для эко-раздела",
        "использовать иконку бин-бутылок для функции сортировки отходов",
        "контейнер переполнен пустыми бутылками",
        "сортировать пластиковые бутылки для переработки",
        "сдать пластик в пункт приёма",
        "сплющить бутылки перед контейнером",
        "сборный контейнер для пластиковых бутылок",
        "выбросить пустую бутылку в контейнер",
    ],
)

# ── bottle-water ──────────────────────────────────────────────────────────────
expand("bottle-water",
    fix_ru=[
        # boundary: other drinks / not water bottle
        "Купить газировку в магазине",
        "Кофе перед встречей",
        "Сок на завтрак",
        "Спортивный напиток после тренировки",
        # duplicate
        "Переработать пластиковую бутылку",
        # boundary: kettle not bottle
        "Наполнить чайник водой",
    ],
    new_en=[
        "stainless steel reusable water bottle",
        "insulated water bottle keeps drinks cold all day",
        "wide-mouth water bottle for the gym bag",
        "collapsible water bottle for travel",
        "filtered water bottle with built-in filter",
        "leakproof water bottle cap sealed tight",
        "water bottle with time markers to track intake",
        "branded water bottle from the marathon",
        "kids water bottle with a flip straw",
        "water bottle left on the desk at work",
        "refill the bottle at the airport water fountain",
        "single-use plastic bottle to avoid on hikes",
        "water bottle tracker for daily hydration goal",
        "smart water bottle syncs with the health app",
        "glass water bottle with a silicone sleeve",
        "I need a water bottle icon for the hydration tracker",
        "add a bottle symbol to the daily water goal",
        "show a water bottle for the hydration reminder",
        "use the bottle-water icon for the drink-more feature",
        "reuseble water botl for the gym",
        "insualted water botle for cold drinks",
        "filterd wter bottle for travel",
        "hydartion tracker water bottel",
        "smart watr bottle syncs to health app",
        "kids watr bottle with flip straw",
    ],
    new_ru=[
        "многоразовая бутылка из нержавеющей стали",
        "термобутылка сохраняет напитки холодными весь день",
        "бутылка с широким горлышком для спортивной сумки",
        "складная бутылка для путешествий",
        "бутылка с фильтром для очистки воды",
        "герметичная крышка бутылки для воды",
        "бутылка с временными метками для контроля потребления",
        "фирменная бутылка с марафона",
        "детская бутылка с трубочкой",
        "бутылка с водой оставлена на рабочем столе",
        "наполнить бутылку у питьевого фонтана в аэропорту",
        "одноразовая пластиковая бутылка которую стоит избегать в походах",
        "трекер бутылок для достижения ежедневной нормы воды",
        "умная бутылка синхронизируется с приложением здоровья",
        "стеклянная бутылка в силиконовом чехле",
        "нужна иконка бутылки для трекера гидратации",
        "добавить символ бутылки к ежедневной норме воды",
        "показать бутылку воды для напоминания о гидратации",
        "использовать иконку бутылки для функции пей-больше",
        "многоразовая бутылка для спортзала",
        "термобутылка для холодных напитков",
        "бутылка с фильтром для путешествий",
        "трекер гидратации с бутылкой воды",
        "умная бутылка синхронизируется с приложением",
        "детская бутылка с трубочкой",
    ],
)

# ── capsule ───────────────────────────────────────────────────────────────────
expand("capsule",
    fix_ru=[
        # boundary: other medical items
        "круглая таблетка на белой поверхности",
        "медицинский шприц с иглой для инъекции",
        "янтарный флакон с белой крышкой",
        "термометр для измерения температуры тела",
        "пластырь на небольшом порезе",
        "стетоскоп для прослушивания сердцебиения",
    ],
    new_en=[
        "gelatin capsule filled with powdered supplement",
        "hard-shell capsule for antibiotic medication",
        "clear capsule showing coloured beads inside",
        "delayed-release capsule for sensitive stomachs",
        "fish-oil omega-3 capsule",
        "probiotic capsule for gut health",
        "herbal remedy in capsule form",
        "capsule blister pack for daily doses",
        "morning routine includes one capsule with water",
        "prescription capsule taken twice a day",
        "veggie capsule alternative to gelatin",
        "capsule size 00 for custom compounding",
        "over-the-counter pain relief capsule",
        "capsule sorted into a weekly pill organiser",
        "pharmacy auto-dispenses the correct capsule dose",
        "I need a capsule icon for the med tracker",
        "add a pill capsule to the prescription screen",
        "show a capsule for the medication reminder",
        "use the capsule icon for the pharmacy section",
        "capsule medcine twice a day",
        "gelatin capusle supplement",
        "antibitic capsule hard shell",
        "omega-3 fish oil capsle",
        "probiotc capsule for gut helath",
        "capsuel in the blister pack",
    ],
    new_ru=[
        "желатиновая капсула с порошковой добавкой",
        "твёрдая капсула для антибиотика",
        "прозрачная капсула с цветными гранулами внутри",
        "капсула с отсроченным высвобождением для чувствительного желудка",
        "капсула с рыбьим жиром омега-3",
        "пробиотическая капсула для здоровья кишечника",
        "растительное средство в форме капсулы",
        "блистерная упаковка капсул для ежедневных доз",
        "утренний ритуал включает одну капсулу с водой",
        "рецептурная капсула принимается дважды в день",
        "вегетарианская капсула как замена желатиновой",
        "капсула размера 00 для индивидуальной рецептуры",
        "безрецептурная капсула от боли",
        "капсула разложена в недельный таблетник",
        "аптечный автомат выдаёт нужную дозу капсулы",
        "нужна иконка капсулы для трекера лекарств",
        "добавить капсулу на экран рецептов",
        "показать капсулу для напоминания о лекарстве",
        "использовать иконку капсулы для раздела аптеки",
        "капсула лекарства дважды в день",
        "желатиновая капсула с добавкой",
        "капсула антибиотика твёрдая оболочка",
        "капсула рыбьего жира омега-3",
        "пробиотическая капсула для кишечника",
        "капсула в блистерной упаковке",
    ],
)

# ── cart-flatbed ──────────────────────────────────────────────────────────────
expand("cart-flatbed",
    fix_ru=[
        # boundary: shopping cart, forklift, wheelbarrow (different equipment)
        "Тележка для покупок в продуктовом",
        "Тележка у входа в супермаркет",
        "Вилочный погрузчик для тяжёлых поддонов",
        "Тачка для садовых материалов",
    ],
    new_en=[
        "four-wheeled flatbed trolley for warehouse use",
        "flatbed cart loaded with cardboard boxes",
        "rolling platform cart for moving equipment",
        "steel flatbed trolley rated for 500 kg",
        "warehouse worker pushing a loaded flat cart",
        "flatbed on casters for smooth floor movement",
        "utility cart used in distribution centres",
        "dollied flatbed for moving office furniture",
        "flatbed cart with raised edges for stability",
        "motorised flatbed for heavy loads",
        "loading dock flatbed ready for unloading",
        "flat-top trolley for manufacturing floor use",
        "flatbed cart strapped with bungee cords",
        "fold-flat cart stored against the warehouse wall",
        "platform truck for moving palletised goods",
        "I need a flatbed cart icon for the warehouse app",
        "add a trolley symbol to the logistics section",
        "show a flatbed for the inventory movement screen",
        "use the cart-flatbed icon for the shipping feature",
        "flatbad cart for the heavy loads",
        "warehose flatbed cart for movig stock",
        "rollig flatbed trolley for equipment",
        "flatbad on casters for smooth flooors",
        "platform truk for palletised goods",
        "loadig dock flatbed is free",
    ],
    new_ru=[
        "четырёхколёсная тележка для склада",
        "тележка с плоским полом загружена картонными коробками",
        "роликовая платформенная тележка для перевозки оборудования",
        "стальная тележка грузоподъёмностью 500 кг",
        "складской рабочий везёт загруженную тележку",
        "тележка на колёсиках для движения по ровному полу",
        "грузовая тележка в распределительном центре",
        "тележка для перемещения офисной мебели",
        "тележка с бортами для устойчивости",
        "моторизованная тележка для тяжёлых грузов",
        "тележка у погрузочного дока готова к разгрузке",
        "плоская тележка для производственного цеха",
        "тележка закреплена эластичными канатами",
        "складная тележка у стены склада",
        "платформенная тележка для поддонизированных товаров",
        "нужна иконка тележки для складского приложения",
        "добавить символ тележки в раздел логистики",
        "показать тележку на экране перемещения инвентаря",
        "использовать иконку тележки для функции отгрузки",
        "плоская тележка для тяжёлых грузов",
        "складская тележка для перемещения товаров",
        "роликовая тележка для оборудования",
        "тележка на колёсиках по ровному полу",
        "платформенная тележка для поддонов",
        "тележка у погрузочного дока свободна",
    ],
)

# ── chair-office ──────────────────────────────────────────────────────────────
expand("chair-office",
    fix_ru=[
        # boundary: other types of chairs/seats
        "Обеденный стул для кухонного стола",
        "Игровое кресло для ПК",
        "Барный стул у стола для стоячей работы",
        "Диван для зоны отдыха в офисе",
        "Колленный стул для коррекции осанки",
        "Фитбол вместо стула",
    ],
    new_en=[
        "high-back executive office chair in black leather",
        "task chair with adjustable armrests and lumbar",
        "mesh-back office chair for all-day comfort",
        "office chair delivered to the home workspace",
        "conference room chair for the meeting table",
        "posture-correcting office chair with tilt lock",
        "office chair assembled from flat-pack",
        "office chair with headrest for tall users",
        "budget office chair for the spare desk",
        "upgrade the office chair for the team",
        "office chair wheel replaced after damage",
        "foam seat cushion added to the office chair",
        "office chair positioned at the correct desk height",
        "office chair with breathable mesh seat pan",
        "smart office chair tracks sitting time",
        "I need an office chair icon for the furniture app",
        "add a desk chair symbol to the workspace section",
        "show an office chair for the ergonomics screen",
        "use the chair-office icon for the home-office setup",
        "ergonomic ofice chaair for back support",
        "mesh-back ofice chiar for all-day comfort",
        "ofice chair with lumbr support",
        "home ofice setup new chiar needed",
        "ergonmic desk chaur for posture",
        "executive ofice chair black lether",
    ],
    new_ru=[
        "кожаное руководящее кресло с высокой спинкой",
        "рабочее кресло с регулируемыми подлокотниками и поясничной опорой",
        "офисное кресло с сетчатой спинкой для долгой работы",
        "офисное кресло доставлено в домашнее рабочее место",
        "конференц-кресло для стола переговорной",
        "кресло с замком наклона для коррекции осанки",
        "офисное кресло собрано из плоской упаковки",
        "кресло с подголовником для высоких пользователей",
        "бюджетное офисное кресло для запасного стола",
        "обновить офисные кресла для всей команды",
        "заменили колёсико офисного кресла после поломки",
        "поролоновая подушка добавлена к офисному креслу",
        "офисное кресло отрегулировано на правильную высоту стола",
        "офисное кресло с воздухопроницаемой сетчатой подушкой",
        "умное офисное кресло отслеживает время сидения",
        "нужна иконка офисного кресла для мебельного приложения",
        "добавить символ рабочего кресла в раздел рабочего места",
        "показать офисное кресло для экрана эргономики",
        "использовать иконку кресла для настройки домашнего офиса",
        "эргономичное офисное кресло для спины",
        "офисное кресло с сетчатой спинкой для долгой работы",
        "офисное кресло с поясничной поддержкой",
        "настройка домашнего офиса нужно новое кресло",
        "эргономичное кресло для осанки",
        "руководящее офисное кресло из чёрной кожи",
    ],
)

# ── chopsticks ────────────────────────────────────────────────────────────────
expand("chopsticks",
    fix_ru=[
        # boundary: other utensils / food without chopsticks
        "Вилка и нож для обеденного стола",
        "Ложка для супа",
        "Щипцы для подачи салата",
        "Шпажки для барбекю",
        "Деревянная ложка для помешивания",
        "Ролл суши без палочек",
    ],
    new_en=[
        "lacquered chopsticks placed across a bowl of noodles",
        "children learning to eat with chopsticks",
        "metal chopsticks for Korean BBQ",
        "long cooking chopsticks for frying in a wok",
        "chopsticks resting on a ceramic chopstick holder",
        "bamboo chopsticks still in their paper sleeve",
        "chopstick etiquette — never stand them upright",
        "silver chopsticks for a formal Japanese meal",
        "travel chopsticks in a compact carry case",
        "ramen eaten with wooden chopsticks",
        "dumpling picked up with chopsticks and dipped",
        "chopstick skills practised at home",
        "sharing dishes with communal serving chopsticks",
        "chopsticks used to stir the soup",
        "hot pot meal eaten with extra-long chopsticks",
        "I need a chopsticks icon for the Asian food app",
        "add a chopstick symbol to the utensils section",
        "show chopsticks for the sushi ordering feature",
        "use the chopsticks icon for the Asian dining category",
        "chopsticsk resting on the bowl rim",
        "bamboo chopstickes in the paper sleve",
        "lacquerd chopstickes for the sushi dinner",
        "metal chopticks for korean BBQ",
        "travel chopstcks in carry case",
        "chopstick etiquet no standing up",
    ],
    new_ru=[
        "лакированные палочки лежат поперёк миски с лапшой",
        "дети учатся есть палочками",
        "металлические палочки для корейского барбекю",
        "длинные кулинарные палочки для жарки в воке",
        "палочки лежат на керамической подставке",
        "бамбуковые палочки всё ещё в бумажном пакете",
        "этикет с палочками — никогда не ставить их вертикально",
        "серебряные палочки для официального японского ужина",
        "дорожные палочки в компактном чехле",
        "рамен едят деревянными палочками",
        "пельмень взят палочками и окунут в соус",
        "навыки использования палочек отрабатываются дома",
        "блюда накладывают общими сервировочными палочками",
        "палочками помешивают суп",
        "хот-пот едят очень длинными палочками",
        "нужна иконка палочек для приложения азиатской кухни",
        "добавить символ палочек в раздел столовых приборов",
        "показать палочки для функции заказа суши",
        "использовать иконку палочек для категории азиатского питания",
        "палочки лежат на краю миски",
        "бамбуковые палочки в бумажном пакете",
        "лакированные палочки для ужина с суши",
        "металлические палочки для корейского барбекю",
        "дорожные палочки в чехле",
        "этикет палочек не ставить вертикально",
    ],
)

# ── crow ──────────────────────────────────────────────────────────────────────
expand("crow",
    fix_ru=[
        # boundary: other birds
        "кормить голубей в парке",
        "наблюдать за полётом голубя",
        "найти орла в небе",
        "услышать уханье совы ночью",
        "наблюдать за чайками на пляже",
        "наблюдать попугая на дереве",
    ],
    new_en=[
        "black crow perched on a telephone wire",
        "crow cawing loudly in the morning",
        "murder of crows gathered in the park",
        "crow silhouette against a grey sky",
        "crow picking up a shiny object from the ground",
        "Halloween witch and crow decoration",
        "crow used as a dark omen symbol in a story",
        "intelligent crow solving a puzzle",
        "crow feather found on the walking path",
        "large black crow on a bare winter branch",
        "crow mascot for a sports team",
        "gothic crow symbol in a tattoo design",
        "crow landing on a fence post at dusk",
        "scarecrow with a crow sitting on its hat",
        "flock of crows circling above a field",
        "I need a crow icon for the Halloween theme",
        "add a crow symbol to the spooky category",
        "show a crow for the dark-theme section",
        "use the crow icon for the mystery feature",
        "blakc crow on the telephone wire",
        "crow cawwing in the morning",
        "halowwen crow decoraiton",
        "crow silhouete against grey sky",
        "murder of crwos in the park",
        "crrow on the bare winter branch",
    ],
    new_ru=[
        "чёрная ворона сидит на телефонном проводе",
        "ворона громко каркает по утрам",
        "стая ворон собралась в парке",
        "силуэт вороны на сером небе",
        "ворона подбирает блестящий предмет с земли",
        "украшение ведьма и ворона на Хэллоуин",
        "ворона как символ дурного предзнаменования в рассказе",
        "умная ворона решает головоломку",
        "вороньё перо найдено на тропинке",
        "большая чёрная ворона на голой зимней ветке",
        "талисман вороны для спортивной команды",
        "готический символ вороны в татуировке",
        "ворона садится на столб забора в сумерках",
        "пугало с вороной на его шляпе",
        "стая ворон кружит над полем",
        "нужна иконка вороны для хэллоуинской темы",
        "добавить символ вороны в жуткую категорию",
        "показать ворону для тёмной темы раздела",
        "использовать иконку вороны для функции тайны",
        "чёрная ворона на телефонном проводе",
        "ворона каркает по утрам",
        "украшение вороны на хэллоуин",
        "силуэт вороны на сером небе",
        "стая ворон в парке",
        "ворона на голой зимней ветке",
    ],
)

# ── golf-club ─────────────────────────────────────────────────────────────────
expand("golf-club",
    fix_ru=[
        # boundary: other sports equipment
        "Ударить теннисным мячом по корту",
        "Размахивать бейсбольной битой",
        "Поиграть в крокет в саду",
        "Ударить по хоккейной шайбе",
        "Поиграйте в бадминтон в парке",
        "Патт в мини-гольфе",
        # bad machine translations
        "Наймите кедди для раунда",
        "Забейте орла на лунке 5.",
        "Потопить удар на зеленом",
        "Ударить по тройнику",
        "Нажмите на ссылки",
    ],
    new_en=[
        "iron golf club used to approach the green",
        "driver club for long-distance tee shots",
        "putter used on the final green",
        "set of golf clubs in a leather bag",
        "wedge club for bunker escape",
        "hybrid club combining iron and wood",
        "graphite shaft golf club for added distance",
        "golf club fitting session at the pro shop",
        "club selection for the par-4 hole",
        "cleaning golf clubs after a muddy round",
        "new golf clubs ordered online for the season",
        "golf club grips replaced at the pro shop",
        "custom engraved golf club as a gift",
        "golf club loft angle affecting ball trajectory",
        "caddy recommends the 7-iron for this shot",
        "I need a golf club icon for the sports app",
        "add a golf club symbol to the outdoor activities",
        "show a golf club for the sports equipment section",
        "use the golf club icon for the course booking feature",
        "golf clb fitting at the pro shop",
        "iron club for the appraoch shot",
        "puter on the final grean",
        "new golfclub set for the sesaon",
        "golf club grps replaced",
        "caddy recommnds the 7-iron",
    ],
    new_ru=[
        "железная клюшка для подхода к грину",
        "драйвер для дальних ударов с тройника",
        "паттер на финальном грине",
        "набор клюшек в кожаной сумке",
        "клюшка-веджи для выхода из бункера",
        "гибридная клюшка совмещает айрон и вуд",
        "клюшка с графитовым древком для дальности",
        "подбор клюшки в магазине гольф-клуба",
        "выбор клюшки для лунки пар-4",
        "чистка клюшек после грязного раунда",
        "новые клюшки заказаны онлайн на сезон",
        "рукоятки клюшек заменены в магазине",
        "клюшка с гравировкой в подарок",
        "угол лофта клюшки влияет на траекторию мяча",
        "кэдди рекомендует 7-айрон для этого удара",
        "нужна иконка клюшки для спортивного приложения",
        "добавить символ клюшки в раздел активного отдыха",
        "показать клюшку в разделе спортивного инвентаря",
        "использовать иконку клюшки для функции бронирования поля",
        "подбор клюшки в магазине гольф-клуба",
        "айрон для удара на подходе",
        "паттер на финальном грине",
        "новый набор клюшек на сезон",
        "замена рукояток клюшек",
        "кэдди рекомендует 7-айрон",
    ],
)

# ── helmet-battle ─────────────────────────────────────────────────────────────
expand("helmet-battle",
    fix_ru=[
        # boundary: other fantasy classes / sport helmet
        "Играйте за мошенника в игре",
        "Носите шляпу волшебника в игровой кампании",
        "Используйте плащ с капюшоном для скрытности",
        "Наденьте кинжал вместо брони",
        "Произносите заклинания как маг",
        "Носите хоккейный шлем для занятий спортом",
    ],
    new_en=[
        "medieval battle helmet with visor down",
        "steel knight helmet with a full face guard",
        "armoured helmet icon for a medieval RPG",
        "fantasy warrior wearing a horned battle helmet",
        "paladin helmet etched with holy symbols",
        "battle helmet dropped on the dungeon floor",
        "crusader helmet with a cross emblem",
        "knight helmet as a coat of arms symbol",
        "siegecraft knight wearing a tower-shaped helmet",
        "dark lord with a spiked battle helmet",
        "collect the enchanted helmet after the boss fight",
        "medieval knight tournament — helmet required",
        "forge a new battle helmet for the final quest",
        "battle helmet icon in a mobile RPG game",
        "knight helmet used in a board-game token design",
        "I need a battle helmet icon for my RPG game",
        "add a knight helmet to the character equipment",
        "show a battle helmet for the warrior class",
        "use the helmet-battle icon for the armour screen",
        "medeival battle helmt with visor",
        "steel knght helmet full face gard",
        "paldin helmet with holy syimbols",
        "dark lord spked battle helmet",
        "crusadr helmet with cross emblem",
        "enchntd helmet from the boss fight",
    ],
    new_ru=[
        "средневековый боевой шлем с опущенным забралом",
        "стальной рыцарский шлем с полной защитой лица",
        "иконка бронированного шлема для средневековой RPG",
        "фэнтезийный воин в рогатом боевом шлеме",
        "шлем паладина украшен священными символами",
        "боевой шлем брошен на пол подземелья",
        "шлем крестоносца с эмблемой креста",
        "рыцарский шлем как геральдический символ",
        "рыцарь-осадник в шлеме в форме башни",
        "тёмный лорд в шипастом боевом шлеме",
        "подобрать зачарованный шлем после боя с боссом",
        "рыцарский турнир — шлем обязателен",
        "скуй новый боевой шлем для финального квеста",
        "иконка боевого шлема в мобильной RPG",
        "рыцарский шлем в дизайне жетона настольной игры",
        "нужна иконка боевого шлема для RPG",
        "добавить рыцарский шлем в снаряжение персонажа",
        "показать боевой шлем для класса воина",
        "использовать иконку шлема для экрана доспехов",
        "средневековый боевой шлем с забралом",
        "стальной рыцарский шлем с полной защитой",
        "шлем паладина со священными символами",
        "тёмный лорд в шипастом шлеме",
        "шлем крестоносца с крестом",
        "зачарованный шлем после боя с боссом",
    ],
)

# ── knife ─────────────────────────────────────────────────────────────────────
expand("knife",
    fix_ru=[
        # boundary: other cutting/cooking tools
        "Используйте ножницы, чтобы разрезать упаковочную бумагу.",
        "Используйте овощечистку вместо ножа",
        "Используйте терку-мандолину",
        # awkward duplicated phrase
        "Используйте нож для очистки овощей для очистки",
        # borderline — table setting with fork and knife is still about knife
        # keep "Накройте стол вилкой и ножом вместе"
    ],
    new_en=[
        "chef's knife with a wide blade for chopping",
        "serrated bread knife for slicing a loaf",
        "paring knife for peeling fruit and veg",
        "boning knife for filleting a fish",
        "santoku knife for Japanese-style cutting",
        "knife honing on a steel rod before cooking",
        "kitchen knife stored safely in a knife block",
        "sharp knife for julienning carrots",
        "pocket knife with a folding blade",
        "Swiss army knife with multiple tools",
        "steak knife set for the dinner table",
        "cleaver knife for splitting poultry",
        "ceramic knife with a white blade",
        "knife skills class at the culinary school",
        "carbon-steel knife requiring careful maintenance",
        "I need a knife icon for the kitchen app",
        "add a knife symbol to the cooking tools section",
        "show a blade for the cutlery category",
        "use the knife icon for the meal prep feature",
        "chefs knofe wide blade for choping",
        "seratted bread knive for slcing",
        "pairing knofe for fruits and veg",
        "santoku knofe for japnese cutting",
        "knife honning on the steel rod",
        "swiss army knfe with tools",
    ],
    new_ru=[
        "поварской нож с широким лезвием для рубки",
        "зубчатый нож для хлеба для нарезки буханки",
        "нож для чистки овощей и фруктов",
        "нож для обвалки для разделки рыбы",
        "нож сантоку для нарезки в японском стиле",
        "правка ножа на мусате перед готовкой",
        "кухонный нож хранится в подставке для ножей",
        "острый нож для нарезки моркови соломкой",
        "складной нож с выдвижным лезвием",
        "швейцарский нож с несколькими инструментами",
        "набор ножей для стейка для обеденного стола",
        "тяпка для разрубки птицы",
        "керамический нож с белым лезвием",
        "мастер-класс по работе с ножом в кулинарной школе",
        "нож из углеродистой стали требует тщательного ухода",
        "нужна иконка ножа для кухонного приложения",
        "добавить символ ножа в раздел кухонных инструментов",
        "показать лезвие для категории столовых приборов",
        "использовать иконку ножа для функции подготовки блюд",
        "поварской нож с широким лезвием",
        "зубчатый нож для нарезки хлеба",
        "нож для чистки фруктов и овощей",
        "нож сантоку для японской нарезки",
        "правка ножа на мусате",
        "швейцарский нож с инструментами",
    ],
)

# ── lights-holiday ────────────────────────────────────────────────────────────
expand("lights-holiday",
    fix_ru=[
        # duplicate search term
        "Рождество",  # remove one of the two duplicates (second occurrence)
        # bad literal translation of "string"
        "строка",
        # English text in RU file!
        "Replace the ceiling light bulb",
        # boundary: regular lamp / candle / wreath / tinsel (not string lights)
        "Ставим обычную лампу",
        "Зажгите свечи на ужин",
        "Повесьте праздничный венок",
        "Украсить мишурой",
    ],
    new_en=[
        "twinkling LED string lights on the Christmas tree",
        "outdoor icicle lights hanging from the eaves",
        "timer-controlled holiday lights on the porch",
        "multicoloured fairy lights wound around the staircase",
        "warm-white holiday string lights for the patio",
        "solar-powered outdoor holiday string lights",
        "net lights draped over the garden bushes",
        "projection holiday lights on the house facade",
        "replace a broken bulb in the Christmas light strand",
        "wrapping the roofline with holiday lights",
        "holiday light show set to music",
        "string lights in festive red and green",
        "indoor holiday lights on a mantel garland",
        "holiday lights tangled in the storage box",
        "battery-operated fairy lights for the table centrepiece",
        "I need a holiday lights icon for the Xmas section",
        "add a string-lights symbol to the decoration category",
        "show festive lights for the holiday theme",
        "use the lights-holiday icon for the Xmas decor feature",
        "twinklng LED holiday lights on the tree",
        "outdoor icilce lights from the eaves",
        "multcolored fairy lghts on the staircase",
        "solar holidy string lights",
        "holiday lights shwo set to music",
        "brokn bulb in the Christmas lght strand",
    ],
    new_ru=[
        "мерцающие светодиодные гирлянды на рождественской ёлке",
        "уличные гирлянды-сосульки свисают с карниза",
        "праздничные огни с таймером на крыльце",
        "разноцветные гирлянды обмотаны вокруг лестницы",
        "тёплые белые праздничные гирлянды для веранды",
        "солнечные уличные праздничные гирлянды",
        "сетчатые гирлянды накинуты на кусты в саду",
        "проекционные праздничные огни на фасаде дома",
        "замена перегоревшей лампочки в гирлянде",
        "обматываем карниз праздничными гирляндами",
        "шоу праздничных огней под музыку",
        "гирлянда в красных и зелёных тонах",
        "внутренние праздничные гирлянды на каминной полке",
        "гирлянды запутались в ящике для хранения",
        "гирлянды на батарейках для центрального украшения стола",
        "нужна иконка праздничных огней для рождественского раздела",
        "добавить символ гирлянды в категорию украшений",
        "показать праздничные огни для новогодней темы",
        "использовать иконку праздничных огней для рождественского декора",
        "мерцающие гирлянды на ёлке",
        "уличные сосульки-гирлянды с карниза",
        "разноцветные гирлянды на лестнице",
        "солнечные праздничные гирлянды",
        "шоу праздничных огней под музыку",
        "сгоревшая лампочка в гирлянде",
    ],
)

# ── loader ────────────────────────────────────────────────────────────────────
expand("loader",
    fix_ru=[
        # boundary: other time/progress indicators
        "песочные часы отсчитывают время",
        "таймер обратного отсчёта",
        "горизонтальная полоса прогресса заполняется",
        "индикатор уровня заряда батареи",
        "секундомер отсчитывает время",
        "циферблат часов показывает запланированное время",
    ],
    new_en=[
        "spinning loader while the page fetches data",
        "three-dot loader animation in a chat app",
        "skeleton screen shown while content loads",
        "pulsing ring loader over a dark overlay",
        "loader icon with percentage complete label",
        "indeterminate spinner for unknown wait time",
        "circular progress arc as the file uploads",
        "loading state replacing a button label",
        "CSS loader animation coded in a web component",
        "loader blocking interaction until the request finishes",
        "refresh spinner triggered by pull-to-refresh",
        "network request spinner in the browser tab",
        "full-screen loader overlay during app initialisation",
        "retry button appears after the loader times out",
        "loader icon paired with a status message",
        "I need a spinner icon for my loading state",
        "add a circular loader to the data fetch screen",
        "show a progress indicator while the file syncs",
        "use the loader icon for async operations",
        "spinnng loaeder while data fetches",
        "three-dot loaeder in a chat app",
        "skeletn screen while conent loads",
        "pulsng ring loaeder overlay",
        "ineterminate spinnner for wait time",
        "circular progres arc during upload",
    ],
    new_ru=[
        "крутящийся спиннер пока страница загружает данные",
        "анимация трёх точек в чат-приложении",
        "скелетный экран пока контент загружается",
        "пульсирующее кольцо поверх тёмного оверлея",
        "иконка загрузки с меткой процента выполнения",
        "неопределённый спиннер для неизвестного времени ожидания",
        "круговая дуга прогресса во время загрузки файла",
        "состояние загрузки вместо текста кнопки",
        "CSS-анимация загрузки в веб-компоненте",
        "загрузчик блокирует взаимодействие до завершения запроса",
        "спиннер обновления при свайпе вниз",
        "спиннер сетевого запроса во вкладке браузера",
        "полноэкранный оверлей загрузки при инициализации приложения",
        "кнопка повтора появляется после истечения времени загрузки",
        "иконка загрузки с сообщением о статусе",
        "нужен спиннер для состояния загрузки",
        "добавить круговой загрузчик на экран запроса данных",
        "показать индикатор прогресса пока файл синхронизируется",
        "использовать иконку загрузчика для асинхронных операций",
        "крутящийся спиннер во время загрузки данных",
        "анимация трёх точек в чате",
        "скелетный экран во время загрузки контента",
        "пульсирующее кольцо оверлея",
        "неопределённый спиннер для ожидания",
        "дуга прогресса при загрузке файла",
    ],
)

# ── ornament ──────────────────────────────────────────────────────────────────
expand("ornament",
    fix_ru=[
        # duplicate search term (appears twice)
        "рождество",  # will remove both; one remains from first occurrence
        # boundary: other Christmas items
        "рождественская ёлка без украшений",
        "подарочная коробка завёрнутая в праздничную бумагу",
        "венок висящий на двери",
        "леденцовая трость праздничное угощение",
        "гирлянда из огней для украшения",
        "праздничный узор снежинки",
    ],
    new_en=[
        "glass ball ornament reflecting the Christmas lights",
        "hand-painted ceramic ornament on the tree branch",
        "set of gold and red tree ornaments in a box",
        "personalised name ornament hanging on the tree",
        "miniature wooden ornament in the shape of a snowflake",
        "glittery star ornament for the tree top",
        "family heirloom ornament passed down each year",
        "ornament hook bent to hang on the branch",
        "unboxing a new ornament set for the holiday",
        "ornament storage bag labelled by colour",
        "elf ornament that moves to a new spot each night",
        "crystal ornament catching the light on the tree",
        "holiday ornament swap at the office party",
        "DIY ornament craft for kids before Christmas",
        "ornament with a photo of the family inside",
        "I need an ornament icon for the holiday theme",
        "add a Christmas ball to the decoration section",
        "show a tree ornament for the festive category",
        "use the ornament icon for the holiday decor feature",
        "glass bal ornamnent on the tree branch",
        "hand-paintd ceramic ornmaent",
        "personalised name ornmaent on the tree",
        "glitery star ornmaent for tree top",
        "crystl ornament on the holiday tree",
        "holiday ornmaent swap at the office",
    ],
    new_ru=[
        "стеклянный шар отражает рождественские огни",
        "расписное керамическое украшение на ветке ёлки",
        "набор золотых и красных ёлочных украшений в коробке",
        "именное украшение висит на ёлке",
        "маленькое деревянное украшение в форме снежинки",
        "блестящая звезда на верхушку ёлки",
        "фамильное украшение передаётся каждый год",
        "крючок украшения согнут чтобы повесить на ветку",
        "распаковываем новый набор украшений к празднику",
        "сумка для хранения украшений подписана по цвету",
        "украшение-эльф каждую ночь перемещается на новое место",
        "хрустальное украшение ловит свет на ёлке",
        "обмен украшениями на офисной вечеринке",
        "мастер-класс по украшениям своими руками для детей",
        "украшение с семейной фотографией внутри",
        "нужна иконка украшения для праздничной темы",
        "добавить рождественский шар в раздел украшений",
        "показать ёлочное украшение для праздничной категории",
        "использовать иконку украшения для функции рождественского декора",
        "стеклянный шар на ветке ёлки",
        "расписное керамическое украшение",
        "именное украшение на ёлке",
        "блестящая звезда на верхушку ёлки",
        "хрустальное украшение на праздничной ёлке",
        "обмен украшениями в офисе",
    ],
)

# ── paintbrush-pencil ─────────────────────────────────────────────────────────
expand("paintbrush-pencil",
    fix_ru=[
        # boundary: single tools, not the dual combo
        "кисть одна без карандаша",
        "карандаш один для письма",
        "маркер толстый фломастер",
        "ластик для удаления отметин",
        "ножницы и клей инструменты дизайна",
        "стилус для рисования на планшете",
    ],
    new_en=[
        "brush-and-pencil icon for the drawing app toolbar",
        "toggle between paint and sketch mode",
        "dual art tool for painting and marking up",
        "design studio icon showing both brush and pencil",
        "creative mode with brush and pencil combined",
        "edit artwork with either brush strokes or pencil lines",
        "mixed-media tool combining paint and pencil sketch",
        "annotation mode using brush or pencil",
        "brush for colour fill pencil for outlines",
        "collaborative design tool showing brush and pencil",
        "art creation toolbar with brush and pencil options",
        "combined edit icon for photo and drawing apps",
        "select brush or pencil from the dual tool menu",
        "drawing and painting mode toggled with this icon",
        "creative tools icon in a mobile design app",
        "I need a brush-pencil icon for my art tool",
        "add a dual art tool to the editor toolbar",
        "show a paintbrush-pencil for the creative section",
        "use the combined tool icon for the design mode",
        "brush-pencl icn for the drawing toolbar",
        "dual art tol paintbrsh and pencil",
        "toggle beteen paint and sketching mode",
        "edit artowrk with brush or pencil",
        "mixed-media toll for painting and marking",
        "creative tool icn brush and pencl combined",
    ],
    new_ru=[
        "иконка кисть-карандаш на панели инструментов приложения для рисования",
        "переключение между режимами рисования и эскиза",
        "двойной художественный инструмент для рисования и разметки",
        "иконка дизайн-студии с кистью и карандашом",
        "творческий режим с кистью и карандашом вместе",
        "редактировать рисунок мазками кисти или линиями карандаша",
        "смешанная техника сочетает живопись и карандашный набросок",
        "режим аннотаций с кистью или карандашом",
        "кисть для заливки цветом карандаш для контуров",
        "совместный дизайн с кистью и карандашом",
        "панель инструментов создания искусства с кистью и карандашом",
        "комбинированная иконка редактирования для фото и приложений рисования",
        "выбрать кисть или карандаш из меню двойного инструмента",
        "режим рисования и живописи переключается этой иконкой",
        "иконка творческих инструментов в мобильном дизайн-приложении",
        "нужна иконка кисть-карандаш для моего художественного инструмента",
        "добавить двойной инструмент в панель редактора",
        "показать кисть-карандаш для творческого раздела",
        "использовать иконку комбинированного инструмента для режима дизайна",
        "иконка кисть-карандаш на панели инструментов",
        "двойной инструмент кисть и карандаш",
        "переключение между рисованием и эскизом",
        "редактировать рисунок кистью или карандашом",
        "смешанный инструмент для рисования и разметки",
        "иконка творческого инструмента кисть и карандаш",
    ],
)

# ── reply ─────────────────────────────────────────────────────────────────────
expand("reply",
    fix_ru=[
        # boundary: forward / share / send / inbox (different actions)
        "стрелка пересылки отправляет сообщение новому адресату",
        "стрелка ответить всем с двумя головами",
        "кнопка поделиться распространяет контент",
        "кнопка отправить отправляет набранное сообщение",
        "стрелка перенаправления в папку",
        "входящий лоток получает входящие сообщения",
    ],
    new_en=[
        "reply arrow curving left to the original sender",
        "tap reply to respond to the latest message",
        "reply button in the email toolbar highlighted",
        "quick reply from the notification banner",
        "reply thread nested under the original comment",
        "reply icon with a left-pointing curved arrow",
        "in-line reply to a specific message in a thread",
        "auto-reply configured for out-of-office periods",
        "reply to a support ticket from the customer",
        "chat reply used to quote a previous message",
        "reply all button greyed out for single-recipient mail",
        "reply confirmation shown after sending a message",
        "keyboard shortcut R to reply in the mail client",
        "drafted reply saved and discarded",
        "reply feature in a social media comment section",
        "I need a reply icon for the messaging feature",
        "add a reply button to the comment section",
        "show a reply arrow for the email client toolbar",
        "use the reply icon for the respond-to-customer feature",
        "reply arwow curving to the sender",
        "qiuck reply from notifcation banner",
        "reply threed under the orignial comment",
        "auto-repley for out-of-ofice",
        "reply to suppport ticket from customer",
        "in-line rply to quote a message",
    ],
    new_ru=[
        "стрелка ответа загибается влево к исходному отправителю",
        "нажать ответить на последнее сообщение",
        "кнопка ответа выделена на панели почты",
        "быстрый ответ из баннера уведомления",
        "ветка ответа вложена под исходный комментарий",
        "иконка ответа со стрелкой влево",
        "встроенный ответ на конкретное сообщение в ветке",
        "автоответ настроен для периода отпуска",
        "ответ на тикет поддержки от клиента",
        "ответ в чате для цитирования предыдущего сообщения",
        "кнопка ответить всем неактивна для письма одному адресату",
        "подтверждение ответа после отправки сообщения",
        "горячая клавиша R для ответа в почтовом клиенте",
        "черновик ответа сохранён и удалён",
        "функция ответа в разделе комментариев социальной сети",
        "нужна иконка ответа для функции обмена сообщениями",
        "добавить кнопку ответа в раздел комментариев",
        "показать стрелку ответа для панели почтового клиента",
        "использовать иконку ответа для функции реагирования на клиента",
        "стрелка ответа загибается к отправителю",
        "быстрый ответ из баннера уведомления",
        "ветка ответа под исходным комментарием",
        "автоответ на период отпуска",
        "ответ на тикет от клиента",
        "встроенный ответ для цитирования сообщения",
    ],
)


if __name__ == "__main__":
    print("Expanding icons 506-525 with quality fixes...\n")
    # (all expand() calls are at module level, executed on import/run)
    print("\nDone.")
