#!/usr/bin/env python3
"""Task-005 part 4: rabbit, raccoon, radiation"""
from gen_icons_task_005_common import gen

# ── rabbit ────────────────────────────────────────────────────────────────────
gen("rabbit",
en=[
    "rabbit",
    "bunny",
    "hare",
    "Easter bunny",
    "pet rabbit",
    "rabbit hutch",
    "spring",
    "animal",
    "mammal",
    "fauna",
    "cottontail",
    "rabbit ears",
    "bunny rabbit",
    "jackrabbit",
    "rabbit food",
    "rabbit cage",
    "wild rabbit",
    "lop-eared rabbit",
    "feed the rabbit its pellets in the morning",
    "clean out the rabbit hutch this weekend",
    "buy hay for the pet rabbit",
    "take the rabbit to the vet for a checkup",
    "the rabbit escaped from the cage again",
    "build a bigger hutch for the new rabbit",
    "buy Easter bunny decorations for the house",
    "hide Easter eggs for the kids from the Easter bunny",
    "the wild rabbits are eating the garden vegetables",
    "put a fence around the garden to keep rabbits out",
    "adopt a rescue rabbit from the shelter",
    "bring the rabbit inside when it gets cold",
    "buy rabbit treats at the pet store",
    "the rabbit needs its nails trimmed",
    "let the rabbit run around the backyard for exercise",
    "get a water bottle for the rabbit cage",
    "brush the rabbit's fur to prevent matting",
    "find a rabbit sitter for the vacation",
    "the rabbit chewed through the phone charger cord",
    "buy bedding for the rabbit hutch",
    "schedule the rabbit's vaccination appointment",
    "the kids want to hold the baby bunnies",
    "look for a rabbit-friendly vet in the area",
    "give the rabbit fresh vegetables as a treat",
    "the rabbit is thumping its feet at night",
    "buy a harness to walk the rabbit outside",
    "check if the rabbit has enough water",
    "the neighbor's rabbit had baby bunnies",
    "research the best diet for a pet rabbit",
    "rabbit-proof the living room before letting it out",
    "the Easter bunny chocolate is on sale",
    "buy a new toy for the rabbit to play with",
    "need to get rabbit pellets from the store",
    "rabit hutch needs cleaning",
    "buny treats from pet store",
    "Eater bunny decorations",
    "rabibt escaped the cage",
    "rabitt food and hay",
],
ru=[
    "кролик",
    "зайчик",
    "заяц",
    "пасхальный кролик",
    "домашний кролик",
    "кроличья клетка",
    "весна",
    "животное",
    "млекопитающее",
    "фауна",
    "дикий кролик",
    "кроличьи уши",
    "крольчонок",
    "заяц-русак",
    "корм для кролика",
    "клетка для кролика",
    "лесной заяц",
    "вислоухий кролик",
    "покормить кролика гранулами утром",
    "почистить кроличью клетку в эти выходные",
    "купить сено для домашнего кролика",
    "отвезти кролика к ветеринару на осмотр",
    "кролик опять сбежал из клетки",
    "построить клетку побольше для нового кролика",
    "купить украшения с пасхальным кроликом для дома",
    "спрятать пасхальные яйца для детей от зайчика",
    "дикие кролики едят овощи в саду",
    "поставить забор вокруг сада от кроликов",
    "взять кролика из приюта",
    "занести кролика в дом когда похолодает",
    "купить лакомства для кролика в зоомагазине",
    "кролику нужно подстричь когти",
    "дать кролику побегать по двору для разминки",
    "купить поилку для кроличьей клетки",
    "расчесать шерсть кролика чтобы не свалялась",
    "найти того кто посмотрит за кроликом на отпуск",
    "кролик перегрыз шнур зарядки телефона",
    "купить подстилку для кроличьей клетки",
    "записать кролика на прививку",
    "дети хотят подержать крольчат",
    "найти ветеринара для кроликов в округе",
    "дать кролику свежие овощи как лакомство",
    "кролик стучит лапами по ночам",
    "купить шлейку чтобы гулять с кроликом на улице",
    "проверить хватает ли кролику воды",
    "у соседского кролика родились крольчата",
    "изучить лучшую диету для домашнего кролика",
    "обезопасить гостиную перед тем как выпустить кролика",
    "шоколадные пасхальные кролики на распродаже",
    "купить новую игрушку для кролика",
    "надо купить гранулы для кролика в магазине",
    "кроличя клетка нуждается в уборке",
    "лакомтва для кролика из зоомагазина",
    "пасхальый кролик украшения",
    "кролк сбежал из клетки",
    "корм и сено для крлоика",
],
de=[
    "Kaninchen",
    "Häschen",
    "Hase",
    "Osterhase",
    "Hauskaninchen",
    "Kaninchenstall",
    "Frühling",
    "Tier",
    "Säugetier",
    "Fauna",
    "Wildkaninchen",
    "Hasenohren",
    "Kaninchenbaby",
    "Feldhase",
    "Kaninchenfutter",
    "Kaninchenkäfig",
    "Waldhase",
    "Widderkaninchen",
    "das Kaninchen morgens mit Pellets füttern",
    "den Kaninchenstall am Wochenende sauber machen",
    "Heu für das Hauskaninchen kaufen",
    "das Kaninchen zum Tierarzt zur Kontrolle bringen",
    "das Kaninchen ist wieder aus dem Käfig entwischt",
    "einen größeren Stall für das neue Kaninchen bauen",
    "Osterhasen-Dekoration fürs Haus kaufen",
    "Ostereier für die Kinder vom Osterhasen verstecken",
    "die wilden Kaninchen fressen das Gemüse im Garten",
    "einen Zaun um den Garten setzen gegen Kaninchen",
    "ein Kaninchen aus dem Tierheim adoptieren",
    "das Kaninchen bei Kälte ins Haus holen",
    "Leckerlis für das Kaninchen im Zooladen kaufen",
    "dem Kaninchen müssen die Krallen geschnitten werden",
    "das Kaninchen im Garten laufen lassen zur Bewegung",
    "eine Trinkflasche für den Kaninchenkäfig besorgen",
    "das Kaninchenfell bürsten damit es nicht verfilzt",
    "einen Kaninchensitter für den Urlaub finden",
    "das Kaninchen hat das Ladekabel durchgenagt",
    "Einstreu für den Kaninchenstall kaufen",
    "den Impftermin fürs Kaninchen vereinbaren",
    "die Kinder wollen die Kaninchenbabys halten",
    "einen kaninchenfreundlichen Tierarzt in der Nähe suchen",
    "dem Kaninchen frisches Gemüse als Leckerli geben",
    "das Kaninchen klopft nachts mit den Pfoten",
    "ein Geschirr kaufen um mit dem Kaninchen draußen spazieren zu gehen",
    "prüfen ob das Kaninchen genug Wasser hat",
    "das Kaninchen der Nachbarn hat Nachwuchs bekommen",
    "die beste Ernährung für ein Hauskaninchen recherchieren",
    "das Wohnzimmer kaninchensicher machen bevor es rausgelassen wird",
    "die Osterhasen-Schokolade ist im Angebot",
    "ein neues Spielzeug für das Kaninchen kaufen",
    "muss Kaninchenpellets im Laden kaufen",
    "Kanichen-Stall muss sauber gemacht werden",
    "Leckrlis für Kaninchen aus dem Zooladen",
    "Osterahse Dekoration",
    "Kanichen ist aus dem Käfig entwischt",
    "Kanichenfutter und Heu",
],
ja=[
    "うさぎ",
    "バニー",
    "野うさぎ",
    "イースターバニー",
    "ペットのうさぎ",
    "うさぎ小屋",
    "春",
    "動物",
    "哺乳類",
    "動物相",
    "ワタオウサギ",
    "うさぎの耳",
    "子うさぎ",
    "ジャックラビット",
    "うさぎのエサ",
    "うさぎのケージ",
    "野生のうさぎ",
    "ロップイヤーのうさぎ",
    "朝にうさぎにペレットをあげる",
    "今週末うさぎ小屋を掃除する",
    "ペットのうさぎ用に干し草を買う",
    "健康診断のためにうさぎを動物病院に連れて行く",
    "うさぎがまたケージから逃げ出した",
    "新しいうさぎのために大きな小屋を作る",
    "家にイースターバニーの飾りを買う",
    "子供たちのためにイースターエッグを隠す",
    "野生のうさぎが庭の野菜を食べている",
    "うさぎが入らないように庭にフェンスを設置する",
    "保護施設からうさぎを引き取る",
    "寒くなったらうさぎを室内に入れる",
    "ペットショップでうさぎのおやつを買う",
    "うさぎの爪を切る必要がある",
    "運動のためにうさぎを庭で走らせる",
    "うさぎのケージ用に給水ボトルを買う",
    "毛玉防止のためにうさぎの毛をブラッシングする",
    "休暇中のうさぎの世話を頼める人を探す",
    "うさぎがスマホの充電ケーブルをかじった",
    "うさぎ小屋用の敷材を買う",
    "うさぎのワクチン予約をする",
    "子供たちが赤ちゃんうさぎを抱きたがっている",
    "近くにうさぎに詳しい動物病院を探す",
    "おやつとして新鮮な野菜をうさぎにあげる",
    "うさぎが夜中に足を踏み鳴らしている",
    "うさぎを外で散歩させるためのハーネスを買う",
    "うさぎの水が足りているか確認する",
    "お隣のうさぎに赤ちゃんが生まれた",
    "ペットうさぎのベストな食事を調べる",
    "うさぎを出す前にリビングをうさぎ対策する",
    "イースターのチョコうさぎがセール中",
    "うさぎの新しいおもちゃを買う",
    "お店でうさぎのペレットを買ってこないと",
    "うさぎごやの掃除が必要",
    "うさぎのおかし買う",
    "イースタばにーの飾り",
    "うさぎがけーじから逃げた",
    "うさぎのえさと干し草",
],
fr=[
    "lapin",
    "lapinou",
    "lièvre",
    "lapin de Pâques",
    "lapin domestique",
    "clapier",
    "printemps",
    "animal",
    "mammifère",
    "faune",
    "lapin de garenne",
    "oreilles de lapin",
    "bébé lapin",
    "lièvre des champs",
    "nourriture pour lapin",
    "cage à lapin",
    "lapin sauvage",
    "lapin bélier",
    "donner les granulés au lapin le matin",
    "nettoyer le clapier ce week-end",
    "acheter du foin pour le lapin domestique",
    "emmener le lapin chez le vétérinaire pour un bilan",
    "le lapin s'est encore échappé de la cage",
    "construire un clapier plus grand pour le nouveau lapin",
    "acheter des décorations de lapin de Pâques pour la maison",
    "cacher les œufs de Pâques pour les enfants",
    "les lapins sauvages mangent les légumes du jardin",
    "mettre une clôture autour du jardin contre les lapins",
    "adopter un lapin au refuge",
    "rentrer le lapin quand il fait froid",
    "acheter des friandises pour le lapin à l'animalerie",
    "il faut couper les griffes du lapin",
    "laisser le lapin courir dans le jardin pour l'exercice",
    "acheter un biberon pour la cage du lapin",
    "brosser le pelage du lapin pour éviter les nœuds",
    "trouver quelqu'un pour garder le lapin pendant les vacances",
    "le lapin a rongé le câble du chargeur de téléphone",
    "acheter de la litière pour le clapier",
    "prendre rendez-vous pour la vaccination du lapin",
    "les enfants veulent tenir les bébés lapins",
    "chercher un vétérinaire spécialisé lapins dans le coin",
    "donner des légumes frais au lapin en friandise",
    "le lapin tape des pattes la nuit",
    "acheter un harnais pour promener le lapin dehors",
    "vérifier si le lapin a assez d'eau",
    "le lapin du voisin a eu des bébés",
    "se renseigner sur le meilleur régime pour un lapin domestique",
    "sécuriser le salon avant de laisser sortir le lapin",
    "le chocolat lapin de Pâques est en promo",
    "acheter un nouveau jouet pour le lapin",
    "il faut aller chercher des granulés pour le lapin",
    "claiper du lapin à nettoyer",
    "frianidses pour le lapin de l'animalerie",
    "lapin de Pâqeus décoration",
    "le lapni s'est échappé de la cage",
    "nourrtiure et foin pour le lapin",
],
es=[
    "conejo",
    "conejito",
    "liebre",
    "conejo de Pascua",
    "conejo mascota",
    "conejera",
    "primavera",
    "animal",
    "mamífero",
    "fauna",
    "conejo de cola blanca",
    "orejas de conejo",
    "conejito bebé",
    "liebre de campo",
    "alimento para conejo",
    "jaula para conejo",
    "conejo silvestre",
    "conejo de orejas caídas",
    "darle los pellets al conejo en la mañana",
    "limpiar la conejera este fin de semana",
    "comprar heno para el conejo mascota",
    "llevar al conejo al veterinario para un chequeo",
    "el conejo se escapó de la jaula otra vez",
    "construir una conejera más grande para el conejo nuevo",
    "comprar decoraciones de conejo de Pascua para la casa",
    "esconder huevos de Pascua para los niños",
    "los conejos silvestres se están comiendo las verduras del jardín",
    "poner una cerca en el jardín para que no entren los conejos",
    "adoptar un conejo del refugio de animales",
    "meter al conejo adentro cuando haga frío",
    "comprar golosinas para el conejo en la tienda de mascotas",
    "hay que cortarle las uñas al conejo",
    "dejar que el conejo corra en el patio para ejercitarse",
    "comprar un bebedero para la jaula del conejo",
    "cepillar el pelaje del conejo para que no se enrede",
    "encontrar a alguien que cuide al conejo durante las vacaciones",
    "el conejo mordió el cable del cargador del teléfono",
    "comprar cama para la conejera",
    "agendar la cita de vacunación del conejo",
    "los niños quieren cargar a los conejitos bebé",
    "buscar un veterinario especialista en conejos en la zona",
    "darle verduras frescas al conejo como premio",
    "el conejo golpea con las patas por las noches",
    "comprar un arnés para pasear al conejo afuera",
    "revisar si el conejo tiene suficiente agua",
    "el conejo del vecino tuvo conejitos",
    "investigar la mejor dieta para un conejo mascota",
    "hacer la sala a prueba de conejos antes de soltarlo",
    "el chocolate de conejo de Pascua está en oferta",
    "comprar un juguete nuevo para el conejo",
    "necesito comprar pellets para el conejo en la tienda",
    "coenjera del conejo necesita limpieza",
    "golosnias para conejo de la tienda",
    "decoraciones de coejo de Pascua",
    "el conjo se escapó de la jaula",
    "alimneto y heno para el conejo",
])


# ── raccoon ───────────────────────────────────────────────────────────────────
gen("raccoon",
en=[
    "raccoon",
    "trash panda",
    "pest",
    "wildlife",
    "nocturnal",
    "bandit",
    "critter",
    "animal",
    "mammal",
    "fauna",
    "raccoon mask",
    "raccoon tracks",
    "garbage raccoon",
    "urban wildlife",
    "raccoon repellent",
    "raccoon trap",
    "raccoon damage",
    "backyard raccoon",
    "the raccoon got into the trash again last night",
    "buy a raccoon-proof garbage can lid",
    "call pest control about the raccoon in the attic",
    "the raccoon tipped over the compost bin",
    "secure the trash cans before the raccoons come",
    "check the attic for raccoon damage",
    "the raccoon left muddy paw prints on the porch",
    "set up a motion-sensor light to scare off raccoons",
    "find a raccoon removal service in the area",
    "the raccoons are digging up the lawn at night",
    "buy raccoon repellent for the garden",
    "repair the fence hole where the raccoon gets in",
    "the raccoon made a nest under the deck",
    "clean up after the raccoon knocked over the bins",
    "call animal control about the raccoon in the yard",
    "the raccoon keeps coming back every night",
    "check if the raccoon got into the chicken coop",
    "put a lock on the garbage can to stop the raccoons",
    "the raccoon ate all the cat food on the porch",
    "get a live trap to relocate the raccoon",
    "the raccoon damaged the roof shingles getting in",
    "seal the crawl space to prevent raccoon entry",
    "the baby raccoons are living under the shed",
    "report the aggressive raccoon to animal services",
    "raccoon-proof the bird feeders in the backyard",
    "the raccoon scratched up the screen door",
    "check for raccoon tracks in the garden",
    "the noise in the chimney might be a raccoon",
    "need to block the raccoon from getting to the fish pond",
    "the raccoon tore open the garbage bag",
    "hire someone to remove the raccoon from the attic",
    "install chicken wire to keep raccoons out of the garden",
    "the raccoon is too bold around people lately",
    "racocon got into the trash",
    "racoon in the atic",
    "racccoon proof garbage lid",
    "racoon repellant for garden",
    "racccon tracks on the porch",
],
ru=[
    "енот",
    "мусорная панда",
    "вредитель",
    "дикая природа",
    "ночной",
    "бандит",
    "зверёк",
    "животное",
    "млекопитающее",
    "фауна",
    "маска енота",
    "следы енота",
    "енот у мусорки",
    "городская фауна",
    "средство от енотов",
    "ловушка для енота",
    "повреждения от енота",
    "енот во дворе",
    "енот опять залез в мусорку прошлой ночью",
    "купить крышку для мусорного бака от енотов",
    "вызвать службу дезинсекции из-за енота на чердаке",
    "енот опрокинул компостный бак",
    "закрепить мусорные баки до прихода енотов",
    "проверить чердак на повреждения от енота",
    "енот оставил грязные следы лап на крыльце",
    "установить датчик движения с фонарём для отпугивания енотов",
    "найти службу по отлову енотов в округе",
    "еноты раскапывают газон по ночам",
    "купить средство от енотов для сада",
    "починить дыру в заборе куда пролезает енот",
    "енот свил гнездо под террасой",
    "убрать за енотом который опрокинул баки",
    "позвонить в службу контроля животных по поводу енота во дворе",
    "енот возвращается каждую ночь",
    "проверить не залез ли енот в курятник",
    "повесить замок на мусорный бак от енотов",
    "енот съел весь кошачий корм на крыльце",
    "купить живоловку чтобы переселить енота",
    "енот повредил черепицу пробираясь на крышу",
    "заделать подпол чтобы енот не пролез",
    "маленькие еноты живут под сараем",
    "сообщить об агрессивном еноте в службу контроля",
    "защитить кормушки для птиц от енотов во дворе",
    "енот поцарапал сетку на двери",
    "проверить следы енота в саду",
    "шум в дымоходе может быть от енота",
    "нужно не дать еноту добраться до рыбного пруда",
    "енот разорвал мусорный пакет",
    "нанять кого-то для удаления енота с чердака",
    "установить сетку чтобы не пускать енотов в сад",
    "енот в последнее время слишком смелый около людей",
    "енто залез в мусорку",
    "енот на чердке",
    "крышка мусорного бака от еноотв",
    "средтво от енотов для сада",
    "слдеы енота на крыльце",
],
de=[
    "Waschbär",
    "Müllpanda",
    "Schädling",
    "Wildtier",
    "nachtaktiv",
    "Bandit",
    "Tier",
    "Säugetier",
    "Fauna",
    "Waschbär-Maske",
    "Waschbärspuren",
    "Müll-Waschbär",
    "städtische Wildtiere",
    "Waschbärabwehr",
    "Waschbärfalle",
    "Waschbärschaden",
    "Waschbär im Garten",
    "Wildtierkontrolle",
    "der Waschbär war letzte Nacht wieder im Müll",
    "einen waschbärsicheren Mülleimer-Deckel kaufen",
    "Schädlingsbekämpfung wegen dem Waschbär auf dem Dachboden rufen",
    "der Waschbär hat den Komposteimer umgeworfen",
    "die Mülltonnen sichern bevor die Waschbären kommen",
    "den Dachboden auf Waschbärschäden prüfen",
    "der Waschbär hat schlammige Pfotenabdrücke auf der Veranda hinterlassen",
    "einen Bewegungsmelder mit Licht gegen Waschbären installieren",
    "einen Waschbär-Entfernungsservice in der Gegend finden",
    "die Waschbären graben nachts den Rasen um",
    "Waschbärabwehrmittel für den Garten kaufen",
    "das Loch im Zaun reparieren wo der Waschbär reinkommt",
    "der Waschbär hat ein Nest unter der Terrasse gebaut",
    "aufräumen nachdem der Waschbär die Tonnen umgeworfen hat",
    "die Tierkontrolle wegen des Waschbären im Garten anrufen",
    "der Waschbär kommt jede Nacht wieder",
    "prüfen ob der Waschbär in den Hühnerstall gekommen ist",
    "ein Schloss an die Mülltonne machen gegen Waschbären",
    "der Waschbär hat das ganze Katzenfutter auf der Veranda gefressen",
    "eine Lebendfalle kaufen um den Waschbären umzusiedeln",
    "der Waschbär hat die Dachschindeln beschädigt",
    "den Kriechkeller abdichten gegen Waschbären",
    "die Waschbärbabys leben unter dem Schuppen",
    "den aggressiven Waschbär beim Tieramt melden",
    "die Vogelfutterhäuschen im Garten waschbärsicher machen",
    "der Waschbär hat die Fliegengittertür zerkratzt",
    "nach Waschbärspuren im Garten schauen",
    "das Geräusch im Kamin könnte ein Waschbär sein",
    "muss den Waschbären vom Fischteich fernhalten",
    "der Waschbär hat den Müllsack aufgerissen",
    "jemanden beauftragen den Waschbären vom Dachboden zu holen",
    "Maschendraht installieren um Waschbären aus dem Garten fernzuhalten",
    "der Waschbär wird in letzter Zeit zu dreist",
    "Waschbr war im Müll",
    "Waschbär auf dem Dachboen",
    "waschbärsichere Mülltonnedeckel",
    "Waschbärabwher für den Garten",
    "Waschbärspren auf der Veranda",
],
ja=[
    "アライグマ",
    "ゴミパンダ",
    "害獣",
    "野生動物",
    "夜行性",
    "バンディット",
    "動物",
    "哺乳類",
    "動物相",
    "アライグマの模様",
    "アライグマの足跡",
    "ゴミを漁るアライグマ",
    "都市の野生動物",
    "アライグマ忌避剤",
    "アライグマの罠",
    "アライグマの被害",
    "裏庭のアライグマ",
    "害獣駆除",
    "昨夜またアライグマがゴミを漁った",
    "アライグマ対策のゴミ箱の蓋を買う",
    "屋根裏のアライグマについて害獣駆除に電話する",
    "アライグマがコンポスト箱をひっくり返した",
    "アライグマが来る前にゴミ箱を固定する",
    "屋根裏にアライグマの被害がないか確認する",
    "アライグマが玄関に泥の足跡を残した",
    "アライグマを追い払うためにセンサーライトを設置する",
    "地域のアライグマ駆除サービスを探す",
    "アライグマが夜中に芝生を掘り返している",
    "庭用のアライグマ忌避剤を買う",
    "アライグマが入ってくるフェンスの穴を修理する",
    "アライグマがデッキの下に巣を作った",
    "アライグマがゴミ箱を倒した後の片付けをする",
    "庭のアライグマについて動物管理に電話する",
    "アライグマが毎晩やってくる",
    "アライグマが鶏小屋に入ったか確認する",
    "アライグマ防止にゴミ箱に鍵をつける",
    "アライグマが玄関の猫のエサを全部食べた",
    "アライグマを移動させるために生け捕り罠を買う",
    "アライグマが屋根の瓦を壊して侵入した",
    "アライグマが入らないように床下を塞ぐ",
    "子アライグマが物置の下に住んでいる",
    "攻撃的なアライグマを動物管理局に報告する",
    "裏庭の鳥のエサ台をアライグマ対策する",
    "アライグマが網戸を引っ掻いた",
    "庭にアライグマの足跡がないか確認する",
    "煙突の音はアライグマかもしれない",
    "アライグマが魚の池に近づかないようにする必要がある",
    "アライグマがゴミ袋を破いた",
    "屋根裏のアライグマを駆除する人を雇う",
    "アライグマを庭に入れないために金網を設置する",
    "最近アライグマが人間の近くで大胆すぎる",
    "アラグイマがゴミを漁った",
    "屋根うらのアライグマ",
    "アライグマ対策のゴミぶたを買う",
    "アライグマ忌ひ剤を庭に",
    "アライグマの足あと玄関",
],
fr=[
    "raton laveur",
    "panda des poubelles",
    "nuisible",
    "faune sauvage",
    "nocturne",
    "bandit",
    "bête",
    "animal",
    "mammifère",
    "faune",
    "masque de raton laveur",
    "traces de raton laveur",
    "raton laveur des poubelles",
    "faune urbaine",
    "répulsif anti-raton laveur",
    "piège à raton laveur",
    "dégâts de raton laveur",
    "raton laveur dans le jardin",
    "le raton laveur est encore allé dans la poubelle cette nuit",
    "acheter un couvercle de poubelle anti-raton laveur",
    "appeler la dératisation pour le raton laveur dans le grenier",
    "le raton laveur a renversé le bac à compost",
    "sécuriser les poubelles avant l'arrivée des ratons laveurs",
    "vérifier le grenier pour les dégâts du raton laveur",
    "le raton laveur a laissé des empreintes boueuses sur le perron",
    "installer une lumière avec détecteur de mouvement contre les ratons laveurs",
    "trouver un service d'enlèvement de raton laveur dans le coin",
    "les ratons laveurs creusent la pelouse la nuit",
    "acheter du répulsif anti-raton laveur pour le jardin",
    "réparer le trou dans la clôture par où passe le raton laveur",
    "le raton laveur a fait un nid sous la terrasse",
    "nettoyer après que le raton laveur a renversé les poubelles",
    "appeler le contrôle animalier pour le raton laveur dans le jardin",
    "le raton laveur revient chaque nuit",
    "vérifier si le raton laveur est entré dans le poulailler",
    "mettre un cadenas sur la poubelle contre les ratons laveurs",
    "le raton laveur a mangé toute la nourriture du chat sur le perron",
    "acheter un piège vivant pour déplacer le raton laveur",
    "le raton laveur a abîmé les bardeaux du toit en entrant",
    "sceller le vide sanitaire pour empêcher les ratons laveurs d'entrer",
    "les bébés ratons laveurs vivent sous le cabanon",
    "signaler le raton laveur agressif aux services animaliers",
    "protéger les mangeoires d'oiseaux des ratons laveurs",
    "le raton laveur a griffé la porte-moustiquaire",
    "vérifier les traces de raton laveur dans le jardin",
    "le bruit dans la cheminée est peut-être un raton laveur",
    "il faut empêcher le raton laveur d'atteindre le bassin",
    "le raton laveur a déchiré le sac poubelle",
    "engager quelqu'un pour retirer le raton laveur du grenier",
    "installer du grillage pour éloigner les ratons laveurs du jardin",
    "le raton laveur est trop hardi près des gens ces derniers temps",
    "raton lvaeur dans la poubelle",
    "raton laveur dans le grneier",
    "couvercle anti-raton lvaeur",
    "répuslif pour le jardin",
    "traces de raton lvaeur sur le perron",
],
es=[
    "mapache",
    "panda de basura",
    "plaga",
    "fauna silvestre",
    "nocturno",
    "bandido",
    "bicho",
    "animal",
    "mamífero",
    "fauna",
    "máscara de mapache",
    "huellas de mapache",
    "mapache del bote de basura",
    "fauna urbana",
    "repelente de mapaches",
    "trampa para mapache",
    "daños por mapache",
    "mapache en el patio",
    "el mapache se metió en la basura otra vez anoche",
    "comprar una tapa de bote de basura a prueba de mapaches",
    "llamar al control de plagas por el mapache en el ático",
    "el mapache volcó el bote de composta",
    "asegurar los botes de basura antes de que vengan los mapaches",
    "revisar el ático por daños del mapache",
    "el mapache dejó huellas de lodo en el porche",
    "instalar una luz con sensor de movimiento para espantar mapaches",
    "encontrar un servicio de remoción de mapaches en la zona",
    "los mapaches están escarbando el pasto en la noche",
    "comprar repelente de mapaches para el jardín",
    "reparar el agujero de la cerca por donde entra el mapache",
    "el mapache hizo un nido debajo de la terraza",
    "limpiar después de que el mapache tiró los botes",
    "llamar al control animal por el mapache en el patio",
    "el mapache sigue regresando cada noche",
    "revisar si el mapache se metió al gallinero",
    "ponerle candado al bote de basura contra los mapaches",
    "el mapache se comió toda la comida del gato en el porche",
    "comprar una trampa para atrapar y reubicar al mapache",
    "el mapache dañó las tejas al meterse por el techo",
    "sellar el espacio bajo la casa para que no entren los mapaches",
    "los mapaches bebé viven debajo del cobertizo",
    "reportar al mapache agresivo al control animal",
    "proteger los comederos de pájaros de los mapaches",
    "el mapache arañó la puerta de mosquitero",
    "buscar huellas de mapache en el jardín",
    "el ruido en la chimenea podría ser un mapache",
    "necesito evitar que el mapache llegue al estanque de peces",
    "el mapache rompió la bolsa de basura",
    "contratar a alguien para sacar al mapache del ático",
    "instalar malla para que los mapaches no entren al jardín",
    "el mapache se está volviendo muy confiado con la gente",
    "mpaache se metió en la basura",
    "mapche en el ático",
    "tapa a prueba de mapcahes",
    "repelnte de mapaches jardín",
    "huelals de mapache en el porche",
])


# ── radiation ─────────────────────────────────────────────────────────────────
gen("radiation",
en=[
    "radiation",
    "nuclear",
    "radioactive",
    "hazard",
    "danger",
    "warning",
    "Geiger counter",
    "nuclear safety",
    "radiation level",
    "contamination",
    "fallout",
    "isotope",
    "ionizing radiation",
    "radiation exposure",
    "nuclear waste",
    "radiation detector",
    "safety inspection",
    "radiation zone",
    "check the radiation levels at the work site",
    "buy a Geiger counter for the inspection",
    "schedule the annual radiation safety inspection",
    "replace the batteries in the radiation detector",
    "attend the nuclear safety training session",
    "submit the radiation exposure report by Friday",
    "order new dosimeters for the lab workers",
    "check if the radioactive material is stored properly",
    "review the radiation safety protocol before the audit",
    "label the radiation hazard zone in the facility",
    "dispose of nuclear waste according to regulations",
    "monitor the radiation levels in the treatment room",
    "get certified in radiation safety for the new job",
    "test the radiation shielding in the X-ray room",
    "report the elevated radiation reading to the supervisor",
    "update the radiation emergency response plan",
    "clean the contaminated equipment in the decontamination area",
    "wear the dosimeter badge during the shift",
    "check the expiration date on the radiation warning signs",
    "call the radiation safety officer about the spill",
    "order lead aprons for the radiology department",
    "review the radiation dose limits for workers",
    "calibrate the Geiger counter before the survey",
    "seal the radioactive source in the proper container",
    "post radiation warning signs outside the restricted area",
    "train new employees on radiation safety procedures",
    "file the quarterly radiation monitoring report",
    "check if the radon levels in the basement are safe",
    "buy a radon test kit for the house",
    "the radiation alarm went off in the lab",
    "need to renew the radiation handling license",
    "schedule a radiation leak inspection for the plant",
    "radaition safety inspection",
    "nucler waste disposal",
    "radiaton detector batteries",
    "Geiger couner calibration",
    "radition warning signs",
],
ru=[
    "радиация",
    "ядерный",
    "радиоактивный",
    "опасность",
    "угроза",
    "предупреждение",
    "счётчик Гейгера",
    "ядерная безопасность",
    "уровень радиации",
    "загрязнение",
    "радиоактивные осадки",
    "изотоп",
    "ионизирующее излучение",
    "радиационное облучение",
    "ядерные отходы",
    "детектор радиации",
    "проверка безопасности",
    "радиационная зона",
    "проверить уровень радиации на рабочем объекте",
    "купить счётчик Гейгера для проверки",
    "запланировать ежегодную проверку радиационной безопасности",
    "заменить батарейки в детекторе радиации",
    "пройти обучение по ядерной безопасности",
    "сдать отчёт о радиационном облучении до пятницы",
    "заказать новые дозиметры для сотрудников лаборатории",
    "проверить правильно ли хранится радиоактивный материал",
    "просмотреть протокол радиационной безопасности перед аудитом",
    "обозначить зону радиационной опасности на объекте",
    "утилизировать ядерные отходы по правилам",
    "мониторить уровень радиации в процедурном кабинете",
    "получить сертификат по радиационной безопасности для новой работы",
    "проверить радиационную защиту в рентгеновском кабинете",
    "сообщить начальнику о повышенных показаниях радиации",
    "обновить план реагирования на радиационную аварию",
    "очистить загрязнённое оборудование в зоне дезактивации",
    "носить дозиметр в течение смены",
    "проверить срок годности знаков радиационной опасности",
    "позвонить инспектору по радиационной безопасности из-за разлива",
    "заказать свинцовые фартуки для рентгенологического отделения",
    "просмотреть допустимые дозы радиации для работников",
    "откалибровать счётчик Гейгера перед замером",
    "герметично закрыть радиоактивный источник в контейнере",
    "разместить знаки радиационной опасности у запретной зоны",
    "обучить новых сотрудников правилам радиационной безопасности",
    "подать квартальный отчёт по радиационному мониторингу",
    "проверить безопасен ли уровень радона в подвале",
    "купить набор для проверки радона в доме",
    "сработала радиационная сигнализация в лаборатории",
    "надо продлить лицензию на работу с радиацией",
    "запланировать проверку на утечку радиации на станции",
    "проврека радиационной безопасности",
    "утлизация ядерных отходов",
    "батарейки детктора радиации",
    "калибрвока счётчика Гейгера",
    "знаки предупреждения о радиаци",
],
de=[
    "Strahlung",
    "nuklear",
    "radioaktiv",
    "Gefahr",
    "Warnung",
    "Geigerzähler",
    "nukleare Sicherheit",
    "Strahlungsniveau",
    "Kontamination",
    "radioaktiver Niederschlag",
    "Isotop",
    "ionisierende Strahlung",
    "Strahlenbelastung",
    "Atommüll",
    "Strahlungsdetektor",
    "Sicherheitsinspektion",
    "Strahlungszone",
    "Strahlenschutz",
    "die Strahlungswerte am Arbeitsplatz prüfen",
    "einen Geigerzähler für die Inspektion kaufen",
    "die jährliche Strahlenschutzinspektion planen",
    "die Batterien im Strahlungsdetektor wechseln",
    "an der Schulung zur nuklearen Sicherheit teilnehmen",
    "den Strahlenbelastungsbericht bis Freitag einreichen",
    "neue Dosimeter für die Labormitarbeiter bestellen",
    "prüfen ob das radioaktive Material richtig gelagert ist",
    "das Strahlenschutzprotokoll vor dem Audit durchgehen",
    "die Strahlungsgefahrenzone in der Anlage kennzeichnen",
    "Atommüll vorschriftsgemäß entsorgen",
    "die Strahlungswerte im Behandlungsraum überwachen",
    "die Strahlenschutzzertifizierung für den neuen Job machen",
    "die Strahlungsabschirmung im Röntgenraum testen",
    "den erhöhten Strahlungswert dem Vorgesetzten melden",
    "den Notfallplan für Strahlungsunfälle aktualisieren",
    "die kontaminierte Ausrüstung im Dekontaminationsbereich reinigen",
    "das Dosimeter während der Schicht tragen",
    "das Ablaufdatum der Strahlungswarnzeichen prüfen",
    "den Strahlenschutzbeauftragten wegen der Verschüttung anrufen",
    "Bleischürzen für die Radiologieabteilung bestellen",
    "die Strahlendosisgrenzwerte für Mitarbeiter überprüfen",
    "den Geigerzähler vor der Messung kalibrieren",
    "die radioaktive Quelle im richtigen Behälter versiegeln",
    "Strahlungswarnzeichen vor dem Sperrbereich anbringen",
    "neue Mitarbeiter in Strahlenschutzverfahren schulen",
    "den vierteljährlichen Strahlungsüberwachungsbericht einreichen",
    "prüfen ob die Radonwerte im Keller sicher sind",
    "ein Radon-Testkit fürs Haus kaufen",
    "der Strahlungsalarm ging im Labor los",
    "muss die Strahlengenehmigung erneuern",
    "eine Überprüfung auf Strahlungslecks in der Anlage planen",
    "Strahlunsschutz-Inspektion",
    "nukleaer Abfallentsorgung",
    "Strahlungsdetektor Batrerien",
    "Geigerzähler Kalibreirung",
    "Stralungswarnzeichen anbringen",
],
ja=[
    "放射線",
    "核",
    "放射性",
    "危険",
    "警告",
    "ガイガーカウンター",
    "原子力安全",
    "放射線レベル",
    "汚染",
    "放射性降下物",
    "同位体",
    "電離放射線",
    "被ばく",
    "核廃棄物",
    "放射線検出器",
    "安全検査",
    "放射線区域",
    "放射線防護",
    "作業現場の放射線レベルを確認する",
    "検査用にガイガーカウンターを買う",
    "年次放射線安全検査をスケジュールする",
    "放射線検出器の電池を交換する",
    "原子力安全研修に出席する",
    "金曜日までに被ばく報告書を提出する",
    "ラボスタッフ用に新しい線量計を注文する",
    "放射性物質が適切に保管されているか確認する",
    "監査前に放射線安全プロトコルを確認する",
    "施設内の放射線危険区域を表示する",
    "規則に従って核廃棄物を処分する",
    "治療室の放射線レベルをモニタリングする",
    "新しい仕事のために放射線安全の資格を取る",
    "レントゲン室の放射線遮蔽をテストする",
    "上昇した放射線の数値を上司に報告する",
    "放射線緊急対応計画を更新する",
    "除染エリアで汚染された機器を洗浄する",
    "勤務中は線量計バッジを着用する",
    "放射線警告標識の有効期限を確認する",
    "漏洩について放射線安全管理者に電話する",
    "放射線科用の鉛エプロンを注文する",
    "作業者の放射線量限度を確認する",
    "測定前にガイガーカウンターを校正する",
    "放射性線源を適切な容器に密封する",
    "立入禁止区域の外に放射線警告標識を掲示する",
    "新入社員に放射線安全手順を教育する",
    "四半期ごとの放射線モニタリング報告書を提出する",
    "地下室のラドンレベルが安全か確認する",
    "家のラドン検査キットを買う",
    "研究室で放射線アラームが鳴った",
    "放射線取扱免許を更新しなきゃ",
    "発電所の放射線漏れ検査をスケジュールする",
    "ほうしゃせん安全検査",
    "かく廃棄物処分",
    "放射線けんしゅつ器の電池",
    "ガイガーカウンタこうせい",
    "放射線けいこく標識",
],
fr=[
    "radiation",
    "nucléaire",
    "radioactif",
    "danger",
    "avertissement",
    "compteur Geiger",
    "sécurité nucléaire",
    "niveau de radiation",
    "contamination",
    "retombées radioactives",
    "isotope",
    "rayonnement ionisant",
    "exposition aux radiations",
    "déchets nucléaires",
    "détecteur de radiation",
    "inspection de sécurité",
    "zone de radiation",
    "radioprotection",
    "vérifier les niveaux de radiation sur le site de travail",
    "acheter un compteur Geiger pour l'inspection",
    "planifier l'inspection annuelle de radioprotection",
    "changer les piles du détecteur de radiation",
    "assister à la formation sur la sécurité nucléaire",
    "soumettre le rapport d'exposition aux radiations avant vendredi",
    "commander de nouveaux dosimètres pour le personnel du labo",
    "vérifier si le matériau radioactif est correctement stocké",
    "revoir le protocole de radioprotection avant l'audit",
    "signaler la zone de danger radioactif dans l'établissement",
    "éliminer les déchets nucléaires conformément à la réglementation",
    "surveiller les niveaux de radiation dans la salle de traitement",
    "obtenir la certification en radioprotection pour le nouveau poste",
    "tester le blindage contre les radiations dans la salle de radio",
    "signaler la lecture de radiation élevée au superviseur",
    "mettre à jour le plan d'urgence en cas d'accident radiologique",
    "nettoyer l'équipement contaminé dans la zone de décontamination",
    "porter le badge dosimètre pendant le service",
    "vérifier la date d'expiration des panneaux d'avertissement radiation",
    "appeler le responsable radioprotection à propos du déversement",
    "commander des tabliers en plomb pour le service de radiologie",
    "revoir les limites de dose de radiation pour les travailleurs",
    "calibrer le compteur Geiger avant le relevé",
    "sceller la source radioactive dans le conteneur approprié",
    "afficher les panneaux d'avertissement radiation hors de la zone restreinte",
    "former les nouveaux employés aux procédures de radioprotection",
    "déposer le rapport trimestriel de surveillance radiologique",
    "vérifier si les niveaux de radon dans le sous-sol sont sûrs",
    "acheter un kit de test radon pour la maison",
    "l'alarme de radiation s'est déclenchée au labo",
    "il faut renouveler le permis de manipulation de radiations",
    "planifier une inspection des fuites de radiation à la centrale",
    "radaition inspection de sécurité",
    "décehts nucléaires à éliminer",
    "piles du détectuer de radiation",
    "calibrer le comptuer Geiger",
    "panneaux d'averitssement radiation",
],
es=[
    "radiación",
    "nuclear",
    "radiactivo",
    "peligro",
    "advertencia",
    "contador Geiger",
    "seguridad nuclear",
    "nivel de radiación",
    "contaminación",
    "lluvia radiactiva",
    "isótopo",
    "radiación ionizante",
    "exposición a la radiación",
    "desechos nucleares",
    "detector de radiación",
    "inspección de seguridad",
    "zona de radiación",
    "protección radiológica",
    "revisar los niveles de radiación en el sitio de trabajo",
    "comprar un contador Geiger para la inspección",
    "programar la inspección anual de seguridad radiológica",
    "cambiar las pilas del detector de radiación",
    "asistir a la capacitación de seguridad nuclear",
    "entregar el reporte de exposición a la radiación antes del viernes",
    "pedir dosímetros nuevos para el personal del laboratorio",
    "revisar si el material radiactivo está almacenado correctamente",
    "repasar el protocolo de seguridad radiológica antes de la auditoría",
    "señalizar la zona de peligro radiactivo en la instalación",
    "desechar los residuos nucleares según la normativa",
    "monitorear los niveles de radiación en la sala de tratamiento",
    "obtener la certificación en seguridad radiológica para el nuevo trabajo",
    "probar el blindaje contra radiación en la sala de rayos X",
    "reportar la lectura elevada de radiación al supervisor",
    "actualizar el plan de emergencia por radiación",
    "limpiar el equipo contaminado en el área de descontaminación",
    "usar la placa de dosímetro durante el turno",
    "revisar la fecha de vencimiento de los letreros de advertencia de radiación",
    "llamar al oficial de seguridad radiológica por el derrame",
    "pedir delantales de plomo para el departamento de radiología",
    "repasar los límites de dosis de radiación para los trabajadores",
    "calibrar el contador Geiger antes del levantamiento",
    "sellar la fuente radiactiva en el contenedor apropiado",
    "colocar letreros de advertencia de radiación fuera de la zona restringida",
    "capacitar a los empleados nuevos en procedimientos de seguridad radiológica",
    "presentar el reporte trimestral de monitoreo de radiación",
    "revisar si los niveles de radón en el sótano son seguros",
    "comprar un kit de prueba de radón para la casa",
    "la alarma de radiación se activó en el laboratorio",
    "necesito renovar la licencia de manejo de radiación",
    "programar una inspección de fugas de radiación en la planta",
    "radiacón inspección de seguridad",
    "descehos nucleares a desechar",
    "pilas del detecotr de radiación",
    "calibrar el contadro Geiger",
    "letreros de advertecnia de radiación",
])

print("\n=== Part 4 done (rabbit, raccoon, radiation) ===")
