#!/usr/bin/env python3
"""Batch task-002: 10 icons x 6 languages x 60 phrases.

Icons: usb-drive, user, utensils, van-shuttle, vault,
       vials, violin, volcano, walkie-talkie, wand

This file: shared helpers + icons 1-5.
Run gen_icons_task_002b.py for icons 6-10.
"""

import csv, re
from pathlib import Path

ICONS_DIR = Path(__file__).resolve().parent / "icons"
LANGS = ["en", "ru", "de", "ja", "fr", "es"]

BAD_EN = [
    re.compile(r"\bicon\b", re.I),
    re.compile(r"\bsymbol\b.{0,10}\bfor\b", re.I),
    re.compile(r"show .+ for the", re.I),
    re.compile(r"I need a .+ for", re.I),
]
BAD_RU = [
    re.compile(r"иконк[аиуе]", re.I),
    re.compile(r"символ .+ для", re.I),
    re.compile(r"приложени[еяю]", re.I),
]

def read_csv(path):
    if not path.exists():
        return []
    with path.open(encoding="utf-8", newline="") as f:
        return [r["text"].strip() for r in csv.DictReader(f) if r["text"].strip()]

def write_csv(path, texts, label):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["text", "label"])
        for t in texts:
            w.writerow([t, label])

def is_bad_en(t):
    return any(p.search(t) for p in BAD_EN)

def is_bad_ru(t):
    return any(p.search(t) for p in BAD_RU)

def has_mixed_en(t):
    latin = re.findall(r"[a-zA-Z]{2,}", t)
    borrowed = {"usb", "ssd", "rpg", "dnd", "gb"}
    return len([w for w in latin if w.lower() not in borrowed]) >= 2

def process(icon, rm_en=set(), rm_ru=set(),
            new_en=None, new_ru=None, new_de=None,
            new_ja=None, new_fr=None, new_es=None):
    en_p = ICONS_DIR / icon / "train_en.csv"
    ru_p = ICONS_DIR / icon / "train_ru.csv"
    ex_en = read_csv(en_p)
    ex_ru = read_csv(ru_p)
    if rm_en:
        ex_en = [t for i, t in enumerate(ex_en) if (i+1) not in rm_en]
    if rm_ru:
        ex_ru = [t for i, t in enumerate(ex_ru) if (i+1) not in rm_ru]
    ex_en = [t for t in ex_en if not is_bad_en(t)]
    ex_ru = [t for t in ex_ru if not is_bad_ru(t) and not has_mixed_en(t)]
    def merge(existing, new):
        s = set(existing)
        for t in (new or []):
            if t not in s:
                existing.append(t)
                s.add(t)
        return existing
    ex_en = merge(ex_en, new_en)
    ex_ru = merge(ex_ru, new_ru)
    write_csv(en_p, ex_en, icon)
    write_csv(ru_p, ex_ru, icon)
    for lang, data in [("de", new_de), ("ja", new_ja), ("fr", new_fr), ("es", new_es)]:
        if data is not None:
            write_csv(ICONS_DIR / icon / f"train_{lang}.csv", data, icon)
    ok = True
    for lang in LANGS:
        p = ICONS_DIR / icon / f"train_{lang}.csv"
        if p.exists():
            n = len(read_csv(p))
            if n != 60:
                print(f"  WARNING {icon}/{lang}: {n} rows (expected 60)")
                ok = False
    if ok:
        print(f"  {icon}: all 6 langs = 60 rows OK")


# ═══════════════════════════════════════════════════════════════════════════
# 1. usb-drive
# ═══════════════════════════════════════════════════════════════════════════
process("usb-drive",
    rm_en={21},
    new_en=[
        "flash drive", "pen drive", "USB stick", "thumb drive", "USB storage",
        "portable drive", "memory stick", "USB key", "USB dongle",
        "back up photos to the flash drive",
        "buy a new USB drive for work",
        "copy the presentation onto the USB stick",
        "format the pen drive before using it",
        "return the borrowed USB drive to Mike",
        "label the flash drives for the team",
        "check if the thumb drive has enough space",
        "grab the USB drive from the desk drawer",
        "scan the USB stick for viruses before opening",
        "transfer the report to the USB drive",
        "bring a USB drive to the meeting",
        "order USB drives in bulk for the office",
        "save the installer on a bootable USB",
        "plug in the flash drive and copy the folder",
        "lend Sarah my spare USB drive",
        "find the USB drive with the tax documents",
        "move the music library to the pen drive",
        "eject the USB drive safely before unplugging",
        "encrypt the flash drive with sensitive files",
        "pack a USB drive for the trip",
        "pick up a 64 GB flash drive at the store",
        "USB drve backup",
        "flsh drive transfer files",
    ],
    new_ru=[
        "флеш-накопитель", "юсб-флешка", "переносной накопитель", "карта памяти USB",
        "купить новую флешку на 64 гигабайта",
        "скопировать отчёт на флешку для начальника",
        "взять флешку на совещание",
        "вернуть флешку Мише после копирования",
        "проверить сколько места на флешке",
        "заказать партию флешек для офиса",
        "достать флешку из ящика стола",
        "подписать флешки для каждого сотрудника",
        "перенести музыку на флешку в машину",
        "зашифровать флешку с конфиденциальными файлами",
        "упаковать флешку в дорожную сумку",
        "одолжить Саше запасную флешку",
        "купить флешку в магазине электроники",
        "безопасно извлечь флешку перед отключением",
        "скинуть фотографии на флеш-накопитель",
        "отнести флешку с документами в офис",
        "флшека для копирования",
    ],
    new_de=[
        "USB-Stick", "Flash-Laufwerk", "Speicherstick", "USB-Laufwerk", "Datenstick",
        "USB-Speicher", "tragbarer Speicher", "Memorystick", "Pen-Drive",
        "USB-Datenträger", "USB-Schlüssel", "externer USB-Speicher",
        "kleiner USB-Stick", "USB-Stick am Schlüsselbund", "schneller USB-3.0-Stick",
        "großer USB-Stick 128 GB", "verschlüsselter USB-Stick", "USB-Stick für Backups",
        "Fotos auf den USB-Stick sichern", "neuen USB-Stick für die Arbeit kaufen",
        "Präsentation auf den USB-Stick kopieren", "den USB-Stick vor der Nutzung formatieren",
        "den geliehenen USB-Stick an Max zurückgeben", "USB-Sticks für das Team beschriften",
        "prüfen ob genug Platz auf dem Stick ist", "den USB-Stick aus der Schublade holen",
        "USB-Stick vor dem Öffnen auf Viren scannen", "Bericht auf den USB-Stick übertragen",
        "USB-Stick zum Meeting mitbringen", "USB-Sticks in großer Menge bestellen",
        "Installer auf einem bootfähigen USB speichern", "Flash-Laufwerk einstecken und Ordner kopieren",
        "Sarah meinen Ersatz-USB-Stick leihen", "den USB-Stick mit den Steuerdokumenten finden",
        "Musiksammlung auf den Stick verschieben", "USB-Stick sicher auswerfen vor dem Abziehen",
        "den Flash-Stick mit sensiblen Dateien verschlüsseln", "USB-Stick für die Reise einpacken",
        "einen 64-GB-Stick im Laden kaufen", "Backup der Arbeit auf USB-Stick machen",
        "Dokumente vom USB-Stick auf den Laptop kopieren", "den alten USB-Stick aufräumen",
        "USB-Stick an den Fernseher anschließen", "Musik auf dem USB-Stick im Auto hören",
        "USB-Stick mit Hausaufgaben in die Schule mitnehmen", "Zugangsdaten auf den USB-Stick kopieren",
        "Vertrag auf den USB-Stick speichern", "USB-Stick an Kollegen weitergeben",
        "den verlorenen USB-Stick im Büro suchen", "Projektdateien auf den USB-Stick ziehen",
        "USB-Stick mit Firmenlogo bestellen",
        "UBS-Stick Backup machen", "Flasch-Laufwerk Dateien kopiren", "USB-Stik formatieren",
    ],
    new_ja=[
        "USBメモリ", "フラッシュドライブ", "USBスティック", "USBドライブ", "サムドライブ",
        "ペンドライブ", "USBストレージ", "ポータブルドライブ", "メモリスティック",
        "外付けUSBメモリ", "小型USBメモリ", "USB3.0メモリ", "暗号化USBメモリ",
        "キーホルダー付きUSBメモリ", "大容量USBメモリ", "バックアップ用USBメモリ",
        "USB記憶装置", "携帯用USBメモリ",
        "写真をUSBメモリにバックアップする", "仕事用に新しいUSBメモリを買う",
        "プレゼン資料をUSBメモリにコピーする", "使う前にUSBメモリをフォーマットする",
        "借りたUSBメモリを田中さんに返す", "チーム用のUSBメモリにラベルを貼る",
        "USBメモリの空き容量を確認する", "引き出しからUSBメモリを取り出す",
        "USBメモリのウイルスチェックをする", "報告書をUSBメモリに移す",
        "会議にUSBメモリを持っていく", "オフィス用にUSBメモリをまとめて注文する",
        "ブート用USBメモリにインストーラを保存する", "USBメモリを差してフォルダをコピーする",
        "予備のUSBメモリを佐藤さんに貸す", "税務書類の入ったUSBメモリを探す",
        "音楽ライブラリをUSBメモリに移動する", "抜く前にUSBメモリを安全に取り外す",
        "機密ファイルの入ったUSBメモリを暗号化する", "旅行用にUSBメモリを準備する",
        "お店で64GBのUSBメモリを買う", "USBメモリからノートパソコンに書類をコピーする",
        "古いUSBメモリのデータを整理する", "テレビにUSBメモリを接続する",
        "車でUSBメモリの音楽を聴く", "学校に宿題の入ったUSBメモリを持っていく",
        "アクセスキーをUSBメモリにコピーする", "契約書をUSBメモリに保存する",
        "同僚にUSBメモリを渡す", "オフィスでなくしたUSBメモリを探す",
        "プロジェクトファイルをUSBメモリに入れる", "会社ロゴ入りUSBメモリを発注する",
        "USBメモリにバクアップ", "フラッシュドライブにファイルをコピーする", "USBメモリをフォーマトする",
    ],
    new_fr=[
        "clé USB", "lecteur flash", "clé mémoire", "lecteur USB", "disque USB",
        "stockage USB", "clé USB portable", "mémoire flash", "pen drive",
        "clé USB 3.0", "clé USB cryptée", "petite clé USB", "clé USB porte-clés",
        "clé USB grande capacité", "clé USB de sauvegarde", "support USB",
        "clé USB externe", "stockage portable USB",
        "sauvegarder les photos sur la clé USB", "acheter une nouvelle clé USB pour le travail",
        "copier la présentation sur la clé USB", "formater la clé USB avant de l'utiliser",
        "rendre la clé USB empruntée à Marc", "étiqueter les clés USB pour l'équipe",
        "vérifier s'il y a assez de place sur la clé", "prendre la clé USB dans le tiroir du bureau",
        "scanner la clé USB contre les virus", "transférer le rapport sur la clé USB",
        "apporter une clé USB à la réunion", "commander des clés USB en gros pour le bureau",
        "enregistrer l'installateur sur une clé USB bootable", "brancher la clé USB et copier le dossier",
        "prêter ma clé USB de secours à Sophie", "trouver la clé USB avec les documents fiscaux",
        "déplacer la bibliothèque musicale sur la clé", "éjecter la clé USB avant de la débrancher",
        "chiffrer la clé USB avec les fichiers sensibles", "emporter une clé USB pour le voyage",
        "acheter une clé USB de 64 Go au magasin", "faire une sauvegarde du travail sur clé USB",
        "copier les documents de la clé vers le portable", "nettoyer l'ancienne clé USB",
        "brancher la clé USB sur la télévision", "écouter la musique de la clé USB en voiture",
        "amener la clé USB avec les devoirs à l'école", "copier les codes d'accès sur la clé USB",
        "enregistrer le contrat sur la clé USB", "passer la clé USB au collègue",
        "chercher la clé USB perdue au bureau", "mettre les fichiers du projet sur la clé USB",
        "commander des clés USB avec le logo entreprise",
        "clée USB sauvegarde", "clé UBS copier fichiers", "clé USB formater",
    ],
    new_es=[
        "memoria USB", "pendrive", "llave USB", "unidad flash", "disco USB",
        "almacenamiento USB", "memoria portátil", "memoria flash", "USB extraíble",
        "USB 3.0", "USB cifrado", "USB pequeño", "USB llavero",
        "USB de gran capacidad", "USB de respaldo", "soporte USB",
        "USB externo", "almacenamiento portátil USB",
        "respaldar las fotos en la memoria USB", "comprar una memoria USB nueva para el trabajo",
        "copiar la presentación en el pendrive", "formatear el pendrive antes de usarlo",
        "devolver la memoria USB prestada a Miguel", "etiquetar las memorias USB del equipo",
        "revisar si hay espacio en la memoria USB", "sacar la memoria USB del cajón del escritorio",
        "escanear la USB en busca de virus", "transferir el informe a la memoria USB",
        "llevar una memoria USB a la reunión", "pedir memorias USB al por mayor para la oficina",
        "guardar el instalador en un USB booteable", "conectar el pendrive y copiar la carpeta",
        "prestar mi USB de repuesto a Sofía", "encontrar la memoria USB con los documentos fiscales",
        "mover la biblioteca de música al pendrive", "expulsar la USB de forma segura antes de desconectar",
        "cifrar la memoria USB con archivos confidenciales", "empacar una memoria USB para el viaje",
        "comprar un pendrive de 64 GB en la tienda", "hacer respaldo del trabajo en la memoria USB",
        "copiar documentos del USB a la laptop", "limpiar la memoria USB antigua",
        "conectar la USB al televisor", "escuchar música de la USB en el carro",
        "llevar la USB con la tarea a la escuela", "copiar las claves de acceso en la USB",
        "guardar el contrato en la memoria USB", "pasar la memoria USB al compañero",
        "buscar la memoria USB perdida en la oficina", "poner los archivos del proyecto en la USB",
        "pedir memorias USB con el logo de la empresa",
        "memora USB respaldo", "pendrave copiar archivos", "memória USB formatear",
    ],
)

# ═══════════════════════════════════════════════════════════════════════════
# 2. user
# ═══════════════════════════════════════════════════════════════════════════
process("user",
    rm_ru={44, 45, 46, 47, 48, 49},
    new_en=[
        "account", "avatar", "profile", "username", "login", "signup",
        "member", "individual", "my account", "personal page",
        "user settings", "registered user",
        "update my profile picture", "create a new account on the website",
        "change the username in settings", "reset the account password",
        "fill out the user profile details", "verify the account with email",
        "check my account balance", "edit my bio on the profile page",
        "log into my account on the new phone", "deactivate the old user account",
        "add a phone number to my profile", "review the account privacy settings",
        "switch to a different user account", "set up two-factor authentication on my account",
        "upload a new avatar for the forum", "delete the inactive user account",
        "invite a new user to the workspace", "complete the profile setup wizard",
        "link the social media account to my profile",
        "check if my acccount is verified", "update the acount email address",
        "profle settings need updating",
    ],
    new_ru=[
        "аккаунт", "логин", "регистрация", "участник",
        "личная страница", "настройки пользователя", "зарегистрированный пользователь",
        "обновить фото профиля", "создать новый аккаунт на сайте",
        "поменять имя пользователя в настройках", "сбросить пароль аккаунта",
        "заполнить данные профиля пользователя", "подтвердить аккаунт по электронной почте",
        "проверить баланс аккаунта", "отредактировать описание на странице профиля",
        "войти в аккаунт на новом телефоне", "деактивировать старый аккаунт",
        "добавить номер телефона в профиль", "проверить настройки конфиденциальности аккаунта",
        "переключиться на другой аккаунт", "настроить двухфакторную аутентификацию",
        "загрузить новый аватар для форума", "удалить неактивный аккаунт",
        "пригласить нового пользователя в рабочее пространство",
        "завершить настройку профиля", "привязать соцсеть к профилю",
        "проверить подтверждён ли аккаунт", "обновить электронную почту акаунта",
        "настроки профиля нужно обновить",
    ],
    new_de=[
        "Konto", "Benutzerkonto", "Profil", "Avatar", "Benutzername",
        "Anmeldung", "Registrierung", "Mitglied", "Person", "Einzelperson",
        "persönliche Seite", "Benutzereinstellungen", "mein Konto",
        "Benutzerprofil", "registrierter Benutzer", "Nutzer", "Nutzerkonto", "Anmeldedaten",
        "Profilbild aktualisieren", "ein neues Konto auf der Website erstellen",
        "den Benutzernamen in den Einstellungen ändern", "das Kontopasswort zurücksetzen",
        "die Profildaten des Benutzers ausfüllen", "das Konto per E-Mail bestätigen",
        "meinen Kontostand überprüfen", "die Biografie auf der Profilseite bearbeiten",
        "mich auf dem neuen Handy in mein Konto einloggen", "das alte Benutzerkonto deaktivieren",
        "eine Telefonnummer zum Profil hinzufügen", "die Datenschutzeinstellungen des Kontos prüfen",
        "zu einem anderen Benutzerkonto wechseln", "Zwei-Faktor-Authentifizierung einrichten",
        "einen neuen Avatar für das Forum hochladen", "das inaktive Benutzerkonto löschen",
        "einen neuen Benutzer zum Arbeitsbereich einladen",
        "den Profil-Einrichtungsassistenten abschließen",
        "das Social-Media-Konto mit dem Profil verknüpfen", "prüfen ob mein Konto verifiziert ist",
        "die Konto-E-Mail-Adresse aktualisieren", "Profilname und Beschreibung anpassen",
        "Passwort für das Benutzerkonto ändern", "Kontosicherheit überprüfen",
        "Profil auf privat stellen", "neues Mitglied im Team anlegen",
        "Benutzerdaten exportieren", "Konto nach Inaktivität reaktivieren",
        "Profilbild zuschneiden und hochladen", "Benachrichtigungen im Konto einstellen",
        "Kontoverknüpfung mit Google einrichten", "altes Passwort im Profil ändern",
        "Benutzerprofil für den neuen Job aktualisieren", "Konto für die App einrichten",
        "Adresse im Benutzerprofil aktualisieren", "abgemeldetes Konto wieder aktivieren",
        "Kontodaten an den Support schicken", "Profil vor der Bewerbung aktualisieren",
        "Benutzernam ändern", "Kontto Passwort zurücksetzen",
        "Profl Einstellungen prüfen", "Benuzerkonto deaktivieren",
    ],
    new_ja=[
        "アカウント", "プロフィール", "アバター", "ユーザー名", "ログイン",
        "サインアップ", "メンバー", "個人ページ", "ユーザー設定", "マイアカウント",
        "登録ユーザー", "ユーザー", "利用者", "会員", "本人確認",
        "ユーザープロフィール", "アカウント設定", "ログイン情報",
        "プロフィール写真を更新する", "ウェブサイトで新しいアカウントを作成する",
        "設定でユーザー名を変更する", "アカウントのパスワードをリセットする",
        "ユーザープロフィールの詳細を入力する", "メールでアカウントを確認する",
        "アカウントの残高を確認する", "プロフィールページの自己紹介を編集する",
        "新しい電話でアカウントにログインする", "古いユーザーアカウントを無効にする",
        "プロフィールに電話番号を追加する", "アカウントのプライバシー設定を確認する",
        "別のユーザーアカウントに切り替える", "アカウントに二段階認証を設定する",
        "フォーラム用の新しいアバターをアップロードする", "使っていないアカウントを削除する",
        "ワークスペースに新しいユーザーを招待する", "プロフィール設定ウィザードを完了する",
        "SNSアカウントをプロフィールにリンクする", "アカウントが認証済みか確認する",
        "アカウントのメールアドレスを更新する", "プロフィール名と説明を変更する",
        "アカウントのパスワードを変更する", "アカウントのセキュリティを確認する",
        "プロフィールを非公開にする", "チームに新しいメンバーを追加する",
        "ユーザーデータをエクスポートする", "休止後にアカウントを再有効化する",
        "プロフィール写真をトリミングしてアップロードする", "アカウントの通知設定を変更する",
        "Googleアカウントと連携する", "古いパスワードを変更する",
        "新しい仕事用にプロフィールを更新する", "アプリのアカウントを設定する",
        "プロフィールの住所を更新する", "応募前にプロフィールを更新する",
        "ユーザー名を変更する", "アカウントパスワドをリセット",
        "プロフィル設定を確認する", "ユーザーアカウトを無効にする",
    ],
    new_fr=[
        "compte", "profil", "avatar", "nom d'utilisateur", "connexion",
        "inscription", "membre", "personne", "individu", "page personnelle",
        "paramètres utilisateur", "mon compte", "profil utilisateur",
        "utilisateur enregistré", "utilisateur", "compte utilisateur",
        "identifiants", "données de connexion",
        "mettre à jour la photo de profil", "créer un nouveau compte sur le site",
        "changer le nom d'utilisateur dans les paramètres", "réinitialiser le mot de passe du compte",
        "remplir les détails du profil utilisateur", "vérifier le compte par e-mail",
        "consulter le solde du compte", "modifier la bio sur la page de profil",
        "se connecter au compte sur le nouveau téléphone", "désactiver l'ancien compte utilisateur",
        "ajouter un numéro de téléphone au profil", "vérifier les paramètres de confidentialité du compte",
        "passer à un autre compte utilisateur", "configurer l'authentification à deux facteurs",
        "télécharger un nouvel avatar pour le forum", "supprimer le compte utilisateur inactif",
        "inviter un nouvel utilisateur dans l'espace de travail",
        "terminer l'assistant de configuration du profil",
        "lier le compte de réseau social au profil", "vérifier si mon compte est validé",
        "mettre à jour l'adresse e-mail du compte", "modifier le nom et la description du profil",
        "changer le mot de passe du compte", "vérifier la sécurité du compte",
        "mettre le profil en privé", "créer un nouveau membre dans l'équipe",
        "exporter les données utilisateur", "réactiver le compte après inactivité",
        "recadrer et télécharger la photo de profil", "régler les notifications du compte",
        "configurer la liaison avec le compte Google", "changer l'ancien mot de passe dans le profil",
        "mettre à jour le profil pour le nouvel emploi", "configurer le compte pour l'application",
        "mettre à jour l'adresse dans le profil", "envoyer les infos du compte au support",
        "mettre à jour le profil avant la candidature", "changer le nom d'utilisateur",
        "réinitialisr le mot de passe", "paramèters du profil à vérifier",
        "compt utilisateur désactiver",
    ],
    new_es=[
        "cuenta", "perfil", "avatar", "nombre de usuario", "inicio de sesión",
        "registro", "miembro", "persona", "individuo", "página personal",
        "ajustes de usuario", "mi cuenta", "perfil de usuario",
        "usuario registrado", "usuario", "cuenta de usuario",
        "credenciales", "datos de acceso",
        "actualizar la foto de perfil", "crear una cuenta nueva en el sitio web",
        "cambiar el nombre de usuario en los ajustes", "restablecer la contraseña de la cuenta",
        "completar los datos del perfil de usuario", "verificar la cuenta por correo electrónico",
        "revisar el saldo de la cuenta", "editar la biografía en la página de perfil",
        "iniciar sesión en la cuenta desde el nuevo teléfono", "desactivar la cuenta de usuario antigua",
        "agregar un número de teléfono al perfil", "revisar los ajustes de privacidad de la cuenta",
        "cambiar a otra cuenta de usuario", "configurar la autenticación de dos factores",
        "subir un nuevo avatar para el foro", "eliminar la cuenta de usuario inactiva",
        "invitar a un nuevo usuario al espacio de trabajo",
        "completar el asistente de configuración del perfil",
        "vincular la cuenta de red social al perfil", "verificar si mi cuenta está validada",
        "actualizar el correo electrónico de la cuenta", "modificar el nombre y descripción del perfil",
        "cambiar la contraseña de la cuenta", "verificar la seguridad de la cuenta",
        "poner el perfil en privado", "crear un nuevo miembro en el equipo",
        "exportar los datos de usuario", "reactivar la cuenta después de inactividad",
        "recortar y subir la foto de perfil", "ajustar las notificaciones de la cuenta",
        "configurar la vinculación con la cuenta de Google",
        "cambiar la contraseña antigua en el perfil",
        "actualizar el perfil para el nuevo trabajo", "configurar la cuenta para la aplicación",
        "actualizar la dirección en el perfil", "enviar los datos de la cuenta al soporte",
        "actualizar el perfil antes de la solicitud", "cambiar el nombre de usuario",
        "restablcer la contraseña", "ajustes del perfíl verificar",
        "cueta de usuario desactivar",
    ],
)

# ═══════════════════════════════════════════════════════════════════════════
# 3. utensils
# ═══════════════════════════════════════════════════════════════════════════
process("utensils",
    rm_ru={38, 39, 40, 41, 42, 43},
    new_en=[
        "cutlery", "silverware", "spoon", "fork", "knife", "dining set",
        "table setting", "flatware", "place setting", "stainless steel cutlery", "serving utensils",
        "buy a new cutlery set for the kitchen", "polish the silverware before the dinner party",
        "set the table with fork knife and spoon", "wash the utensils after dinner",
        "replace the old kitchen utensils", "pack utensils for the picnic",
        "sort the cutlery drawer", "grab a fork and knife from the drawer",
        "put the silverware in the dishwasher", "bring extra utensils to the potluck",
        "buy disposable utensils for the barbecue", "order a camping utensil kit online",
        "find matching utensils for the new dishes", "dry the cutlery and put it away",
        "sharpen the dinner knives", "lay out dessert spoons for the guests",
        "count the utensils before the event", "pick up bamboo utensils at the eco store",
        "store the good silverware in the cabinet", "hand wash the wooden utensils",
        "wrap utensils in napkins for the buffet", "buy kids utensils for the toddler",
        "cutelry set for new apartment", "silverwear polish before guests", "untensils for the picnic",
    ],
    new_ru=[
        "столовые приборы", "серебро столовое", "вилка", "нож столовый",
        "ложка столовая", "сервировка", "набор приборов", "нержавеющие приборы",
        "купить новый набор столовых приборов", "почистить серебряные приборы перед ужином",
        "накрыть стол вилками ножами и ложками", "помыть приборы после ужина",
        "заменить старые кухонные приборы", "взять приборы на пикник",
        "разобрать ящик со столовыми приборами", "достать вилку и нож из ящика",
        "положить приборы в посудомоечную машину", "принести дополнительные приборы на вечеринку",
        "купить одноразовые приборы для шашлыка", "заказать походный набор приборов онлайн",
        "найти подходящие приборы к новой посуде", "высушить приборы и убрать на место",
        "наточить столовые ножи", "разложить десертные ложки для гостей",
        "посчитать приборы перед мероприятием", "купить бамбуковые приборы в эко-магазине",
        "убрать парадные приборы в шкаф", "вымыть деревянные приборы вручную",
        "завернуть приборы в салфетки для фуршета", "купить детские приборы для малыша",
        "столоые приборы для новой квартиры", "сребряные приборы почистить перед гостями",
        "прибры для пикника",
    ],
    new_de=[
        "Besteck", "Silberbesteck", "Gabel", "Messer", "Löffel", "Essbesteck",
        "Tischgedeck", "Besteckset", "Gedeck", "Edelstahlbesteck", "Servierbesteck",
        "Tafelbesteck", "Kuchengabel", "Suppenlöffel", "Buttermesser",
        "Einwegbesteck", "Campingbesteck", "Kinderbesteck",
        "neues Besteckset für die Küche kaufen", "das Silberbesteck vor der Dinnerparty polieren",
        "den Tisch mit Gabel Messer und Löffel decken", "das Besteck nach dem Abendessen abwaschen",
        "das alte Küchenbesteck ersetzen", "Besteck für das Picknick einpacken",
        "die Besteckschublade sortieren", "Gabel und Messer aus der Schublade nehmen",
        "das Besteck in den Geschirrspüler räumen", "zusätzliches Besteck zum Potluck mitbringen",
        "Einwegbesteck für den Grillabend kaufen", "Campingbesteck online bestellen",
        "passendes Besteck zum neuen Geschirr finden", "das Besteck abtrocknen und wegräumen",
        "die Tafelmesser schärfen", "Dessertlöffel für die Gäste bereitstellen",
        "Besteck vor der Veranstaltung zählen", "Bambusbesteck im Ökoladen kaufen",
        "das gute Silberbesteck im Schrank verstauen", "Holzbesteck von Hand waschen",
        "Besteck in Servietten für das Buffet wickeln", "Kinderbesteck für das Kleinkind kaufen",
        "Besteck für die neue Wohnung besorgen", "Kuchengabeln für den Nachtisch auslegen",
        "neues Steakmesser-Set bestellen", "Besteckkasten als Geschenk einpacken",
        "Teelöffel nachkaufen es fehlen welche", "das Besteck nach Größe sortieren",
        "Picknickbesteck in den Rucksack packen", "Besteck im Restaurant nachfragen",
        "neues Besteck für die Kantine bestellen", "die Gabeln im Besteckkorb sortieren",
        "Löffel für die Suppe bereitstellen", "Besteck für zehn Personen bereitstellen",
        "Grillbesteck aus dem Keller holen",
        "Bestek für das Picknick einpackn", "Silberbestek polieren",
        "Gabeln und Meser aus der Schublade", "Bestck nach dem Essen abwaschen",
    ],
    new_ja=[
        "カトラリー", "フォーク", "ナイフ", "スプーン", "食器セット",
        "テーブルセッティング", "銀食器", "ステンレスカトラリー", "食卓用具",
        "取り分け用具", "デザートスプーン", "バターナイフ", "使い捨てカトラリー",
        "キャンプ用カトラリー", "子供用カトラリー", "ケーキフォーク",
        "スープスプーン", "カトラリーセット",
        "キッチン用に新しいカトラリーセットを買う", "ディナーパーティの前に銀食器を磨く",
        "フォークとナイフとスプーンでテーブルをセットする", "夕食後にカトラリーを洗う",
        "古いキッチン用具を交換する", "ピクニック用にカトラリーを用意する",
        "カトラリーの引き出しを整理する", "引き出しからフォークとナイフを取り出す",
        "カトラリーを食洗機に入れる", "持ち寄りパーティに予備のカトラリーを持っていく",
        "バーベキュー用に使い捨てカトラリーを買う", "キャンプ用カトラリーキットをオンラインで注文する",
        "新しい食器に合うカトラリーを探す", "カトラリーを乾かして片付ける",
        "ディナーナイフを研ぐ", "ゲスト用にデザートスプーンを並べる",
        "イベント前にカトラリーを数える", "エコショップで竹のカトラリーを買う",
        "良い銀食器を棚にしまう", "木製カトラリーを手洗いする",
        "ビュッフェ用にカトラリーをナプキンで包む", "幼児用のカトラリーを買う",
        "新しいアパート用にカトラリーを揃える", "ケーキフォークをデザート用に出す",
        "新しいステーキナイフセットを注文する", "カトラリーボックスをプレゼント用に包む",
        "ティースプーンを買い足す", "カトラリーをサイズ別に整理する",
        "ピクニック用カトラリーをリュックに入れる", "レストランでカトラリーを頼む",
        "食堂用に新しいカトラリーを注文する", "バスケットのフォークを整理する",
        "スープ用のスプーンを準備する", "10人分のカトラリーを用意する",
        "結婚祝いにカトラリーセットを選ぶ",
        "銀食器をみがく", "フォークとナイフを引き出しから取る",
        "夕食のあとカトラリーをあらう",
    ],
    new_fr=[
        "couverts", "argenterie", "fourchette", "couteau", "cuillère",
        "service de table", "couvert de table", "ménagère", "couverts en inox",
        "couverts de service", "fourchette à dessert", "cuillère à soupe",
        "couteau à beurre", "couverts jetables", "couverts de camping",
        "couverts pour enfants", "couvert individuel", "set de couverts",
        "acheter un nouveau set de couverts pour la cuisine", "polir l'argenterie avant le dîner",
        "mettre la table avec fourchette couteau et cuillère", "laver les couverts après le dîner",
        "remplacer les vieux couverts de cuisine", "préparer les couverts pour le pique-nique",
        "ranger le tiroir à couverts", "prendre une fourchette et un couteau dans le tiroir",
        "mettre les couverts au lave-vaisselle", "apporter des couverts supplémentaires au repas partagé",
        "acheter des couverts jetables pour le barbecue", "commander un kit de couverts de camping en ligne",
        "trouver des couverts assortis à la nouvelle vaisselle", "sécher les couverts et les ranger",
        "aiguiser les couteaux de table", "disposer les cuillères à dessert pour les invités",
        "compter les couverts avant l'événement", "acheter des couverts en bambou au magasin bio",
        "ranger la belle argenterie dans le buffet", "laver les couverts en bois à la main",
        "enrouler les couverts dans les serviettes pour le buffet",
        "acheter des couverts pour enfants pour le bébé",
        "trouver des couverts pour le nouvel appartement",
        "sortir les fourchettes à gâteau pour le dessert",
        "commander un nouveau set de couteaux à steak", "emballer la ménagère en cadeau",
        "racheter des petites cuillères il en manque", "trier les couverts par taille",
        "mettre les couverts de pique-nique dans le sac", "demander des couverts au restaurant",
        "commander de nouveaux couverts pour la cantine", "trier les fourchettes dans le panier",
        "préparer les cuillères pour la soupe",
        "argentrie polir avant les invités", "fouchettes et couteaux du tiroir",
        "coverts après le dîner laver",
    ],
    new_es=[
        "cubiertos", "cubertería", "tenedor", "cuchillo", "cuchara",
        "juego de mesa", "servicio de mesa", "cubiertos de acero inoxidable",
        "cubiertos para servir", "tenedor de postre", "cuchara sopera",
        "cuchillo de mantequilla", "cubiertos desechables", "cubiertos de camping",
        "cubiertos para niños", "cubierto individual", "set de cubiertos", "cubertería de plata",
        "comprar un nuevo juego de cubiertos para la cocina", "pulir la cubertería de plata antes de la cena",
        "poner la mesa con tenedor cuchillo y cuchara", "lavar los cubiertos después de cenar",
        "reemplazar los cubiertos viejos de la cocina", "preparar cubiertos para el pícnic",
        "ordenar el cajón de cubiertos", "sacar un tenedor y cuchillo del cajón",
        "poner los cubiertos en el lavavajillas", "llevar cubiertos extra a la comida compartida",
        "comprar cubiertos desechables para la parrillada", "pedir un kit de cubiertos de camping en línea",
        "buscar cubiertos que combinen con la vajilla nueva", "secar los cubiertos y guardarlos",
        "afilar los cuchillos de mesa", "colocar cucharas de postre para los invitados",
        "contar los cubiertos antes del evento", "comprar cubiertos de bambú en la tienda ecológica",
        "guardar la cubertería buena en el aparador", "lavar los cubiertos de madera a mano",
        "envolver cubiertos en servilletas para el bufé", "comprar cubiertos para niños para el bebé",
        "conseguir cubiertos para el nuevo departamento", "sacar los tenedores de pastel para el postre",
        "pedir un nuevo juego de cuchillos para carne", "envolver la cubertería como regalo",
        "comprar cucharitas que hacen falta", "clasificar los cubiertos por tamaño",
        "meter los cubiertos de pícnic en la mochila", "pedir cubiertos en el restaurante",
        "pedir cubiertos nuevos para el comedor", "ordenar los tenedores en la cesta",
        "preparar cucharas para la sopa",
        "cubeirtos para el pícnic preparar", "cuberteria pulir antes de los invitados",
        "tenedores y cuchilols del cajón", "cubietos después de cenar lavar",
    ],
)

# ═══════════════════════════════════════════════════════════════════════════
# 4. van-shuttle
# ═══════════════════════════════════════════════════════════════════════════
process("van-shuttle",
    rm_ru={32, 33, 34, 35, 36, 37},
    new_en=[
        "shuttle bus", "airport transfer", "passenger van", "minivan shuttle",
        "transit van", "commuter shuttle", "hotel shuttle",
        "book the airport shuttle for tomorrow morning", "check the shuttle bus schedule to downtown",
        "reserve a van for the group trip", "call the hotel shuttle service",
        "pick everyone up in the shuttle van", "schedule the office shuttle for Monday",
        "confirm the airport shuttle pickup time", "wait for the shuttle at the terminal",
        "find a shuttle from the cruise port", "hire a shuttle van for the wedding guests",
        "check if the shuttle runs on weekends", "pay for the shuttle ride to the airport",
        "track the shuttle bus on the app", "request a wheelchair-accessible shuttle",
        "drop off the rental van at the lot", "take the shuttle to the parking lot",
        "split the shuttle fare with the team", "ask about the free hotel shuttle",
        "look up shuttle times for the theme park", "load the luggage into the shuttle van",
        "tip the shuttle driver after the ride",
        "airprt shuttle booking", "shutle van for the group", "van shuutle schedule",
    ],
    new_ru=[
        "шаттл-автобус", "трансфер в аэропорт", "пассажирский фургон",
        "маршрутный минивэн", "корпоративный шаттл", "отельный трансфер",
        "заказать трансфер в аэропорт на завтра", "посмотреть расписание шаттла в центр города",
        "забронировать фургон для групповой поездки", "позвонить в службу трансфера отеля",
        "забрать всех на шаттле", "запланировать офисный шаттл на понедельник",
        "подтвердить время подачи шаттла в аэропорт", "ждать шаттл у терминала",
        "найти трансфер от круизного порта", "арендовать шаттл для гостей свадьбы",
        "уточнить ходит ли шаттл по выходным", "оплатить поездку на шаттле в аэропорт",
        "отследить шаттл-автобус", "запросить шаттл с доступом для колясок",
        "вернуть арендованный фургон на парковку", "доехать на шаттле до парковки",
        "разделить стоимость шаттла с командой", "узнать про бесплатный трансфер отеля",
        "найти расписание шаттла в парк развлечений", "загрузить багаж в шаттл",
        "оставить чаевые водителю шаттла",
        "трансфер в аэрпорт забронировать", "шаттл для групы", "расписание шатла уточнить",
    ],
    new_de=[
        "Shuttlebus", "Flughafentransfer", "Kleinbus", "Passagiervan",
        "Minibusse", "Pendelbus", "Hotelshuttle", "Transferbus",
        "Gruppentransfer", "Reisebus Shuttle", "Elektro-Shuttle",
        "barrierefreier Shuttle", "Firmen-Shuttle", "Stadion-Shuttle",
        "Veranstaltungs-Shuttle", "Kreuzfahrt-Shuttle", "Flughafen-Shuttle", "Mietwagen Van",
        "Flughafenshuttle für morgen früh buchen", "Shuttlebus-Fahrplan in die Innenstadt prüfen",
        "einen Van für den Gruppenausflug reservieren", "den Hotelshuttle-Service anrufen",
        "alle mit dem Shuttle abholen", "den Büro-Shuttle für Montag planen",
        "die Abholzeit des Flughafenshuttles bestätigen", "am Terminal auf den Shuttle warten",
        "einen Shuttle vom Kreuzfahrthafen finden", "Shuttle für die Hochzeitsgäste mieten",
        "prüfen ob der Shuttle am Wochenende fährt", "die Shuttlefahrt zum Flughafen bezahlen",
        "den Shuttlebus in der App verfolgen", "einen barrierefreien Shuttle anfordern",
        "den Mietwagen am Parkplatz abgeben", "mit dem Shuttle zum Parkplatz fahren",
        "die Shuttlekosten mit dem Team teilen", "nach dem kostenlosen Hotelshuttle fragen",
        "Shuttlezeiten für den Freizeitpark nachschauen", "das Gepäck in den Shuttle laden",
        "dem Shuttlefahrer Trinkgeld geben", "den Gruppenbus für die Konferenz bestellen",
        "Transfer vom Bahnhof zum Hotel organisieren", "Shuttle-Route zur Messe herausfinden",
        "Firmenshuttle-Fahrkarte besorgen", "Reisegruppe im Minibus zum Museum bringen",
        "pünktlich am Shuttlestopp sein", "den nächsten Shuttle nach Ankunft nehmen",
        "Kindersitze im Shuttle anfragen", "Abendshuttle zum Konzert buchen",
        "den Rückfahrt-Shuttle reservieren", "Shuttle nach dem Spiel zum Parkplatz nehmen",
        "Flughafnshuttle buchen", "Shuttlebus Fahrpaln prüfen", "Gruppentransfr reservieren",
    ],
    new_ja=[
        "シャトルバス", "空港送迎", "送迎バン", "ミニバス", "乗合バス",
        "通勤シャトル", "ホテル送迎", "送迎サービス", "グループ送迎",
        "電動シャトル", "バリアフリーシャトル", "イベントシャトル",
        "クルーズ港シャトル", "駐車場シャトル", "テーマパークシャトル",
        "結婚式送迎", "空港トランスファー", "レンタルバン",
        "明日の朝の空港シャトルを予約する", "ダウンタウン行きシャトルの時刻表を確認する",
        "グループ旅行用のバンを予約する", "ホテルの送迎サービスに電話する",
        "シャトルバンで全員を迎えに行く", "月曜日のオフィスシャトルを手配する",
        "空港シャトルのピックアップ時間を確認する", "ターミナルでシャトルを待つ",
        "クルーズ港からのシャトルを探す", "結婚式のゲスト用にシャトルバンを手配する",
        "週末にシャトルが運行しているか確認する", "空港までのシャトル料金を支払う",
        "アプリでシャトルバスを追跡する", "車椅子対応のシャトルをリクエストする",
        "レンタルバンを駐車場に返す", "シャトルで駐車場まで行く",
        "チームでシャトル代を割り勘にする", "ホテルの無料送迎について聞く",
        "テーマパーク行きシャトルの時間を調べる", "シャトルバンに荷物を積む",
        "シャトルの運転手にチップを渡す", "会議用のグループバスを予約する",
        "駅からホテルへの送迎を手配する", "展示会行きシャトルのルートを調べる",
        "会社シャトルの乗車券を取る", "ミニバスで博物館にグループを連れていく",
        "シャトル乗り場に時間通りに行く", "到着後に次のシャトルに乗る",
        "シャトルでチャイルドシートを頼む", "コンサート行き夜のシャトルを予約する",
        "帰りのシャトルを予約する", "試合後に駐車場行きシャトルに乗る",
        "空港シャトルを予約すr", "シャトルバスの時刻表をかくにんする", "グループ送迎を予やくする",
    ],
    new_fr=[
        "navette", "transfert aéroport", "minibus", "van passagers",
        "bus navette", "navette hôtel", "navette entreprise", "transfert",
        "navette groupe", "navette électrique", "navette accessible",
        "navette événement", "navette croisière", "navette parking",
        "navette parc", "navette mariage", "navette aéroport", "van de location",
        "réserver la navette aéroport pour demain matin",
        "vérifier les horaires de la navette vers le centre-ville",
        "réserver un van pour la sortie de groupe", "appeler le service de navette de l'hôtel",
        "récupérer tout le monde avec la navette", "planifier la navette du bureau pour lundi",
        "confirmer l'heure de la navette aéroport", "attendre la navette au terminal",
        "trouver une navette depuis le port de croisière",
        "louer une navette pour les invités du mariage",
        "vérifier si la navette circule le week-end", "payer le trajet en navette vers l'aéroport",
        "suivre la navette sur l'application",
        "demander une navette accessible aux fauteuils roulants",
        "rendre le van de location au parking", "prendre la navette jusqu'au parking",
        "partager le coût de la navette avec l'équipe",
        "se renseigner sur la navette gratuite de l'hôtel",
        "consulter les horaires de la navette du parc", "charger les bagages dans la navette",
        "laisser un pourboire au chauffeur de la navette",
        "réserver un bus pour le groupe de la conférence",
        "organiser le transfert de la gare à l'hôtel",
        "navettte aéroport réserver", "horaires navete vérifier", "transert groupe réserver",
    ],
    new_es=[
        "servicio de transporte", "traslado aeropuerto", "furgoneta de pasajeros",
        "minibús", "autobús lanzadera", "shuttle hotel", "transporte corporativo",
        "traslado", "transporte grupal", "shuttle eléctrico", "transporte accesible",
        "shuttle de evento", "shuttle de crucero", "shuttle de estacionamiento",
        "shuttle de parque temático", "transporte de boda", "transfer aeropuerto", "van de alquiler",
        "reservar el shuttle del aeropuerto para mañana temprano",
        "revisar los horarios del shuttle al centro", "reservar una van para el viaje grupal",
        "llamar al servicio de shuttle del hotel", "recoger a todos en la van del shuttle",
        "programar el shuttle de la oficina para el lunes",
        "confirmar la hora del shuttle al aeropuerto", "esperar el shuttle en la terminal",
        "buscar un shuttle desde el puerto de cruceros",
        "contratar un shuttle para los invitados de la boda",
        "verificar si el shuttle funciona los fines de semana",
        "pagar el viaje en shuttle al aeropuerto", "rastrear el shuttle en la aplicación",
        "solicitar un shuttle accesible para silla de ruedas",
        "devolver la van de alquiler al estacionamiento", "tomar el shuttle hasta el estacionamiento",
        "dividir el costo del shuttle con el equipo", "preguntar por el shuttle gratuito del hotel",
        "buscar los horarios del shuttle al parque temático", "cargar el equipaje en el shuttle",
        "darle propina al conductor del shuttle", "reservar un autobús para el grupo de la conferencia",
        "organizar el traslado de la estación al hotel",
        "shutle del aeropuerto reservar", "horarios del shutle revisar", "trasaldo grupal reservar",
    ],
)

# ═══════════════════════════════════════════════════════════════════════════
# 5. vault
# ═══════════════════════════════════════════════════════════════════════════
process("vault",
    rm_ru={41, 42, 43, 44, 45, 46},
    new_en=[
        "safe deposit box", "strongbox", "security vault", "combination safe",
        "bank safe", "home safe", "fireproof vault",
        "put the jewelry in the vault before leaving", "change the vault combination code",
        "check the safe deposit box at the bank", "store the backup drives in the vault",
        "buy a fireproof safe for the house", "install a wall safe in the bedroom",
        "take the passports out of the vault", "rent a safe deposit box at the bank",
        "put the cash in the home safe tonight", "get the vault key from the manager",
        "insure the contents of the vault", "lock the documents in the office safe",
        "pick up a small safe from the hardware store", "remember the vault code before the trip",
        "move the safe to the new house", "ask the bank about vault access hours",
        "store the will in the bank vault", "hide the spare key in the safe",
        "vaul combination code", "sfe deposit box at the bank", "put valubles in the vault",
    ],
    new_ru=[
        "депозитная ячейка", "несгораемый шкаф", "кодовый сейф",
        "банковский сейф", "домашний сейф огнеупорный",
        "положить украшения в сейф перед уходом", "поменять код комбинации сейфа",
        "проверить депозитную ячейку в банке", "убрать резервные диски в хранилище",
        "купить огнеупорный сейф для дома", "установить настенный сейф в спальне",
        "достать паспорта из сейфа", "арендовать депозитную ячейку в банке",
        "положить наличные в домашний сейф вечером", "получить ключ от хранилища у менеджера",
        "застраховать содержимое сейфа", "запереть документы в офисном сейфе",
        "купить маленький сейф в строительном магазине", "запомнить код от сейфа перед поездкой",
        "перевезти сейф в новый дом", "узнать часы доступа к хранилищу в банке",
        "хранить завещание в банковском хранилище", "спрятать запасной ключ в сейфе",
        "сейф комбинция код поменять", "депозитная ячйка в банке", "убрать ценнсти в хранилище",
    ],
    new_de=[
        "Tresor", "Safe", "Banktresor", "Bankschließfach", "Panzerschrank",
        "Haustresor", "Wandtresor", "Möbeltresor", "Geldkassette", "Wertfach",
        "Schließfach", "feuerfester Tresor", "Dokumententresor", "Hotelsafe",
        "Bürosafe", "Zahlenschloss-Tresor", "Sicherheitsschrank", "Tresorraum",
        "den Schmuck vor dem Weggehen in den Tresor legen", "die Tresorkombination ändern",
        "das Bankschließfach überprüfen", "die Backup-Festplatten im Tresor aufbewahren",
        "einen feuerfesten Safe für das Haus kaufen", "einen Wandtresor im Schlafzimmer einbauen",
        "die Pässe aus dem Tresor nehmen", "ein Schließfach bei der Bank mieten",
        "das Bargeld heute Abend in den Haustresor legen", "den Tresorschlüssel vom Manager holen",
        "den Inhalt des Tresors versichern", "die Dokumente im Bürosafe einschließen",
        "einen kleinen Safe im Baumarkt kaufen", "den Tresorcode vor der Reise merken",
        "den Safe ins neue Haus umziehen", "bei der Bank nach Tresor-Öffnungszeiten fragen",
        "das Testament im Banktresor aufbewahren", "den Ersatzschlüssel im Safe verstecken",
        "Wertsachen über Nacht in den Hotelsafe legen", "den alten Tresor entsorgen lassen",
        "den Tresor an der Wand befestigen", "neuen Tresorcode programmieren",
        "wichtige Papiere im Panzerschrank verstauen", "Tresor-Batterie wechseln",
        "digitalen Safe mit Fingerabdruck einrichten",
        "Tresorinhalt für die Versicherung fotografieren",
        "Notfall-Tresorschlüssel beim Nachbarn hinterlegen", "Safe-Lieferung für Freitag planen",
        "den Banktresor vor dem Urlaub besuchen",
        "Trsor Kombination ändern", "Bankschliessfach überprfen",
        "Dokumnete im Safe einschließen", "feurfesten Tresor kaufen",
    ],
    new_ja=[
        "金庫", "貸金庫", "セーフティボックス", "銀行金庫", "家庭用金庫",
        "耐火金庫", "壁掛け金庫", "ダイヤル金庫", "オフィス金庫", "ホテル金庫",
        "セキュリティ金庫", "防犯金庫", "鍵付き金庫", "小型金庫", "暗証番号式金庫",
        "重要書類保管庫", "金庫室", "宝石保管庫",
        "出かける前に宝石を金庫に入れる", "金庫のダイヤル番号を変更する",
        "銀行の貸金庫を確認する", "バックアップドライブを金庫に保管する",
        "家用の耐火金庫を買う", "寝室に壁掛け金庫を取り付ける",
        "金庫からパスポートを取り出す", "銀行で貸金庫を借りる",
        "今夜現金を家庭用金庫に入れる", "マネージャーから金庫の鍵をもらう",
        "金庫の中身に保険をかける", "オフィスの金庫に書類を閉じ込める",
        "ホームセンターで小さな金庫を買う", "旅行前に金庫の暗証番号を覚える",
        "金庫を新しい家に引っ越す", "銀行に金庫のアクセス時間を聞く",
        "遺言書を銀行の金庫に保管する", "予備の鍵を金庫に隠す",
        "ホテルの金庫に貴重品を入れる", "古い金庫を処分する",
        "金庫を壁に固定する", "新しい金庫の暗証番号を設定する",
        "重要書類を金庫にしまう", "金庫の電池を交換する",
        "指紋認証金庫を設定する", "保険用に金庫の中身を撮影する",
        "緊急用の金庫の鍵を隣人に預ける", "金曜日に金庫の配達を手配する",
        "休暇前に銀行の金庫を訪問する", "金庫のダイヤルを変更する",
        "きんこのダイヤル番号を変更する", "銀行の貸金こを確認する",
        "書類をきんこに入れる", "耐火きんこを買う",
    ],
    new_fr=[
        "coffre-fort", "coffre de banque", "coffre mural", "coffre", "chambre forte",
        "coffre-fort domestique", "coffre ignifuge", "coffre à combinaison",
        "coffre de bureau", "coffre d'hôtel", "coffre de sécurité",
        "coffret de sûreté", "petit coffre-fort", "coffre-fort numérique",
        "coffre-fort à empreinte", "coffre de documents", "coffre-fort blindé", "boîte de dépôt",
        "mettre les bijoux dans le coffre avant de partir", "changer la combinaison du coffre-fort",
        "vérifier le coffre de dépôt à la banque", "stocker les disques de sauvegarde dans le coffre",
        "acheter un coffre-fort ignifuge pour la maison", "installer un coffre mural dans la chambre",
        "sortir les passeports du coffre", "louer un coffre à la banque",
        "mettre l'argent liquide dans le coffre ce soir",
        "récupérer la clé du coffre chez le directeur", "assurer le contenu du coffre-fort",
        "enfermer les documents dans le coffre du bureau",
        "acheter un petit coffre à la quincaillerie", "retenir le code du coffre avant le voyage",
        "déménager le coffre-fort dans la nouvelle maison",
        "demander les heures d'accès au coffre à la banque",
        "garder le testament dans le coffre bancaire", "cacher la clé de secours dans le coffre",
        "mettre les objets de valeur dans le coffre de l'hôtel",
        "faire enlever l'ancien coffre-fort", "fixer le coffre au mur",
        "programmer le nouveau code du coffre", "ranger les papiers importants dans le coffre",
        "changer la pile du coffre-fort", "configurer le coffre à empreinte digitale",
        "photographier le contenu du coffre pour l'assurance",
        "laisser la clé de secours du coffre chez le voisin",
        "planifier la livraison du coffre pour vendredi", "visiter le coffre bancaire avant les vacances",
        "coffr-fort combinaison changer", "coffre de banqu vérifier",
        "documnts dans le coffre enfermer", "coffre-fort ignifuge achter",
    ],
    new_es=[
        "caja fuerte", "bóveda", "caja de seguridad", "caja fuerte de banco",
        "caja fuerte doméstica", "caja fuerte ignífuga", "caja fuerte de pared",
        "caja fuerte de combinación", "caja fuerte de oficina", "caja de hotel",
        "caja fuerte digital", "caja fuerte blindada", "caja fuerte pequeña",
        "caja fuerte de documentos", "caja fuerte con huella", "caja de depósito",
        "bóveda bancaria", "caja de valores",
        "guardar las joyas en la caja fuerte antes de salir", "cambiar la combinación de la caja fuerte",
        "revisar la caja de depósito en el banco", "guardar los discos de respaldo en la bóveda",
        "comprar una caja fuerte ignífuga para la casa",
        "instalar una caja fuerte de pared en la habitación",
        "sacar los pasaportes de la caja fuerte", "rentar una caja de seguridad en el banco",
        "poner el efectivo en la caja fuerte esta noche",
        "conseguir la llave de la bóveda con el gerente", "asegurar el contenido de la caja fuerte",
        "guardar los documentos en la caja fuerte de la oficina",
        "comprar una caja fuerte pequeña en la ferretería",
        "recordar el código de la caja fuerte antes del viaje",
        "mudar la caja fuerte a la casa nueva", "preguntar en el banco por los horarios de la bóveda",
        "guardar el testamento en la bóveda del banco",
        "esconder la llave de repuesto en la caja fuerte",
        "poner los objetos de valor en la caja del hotel", "deshacerse de la caja fuerte vieja",
        "fijar la caja fuerte a la pared", "programar el nuevo código de la caja fuerte",
        "guardar papeles importantes en la caja fuerte", "cambiar la pila de la caja fuerte",
        "configurar la caja fuerte con huella digital",
        "fotografiar el contenido de la caja fuerte para el seguro",
        "dejar la llave de emergencia con el vecino",
        "programar la entrega de la caja fuerte para el viernes",
        "visitar la bóveda del banco antes de las vacaciones",
        "caja fuert combinación cambiar", "cja de depósito en el banco",
        "documentos en la caja fuerte guaradr", "caja fuerte ignifuga comprar",
    ],
)

print("\n== Icons 1-5 done. Run gen_icons_task_002b.py for 6-10. ==")
