#!/usr/bin/env python3
"""Task-003 part A: pen, pencil, people, person-hiking."""

from gen_icons_task_006_common import build_icon

# ── PEN ──────────────────────────────────────────────────────────────────────
build_icon("pen", {
    "en": [
        # keywords (~18)
        "ballpoint", "pen", "write", "writing", "edit",
        "ballpoint pen", "ink pen", "gel pen", "felt-tip pen",
        "sign a document", "write a letter", "handwriting",
        "pen refill", "blue pen", "black pen", "red pen",
        "pen cap", "pen case",
        # task phrases (~37)
        "buy a new pen from the store",
        "pick up pens for the office",
        "write a thank-you note with a pen",
        "sign the contract with a ballpoint pen",
        "edit the draft with a red pen",
        "write down the address with a pen",
        "fill out the form with a pen",
        "lend my pen to a coworker",
        "return the borrowed pen",
        "replace the pen ink cartridge",
        "write a birthday card by hand",
        "pack a pen in my bag for the meeting",
        "find a working pen for the signature",
        "leave a pen on the desk for notes",
        "grab a pen and write this down",
        "keep a pen handy for quick notes",
        "clip the pen to my notebook",
        "take notes with a pen during the lecture",
        "mark the important sections with a pen",
        "write the grocery list with a pen",
        "add a pen to the school supplies list",
        "get a new pen set as a gift",
        "order pen refills online",
        "throw away the dried-out pen",
        "test the pen before buying it",
        "write my journal entry with a pen",
        "put the pen back in the holder",
        "bring a pen to the exam",
        "sign the check with a pen",
        "use a pen to jot down ideas",
        "hand the pen to the customer to sign",
        "write feedback on the paper with a pen",
        "annotate the printout with a pen",
        "underline key points with a pen",
        "label the box with a pen",
        "write the return address with a pen",
        "cap the pen after use",
        # typos (~5)
        "balppoint pen for signing",
        "wriet a letter by hand",
        "edti the document with a pen",
        "pne ink refill",
        "siign the form with a pen",
    ],
    "ru": [
        "ручка", "шариковая ручка", "писать", "письмо", "редактировать",
        "шариковая ручка для подписи", "гелевая ручка", "чернильная ручка",
        "подпись", "чёрная ручка", "синяя ручка", "красная ручка",
        "колпачок ручки", "пенал для ручек", "стержень для ручки",
        "написать письмо вручную", "заполнить бланк ручкой", "почерк",
        "купить новую ручку в магазине",
        "взять ручки для офиса",
        "написать благодарственную записку ручкой",
        "подписать контракт шариковой ручкой",
        "отредактировать черновик красной ручкой",
        "записать адрес ручкой",
        "заполнить форму ручкой",
        "одолжить ручку коллеге",
        "вернуть одолженную ручку",
        "заменить стержень в ручке",
        "написать поздравительную открытку от руки",
        "положить ручку в сумку на встречу",
        "найти рабочую ручку для подписи",
        "оставить ручку на столе для заметок",
        "взять ручку и записать это",
        "держать ручку под рукой для заметок",
        "прикрепить ручку к блокноту",
        "делать записи ручкой на лекции",
        "отметить важные разделы ручкой",
        "написать список продуктов ручкой",
        "добавить ручку в список школьных принадлежностей",
        "купить набор ручек в подарок",
        "заказать стержни для ручек онлайн",
        "выбросить высохшую ручку",
        "проверить ручку перед покупкой",
        "написать запись в дневнике ручкой",
        "положить ручку обратно в подставку",
        "принести ручку на экзамен",
        "подписать чек ручкой",
        "записать идеи ручкой",
        "передать ручку клиенту для подписи",
        "написать отзыв на бумаге ручкой",
        "подчеркнуть главное ручкой",
        "подписать посылку ручкой",
        "написать обратный адрес ручкой",
        "закрыть ручку колпачком после использования",
        "пометить коробку ручкой",
        "шарикоавя ручка для подписания",
        "наисать письмо от руки",
        "редакитровать документ ручкой",
        "стрежень для ручки",
        "подиспать форму ручкой",
    ],
    "de": [
        "Kugelschreiber", "Stift", "schreiben", "Schrift", "bearbeiten",
        "Kugelschreiber zum Unterschreiben", "Gelstift", "Tintenstift",
        "Unterschrift", "schwarzer Stift", "blauer Stift", "roter Stift",
        "Stiftkappe", "Stiftetui", "Stiftmine", "einen Brief schreiben",
        "Formular mit Stift ausfüllen", "Handschrift",
        "einen neuen Stift im Laden kaufen",
        "Stifte fürs Büro besorgen",
        "einen Dankesbrief mit dem Stift schreiben",
        "den Vertrag mit dem Kugelschreiber unterschreiben",
        "den Entwurf mit einem roten Stift korrigieren",
        "die Adresse mit einem Stift aufschreiben",
        "das Formular mit einem Stift ausfüllen",
        "meinem Kollegen einen Stift leihen",
        "den geliehenen Stift zurückgeben",
        "die Mine im Stift austauschen",
        "eine Geburtstagskarte von Hand schreiben",
        "einen Stift für das Meeting einpacken",
        "einen funktionierenden Stift zum Unterschreiben finden",
        "einen Stift auf dem Schreibtisch lassen",
        "einen Stift nehmen und das notieren",
        "immer einen Stift griffbereit haben",
        "den Stift am Notizbuch befestigen",
        "Notizen mit dem Stift in der Vorlesung machen",
        "wichtige Abschnitte mit dem Stift markieren",
        "die Einkaufsliste mit einem Stift schreiben",
        "einen Stift zur Schulliste hinzufügen",
        "ein Stifteset als Geschenk kaufen",
        "Stiftminen online bestellen",
        "den eingetrockneten Stift wegwerfen",
        "den Stift vor dem Kauf testen",
        "meinen Tagebucheintrag mit dem Stift schreiben",
        "den Stift zurück in die Halterung legen",
        "einen Stift zur Prüfung mitbringen",
        "den Scheck mit einem Stift unterschreiben",
        "Ideen mit dem Stift notieren",
        "dem Kunden den Stift zum Unterschreiben geben",
        "Feedback auf dem Papier mit Stift schreiben",
        "wichtige Stellen mit dem Stift unterstreichen",
        "die Kiste mit einem Stift beschriften",
        "die Absenderadresse mit dem Stift schreiben",
        "den Stift nach Gebrauch zudeckeln",
        "den Ausdruck mit dem Stift kommentieren",
        "Kugelschreibre zum Unterschreiben",
        "schrieben mit dem Stift",
        "Stfit für die Schule kaufen",
        "den Vertarg unterschreiben",
        "Stift Mien austauschen",
    ],
    "ja": [
        "ボールペン", "ペン", "書く", "筆記", "編集",
        "署名用ペン", "ゲルペン", "インクペン",
        "署名", "黒ペン", "青ペン", "赤ペン",
        "ペンキャップ", "ペンケース", "ペンの替え芯", "手紙を書く",
        "ペンで用紙に記入する", "手書き",
        "お店で新しいペンを買う",
        "オフィス用にペンを用意する",
        "ペンでお礼の手紙を書く",
        "ボールペンで契約書にサインする",
        "赤ペンで下書きを修正する",
        "ペンで住所を書き留める",
        "ペンで申請書に記入する",
        "同僚にペンを貸す",
        "借りたペンを返す",
        "ペンの替え芯を交換する",
        "手書きで誕生日カードを書く",
        "会議用にペンをカバンに入れる",
        "署名用の書けるペンを探す",
        "メモ用にデスクにペンを置く",
        "ペンを取ってこれを書き留める",
        "いつでもメモ用にペンを持っておく",
        "ペンをノートに挟む",
        "講義中にペンでノートを取る",
        "ペンで重要な部分に印をつける",
        "ペンで買い物リストを書く",
        "学用品リストにペンを追加する",
        "プレゼント用にペンセットを買う",
        "ペンの替え芯をオンラインで注文する",
        "インクの出ないペンを捨てる",
        "購入前にペンを試し書きする",
        "ペンで日記を書く",
        "ペンをペン立てに戻す",
        "試験にペンを持っていく",
        "ペンで小切手にサインする",
        "ペンでアイデアをメモする",
        "お客様にサイン用のペンを渡す",
        "ペンで用紙にフィードバックを書く",
        "ペンで重要な箇所に下線を引く",
        "ペンで箱にラベルを書く",
        "ペンで差出人住所を書く",
        "使用後にペンにキャップをする",
        "ペンで印刷物に注釈を入れる",
        "ボールぺンで署名する",
        "てがみを書く",
        "ぺンのインクを替える",
        "しょめい用のペン",
        "ペンを買てくる",
    ],
    "fr": [
        "stylo", "stylo bille", "écrire", "écriture", "modifier",
        "stylo pour signer", "stylo gel", "stylo encre",
        "signature", "stylo noir", "stylo bleu", "stylo rouge",
        "capuchon du stylo", "trousse à stylos", "recharge de stylo",
        "écrire une lettre", "remplir un formulaire au stylo", "écriture manuscrite",
        "acheter un nouveau stylo au magasin",
        "prendre des stylos pour le bureau",
        "écrire un mot de remerciement au stylo",
        "signer le contrat avec un stylo bille",
        "corriger le brouillon avec un stylo rouge",
        "noter l'adresse avec un stylo",
        "remplir le formulaire au stylo",
        "prêter mon stylo à un collègue",
        "rendre le stylo emprunté",
        "remplacer la cartouche du stylo",
        "écrire une carte d'anniversaire à la main",
        "mettre un stylo dans mon sac pour la réunion",
        "trouver un stylo qui marche pour signer",
        "laisser un stylo sur le bureau pour les notes",
        "prendre un stylo et noter cela",
        "garder un stylo à portée de main",
        "attacher le stylo au carnet",
        "prendre des notes au stylo pendant le cours",
        "marquer les passages importants au stylo",
        "écrire la liste de courses au stylo",
        "ajouter un stylo à la liste de fournitures",
        "acheter un coffret de stylos en cadeau",
        "commander des recharges de stylo en ligne",
        "jeter le stylo qui ne marche plus",
        "tester le stylo avant de l'acheter",
        "écrire mon journal intime au stylo",
        "remettre le stylo dans son support",
        "apporter un stylo à l'examen",
        "signer le chèque avec un stylo",
        "noter des idées avec un stylo",
        "donner le stylo au client pour signer",
        "écrire un commentaire au stylo sur le papier",
        "souligner les points clés au stylo",
        "étiqueter la boîte avec un stylo",
        "écrire l'adresse de retour au stylo",
        "remettre le capuchon du stylo après usage",
        "annoter le document imprimé au stylo",
        "stylo bille pour siniger",
        "écrrie une lettre à la main",
        "modifer le document au stylo",
        "rechagre de stylo",
        "siganer le formulaire au stylo",
    ],
    "es": [
        "bolígrafo", "pluma", "escribir", "escritura", "editar",
        "bolígrafo para firmar", "bolígrafo de gel", "pluma de tinta",
        "firma", "bolígrafo negro", "bolígrafo azul", "bolígrafo rojo",
        "tapa del bolígrafo", "estuche de bolígrafos", "recambio de bolígrafo",
        "escribir una carta", "llenar un formulario con bolígrafo", "caligrafía",
        "comprar un bolígrafo nuevo en la tienda",
        "conseguir bolígrafos para la oficina",
        "escribir una nota de agradecimiento con bolígrafo",
        "firmar el contrato con un bolígrafo",
        "corregir el borrador con un bolígrafo rojo",
        "apuntar la dirección con un bolígrafo",
        "rellenar el formulario con un bolígrafo",
        "prestarle mi bolígrafo a un compañero",
        "devolver el bolígrafo prestado",
        "cambiar la carga del bolígrafo",
        "escribir una tarjeta de cumpleaños a mano",
        "meter un bolígrafo en la bolsa para la reunión",
        "encontrar un bolígrafo que funcione para firmar",
        "dejar un bolígrafo en el escritorio para notas",
        "tomar un bolígrafo y anotar esto",
        "tener un bolígrafo a la mano para notas rápidas",
        "sujetar el bolígrafo al cuaderno",
        "tomar apuntes con bolígrafo durante la clase",
        "marcar las secciones importantes con bolígrafo",
        "escribir la lista de compras con un bolígrafo",
        "agregar un bolígrafo a la lista de útiles escolares",
        "comprar un set de bolígrafos como regalo",
        "pedir recambios de bolígrafo en línea",
        "tirar el bolígrafo que ya no sirve",
        "probar el bolígrafo antes de comprarlo",
        "escribir en mi diario con un bolígrafo",
        "poner el bolígrafo de vuelta en el portalápices",
        "llevar un bolígrafo al examen",
        "firmar el cheque con un bolígrafo",
        "anotar ideas con un bolígrafo",
        "darle el bolígrafo al cliente para que firme",
        "escribir comentarios en el papel con bolígrafo",
        "subrayar los puntos clave con un bolígrafo",
        "etiquetar la caja con un bolígrafo",
        "escribir la dirección de remitente con bolígrafo",
        "tapar el bolígrafo después de usarlo",
        "anotar en el documento impreso con bolígrafo",
        "boligrafo para firmra",
        "escirbir una carta a mano",
        "editr el documento con bolígrafo",
        "recmabio de bolígrafo",
        "firmar el fromulario con bolígrafo",
    ],
})


# ── PENCIL ───────────────────────────────────────────────────────────────────
build_icon("pencil", {
    "en": [
        "pencil", "lead", "draw", "design", "edit", "write", "update",
        "graphite pencil", "mechanical pencil", "colored pencil",
        "pencil sharpener", "number two pencil", "drawing pencil",
        "sketch with pencil", "pencil eraser", "drafting pencil",
        "pencil lead", "pencil set",
        "sharpen the pencil before class",
        "buy a new pack of pencils for school",
        "draw a rough sketch with a pencil",
        "sketch the floor plan with a pencil",
        "write the answer in pencil",
        "erase the pencil marks on the paper",
        "bring pencils to the art class",
        "draw freehand lines on the canvas",
        "design a layout with a pencil sketch",
        "rough pencil design on graph paper",
        "edit a text field by tapping the pencil",
        "modify an entry by clicking the pencil",
        "modify existing data in the form",
        "update a record by tapping the pencil",
        "update your profile with the edit pencil",
        "write notes by hand with a pencil",
        "write in a sketchbook with a sharpened pencil",
        "add pencils to the supply list",
        "replace the broken pencil lead",
        "take the drawing test with a pencil",
        "shade the drawing with a soft pencil",
        "outline the design in pencil first",
        "mark the measurements with a pencil",
        "label the diagram with a pencil",
        "fill in the bubble sheet with a pencil",
        "keep a pencil in my desk drawer",
        "lend a pencil to a classmate",
        "return the borrowed pencil",
        "pack extra pencils for the exam",
        "use a pencil for the crossword puzzle",
        "draw a portrait with a graphite pencil",
        "draft the blueprint with a pencil",
        "write the math homework in pencil",
        "circle the correct answer with a pencil",
        "underline the key terms in pencil",
        "doodle with a pencil during the meeting",
        "trace the pattern with a pencil",
        "pencial for drawing",
        "pencl sketch on paper",
        "pencli icon for editing",
        "penci drawing on paper",
        "sharppen the pencil",
    ],
    "ru": [
        "карандаш", "грифель", "рисовать", "дизайн", "редактировать",
        "писать", "обновить", "графитовый карандаш", "механический карандаш",
        "цветной карандаш", "точилка для карандашей", "простой карандаш",
        "карандаш для рисования", "набросок карандашом", "ластик на карандаше",
        "чертёжный карандаш", "грифель карандаша", "набор карандашей",
        "заточить карандаш перед уроком",
        "купить новую пачку карандашей в школу",
        "нарисовать черновой набросок карандашом",
        "начертить план этажа карандашом",
        "написать ответ карандашом",
        "стереть карандашные отметки на бумаге",
        "принести карандаши на урок рисования",
        "рисовать от руки линии на холсте",
        "сделать макет карандашным наброском",
        "черновой эскиз карандашом на миллиметровке",
        "изменить запись нажатием на карандаш",
        "изменить существующие данные в форме",
        "обновить запись через карандаш",
        "писать заметки от руки карандашом",
        "писать в скетчбуке остро заточенным карандашом",
        "добавить карандаши в список принадлежностей",
        "заменить сломанный грифель карандаша",
        "сдать тест по рисованию карандашом",
        "заштриховать рисунок мягким карандашом",
        "обвести контур дизайна карандашом",
        "отметить размеры карандашом",
        "подписать схему карандашом",
        "заполнить бланк ответов карандашом",
        "держать карандаш в ящике стола",
        "одолжить карандаш однокласснику",
        "вернуть одолженный карандаш",
        "взять запасные карандаши на экзамен",
        "разгадывать кроссворд карандашом",
        "нарисовать портрет графитовым карандашом",
        "начертить чертёж карандашом",
        "написать домашку по математике карандашом",
        "обвести правильный ответ карандашом",
        "подчеркнуть ключевые термины карандашом",
        "рисовать каракули карандашом на встрече",
        "обвести шаблон карандашом",
        "нарисовать быстрый скетч карандашом",
        "редактировать поле текста через карандаш",
        "карандаш для рисованя",
        "карандашный набрсок на бумаге",
        "иконка карандша для редактирования",
        "рисунк карандашом на бумаге",
        "заточтиь карандаш",
    ],
    "de": [
        "Bleistift", "Mine", "zeichnen", "Design", "bearbeiten",
        "schreiben", "aktualisieren", "Graphitstift", "Druckbleistift",
        "Buntstift", "Bleistiftspitzer", "Schulbleistift",
        "Zeichenbleistift", "Bleistiftskizze", "Radiergummi am Bleistift",
        "technischer Zeichenstift", "Bleistiftmine", "Bleistiftset",
        "den Bleistift vor dem Unterricht spitzen",
        "eine neue Packung Bleistifte für die Schule kaufen",
        "eine grobe Skizze mit dem Bleistift zeichnen",
        "den Grundriss mit einem Bleistift skizzieren",
        "die Antwort mit Bleistift schreiben",
        "die Bleistiftspuren auf dem Papier radieren",
        "Bleistifte zum Kunstunterricht mitbringen",
        "freihändig Linien auf die Leinwand zeichnen",
        "ein Layout mit einer Bleistiftskizze entwerfen",
        "eine grobe Bleistiftskizze auf Millimeterpapier",
        "einen Eintrag durch Tippen auf den Bleistift ändern",
        "vorhandene Daten im Formular ändern",
        "einen Datensatz mit dem Bleistift aktualisieren",
        "Notizen mit dem Bleistift von Hand schreiben",
        "in ein Skizzenbuch mit einem gespitzten Bleistift schreiben",
        "Bleistifte zur Einkaufsliste hinzufügen",
        "die gebrochene Bleistiftmine ersetzen",
        "die Zeichenprüfung mit Bleistift ablegen",
        "die Zeichnung mit einem weichen Bleistift schattieren",
        "den Designentwurf zuerst in Bleistift umreißen",
        "die Maße mit einem Bleistift markieren",
        "das Diagramm mit einem Bleistift beschriften",
        "den Antwortbogen mit Bleistift ausfüllen",
        "einen Bleistift in der Schreibtischschublade haben",
        "einem Mitschüler einen Bleistift leihen",
        "den geliehenen Bleistift zurückgeben",
        "zusätzliche Bleistifte für die Prüfung einpacken",
        "das Kreuzworträtsel mit einem Bleistift lösen",
        "ein Porträt mit einem Graphitstift zeichnen",
        "die Blaupause mit einem Bleistift entwerfen",
        "die Matheaufgaben mit Bleistift schreiben",
        "die richtige Antwort mit Bleistift einkreisen",
        "Schlüsselbegriffe mit Bleistift unterstreichen",
        "während der Besprechung mit dem Bleistift kritzeln",
        "das Muster mit einem Bleistift nachzeichnen",
        "eine schnelle Skizze mit dem Bleistift machen",
        "das Textfeld mit dem Bleistift bearbeiten",
        "Bleistitf zum Zeichnen",
        "Bleistfitskizze auf Papier",
        "Bleisitft für Bearbeitung",
        "Zeichnugn mit Bleistift",
        "Bleistfit spitzen",
    ],
    "ja": [
        "鉛筆", "芯", "描く", "デザイン", "編集",
        "書く", "更新", "黒鉛の鉛筆", "シャープペンシル",
        "色鉛筆", "鉛筆削り", "二番鉛筆",
        "画用鉛筆", "鉛筆スケッチ", "鉛筆の消しゴム",
        "製図用鉛筆", "鉛筆の芯", "鉛筆セット",
        "授業の前に鉛筆を削る",
        "学校用に新しい鉛筆を買う",
        "鉛筆でラフスケッチを描く",
        "鉛筆で間取り図を描く",
        "鉛筆で答えを書く",
        "紙の鉛筆の跡を消す",
        "美術の授業に鉛筆を持っていく",
        "キャンバスにフリーハンドで線を描く",
        "鉛筆スケッチでレイアウトをデザインする",
        "方眼紙に鉛筆でラフデザインを描く",
        "鉛筆をタップしてエントリを変更する",
        "フォームの既存データを修正する",
        "鉛筆をタップして記録を更新する",
        "鉛筆で手書きメモを取る",
        "削った鉛筆でスケッチブックに書く",
        "文房具リストに鉛筆を追加する",
        "折れた鉛筆の芯を交換する",
        "鉛筆でデッサンのテストを受ける",
        "柔らかい鉛筆で絵に陰影をつける",
        "まず鉛筆でデザインの輪郭を描く",
        "鉛筆で寸法を印する",
        "鉛筆で図にラベルをつける",
        "鉛筆でマークシートを塗りつぶす",
        "机の引き出しに鉛筆を入れておく",
        "クラスメートに鉛筆を貸す",
        "借りた鉛筆を返す",
        "試験に予備の鉛筆を持っていく",
        "鉛筆でクロスワードパズルを解く",
        "黒鉛鉛筆で肖像画を描く",
        "鉛筆で設計図を描く",
        "鉛筆で数学の宿題を書く",
        "鉛筆で正解を丸で囲む",
        "鉛筆で重要な用語に下線を引く",
        "会議中に鉛筆で落書きをする",
        "鉛筆でパターンをなぞる",
        "鉛筆で素早いスケッチを描く",
        "鉛筆でテキストフィールドを編集する",
        "えんぴつで絵を描く",
        "鉛筆のスケッチを描く",
        "えんぴつの芯を替える",
        "鉛筆を削てから書く",
        "鉛筆でデザンを描く",
    ],
    "fr": [
        "crayon", "mine", "dessiner", "design", "modifier",
        "écrire", "mettre à jour", "crayon graphite", "porte-mine",
        "crayon de couleur", "taille-crayon", "crayon de bois",
        "crayon à dessin", "croquis au crayon", "gomme du crayon",
        "crayon technique", "mine de crayon", "set de crayons",
        "tailler le crayon avant le cours",
        "acheter un nouveau paquet de crayons pour l'école",
        "faire un croquis rapide au crayon",
        "dessiner le plan au crayon",
        "écrire la réponse au crayon",
        "effacer les marques de crayon sur le papier",
        "apporter des crayons au cours de dessin",
        "dessiner des lignes à main levée sur la toile",
        "concevoir un agencement avec un croquis au crayon",
        "ébauche au crayon sur du papier millimétré",
        "modifier une entrée en appuyant sur le crayon",
        "modifier les données existantes dans le formulaire",
        "mettre à jour un enregistrement via le crayon",
        "écrire des notes à la main au crayon",
        "écrire dans un carnet de croquis avec un crayon taillé",
        "ajouter des crayons à la liste de fournitures",
        "remplacer la mine de crayon cassée",
        "passer le test de dessin au crayon",
        "ombrer le dessin avec un crayon tendre",
        "tracer le contour du design au crayon d'abord",
        "marquer les mesures au crayon",
        "étiqueter le diagramme au crayon",
        "remplir la grille de réponses au crayon",
        "garder un crayon dans le tiroir du bureau",
        "prêter un crayon à un camarade de classe",
        "rendre le crayon emprunté",
        "prendre des crayons de rechange pour l'examen",
        "faire les mots croisés au crayon",
        "dessiner un portrait au crayon graphite",
        "ébaucher le plan au crayon",
        "écrire les devoirs de maths au crayon",
        "entourer la bonne réponse au crayon",
        "souligner les termes clés au crayon",
        "gribouiller au crayon pendant la réunion",
        "tracer le patron au crayon",
        "dessiner un rapide croquis au crayon",
        "modifier le champ de texte avec le crayon",
        "crayon puor dessiner",
        "croqusi au crayon sur papier",
        "crayno pour modifier",
        "desisn au crayon",
        "tailelr le crayon",
    ],
    "es": [
        "lápiz", "mina", "dibujar", "diseño", "editar",
        "escribir", "actualizar", "lápiz de grafito", "portaminas",
        "lápiz de color", "sacapuntas", "lápiz escolar",
        "lápiz de dibujo", "boceto a lápiz", "borrador del lápiz",
        "lápiz técnico", "mina de lápiz", "set de lápices",
        "sacar punta al lápiz antes de clase",
        "comprar un paquete nuevo de lápices para la escuela",
        "hacer un boceto rápido con lápiz",
        "dibujar el plano con un lápiz",
        "escribir la respuesta con lápiz",
        "borrar las marcas de lápiz en el papel",
        "llevar lápices a la clase de arte",
        "dibujar líneas a mano alzada en el lienzo",
        "diseñar un layout con un boceto a lápiz",
        "boceto a lápiz en papel cuadriculado",
        "modificar una entrada tocando el lápiz",
        "modificar los datos existentes en el formulario",
        "actualizar un registro tocando el lápiz",
        "escribir notas a mano con un lápiz",
        "escribir en un cuaderno de bocetos con un lápiz afilado",
        "agregar lápices a la lista de útiles",
        "reemplazar la mina rota del lápiz",
        "hacer el examen de dibujo con lápiz",
        "sombrear el dibujo con un lápiz suave",
        "delinear el diseño primero a lápiz",
        "marcar las medidas con un lápiz",
        "etiquetar el diagrama con un lápiz",
        "rellenar la hoja de respuestas con lápiz",
        "tener un lápiz en el cajón del escritorio",
        "prestarle un lápiz a un compañero de clase",
        "devolver el lápiz prestado",
        "llevar lápices extra al examen",
        "hacer el crucigrama con un lápiz",
        "dibujar un retrato con lápiz de grafito",
        "hacer el plano con un lápiz",
        "escribir la tarea de matemáticas con lápiz",
        "encerrar en un círculo la respuesta correcta con lápiz",
        "subrayar los términos clave con lápiz",
        "garabatear con lápiz durante la reunión",
        "trazar el patrón con un lápiz",
        "hacer un boceto rápido a lápiz",
        "editar el campo de texto con el lápiz",
        "lapiz para dibuajr",
        "boceto a lapíz en papel",
        "lapíz para editr",
        "dibjuo con lápiz",
        "sacapuntsa del lápiz",
    ],
})


# ── PEOPLE ───────────────────────────────────────────────────────────────────
build_icon("people", {
    "en": [
        "crowd", "group", "team", "members", "users", "humans",
        "people", "team meeting", "group activity", "community",
        "teammates", "colleagues", "staff", "crew", "gathering",
        "social event", "group project", "team building",
        "organize a team meeting for Monday",
        "gather people for the group photo",
        "invite the team to the planning session",
        "schedule a meeting with team members",
        "add more people to the project group",
        "call the group together for a briefing",
        "split people into smaller teams",
        "assign team members to the new project",
        "send a group message to all members",
        "coordinate with the team on the deadline",
        "hire more people for the department",
        "bring the group together for a workshop",
        "meet with the team after lunch",
        "update the team about the schedule change",
        "plan a social event for the group",
        "set up a group chat for the team",
        "prepare a presentation for the team",
        "lead the group discussion today",
        "introduce new members to the team",
        "reserve a room for the team meeting",
        "collect feedback from the group",
        "celebrate the team achievement together",
        "collaborate with team members on the report",
        "join the group for the team outing",
        "recruit more people to volunteer",
        "divide the group into breakout rooms",
        "host a team lunch this Friday",
        "count how many people are coming",
        "notify all team members about the change",
        "get the group ready for the presentation",
        "walk to the meeting with my teammates",
        "work with the group on the proposal",
        "book a restaurant for the team dinner",
        "welcome new people to the community",
        "coordinate the group volunteer effort",
        "arrange seats for the group at the event",
        "check if all team members confirmed",
        "teem meeting on Monday",
        "gropu project discussion",
        "peolpe gathering for event",
        "memebers of the team",
        "schedul a group activity",
    ],
    "ru": [
        "толпа", "группа", "команда", "участники", "пользователи", "люди",
        "коллектив", "командное совещание", "групповая деятельность", "сообщество",
        "сокомандники", "коллеги", "персонал", "экипаж", "собрание",
        "социальное мероприятие", "групповой проект", "тимбилдинг",
        "организовать командное совещание на понедельник",
        "собрать людей для групповой фотографии",
        "пригласить команду на сессию планирования",
        "назначить встречу с участниками команды",
        "добавить больше людей в группу проекта",
        "созвать группу на брифинг",
        "разделить людей на маленькие команды",
        "назначить участников команды на новый проект",
        "отправить групповое сообщение всем участникам",
        "согласовать с командой по дедлайну",
        "нанять больше людей в отдел",
        "собрать группу на мастер-класс",
        "встретиться с командой после обеда",
        "сообщить команде об изменении расписания",
        "спланировать мероприятие для группы",
        "создать групповой чат для команды",
        "подготовить презентацию для команды",
        "провести групповое обсуждение сегодня",
        "представить новых участников команде",
        "забронировать комнату для совещания команды",
        "собрать обратную связь от группы",
        "отпраздновать достижение команды вместе",
        "работать с участниками команды над отчётом",
        "присоединиться к группе на командной вылазке",
        "набрать больше людей в волонтёры",
        "разделить группу на отдельные комнаты",
        "устроить командный обед в пятницу",
        "посчитать сколько людей придёт",
        "уведомить всех участников команды об изменении",
        "подготовить группу к презентации",
        "пойти на встречу вместе с сокомандниками",
        "работать с группой над предложением",
        "забронировать ресторан на командный ужин",
        "приветствовать новых людей в сообществе",
        "координировать групповую волонтёрскую работу",
        "расставить места для группы на мероприятии",
        "проверить подтвердили ли все участники команды",
        "командое совещание в понедельник",
        "груповой проект обсуждение",
        "люид собираются на мероприятие",
        "участнки команды",
        "назначть групповую активность",
    ],
    "de": [
        "Menge", "Gruppe", "Team", "Mitglieder", "Benutzer", "Menschen",
        "Kollektiv", "Teammeeting", "Gruppenaktivität", "Gemeinschaft",
        "Teamkollegen", "Kollegen", "Personal", "Crew", "Versammlung",
        "soziale Veranstaltung", "Gruppenprojekt", "Teambuilding",
        "ein Teammeeting für Montag organisieren",
        "Leute für das Gruppenfoto zusammenbringen",
        "das Team zur Planungssitzung einladen",
        "ein Meeting mit Teammitgliedern planen",
        "mehr Leute zur Projektgruppe hinzufügen",
        "die Gruppe zu einem Briefing zusammenrufen",
        "Leute in kleinere Teams aufteilen",
        "Teammitglieder dem neuen Projekt zuweisen",
        "eine Gruppennachricht an alle Mitglieder senden",
        "mit dem Team die Frist abstimmen",
        "mehr Leute für die Abteilung einstellen",
        "die Gruppe für einen Workshop zusammenbringen",
        "nach dem Mittagessen mit dem Team treffen",
        "das Team über die Planänderung informieren",
        "eine Veranstaltung für die Gruppe planen",
        "einen Gruppenchat für das Team einrichten",
        "eine Präsentation für das Team vorbereiten",
        "die Gruppendiskussion heute leiten",
        "neue Mitglieder dem Team vorstellen",
        "einen Raum für das Teammeeting reservieren",
        "Feedback von der Gruppe sammeln",
        "den Teamerfolg gemeinsam feiern",
        "mit Teammitgliedern am Bericht arbeiten",
        "zum Teamausflug mit der Gruppe gehen",
        "mehr Freiwillige rekrutieren",
        "die Gruppe in Breakout-Räume aufteilen",
        "ein Teamessen am Freitag veranstalten",
        "zählen wie viele Leute kommen",
        "alle Teammitglieder über die Änderung benachrichtigen",
        "die Gruppe für die Präsentation vorbereiten",
        "mit Teamkollegen zum Meeting gehen",
        "mit der Gruppe am Vorschlag arbeiten",
        "ein Restaurant für das Teamessen buchen",
        "neue Leute in der Gemeinschaft willkommen heißen",
        "die Gruppenfreiwilligenarbeit koordinieren",
        "Plätze für die Gruppe bei der Veranstaltung anordnen",
        "prüfen ob alle Teammitglieder bestätigt haben",
        "Teammeeitng am Montag",
        "Grupe Projekt Diskussion",
        "Menshcen sammeln sich",
        "Mitglider des Teams",
        "Gruppenaktivtät planen",
    ],
    "ja": [
        "群衆", "グループ", "チーム", "メンバー", "ユーザー", "人々",
        "集団", "チームミーティング", "グループ活動", "コミュニティ",
        "チームメイト", "同僚", "スタッフ", "クルー", "集まり",
        "社交イベント", "グループプロジェクト", "チームビルディング",
        "月曜日にチームミーティングを開く",
        "グループ写真のために人を集める",
        "計画セッションにチームを招待する",
        "チームメンバーと会議を予定する",
        "プロジェクトグループにもっと人を追加する",
        "ブリーフィングのためにグループを集める",
        "人をもっと小さなチームに分ける",
        "新しいプロジェクトにチームメンバーを割り当てる",
        "全メンバーにグループメッセージを送る",
        "締め切りについてチームと調整する",
        "部署にもっと人を採用する",
        "ワークショップのためにグループを集める",
        "昼食後にチームと会う",
        "スケジュール変更についてチームに報告する",
        "グループのための社交イベントを企画する",
        "チーム用のグループチャットを作る",
        "チーム向けにプレゼンを準備する",
        "今日のグループディスカッションを進行する",
        "新しいメンバーをチームに紹介する",
        "チームミーティング用の部屋を予約する",
        "グループからフィードバックを集める",
        "チームの成果をみんなで祝う",
        "チームメンバーとレポートを作成する",
        "チームのお出かけにグループで参加する",
        "ボランティアをもっと募集する",
        "グループを分科会に分ける",
        "金曜日にチームランチを開く",
        "何人来るか数える",
        "変更について全チームメンバーに通知する",
        "プレゼンに向けてグループを準備させる",
        "チームメイトと一緒に会議に行く",
        "グループで提案書に取り組む",
        "チームディナー用にレストランを予約する",
        "コミュニティに新しい人を歓迎する",
        "グループのボランティア活動を調整する",
        "イベントでグループの席を手配する",
        "全チームメンバーが確認したか確認する",
        "チームミーテイングを月曜日に",
        "グルーブプロジェクト討論",
        "ひとびとがイベントに集る",
        "メンバの確認をする",
        "グループかつどうを計画する",
    ],
    "fr": [
        "foule", "groupe", "équipe", "membres", "utilisateurs", "humains",
        "gens", "réunion d'équipe", "activité de groupe", "communauté",
        "coéquipiers", "collègues", "personnel", "équipage", "rassemblement",
        "événement social", "projet de groupe", "renforcement d'équipe",
        "organiser une réunion d'équipe pour lundi",
        "rassembler les gens pour la photo de groupe",
        "inviter l'équipe à la session de planification",
        "planifier une réunion avec les membres de l'équipe",
        "ajouter plus de personnes au groupe du projet",
        "appeler le groupe pour un briefing",
        "diviser les gens en petites équipes",
        "assigner des membres d'équipe au nouveau projet",
        "envoyer un message groupé à tous les membres",
        "se coordonner avec l'équipe sur la date limite",
        "embaucher plus de personnes pour le département",
        "rassembler le groupe pour un atelier",
        "retrouver l'équipe après le déjeuner",
        "informer l'équipe du changement de planning",
        "planifier un événement social pour le groupe",
        "créer un chat de groupe pour l'équipe",
        "préparer une présentation pour l'équipe",
        "animer la discussion de groupe aujourd'hui",
        "présenter les nouveaux membres à l'équipe",
        "réserver une salle pour la réunion d'équipe",
        "recueillir les avis du groupe",
        "célébrer la réussite de l'équipe ensemble",
        "collaborer avec les membres de l'équipe sur le rapport",
        "rejoindre le groupe pour la sortie d'équipe",
        "recruter plus de bénévoles",
        "diviser le groupe en sous-salles",
        "organiser un déjeuner d'équipe ce vendredi",
        "compter combien de personnes viennent",
        "prévenir tous les membres de l'équipe du changement",
        "préparer le groupe pour la présentation",
        "aller à la réunion avec mes coéquipiers",
        "travailler avec le groupe sur la proposition",
        "réserver un restaurant pour le dîner d'équipe",
        "accueillir les nouvelles personnes dans la communauté",
        "coordonner le bénévolat de groupe",
        "organiser les places pour le groupe à l'événement",
        "vérifier que tous les membres ont confirmé",
        "réuinon d'équipe lundi",
        "porjet de groupe discussion",
        "persnonnes rassemblement",
        "mebmres de l'équipe",
        "planfier une activité de groupe",
    ],
    "es": [
        "multitud", "grupo", "equipo", "miembros", "usuarios", "humanos",
        "gente", "reunión de equipo", "actividad grupal", "comunidad",
        "compañeros de equipo", "colegas", "personal", "tripulación", "reunión",
        "evento social", "proyecto grupal", "trabajo en equipo",
        "organizar una reunión de equipo para el lunes",
        "reunir a la gente para la foto grupal",
        "invitar al equipo a la sesión de planificación",
        "programar una reunión con los miembros del equipo",
        "agregar más personas al grupo del proyecto",
        "convocar al grupo para un briefing",
        "dividir a la gente en equipos más pequeños",
        "asignar miembros del equipo al nuevo proyecto",
        "enviar un mensaje grupal a todos los miembros",
        "coordinar con el equipo sobre la fecha límite",
        "contratar más personas para el departamento",
        "reunir al grupo para un taller",
        "reunirse con el equipo después del almuerzo",
        "informar al equipo sobre el cambio de horario",
        "planear un evento social para el grupo",
        "crear un chat grupal para el equipo",
        "preparar una presentación para el equipo",
        "dirigir la discusión grupal hoy",
        "presentar a los nuevos miembros al equipo",
        "reservar una sala para la reunión de equipo",
        "recoger opiniones del grupo",
        "celebrar el logro del equipo juntos",
        "colaborar con los miembros del equipo en el informe",
        "unirse al grupo para la salida del equipo",
        "reclutar más voluntarios",
        "dividir el grupo en salas separadas",
        "organizar un almuerzo de equipo este viernes",
        "contar cuántas personas van a venir",
        "notificar a todos los miembros del equipo del cambio",
        "preparar al grupo para la presentación",
        "ir a la reunión con mis compañeros de equipo",
        "trabajar con el grupo en la propuesta",
        "reservar un restaurante para la cena del equipo",
        "dar la bienvenida a nuevas personas en la comunidad",
        "coordinar el voluntariado del grupo",
        "organizar los asientos del grupo en el evento",
        "verificar que todos los miembros confirmaron",
        "reuinón de equipo el lunes",
        "poreyecto grupal discusión",
        "perosnas reuniéndose",
        "miembors del equipo",
        "plnaear una actividad grupal",
    ],
})


# ── PERSON-HIKING ────────────────────────────────────────────────────────────
build_icon("person-hiking", {
    "en": [
        "hike", "hiking", "trail", "backpacking", "camping",
        "mountain", "trekking", "outdoor adventure", "nature walk",
        "hiking boots", "hiking gear", "trail map", "summit",
        "national park", "wilderness", "backpack", "trailhead",
        "day hike",
        "go hiking this weekend",
        "plan a hike in the mountains",
        "pack the backpack for the hiking trip",
        "check the trail map before heading out",
        "buy new hiking boots at the store",
        "hike to the summit of the mountain",
        "bring water for the hiking trail",
        "reserve a campsite for after the hike",
        "download the trail map to my phone",
        "start the hike early in the morning",
        "take a break halfway up the hiking trail",
        "hike the loop trail in the national park",
        "prepare snacks for the day hike",
        "sign up for the group hiking trip",
        "check the weather before the hike",
        "drive to the trailhead parking lot",
        "hike along the river trail today",
        "lace up hiking boots and hit the trail",
        "complete the ten mile hiking route",
        "bring a first aid kit on the hike",
        "take photos during the mountain hike",
        "hike with friends on Saturday morning",
        "find a new hiking trail nearby",
        "mark the trail on the hiking app",
        "set a goal to hike every weekend",
        "explore the wilderness hiking area",
        "pack rain gear for the hike",
        "rest at the campsite after a long hike",
        "refill the water bottle at the trail spring",
        "stretch before starting the hike",
        "wear sunscreen on the hiking trip",
        "pick up trail snacks at the store",
        "book the mountain hiking tour",
        "invite a friend to go hiking with me",
        "walk back to the trailhead before dark",
        "clean the hiking boots after the trail",
        "log the hiking distance in my app",
        "plan next month's backpacking trip",
        "hikign trail in the park",
        "mountian hike this weekend",
        "bakcpacking trip gear list",
        "tral map for the hike",
        "hikng boots need cleaning",
    ],
    "ru": [
        "поход", "туризм", "тропа", "рюкзак за спиной", "кемпинг",
        "гора", "треккинг", "приключение на природе", "прогулка на природе",
        "походные ботинки", "походное снаряжение", "карта маршрута", "вершина",
        "национальный парк", "дикая природа", "рюкзак", "начало тропы",
        "однодневный поход",
        "пойти в поход на выходных",
        "спланировать поход в горы",
        "собрать рюкзак для похода",
        "проверить карту маршрута перед выходом",
        "купить новые походные ботинки в магазине",
        "дойти до вершины горы",
        "взять воду на тропу",
        "забронировать место в кемпинге после похода",
        "скачать карту маршрута на телефон",
        "начать поход рано утром",
        "сделать привал на середине тропы",
        "пройти кольцевой маршрут в национальном парке",
        "подготовить перекус для однодневного похода",
        "записаться на групповой поход",
        "проверить погоду перед походом",
        "доехать до парковки у начала тропы",
        "пойти по тропе вдоль реки сегодня",
        "зашнуровать ботинки и выйти на тропу",
        "пройти маршрут длиной в шестнадцать километров",
        "взять аптечку в поход",
        "фотографировать во время горного похода",
        "пойти в поход с друзьями в субботу утром",
        "найти новую тропу для похода поблизости",
        "отметить тропу в приложении для походов",
        "поставить цель ходить в поход каждые выходные",
        "исследовать зону дикой природы пешком",
        "взять дождевик в поход",
        "отдохнуть в кемпинге после долгого похода",
        "наполнить бутылку у родника на тропе",
        "размяться перед началом похода",
        "нанести солнцезащитный крем перед походом",
        "купить перекус для тропы в магазине",
        "забронировать горный поход с гидом",
        "пригласить друга пойти в поход со мной",
        "вернуться к началу тропы до темноты",
        "почистить ботинки после похода",
        "записать пройденное расстояние в приложении",
        "спланировать поход с рюкзаком на следующий месяц",
        "похд по тропе в парке",
        "горнй поход на выходных",
        "снаряжние для рюкзачного похода",
        "карта маршрта для похода",
        "походне ботинки нужно почистить",
    ],
    "de": [
        "Wanderung", "Wandern", "Wanderweg", "Rucksacktour", "Camping",
        "Berg", "Trekking", "Outdoor-Abenteuer", "Naturwanderung",
        "Wanderschuhe", "Wanderausrüstung", "Wanderkarte", "Gipfel",
        "Nationalpark", "Wildnis", "Rucksack", "Ausgangspunkt",
        "Tageswanderung",
        "am Wochenende wandern gehen",
        "eine Bergwanderung planen",
        "den Rucksack für die Wanderung packen",
        "die Wanderkarte vor dem Start prüfen",
        "neue Wanderschuhe im Laden kaufen",
        "zum Gipfel des Berges wandern",
        "Wasser für den Wanderweg mitnehmen",
        "einen Campingplatz nach der Wanderung reservieren",
        "die Wanderkarte aufs Handy laden",
        "die Wanderung früh am Morgen starten",
        "auf halbem Weg eine Pause machen",
        "die Rundwanderung im Nationalpark laufen",
        "Snacks für die Tageswanderung vorbereiten",
        "sich für die Gruppenwanderung anmelden",
        "das Wetter vor der Wanderung prüfen",
        "zum Parkplatz am Ausgangspunkt fahren",
        "heute den Flussweg entlang wandern",
        "Wanderschuhe schnüren und los",
        "die sechzehn Kilometer Wanderroute schaffen",
        "eine Erste-Hilfe-Tasche auf die Wanderung mitnehmen",
        "Fotos während der Bergwanderung machen",
        "Samstag morgens mit Freunden wandern",
        "einen neuen Wanderweg in der Nähe finden",
        "den Weg in der Wander-App markieren",
        "das Ziel setzen jedes Wochenende zu wandern",
        "die Wildnis zu Fuß erkunden",
        "Regenkleidung für die Wanderung einpacken",
        "nach der langen Wanderung am Campingplatz ausruhen",
        "die Flasche an der Quelle am Weg auffüllen",
        "sich vor der Wanderung dehnen",
        "Sonnencreme für die Wanderung auftragen",
        "Wandersnacks im Laden besorgen",
        "die Bergwanderungstour buchen",
        "einen Freund zum Mitwandern einladen",
        "vor Einbruch der Dunkelheit zum Start zurückkehren",
        "die Wanderschuhe nach dem Weg reinigen",
        "die Wanderstrecke in der App eintragen",
        "die Rucksacktour für nächsten Monat planen",
        "Wanderwen im Park",
        "Bergwanderugn am Wochenende",
        "Rucksacktoru Ausrüstungsliste",
        "Wanderkrate für die Tour",
        "Wanderschueh müssen gereinigt werden",
    ],
    "ja": [
        "ハイキング", "登山", "トレイル", "バックパッキング", "キャンプ",
        "山", "トレッキング", "アウトドア冒険", "自然散策",
        "登山靴", "ハイキング用品", "トレイルマップ", "山頂",
        "国立公園", "荒野", "リュックサック", "登山口",
        "日帰りハイキング",
        "週末にハイキングに行く",
        "山でのハイキングを計画する",
        "ハイキング旅行用にリュックを詰める",
        "出発前にトレイルマップを確認する",
        "お店で新しい登山靴を買う",
        "山の頂上までハイキングする",
        "トレイル用に水を持っていく",
        "ハイキング後のキャンプ場を予約する",
        "トレイルマップをスマホにダウンロードする",
        "早朝にハイキングを開始する",
        "トレイルの途中で休憩を取る",
        "国立公園の周回コースをハイキングする",
        "日帰りハイキング用の軽食を準備する",
        "グループハイキングに申し込む",
        "ハイキング前に天気を確認する",
        "登山口の駐車場まで車で行く",
        "今日は川沿いのトレイルをハイキングする",
        "登山靴の紐を結んでトレイルに出発する",
        "十六キロのハイキングルートを完走する",
        "ハイキングに救急セットを持参する",
        "山でのハイキング中に写真を撮る",
        "土曜の朝に友達とハイキングに行く",
        "近くの新しいハイキングコースを探す",
        "ハイキングアプリでトレイルをマークする",
        "毎週末ハイキングする目標を立てる",
        "荒野のハイキングエリアを探検する",
        "ハイキングに雨具を持っていく",
        "長いハイキングの後キャンプ場で休む",
        "トレイルの湧き水でボトルを補充する",
        "ハイキング前にストレッチする",
        "ハイキング旅行に日焼け止めを塗る",
        "お店でトレイル用の軽食を買う",
        "山のハイキングツアーを予約する",
        "友達をハイキングに誘う",
        "暗くなる前に登山口に戻る",
        "ハイキング後に登山靴を掃除する",
        "アプリにハイキングの距離を記録する",
        "来月のバックパッキング旅行を計画する",
        "ハイキングのトレイル公園で",
        "山ハイキンク週末に",
        "バックパキング旅行の持ち物リスト",
        "トレイルマプを確認する",
        "登山靴のクリーニンクが必要",
    ],
    "fr": [
        "randonnée", "marche en montagne", "sentier", "trekking", "camping",
        "montagne", "excursion", "aventure en plein air", "balade nature",
        "chaussures de randonnée", "équipement de randonnée", "carte du sentier", "sommet",
        "parc national", "nature sauvage", "sac à dos", "départ du sentier",
        "randonnée d'une journée",
        "partir en randonnée ce week-end",
        "planifier une randonnée en montagne",
        "préparer le sac à dos pour la randonnée",
        "vérifier la carte du sentier avant de partir",
        "acheter de nouvelles chaussures de randonnée",
        "randonner jusqu'au sommet de la montagne",
        "emporter de l'eau pour le sentier",
        "réserver un camping après la randonnée",
        "télécharger la carte du sentier sur mon téléphone",
        "commencer la randonnée tôt le matin",
        "faire une pause à mi-chemin du sentier",
        "faire la boucle du sentier dans le parc national",
        "préparer des collations pour la randonnée",
        "s'inscrire à la randonnée de groupe",
        "vérifier la météo avant la randonnée",
        "conduire jusqu'au parking du départ du sentier",
        "randonner le long du sentier de la rivière aujourd'hui",
        "lacer les chaussures de randonnée et partir",
        "terminer le parcours de seize kilomètres",
        "emporter une trousse de secours en randonnée",
        "prendre des photos pendant la randonnée en montagne",
        "randonner avec des amis samedi matin",
        "trouver un nouveau sentier de randonnée à proximité",
        "marquer le sentier sur l'application de randonnée",
        "se fixer l'objectif de randonner chaque week-end",
        "explorer la zone de nature sauvage à pied",
        "emporter un imperméable pour la randonnée",
        "se reposer au camping après une longue randonnée",
        "remplir la gourde à la source du sentier",
        "s'étirer avant de commencer la randonnée",
        "mettre de la crème solaire pour la randonnée",
        "acheter des collations de sentier au magasin",
        "réserver la randonnée guidée en montagne",
        "inviter un ami à randonner avec moi",
        "rentrer au départ du sentier avant la nuit",
        "nettoyer les chaussures de randonnée après le sentier",
        "enregistrer la distance de randonnée dans mon appli",
        "planifier le trek du mois prochain",
        "randonnéee dans le parc",
        "motagne randonnée ce week-end",
        "équipeemnt de trekking",
        "carte du sentire pour la rando",
        "chaussures de randonnéé à nettoyer",
    ],
    "es": [
        "senderismo", "caminata", "sendero", "mochilero", "camping",
        "montaña", "trekking", "aventura al aire libre", "paseo por la naturaleza",
        "botas de senderismo", "equipo de senderismo", "mapa del sendero", "cumbre",
        "parque nacional", "vida silvestre", "mochila", "inicio del sendero",
        "caminata de un día",
        "ir de senderismo este fin de semana",
        "planear una caminata en la montaña",
        "preparar la mochila para la excursión",
        "revisar el mapa del sendero antes de salir",
        "comprar botas de senderismo nuevas en la tienda",
        "hacer senderismo hasta la cumbre de la montaña",
        "llevar agua para el sendero",
        "reservar un sitio de camping después de la caminata",
        "descargar el mapa del sendero en mi teléfono",
        "empezar la caminata temprano por la mañana",
        "tomar un descanso a mitad del sendero",
        "hacer el circuito del sendero en el parque nacional",
        "preparar bocadillos para la caminata del día",
        "inscribirse en la caminata grupal",
        "revisar el clima antes de la caminata",
        "manejar hasta el estacionamiento del inicio del sendero",
        "caminar por el sendero del río hoy",
        "atar las botas de senderismo y salir al sendero",
        "completar la ruta de senderismo de dieciséis kilómetros",
        "llevar un botiquín de primeros auxilios a la caminata",
        "tomar fotos durante la caminata en la montaña",
        "ir de senderismo con amigos el sábado por la mañana",
        "encontrar un nuevo sendero para caminar cerca",
        "marcar el sendero en la aplicación de senderismo",
        "ponerse la meta de hacer senderismo cada fin de semana",
        "explorar la zona silvestre caminando",
        "llevar impermeable para la caminata",
        "descansar en el campamento después de una larga caminata",
        "rellenar la botella en el manantial del sendero",
        "estirar antes de empezar la caminata",
        "ponerse protector solar para la caminata",
        "comprar bocadillos para el sendero en la tienda",
        "reservar el tour de senderismo en la montaña",
        "invitar a un amigo a hacer senderismo conmigo",
        "regresar al inicio del sendero antes de que oscurezca",
        "limpiar las botas de senderismo después del sendero",
        "registrar la distancia de senderismo en mi app",
        "planear la excursión con mochila del próximo mes",
        "sendersimo en el parque",
        "mnotaña caminata este fin de semana",
        "equipo de trekking lista",
        "mapa del sendro para la caminata",
        "botas de sendersmo necesitan limpieza",
    ],
})


print("Part A (pen, pencil, people, person-hiking) done.")
