#!/usr/bin/env python3
"""Task-003 part 4: mouse-field, mp3-player"""
from gen_icons_task_003_lib import build_icon

# ── mouse-field ──────────────────────────────────────────────────────────────
build_icon("mouse-field",
    keep_en=[
        "rat",
        "rodent",
        "squeak",
        "field mouse foraging for food",
        "mouse trap with cheese bait",
        "rodent pest control symbol",
        "mose field animal",
        "mouce with cheese",
        "rodant squeak",
    ],
    new_en=[
        "field mouse",
        "mouse",
        "pest",
        "mice",
        "exterminator",
        "trap",
        "vermin",
        "critter",
        "rodent control",
        "mouse hole",
        "set a mouse trap in the garage",
        "call the exterminator about the mice",
        "check the basement for mouse droppings",
        "buy mouse traps at the hardware store",
        "seal the holes where mice get in",
        "schedule pest control for the house",
        "clean up mouse nest in the attic",
        "put bait in the mouse trap tonight",
        "look for signs of rodent activity",
        "hire pest control for the mouse problem",
        "pick up poison-free mouse traps",
        "check the garage for field mice",
        "block the mouse entry point under the sink",
        "replace the old mouse traps",
        "ask the landlord about the mouse issue",
        "research humane mouse traps online",
        "move food into sealed containers from mice",
        "inspect the garden shed for rodents",
        "get a cat to deal with the mice",
        "set snap traps along the wall",
        "check live trap for mice this morning",
        "call pest control for the field mouse problem",
        "find where the mice are nesting",
        "buy steel wool to plug mouse holes",
        "return the live mouse trap to the store",
        "set up ultrasonic rodent repeller",
        "clear brush pile where mice hide",
        "check crawl space for mouse activity",
        "schedule annual pest inspection",
        "look up natural mouse repellent options",
        "mousetrap in the garag",
        "extermnator for mice",
        "mouse problm in the attic",
        "rodant droppings in basment",
        "pest contrl for the house",
        "clean the mouse nest tomorow",
        "feild mouse in the garden",
        "mouce traps to buy",
        "seal mouse holes in the kichen",
        "check trps this morning",
        "replace old mouse trps",
    ],
    keep_ru=[
        "крыса",
        "грызун",
        "писк",
        "полевая мышь в поисках еды",
        "мышеловка с приманкой из сыра",
        "символ борьбы с грызунами-вредителями",
        "мышк в поле",
        "крыас с сыром",
        "грызну писк",
    ],
    new_ru=[
        "полевая мышь",
        "мышь",
        "вредитель",
        "мыши",
        "дератизатор",
        "ловушка",
        "грызуны",
        "нора",
        "мышиная нора",
        "борьба с грызунами",
        "поставить мышеловку в гараже",
        "позвонить дератизатору насчёт мышей",
        "проверить подвал на мышиный помёт",
        "купить мышеловки в хозяйственном магазине",
        "заделать дыры откуда лезут мыши",
        "заказать дератизацию дома",
        "убрать мышиное гнездо на чердаке",
        "положить приманку в мышеловку сегодня",
        "проверить есть ли следы грызунов",
        "нанять службу от мышей",
        "купить гуманные мышеловки",
        "проверить гараж на полевых мышей",
        "заблокировать вход мыши под раковиной",
        "заменить старые мышеловки",
        "сообщить хозяину квартиры о мышах",
        "найти гуманные мышеловки в интернете",
        "переложить еду в герметичные контейнеры от мышей",
        "осмотреть садовый сарай на грызунов",
        "завести кота чтобы ловить мышей",
        "поставить ловушки вдоль стены",
        "проверить живоловку утром",
        "вызвать службу от полевых мышей",
        "найти где гнездятся мыши",
        "купить стальную вату чтобы заткнуть норы",
        "вернуть живоловку для мышей в магазин",
        "установить ультразвуковой отпугиватель грызунов",
        "убрать кучу хвороста где прячутся мыши",
        "проверить подполье на мышей",
        "запланировать ежегодный осмотр на вредителей",
        "найти натуральные средства от мышей",
        "мышловка в гараже",
        "дератизтор для мышей",
        "мышиная проблма на чердаке",
        "помёт грызунв в подвале",
        "борьба с вредителми в доме",
        "убрать мышное гнездо завтра",
        "полевая мыш в саду",
        "мышловки купить",
        "заделать мышиные норы на кухне",
        "проверить ловушки утрм",
        "заменить старые мышловки",
    ],
    de=[
        "Feldmaus",
        "Maus",
        "Ratte",
        "Nagetier",
        "Schädling",
        "Mäuse",
        "Kammerjäger",
        "Falle",
        "Ungeziefer",
        "Mäuseloch",
        "Nager",
        "Mausefalle",
        "Schädlingsbekämpfung",
        "Mäusenest",
        "Mäuseplage",
        "Köder",
        "Lebendfalle",
        "Schädlingsbefall",
        "Mausefalle in der Garage aufstellen",
        "Kammerjäger wegen der Mäuse anrufen",
        "Keller auf Mäusekot prüfen",
        "Mausefallen im Baumarkt kaufen",
        "Löcher abdichten wo Mäuse reinkommen",
        "Schädlingsbekämpfung für das Haus bestellen",
        "Mäusenest auf dem Dachboden entfernen",
        "Köder in die Mausefalle legen",
        "nach Zeichen von Nagetieraktivität suchen",
        "Schädlingsbekämpfer wegen der Mäuse holen",
        "giftfreie Mausefallen kaufen",
        "Garage auf Feldmäuse prüfen",
        "Mauseeingang unter der Spüle blockieren",
        "alte Mausefallen austauschen",
        "Vermieter wegen der Mäuse informieren",
        "humane Mausefallen online suchen",
        "Essen in dichte Behälter umfüllen wegen Mäusen",
        "Gartenschuppen auf Nagetiere prüfen",
        "Katze anschaffen um Mäuse zu fangen",
        "Schlagfallen entlang der Wand aufstellen",
        "Lebendfalle heute Morgen kontrollieren",
        "Schädlingsbekämpfung für Feldmäuse rufen",
        "herausfinden wo die Mäuse nisten",
        "Stahlwolle zum Stopfen der Mauselöcher kaufen",
        "Ultraschall-Mäuseabwehr aufstellen",
        "Reisighaufen entfernen wo Mäuse sich verstecken",
        "Kriechkeller auf Mäuseaktivität prüfen",
        "jährliche Schädlingsinspektion planen",
        "natürliche Mäuseabwehrmittel nachschauen",
        "Mausefale in der Garage",
        "Kammerjäger für Mäse",
        "Mäuseproblem auf dem Dachbden",
        "Nagetierkot im Keler",
        "Schädlingsbekämpfung fürs Hus",
    ],
    ja=[
        "野ネズミ",
        "ネズミ",
        "ドブネズミ",
        "げっ歯類",
        "害獣",
        "ネズミ駆除",
        "罠",
        "害虫駆除",
        "ネズミの穴",
        "ネズミ捕り",
        "駆除業者",
        "ネズミの巣",
        "ネズミ被害",
        "餌",
        "生け捕り罠",
        "ネズミの糞",
        "殺鼠剤",
        "害獣対策",
        "ガレージにネズミ捕りを仕掛ける",
        "ネズミについて駆除業者に電話する",
        "地下室にネズミの糞がないか確認する",
        "ホームセンターでネズミ捕りを買う",
        "ネズミが入ってくる穴を塞ぐ",
        "家のネズミ駆除を予約する",
        "屋根裏のネズミの巣を片付ける",
        "今夜ネズミ捕りに餌を入れる",
        "ネズミの活動の兆候を探す",
        "ネズミ問題で害獣駆除を依頼する",
        "毒なしのネズミ捕りを買う",
        "ガレージに野ネズミがいないか確認する",
        "シンク下のネズミの侵入口を塞ぐ",
        "古いネズミ捕りを交換する",
        "大家にネズミの問題を相談する",
        "人道的なネズミ捕りをネットで調べる",
        "ネズミ対策で食品を密閉容器に移す",
        "庭の物置にネズミがいないか点検する",
        "ネズミ対策に猫を飼う",
        "壁際にパチン式の罠を仕掛ける",
        "今朝生け捕り罠を確認する",
        "野ネズミの問題で害獣駆除を呼ぶ",
        "ネズミの巣がどこにあるか探す",
        "ネズミの穴を塞ぐためにスチールウールを買う",
        "超音波ネズミ除けを設置する",
        "ネズミが隠れる草むらを片付ける",
        "床下のネズミの活動を確認する",
        "年一回の害獣点検を予約する",
        "天然のネズミ忌避剤を調べる",
        "ねずみとり を しかける",
        "くじょ ぎょうしゃ に でんわ",
        "ねずみ の あな を ふさぐ",
        "ねずみ を つかまえる",
        "ガレージ の ねずみ たいさく",
    ],
    fr=[
        "mulot",
        "souris",
        "rat",
        "rongeur",
        "nuisible",
        "souris des champs",
        "exterminateur",
        "piège",
        "vermine",
        "trou de souris",
        "dératisation",
        "piège à souris",
        "lutte antiparasitaire",
        "nid de souris",
        "invasion de souris",
        "appât",
        "piège vivant",
        "infestation",
        "installer un piège à souris dans le garage",
        "appeler l'exterminateur pour les souris",
        "vérifier le sous-sol pour les crottes de souris",
        "acheter des pièges à souris à la quincaillerie",
        "boucher les trous par où les souris entrent",
        "planifier la dératisation de la maison",
        "nettoyer le nid de souris dans le grenier",
        "mettre l'appât dans le piège à souris ce soir",
        "chercher des signes d'activité de rongeurs",
        "engager un dératiseur pour le problème de souris",
        "acheter des pièges à souris sans poison",
        "vérifier le garage pour les mulots",
        "bloquer l'entrée de souris sous l'évier",
        "remplacer les vieux pièges à souris",
        "prévenir le propriétaire du problème de souris",
        "rechercher des pièges à souris humains en ligne",
        "mettre la nourriture dans des contenants hermétiques",
        "inspecter l'abri de jardin pour les rongeurs",
        "adopter un chat pour attraper les souris",
        "placer des pièges à ressort le long du mur",
        "vérifier le piège vivant ce matin",
        "appeler la dératisation pour les mulots",
        "trouver où nichent les souris",
        "acheter de la laine d'acier pour boucher les trous",
        "installer un répulsif à ultrasons pour rongeurs",
        "dégager le tas de broussailles où se cachent les souris",
        "vérifier le vide sanitaire pour les souris",
        "planifier l'inspection annuelle contre les nuisibles",
        "chercher des répulsifs naturels contre les souris",
        "piège à souris dans le garag",
        "extarminateur pour les souris",
        "problème de souris au grenir",
        "crottes de rongurs dans le sous-sol",
        "dératisaton de la maison",
    ],
    es=[
        "ratón de campo",
        "ratón",
        "rata",
        "roedor",
        "plaga",
        "ratones",
        "exterminador",
        "trampa",
        "alimañas",
        "madriguera de ratón",
        "control de plagas",
        "ratonera",
        "desratización",
        "nido de ratones",
        "invasión de ratones",
        "cebo",
        "trampa humanitaria",
        "infestación",
        "poner una ratonera en el garaje",
        "llamar al exterminador por los ratones",
        "revisar el sótano por excrementos de ratón",
        "comprar ratoneras en la ferretería",
        "sellar los agujeros por donde entran los ratones",
        "programar el control de plagas para la casa",
        "limpiar el nido de ratones en el ático",
        "poner cebo en la ratonera esta noche",
        "buscar señales de actividad de roedores",
        "contratar control de plagas por los ratones",
        "comprar ratoneras sin veneno",
        "revisar el garaje por ratones de campo",
        "bloquear la entrada de ratones bajo el fregadero",
        "reemplazar las ratoneras viejas",
        "avisar al casero del problema de ratones",
        "buscar ratoneras humanitarias en internet",
        "guardar la comida en envases sellados por los ratones",
        "inspeccionar el cobertizo por roedores",
        "adoptar un gato para atrapar ratones",
        "poner trampas de resorte a lo largo de la pared",
        "revisar la trampa humanitaria esta mañana",
        "llamar al control de plagas por ratones de campo",
        "encontrar dónde anidan los ratones",
        "comprar lana de acero para tapar madrigueras",
        "instalar repelente ultrasónico de roedores",
        "quitar la pila de ramas donde se esconden los ratones",
        "revisar el espacio debajo de la casa por ratones",
        "programar la inspección anual contra plagas",
        "buscar repelentes naturales contra ratones",
        "ratonera en el garaj",
        "exterminadr para ratones",
        "problema de ratones en el atico",
        "excrementos de roedres en el sótano",
        "contrl de plagas para la casa",
    ],
)

# ── mp3-player ───────────────────────────────────────────────────────────────
build_icon("mp3-player",
    keep_en=[
        "handheld",
        "ipod",
        "itunes",
        "zune",
        "audio playback device portable",
        "audio streaming on handheld",
        "handheld music player device",
        "handheld gadget for listening",
        "iPod classic music player",
        "iPod shuffle with earbuds",
        "iTunes music library sync",
        "iTunes podcast subscription",
        "music player in pocket",
        "listen to music on the go",
        "Zune Microsoft music player",
        "Zune HD portable device",
        "classic iPod with click wheel for music",
        "pocket-sized MP3 player for jogging",
        "music player with earbuds included",
        "old school digital music device",
        "portable audio player for workout",
        "MP3 player with small screen and controls",
        "shuffle playlist on a handheld device",
        "digital music player for commute",
        "retro personal music device",
        "music storage device before streaming",
        "mp3 palyer music",
        "ipood classic",
        "handhled music device",
        "musci player portable",
    ],
    new_en=[
        "audio",
        "music",
        "player",
        "portable",
        "walkman",
        "mp3",
        "charge the mp3 player before the run",
        "download songs to the mp3 player",
        "organize the playlist on the iPod",
        "sync the music library to the player",
        "buy earbuds for the mp3 player",
        "load new albums onto the portable player",
        "plug in the mp3 player to charge overnight",
        "transfer podcasts to the handheld player",
        "create a workout playlist on the mp3 player",
        "fix the headphone jack on the old iPod",
        "sell the old Zune on the marketplace",
        "replace the battery in the iPod classic",
        "back up the music from the mp3 player",
        "find the charging cable for the player",
        "clear storage on the mp3 player",
        "update the firmware on the music player",
        "gift an mp3 player for the birthday",
        "connect the mp3 player to the car stereo",
        "compare portable music players online",
        "set up shuffle mode on the player",
        "clean the screen of the mp3 player",
        "load audiobooks onto the portable player",
        "bring the mp3 player to the gym",
        "chrage the mp3 playr",
    ],
    keep_ru=[
        "музыкальный плеер",
        "карманный плеер",
        "слушать музыку с плеера",
        "загрузить песни в плеер",
        "старый mp3-плеер",
        "плеер для бега",
        "кнопочный музыкальный плеер",
        "портативный аудиоплеер",
        "маленький плеер с экраном",
        "плеер с наушниками",
        "офлайн-плеер для музыки",
        "плеер в кармане",
        "включить музыку на плеере",
        "выбрать трек в плеере",
        "поставить песню на паузу",
        "листать музыку на плеере",
        "портативный плеер без интернета",
        "отдельный плеер для музыки",
        "плеер с колесом прокрутки",
        "ретро-плеер для песен",
        "устройство для mp3",
        "музыкальный плеер для поездки",
        "аудиоплеер для тренировок",
        "старый плеер с кнопками",
        "загрузить альбом в плеер",
        "карманное устройство для музыки",
        "выбрать подкаст в плеере",
        "хранить музыку офлайн",
        "плеер для долгой дороги",
        "небольшой плеер для аудиокниг",
        "отдельный гаджет для музыки",
        "слушать альбом без телефона",
        "плеер с плейлистами",
        "носимый плеер для музыки",
        "музыкальный плеер на прогулку",
        "портативный проигрыватель музыки",
        "карманный mp3-плеер для школы",
        "кнопки управления музыкой",
        "автономный плеер для треков",
        "музыкальное устройство для наушников",
    ],
    new_ru=[
        "аудио",
        "портативный",
        "плеер",
        "mp3",
        "наушники",
        "зарядить mp3-плеер перед пробежкой",
        "скачать песни в mp3-плеер",
        "составить плейлист на плеере",
        "синхронизировать музыку с плеером",
        "купить наушники для mp3-плеера",
        "загрузить новые альбомы в портативный плеер",
        "поставить mp3-плеер на зарядку на ночь",
        "перенести подкасты на плеер",
        "создать плейлист для тренировки на плеере",
        "починить разъём наушников на старом плеере",
        "подарить mp3-плеер на день рождения",
        "заменить батарейку в старом плеере",
        "сделать резервную копию музыки с плеера",
        "найти зарядный кабель для плеера",
        "очистить память mp3-плеера",
        "обновить прошивку музыкального плеера",
        "зарядть mp3-плеер",
        "скачть песни в плеер",
        "плеер для тренровки",
        "загрзить альбом в плеер",
    ],
    de=[
        "MP3-Player",
        "iPod",
        "Musikplayer",
        "tragbar",
        "Audio",
        "Walkman",
        "Musik",
        "Kopfhörer",
        "Playlist",
        "Player",
        "Abspielen",
        "Gerät",
        "tragbares Audiogerät",
        "Musikgerät",
        "Klickrad",
        "Shuffle",
        "Podcast",
        "Audiobuch",
        "MP3-Player vor dem Laufen aufladen",
        "Songs auf den MP3-Player laden",
        "Playlist auf dem iPod ordnen",
        "Musikbibliothek mit dem Player synchronisieren",
        "Kopfhörer für den MP3-Player kaufen",
        "neue Alben auf den tragbaren Player laden",
        "MP3-Player über Nacht zum Laden anschließen",
        "Podcasts auf den Player übertragen",
        "Workout-Playlist auf dem MP3-Player erstellen",
        "Kopfhöreranschluss am alten iPod reparieren",
        "alten Zune auf dem Marktplatz verkaufen",
        "Batterie im iPod classic wechseln",
        "Musik vom MP3-Player sichern",
        "Ladekabel für den Player finden",
        "Speicher auf dem MP3-Player freimachen",
        "Firmware des Musikplayers aktualisieren",
        "MP3-Player zum Geburtstag schenken",
        "MP3-Player mit dem Autoradio verbinden",
        "tragbare Musikplayer online vergleichen",
        "Zufallsmodus auf dem Player einstellen",
        "Bildschirm des MP3-Players reinigen",
        "Hörbücher auf den tragbaren Player laden",
        "MP3-Player ins Fitnessstudio mitnehmen",
        "Musik für den Pendelweg auf den Player laden",
        "Playlist für die Reise zusammenstellen",
        "neuen Kopfhörer für den Player kaufen",
        "Player in die Tasche packen",
        "Lieblingssongs auf den Player laden",
        "MP3-Playr aufladen",
        "Musick auf den Player laden",
        "Playlsit erstellen",
        "Kopfhöhrer kaufen",
        "Audiobuch auf den Playr laden",
        "iPood classic reparieren",
    ],
    ja=[
        "MP3プレーヤー",
        "iPod",
        "音楽プレーヤー",
        "ポータブル",
        "オーディオ",
        "ウォークマン",
        "音楽",
        "イヤホン",
        "プレイリスト",
        "プレーヤー",
        "再生",
        "デバイス",
        "携帯音楽プレーヤー",
        "音楽機器",
        "クリックホイール",
        "シャッフル",
        "ポッドキャスト",
        "オーディオブック",
        "ランニング前にMP3プレーヤーを充電する",
        "MP3プレーヤーに曲をダウンロードする",
        "iPodのプレイリストを整理する",
        "プレーヤーに音楽ライブラリを同期する",
        "MP3プレーヤー用のイヤホンを買う",
        "ポータブルプレーヤーに新しいアルバムを入れる",
        "MP3プレーヤーを一晩充電する",
        "ハンドヘルドプレーヤーにポッドキャストを転送する",
        "MP3プレーヤーにワークアウト用プレイリストを作る",
        "古いiPodのイヤホンジャックを修理する",
        "古いZuneをフリマで売る",
        "iPod classicのバッテリーを交換する",
        "MP3プレーヤーの音楽をバックアップする",
        "プレーヤーの充電ケーブルを探す",
        "MP3プレーヤーのストレージを空ける",
        "音楽プレーヤーのファームウェアを更新する",
        "誕生日にMP3プレーヤーをプレゼントする",
        "MP3プレーヤーを車のステレオに接続する",
        "ポータブル音楽プレーヤーをネットで比較する",
        "プレーヤーのシャッフルモードを設定する",
        "MP3プレーヤーの画面を拭く",
        "ポータブルプレーヤーにオーディオブックを入れる",
        "MP3プレーヤーをジムに持っていく",
        "通勤用の音楽をプレーヤーに入れる",
        "旅行用のプレイリストを作る",
        "プレーヤー用に新しいイヤホンを買う",
        "プレーヤーをカバンに入れる",
        "好きな曲をプレーヤーに入れる",
        "MP3プレーヤー を じゅうでん する",
        "おんがく を ダウンロード する",
        "プレイリスト を つくる",
        "イヤホン を かう",
        "おんがく プレーヤー を もっていく",
    ],
    fr=[
        "lecteur MP3",
        "iPod",
        "lecteur de musique",
        "portable",
        "audio",
        "baladeur",
        "musique",
        "écouteurs",
        "playlist",
        "lecteur",
        "lecture",
        "appareil",
        "appareil audio portable",
        "baladeur numérique",
        "molette cliquable",
        "aléatoire",
        "podcast",
        "livre audio",
        "charger le lecteur MP3 avant la course",
        "télécharger des chansons sur le lecteur MP3",
        "organiser la playlist sur l'iPod",
        "synchroniser la bibliothèque musicale avec le lecteur",
        "acheter des écouteurs pour le lecteur MP3",
        "charger de nouveaux albums sur le lecteur portable",
        "brancher le lecteur MP3 pour la nuit",
        "transférer des podcasts sur le lecteur",
        "créer une playlist d'entraînement sur le lecteur MP3",
        "réparer la prise casque du vieil iPod",
        "vendre le vieux Zune sur le marché en ligne",
        "remplacer la batterie de l'iPod classic",
        "sauvegarder la musique du lecteur MP3",
        "trouver le câble de charge du lecteur",
        "libérer du stockage sur le lecteur MP3",
        "mettre à jour le firmware du lecteur de musique",
        "offrir un lecteur MP3 pour l'anniversaire",
        "connecter le lecteur MP3 à l'autoradio",
        "comparer les lecteurs de musique portables en ligne",
        "activer le mode aléatoire sur le lecteur",
        "nettoyer l'écran du lecteur MP3",
        "charger des livres audio sur le lecteur portable",
        "apporter le lecteur MP3 à la salle de sport",
        "charger de la musique pour le trajet",
        "préparer une playlist pour le voyage",
        "acheter de nouveaux écouteurs pour le lecteur",
        "mettre le lecteur dans le sac",
        "charger les chansons préférées sur le lecteur",
        "charger le lectuer MP3",
        "téléchager des chansons",
        "playlsit à organiser",
        "écouteus à acheter",
        "livre audoi sur le lecteur",
    ],
    es=[
        "reproductor MP3",
        "iPod",
        "reproductor de música",
        "portátil",
        "audio",
        "walkman",
        "música",
        "audífonos",
        "playlist",
        "reproductor",
        "reproducción",
        "dispositivo",
        "aparato de audio portátil",
        "reproductor digital",
        "rueda de clic",
        "aleatorio",
        "podcast",
        "audiolibro",
        "cargar el reproductor MP3 antes de correr",
        "descargar canciones en el reproductor MP3",
        "organizar la playlist en el iPod",
        "sincronizar la biblioteca musical con el reproductor",
        "comprar audífonos para el reproductor MP3",
        "cargar nuevos álbumes en el reproductor portátil",
        "conectar el reproductor MP3 a cargar durante la noche",
        "transferir podcasts al reproductor",
        "crear una playlist de ejercicio en el reproductor MP3",
        "reparar la entrada de audífonos del viejo iPod",
        "vender el viejo Zune en el mercado en línea",
        "reemplazar la batería del iPod classic",
        "respaldar la música del reproductor MP3",
        "encontrar el cable de carga del reproductor",
        "liberar espacio en el reproductor MP3",
        "actualizar el firmware del reproductor de música",
        "regalar un reproductor MP3 de cumpleaños",
        "conectar el reproductor MP3 al estéreo del auto",
        "comparar reproductores de música portátiles en línea",
        "activar el modo aleatorio en el reproductor",
        "limpiar la pantalla del reproductor MP3",
        "cargar audiolibros en el reproductor portátil",
        "llevar el reproductor MP3 al gimnasio",
        "cargar música para el trayecto",
        "preparar una playlist para el viaje",
        "comprar nuevos audífonos para el reproductor",
        "meter el reproductor en la mochila",
        "cargar las canciones favoritas en el reproductor",
        "cargr el reproductor MP3",
        "descargr canciones en el reproductor",
        "playlsit para organizar",
        "audífonos para comprar",
        "audiolbro en el reproductor",
    ],
)

print("Part 4 done: mouse-field, mp3-player")
