#!/usr/bin/env python3
"""Task-003 part 5: music, mustache"""
from gen_icons_task_003_lib import build_icon

# ── music ────────────────────────────────────────────────────────────────────
# Note: boundary = music-note. Avoid visual descriptions of note symbols.
build_icon("music",
    keep_en=[
        "lyrics",
        "melody",
        "music",
        "note",
        "song lyrics displayed in a music player",
        "lyrics scroll as the song plays",
        "hum a catchy melody stuck in your head",
        "music streaming from a phone speaker",
        "background music playing during a workout",
        "sing along to your favorite song",
        "rich sound coming from the music player",
        "play a song in a music streaming app",
        "muisc playing in the background",
        "msuic streaming app",
        "musci note icon",
        "musik player on the phone",
    ],
    new_en=[
        "song",
        "sound",
        "musical",
        "playlist",
        "tune",
        "rhythm",
        "band",
        "concert",
        "album",
        "genre",
        "listen to music while cooking dinner",
        "practice guitar for an hour today",
        "make a road trip playlist",
        "buy concert tickets for next month",
        "learn the lyrics to the new song",
        "download the album before the flight",
        "find new music for the workout playlist",
        "tune the guitar before band practice",
        "set music as the morning alarm",
        "stream the new album on release day",
        "sign up for music lessons this fall",
        "pick a song for the wedding first dance",
        "share the playlist with friends",
        "buy a gift card for the music store",
        "listen to the podcast about music history",
        "practice piano scales before the recital",
        "add songs to the study playlist",
        "look up the song lyrics online",
        "attend the live music event downtown",
        "record a voice memo of the melody idea",
        "organize the music library by genre",
        "create a calm music playlist for sleep",
        "book the rehearsal room for band practice",
        "check the setlist for the concert",
        "ask the DJ to play our song",
        "subscribe to the music streaming service",
        "rate the album after listening",
        "pick up guitar strings at the music shop",
        "musci lessons this fall",
        "playlst for the road trip",
        "concrt tickets next month",
        "albm download before the flight",
        "prctice piano before recital",
        "meldoy idea to record",
    ],
    keep_ru=[
        "текст песни",
        "мелодия",
        "музыка",
        "нота",
        "петь",
        "звук",
        "слова песни в музыкальном плеере",
        "текст песни прокручивается во время воспроизведения",
        "напевать прилипчивую мелодию",
        "музыка играет через динамик телефона",
        "фоновая музыка во время тренировки",
        "подпевать любимой песне",
        "музыка играет на фоне",
        "музыкальное приложение стриминга",
    ],
    new_ru=[
        "песня",
        "музыкальный",
        "плейлист",
        "мотив",
        "ритм",
        "группа",
        "концерт",
        "альбом",
        "жанр",
        "слушать музыку во время готовки",
        "позаниматься на гитаре час сегодня",
        "составить плейлист для поездки",
        "купить билеты на концерт на следующий месяц",
        "выучить слова новой песни",
        "скачать альбом перед полётом",
        "найти новую музыку для тренировочного плейлиста",
        "настроить гитару перед репетицией группы",
        "поставить музыку на утренний будильник",
        "послушать новый альбом в день выхода",
        "записаться на уроки музыки осенью",
        "выбрать песню для первого танца на свадьбе",
        "поделиться плейлистом с друзьями",
        "купить подарочную карту в музыкальный магазин",
        "послушать подкаст об истории музыки",
        "позаниматься гаммами на пианино перед концертом",
        "добавить песни в плейлист для учёбы",
        "найти слова песни в интернете",
        "сходить на живую музыку в центре",
        "записать голосовую заметку с идеей мелодии",
        "рассортировать музыку по жанрам",
        "создать спокойный плейлист для сна",
        "забронировать репетиционную комнату для группы",
        "посмотреть сетлист концерта",
        "попросить диджея поставить нашу песню",
        "подписаться на музыкальный стриминг",
        "оценить альбом после прослушивания",
        "купить струны для гитары в музыкальном магазине",
        "уроки музки осенью",
        "плейлст для поездки",
        "билеты на конрцет",
        "альбм скачать перед полётом",
        "репетиця на пианино",
        "мелдия идея записать",
    ],
    de=[
        "Musik",
        "Lied",
        "Melodie",
        "Note",
        "Klang",
        "Rhythmus",
        "Band",
        "Konzert",
        "Album",
        "Genre",
        "Playlist",
        "Text",
        "Liedtext",
        "Gesang",
        "Ton",
        "Stimmung",
        "Instrument",
        "Sänger",
        "beim Kochen Musik hören",
        "heute eine Stunde Gitarre üben",
        "Playlist für den Roadtrip erstellen",
        "Konzertkarten für nächsten Monat kaufen",
        "den Text des neuen Liedes lernen",
        "das Album vor dem Flug herunterladen",
        "neue Musik für die Trainingsplaylist finden",
        "Gitarre vor der Bandprobe stimmen",
        "Musik als Morgenwecker einstellen",
        "neues Album am Erscheinungstag streamen",
        "im Herbst für Musikunterricht anmelden",
        "Lied für den Hochzeitstanz aussuchen",
        "Playlist mit Freunden teilen",
        "Geschenkkarte für den Musikladen kaufen",
        "Podcast über Musikgeschichte hören",
        "Tonleitern am Klavier vor dem Konzert üben",
        "Songs zur Lernplaylist hinzufügen",
        "Liedtext im Internet nachschauen",
        "Livemusik-Event in der Stadt besuchen",
        "Sprachnotiz mit Melodieidee aufnehmen",
        "Musikbibliothek nach Genre sortieren",
        "ruhige Schlafplaylist erstellen",
        "Proberaum für die Bandprobe buchen",
        "Setlist für das Konzert prüfen",
        "DJ bitten unser Lied zu spielen",
        "Musikstreamingdienst abonnieren",
        "Album nach dem Hören bewerten",
        "Gitarrensaiten im Musikladen kaufen",
        "Musikuntericht im Herbst",
        "Playlsit für den Roadtrip",
        "Konzertkaten nächsten Monat",
        "Albm herunterladen",
        "Klavir üben vor dem Konzert",
        "Melodieidee aufnehemn",
    ],
    ja=[
        "音楽",
        "歌",
        "メロディー",
        "音符",
        "音",
        "リズム",
        "バンド",
        "コンサート",
        "アルバム",
        "ジャンル",
        "プレイリスト",
        "歌詞",
        "曲",
        "歌声",
        "トーン",
        "楽器",
        "ミュージシャン",
        "ライブ",
        "料理中に音楽を聴く",
        "今日ギターを一時間練習する",
        "ドライブ用のプレイリストを作る",
        "来月のコンサートチケットを買う",
        "新曲の歌詞を覚える",
        "フライト前にアルバムをダウンロードする",
        "ワークアウト用プレイリストに新しい曲を見つける",
        "バンド練習前にギターをチューニングする",
        "朝のアラームに音楽を設定する",
        "発売日に新アルバムをストリーミングする",
        "秋から音楽のレッスンに申し込む",
        "結婚式のファーストダンスの曲を選ぶ",
        "プレイリストを友達とシェアする",
        "音楽ストアのギフトカードを買う",
        "音楽の歴史のポッドキャストを聴く",
        "発表会前にピアノのスケールを練習する",
        "勉強用プレイリストに曲を追加する",
        "ネットで歌詞を調べる",
        "街のライブ音楽イベントに行く",
        "メロディーのアイデアをボイスメモに録音する",
        "音楽ライブラリをジャンル別に整理する",
        "睡眠用の穏やかなプレイリストを作る",
        "バンド練習用のリハーサル室を予約する",
        "コンサートのセットリストを確認する",
        "DJに私たちの曲をリクエストする",
        "音楽ストリーミングサービスに加入する",
        "聴いた後にアルバムを評価する",
        "楽器店でギターの弦を買う",
        "おんがく の レッスン",
        "プレイリスト を つくる",
        "コンサート の チケット",
        "アルバム を ダウンロード",
        "ピアノ を れんしゅう",
    ],
    fr=[
        "musique",
        "chanson",
        "mélodie",
        "note",
        "son",
        "rythme",
        "groupe",
        "concert",
        "album",
        "genre",
        "playlist",
        "paroles",
        "morceau",
        "chant",
        "ton",
        "instrument",
        "musicien",
        "spectacle",
        "écouter de la musique en cuisinant",
        "pratiquer la guitare une heure aujourd'hui",
        "faire une playlist pour le road trip",
        "acheter des billets de concert pour le mois prochain",
        "apprendre les paroles de la nouvelle chanson",
        "télécharger l'album avant le vol",
        "trouver de la nouvelle musique pour la playlist sport",
        "accorder la guitare avant la répétition",
        "mettre de la musique comme alarme du matin",
        "écouter le nouvel album le jour de sa sortie",
        "s'inscrire aux cours de musique cet automne",
        "choisir une chanson pour la première danse du mariage",
        "partager la playlist avec les amis",
        "acheter une carte cadeau pour le magasin de musique",
        "écouter le podcast sur l'histoire de la musique",
        "pratiquer les gammes au piano avant le récital",
        "ajouter des chansons à la playlist d'étude",
        "chercher les paroles de la chanson en ligne",
        "assister à l'événement de musique live en ville",
        "enregistrer un mémo vocal de l'idée de mélodie",
        "organiser la bibliothèque musicale par genre",
        "créer une playlist calme pour dormir",
        "réserver la salle de répétition pour le groupe",
        "vérifier la setlist du concert",
        "demander au DJ de passer notre chanson",
        "s'abonner au service de streaming musical",
        "noter l'album après l'écoute",
        "acheter des cordes de guitare au magasin de musique",
        "cours de musiqe cet automne",
        "playlsit pour le road trip",
        "billets de concrt mois prochain",
        "albm à télécharger",
        "pratiqer le piano avant le récital",
        "idée de méloide à enregistrer",
    ],
    es=[
        "música",
        "canción",
        "melodía",
        "nota",
        "sonido",
        "ritmo",
        "banda",
        "concierto",
        "álbum",
        "género",
        "playlist",
        "letra",
        "tema",
        "canto",
        "tono",
        "instrumento",
        "músico",
        "espectáculo",
        "escuchar música mientras cocino",
        "practicar guitarra una hora hoy",
        "hacer una playlist para el viaje en auto",
        "comprar boletos de concierto para el próximo mes",
        "aprender la letra de la nueva canción",
        "descargar el álbum antes del vuelo",
        "encontrar música nueva para la playlist del ejercicio",
        "afinar la guitarra antes del ensayo de la banda",
        "poner música como alarma de la mañana",
        "escuchar el nuevo álbum el día de lanzamiento",
        "inscribirse en clases de música este otoño",
        "elegir una canción para el primer baile de la boda",
        "compartir la playlist con amigos",
        "comprar una tarjeta de regalo para la tienda de música",
        "escuchar el podcast sobre historia de la música",
        "practicar escalas en el piano antes del recital",
        "agregar canciones a la playlist de estudio",
        "buscar la letra de la canción en línea",
        "ir al evento de música en vivo en el centro",
        "grabar una nota de voz con la idea de melodía",
        "organizar la biblioteca musical por género",
        "crear una playlist tranquila para dormir",
        "reservar la sala de ensayo para la banda",
        "revisar la setlist del concierto",
        "pedirle al DJ que ponga nuestra canción",
        "suscribirse al servicio de streaming de música",
        "calificar el álbum después de escucharlo",
        "comprar cuerdas de guitarra en la tienda de música",
        "clases de musica este otoño",
        "playlst para el viaje",
        "boletos de concieto próximo mes",
        "albm descargar antes del vuelo",
        "practicr piano antes del recital",
        "idéa de melodía para grabar",
    ],
)

# ── mustache ─────────────────────────────────────────────────────────────────
build_icon("mustache",
    keep_en=[
        "beard",
        "hair",
        "lumberjack",
        "shave",
        "walrus",
        "whiskers",
        "thick beard and mustache combo",
        "bushy lumberjack mustache with a beard",
        "lumberjack style facial hair",
        "shave off the mustache for a new look",
        "shave styling kit for mustache grooming",
        "walrus-style drooping mustache",
        "grow a mustache for Movember awareness",
        "style a mustache with wax for a sharp curl",
        "mustahce waxed for a curl",
        "mustace grooming kit",
        "moustahce style for Movember",
        "mustche trimmed neatly",
    ],
    new_en=[
        "facial hair",
        "hipster",
        "moustache",
        "mustache",
        "grooming",
        "barber",
        "trim",
        "wax",
        "Movember",
        "handlebar",
        "trim the mustache before the meeting",
        "book a barber appointment for Saturday",
        "buy mustache wax at the grooming store",
        "shape the mustache with a small comb",
        "schedule a beard and mustache trim",
        "try a new mustache style this month",
        "order a mustache grooming kit online",
        "practice curling the handlebar mustache",
        "remind dad about his barber appointment",
        "pick up razors for mustache cleanup",
        "watch a tutorial on mustache styling",
        "enter the Movember mustache contest",
        "donate to Movember through the mustache event",
        "compare beard oils at the barber shop",
        "clean the mustache trimmer after use",
        "buy a mustache comb for the travel kit",
        "dye the mustache to match the hair color",
        "take a before and after mustache photo",
        "set a reminder to trim the mustache weekly",
        "ask the barber for a pencil mustache style",
        "replace the blade on the mustache trimmer",
        "grow out the mustache for the costume party",
        "research vintage mustache styles",
        "buy aftershave for the mustache area",
        "get a hot towel shave at the barber",
        "trim mustach before work",
        "barber appointmnt on Saturday",
        "mustache wax to buy",
        "groom the mustache tomorow",
        "Movember mustach contest",
        "book barber for mustache trm",
        "buy groming kit for mustache",
        "mustache style for the costum party",
    ],
    keep_ru=[
        "борода",
        "волосы",
        "лесоруб",
        "бритье",
        "моржовый",
        "усы",
        "густая борода и усы вместе",
        "пышные усы лесоруба с бородой",
        "растительность на лице в стиле лесоруба",
        "сбрить усы ради нового образа",
        "набор для укладки усов и бритья",
        "моржовые опущенные усы",
        "отрастить усы к movember",
        "уложить усы воском для четкого завитка",
        "усы навощены и закручены",
        "набор для ухода за усами",
        "стиль усов для movember",
        "усы аккуратно подстрижены",
    ],
    new_ru=[
        "растительность на лице",
        "хипстер",
        "усики",
        "усы закрученные",
        "груминг",
        "барбер",
        "стрижка",
        "воск",
        "Мовембер",
        "руль",
        "подстричь усы перед встречей",
        "записаться к барберу на субботу",
        "купить воск для усов в магазине",
        "уложить усы маленькой расчёской",
        "запланировать стрижку бороды и усов",
        "попробовать новый стиль усов в этом месяце",
        "заказать набор для ухода за усами онлайн",
        "потренироваться закручивать усы",
        "напомнить папе про запись к барберу",
        "купить бритвы для подравнивания усов",
        "посмотреть видеоурок по укладке усов",
        "записаться на конкурс усов в Мовембер",
        "поддержать Мовембер через усатый марафон",
        "сравнить масла для бороды в барбершопе",
        "почистить триммер для усов после использования",
        "купить расчёску для усов в дорожный набор",
        "покрасить усы в цвет волос",
        "сделать фото усов до и после",
        "поставить напоминание стричь усы еженедельно",
        "попросить барбера сделать тонкие усы",
        "заменить лезвие на триммере для усов",
        "отрастить усы для костюмированной вечеринки",
        "изучить винтажные стили усов",
        "купить лосьон после бритья для зоны усов",
        "сделать горячее бритьё у барбера",
        "подстрчь усы перед работой",
        "запись к барбру на субботу",
        "воск для усв купить",
        "усы уложть завтра",
        "конкурс усв в Мовембер",
        "записться к барберу на стрижку усов",
        "купть набор для усов",
        "усы для костюмровной вечеринки",
    ],
    de=[
        "Schnurrbart",
        "Bart",
        "Gesichtsbehaarung",
        "Hipster",
        "Oberlippenbart",
        "Pflege",
        "Barbier",
        "Trimmen",
        "Wachs",
        "Movember",
        "Lenker",
        "Rasur",
        "Bartwachs",
        "Barttrimmer",
        "Männerpflege",
        "Bartöl",
        "Rasiermesser",
        "Bartpflege",
        "Schnurrbart vor dem Treffen trimmen",
        "Friseurtermin für Samstag buchen",
        "Schnurrbartwachs im Pflegeladen kaufen",
        "Schnurrbart mit kleinem Kamm formen",
        "Bart- und Schnurrbarttrimm einplanen",
        "neuen Schnurrbartstil diesen Monat ausprobieren",
        "Schnurrbart-Pflegeset online bestellen",
        "Lenkerschnurrbart eindrehen üben",
        "Papa an seinen Friseurtermin erinnern",
        "Rasierer zum Schnurrbart-Nachbessern kaufen",
        "Tutorial zur Schnurrbart-Pflege anschauen",
        "beim Movember-Schnurrbart-Wettbewerb mitmachen",
        "für Movember über das Schnurrbart-Event spenden",
        "Bartöle beim Barbier vergleichen",
        "Schnurrbart-Trimmer nach Gebrauch reinigen",
        "Schnurrbartkamm fürs Reiseset kaufen",
        "Schnurrbart passend zur Haarfarbe färben",
        "Vorher-Nachher-Foto vom Schnurrbart machen",
        "Erinnerung setzen Schnurrbart wöchentlich zu trimmen",
        "Barbier um Bleistift-Schnurrbart bitten",
        "Klinge am Schnurrbart-Trimmer austauschen",
        "Schnurrbart für die Kostümparty wachsen lassen",
        "Vintage-Schnurrbartstile recherchieren",
        "Aftershave für die Schnurrbartzone kaufen",
        "Heißrasur beim Barbier machen",
        "Schnurrbart-Pflege für den Urlaub einpacken",
        "neuen Bartöl-Duft beim Barbier testen",
        "Friseurtermin für Bart und Schnurrbart buchen",
        "Schnurbart trimmen vor der Arbeit",
        "Friseurtermin am Samtag",
        "Schnurrbartwachs kaufn",
        "Schnurrbart pflegn morgen",
        "Movember Schnurrbart-Wettbwerb",
        "Barbier buchen für Schnurbart",
        "Pflegeset für Schnurbart kaufen",
    ],
    ja=[
        "口ひげ",
        "ひげ",
        "顔の毛",
        "ヒップスター",
        "ムスタッシュ",
        "グルーミング",
        "理髪店",
        "トリミング",
        "ワックス",
        "モベンバー",
        "ハンドルバー",
        "シェービング",
        "ひげ用ワックス",
        "ひげトリマー",
        "男性グルーミング",
        "ひげオイル",
        "カミソリ",
        "ひげの手入れ",
        "会議の前に口ひげを整える",
        "土曜日に理髪店の予約をする",
        "グルーミングストアでひげ用ワックスを買う",
        "小さなくしで口ひげを整える",
        "ひげと口ひげのトリミングを予約する",
        "今月新しい口ひげのスタイルを試す",
        "口ひげグルーミングキットをオンラインで注文する",
        "ハンドルバー口ひげのカールを練習する",
        "お父さんに理髪店の予約を思い出させる",
        "口ひげのお手入れ用のカミソリを買う",
        "口ひげスタイリングのチュートリアルを見る",
        "モベンバーの口ひげコンテストに参加する",
        "口ひげイベントを通じてモベンバーに寄付する",
        "理髪店でひげオイルを比較する",
        "使用後にひげトリマーを掃除する",
        "旅行キット用の口ひげくしを買う",
        "髪の色に合わせて口ひげを染める",
        "口ひげのビフォーアフター写真を撮る",
        "毎週口ひげを整えるリマインダーを設定する",
        "理髪師にペンシル口ひげスタイルをお願いする",
        "ひげトリマーの刃を交換する",
        "コスチュームパーティーのために口ひげを伸ばす",
        "ヴィンテージの口ひげスタイルを調べる",
        "口ひげ周りのアフターシェーブを買う",
        "理髪店でホットタオルシェーブをする",
        "旅行用にひげの手入れセットを準備する",
        "理髪店で新しいひげオイルの香りを試す",
        "ひげと口ひげのトリミング予約をする",
        "くちひげ を ととのえる",
        "りはつてん の よやく",
        "ひげ の ワックス を かう",
        "くちひげ を そだてる",
        "グルーミング セット を ちゅうもん",
    ],
    fr=[
        "moustache",
        "barbe",
        "pilosité faciale",
        "hipster",
        "croc",
        "soin",
        "barbier",
        "tailler",
        "cire",
        "Movember",
        "guidon",
        "rasage",
        "cire à moustache",
        "tondeuse à barbe",
        "soin masculin",
        "huile à barbe",
        "rasoir",
        "entretien de la barbe",
        "tailler la moustache avant la réunion",
        "prendre rendez-vous chez le barbier pour samedi",
        "acheter de la cire à moustache au magasin de soins",
        "modeler la moustache avec un petit peigne",
        "planifier une taille de barbe et moustache",
        "essayer un nouveau style de moustache ce mois-ci",
        "commander un kit de soin pour moustache en ligne",
        "s'entraîner à boucler la moustache en guidon",
        "rappeler à papa son rendez-vous chez le barbier",
        "acheter des rasoirs pour nettoyer la moustache",
        "regarder un tutoriel sur le style de moustache",
        "participer au concours de moustache Movember",
        "faire un don à Movember via l'événement moustache",
        "comparer les huiles à barbe chez le barbier",
        "nettoyer la tondeuse à moustache après utilisation",
        "acheter un peigne à moustache pour la trousse de voyage",
        "teindre la moustache pour assortir la couleur des cheveux",
        "prendre une photo avant et après de la moustache",
        "mettre un rappel pour tailler la moustache chaque semaine",
        "demander au barbier un style de moustache crayon",
        "remplacer la lame de la tondeuse à moustache",
        "laisser pousser la moustache pour la soirée costumée",
        "rechercher des styles de moustache vintage",
        "acheter de l'après-rasage pour la zone moustache",
        "se faire raser à chaud chez le barbier",
        "préparer le kit de soin moustache pour les vacances",
        "essayer un nouveau parfum d'huile à barbe chez le barbier",
        "taller la moustache avant le travail",
        "rendez-vous chez le barbir samedi",
        "cire à moustache à achter",
        "moustache à soigner demian",
        "concours de moustache Movembr",
        "barbier pour moustach tailler",
        "kit de soin moustach à acheter",
    ],
    es=[
        "bigote",
        "barba",
        "vello facial",
        "hipster",
        "mostacho",
        "cuidado personal",
        "barbero",
        "recortar",
        "cera",
        "Movember",
        "manillar",
        "afeitado",
        "cera para bigote",
        "recortadora de barba",
        "cuidado masculino",
        "aceite para barba",
        "navaja",
        "cuidado de la barba",
        "recortar el bigote antes de la reunión",
        "hacer cita con el barbero para el sábado",
        "comprar cera para bigote en la tienda",
        "dar forma al bigote con un peine pequeño",
        "programar un recorte de barba y bigote",
        "probar un nuevo estilo de bigote este mes",
        "pedir un kit de cuidado de bigote en línea",
        "practicar enroscar el bigote de manillar",
        "recordarle a papá su cita con el barbero",
        "comprar navajas para limpiar el bigote",
        "ver un tutorial sobre estilo de bigote",
        "participar en el concurso de bigotes de Movember",
        "donar a Movember a través del evento de bigotes",
        "comparar aceites para barba en la barbería",
        "limpiar la recortadora de bigote después de usarla",
        "comprar un peine para bigote para el kit de viaje",
        "teñir el bigote para que combine con el color de pelo",
        "tomar una foto de antes y después del bigote",
        "poner un recordatorio para recortar el bigote cada semana",
        "pedirle al barbero un estilo de bigote lápiz",
        "reemplazar la cuchilla de la recortadora de bigote",
        "dejarse crecer el bigote para la fiesta de disfraces",
        "investigar estilos de bigote vintage",
        "comprar aftershave para la zona del bigote",
        "hacerse un afeitado con toalla caliente en la barbería",
        "preparar el kit de cuidado del bigote para vacaciones",
        "probar un nuevo aroma de aceite para barba en la barbería",
        "recortár el bigote antes del trabajo",
        "cita con el barbro el sábado",
        "cera para bigot comprar",
        "bigote cuidar mañna",
        "concurso de bigotes Movembr",
        "barbero para recortar el bigot",
        "kit de cuidado de bigot comprar",
    ],
)

print("Part 5 done: music, mustache")
