#!/usr/bin/env python3
"""Task-008 Part 1: faucet, ferris-wheel, film, film-canister, fingerprint"""

from gen_icons_task_008_common import gen

# ── faucet ────────────────────────────────────────────────────────────────────
gen("faucet",
    en=[
        # keywords (~18)
        "drip",
        "faucet",
        "leak",
        "plumbing",
        "sink",
        "tap",
        "water",
        "potable water",
        "drinking water",
        "water pressure",
        "kitchen faucet",
        "bathroom faucet",
        "leaky faucet",
        "dripping tap",
        "kitchen sink",
        "bathroom sink",
        "tap water",
        "water filter",
        # phrases (~37)
        "fix the leaky faucet",
        "replace the kitchen faucet",
        "call a plumber for the faucet",
        "turn off the tap",
        "wash dishes in the sink",
        "unclog the sink drain",
        "check the water pressure",
        "clean the faucet aerator",
        "wash hands before eating",
        "filter the drinking water",
        "stop the drip to save water",
        "install a new faucet in the bathroom",
        "tighten the faucet handle",
        "buy a water filter for the tap",
        "schedule a plumber for the leak",
        "replace the old kitchen sink",
        "turn off the water before leaving",
        "check under the sink for leaks",
        "the faucet is dripping again",
        "get a new faucet from the hardware store",
        "bathroom faucet needs replacing",
        "plumber coming Tuesday for the faucet",
        "kitchen sink is clogged again",
        "fix the dripping tap in the bathroom",
        "water bill is high because of the leak",
        "shut off the main water valve",
        "hot water not working in the kitchen",
        "install water-saving faucet heads",
        "the tap keeps dripping at night",
        "replace washers in the faucet",
        "clean the sink drain filter",
        "test the water quality at home",
        "run water for two minutes before drinking",
        "faucet handle is loose",
        "new sink for the kitchen remodel",
        "get plumbing supplies at the store",
        "wash hands after coming home",
        # typos (~5)
        "fix the leakign faucet",
        "wash hads before eating",
        "trun off the taap",
        "replace the kitcen faucet",
        "chek the wter pressure",
    ],
    ru=[
        # keywords (~18)
        "капля",
        "кран",
        "течь",
        "сантехника",
        "раковина",
        "смеситель",
        "вода",
        "питьевая вода",
        "водопровод",
        "напор воды",
        "кухонный кран",
        "кран в ванной",
        "протекающий кран",
        "капающий кран",
        "кухонная раковина",
        "раковина в ванной",
        "водопроводная вода",
        "фильтр для воды",
        # phrases (~37)
        "починить протекающий кран",
        "заменить кран на кухне",
        "вызвать сантехника для крана",
        "выключить кран",
        "мыть посуду в раковине",
        "прочистить слив раковины",
        "проверить напор воды",
        "почистить аэратор крана",
        "мыть руки перед едой",
        "фильтровать питьевую воду",
        "остановить капание крана",
        "установить новый смеситель в ванной",
        "подтянуть ручку крана",
        "купить фильтр для воды на кран",
        "записаться к сантехнику на вторник",
        "заменить старую кухонную раковину",
        "перекрыть воду перед уходом",
        "проверить под раковиной на протечки",
        "кран опять капает",
        "купить новый кран в строительном магазине",
        "смеситель в ванной пора менять",
        "сантехник придёт во вторник чинить кран",
        "кухонная раковина опять засорилась",
        "починить капающий кран в ванной",
        "счёт за воду большой из-за протечки",
        "перекрыть главный водопроводный вентиль",
        "горячая вода не идёт на кухне",
        "поставить водосберегающие насадки на кран",
        "кран продолжает капать ночью",
        "заменить прокладки в кране",
        "почистить фильтр слива раковины",
        "проверить качество воды дома",
        "пропустить воду две минуты перед питьём",
        "ручка крана шатается",
        "новая раковина для ремонта кухни",
        "купить сантехнику в магазине",
        "мыть руки после прихода домой",
        # typos (~5)
        "починить потекающий кран",
        "помыть руик перед едой",
        "выключть кран",
        "заменть кран на кухне",
        "праверить напор воды",
    ],
    de=[
        # keywords (~18)
        "Tropfen",
        "Wasserhahn",
        "Leck",
        "Klempner",
        "Spüle",
        "Hahn",
        "Wasser",
        "Trinkwasser",
        "Leitungswasser",
        "Wasserdruck",
        "Küchenhahn",
        "Badezimmerhahn",
        "tropfender Hahn",
        "undichter Wasserhahn",
        "Küchenspüle",
        "Waschbecken",
        "Wasserfilter",
        "Abfluss",
        # phrases (~37)
        "den tropfenden Wasserhahn reparieren",
        "den Küchenhahn austauschen",
        "Klempner wegen Wasserhahn anrufen",
        "den Hahn zudrehen",
        "Geschirr im Spülbecken abwaschen",
        "den Abfluss der Spüle reinigen",
        "den Wasserdruck überprüfen",
        "den Perlator am Hahn reinigen",
        "Hände vor dem Essen waschen",
        "Trinkwasser filtern",
        "das Tropfen abstellen um Wasser zu sparen",
        "neuen Wasserhahn im Bad einbauen",
        "den Griff am Wasserhahn festziehen",
        "Wasserfilter für den Hahn kaufen",
        "Klempnertermin wegen dem Leck machen",
        "die alte Küchenspüle austauschen",
        "Wasser abstellen bevor ich gehe",
        "unter der Spüle nach Lecks schauen",
        "der Wasserhahn tropft schon wieder",
        "neuen Hahn im Baumarkt holen",
        "Wasserhahn im Bad muss raus",
        "Klempner kommt Dienstag wegen dem Hahn",
        "Küchenspüle ist wieder verstopft",
        "tropfenden Hahn im Bad reparieren",
        "Wasserrechnung ist hoch wegen dem Leck",
        "Hauptwasserventil zudrehen",
        "kein heißes Wasser in der Küche",
        "Wasserspar-Aufsätze für den Hahn einbauen",
        "der Hahn tropft nachts weiter",
        "Dichtungen im Wasserhahn austauschen",
        "Abflusssieb der Spüle säubern",
        "Wasserqualität zu Hause testen",
        "Wasser zwei Minuten laufen lassen vor dem Trinken",
        "Griff am Hahn wackelt",
        "neue Spüle für die Küchenrenovierung",
        "Sanitärbedarf im Baumarkt kaufen",
        "Hände waschen nach dem Heimkommen",
        # typos (~5)
        "den tropfneden Wasserhahn repariren",
        "Hände vor dem Esen waschen",
        "den Han zudrehen",
        "Wasserdurck überprüfen",
        "Küchenhhan austauschen",
    ],
    ja=[
        # keywords (~18)
        "蛇口",
        "水漏れ",
        "水道",
        "配管",
        "シンク",
        "水",
        "飲料水",
        "水圧",
        "キッチンの蛇口",
        "洗面台の蛇口",
        "水漏れ修理",
        "水道水",
        "浄水器",
        "排水口",
        "水回り",
        "給水",
        "水道管",
        "漏水",
        # phrases (~37)
        "蛇口の水漏れを直す",
        "キッチンの蛇口を交換する",
        "水道業者に蛇口の修理を頼む",
        "蛇口を閉める",
        "シンクで食器を洗う",
        "シンクの排水口を掃除する",
        "水圧を確認する",
        "蛇口の泡沫器を掃除する",
        "食事前に手を洗う",
        "飲料水をフィルターにかける",
        "水を節約するために水漏れを止める",
        "洗面所に新しい蛇口を取り付ける",
        "蛇口のハンドルを締め直す",
        "蛇口用の浄水器を買う",
        "水漏れ修理の予約をする",
        "古いキッチンシンクを交換する",
        "出かける前に水を止める",
        "シンクの下の水漏れを確認する",
        "蛇口がまたポタポタ漏れている",
        "ホームセンターで新しい蛇口を買う",
        "洗面所の蛇口を交換する時期だ",
        "火曜日に水道業者が蛇口を直しに来る",
        "キッチンのシンクがまた詰まった",
        "洗面所のポタポタする蛇口を直す",
        "水漏れのせいで水道代が高い",
        "元栓を閉める",
        "キッチンでお湯が出ない",
        "節水シャワーヘッドを蛇口に付ける",
        "夜中に蛇口がポタポタ音がする",
        "蛇口のパッキンを交換する",
        "シンクの排水フィルターを掃除する",
        "自宅の水質を検査する",
        "飲む前に水を2分間流す",
        "蛇口のハンドルがグラグラする",
        "キッチンリフォーム用の新しいシンク",
        "水道用品をお店で買う",
        "帰宅したら手を洗う",
        # typos (~5)
        "蛇口の水もれを直す",
        "食事まえに手をあらう",
        "シンクで食器をあらう",
        "水あつを確認する",
        "蛇口をしめる",
    ],
    fr=[
        # keywords (~18)
        "robinet",
        "fuite",
        "plomberie",
        "évier",
        "eau",
        "eau potable",
        "pression d'eau",
        "robinet de cuisine",
        "robinet de salle de bain",
        "fuite d'eau",
        "robinet qui goutte",
        "lavabo",
        "filtre à eau",
        "tuyauterie",
        "goutte",
        "eau courante",
        "vidange",
        "plombier",
        # phrases (~37)
        "réparer le robinet qui fuit",
        "remplacer le robinet de la cuisine",
        "appeler le plombier pour le robinet",
        "fermer le robinet",
        "faire la vaisselle dans l'évier",
        "déboucher l'évier",
        "vérifier la pression d'eau",
        "nettoyer le mousseur du robinet",
        "se laver les mains avant de manger",
        "filtrer l'eau potable",
        "arrêter la fuite pour économiser l'eau",
        "installer un nouveau robinet dans la salle de bain",
        "resserrer la poignée du robinet",
        "acheter un filtre à eau pour le robinet",
        "prendre rendez-vous avec le plombier pour la fuite",
        "remplacer le vieil évier de la cuisine",
        "couper l'eau avant de partir",
        "vérifier sous l'évier s'il y a des fuites",
        "le robinet goutte encore",
        "acheter un nouveau robinet à la quincaillerie",
        "le robinet de la salle de bain doit être changé",
        "le plombier vient mardi pour le robinet",
        "l'évier de la cuisine est encore bouché",
        "réparer le robinet qui goutte dans la salle de bain",
        "la facture d'eau est élevée à cause de la fuite",
        "fermer la vanne d'eau principale",
        "pas d'eau chaude dans la cuisine",
        "installer des embouts économiseurs d'eau",
        "le robinet continue de couler la nuit",
        "changer les joints du robinet",
        "nettoyer le filtre du siphon",
        "tester la qualité de l'eau à la maison",
        "laisser couler l'eau deux minutes avant de boire",
        "la poignée du robinet est desserrée",
        "nouvel évier pour la rénovation de la cuisine",
        "acheter des fournitures de plomberie",
        "se laver les mains en rentrant",
        # typos (~5)
        "réparer le robnet qui fuit",
        "se laver les mians avant de manger",
        "fermr le robinet",
        "vérifier la presion d'eau",
        "remplacer le robienet de cuisine",
    ],
    es=[
        # keywords (~18)
        "grifo",
        "fuga",
        "fontanería",
        "fregadero",
        "agua",
        "agua potable",
        "presión de agua",
        "grifo de cocina",
        "grifo del baño",
        "fuga de agua",
        "grifo que gotea",
        "lavabo",
        "filtro de agua",
        "tubería",
        "goteo",
        "agua corriente",
        "desagüe",
        "fontanero",
        # phrases (~37)
        "arreglar el grifo que gotea",
        "cambiar el grifo de la cocina",
        "llamar al fontanero por el grifo",
        "cerrar el grifo",
        "lavar los platos en el fregadero",
        "desatascar el fregadero",
        "revisar la presión de agua",
        "limpiar el aireador del grifo",
        "lavarse las manos antes de comer",
        "filtrar el agua potable",
        "parar el goteo para ahorrar agua",
        "instalar un grifo nuevo en el baño",
        "apretar la manija del grifo",
        "comprar un filtro de agua para el grifo",
        "pedir cita con el fontanero por la fuga",
        "cambiar el fregadero viejo de la cocina",
        "cortar el agua antes de salir",
        "revisar debajo del fregadero por fugas",
        "el grifo está goteando otra vez",
        "comprar un grifo nuevo en la ferretería",
        "el grifo del baño hay que cambiarlo",
        "el fontanero viene el martes por el grifo",
        "el fregadero de la cocina está atascado otra vez",
        "arreglar el grifo que gotea en el baño",
        "la factura del agua está alta por la fuga",
        "cerrar la llave de paso principal",
        "no sale agua caliente en la cocina",
        "poner cabezales ahorradores de agua",
        "el grifo sigue goteando de noche",
        "cambiar las juntas del grifo",
        "limpiar el filtro del desagüe",
        "analizar la calidad del agua en casa",
        "dejar correr el agua dos minutos antes de beber",
        "la manija del grifo está floja",
        "fregadero nuevo para la reforma de la cocina",
        "comprar material de fontanería",
        "lavarse las manos al llegar a casa",
        # typos (~5)
        "arreglar el grfo que gotea",
        "lavarse las mnaos antes de comer",
        "cerrar el gripo",
        "revisar la precion de agua",
        "cambiar el griifo de cocina",
    ],
)

# ── ferris-wheel ──────────────────────────────────────────────────────────────
gen("ferris-wheel",
    en=[
        "amusement park",
        "carnival",
        "fair",
        "ferris wheel",
        "ride",
        "theme park",
        "big wheel",
        "funfair",
        "roller coaster",
        "bumper cars",
        "cotton candy",
        "ticket booth",
        "carousel",
        "midway",
        "state fair",
        "county fair",
        "thrill ride",
        "amusement ride",
        "buy tickets to the amusement park",
        "go to the state fair this weekend",
        "ride the ferris wheel at the carnival",
        "take the kids to the theme park",
        "plan a day at the amusement park",
        "wait in line for the ferris wheel",
        "see the view from the top of the ferris wheel",
        "visit the theme park on Saturday",
        "eat carnival food at the fair",
        "get cotton candy at the fair",
        "ride the roller coaster at the park",
        "buy season passes for the theme park",
        "take photos from the ferris wheel",
        "find parking at the amusement park",
        "check the theme park hours",
        "bring sunscreen to the amusement park",
        "meet at the ferris wheel entrance",
        "the carnival is in town this week",
        "county fair opens on Friday",
        "get wristbands for unlimited rides",
        "the kids want to go on the ferris wheel again",
        "pick up carnival tickets at the gate",
        "theme park day with the family",
        "try every ride at the fair",
        "watch the fireworks at the amusement park",
        "the ferris wheel has a long wait",
        "pack snacks for the theme park trip",
        "book hotel near the theme park",
        "ride the bumper cars at the carnival",
        "win a prize at the carnival game",
        "the fair closes at ten tonight",
        "get fast passes for the theme park",
        "carousel ride for the little ones",
        "bring jackets for the evening rides",
        "check weather before the amusement park",
        "plan the birthday party at the amusement park",
        "ride the ferris whele",
        "visit the amsuement park",
        "go to the couty fair",
        "theme pakr with kids",
        "buy carnvial tickets",
    ],
    ru=[
        "парк развлечений",
        "карнавал",
        "ярмарка",
        "колесо обозрения",
        "аттракцион",
        "тематический парк",
        "большое колесо",
        "луна-парк",
        "американские горки",
        "автодром",
        "сахарная вата",
        "касса",
        "карусель",
        "городская ярмарка",
        "ярмарка выходного дня",
        "билеты на аттракционы",
        "детские аттракционы",
        "парк аттракционов",
        "купить билеты в парк развлечений",
        "сходить на ярмарку в эти выходные",
        "покататься на колесе обозрения на карнавале",
        "отвезти детей в тематический парк",
        "запланировать день в парке развлечений",
        "подождать в очереди на колесо обозрения",
        "посмотреть вид с вершины колеса обозрения",
        "посетить тематический парк в субботу",
        "поесть карнавальную еду на ярмарке",
        "купить сахарную вату на ярмарке",
        "покататься на американских горках в парке",
        "купить абонемент в тематический парк",
        "сфотографироваться с колеса обозрения",
        "найти парковку у парка развлечений",
        "проверить расписание тематического парка",
        "взять солнцезащитный крем в парк развлечений",
        "встретиться у входа на колесо обозрения",
        "карнавал приехал в город на этой неделе",
        "городская ярмарка открывается в пятницу",
        "взять браслеты на все аттракционы",
        "дети хотят ещё раз на колесо обозрения",
        "забрать билеты на карнавал у входа",
        "день в тематическом парке с семьёй",
        "попробовать все аттракционы на ярмарке",
        "посмотреть фейерверк в парке развлечений",
        "на колесо обозрения большая очередь",
        "взять перекус в тематический парк",
        "забронировать отель рядом с тематическим парком",
        "покататься на автодроме на карнавале",
        "выиграть приз в карнавальной игре",
        "ярмарка закрывается в десять вечера",
        "купить быстрые пропуска в тематический парк",
        "карусель для малышей",
        "взять куртки на вечерние аттракционы",
        "проверить погоду перед парком развлечений",
        "устроить день рождения в парке развлечений",
        "покататся на колесе обозрения",
        "посетть тематический парк",
        "купть билеты на ярмарку",
        "парк развлечний с детьми",
        "сходть на карнавал",
    ],
    de=[
        "Freizeitpark",
        "Karneval",
        "Jahrmarkt",
        "Riesenrad",
        "Fahrgeschäft",
        "Themenpark",
        "Kirmes",
        "Rummel",
        "Achterbahn",
        "Autoscooter",
        "Zuckerwatte",
        "Karussell",
        "Volksfest",
        "Stadtfest",
        "Fahrkarte",
        "Kettenkarussell",
        "Schaukel",
        "Festplatz",
        "Tickets für den Freizeitpark kaufen",
        "am Wochenende zum Jahrmarkt gehen",
        "Riesenrad auf dem Karneval fahren",
        "die Kinder in den Themenpark bringen",
        "einen Tag im Freizeitpark planen",
        "am Riesenrad anstehen",
        "die Aussicht vom Riesenrad genießen",
        "den Themenpark am Samstag besuchen",
        "Jahrmarktessen probieren",
        "Zuckerwatte auf dem Jahrmarkt kaufen",
        "Achterbahn im Freizeitpark fahren",
        "Saisonkarten für den Themenpark kaufen",
        "Fotos vom Riesenrad machen",
        "Parkplatz am Freizeitpark finden",
        "Öffnungszeiten vom Themenpark prüfen",
        "Sonnencreme für den Freizeitpark einpacken",
        "am Riesenrad-Eingang treffen",
        "der Karneval ist diese Woche in der Stadt",
        "Volksfest beginnt am Freitag",
        "Bändchen für alle Fahrgeschäfte holen",
        "die Kinder wollen nochmal aufs Riesenrad",
        "Karneval-Tickets am Eingang abholen",
        "Themenpark-Tag mit der Familie",
        "jedes Fahrgeschäft auf dem Jahrmarkt ausprobieren",
        "Feuerwerk im Freizeitpark ansehen",
        "am Riesenrad ist lange Wartezeit",
        "Snacks für den Themenpark-Ausflug einpacken",
        "Hotel in der Nähe des Themenparks buchen",
        "Autoscooter auf dem Karneval fahren",
        "einen Preis beim Karnevalsspiel gewinnen",
        "der Jahrmarkt schließt um zehn heute Abend",
        "Schnellpässe für den Themenpark holen",
        "Karussell für die Kleinen",
        "Jacken für die Abendfahrten mitnehmen",
        "Wetter prüfen bevor es zum Freizeitpark geht",
        "Kindergeburtstag im Freizeitpark planen",
        "Riesenrad auf dem Karnevl fahren",
        "Freizeitprak besuchen",
        "Tickets für den Themenprak kaufen",
        "Achterbhan im Park fahren",
        "Zuckerwate auf dem Jahrmarkt",
    ],
    ja=[
        "遊園地",
        "カーニバル",
        "お祭り",
        "観覧車",
        "乗り物",
        "テーマパーク",
        "ジェットコースター",
        "ゴーカート",
        "綿あめ",
        "チケット売り場",
        "メリーゴーランド",
        "屋台",
        "縁日",
        "アトラクション",
        "入場券",
        "遊具",
        "フリーパス",
        "移動遊園地",
        "遊園地のチケットを買う",
        "週末にお祭りに行く",
        "カーニバルで観覧車に乗る",
        "子供たちをテーマパークに連れて行く",
        "遊園地での一日を計画する",
        "観覧車の列に並ぶ",
        "観覧車の頂上から景色を見る",
        "土曜日にテーマパークに行く",
        "お祭りで屋台の食べ物を食べる",
        "お祭りで綿あめを買う",
        "遊園地でジェットコースターに乗る",
        "テーマパークの年間パスを買う",
        "観覧車から写真を撮る",
        "遊園地の駐車場を探す",
        "テーマパークの営業時間を確認する",
        "遊園地に日焼け止めを持っていく",
        "観覧車の入口で待ち合わせ",
        "今週カーニバルが街に来ている",
        "お祭りは金曜日に始まる",
        "乗り放題のリストバンドをもらう",
        "子供たちがまた観覧車に乗りたがっている",
        "カーニバルのチケットを入口で受け取る",
        "家族でテーマパークの日",
        "お祭りの全部のアトラクションに乗る",
        "遊園地で花火を見る",
        "観覧車は待ち時間が長い",
        "テーマパークにおやつを持っていく",
        "テーマパーク近くのホテルを予約する",
        "カーニバルでゴーカートに乗る",
        "カーニバルのゲームで景品を取る",
        "お祭りは今夜10時に終わる",
        "テーマパークのファストパスを取る",
        "小さい子用のメリーゴーランド",
        "夜の乗り物用にジャケットを持っていく",
        "遊園地に行く前に天気を確認する",
        "遊園地で誕生日パーティーをする",
        "遊園地のチケトを買う",
        "テーマパクに行く",
        "観覧車にのる",
        "お祭りにいく",
        "ジェットコースタに乗る",
    ],
    fr=[
        "parc d'attractions",
        "carnaval",
        "foire",
        "grande roue",
        "manège",
        "parc à thème",
        "fête foraine",
        "montagnes russes",
        "auto-tamponneuses",
        "barbe à papa",
        "billetterie",
        "carrousel",
        "kermesse",
        "attraction",
        "billet d'entrée",
        "stand de jeux",
        "toboggan",
        "parc de loisirs",
        "acheter des billets pour le parc d'attractions",
        "aller à la foire ce week-end",
        "faire un tour de grande roue au carnaval",
        "emmener les enfants au parc à thème",
        "planifier une journée au parc d'attractions",
        "faire la queue pour la grande roue",
        "admirer la vue du haut de la grande roue",
        "visiter le parc à thème samedi",
        "manger de la nourriture de foire",
        "acheter de la barbe à papa à la foire",
        "faire les montagnes russes au parc",
        "acheter des abonnements pour le parc à thème",
        "prendre des photos depuis la grande roue",
        "trouver le parking du parc d'attractions",
        "vérifier les horaires du parc à thème",
        "prendre de la crème solaire pour le parc",
        "se retrouver à l'entrée de la grande roue",
        "le carnaval est en ville cette semaine",
        "la foire ouvre vendredi",
        "prendre des bracelets pour tous les manèges",
        "les enfants veulent refaire la grande roue",
        "récupérer les billets du carnaval à l'entrée",
        "journée au parc à thème en famille",
        "essayer tous les manèges de la foire",
        "regarder le feu d'artifice au parc d'attractions",
        "la grande roue a une longue file d'attente",
        "emporter des goûters pour le parc à thème",
        "réserver un hôtel près du parc à thème",
        "faire les auto-tamponneuses au carnaval",
        "gagner un prix au jeu de la foire",
        "la foire ferme à vingt-deux heures ce soir",
        "prendre des coupe-files pour le parc à thème",
        "le carrousel pour les plus petits",
        "prendre des vestes pour les manèges du soir",
        "vérifier la météo avant le parc d'attractions",
        "organiser l'anniversaire au parc d'attractions",
        "faire un tour de grnade roue",
        "parc d'attrctions ce week-end",
        "acheter des billets pour le carnval",
        "emmener les enfnats au parc",
        "vérifier les horiares du parc",
    ],
    es=[
        "parque de atracciones",
        "carnaval",
        "feria",
        "noria",
        "atracción",
        "parque temático",
        "feria del pueblo",
        "montaña rusa",
        "autos de choque",
        "algodón de azúcar",
        "taquilla",
        "carrusel",
        "verbena",
        "recinto ferial",
        "entrada",
        "tiovivo",
        "caseta de feria",
        "parque de diversiones",
        "comprar entradas para el parque de atracciones",
        "ir a la feria este fin de semana",
        "montar en la noria del carnaval",
        "llevar a los niños al parque temático",
        "planear un día en el parque de atracciones",
        "hacer cola para la noria",
        "ver las vistas desde la noria",
        "visitar el parque temático el sábado",
        "comer comida de feria",
        "comprar algodón de azúcar en la feria",
        "montar en la montaña rusa del parque",
        "comprar pases de temporada para el parque temático",
        "sacar fotos desde la noria",
        "buscar aparcamiento en el parque de atracciones",
        "consultar el horario del parque temático",
        "llevar protector solar al parque de atracciones",
        "quedar en la entrada de la noria",
        "el carnaval está en la ciudad esta semana",
        "la feria del pueblo empieza el viernes",
        "conseguir pulseras para todas las atracciones",
        "los niños quieren subir otra vez a la noria",
        "recoger las entradas del carnaval en la puerta",
        "día de parque temático con la familia",
        "probar todas las atracciones de la feria",
        "ver los fuegos artificiales en el parque",
        "hay mucha cola en la noria",
        "llevar snacks al parque temático",
        "reservar hotel cerca del parque temático",
        "montar en los autos de choque del carnaval",
        "ganar un premio en el juego de la feria",
        "la feria cierra a las diez esta noche",
        "sacar pases rápidos para el parque temático",
        "el carrusel para los más pequeños",
        "llevar chaquetas para las atracciones de noche",
        "mirar el tiempo antes del parque de atracciones",
        "organizar el cumpleaños en el parque de atracciones",
        "montar en la noira del carnaval",
        "parque de atraccones este fin de semana",
        "comprar entrdas para el parque",
        "llevar a los niñso al parque temático",
        "ver las vitsas desde la noria",
    ],
)

# ── film ──────────────────────────────────────────────────────────────────────
gen("film",
    en=[
        "cinema",
        "film",
        "movie",
        "reel",
        "strip",
        "video",
        "movie night",
        "film festival",
        "movie theater",
        "film premiere",
        "movie trailer",
        "film screening",
        "blockbuster",
        "documentary",
        "short film",
        "feature film",
        "movie tickets",
        "film review",
        "go to the cinema tonight",
        "buy movie tickets online",
        "watch a film at home",
        "choose a film to watch this weekend",
        "watch the movie trailer before deciding",
        "download a movie for the flight",
        "attend the film festival downtown",
        "see the new film premiere",
        "stream a film on the couch",
        "plan a movie night with friends",
        "review the film for the blog",
        "watch a classic film with the family",
        "buy popcorn at the movie theater",
        "find showtimes at the cinema",
        "the new movie comes out Friday",
        "rent a movie for tonight",
        "check reviews before picking a film",
        "film festival starts next week",
        "movie night on Saturday at our place",
        "watch the documentary about ocean life",
        "record a short video for the project",
        "edit the video before posting",
        "submit the short film to the competition",
        "pick up the projector for movie night",
        "book seats for the evening show",
        "the film got great reviews",
        "watch the sequel to that movie",
        "bring snacks for the movie marathon",
        "subtitles for the foreign film",
        "catch the late showing at the cinema",
        "recommend a good film to watch",
        "new film release this week",
        "grab dinner before the movie",
        "charge the laptop for movie night",
        "cancel the movie if it rains",
        "reserve IMAX tickets for Saturday",
        "go to the ciinema",
        "wathc a flim tonight",
        "buy movei tickets",
        "straeam a film",
        "moive night on Saturday",
    ],
    ru=[
        "кино",
        "фильм",
        "кинотеатр",
        "видео",
        "кинолента",
        "киноплёнка",
        "киновечер",
        "кинофестиваль",
        "премьера фильма",
        "трейлер фильма",
        "киносеанс",
        "блокбастер",
        "документальный фильм",
        "короткометражка",
        "полнометражный фильм",
        "билеты в кино",
        "рецензия на фильм",
        "киноафиша",
        "сходить в кино сегодня вечером",
        "купить билеты в кинотеатр онлайн",
        "посмотреть фильм дома",
        "выбрать фильм на выходные",
        "посмотреть трейлер фильма перед выбором",
        "скачать фильм на самолёт",
        "сходить на кинофестиваль в центре города",
        "пойти на премьеру нового фильма",
        "включить фильм на диване",
        "устроить киновечер с друзьями",
        "написать рецензию на фильм",
        "посмотреть классический фильм с семьёй",
        "купить попкорн в кинотеатре",
        "узнать расписание сеансов в кино",
        "новый фильм выходит в пятницу",
        "взять фильм напрокат на вечер",
        "почитать отзывы перед выбором фильма",
        "кинофестиваль начинается на следующей неделе",
        "киновечер в субботу у нас дома",
        "посмотреть документальный фильм о жизни океана",
        "записать короткое видео для проекта",
        "смонтировать видео перед публикацией",
        "отправить короткометражку на конкурс",
        "забрать проектор для киновечера",
        "забронировать места на вечерний сеанс",
        "фильм получил отличные отзывы",
        "посмотреть продолжение того фильма",
        "взять закуски для киномарафона",
        "субтитры к зарубежному фильму",
        "успеть на поздний сеанс в кинотеатре",
        "порекомендовать хороший фильм",
        "новый фильм в прокате на этой неделе",
        "поужинать перед кино",
        "зарядить ноутбук для киновечера",
        "отменить кино если будет дождь",
        "забронировать IMAX на субботу",
        "сходть в кино сегодня",
        "посмотерть фильм дома",
        "купть билеты в кинотеатр",
        "включть фильм на диване",
        "киновечр с друзьями",
    ],
    de=[
        "Kino",
        "Film",
        "Spielfilm",
        "Filmrolle",
        "Filmstreifen",
        "Video",
        "Filmabend",
        "Filmfestival",
        "Kinovorstellung",
        "Filmpremiere",
        "Filmtrailer",
        "Kinokarte",
        "Blockbuster",
        "Dokumentarfilm",
        "Kurzfilm",
        "Kinofilm",
        "Filmkritik",
        "Kinoprogramm",
        "heute Abend ins Kino gehen",
        "Kinokarten online kaufen",
        "einen Film zu Hause schauen",
        "einen Film fürs Wochenende aussuchen",
        "den Filmtrailer vor der Entscheidung anschauen",
        "einen Film für den Flug herunterladen",
        "zum Filmfestival in der Innenstadt gehen",
        "zur Filmpremiere gehen",
        "einen Film auf dem Sofa streamen",
        "einen Filmabend mit Freunden planen",
        "eine Filmkritik schreiben",
        "einen Klassiker mit der Familie schauen",
        "Popcorn im Kino kaufen",
        "Vorstellungszeiten im Kino prüfen",
        "der neue Film kommt am Freitag raus",
        "einen Film für heute Abend ausleihen",
        "Bewertungen vor der Filmwahl lesen",
        "Filmfestival beginnt nächste Woche",
        "Filmabend am Samstag bei uns",
        "den Dokumentarfilm über Meeresleben schauen",
        "ein kurzes Video fürs Projekt aufnehmen",
        "das Video vor dem Posten bearbeiten",
        "den Kurzfilm zum Wettbewerb einreichen",
        "den Projektor für den Filmabend holen",
        "Plätze für die Abendvorstellung buchen",
        "der Film hat super Kritiken bekommen",
        "die Fortsetzung des Films schauen",
        "Snacks für den Filmmarathon mitbringen",
        "Untertitel für den ausländischen Film",
        "die Spätvorstellung im Kino erwischen",
        "einen guten Film empfehlen",
        "neuer Filmstart diese Woche",
        "vor dem Film noch Abendessen",
        "den Laptop für den Filmabend laden",
        "Kino absagen falls es regnet",
        "IMAX-Tickets für Samstag reservieren",
        "heute Abned ins Kino gehen",
        "einen Flim zu Hause schauen",
        "Kinokaten online kaufen",
        "Filmabned mit Freunden",
        "einen Fil fürs Wochenende",
    ],
    ja=[
        "映画",
        "映画館",
        "フィルム",
        "動画",
        "映画祭",
        "上映",
        "予告編",
        "映画の夜",
        "映画チケット",
        "ドキュメンタリー",
        "短編映画",
        "長編映画",
        "ブロックバスター",
        "映画レビュー",
        "映画鑑賞",
        "ビデオ編集",
        "映画プレミア",
        "上映時間",
        "今夜映画館に行く",
        "映画チケットをオンラインで買う",
        "家で映画を観る",
        "週末に観る映画を選ぶ",
        "決める前に予告編を観る",
        "飛行機用に映画をダウンロードする",
        "街の映画祭に行く",
        "新作映画のプレミアに行く",
        "ソファで映画をストリーミングする",
        "友達と映画の夜を計画する",
        "映画のレビューを書く",
        "家族でクラシック映画を観る",
        "映画館でポップコーンを買う",
        "映画館の上映時間を調べる",
        "新作映画が金曜日に公開される",
        "今夜の映画をレンタルする",
        "映画を選ぶ前にレビューを確認する",
        "映画祭は来週始まる",
        "土曜日にうちで映画の夜",
        "海の生き物のドキュメンタリーを観る",
        "プロジェクト用の短い動画を撮る",
        "投稿前に動画を編集する",
        "短編映画をコンペに応募する",
        "映画の夜用にプロジェクターを取りに行く",
        "夜の上映の席を予約する",
        "あの映画は評判がいい",
        "あの映画の続編を観る",
        "映画マラソン用のおやつを持っていく",
        "外国映画の字幕",
        "映画館のレイトショーに間に合う",
        "おすすめの映画を教える",
        "今週の新作映画",
        "映画の前に夕食を食べる",
        "映画の夜用にノートパソコンを充電する",
        "雨なら映画をキャンセルする",
        "土曜日のIMAXチケットを予約する",
        "今夜映画感に行く",
        "映画チケトをオンラインで買う",
        "家で映画をみる",
        "映画のよるを計画する",
        "予告へんを観る",
    ],
    fr=[
        "cinéma",
        "film",
        "long-métrage",
        "bobine",
        "pellicule",
        "vidéo",
        "soirée cinéma",
        "festival de cinéma",
        "salle de cinéma",
        "avant-première",
        "bande-annonce",
        "séance",
        "blockbuster",
        "documentaire",
        "court-métrage",
        "billet de cinéma",
        "critique de film",
        "programme cinéma",
        "aller au cinéma ce soir",
        "acheter des places de cinéma en ligne",
        "regarder un film à la maison",
        "choisir un film pour le week-end",
        "regarder la bande-annonce avant de choisir",
        "télécharger un film pour l'avion",
        "aller au festival de cinéma en ville",
        "aller à l'avant-première du nouveau film",
        "regarder un film sur le canapé",
        "organiser une soirée cinéma avec des amis",
        "écrire une critique de film",
        "regarder un classique en famille",
        "acheter du popcorn au cinéma",
        "vérifier les horaires de séance au cinéma",
        "le nouveau film sort vendredi",
        "louer un film pour ce soir",
        "lire les critiques avant de choisir un film",
        "le festival de cinéma commence la semaine prochaine",
        "soirée cinéma samedi chez nous",
        "regarder le documentaire sur la vie marine",
        "enregistrer une courte vidéo pour le projet",
        "monter la vidéo avant de publier",
        "soumettre le court-métrage au concours",
        "récupérer le projecteur pour la soirée cinéma",
        "réserver des places pour la séance du soir",
        "le film a reçu de très bonnes critiques",
        "regarder la suite de ce film",
        "apporter des snacks pour le marathon de films",
        "sous-titres pour le film étranger",
        "attraper la séance tardive au cinéma",
        "recommander un bon film à regarder",
        "nouvelle sortie de film cette semaine",
        "dîner avant le film",
        "charger le portable pour la soirée cinéma",
        "annuler le ciné s'il pleut",
        "réserver des places IMAX pour samedi",
        "aller au cinmea ce soir",
        "acheter des places de cinéam",
        "regarger un film à la maison",
        "soirée cinéam samedi",
        "choisir un flim pour le week-end",
    ],
    es=[
        "cine",
        "película",
        "largometraje",
        "rollo de película",
        "tira de película",
        "video",
        "noche de cine",
        "festival de cine",
        "sala de cine",
        "estreno",
        "tráiler",
        "sesión",
        "taquillera",
        "documental",
        "cortometraje",
        "entrada de cine",
        "crítica de cine",
        "cartelera",
        "ir al cine esta noche",
        "comprar entradas de cine en línea",
        "ver una película en casa",
        "elegir una película para el fin de semana",
        "ver el tráiler antes de decidir",
        "descargar una película para el avión",
        "ir al festival de cine en el centro",
        "ir al estreno de la nueva película",
        "poner una película en el sofá",
        "organizar una noche de cine con amigos",
        "escribir una crítica de la película",
        "ver un clásico en familia",
        "comprar palomitas en el cine",
        "consultar la cartelera del cine",
        "la nueva película se estrena el viernes",
        "alquilar una película para esta noche",
        "leer reseñas antes de elegir película",
        "el festival de cine empieza la semana que viene",
        "noche de cine el sábado en nuestra casa",
        "ver el documental sobre la vida marina",
        "grabar un video corto para el proyecto",
        "editar el video antes de publicar",
        "enviar el cortometraje al concurso",
        "recoger el proyector para la noche de cine",
        "reservar asientos para la sesión de la noche",
        "la película tiene muy buenas críticas",
        "ver la secuela de esa película",
        "llevar snacks para el maratón de películas",
        "subtítulos para la película extranjera",
        "llegar a la sesión de noche del cine",
        "recomendar una buena película",
        "nuevo estreno esta semana",
        "cenar antes de la película",
        "cargar el portátil para la noche de cine",
        "cancelar el cine si llueve",
        "reservar entradas IMAX para el sábado",
        "ir al cien esta noche",
        "comprar enrtadas de cine",
        "ver una pelícla en casa",
        "noche de cien el sábado",
        "elegir una pelicual para el fin de semana",
    ],
)

# ── film-canister ─────────────────────────────────────────────────────────────
gen("film-canister",
    en=[
        "film",
        "negative",
        "photography",
        "retro",
        "roll",
        "35mm",
        "darkroom",
        "analog",
        "film roll",
        "develop film",
        "film camera",
        "vintage camera",
        "disposable camera",
        "photo paper",
        "film photography",
        "film canister",
        "exposure",
        "light meter",
        "develop the film roll at the lab",
        "buy a roll of 35mm film",
        "shoot with a film camera this weekend",
        "set up a darkroom at home",
        "take the film to be developed",
        "scan the developed negatives",
        "print photos from the film negatives",
        "buy a disposable camera for the trip",
        "learn film photography basics",
        "try shooting on film for the first time",
        "find a darkroom to rent",
        "practice analog photography",
        "get a retro look with film grain",
        "find a vintage film camera online",
        "shoot a roll of black and white film",
        "load the film canister into the camera",
        "check the exposure settings on the camera",
        "buy photo paper for darkroom prints",
        "the film needs to be developed before Friday",
        "pick up the developed photos from the lab",
        "film photography class on Saturday",
        "bring extra film rolls for the trip",
        "store film canisters in a cool place",
        "compare digital and analog photography",
        "the vintage camera shop has 35mm film",
        "finish shooting the roll before developing",
        "take portraits on film",
        "use a light meter for the exposure",
        "the film came out great after developing",
        "try color and black and white film",
        "gift a disposable camera for the party",
        "film photography project for school",
        "organize old negatives in an album",
        "shoot with 35mm flim",
        "devlop the film roll",
        "by a disposbale camera",
        "vintge film photography",
        "darkrom developing",
    ],
    ru=[
        "плёнка",
        "негатив",
        "фотография",
        "ретро",
        "рулон",
        "35 мм",
        "тёмная комната",
        "аналоговый",
        "рулон плёнки",
        "проявить плёнку",
        "плёночная камера",
        "винтажная камера",
        "одноразовая камера",
        "фотобумага",
        "плёночная фотография",
        "кассета с плёнкой",
        "экспозиция",
        "экспонометр",
        "проявить рулон плёнки в лаборатории",
        "купить рулон плёнки 35 мм",
        "снимать на плёночную камеру в выходные",
        "оборудовать тёмную комнату дома",
        "отнести плёнку на проявку",
        "отсканировать проявленные негативы",
        "напечатать фотографии с негативов",
        "купить одноразовую камеру для поездки",
        "изучить основы плёночной фотографии",
        "впервые попробовать снимать на плёнку",
        "найти тёмную комнату в аренду",
        "практиковаться в аналоговой фотографии",
        "получить ретро-эффект с зернистостью плёнки",
        "найти винтажную плёночную камеру онлайн",
        "снять рулон чёрно-белой плёнки",
        "зарядить кассету с плёнкой в камеру",
        "проверить настройки экспозиции на камере",
        "купить фотобумагу для печати в тёмной комнате",
        "плёнку нужно проявить до пятницы",
        "забрать проявленные фотографии из лаборатории",
        "курсы плёночной фотографии в субботу",
        "взять запасные рулоны плёнки в поездку",
        "хранить кассеты с плёнкой в прохладном месте",
        "сравнить цифровую и аналоговую фотографию",
        "в магазине винтажных камер есть плёнка 35 мм",
        "доснять рулон перед проявкой",
        "снять портреты на плёнку",
        "использовать экспонометр для настройки экспозиции",
        "плёнка отлично получилась после проявки",
        "попробовать цветную и чёрно-белую плёнку",
        "подарить одноразовую камеру на вечеринку",
        "проект по плёночной фотографии для учёбы",
        "разобрать старые негативы по альбомам",
        "снимать на 35-мм плонку",
        "проявть рулон плёнки",
        "купить одноразовою камеру",
        "винтажная плёнчная фотография",
        "тёмная комнта для проявки",
    ],
    de=[
        "Film",
        "Negativ",
        "Fotografie",
        "Retro",
        "Filmrolle",
        "35mm",
        "Dunkelkammer",
        "Analog",
        "Filmpatrone",
        "Film entwickeln",
        "Filmkamera",
        "Vintage-Kamera",
        "Einwegkamera",
        "Fotopapier",
        "Analogfotografie",
        "Belichtung",
        "Belichtungsmesser",
        "Schwarzweißfilm",
        "den Film im Labor entwickeln lassen",
        "eine Rolle 35mm-Film kaufen",
        "am Wochenende mit der Filmkamera fotografieren",
        "eine Dunkelkammer zu Hause einrichten",
        "den Film zum Entwickeln bringen",
        "die entwickelten Negative scannen",
        "Fotos von den Negativen drucken",
        "eine Einwegkamera für die Reise kaufen",
        "Grundlagen der Filmfotografie lernen",
        "zum ersten Mal auf Film fotografieren",
        "eine Dunkelkammer zum Mieten finden",
        "Analogfotografie üben",
        "Retro-Look mit Filmkorn erzielen",
        "eine Vintage-Filmkamera online finden",
        "eine Rolle Schwarzweißfilm fotografieren",
        "die Filmpatrone in die Kamera einlegen",
        "die Belichtungseinstellungen prüfen",
        "Fotopapier für Dunkelkammer-Abzüge kaufen",
        "der Film muss vor Freitag entwickelt werden",
        "die entwickelten Fotos aus dem Labor abholen",
        "Filmfotografie-Kurs am Samstag",
        "extra Filmrollen für die Reise mitnehmen",
        "Filmpatronen kühl lagern",
        "digitale und analoge Fotografie vergleichen",
        "der Vintage-Laden hat 35mm-Film",
        "die Rolle fertig fotografieren vor dem Entwickeln",
        "Porträts auf Film aufnehmen",
        "einen Belichtungsmesser verwenden",
        "der Film ist nach dem Entwickeln toll geworden",
        "Farb- und Schwarzweißfilm ausprobieren",
        "eine Einwegkamera für die Party schenken",
        "Filmfotografie-Projekt für die Schule",
        "alte Negative in ein Album sortieren",
        "mit 35mm Flim fotografieren",
        "den Flim entwickeln lassen",
        "Einwegkamra für die Reise",
        "Vintge Filmkamera",
        "Dunkelkamer einrichten",
    ],
    ja=[
        "フィルム",
        "ネガ",
        "写真",
        "レトロ",
        "ロール",
        "35ミリ",
        "暗室",
        "アナログ",
        "フィルムロール",
        "フィルム現像",
        "フィルムカメラ",
        "ヴィンテージカメラ",
        "使い捨てカメラ",
        "印画紙",
        "フィルム写真",
        "フィルムケース",
        "露出",
        "露出計",
        "ラボでフィルムを現像する",
        "35ミリフィルムを一本買う",
        "週末にフィルムカメラで撮影する",
        "自宅に暗室を作る",
        "フィルムを現像に出す",
        "現像したネガをスキャンする",
        "ネガから写真をプリントする",
        "旅行用に使い捨てカメラを買う",
        "フィルム写真の基本を学ぶ",
        "初めてフィルムで撮影してみる",
        "レンタルできる暗室を探す",
        "アナログ写真を練習する",
        "フィルムの粒子感でレトロな雰囲気を出す",
        "ヴィンテージのフィルムカメラをオンラインで探す",
        "白黒フィルムを一本撮り切る",
        "フィルムケースをカメラにセットする",
        "カメラの露出設定を確認する",
        "暗室プリント用の印画紙を買う",
        "金曜日までにフィルムを現像する必要がある",
        "ラボから現像した写真を受け取る",
        "土曜日にフィルム写真教室がある",
        "旅行に予備のフィルムロールを持っていく",
        "フィルムケースを涼しい場所に保管する",
        "デジタルとアナログの写真を比較する",
        "ヴィンテージカメラ店に35ミリフィルムがある",
        "現像前にロールを撮り切る",
        "フィルムでポートレートを撮る",
        "露出計を使って露出を合わせる",
        "現像後のフィルムがとてもきれいだった",
        "カラーと白黒のフィルムを試す",
        "パーティー用に使い捨てカメラをプレゼントする",
        "学校のフィルム写真プロジェクト",
        "古いネガをアルバムに整理する",
        "35ミリフイルムを買う",
        "フィルムを現象する",
        "使い捨てカメラをかう",
        "フイルム写真の基本",
        "暗室でげんぞうする",
    ],
    fr=[
        "pellicule",
        "négatif",
        "photographie",
        "rétro",
        "rouleau",
        "35mm",
        "chambre noire",
        "argentique",
        "rouleau de pellicule",
        "développer la pellicule",
        "appareil argentique",
        "appareil vintage",
        "appareil jetable",
        "papier photo",
        "photo argentique",
        "cartouche de pellicule",
        "exposition",
        "posemètre",
        "développer la pellicule au labo",
        "acheter un rouleau de pellicule 35mm",
        "photographier avec un appareil argentique ce week-end",
        "installer une chambre noire à la maison",
        "apporter la pellicule à développer",
        "scanner les négatifs développés",
        "imprimer des photos à partir des négatifs",
        "acheter un appareil jetable pour le voyage",
        "apprendre les bases de la photo argentique",
        "essayer de photographier sur pellicule pour la première fois",
        "trouver une chambre noire à louer",
        "pratiquer la photographie argentique",
        "obtenir un look rétro avec le grain de la pellicule",
        "trouver un appareil argentique vintage en ligne",
        "photographier un rouleau de pellicule noir et blanc",
        "charger la cartouche de pellicule dans l'appareil",
        "vérifier les réglages d'exposition",
        "acheter du papier photo pour les tirages en chambre noire",
        "la pellicule doit être développée avant vendredi",
        "récupérer les photos développées au labo",
        "cours de photo argentique samedi",
        "prendre des rouleaux de pellicule supplémentaires pour le voyage",
        "conserver les cartouches de pellicule au frais",
        "comparer la photographie numérique et argentique",
        "la boutique vintage a de la pellicule 35mm",
        "finir le rouleau avant de développer",
        "faire des portraits sur pellicule",
        "utiliser un posemètre pour l'exposition",
        "la pellicule est très bien sortie après développement",
        "essayer la pellicule couleur et noir et blanc",
        "offrir un appareil jetable pour la fête",
        "projet de photo argentique pour l'école",
        "ranger les vieux négatifs dans un album",
        "développer la pelicule au labo",
        "acheter un rouelau de pellicule",
        "photographir avec un appareil argentique",
        "chambre noire à la maiosn",
        "apparareil jetable pour le voyage",
    ],
    es=[
        "película",
        "negativo",
        "fotografía",
        "retro",
        "rollo",
        "35mm",
        "cuarto oscuro",
        "analógico",
        "rollo de película",
        "revelar película",
        "cámara de película",
        "cámara vintage",
        "cámara desechable",
        "papel fotográfico",
        "fotografía analógica",
        "carrete",
        "exposición",
        "fotómetro",
        "revelar el rollo de película en el laboratorio",
        "comprar un rollo de película de 35mm",
        "fotografiar con cámara de película este fin de semana",
        "montar un cuarto oscuro en casa",
        "llevar la película a revelar",
        "escanear los negativos revelados",
        "imprimir fotos de los negativos",
        "comprar una cámara desechable para el viaje",
        "aprender los básicos de fotografía analógica",
        "probar por primera vez a fotografiar en película",
        "encontrar un cuarto oscuro para alquilar",
        "practicar la fotografía analógica",
        "conseguir un look retro con el grano de la película",
        "buscar una cámara vintage de película en línea",
        "fotografiar un rollo de película en blanco y negro",
        "cargar el carrete en la cámara",
        "revisar los ajustes de exposición en la cámara",
        "comprar papel fotográfico para el cuarto oscuro",
        "la película hay que revelarla antes del viernes",
        "recoger las fotos reveladas del laboratorio",
        "clase de fotografía analógica el sábado",
        "llevar rollos de película extra para el viaje",
        "guardar los carretes en un lugar fresco",
        "comparar la fotografía digital y la analógica",
        "la tienda vintage tiene película de 35mm",
        "terminar de fotografiar el rollo antes de revelar",
        "hacer retratos en película",
        "usar un fotómetro para la exposición",
        "la película salió genial después de revelar",
        "probar película en color y en blanco y negro",
        "regalar una cámara desechable para la fiesta",
        "proyecto de fotografía analógica para la escuela",
        "organizar los negativos viejos en un álbum",
        "revelar el rolo de película",
        "comprar un rollo de pelicula",
        "fotografar con cámara de película",
        "cámara desechble para el viaje",
        "cuarto oscur en casa",
    ],
)

# ── fingerprint ───────────────────────────────────────────────────────────────
gen("fingerprint",
    en=[
        "biometric",
        "fingerprint",
        "identity",
        "scan",
        "security",
        "touch",
        "unique",
        "fingerprint scanner",
        "biometric login",
        "touch ID",
        "fingerprint lock",
        "identity verification",
        "fingerprint sensor",
        "biometric security",
        "fingerprint unlock",
        "access control",
        "fingerprint reader",
        "authentication",
        "set up fingerprint unlock on the phone",
        "register a fingerprint for the door lock",
        "use the fingerprint scanner at the office",
        "add a second fingerprint to the phone",
        "fingerprint sensor not working properly",
        "verify identity with fingerprint at the bank",
        "unlock the laptop with fingerprint",
        "set up biometric login for the app",
        "clean the fingerprint sensor on the phone",
        "replace the fingerprint reader at the entrance",
        "enroll fingerprint for the gym membership",
        "fingerprint access for the server room",
        "update biometric data at the office",
        "the fingerprint scanner needs calibrating",
        "forgot PIN so using fingerprint instead",
        "get fingerprinted for the background check",
        "set up fingerprint for mobile payments",
        "fingerprint login for the banking app",
        "touch ID stopped working after the update",
        "register all fingers for the lock",
        "biometric check at the airport",
        "enable fingerprint for the password manager",
        "the door lock only accepts fingerprints",
        "fingerprint attendance system at work",
        "wipe the scanner before scanning fingerprint",
        "add my fingerprint to the shared tablet",
        "fingerprint not recognized try again",
        "security upgrade to fingerprint access",
        "set up fingerprint on the new phone",
        "biometric enrollment at the office tomorrow",
        "test the new fingerprint lock on the door",
        "fingerprint reader for the home safe",
        "enable biometric unlock on the app",
        "fingerpirnt scanner",
        "biometrc fingerprint",
        "fingerpint unlock",
        "set up finerprint on phone",
        "tocuh ID not working",
    ],
    ru=[
        "биометрия",
        "отпечаток пальца",
        "идентификация",
        "сканирование",
        "безопасность",
        "касание",
        "уникальный",
        "сканер отпечатков",
        "биометрический вход",
        "датчик отпечатка",
        "замок по отпечатку",
        "верификация личности",
        "сенсор отпечатка",
        "биометрическая защита",
        "разблокировка по отпечатку",
        "контроль доступа",
        "считыватель отпечатков",
        "аутентификация",
        "настроить разблокировку по отпечатку на телефоне",
        "зарегистрировать отпечаток для дверного замка",
        "использовать сканер отпечатков в офисе",
        "добавить второй отпечаток на телефон",
        "датчик отпечатка работает некорректно",
        "подтвердить личность по отпечатку в банке",
        "разблокировать ноутбук по отпечатку",
        "настроить биометрический вход в приложение",
        "протереть сенсор отпечатка на телефоне",
        "заменить считыватель отпечатков на входе",
        "зарегистрировать отпечаток для абонемента в зал",
        "доступ в серверную по отпечатку",
        "обновить биометрические данные в офисе",
        "сканер отпечатков нужно откалибровать",
        "забыл ПИН-код и использую отпечаток",
        "сдать отпечатки для проверки",
        "настроить отпечаток для мобильных платежей",
        "вход в банковское приложение по отпечатку",
        "датчик отпечатка перестал работать после обновления",
        "зарегистрировать все пальцы для замка",
        "биометрическая проверка в аэропорту",
        "включить отпечаток для менеджера паролей",
        "дверной замок принимает только отпечатки",
        "система учёта по отпечаткам на работе",
        "протереть сканер перед сканированием отпечатка",
        "добавить мой отпечаток на общий планшет",
        "отпечаток не распознан попробуйте ещё раз",
        "обновить систему безопасности на отпечаток",
        "настроить отпечаток на новом телефоне",
        "регистрация биометрии в офисе завтра",
        "проверить новый замок по отпечатку на двери",
        "считыватель отпечатков для домашнего сейфа",
        "включить биометрическую разблокировку в приложении",
        "сканер отпечатов пальцев",
        "биометрическй вход",
        "отпечаток палца не распознан",
        "настроить отпечаток на телефне",
        "разблакировка по отпечатку",
    ],
    de=[
        "Biometrie",
        "Fingerabdruck",
        "Identität",
        "Scan",
        "Sicherheit",
        "Berührung",
        "einzigartig",
        "Fingerabdruckscanner",
        "biometrische Anmeldung",
        "Touch ID",
        "Fingerabdrucksperre",
        "Identitätsprüfung",
        "Fingerabdrucksensor",
        "biometrische Sicherheit",
        "Fingerabdruck-Entsperrung",
        "Zugangskontrolle",
        "Fingerabdruckleser",
        "Authentifizierung",
        "Fingerabdruck-Entsperrung am Handy einrichten",
        "Fingerabdruck für das Türschloss registrieren",
        "den Fingerabdruckscanner im Büro verwenden",
        "einen zweiten Fingerabdruck am Handy hinzufügen",
        "Fingerabdrucksensor funktioniert nicht richtig",
        "Identität per Fingerabdruck bei der Bank bestätigen",
        "den Laptop mit Fingerabdruck entsperren",
        "biometrische Anmeldung für die App einrichten",
        "den Fingerabdrucksensor am Handy reinigen",
        "den Fingerabdruckleser am Eingang austauschen",
        "Fingerabdruck für die Fitnessstudio-Mitgliedschaft registrieren",
        "Fingerabdruck-Zugang für den Serverraum",
        "biometrische Daten im Büro aktualisieren",
        "der Fingerabdruckscanner muss kalibriert werden",
        "PIN vergessen also Fingerabdruck verwenden",
        "Fingerabdrücke für die Hintergrundprüfung abgeben",
        "Fingerabdruck für mobiles Bezahlen einrichten",
        "Fingerabdruck-Login für die Banking-App",
        "Touch ID funktioniert nach dem Update nicht mehr",
        "alle Finger für das Schloss registrieren",
        "biometrische Kontrolle am Flughafen",
        "Fingerabdruck für den Passwort-Manager aktivieren",
        "das Türschloss akzeptiert nur Fingerabdrücke",
        "Anwesenheitssystem per Fingerabdruck bei der Arbeit",
        "den Scanner vor dem Fingerabdruck-Scan abwischen",
        "meinen Fingerabdruck zum gemeinsamen Tablet hinzufügen",
        "Fingerabdruck nicht erkannt bitte erneut versuchen",
        "Sicherheitsupgrade auf Fingerabdruck-Zugang",
        "Fingerabdruck am neuen Handy einrichten",
        "biometrische Registrierung im Büro morgen",
        "das neue Fingerabdruckschloss an der Tür testen",
        "Fingerabdruckleser für den Tresor zu Hause",
        "biometrische Entsperrung in der App aktivieren",
        "Fingerabdruckscaner funktioniert nicht",
        "biometriche Anmeldung einrichten",
        "Fingerabdruk nicht erkannt",
        "Fingeabdruck am Handy einrichten",
        "Touch ID funktioneirt nicht",
    ],
    ja=[
        "生体認証",
        "指紋",
        "本人確認",
        "スキャン",
        "セキュリティ",
        "タッチ",
        "固有",
        "指紋スキャナー",
        "生体認証ログイン",
        "タッチID",
        "指紋ロック",
        "身元確認",
        "指紋センサー",
        "生体認証セキュリティ",
        "指紋認証解除",
        "アクセス制御",
        "指紋リーダー",
        "認証",
        "スマホの指紋認証を設定する",
        "ドアのロックに指紋を登録する",
        "オフィスの指紋スキャナーを使う",
        "スマホに2つ目の指紋を追加する",
        "指紋センサーが正常に動作しない",
        "銀行で指紋で本人確認する",
        "ノートパソコンを指紋で解除する",
        "アプリの生体認証ログインを設定する",
        "スマホの指紋センサーを拭く",
        "入口の指紋リーダーを交換する",
        "ジムの会員証に指紋を登録する",
        "サーバールームの指紋アクセス",
        "オフィスで生体認証データを更新する",
        "指紋スキャナーのキャリブレーションが必要",
        "PINを忘れたので指紋を使う",
        "身元調査のために指紋を取る",
        "モバイル決済に指紋を設定する",
        "銀行アプリの指紋ログイン",
        "アップデート後にタッチIDが動かなくなった",
        "ロック用にすべての指を登録する",
        "空港の生体認証チェック",
        "パスワードマネージャーの指紋認証を有効にする",
        "ドアロックは指紋のみ対応",
        "職場の指紋出勤管理システム",
        "指紋スキャン前にスキャナーを拭く",
        "共有タブレットに自分の指紋を追加する",
        "指紋が認識されませんもう一度試してください",
        "セキュリティを指紋アクセスにアップグレード",
        "新しいスマホで指紋を設定する",
        "明日オフィスで生体認証の登録",
        "ドアの新しい指紋ロックをテストする",
        "家庭用金庫の指紋リーダー",
        "アプリの生体認証解除を有効にする",
        "指紋スキャナが動かない",
        "生体にんしょうログイン",
        "指紋にんしょうを設定する",
        "タッチIDがうごかない",
        "指紋りーだーを交換する",
    ],
    fr=[
        "biométrie",
        "empreinte digitale",
        "identité",
        "scan",
        "sécurité",
        "toucher",
        "unique",
        "lecteur d'empreintes",
        "connexion biométrique",
        "touch ID",
        "verrouillage par empreinte",
        "vérification d'identité",
        "capteur d'empreintes",
        "sécurité biométrique",
        "déverrouillage par empreinte",
        "contrôle d'accès",
        "scanner d'empreintes",
        "authentification",
        "configurer le déverrouillage par empreinte sur le téléphone",
        "enregistrer une empreinte pour la serrure de la porte",
        "utiliser le lecteur d'empreintes au bureau",
        "ajouter une deuxième empreinte au téléphone",
        "le capteur d'empreintes ne fonctionne pas correctement",
        "vérifier l'identité par empreinte à la banque",
        "déverrouiller le portable avec l'empreinte",
        "configurer la connexion biométrique pour l'appli",
        "nettoyer le capteur d'empreintes du téléphone",
        "remplacer le lecteur d'empreintes à l'entrée",
        "enregistrer l'empreinte pour l'abonnement à la salle de sport",
        "accès au local serveur par empreinte",
        "mettre à jour les données biométriques au bureau",
        "le lecteur d'empreintes doit être recalibré",
        "j'ai oublié le code PIN j'utilise l'empreinte",
        "donner ses empreintes pour la vérification des antécédents",
        "configurer l'empreinte pour les paiements mobiles",
        "connexion par empreinte pour l'appli bancaire",
        "touch ID ne marche plus après la mise à jour",
        "enregistrer tous les doigts pour la serrure",
        "contrôle biométrique à l'aéroport",
        "activer l'empreinte pour le gestionnaire de mots de passe",
        "la serrure n'accepte que les empreintes",
        "système de pointage par empreinte au travail",
        "essuyer le capteur avant de scanner l'empreinte",
        "ajouter mon empreinte sur la tablette partagée",
        "empreinte non reconnue réessayez",
        "mise à niveau de sécurité vers l'accès par empreinte",
        "configurer l'empreinte sur le nouveau téléphone",
        "inscription biométrique au bureau demain",
        "tester la nouvelle serrure à empreinte sur la porte",
        "lecteur d'empreintes pour le coffre-fort",
        "activer le déverrouillage biométrique dans l'appli",
        "lectuer d'empreintes ne fonctionne pas",
        "connexion biométriqe par empreinte",
        "empreinte non reconue réessayez",
        "configurer l'empreint sur le téléphone",
        "déverouillage par empreinte",
    ],
    es=[
        "biometría",
        "huella dactilar",
        "identidad",
        "escaneo",
        "seguridad",
        "toque",
        "único",
        "escáner de huellas",
        "inicio biométrico",
        "touch ID",
        "bloqueo por huella",
        "verificación de identidad",
        "sensor de huellas",
        "seguridad biométrica",
        "desbloqueo por huella",
        "control de acceso",
        "lector de huellas",
        "autenticación",
        "configurar el desbloqueo por huella en el móvil",
        "registrar una huella para la cerradura de la puerta",
        "usar el escáner de huellas en la oficina",
        "añadir una segunda huella al móvil",
        "el sensor de huellas no funciona bien",
        "verificar la identidad con huella en el banco",
        "desbloquear el portátil con la huella",
        "configurar el inicio biométrico en la app",
        "limpiar el sensor de huellas del móvil",
        "cambiar el lector de huellas de la entrada",
        "registrar la huella para el abono del gimnasio",
        "acceso a la sala de servidores por huella",
        "actualizar los datos biométricos en la oficina",
        "el escáner de huellas necesita calibración",
        "olvidé el PIN así que uso la huella",
        "dar las huellas para la verificación de antecedentes",
        "configurar la huella para pagos móviles",
        "inicio de sesión por huella en la app del banco",
        "el touch ID dejó de funcionar tras la actualización",
        "registrar todos los dedos para la cerradura",
        "control biométrico en el aeropuerto",
        "activar la huella para el gestor de contraseñas",
        "la cerradura solo acepta huellas",
        "sistema de fichaje por huella en el trabajo",
        "limpiar el escáner antes de escanear la huella",
        "añadir mi huella en la tablet compartida",
        "huella no reconocida inténtelo de nuevo",
        "mejora de seguridad a acceso por huella",
        "configurar la huella en el móvil nuevo",
        "registro biométrico en la oficina mañana",
        "probar la nueva cerradura de huella en la puerta",
        "lector de huellas para la caja fuerte de casa",
        "activar el desbloqueo biométrico en la app",
        "escáner de huelals no funciona",
        "biometría de huella dactlar",
        "desbloquoe por huella",
        "configurar la hualla en el móvil",
        "tocuh ID no funciona",
    ],
)

print("\n--- Part 1 done: faucet, ferris-wheel, film, film-canister, fingerprint ---")
