#!/usr/bin/env python3
"""Task-003 part B: person-meditating, person-walking, phone."""

from gen_icons_task_006_common import build_icon

# ── PERSON-MEDITATING ────────────────────────────────────────────────────────
build_icon("person-meditating", {
    "en": [
        "calm", "meditation", "meditate", "mindfulness", "yoga",
        "zen", "lotus", "breathing", "relaxation", "inner peace",
        "mindful", "serenity", "tranquility", "stillness",
        "yoga class", "guided meditation", "deep breathing",
        "meditation session",
        "do a meditation session before bed",
        "practice mindfulness for ten minutes",
        "sign up for a yoga class",
        "try a guided meditation app",
        "meditate every morning for clarity",
        "sit in lotus position and meditate",
        "attend the weekly meditation group",
        "set a timer for the meditation session",
        "practice deep breathing to calm down",
        "schedule a yoga class on Wednesday",
        "download a meditation app on my phone",
        "do yoga stretches after waking up",
        "join the mindfulness retreat next month",
        "meditate during my lunch break",
        "find a quiet spot to meditate",
        "practice zen meditation after work",
        "listen to calming music for meditation",
        "start a daily meditation habit",
        "learn a new yoga pose today",
        "take a mindfulness break between tasks",
        "go to the yoga studio for the evening class",
        "read a book about meditation techniques",
        "add meditation to my daily routine",
        "do a five minute breathing exercise",
        "try a body scan meditation tonight",
        "practice gratitude during meditation",
        "stretch and meditate in the morning",
        "do yoga with a friend this weekend",
        "book a spot at the meditation center",
        "clear my mind with a short meditation",
        "prepare the yoga mat for practice",
        "focus on breathing during the session",
        "complete the thirty day meditation challenge",
        "attend the sunrise yoga session",
        "practice stillness and silence for ten minutes",
        "review my meditation progress this week",
        "set a reminder to meditate tonight",
        "mediatte in lotus position",
        "yoag meditation pose",
        "contmeplate in silence",
        "mintfulness practice daily",
        "meditatoin session before sleep",
    ],
    "ru": [
        "спокойствие", "медитация", "медитировать", "осознанность", "йога",
        "дзен", "лотос", "дыхание", "расслабление", "внутренний покой",
        "осознанный", "безмятежность", "спокойствие духа", "неподвижность",
        "занятие йогой", "управляемая медитация", "глубокое дыхание",
        "сеанс медитации",
        "провести сеанс медитации перед сном",
        "практиковать осознанность десять минут",
        "записаться на занятие йогой",
        "попробовать приложение для медитации",
        "медитировать каждое утро для ясности",
        "сесть в позу лотоса и медитировать",
        "посетить еженедельную группу медитации",
        "поставить таймер для сеанса медитации",
        "практиковать глубокое дыхание для успокоения",
        "записать занятие йогой на среду",
        "скачать приложение для медитации на телефон",
        "сделать йога-растяжку после пробуждения",
        "присоединиться к ретриту осознанности в следующем месяце",
        "медитировать во время обеденного перерыва",
        "найти тихое место для медитации",
        "практиковать дзен-медитацию после работы",
        "слушать спокойную музыку для медитации",
        "начать привычку ежедневной медитации",
        "выучить новую позу йоги сегодня",
        "сделать перерыв на осознанность между задачами",
        "пойти в йога-студию на вечернее занятие",
        "прочитать книгу о техниках медитации",
        "добавить медитацию в ежедневное расписание",
        "сделать пятиминутное дыхательное упражнение",
        "попробовать медитацию сканирования тела сегодня вечером",
        "практиковать благодарность во время медитации",
        "размяться и помедитировать утром",
        "заняться йогой с другом на выходных",
        "забронировать место в центре медитации",
        "очистить ум короткой медитацией",
        "подготовить коврик для йоги к занятию",
        "сосредоточиться на дыхании во время сеанса",
        "завершить тридцатидневный челлендж медитации",
        "посетить утренний сеанс йоги на рассвете",
        "практиковать неподвижность и тишину десять минут",
        "просмотреть прогресс медитации за эту неделю",
        "поставить напоминание помедитировать вечером",
        "медитировтаь в позе лотоса",
        "поза йоаг для медитации",
        "созерцтаь в тишине",
        "осознанноть практика ежедневная",
        "сенас медитации перед сном",
    ],
    "de": [
        "Ruhe", "Meditation", "meditieren", "Achtsamkeit", "Yoga",
        "Zen", "Lotus", "Atmung", "Entspannung", "innerer Frieden",
        "achtsam", "Gelassenheit", "Stille", "Regungslosigkeit",
        "Yogakurs", "geführte Meditation", "tiefes Atmen",
        "Meditationssitzung",
        "vor dem Schlafen eine Meditationssitzung machen",
        "zehn Minuten Achtsamkeit üben",
        "sich für einen Yogakurs anmelden",
        "eine Meditations-App ausprobieren",
        "jeden Morgen für Klarheit meditieren",
        "im Lotussitz sitzen und meditieren",
        "die wöchentliche Meditationsgruppe besuchen",
        "einen Timer für die Meditationssitzung stellen",
        "tiefes Atmen zur Beruhigung üben",
        "einen Yogakurs am Mittwoch planen",
        "eine Meditations-App aufs Handy laden",
        "nach dem Aufwachen Yoga-Dehnungen machen",
        "nächsten Monat am Achtsamkeitsretreat teilnehmen",
        "in der Mittagspause meditieren",
        "einen ruhigen Ort zum Meditieren finden",
        "nach der Arbeit Zen-Meditation üben",
        "beruhigende Musik zur Meditation hören",
        "eine tägliche Meditationsgewohnheit starten",
        "heute eine neue Yoga-Pose lernen",
        "eine Achtsamkeitspause zwischen Aufgaben machen",
        "zum Yogastudio für den Abendkurs gehen",
        "ein Buch über Meditationstechniken lesen",
        "Meditation in den Tagesablauf einbauen",
        "eine fünfminütige Atemübung machen",
        "heute Abend eine Body-Scan-Meditation ausprobieren",
        "Dankbarkeit während der Meditation üben",
        "morgens dehnen und meditieren",
        "am Wochenende mit einem Freund Yoga machen",
        "einen Platz im Meditationszentrum buchen",
        "den Geist mit einer kurzen Meditation klären",
        "die Yogamatte für die Übung vorbereiten",
        "sich während der Sitzung auf die Atmung konzentrieren",
        "die dreißigtägige Meditations-Challenge abschließen",
        "die Yoga-Sitzung bei Sonnenaufgang besuchen",
        "zehn Minuten Stille und Regungslosigkeit üben",
        "den Meditationsfortschritt diese Woche überprüfen",
        "eine Erinnerung zum Meditieren stellen",
        "Meditatoin im Lotussitz",
        "Yoag Meditationspose",
        "in Stilel meditieren",
        "Achtsamkeit tägich üben",
        "Meditationssituzng vor dem Schlaf",
    ],
    "ja": [
        "穏やかさ", "瞑想", "瞑想する", "マインドフルネス", "ヨガ",
        "禅", "蓮華座", "呼吸法", "リラクゼーション", "内なる平和",
        "マインドフル", "静寂", "安らぎ", "静止",
        "ヨガ教室", "ガイド付き瞑想", "深呼吸",
        "瞑想セッション",
        "寝る前に瞑想セッションをする",
        "十分間マインドフルネスを練習する",
        "ヨガ教室に申し込む",
        "瞑想アプリを試す",
        "毎朝クリアになるために瞑想する",
        "蓮華座に座って瞑想する",
        "週一の瞑想グループに参加する",
        "瞑想セッションのタイマーを設定する",
        "落ち着くために深呼吸を練習する",
        "水曜日にヨガ教室を予約する",
        "スマホに瞑想アプリをダウンロードする",
        "起きた後にヨガストレッチをする",
        "来月のマインドフルネスリトリートに参加する",
        "昼休みに瞑想する",
        "瞑想するための静かな場所を見つける",
        "仕事の後に禅の瞑想を練習する",
        "瞑想用の落ち着く音楽を聴く",
        "毎日の瞑想習慣を始める",
        "今日新しいヨガのポーズを学ぶ",
        "タスクの合間にマインドフルネス休憩を取る",
        "夕方のクラスにヨガスタジオに行く",
        "瞑想テクニックの本を読む",
        "日課に瞑想を追加する",
        "五分間の呼吸エクササイズをする",
        "今夜ボディスキャン瞑想を試す",
        "瞑想中に感謝を実践する",
        "朝ストレッチと瞑想をする",
        "週末に友達とヨガをする",
        "瞑想センターの席を予約する",
        "短い瞑想で心を整える",
        "ヨガマットを練習用に準備する",
        "セッション中に呼吸に集中する",
        "三十日間の瞑想チャレンジを完了する",
        "日の出のヨガセッションに参加する",
        "十分間静止と沈黙を練習する",
        "今週の瞑想の進捗を確認する",
        "今夜瞑想するリマインダーを設定する",
        "めいそうを蓮華座で行う",
        "ヨカの瞑想ポーズ",
        "しずかに瞑想する",
        "マインドフルネスを毎日練しゅうする",
        "瞑想のセッシヨン寝る前に",
    ],
    "fr": [
        "calme", "méditation", "méditer", "pleine conscience", "yoga",
        "zen", "lotus", "respiration", "relaxation", "paix intérieure",
        "attentif", "sérénité", "tranquillité", "immobilité",
        "cours de yoga", "méditation guidée", "respiration profonde",
        "séance de méditation",
        "faire une séance de méditation avant de dormir",
        "pratiquer la pleine conscience pendant dix minutes",
        "s'inscrire à un cours de yoga",
        "essayer une application de méditation guidée",
        "méditer chaque matin pour la clarté",
        "s'asseoir en position du lotus et méditer",
        "assister au groupe de méditation hebdomadaire",
        "mettre un minuteur pour la séance de méditation",
        "pratiquer la respiration profonde pour se calmer",
        "planifier un cours de yoga mercredi",
        "télécharger une appli de méditation sur mon téléphone",
        "faire des étirements de yoga au réveil",
        "rejoindre la retraite de pleine conscience le mois prochain",
        "méditer pendant ma pause déjeuner",
        "trouver un endroit calme pour méditer",
        "pratiquer la méditation zen après le travail",
        "écouter de la musique apaisante pour méditer",
        "commencer une habitude de méditation quotidienne",
        "apprendre une nouvelle pose de yoga aujourd'hui",
        "faire une pause pleine conscience entre les tâches",
        "aller au studio de yoga pour le cours du soir",
        "lire un livre sur les techniques de méditation",
        "ajouter la méditation à ma routine quotidienne",
        "faire un exercice de respiration de cinq minutes",
        "essayer une méditation body scan ce soir",
        "pratiquer la gratitude pendant la méditation",
        "s'étirer et méditer le matin",
        "faire du yoga avec un ami ce week-end",
        "réserver une place au centre de méditation",
        "clarifier mon esprit avec une courte méditation",
        "préparer le tapis de yoga pour la pratique",
        "se concentrer sur la respiration pendant la séance",
        "terminer le défi de méditation de trente jours",
        "assister à la séance de yoga au lever du soleil",
        "pratiquer l'immobilité et le silence pendant dix minutes",
        "revoir mes progrès en méditation cette semaine",
        "mettre un rappel pour méditer ce soir",
        "méidter en position du lotus",
        "yoag pose de méditation",
        "contempler en silnece",
        "pleine consciecne pratique quotidienne",
        "séacne de méditation avant dormir",
    ],
    "es": [
        "calma", "meditación", "meditar", "atención plena", "yoga",
        "zen", "loto", "respiración", "relajación", "paz interior",
        "consciente", "serenidad", "tranquilidad", "quietud",
        "clase de yoga", "meditación guiada", "respiración profunda",
        "sesión de meditación",
        "hacer una sesión de meditación antes de dormir",
        "practicar la atención plena durante diez minutos",
        "inscribirse en una clase de yoga",
        "probar una app de meditación guiada",
        "meditar cada mañana para tener claridad",
        "sentarse en posición de loto y meditar",
        "asistir al grupo de meditación semanal",
        "poner un temporizador para la sesión de meditación",
        "practicar la respiración profunda para calmarse",
        "agendar una clase de yoga el miércoles",
        "descargar una app de meditación en mi teléfono",
        "hacer estiramientos de yoga al despertar",
        "unirse al retiro de atención plena el próximo mes",
        "meditar durante mi pausa del almuerzo",
        "encontrar un lugar tranquilo para meditar",
        "practicar meditación zen después del trabajo",
        "escuchar música relajante para meditar",
        "empezar un hábito de meditación diario",
        "aprender una nueva postura de yoga hoy",
        "tomar una pausa de atención plena entre tareas",
        "ir al estudio de yoga para la clase de la noche",
        "leer un libro sobre técnicas de meditación",
        "agregar la meditación a mi rutina diaria",
        "hacer un ejercicio de respiración de cinco minutos",
        "probar una meditación de escaneo corporal esta noche",
        "practicar la gratitud durante la meditación",
        "estirar y meditar por la mañana",
        "hacer yoga con un amigo este fin de semana",
        "reservar un lugar en el centro de meditación",
        "despejar la mente con una meditación corta",
        "preparar la esterilla de yoga para la práctica",
        "concentrarse en la respiración durante la sesión",
        "completar el reto de meditación de treinta días",
        "asistir a la sesión de yoga al amanecer",
        "practicar la quietud y el silencio durante diez minutos",
        "revisar mi progreso de meditación esta semana",
        "poner un recordatorio para meditar esta noche",
        "meditiar en posición de loto",
        "yoag pose de meditación",
        "contemplra en silencio",
        "atencion plnea práctica diaria",
        "sesón de meditación antes de dormir",
    ],
})


# ── PERSON-WALKING ───────────────────────────────────────────────────────────
build_icon("person-walking", {
    "en": [
        "walk", "walking", "pedestrian", "steps", "exercise",
        "stroll", "footpath", "sidewalk", "step count", "daily walk",
        "walking route", "on foot", "pace", "stride",
        "walking shoes", "morning walk", "evening walk",
        "fitness walking",
        "go for a walk after dinner",
        "walk to work this morning",
        "take a walk around the block",
        "walk the dog in the park",
        "count my steps for the day",
        "go for a morning walk before breakfast",
        "walk to the store instead of driving",
        "take a stroll along the waterfront",
        "walk to the bus stop",
        "get ten thousand steps today",
        "go walking with a friend after lunch",
        "walk around the neighborhood",
        "walk to school with the kids",
        "take the walking path through the park",
        "go for an evening walk to unwind",
        "walk during the break at work",
        "track my walking distance on the app",
        "walk to the meeting instead of taking a cab",
        "take a brisk walk for exercise",
        "walk to pick up lunch nearby",
        "go for a walk in the morning sun",
        "walk the long route home for extra steps",
        "walk to the coffee shop down the street",
        "take a slow walk after the meal",
        "walk a few laps around the track",
        "try to walk more every day",
        "walk to the library this afternoon",
        "go for a walk to clear my head",
        "take the stairs and walk more today",
        "walk to the post office to mail a letter",
        "pace around the room while on the phone",
        "walk along the trail by the lake",
        "walk to the farmer's market on Saturday",
        "challenge myself to walk five miles today",
        "go for a power walk before work",
        "take a walk and listen to a podcast",
        "walk to the pharmacy to pick up medicine",
        "walkin to the store",
        "pedistrian crossing the street",
        "walkign exercise for health",
        "stesp count for the day",
        "mornign walk before breakfast",
    ],
    "ru": [
        "прогулка", "ходьба", "пешеход", "шаги", "упражнение",
        "гуляние", "пешеходная дорожка", "тротуар", "подсчёт шагов", "ежедневная прогулка",
        "пешеходный маршрут", "пешком", "темп", "шаг",
        "обувь для ходьбы", "утренняя прогулка", "вечерняя прогулка",
        "фитнес-ходьба",
        "прогуляться после ужина",
        "пойти на работу пешком утром",
        "прогуляться вокруг квартала",
        "погулять с собакой в парке",
        "посчитать шаги за день",
        "пойти на утреннюю прогулку перед завтраком",
        "пойти в магазин пешком вместо машины",
        "прогуляться вдоль набережной",
        "дойти пешком до остановки",
        "набрать десять тысяч шагов сегодня",
        "пойти гулять с другом после обеда",
        "прогуляться по району",
        "пойти в школу пешком с детьми",
        "пройти по пешеходной дорожке через парк",
        "пойти на вечернюю прогулку для расслабления",
        "ходить во время перерыва на работе",
        "отслеживать пройденное расстояние в приложении",
        "пойти на встречу пешком вместо такси",
        "сделать быструю прогулку для упражнения",
        "дойти пешком до ближайшего обеда",
        "прогуляться на утреннем солнце",
        "пойти домой длинной дорогой для дополнительных шагов",
        "дойти пешком до кофейни за углом",
        "медленно прогуляться после еды",
        "пройти несколько кругов по дорожке",
        "стараться ходить больше каждый день",
        "пойти в библиотеку пешком после обеда",
        "прогуляться чтобы прояснить голову",
        "подниматься по лестнице и больше ходить сегодня",
        "дойти пешком до почты отправить письмо",
        "ходить по комнате во время телефонного разговора",
        "прогуляться по тропинке вдоль озера",
        "пойти на фермерский рынок пешком в субботу",
        "поставить себе цель пройти восемь километров сегодня",
        "сделать энергичную прогулку перед работой",
        "прогуляться и послушать подкаст",
        "дойти пешком до аптеки за лекарством",
        "прогулак до магазина",
        "пешехд переходит улицу",
        "ходьа упражнение для здоровья",
        "подсчёт шагв за день",
        "утреняя прогулка перед завтраком",
    ],
    "de": [
        "Spaziergang", "Gehen", "Fußgänger", "Schritte", "Bewegung",
        "Bummel", "Fußweg", "Gehweg", "Schrittzähler", "täglicher Spaziergang",
        "Gehroute", "zu Fuß", "Tempo", "Schritt",
        "Laufschuhe", "Morgenspaziergang", "Abendspaziergang",
        "Fitness-Walking",
        "nach dem Abendessen spazieren gehen",
        "heute Morgen zu Fuß zur Arbeit gehen",
        "einmal um den Block spazieren",
        "mit dem Hund im Park spazieren gehen",
        "meine Schritte für den Tag zählen",
        "vor dem Frühstück einen Morgenspaziergang machen",
        "zu Fuß zum Laden gehen statt zu fahren",
        "am Ufer entlang schlendern",
        "zu Fuß zur Bushaltestelle gehen",
        "heute zehntausend Schritte schaffen",
        "nach dem Mittagessen mit einem Freund spazieren",
        "durch die Nachbarschaft spazieren",
        "mit den Kindern zu Fuß zur Schule gehen",
        "den Fußweg durch den Park nehmen",
        "einen Abendspaziergang zum Entspannen machen",
        "in der Arbeitspause spazieren gehen",
        "die Gehstrecke in der App verfolgen",
        "zu Fuß zum Meeting gehen statt ein Taxi zu nehmen",
        "einen zügigen Spaziergang als Bewegung machen",
        "zu Fuß zum Mittagessen in der Nähe gehen",
        "in der Morgensonne spazieren gehen",
        "den langen Weg nach Hause für mehr Schritte nehmen",
        "zu Fuß zum Café die Straße runter gehen",
        "nach dem Essen einen langsamen Spaziergang machen",
        "ein paar Runden auf der Bahn gehen",
        "versuchen jeden Tag mehr zu gehen",
        "heute Nachmittag zu Fuß zur Bibliothek gehen",
        "spazieren gehen um den Kopf freizubekommen",
        "heute die Treppe nehmen und mehr gehen",
        "zu Fuß zur Post einen Brief aufgeben",
        "beim Telefonieren im Zimmer auf und ab gehen",
        "am See entlang spazieren",
        "am Samstag zu Fuß zum Bauernmarkt gehen",
        "die Herausforderung annehmen heute acht Kilometer zu gehen",
        "vor der Arbeit einen Power-Walk machen",
        "spazieren gehen und einen Podcast hören",
        "zu Fuß zur Apotheke Medikamente holen",
        "zum Ladn spazieren",
        "Fußgäner überquert die Straße",
        "Gehne als Gesundheitsübung",
        "Schrittzähel für den Tag",
        "Morgenspaziergagn vor dem Frühstück",
    ],
    "ja": [
        "散歩", "歩行", "歩行者", "歩数", "運動",
        "ぶらぶら歩き", "歩道", "舗装道路", "歩数計", "毎日の散歩",
        "ウォーキングルート", "徒歩", "ペース", "歩幅",
        "ウォーキングシューズ", "朝の散歩", "夕方の散歩",
        "フィットネスウォーキング",
        "夕食後に散歩に行く",
        "今朝は歩いて仕事に行く",
        "ブロックを一周歩く",
        "公園で犬の散歩をする",
        "今日の歩数を数える",
        "朝食前に朝の散歩に行く",
        "車の代わりに歩いてお店に行く",
        "海沿いを散歩する",
        "バス停まで歩く",
        "今日一万歩を達成する",
        "昼食後に友達と散歩する",
        "近所を歩き回る",
        "子供と歩いて学校に行く",
        "公園を通る歩道を歩く",
        "リラックスするために夕方の散歩に行く",
        "仕事の休憩中に歩く",
        "アプリで歩いた距離を記録する",
        "タクシーの代わりに歩いて会議に行く",
        "運動のために早歩きをする",
        "近くに歩いて昼食を買いに行く",
        "朝日の中を散歩する",
        "余分な歩数のために遠回りして家に帰る",
        "通り沿いのコーヒーショップまで歩く",
        "食後にゆっくり散歩する",
        "トラックを数周歩く",
        "毎日もっと歩くようにする",
        "今日の午後は歩いて図書館に行く",
        "頭をすっきりさせるために散歩する",
        "今日は階段を使ってもっと歩く",
        "手紙を出しに歩いて郵便局に行く",
        "電話中に部屋の中を歩き回る",
        "湖のそばのトレイルを歩く",
        "土曜日に歩いてファーマーズマーケットに行く",
        "今日八キロ歩くことに挑戦する",
        "仕事前にパワーウォーキングをする",
        "散歩しながらポッドキャストを聴く",
        "歩いて薬局に薬を取りに行く",
        "あるいてお店に行く",
        "歩こう者が道を渡る",
        "ウォーキンク運動で健康に",
        "きょうの歩すうを確認",
        "あさの散歩前に朝食",
    ],
    "fr": [
        "marche", "marcher", "piéton", "pas", "exercice",
        "promenade", "chemin piéton", "trottoir", "compteur de pas", "marche quotidienne",
        "itinéraire à pied", "à pied", "rythme", "foulée",
        "chaussures de marche", "marche matinale", "marche du soir",
        "marche sportive",
        "aller marcher après le dîner",
        "aller au travail à pied ce matin",
        "faire le tour du pâté de maisons",
        "promener le chien dans le parc",
        "compter mes pas de la journée",
        "faire une marche matinale avant le petit-déjeuner",
        "aller au magasin à pied au lieu de conduire",
        "se promener le long du bord de mer",
        "marcher jusqu'à l'arrêt de bus",
        "atteindre dix mille pas aujourd'hui",
        "aller marcher avec un ami après le déjeuner",
        "marcher dans le quartier",
        "aller à l'école à pied avec les enfants",
        "prendre le chemin piéton à travers le parc",
        "aller se promener le soir pour décompresser",
        "marcher pendant la pause au travail",
        "suivre ma distance de marche sur l'appli",
        "aller à la réunion à pied au lieu de prendre un taxi",
        "faire une marche rapide pour l'exercice",
        "aller chercher le déjeuner à pied",
        "se promener au soleil du matin",
        "prendre le long chemin pour plus de pas",
        "marcher jusqu'au café au bout de la rue",
        "faire une marche lente après le repas",
        "faire quelques tours sur la piste",
        "essayer de marcher plus chaque jour",
        "aller à la bibliothèque à pied cet après-midi",
        "aller marcher pour se vider la tête",
        "prendre les escaliers et plus marcher aujourd'hui",
        "aller à la poste à pied pour envoyer une lettre",
        "marcher dans la pièce au téléphone",
        "se promener sur le sentier au bord du lac",
        "aller au marché fermier à pied samedi",
        "me fixer le défi de marcher huit kilomètres aujourd'hui",
        "faire une marche énergique avant le travail",
        "se promener en écoutant un podcast",
        "aller à la pharmacie à pied chercher des médicaments",
        "amrcher jusqu'au magasin",
        "piéotn traversant la rue",
        "mrache exercice pour la santé",
        "comptuer de pas pour la journée",
        "marhce matinale avant le petit-déjeuner",
    ],
    "es": [
        "caminar", "caminata", "peatón", "pasos", "ejercicio",
        "paseo", "sendero peatonal", "acera", "conteo de pasos", "caminata diaria",
        "ruta a pie", "a pie", "ritmo", "zancada",
        "zapatos para caminar", "caminata matutina", "caminata nocturna",
        "caminata deportiva",
        "salir a caminar después de cenar",
        "ir caminando al trabajo esta mañana",
        "dar una vuelta a la manzana",
        "pasear al perro en el parque",
        "contar mis pasos del día",
        "hacer una caminata matutina antes del desayuno",
        "ir a la tienda a pie en vez de manejar",
        "pasear por el malecón",
        "caminar hasta la parada del autobús",
        "lograr diez mil pasos hoy",
        "ir a caminar con un amigo después del almuerzo",
        "caminar por el vecindario",
        "ir caminando a la escuela con los niños",
        "tomar el camino peatonal por el parque",
        "salir a caminar por la noche para relajarse",
        "caminar durante el descanso en el trabajo",
        "rastrear mi distancia caminada en la app",
        "ir caminando a la reunión en vez de tomar un taxi",
        "hacer una caminata rápida como ejercicio",
        "ir caminando a buscar el almuerzo cerca",
        "pasear bajo el sol de la mañana",
        "tomar el camino largo a casa para más pasos",
        "caminar hasta la cafetería de la calle",
        "dar un paseo lento después de comer",
        "dar unas vueltas en la pista",
        "intentar caminar más todos los días",
        "ir caminando a la biblioteca esta tarde",
        "salir a caminar para despejar la mente",
        "subir las escaleras y caminar más hoy",
        "ir caminando al correo a enviar una carta",
        "caminar por la habitación mientras hablo por teléfono",
        "pasear por el sendero junto al lago",
        "ir al mercado de agricultores a pie el sábado",
        "retarme a caminar ocho kilómetros hoy",
        "hacer una caminata enérgica antes del trabajo",
        "caminar y escuchar un podcast",
        "ir caminando a la farmacia a recoger medicinas",
        "camianr hasta la tienda",
        "peatno cruzando la calle",
        "caminata ejericicio para la salud",
        "contoe de pasos del día",
        "caminata mautina antes del desayuno",
    ],
})


# ── PHONE ────────────────────────────────────────────────────────────────────
build_icon("phone", {
    "en": [
        "phone", "call", "telephone", "mobile", "cell",
        "number", "iphone", "smartphone", "screen", "ring",
        "dial", "voicemail", "phone call", "cell phone",
        "caller", "incoming call", "phone number",
        "missed call",
        "make a phone call to the doctor",
        "charge my phone before leaving",
        "buy a new phone case",
        "call mom on the phone tonight",
        "answer the incoming phone call",
        "check my missed calls on the phone",
        "schedule a phone call with the client",
        "fix the cracked phone screen",
        "update the phone software",
        "set up the new phone",
        "transfer contacts to the new phone",
        "call the restaurant to make a reservation",
        "put the phone on silent during the meeting",
        "save the phone number in my contacts",
        "return the missed phone call",
        "charge the phone overnight",
        "buy a screen protector for the phone",
        "call customer service about the order",
        "pick up the phone when it rings",
        "call the office to confirm the meeting",
        "replace the old phone battery",
        "download a new app on the phone",
        "clean the phone screen with a cloth",
        "call a cab on my phone",
        "record a new voicemail greeting",
        "set an alarm on the phone for tomorrow",
        "pay the phone bill this week",
        "back up the phone data to the cloud",
        "take the phone to the repair shop",
        "hand the phone to my colleague for the call",
        "call the school about the schedule",
        "mute the phone during the movie",
        "plug the phone into the charger",
        "find my phone in the house",
        "upgrade to a newer phone model",
        "check the phone for new messages",
        "call the plumber to fix the leak",
        "phoen call to the doctor",
        "chrage the phone before leaving",
        "phnoe number to save",
        "anwser the incoming call",
        "scren protector for the phone",
    ],
    "ru": [
        "телефон", "звонок", "трубка", "мобильный", "сотовый",
        "номер", "айфон", "смартфон", "экран", "звонить",
        "набрать", "голосовая почта", "телефонный звонок", "сотовый телефон",
        "звонящий", "входящий звонок", "номер телефона",
        "пропущенный звонок",
        "позвонить врачу по телефону",
        "зарядить телефон перед выходом",
        "купить новый чехол для телефона",
        "позвонить маме по телефону вечером",
        "ответить на входящий звонок",
        "проверить пропущенные звонки на телефоне",
        "запланировать телефонный звонок с клиентом",
        "починить треснувший экран телефона",
        "обновить программное обеспечение телефона",
        "настроить новый телефон",
        "перенести контакты на новый телефон",
        "позвонить в ресторан забронировать столик",
        "поставить телефон на беззвучный на встрече",
        "сохранить номер телефона в контактах",
        "перезвонить по пропущенному звонку",
        "поставить телефон на зарядку на ночь",
        "купить защитное стекло для телефона",
        "позвонить в службу поддержки по заказу",
        "взять трубку когда звонит телефон",
        "позвонить в офис подтвердить встречу",
        "заменить старый аккумулятор телефона",
        "скачать новое приложение на телефон",
        "протереть экран телефона тряпочкой",
        "вызвать такси через телефон",
        "записать новое приветствие голосовой почты",
        "поставить будильник на телефоне на завтра",
        "оплатить счёт за телефон на этой неделе",
        "сделать резервную копию данных телефона в облако",
        "отнести телефон в ремонт",
        "передать телефон коллеге для разговора",
        "позвонить в школу насчёт расписания",
        "отключить звук телефона во время фильма",
        "воткнуть телефон в зарядку",
        "найти телефон в доме",
        "обновить телефон на новую модель",
        "проверить телефон на новые сообщения",
        "позвонить сантехнику починить утечку",
        "телефоный звонок врачу",
        "зарядть телефон перед выходом",
        "номре телефона для сохранения",
        "отвеить на входящий звонок",
        "защитное стекл для телефона",
    ],
    "de": [
        "Telefon", "Anruf", "Hörer", "Handy", "Mobiltelefon",
        "Nummer", "iPhone", "Smartphone", "Bildschirm", "klingeln",
        "wählen", "Mailbox", "Telefonanruf", "Handy",
        "Anrufer", "eingehender Anruf", "Telefonnummer",
        "verpasster Anruf",
        "den Arzt anrufen",
        "das Handy vor dem Losgehen aufladen",
        "eine neue Handyhülle kaufen",
        "Mama heute Abend anrufen",
        "den eingehenden Anruf annehmen",
        "verpasste Anrufe auf dem Handy prüfen",
        "einen Telefonanruf mit dem Kunden planen",
        "den gesprungenen Handybildschirm reparieren",
        "die Telefonsoftware aktualisieren",
        "das neue Handy einrichten",
        "Kontakte auf das neue Handy übertragen",
        "im Restaurant anrufen um zu reservieren",
        "das Handy im Meeting auf lautlos stellen",
        "die Telefonnummer in den Kontakten speichern",
        "den verpassten Anruf zurückrufen",
        "das Handy über Nacht aufladen",
        "eine Displayschutzfolie für das Handy kaufen",
        "den Kundenservice wegen der Bestellung anrufen",
        "das Telefon abnehmen wenn es klingelt",
        "im Büro anrufen um das Meeting zu bestätigen",
        "den alten Handyakku ersetzen",
        "eine neue App aufs Handy laden",
        "den Handybildschirm mit einem Tuch reinigen",
        "ein Taxi über das Handy rufen",
        "eine neue Mailbox-Ansage aufnehmen",
        "den Wecker auf dem Handy für morgen stellen",
        "diese Woche die Handyrechnung bezahlen",
        "die Handydaten in der Cloud sichern",
        "das Handy in die Werkstatt bringen",
        "dem Kollegen das Telefon für das Gespräch geben",
        "in der Schule wegen dem Stundenplan anrufen",
        "das Handy im Kino stumm schalten",
        "das Handy ans Ladegerät anschließen",
        "mein Handy im Haus finden",
        "auf ein neueres Handymodell umsteigen",
        "das Handy auf neue Nachrichten prüfen",
        "den Klempner anrufen wegen dem Leck",
        "Teelfonanruf beim Arzt",
        "das Hadny vor dem Gehen aufladen",
        "Telefonumemr speichern",
        "den eingehdenen Anruf annehmen",
        "Diplayfolie für das Handy",
    ],
    "ja": [
        "電話", "通話", "受話器", "モバイル", "携帯",
        "番号", "アイフォン", "スマートフォン", "画面", "着信",
        "ダイヤル", "留守電", "電話をかける", "携帯電話",
        "発信者", "着信電話", "電話番号",
        "不在着信",
        "医者に電話する",
        "出かける前にスマホを充電する",
        "新しいスマホケースを買う",
        "今夜お母さんに電話する",
        "着信電話に出る",
        "スマホで不在着信を確認する",
        "クライアントとの電話を予定する",
        "割れたスマホの画面を修理する",
        "スマホのソフトウェアを更新する",
        "新しいスマホをセットアップする",
        "新しいスマホに連絡先を移す",
        "レストランに電話して予約する",
        "会議中にスマホをサイレントにする",
        "電話番号を連絡先に保存する",
        "不在着信に折り返し電話する",
        "夜間にスマホを充電する",
        "スマホ用の保護フィルムを買う",
        "注文についてカスタマーサービスに電話する",
        "電話が鳴ったら出る",
        "会議の確認のためオフィスに電話する",
        "古いスマホのバッテリーを交換する",
        "スマホに新しいアプリをダウンロードする",
        "スマホの画面を布で拭く",
        "スマホでタクシーを呼ぶ",
        "新しい留守電のメッセージを録音する",
        "明日のためにスマホのアラームを設定する",
        "今週電話料金を支払う",
        "スマホのデータをクラウドにバックアップする",
        "スマホを修理店に持っていく",
        "通話のために同僚にスマホを渡す",
        "学校にスケジュールについて電話する",
        "映画中にスマホをミュートにする",
        "スマホを充電器に繋ぐ",
        "家の中でスマホを見つける",
        "新しいスマホモデルにアップグレードする",
        "スマホで新しいメッセージを確認する",
        "水漏れ修理のために配管工に電話する",
        "でんわを医者にかける",
        "じゅうでんする前にスマホ",
        "でんわ番号を保存する",
        "着信でんわに出る",
        "スマホの画面ほごフィルム",
    ],
    "fr": [
        "téléphone", "appel", "combiné", "portable", "mobile",
        "numéro", "iPhone", "smartphone", "écran", "sonnerie",
        "composer", "messagerie vocale", "appel téléphonique", "téléphone portable",
        "appelant", "appel entrant", "numéro de téléphone",
        "appel manqué",
        "appeler le médecin",
        "charger mon téléphone avant de partir",
        "acheter une nouvelle coque de téléphone",
        "appeler maman ce soir",
        "répondre à l'appel entrant",
        "vérifier mes appels manqués sur le téléphone",
        "planifier un appel téléphonique avec le client",
        "réparer l'écran fissuré du téléphone",
        "mettre à jour le logiciel du téléphone",
        "configurer le nouveau téléphone",
        "transférer les contacts sur le nouveau téléphone",
        "appeler le restaurant pour réserver",
        "mettre le téléphone en silencieux pendant la réunion",
        "enregistrer le numéro de téléphone dans mes contacts",
        "rappeler l'appel manqué",
        "charger le téléphone pendant la nuit",
        "acheter un protecteur d'écran pour le téléphone",
        "appeler le service client à propos de la commande",
        "décrocher le téléphone quand il sonne",
        "appeler le bureau pour confirmer la réunion",
        "remplacer la vieille batterie du téléphone",
        "télécharger une nouvelle appli sur le téléphone",
        "nettoyer l'écran du téléphone avec un chiffon",
        "appeler un taxi avec mon téléphone",
        "enregistrer un nouveau message vocal",
        "mettre une alarme sur le téléphone pour demain",
        "payer la facture de téléphone cette semaine",
        "sauvegarder les données du téléphone dans le cloud",
        "amener le téléphone au magasin de réparation",
        "passer le téléphone à mon collègue pour l'appel",
        "appeler l'école au sujet de l'emploi du temps",
        "couper le son du téléphone pendant le film",
        "brancher le téléphone au chargeur",
        "retrouver mon téléphone dans la maison",
        "passer à un modèle de téléphone plus récent",
        "vérifier le téléphone pour de nouveaux messages",
        "appeler le plombier pour la fuite",
        "appel téléphnoique au médecin",
        "chagrer le téléphone avant de partir",
        "numéor de téléphone à enregistrer",
        "répondre à l'appel enrtant",
        "protectueur d'écran pour le téléphone",
    ],
    "es": [
        "teléfono", "llamada", "auricular", "móvil", "celular",
        "número", "iPhone", "smartphone", "pantalla", "timbre",
        "marcar", "buzón de voz", "llamada telefónica", "teléfono celular",
        "persona que llama", "llamada entrante", "número de teléfono",
        "llamada perdida",
        "llamar al doctor por teléfono",
        "cargar mi teléfono antes de salir",
        "comprar una funda nueva para el teléfono",
        "llamar a mamá esta noche",
        "contestar la llamada entrante",
        "revisar mis llamadas perdidas en el teléfono",
        "programar una llamada telefónica con el cliente",
        "reparar la pantalla rota del teléfono",
        "actualizar el software del teléfono",
        "configurar el teléfono nuevo",
        "transferir contactos al teléfono nuevo",
        "llamar al restaurante para hacer una reservación",
        "poner el teléfono en silencio durante la reunión",
        "guardar el número de teléfono en mis contactos",
        "devolver la llamada perdida",
        "cargar el teléfono durante la noche",
        "comprar un protector de pantalla para el teléfono",
        "llamar al servicio al cliente por el pedido",
        "contestar el teléfono cuando suene",
        "llamar a la oficina para confirmar la reunión",
        "reemplazar la batería vieja del teléfono",
        "descargar una nueva app en el teléfono",
        "limpiar la pantalla del teléfono con un paño",
        "pedir un taxi con el teléfono",
        "grabar un nuevo saludo de buzón de voz",
        "poner una alarma en el teléfono para mañana",
        "pagar la cuenta del teléfono esta semana",
        "respaldar los datos del teléfono en la nube",
        "llevar el teléfono al taller de reparación",
        "pasarle el teléfono a mi colega para la llamada",
        "llamar a la escuela sobre el horario",
        "silenciar el teléfono durante la película",
        "enchufar el teléfono al cargador",
        "encontrar mi teléfono en la casa",
        "cambiar a un modelo de teléfono más nuevo",
        "revisar el teléfono por nuevos mensajes",
        "llamar al plomero para arreglar la fuga",
        "llamda telefónica al doctor",
        "cargra el teléfono antes de salir",
        "núemro de teléfono para guardar",
        "contestra la llamada entrante",
        "protecor de pantalla para el teléfono",
    ],
})


print("Part B (person-meditating, person-walking, phone) done.")
