#!/usr/bin/env python3
"""Batch task-003c: shish-kebab, shop, shorts (60 x 6 langs)."""

import csv
from pathlib import Path

icons_dir = Path("icons")


def write_csv(path, texts, label):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["text", "label"])
        for t in texts:
            w.writerow([t, label])


def build(icon, en, ru, de, ja, fr, es):
    for lang, data in [("en", en), ("ru", ru), ("de", de), ("ja", ja), ("fr", fr), ("es", es)]:
        deduped = list(dict.fromkeys(data))
        if len(deduped) != 60:
            raise ValueError(f"{icon} {lang} has {len(deduped)}, need 60")
        write_csv(icons_dir / icon / f"train_{lang}.csv", deduped, icon)
    print(f"  {icon}: EN=60 RU=60 DE=60 JA=60 FR=60 ES=60")


# ── shish-kebab ───────────────────────────────────────────────────────────────
build("shish-kebab",
en=[
    "kabob", "kebob", "shawarma", "skewer", "souvlaki",
    "kebab", "shish kebab", "grill", "BBQ", "meat stick",
    "doner", "kofta", "satay", "yakitori", "brochette",
    "grilled meat", "charcoal grill", "marinade",
    "grill shish kebab over hot coals",
    "BBQ grill with kebab skewers",
    "kabob skewer with marinated meat",
    "lamb kabob on metal skewer",
    "kebob cooked on charcoal fire",
    "chicken kebob with peppers",
    "grilled meat on a wooden skewer",
    "meat and vegetable skewer on grill",
    "shawarma spiced meat on vertical spit",
    "Middle Eastern shawarma wrap",
    "skewer of beef and vegetables grilled",
    "metal skewer over campfire",
    "souvlaki pork skewer in Greece",
    "souvlaki served in pita bread",
    "shish kebab skewer with alternating meat and vegetables",
    "lamb shish kebab grilled over charcoal",
    "Turkish doner kebab on vertical spit",
    "chicken souvlaki in pita with tzatziki",
    "BBQ skewer of marinated pork and peppers",
    "Middle Eastern kofta meatball kebab",
    "Persian lamb koobideh kebab on flat skewer",
    "street food skewer sold at night market",
    "Korean bulgogi beef skewer on grill",
    "vegetable skewer with mushrooms and zucchini",
    "marinate the chicken for kebabs tonight",
    "buy metal skewers for the barbecue",
    "grill kebabs at the backyard cookout",
    "order shish kebab from the Turkish restaurant",
    "prepare the lamb marinade for tomorrow's kebabs",
    "thread vegetables onto skewers for grilling",
    "pick up bamboo skewers at the grocery store",
    "make chicken satay skewers for the party",
    "try the street vendor's grilled kebabs",
    "cook yakitori chicken skewers at home",
    "bring kebab supplies to the camping trip",
    "lamb shish kebba grilled over charcoal",
    "chciken souvlaki in pita with tzatziki",
    "BBQ skweer of marinated pork",
    "Turksh doner kebab on vertical spit",
    "marinate the chciken for kebabs",
],
ru=[
    "кебаб", "кебоб", "шаурма", "шашлык", "сувлаки",
    "шиш-кебаб", "гриль", "барбекю", "мясо на палочке", "шампур",
    "донер", "кофта-кебаб", "сатай", "якитори", "брошет",
    "жареное мясо", "угольный гриль", "маринад",
    "шашлык из баранины на горячих углях",
    "барбекю-гриль с шашлыками",
    "шампур кебаба с маринованным мясом",
    "кебаб из баранины на металлическом шампуре",
    "кебоб приготовлен на угольном огне",
    "куриный кебоб с перцем",
    "жареное мясо на деревянном шампуре",
    "мясо и овощи на шампуре на гриле",
    "шаурма специи мясо на вертикальном вертеле",
    "шаурма ближневосточная в лаваше",
    "шашлык из говядины и овощей",
    "металлический шашлык над костром",
    "сувлаки из свинины в Греции",
    "сувлаки в лаваше",
    "шашлык с чередующимися мясом и овощами",
    "шашлык из баранины на угольном гриле",
    "турецкий донер-кебаб на вертикальном вертеле",
    "куриный сувлаки в лаваше с дзадзики",
    "BBQ-шашлык из маринованной свинины и перцев",
    "ближневосточный кофта-кебаб из мясных шариков",
    "персидский кубидэ из баранины на плоском шампуре",
    "уличная еда шашлык на ночном рынке",
    "корейский булгоги шашлык из говядины",
    "овощной шашлык с грибами и цукини",
    "замариновать курицу для шашлыков на вечер",
    "купить металлические шампуры для барбекю",
    "жарить шашлыки на заднем дворе",
    "заказать шиш-кебаб из турецкого ресторана",
    "приготовить маринад для завтрашних шашлыков",
    "нанизать овощи на шампуры для гриля",
    "купить бамбуковые шампуры в продуктовом",
    "сделать куриные сатай-шампуры для вечеринки",
    "попробовать шашлык у уличного продавца",
    "приготовить якитори из курицы дома",
    "взять припасы для шашлыков в поход",
    "шашлык из барнины на угольном гриле",
    "куриный сувлакии в лаваше",
    "BBQ-шашлык из маринованнй свинины",
    "турецкий донер-кебба на вертеле",
    "замарновать курицу для шашлыков",
],
de=[
    "Kebab", "Kebob", "Schawarma", "Spieß", "Souvlaki",
    "Schisch-Kebab", "Grill", "BBQ", "Fleischspieß", "Grillspieß",
    "Döner", "Köfte", "Satay", "Yakitori", "Brochette",
    "Grillfleisch", "Holzkohlegrill", "Marinade",
    "Schisch-Kebab über heißen Kohlen grillen",
    "BBQ-Grill mit Kebab-Spießen",
    "Kebab-Spieß mit mariniertem Fleisch",
    "Lammkebab auf Metallspieß",
    "Kebob auf Holzkohlefeuer gegrillt",
    "Hähnchenkebob mit Paprika",
    "gegrilltes Fleisch auf Holzspieß",
    "Fleisch und Gemüse auf Grillspieß",
    "Schawarma Gewürzfleisch am Drehspieß",
    "nahöstlicher Schawarma im Fladenbrot",
    "Rindfleisch und Gemüse gegrillt auf Spieß",
    "Metallspieß über Lagerfeuer",
    "Souvlaki Schweinespieß aus Griechenland",
    "Souvlaki im Pitabrot serviert",
    "Schisch-Kebab mit abwechselnd Fleisch und Gemüse",
    "Lammkebab auf Holzkohle gegrillt",
    "türkischer Döner am Drehspieß",
    "Hähnchen-Souvlaki im Pita mit Tzatziki",
    "BBQ-Spieß mit mariniertem Schweinefleisch",
    "Köfte-Kebab aus Fleischbällchen",
    "persischer Koobideh-Kebab auf Flachspieß",
    "Streetfood-Spieß auf Nachtmarkt",
    "koreanischer Bulgogi-Rindfleischspieß",
    "Gemüsespieß mit Pilzen und Zucchini",
    "Hähnchen für Kebabs heute Abend marinieren",
    "Metallspieße für Grillparty kaufen",
    "Kebabs beim Grillen im Garten grillen",
    "Schisch-Kebab im türkischen Restaurant bestellen",
    "Lammmarinade für morgen vorbereiten",
    "Gemüse auf Spieße fädeln zum Grillen",
    "Bambussspieße im Supermarkt besorgen",
    "Hähnchen-Satay-Spieße für die Party machen",
    "Kebabs beim Straßenverkäufer probieren",
    "Yakitori-Hähnchenspieße zu Hause kochen",
    "Kebab-Zubehör zum Camping mitnehmen",
    "Lammkebab auf Holzkhole gegrillt",
    "Hähnchen-Souvlki im Pita",
    "BBQ-Speiß mit mariniertem Schweinefleisch",
    "türksicher Döner am Drehspieß",
    "Hähnchen für Kebas heute marinieren",
],
ja=[
    "ケバブ", "ケボブ", "シャワルマ", "串", "スブラキ",
    "シシケバブ", "グリル", "バーベキュー", "肉串", "焼き鳥串",
    "ドネル", "コフタ", "サテー", "焼き鳥", "ブロシェット",
    "焼肉", "炭火焼き", "マリネ",
    "熱い炭の上でシシケバブを焼く",
    "ケバブ串のあるバーベキューグリル",
    "マリネした肉のケバブ串",
    "金属串のラムケバブ",
    "炭火で焼いたケボブ",
    "ピーマン入りチキンケボブ",
    "木の串で焼いた肉",
    "グリルの上の肉と野菜の串",
    "縦型回転焼きのシャワルマ",
    "中東のシャワルマラップ",
    "焼いた牛肉と野菜の串",
    "キャンプファイヤーの上の金属串",
    "ギリシャの豚肉スブラキ",
    "ピタパンに入ったスブラキ",
    "肉と野菜が交互に刺さったシシケバブ",
    "炭火焼きのラムシシケバブ",
    "トルコのドネルケバブ",
    "ツァツィキ入りピタのチキンスブラキ",
    "マリネ豚肉とピーマンのバーベキュー串",
    "中東のコフタミートボールケバブ",
    "ペルシャのクビデケバブ",
    "夜市で売られている串焼き",
    "韓国のプルコギ牛肉串",
    "きのことズッキーニの野菜串",
    "今夜のケバブ用にチキンをマリネする",
    "バーベキュー用の金属串を買う",
    "裏庭のバーベキューでケバブを焼く",
    "トルコ料理店でシシケバブを注文する",
    "明日のケバブ用にラムのマリネを準備する",
    "グリル用に串に野菜を刺す",
    "スーパーで竹串を買う",
    "パーティー用にチキンサテー串を作る",
    "屋台のケバブを試す",
    "家で焼き鳥串を作る",
    "キャンプにケバブの材料を持っていく",
    "炭火やきのラムケバブ",
    "チキンすぶらきをピタで食べる",
    "バーベキュー串でまりねした豚肉",
    "トルコのどねるケバブ",
    "けばぶ用にチキンをマリネする",
],
fr=[
    "kebab", "kébob", "chawarma", "brochette", "souvlaki",
    "chiche-kebab", "grill", "barbecue", "viande en brochette", "pic",
    "döner", "kefta", "satay", "yakitori", "brochette grillée",
    "viande grillée", "gril au charbon", "marinade",
    "griller des chiche-kebabs sur des braises",
    "barbecue avec des brochettes de kebab",
    "brochette de kebab à la viande marinée",
    "kebab d'agneau sur brochette en métal",
    "kébob cuit au feu de charbon",
    "kébob de poulet aux poivrons",
    "viande grillée sur une brochette en bois",
    "brochette de viande et légumes sur le gril",
    "chawarma viande épicée sur broche verticale",
    "chawarma du Moyen-Orient en pain pita",
    "brochette de bœuf et légumes grillée",
    "brochette en métal au-dessus du feu de camp",
    "souvlaki de porc en Grèce",
    "souvlaki servi dans du pain pita",
    "chiche-kebab avec viande et légumes alternés",
    "kebab d'agneau grillé au charbon",
    "döner turc sur broche verticale",
    "souvlaki de poulet en pita avec tzatziki",
    "brochette BBQ de porc mariné et poivrons",
    "kefta en boulettes du Moyen-Orient",
    "koobideh perse d'agneau sur brochette plate",
    "brochette de street food au marché de nuit",
    "brochette de bœuf bulgogi coréen",
    "brochette de légumes avec champignons et courgettes",
    "mariner le poulet pour les kebabs ce soir",
    "acheter des brochettes en métal pour le barbecue",
    "griller des kebabs lors du barbecue dans le jardin",
    "commander des chiche-kebabs au restaurant turc",
    "préparer la marinade d'agneau pour demain",
    "enfiler des légumes sur les brochettes pour griller",
    "acheter des pics en bambou au supermarché",
    "faire des brochettes satay de poulet pour la fête",
    "goûter les kebabs du vendeur ambulant",
    "cuisiner des yakitori de poulet à la maison",
    "apporter les fournitures kebab au camping",
    "kebab d'agnau grillé au charbon",
    "souvlki de poulet en pita",
    "brochette BBQ de porc marné",
    "döner turc sur broch verticale",
    "mariner le poulet pour les kebas ce soir",
],
es=[
    "kebab", "kebob", "shawarma", "brocheta", "souvlaki",
    "pincho", "parrilla", "barbacoa", "pincho de carne", "palillo",
    "döner", "kofta", "satay", "yakitori", "brocheta asada",
    "carne asada", "carbón", "adobo",
    "asar pincho de kebab sobre brasas",
    "parrilla de barbacoa con brochetas de kebab",
    "brocheta de kebab con carne marinada",
    "kebab de cordero en brocheta de metal",
    "kebob cocido al fuego de carbón",
    "kebob de pollo con pimientos",
    "carne asada en brocheta de madera",
    "brocheta de carne y verduras en la parrilla",
    "shawarma de carne especiada en asador vertical",
    "shawarma de Medio Oriente en pan pita",
    "brocheta de res y verduras a la parrilla",
    "brocheta de metal sobre fogata",
    "souvlaki de cerdo en Grecia",
    "souvlaki servido en pan pita",
    "pincho con carne y verduras alternadas",
    "kebab de cordero a la parrilla con carbón",
    "döner turco en asador vertical",
    "souvlaki de pollo en pita con tzatziki",
    "brocheta BBQ de cerdo marinado y pimientos",
    "kofta de albóndigas del Medio Oriente",
    "koobideh persa de cordero en brocheta plana",
    "brocheta callejera en mercado nocturno",
    "brocheta de res bulgogi coreano",
    "brocheta de verduras con champiñones y calabacín",
    "marinar el pollo para los kebabs esta noche",
    "comprar brochetas de metal para la barbacoa",
    "asar kebabs en la parrillada del patio",
    "pedir pincho kebab del restaurante turco",
    "preparar el adobo de cordero para mañana",
    "ensartar verduras en brochetas para asar",
    "comprar palillos de bambú en el supermercado",
    "hacer brochetas satay de pollo para la fiesta",
    "probar los kebabs del vendedor ambulante",
    "cocinar yakitori de pollo en casa",
    "llevar provisiones de kebab al camping",
    "kebab de cordro a la parrilla",
    "souvlaki de pollo en pita con tzatzki",
    "brocheta BBQ de cerdo marindao",
    "döner turco en asadr vertical",
    "marinar el pollo para los kebas esta noche",
],
)

# ── shop ──────────────────────────────────────────────────────────────────────
build("shop",
en=[
    "bodega", "buy", "market", "store", "shop",
    "retail", "purchase", "boutique", "mall", "grocery",
    "storefront", "vendor", "merchant", "bazaar", "outlet",
    "convenience store", "shopping", "commerce",
    "bodega corner shop open late night",
    "bodega with deli sandwiches and snacks",
    "buy groceries at convenience store",
    "open-air market with vendor stalls",
    "fresh produce market in town square",
    "purchase tickets at box office shop",
    "purchase items with contactless pay",
    "shopping at the mall with bags",
    "weekend shopping trip downtown",
    "store window display with sale signs",
    "grocery store entrance with cart",
    "small retail shop with sign above door",
    "boutique fashion shop in city center",
    "hardware store with tools in window",
    "shopping cart filled with items",
    "shop front with awning and display window",
    "farmer's market outdoor shop stalls",
    "gift shop at museum or tourist site",
    "pop-up shop temporary retail stall",
    "go to the shop for milk and bread",
    "visit the new boutique on Main Street",
    "buy birthday gifts at the mall",
    "compare prices at different shops",
    "pick up the online order at the store",
    "browse the antique shop for furniture",
    "stop at the corner store on the way home",
    "buy fresh vegetables at the market",
    "find a good deal at the outlet shop",
    "shop for school supplies this weekend",
    "check the store hours before going",
    "return the item to the shop for a refund",
    "small reatil shop with sign above door",
    "convienence store open 24 hours",
    "boutiqe fashion shop in city center",
    "shoppng cart filled with items",
    "buy grocereis at the corner store",
],
ru=[
    "магазин", "рынок", "шоппинг", "бодега", "покупка",
    "розница", "бутик", "торговый центр", "продуктовый", "витрина",
    "продавец", "торговец", "базар", "аутлет", "универсам",
    "мини-маркет", "коммерция", "лавка",
    "угловой магазин открыт поздно ночью",
    "бодега с бутербродами и закусками",
    "купить продукты в удобном магазине",
    "открытый рынок с прилавками продавцов",
    "рынок свежих продуктов на главной площади",
    "купить билеты в кассе",
    "купить товары бесконтактной оплатой",
    "шоппинг в торговом центре с сумками",
    "выходной поход за покупками в центр",
    "витрина магазина со знаками распродажи",
    "вход в продуктовый магазин с тележкой",
    "небольшой розничный магазин с вывеской над дверью",
    "бутик модной одежды в центре города",
    "хозяйственный магазин с инструментами в витрине",
    "корзина для покупок наполнена товарами",
    "витрина магазина с маркизой и дисплеем",
    "уличный рынок фермерских продуктов",
    "сувенирный магазин в музее или у достопримечательности",
    "временный pop-up магазин",
    "зайти в магазин за молоком и хлебом",
    "посетить новый бутик на главной улице",
    "купить подарки на день рождения в торговом центре",
    "сравнить цены в разных магазинах",
    "забрать онлайн-заказ из магазина",
    "осмотреть антикварный магазин в поиске мебели",
    "заскочить в магазинчик по дороге домой",
    "купить свежие овощи на рынке",
    "найти выгодное предложение в аутлете",
    "закупить школьные принадлежности в выходные",
    "проверить часы работы магазина перед визитом",
    "вернуть товар в магазин для возврата денег",
    "небольшой розничны магазин с вывеской",
    "круглосуточный магзаин",
    "бутик модной оджеды в центре",
    "корзина для покупк с товарами",
    "купить продуктыв удобном магзине",
],
de=[
    "Laden", "kaufen", "Markt", "Geschäft", "Shop",
    "Einzelhandel", "Einkauf", "Boutique", "Einkaufszentrum", "Lebensmittelgeschäft",
    "Schaufenster", "Händler", "Kaufmann", "Basar", "Outlet",
    "Kiosk", "Einkaufen", "Handel",
    "Eckladen spätabends geöffnet",
    "Kiosk mit Sandwiches und Snacks",
    "Lebensmittel im Supermarkt kaufen",
    "Freiluftmarkt mit Verkaufsständen",
    "Frischwarenmarkt auf dem Marktplatz",
    "Karten an der Theaterkasse kaufen",
    "Waren mit kontaktlosem Bezahlen kaufen",
    "Einkaufen im Einkaufszentrum mit Tüten",
    "Wochenend-Einkaufsbummel in der Innenstadt",
    "Schaufenster mit Verkaufsschildern",
    "Eingang zum Lebensmittelgeschäft mit Einkaufswagen",
    "kleiner Laden mit Schild über der Tür",
    "Modeboutique in der Innenstadt",
    "Baumarkt mit Werkzeug im Schaufenster",
    "Einkaufswagen voller Waren",
    "Ladenfront mit Markise und Schaufenster",
    "Bauernmarkt mit Freiluftständen",
    "Souvenirshop im Museum oder an Sehenswürdigkeit",
    "Pop-up-Shop temporärer Verkaufsstand",
    "zum Laden gehen für Milch und Brot",
    "neue Boutique in der Hauptstraße besuchen",
    "Geburtstagsgeschenke im Einkaufszentrum kaufen",
    "Preise in verschiedenen Geschäften vergleichen",
    "Online-Bestellung im Laden abholen",
    "Antiquitätengeschäft nach Möbeln durchstöbern",
    "am Eckladen auf dem Heimweg vorbeischauen",
    "frisches Gemüse auf dem Markt kaufen",
    "gutes Angebot im Outlet finden",
    "Schulbedarf am Wochenende einkaufen",
    "Öffnungszeiten vor dem Besuch prüfen",
    "Artikel im Laden für Erstattung zurückgeben",
    "kleiner Ladn mit Schild über der Tür",
    "Einkaufszentrum mit Verkaufsschildrn",
    "Freiluftmrkt mit Verkaufsständen",
    "Boutiqe in der Innenstadt",
    "Einkaufswgen voller Waren",
],
ja=[
    "店", "買う", "市場", "ストア", "ショップ",
    "小売", "購入", "ブティック", "モール", "食料品店",
    "店頭", "売り手", "商人", "バザール", "アウトレット",
    "コンビニ", "買い物", "商業",
    "夜遅くまで開いている角の店",
    "サンドイッチとスナックのある売店",
    "コンビニで食料品を買う",
    "露店が並ぶ青空市場",
    "町の広場の生鮮市場",
    "チケット売り場でチケットを買う",
    "非接触決済で商品を購入する",
    "バッグを持ってモールで買い物",
    "週末に繁華街でショッピング",
    "セールの看板がある店のウィンドウ",
    "カート付きの食料品店の入口",
    "ドアの上に看板がある小さな小売店",
    "街の中心のブティックファッション店",
    "窓に工具が並ぶ金物店",
    "商品でいっぱいのショッピングカート",
    "日よけとショーウィンドウのある店頭",
    "屋外のファーマーズマーケット",
    "博物館や観光地のギフトショップ",
    "ポップアップショップの一時販売店",
    "牛乳とパンを買いに店に行く",
    "メインストリートの新しいブティックを訪れる",
    "モールで誕生日プレゼントを買う",
    "色々な店で値段を比較する",
    "店でオンライン注文品を受け取る",
    "家具を探してアンティークショップを見る",
    "帰り道にコンビニに寄る",
    "市場で新鮮な野菜を買う",
    "アウトレットでお得な商品を見つける",
    "週末に学用品を買いに行く",
    "行く前に店の営業時間を確認する",
    "返金のために商品を店に返す",
    "小さなこうり店に看板がある",
    "まるいちにちえいぎょうのコンビニ",
    "ブティクファッション店",
    "ショッピングかーとに商品を入れる",
    "しょくりょうひんを角の店でかう",
],
fr=[
    "boutique", "acheter", "marché", "magasin", "shop",
    "commerce de détail", "achat", "échoppe", "centre commercial", "épicerie",
    "vitrine", "vendeur", "commerçant", "bazar", "magasin d'usine",
    "supérette", "shopping", "commerce",
    "échoppe de quartier ouverte tard le soir",
    "épicerie avec sandwiches et snacks",
    "acheter des courses à la supérette",
    "marché en plein air avec des stands",
    "marché de produits frais sur la place",
    "acheter des billets au guichet",
    "acheter des articles en paiement sans contact",
    "faire du shopping au centre commercial avec des sacs",
    "sortie shopping le week-end en centre-ville",
    "vitrine avec des panneaux de soldes",
    "entrée de l'épicerie avec un chariot",
    "petit commerce avec enseigne au-dessus de la porte",
    "boutique de mode en centre-ville",
    "quincaillerie avec des outils en vitrine",
    "chariot de courses rempli d'articles",
    "devanture de boutique avec auvent et vitrine",
    "marché de producteurs en plein air",
    "boutique de souvenirs au musée",
    "boutique éphémère temporaire",
    "aller au magasin chercher du lait et du pain",
    "visiter la nouvelle boutique sur la rue principale",
    "acheter des cadeaux d'anniversaire au centre commercial",
    "comparer les prix dans différents magasins",
    "récupérer la commande en ligne au magasin",
    "fouiller le magasin d'antiquités pour des meubles",
    "s'arrêter à la supérette en rentrant",
    "acheter des légumes frais au marché",
    "trouver une bonne affaire au magasin d'usine",
    "acheter les fournitures scolaires ce week-end",
    "vérifier les horaires du magasin avant d'y aller",
    "retourner l'article au magasin pour un remboursement",
    "petit comerce avec enseigne au-dessus",
    "suprette ouverte 24 heures",
    "boutiqu de mode en centre-ville",
    "chariot de courses rempli d'artciles",
    "acheter des corses à la supérette",
],
es=[
    "tienda", "comprar", "mercado", "almacén", "shop",
    "comercio minorista", "compra", "boutique", "centro comercial", "supermercado",
    "escaparate", "vendedor", "comerciante", "bazar", "outlet",
    "tienda de conveniencia", "compras", "comercio",
    "tienda de esquina abierta hasta tarde",
    "bodega con sándwiches y snacks",
    "comprar víveres en la tienda de conveniencia",
    "mercado al aire libre con puestos de vendedores",
    "mercado de productos frescos en la plaza",
    "comprar entradas en la taquilla",
    "comprar artículos con pago sin contacto",
    "ir de compras al centro comercial con bolsas",
    "salida de compras el fin de semana al centro",
    "escaparate con carteles de rebajas",
    "entrada del supermercado con carrito",
    "pequeña tienda minorista con letrero sobre la puerta",
    "boutique de moda en el centro de la ciudad",
    "ferretería con herramientas en el escaparate",
    "carrito de compras lleno de artículos",
    "frente de tienda con toldo y vitrina",
    "mercado de agricultores al aire libre",
    "tienda de regalos en el museo o sitio turístico",
    "tienda pop-up temporal",
    "ir a la tienda por leche y pan",
    "visitar la nueva boutique en la calle principal",
    "comprar regalos de cumpleaños en el centro comercial",
    "comparar precios en diferentes tiendas",
    "recoger el pedido en línea en la tienda",
    "recorrer la tienda de antigüedades buscando muebles",
    "parar en la tienda de la esquina de camino a casa",
    "comprar verduras frescas en el mercado",
    "encontrar una buena oferta en el outlet",
    "comprar útiles escolares este fin de semana",
    "verificar el horario de la tienda antes de ir",
    "devolver el artículo a la tienda para reembolso",
    "pequeña tiena minorista con letrero",
    "tienda de convenincia abierta 24 horas",
    "boutiqu de moda en el centro",
    "carrito de compras lleno de artíclos",
    "comprar vívres en la tienda de esquina",
],
)

# ── shorts ────────────────────────────────────────────────────────────────────
build("shorts",
en=[
    "boxers", "drawers", "shorts", "swimsuit", "trunks",
    "underwear", "gym shorts", "board shorts", "denim shorts", "cargo shorts",
    "athletic shorts", "running shorts", "swim trunks", "summer wear", "cutoffs",
    "bermudas", "jogging shorts", "casual shorts",
    "boxer shorts in a laundry pile",
    "elastic waistband boxers on a hanger",
    "casual pants cut short at the thigh",
    "pair of shorts for a summer outing",
    "denim shorts with cuffed hems",
    "summer shorts on a beach day",
    "bright summer shorts in a tropical print",
    "swimsuit trunks for the pool",
    "board shorts worn as a swimsuit at the beach",
    "swim trunks for the outdoor pool",
    "cotton underwear boxer shorts",
    "knee-length shorts with two side pockets",
    "wear shorts on a warm summer afternoon",
    "athletic shorts with a drawstring elastic waist",
    "pack a pair of shorts for the beach vacation",
    "light cotton shorts folded on a shelf",
    "pull on shorts for a morning jog in the park",
    "denim cutoff shorts with a frayed hem",
    "buy new gym shorts for the fitness class",
    "try on cargo shorts at the store",
    "pack summer shorts for the camping trip",
    "fold the clean shorts and put them in the drawer",
    "buy board shorts for the surfing trip",
    "replace the old running shorts with new ones",
    "order bermuda shorts from the online shop",
    "find matching shorts for the beach outfit",
    "wash the gym shorts after every workout",
    "choose lightweight shorts for the hike",
    "hang the wet swim trunks to dry",
    "pick out shorts for the kids' summer camp",
    "try on linen shorts at the boutique",
    "donate outgrown shorts to charity",
    "hem the shorts to the right length",
    "compare prices on running shorts online",
    "shoorts for a summer day",
    "shrots folded in a drawer",
    "horts for the gym session",
    "shortts with a drawstring waist",
    "buy new gym shrots for the class",
],
ru=[
    "боксеры", "шорты", "купальник", "плавки", "нижнее белье",
    "спортивные шорты", "бордшорты", "джинсовые шорты", "шорты-карго", "атлетические шорты",
    "беговые шорты", "плавательные шорты", "летняя одежда", "обрезные шорты",
    "бермуды", "шорты для бега", "повседневные шорты", "пляжные шорты",
    "боксеры в корзине для стирки",
    "боксеры на резинке висят на вешалке",
    "повседневные брюки укорочены до шорт",
    "пара шорт для летней прогулки",
    "джинсовые шорты с подвернутым краем",
    "летние шорты для дня на пляже",
    "яркие летние шорты с тропическим принтом",
    "плавательные шорты для бассейна",
    "бордшорты как купальник на пляже",
    "плавки для открытого бассейна",
    "хлопковые бельевые шорты",
    "шорты до колена с двумя карманами",
    "носить шорты теплым летним днем",
    "спортивные шорты с эластичным поясом и шнурком",
    "собрать шорты для отпуска на пляже",
    "легкие хлопковые шорты сложены на полке",
    "надеть шорты для утренней пробежки",
    "джинсовые короткие шорты с рваным краем",
    "купить новые спортивные шорты для фитнеса",
    "примерить шорты-карго в магазине",
    "собрать летние шорты для похода",
    "сложить чистые шорты и убрать в ящик",
    "купить бордшорты для серфинга",
    "заменить старые беговые шорты на новые",
    "заказать бермуды из интернет-магазина",
    "подобрать шорты к пляжному наряду",
    "стирать спортивные шорты после каждой тренировки",
    "выбрать лёгкие шорты для похода",
    "повесить мокрые плавки сушиться",
    "выбрать шорты для летнего лагеря детей",
    "примерить льняные шорты в бутике",
    "отдать маленькие шорты на благотворительность",
    "подшить шорты до нужной длины",
    "сравнить цены на беговые шорты онлайн",
    "шорты для летнего дня",
    "шорты сложены в ящике",
    "шорты для тренировки в зале",
    "шорты на поясе со шнурком",
    "купить новые шорты для фитнса",
],
de=[
    "Boxershorts", "Shorts", "Badehose", "Unterwäsche", "Sportshorts",
    "Boardshorts", "Jeansshorts", "Cargoshorts", "Laufshorts", "Badeshorts",
    "Sommerkleidung", "Cutoffs", "Bermudas", "Joggingshorts", "Freizeitshorts",
    "Kurze Hose", "Turnhose", "Schwimmhose",
    "Boxershorts im Wäschehaufen",
    "Boxershorts mit Gummibund auf Bügel",
    "Alltagshose am Oberschenkel gekürzt",
    "kurze Hose für einen Sommerausflug",
    "Jeansshorts mit umgeschlagenem Saum",
    "Sommershorts am Strandtag",
    "leuchtende Sommershorts mit Tropenprint",
    "Badehose für den Pool",
    "Boardshorts als Badebekleidung am Strand",
    "Schwimmhose für das Freibad",
    "Baumwoll-Boxershorts Unterwäsche",
    "knielange Shorts mit zwei Seitentaschen",
    "Shorts an einem warmen Sommernachmittag tragen",
    "Sportshorts mit Kordelzug und Gummibund",
    "ein Paar Shorts für den Strandurlaub einpacken",
    "leichte Baumwollshorts auf Regal gefaltet",
    "Shorts für den Morgenlauf anziehen",
    "Jeans-Cutoff-Shorts mit ausgefranstem Saum",
    "neue Sportshorts für Fitnessklasse kaufen",
    "Cargoshorts im Laden anprobieren",
    "Sommershorts für den Campingtrip einpacken",
    "saubere Shorts falten und in Schublade legen",
    "Boardshorts für den Surftrip kaufen",
    "alte Laufshorts durch neue ersetzen",
    "Bermudashorts im Online-Shop bestellen",
    "passende Shorts für das Strandoutfit finden",
    "Sportshorts nach jedem Training waschen",
    "leichte Shorts für die Wanderung wählen",
    "nasse Badehose zum Trocknen aufhängen",
    "Shorts für das Sommerferienlager der Kinder aussuchen",
    "Leinenshorts in der Boutique anprobieren",
    "zu klein gewordene Shorts spenden",
    "Shorts auf die richtige Länge kürzen",
    "Preise für Laufshorts online vergleichen",
    "Sommershorts für einen Sommertag",
    "Shrots im Schublade gefaltet",
    "Horts für das Gym-Training",
    "Shortes mit Kordelzug am Bund",
    "neue Sportshorts für die Klase kaufen",
],
ja=[
    "ボクサーパンツ", "ショーツ", "水着", "トランクス", "下着",
    "スポーツショーツ", "ボードショーツ", "デニムショーツ", "カーゴショーツ", "アスレチックショーツ",
    "ランニングショーツ", "スイムトランクス", "夏服", "カットオフ",
    "バミューダパンツ", "ジョギングショーツ", "カジュアルショーツ", "ジムショーツ",
    "洗濯物の山にあるボクサーパンツ",
    "ハンガーにかかったゴムウエストのボクサー",
    "太ももで短く切ったカジュアルパンツ",
    "夏のお出かけ用のショートパンツ",
    "裾を折り返したデニムショーツ",
    "ビーチの日の夏のショーツ",
    "トロピカル柄の明るい夏のショーツ",
    "プール用の水着トランクス",
    "ビーチで水着として履くボードショーツ",
    "屋外プール用のスイムトランクス",
    "コットンのボクサーショーツ下着",
    "サイドポケット付きの膝丈ショーツ",
    "暖かい夏の午後にショーツを履く",
    "ドローストリング付きスポーツショーツ",
    "ビーチ休暇用にショーツを詰める",
    "棚に畳んで置かれた軽いコットンショーツ",
    "朝のジョギング用にショーツを履く",
    "ほつれた裾のデニムカットオフショーツ",
    "フィットネスクラス用に新しいジムショーツを買う",
    "店でカーゴショーツを試着する",
    "キャンプ用に夏のショーツを詰める",
    "きれいなショーツを畳んで引き出しにしまう",
    "サーフィン旅行用にボードショーツを買う",
    "古いランニングショーツを新しいものに交換する",
    "オンラインショップでバミューダパンツを注文する",
    "ビーチコーデに合うショーツを見つける",
    "毎回のトレーニング後にジムショーツを洗う",
    "ハイキング用に軽いショーツを選ぶ",
    "濡れたスイムトランクスを干す",
    "子供の夏キャンプ用のショーツを選ぶ",
    "ブティックでリネンショーツを試着する",
    "サイズアウトしたショーツを寄付する",
    "ショーツを適切な丈に裾上げする",
    "ランニングショーツの値段をオンラインで比較する",
    "夏の日のしょーつ",
    "引き出しに畳まれたしょうつ",
    "ジムのとれーにんぐ用ショーツ",
    "ひも付きウエストのしょーつ",
    "新しいじむショーツを買う",
],
fr=[
    "boxer", "short", "maillot de bain", "caleçon", "sous-vêtement",
    "short de sport", "boardshort", "short en jean", "short cargo", "short de course",
    "short de bain", "vêtement d'été", "short coupé", "bermuda",
    "short de jogging", "short décontracté", "short de gym", "short de plage",
    "boxers dans le tas de linge",
    "boxers à taille élastique sur un cintre",
    "pantalon décontracté coupé à la cuisse",
    "paire de shorts pour une sortie d'été",
    "short en jean avec ourlet retroussé",
    "short d'été à la plage",
    "short d'été coloré à motif tropical",
    "maillot de bain pour la piscine",
    "boardshort comme maillot à la plage",
    "short de bain pour la piscine extérieure",
    "boxers en coton sous-vêtement",
    "short aux genoux avec deux poches latérales",
    "porter un short par un chaud après-midi d'été",
    "short de sport avec cordon et taille élastique",
    "préparer un short pour les vacances à la plage",
    "short en coton léger plié sur une étagère",
    "enfiler un short pour le jogging matinal",
    "short en jean coupé avec ourlet effiloché",
    "acheter un nouveau short de gym pour le cours",
    "essayer un short cargo en magasin",
    "préparer des shorts d'été pour le camping",
    "plier les shorts propres et les ranger dans le tiroir",
    "acheter un boardshort pour le voyage de surf",
    "remplacer les vieux shorts de course par des neufs",
    "commander un bermuda dans la boutique en ligne",
    "trouver un short assorti pour la tenue de plage",
    "laver le short de sport après chaque entraînement",
    "choisir un short léger pour la randonnée",
    "suspendre le maillot mouillé pour sécher",
    "choisir des shorts pour le camp d'été des enfants",
    "essayer un short en lin à la boutique",
    "donner les shorts devenus trop petits",
    "ourler le short à la bonne longueur",
    "comparer les prix des shorts de course en ligne",
    "shrots pour une journée d'été",
    "shrots pliés dans un tiroir",
    "horts pour la séance de gym",
    "shotrs avec cordon à la taille",
    "acheter de nouveaux shrots de gym",
],
es=[
    "bóxers", "shorts", "traje de baño", "calzoncillos", "ropa interior",
    "shorts deportivos", "shorts de playa", "shorts de mezclilla", "shorts cargo", "shorts de correr",
    "shorts de baño", "ropa de verano", "shorts recortados", "bermudas",
    "shorts de jogging", "shorts casuales", "shorts de gimnasio", "shorts de natación",
    "bóxers en el montón de ropa sucia",
    "bóxers con cintura elástica en un gancho",
    "pantalón casual cortado a la altura del muslo",
    "par de shorts para una salida de verano",
    "shorts de mezclilla con dobladillo enrollado",
    "shorts de verano en un día de playa",
    "shorts de verano coloridos con estampado tropical",
    "traje de baño tipo short para la piscina",
    "shorts de playa usados como traje de baño",
    "shorts de baño para la piscina al aire libre",
    "bóxers de algodón ropa interior",
    "shorts hasta la rodilla con dos bolsillos laterales",
    "usar shorts en una tarde cálida de verano",
    "shorts deportivos con cordón y cintura elástica",
    "empacar shorts para las vacaciones de playa",
    "shorts de algodón ligero doblados en un estante",
    "ponerse shorts para trotar por la mañana",
    "shorts de mezclilla recortados con dobladillo deshilachado",
    "comprar shorts de gimnasio nuevos para la clase",
    "probarse shorts cargo en la tienda",
    "empacar shorts de verano para el viaje de camping",
    "doblar los shorts limpios y guardarlos en el cajón",
    "comprar shorts de playa para el viaje de surf",
    "reemplazar los shorts de correr viejos por nuevos",
    "pedir bermudas en la tienda en línea",
    "encontrar shorts que combinen con el atuendo de playa",
    "lavar los shorts de gimnasio después de cada entrenamiento",
    "elegir shorts ligeros para la caminata",
    "colgar los shorts de baño mojados a secar",
    "elegir shorts para el campamento de verano de los niños",
    "probarse shorts de lino en la boutique",
    "donar shorts que quedaron chicos",
    "hacer el dobladillo de los shorts al largo correcto",
    "comparar precios de shorts de correr en línea",
    "shrots para un día de verano",
    "shrots doblados en un cajón",
    "horts para la sesión de gimnasio",
    "shortts con cordón en la cintura",
    "comprar shorts de gimnasio nuevso para la clase",
],
)

print("Part 3 done: shish-kebab, shop, shorts")
