#!/usr/bin/env python3
"""Batch task-003: Generate 60 phrases x 6 languages for 10 icons.

Icons: scissors, scroll, seedling, sheep, sheet-plastic,
       shirt, shirt-running, shish-kebab, shop, shorts

Cleans existing EN/RU (removes visual, devspeak, boundary/wrong, mixed-lang),
keeps good rows, fills to 60. Creates DE/JA/FR/ES from scratch (60 each).
"""

import csv
from pathlib import Path

icons_dir = Path("icons")


def read_rows(path):
    if not path.exists():
        return []
    with path.open(encoding="utf-8", newline="") as f:
        return [r["text"].strip() for r in csv.DictReader(f)]


def write_csv(path, texts, label):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["text", "label"])
        for t in texts:
            w.writerow([t, label])


def build(icon, en, ru, de, ja, fr, es):
    """Write all 6 langs, assert 60 each."""
    for lang, data in [("en", en), ("ru", ru), ("de", de), ("ja", ja), ("fr", fr), ("es", es)]:
        deduped = list(dict.fromkeys(data))
        if len(deduped) != 60:
            raise ValueError(f"{icon} {lang} has {len(deduped)}, need 60")
        write_csv(icons_dir / icon / f"train_{lang}.csv", deduped, icon)
    print(f"  {icon}: EN=60 RU=60 DE=60 JA=60 FR=60 ES=60")


# ── scissors ──────────────────────────────────────────────────────────────────
build("scissors",
en=[
    # keywords (~18)
    "clip", "cutting", "scissors", "snip", "trim",
    "shears", "cut", "craft scissors", "paper scissors", "fabric scissors",
    "kitchen shears", "nail scissors", "sewing scissors", "hair scissors",
    "pinking shears", "embroidery scissors", "pruning shears", "safety scissors",
    # task phrases
    "clip coupon with scissors along dotted line",
    "clip art paper with scissors",
    "cutting paper with sharp scissors",
    "cutting fabric along sewing pattern",
    "scissors for cutting paper in class",
    "scissors in craft supply kit",
    "snip thread end after sewing",
    "snip corner of envelope to open",
    "tool for cutting ribbon and wrapping",
    "barber tool for snipping hair",
    "hair cutting scissors at barbershop",
    "fabric scissors for seamstress work",
    "precision scissors for paper crafting",
    "kitchen shears for cutting poultry",
    "nail scissors for trimming fingernails",
    "scissors cutting ribbon at grand opening",
    "buy new scissors at the office supply store",
    "cut wrapping paper for birthday gift",
    "trim the hedge with garden shears",
    "cut coupons from the newspaper",
    "snip the tag off the new shirt",
    "trim bangs at home with hair scissors",
    "cut out magazine photos for scrapbook",
    "sharpen dull scissors before craft project",
    "buy child-safe scissors for the kids",
    "cut ribbon for the gift basket",
    "trim loose thread from jacket sleeve",
    "replace broken kitchen shears",
    "cut shapes out of construction paper",
    "pack scissors in the sewing kit",
    "use pinking shears on quilt fabric",
    "snip herbs from the garden with scissors",
    "cut open the package with scissors",
    "trim the dog's fur with grooming shears",
    "bring scissors to the craft workshop",
    "cut felt pieces for the puppet project",
    # typos (~5)
    "pair of sissors with two blade handles",
    "hair cuting scissors at barbershop",
    "chidl-safe scissors with blunt tip",
    "trimm the edges of printed photos",
    "cut wrappping paper for the gift",
],
ru=[
    # keywords (~18)
    "ножницы", "резка", "стрижка", "обрезка", "ножницы для бумаги",
    "ножницы по ткани", "кухонные ножницы", "маникюрные ножницы",
    "швейные ножницы", "парикмахерские ножницы", "садовые ножницы",
    "канцелярские ножницы", "ножницы для вышивки", "безопасные ножницы",
    "секатор", "филировочные ножницы", "портновские ножницы", "ножницы зигзаг",
    # task phrases
    "вырезать купон по пунктирной линии ножницами",
    "вырезать бумагу ножницами",
    "резка бумаги острыми ножницами",
    "резка ткани по выкройке",
    "ножницы для резки бумаги на уроке",
    "ножницы в наборе для творчества",
    "остричь конец нитки после шитья",
    "отрезать уголок конверта чтобы открыть",
    "инструмент для резки ленты и упаковки",
    "парикмахерский инструмент для стрижки",
    "ножницы для стрижки волос в барбершопе",
    "ножницы по ткани для швеи",
    "кухонные ножницы для разделки птицы",
    "ногтевые ножницы для обрезки ногтей",
    "разрезание ленты ножницами на торжественном открытии",
    "купить новые ножницы в канцтоварах",
    "нарезать обёрточную бумагу для подарка",
    "подстричь живую изгородь садовыми ножницами",
    "вырезать купоны из газеты",
    "отрезать бирку с новой рубашки",
    "подровнять чёлку дома парикмахерскими ножницами",
    "вырезать фотографии из журнала для альбома",
    "наточить тупые ножницы перед рукоделием",
    "купить детские безопасные ножницы",
    "отрезать ленту для подарочной корзины",
    "обрезать свободную нитку на рукаве куртки",
    "заменить сломанные кухонные ножницы",
    "вырезать фигуры из цветной бумаги",
    "положить ножницы в швейный набор",
    "нарезать ткань ножницами зигзаг для квилта",
    "срезать зелень в саду ножницами",
    "вскрыть посылку ножницами",
    "подстричь шерсть собаки груминговыми ножницами",
    "взять ножницы на мастер-класс по рукоделию",
    "нарезать фетр для кукольного проекта",
    # typos (~5)
    "ножнциы с двумя лезвиями",
    "ножницы для стрижки волос в барбешропе",
    "безопасные ножинцы для детей",
    "подрвнять края напечатанных фотографий",
    "нарзеать бумагу для оригами",
],
de=[
    "Schere", "Schneiden", "Zuschneiden", "Kürzen", "Abschneiden",
    "Bastelschere", "Papierschere", "Stoffschere", "Küchenschere",
    "Nagelschere", "Nähschere", "Haarschere", "Zackenschere",
    "Gartenschere", "Stickschere", "Kinderschere", "Effilierschere",
    "Heckenschere",
    "Gutschein mit der Schere ausschneiden",
    "Papier mit scharfer Schere schneiden",
    "Stoff entlang der Naht zuschneiden",
    "Schere für den Bastelunterricht einpacken",
    "Faden nach dem Nähen abschneiden",
    "Ecke des Umschlags abschneiden zum Öffnen",
    "Geschenkband mit der Schere schneiden",
    "Haare beim Friseur schneiden lassen",
    "Stoffschere für die Schneiderin",
    "Küchenschere zum Zerteilen von Geflügel",
    "Nagelschere zum Kürzen der Fingernägel",
    "Band bei Eröffnung mit Schere durchschneiden",
    "neue Schere im Bürogeschäft kaufen",
    "Geschenkpapier für Geburtstag zuschneiden",
    "Hecke mit der Gartenschere stutzen",
    "Kupons aus der Zeitung ausschneiden",
    "Etikett von der neuen Bluse abschneiden",
    "Pony zu Hause mit Haarschere nachschneiden",
    "Zeitschriftenbilder für Sammelalbum ausschneiden",
    "stumpfe Schere vor dem Basteln schärfen",
    "Kinderschere für die Kinder kaufen",
    "Band für den Geschenkkorb abschneiden",
    "losen Faden am Jackenärmel abschneiden",
    "kaputte Küchenschere ersetzen",
    "Formen aus Bastelpapier ausschneiden",
    "Schere in das Nähset packen",
    "Stoff mit Zackenschere für Quilt schneiden",
    "Kräuter im Garten mit Schere ernten",
    "Paket mit der Schere öffnen",
    "Hundefell mit Pflegeschere trimmen",
    "Schere zum Bastelworkshop mitbringen",
    "Filz für Puppenprojekt zuschneiden",
    "Ränder der gedruckten Fotos beschneiden",
    "Schere für Schulprojekte besorgen",
    "Origami-Papier mit der Schere schneiden",
    # typos
    "Papir mit scharfer Schere schneiden",
    "Küchenshere zum Zerteilen von Geflügel",
    "neue Schere im Bürogeschäf kaufen",
    "Hecke mit der Gartenshere stutzen",
    "Geschnekpapier zuschneiden",
],
ja=[
    "はさみ", "切る", "カット", "トリミング", "切り取り",
    "工作はさみ", "紙はさみ", "布はさみ", "キッチンはさみ",
    "爪はさみ", "裁縫はさみ", "ヘアはさみ", "ピンキングはさみ",
    "園芸はさみ", "刺繍はさみ", "子供用はさみ", "すきばさみ",
    "剪定ばさみ",
    "クーポンをはさみで切り取る",
    "鋭いはさみで紙を切る",
    "型紙に沿って布を裁断する",
    "工作の授業にはさみを持っていく",
    "縫い終わりに糸をはさみで切る",
    "封筒の角を切って開ける",
    "リボンをはさみで切る",
    "美容院で髪を切ってもらう",
    "裁縫用の布はさみ",
    "キッチンはさみで鶏肉を切る",
    "爪はさみで爪を整える",
    "オープニングでリボンを切る",
    "文房具店で新しいはさみを買う",
    "誕生日プレゼントの包装紙を切る",
    "庭の生け垣を園芸はさみで刈る",
    "新聞からクーポンを切り取る",
    "新しいシャツのタグを切り取る",
    "自宅でヘアはさみで前髪を切る",
    "雑誌の写真をスクラップブック用に切る",
    "工作前に切れないはさみを研ぐ",
    "子供用の安全はさみを買う",
    "ギフトバスケット用のリボンを切る",
    "ジャケットの袖のほつれた糸を切る",
    "壊れたキッチンはさみを交換する",
    "色画用紙から形を切り抜く",
    "裁縫セットにはさみを入れる",
    "キルト用の布をピンキングはさみで切る",
    "庭のハーブをはさみで摘む",
    "荷物をはさみで開封する",
    "犬の毛をトリミングはさみで整える",
    "ワークショップにはさみを持参する",
    "人形プロジェクト用にフェルトを切る",
    "印刷した写真の端を切り揃える",
    "学校の工作用はさみを用意する",
    "折り紙用の紙をはさみで切る",
    # typos
    "はさみで紙をきる",
    "キチンはさみで鶏肉を切る",
    "はさみをもっていく",
    "包装紙をきり取る",
    "はさみで布をさいだんする",
],
fr=[
    "ciseaux", "couper", "découper", "tailler", "rogner",
    "ciseaux de bricolage", "ciseaux à papier", "ciseaux à tissu",
    "ciseaux de cuisine", "ciseaux à ongles", "ciseaux de couture",
    "ciseaux de coiffure", "ciseaux cranteurs", "sécateur",
    "ciseaux à broder", "ciseaux pour enfants", "ciseaux à effiler",
    "cisaille de jardin",
    "découper un coupon avec des ciseaux",
    "couper du papier avec des ciseaux bien aiguisés",
    "tailler le tissu le long du patron",
    "emporter des ciseaux pour le cours de bricolage",
    "couper le fil après la couture",
    "couper le coin de l'enveloppe pour l'ouvrir",
    "couper le ruban avec des ciseaux",
    "se faire couper les cheveux chez le coiffeur",
    "ciseaux à tissu pour la couturière",
    "ciseaux de cuisine pour découper la volaille",
    "ciseaux à ongles pour couper les ongles",
    "couper le ruban lors de l'inauguration",
    "acheter de nouveaux ciseaux à la papeterie",
    "découper le papier cadeau pour un anniversaire",
    "tailler la haie avec le sécateur",
    "découper des coupons dans le journal",
    "couper l'étiquette de la nouvelle chemise",
    "couper la frange à la maison avec des ciseaux",
    "découper des photos de magazine pour un album",
    "aiguiser les ciseaux émoussés avant le bricolage",
    "acheter des ciseaux sécurisés pour les enfants",
    "couper le ruban pour le panier cadeau",
    "couper le fil qui dépasse de la manche",
    "remplacer les ciseaux de cuisine cassés",
    "découper des formes dans du papier cartonné",
    "mettre les ciseaux dans la trousse de couture",
    "couper le tissu avec des ciseaux cranteurs",
    "cueillir les herbes du jardin avec des ciseaux",
    "ouvrir le colis avec des ciseaux",
    "toiletter le chien avec des ciseaux de toilettage",
    "apporter des ciseaux à l'atelier de bricolage",
    "couper du feutre pour le projet de marionnettes",
    "rogner les bords des photos imprimées",
    "préparer des ciseaux pour les travaux manuels",
    "découper du papier pour l'origami",
    # typos
    "ciseax de cuisine pour la volaille",
    "acheter des ciseuax à la papeterie",
    "decouper le papier cadau pour un anniversaire",
    "couper le rubban avec des ciseaux",
    "tailer la haie avec le sécateur",
],
es=[
    "tijeras", "cortar", "recortar", "podar", "recorte",
    "tijeras de manualidades", "tijeras de papel", "tijeras de tela",
    "tijeras de cocina", "tijeras de uñas", "tijeras de costura",
    "tijeras de peluquería", "tijeras dentadas", "podadora",
    "tijeras de bordar", "tijeras para niños", "tijeras de entresacar",
    "tijeras de jardín",
    "recortar un cupón con tijeras",
    "cortar papel con tijeras afiladas",
    "cortar la tela siguiendo el patrón",
    "llevar tijeras a la clase de manualidades",
    "cortar el hilo después de coser",
    "cortar la esquina del sobre para abrirlo",
    "cortar la cinta con tijeras",
    "cortarse el pelo en la peluquería",
    "tijeras de tela para la costurera",
    "tijeras de cocina para trocear el pollo",
    "tijeras de uñas para cortarse las uñas",
    "cortar la cinta en la inauguración",
    "comprar tijeras nuevas en la papelería",
    "recortar el papel de regalo para el cumpleaños",
    "podar el seto con tijeras de jardín",
    "recortar cupones del periódico",
    "cortar la etiqueta de la camisa nueva",
    "recortarse el flequillo en casa con tijeras",
    "recortar fotos de revista para el álbum",
    "afilar las tijeras antes de hacer manualidades",
    "comprar tijeras seguras para los niños",
    "cortar la cinta para la cesta de regalo",
    "cortar el hilo suelto de la manga",
    "reemplazar las tijeras de cocina rotas",
    "recortar formas de cartulina",
    "guardar las tijeras en el costurero",
    "cortar tela con tijeras dentadas para el edredón",
    "cortar hierbas del jardín con tijeras",
    "abrir el paquete con tijeras",
    "recortar el pelo del perro con tijeras de aseo",
    "llevar tijeras al taller de manualidades",
    "cortar fieltro para el proyecto de títeres",
    "recortar los bordes de las fotos impresas",
    "preparar tijeras para trabajos escolares",
    "recortar papel para origami",
    # typos
    "tijerras de cocina para la volaille",
    "comprar tijras nuevas en la papelería",
    "recortar el papél de regalo",
    "cortar la cinta con tijras",
    "podar el seto con tijeras de jardin",
],
)

# ── scroll ────────────────────────────────────────────────────────────────────
build("scroll",
en=[
    "scroll", "parchment", "document", "decree", "manuscript",
    "papyrus", "ancient text", "scripture", "edict", "proclamation",
    "Torah scroll", "script", "announcement", "charter", "writ",
    "old document", "rolled paper", "vellum",
    "announcement written on rolled parchment scroll",
    "royal announcement on wax-sealed scroll",
    "fantasy quest scroll with map inside",
    "paper scroll unrolled to reveal message",
    "old paper scroll with faded writing",
    "scholar reading ancient scroll in library",
    "scholar transcribing scroll text",
    "script written on parchment scroll",
    "wax-sealed scroll tied with ribbon",
    "scroll unrolling to show decree",
    "ancient parchment scroll tied with ribbon",
    "rolled-up paper scroll with wax seal",
    "royal decree written on formal scroll",
    "Torah scroll in synagogue ceremony",
    "historical scroll discovered in cave",
    "fantasy treasure map inside a scroll",
    "announcement scroll posted on village notice board",
    "scholar reading ancient scroll by candlelight",
    "d&d spell scroll used in combat",
    "dnd character reading ancient scroll",
    "dnd lore written on aged scroll",
    "read the ancient scroll for the history class",
    "unroll the parchment scroll to check the text",
    "buy a decorative scroll for the living room",
    "write a medieval-style decree on a scroll",
    "find the old scroll in the attic trunk",
    "bring the Torah scroll to the synagogue",
    "roll up the document into a scroll",
    "study the Dead Sea scrolls exhibit",
    "make a scroll prop for the school play",
    "translate the Latin text on the old scroll",
    "preserve the fragile parchment scroll",
    "frame the diploma as a scroll",
    "prepare scroll invitations for the wedding",
    "photograph the museum scroll exhibit",
    "order a custom calligraphy scroll",
    # typos
    "anceint parchment scroll tied with ribbon",
    "D&D spells croll for magic user",
    "royal decre written on formal scroll",
    "hsitorical scroll discovered in cave",
    "reserach scroll preservation techniques",
],
ru=[
    "свиток", "пергамент", "документ", "декрет", "манускрипт",
    "папирус", "древний текст", "писание", "указ", "грамота",
    "свиток Торы", "скрипт", "объявление", "хартия", "рукопись",
    "старый документ", "свёрнутая бумага", "пергаментный свиток",
    "объявление на развёрнутом пергаментном свитке",
    "королевское объявление на свитке с сургучной печатью",
    "свиток квеста фэнтези с картой внутри",
    "бумажный свиток развёрнут показывает послание",
    "старый бумажный свиток с выцветшими письменами",
    "учёный читает древний свиток в библиотеке",
    "учёный переписывает текст свитка",
    "сценарий написан на пергаментном свитке",
    "свиток с сургучной печатью перевязан лентой",
    "свиток разворачивается и показывает декрет",
    "древний пергаментный свиток перевязан лентой",
    "скрученный бумажный свиток с сургучной печатью",
    "королевский декрет на официальном свитке",
    "свиток Торы на синагогальной церемонии",
    "исторический свиток найден в пещере",
    "карта сокровищ фэнтези внутри свитка",
    "свиток с объявлением на деревенской доске",
    "учёный читает древний свиток при свечах",
    "свиток заклинания D&D в бою",
    "персонаж dnd читает древний свиток",
    "лор dnd написан на старом свитке",
    "прочитать древний свиток для урока истории",
    "развернуть пергаментный свиток и проверить текст",
    "купить декоративный свиток для гостиной",
    "написать средневековый указ на свитке",
    "найти старый свиток в сундуке на чердаке",
    "принести свиток Торы в синагогу",
    "свернуть документ в свиток",
    "посетить выставку свитков Мёртвого моря",
    "сделать свиток-реквизит для школьного спектакля",
    "перевести латинский текст на старом свитке",
    "сохранить хрупкий пергаментный свиток",
    "оформить диплом как свиток в рамке",
    "подготовить свитки-приглашения на свадьбу",
    "сфотографировать свиток в музейной экспозиции",
    # typos
    "дрневний пергаментный свиток с лентой",
    "свиток зклинания D&D для мага",
    "королевский декрет на официальном свтике",
    "исторческий свиток найден в пещере",
    "заказать каллиграфческий свиток",
],
de=[
    "Schriftrolle", "Pergament", "Dokument", "Dekret", "Manuskript",
    "Papyrus", "alter Text", "Schrift", "Erlass", "Proklamation",
    "Tora-Rolle", "Skript", "Ankündigung", "Urkunde", "Handschrift",
    "altes Dokument", "gerolltes Papier", "Pergamentrolle",
    "Ankündigung auf einer Pergamentrolle geschrieben",
    "königliche Ankündigung auf versiegelter Schriftrolle",
    "Fantasy-Questrolle mit Karte darin",
    "Papierrolle ausgerollt zeigt Botschaft",
    "alte Papierrolle mit verblasster Schrift",
    "Gelehrter liest alte Schriftrolle in Bibliothek",
    "Gelehrter kopiert Text einer Schriftrolle",
    "Drehbuch auf Pergamentrolle geschrieben",
    "versiegelte Schriftrolle mit Band gebunden",
    "Schriftrolle entrollt zeigt Dekret",
    "antike Pergamentrolle mit Band",
    "aufgerollte Papierrolle mit Wachssiegel",
    "königliches Dekret auf offizieller Schriftrolle",
    "Tora-Rolle bei Synagogenzeremonie",
    "historische Schriftrolle in Höhle entdeckt",
    "Fantasy-Schatzkarte in einer Schriftrolle",
    "alte Schriftrolle für Geschichtsunterricht lesen",
    "Pergamentrolle ausrollen und Text prüfen",
    "dekorative Schriftrolle fürs Wohnzimmer kaufen",
    "mittelalterliches Dekret auf Schriftrolle schreiben",
    "alte Rolle im Dachbodentruhe finden",
    "Tora-Rolle zur Synagoge bringen",
    "Dokument zu einer Rolle einrollen",
    "Ausstellung der Schriftrollen vom Toten Meer besuchen",
    "Schriftrolle als Requisite für Schulaufführung basteln",
    "lateinischen Text auf alter Rolle übersetzen",
    "zerbrechliche Pergamentrolle konservieren",
    "Diplom als Schriftrolle einrahmen",
    "Rolleneinladungen für Hochzeit vorbereiten",
    "Museumsrolle fotografieren",
    "kalligrafische Schriftrolle bestellen",
    "Methoden zur Rollenkonservierung erforschen",
    "Abschlussrolle an die Wand hängen",
    # typos
    "Pergamentrole mit Band gebunden",
    "alte Schriftrole in Höhle entdeckt",
    "Tora-Role bei Synagogenzeremonie",
    "königliches Dekrt auf Schriftrolle",
    "Gelehrter list alte Schriftrolle",
],
ja=[
    "巻物", "羊皮紙", "文書", "布告", "写本",
    "パピルス", "古文書", "経典", "勅令", "宣言",
    "トーラの巻物", "台本", "告知", "憲章", "手稿",
    "古い文書", "巻いた紙", "羊皮紙の巻物",
    "羊皮紙の巻物に書かれた告知",
    "封蝋付きの巻物の王室布告",
    "ファンタジークエストの地図入り巻物",
    "広げた紙の巻物にメッセージが見える",
    "色あせた文字の古い紙の巻物",
    "図書館で古代の巻物を読む学者",
    "巻物のテキストを書き写す学者",
    "羊皮紙の巻物に書かれた台本",
    "リボンで結ばれた封蝋の巻物",
    "巻物を広げて布告を見せる",
    "リボンで結ばれた古代の羊皮紙巻物",
    "封蝋付きの巻いた紙の巻物",
    "公式巻物に書かれた王の布告",
    "シナゴーグの儀式でトーラの巻物",
    "洞窟で発見された歴史的な巻物",
    "巻物の中のファンタジー宝の地図",
    "歴史の授業のために古代の巻物を読む",
    "羊皮紙の巻物を広げて文章を確認する",
    "リビング用の装飾巻物を買う",
    "巻物に中世風の布告を書く",
    "屋根裏のトランクから古い巻物を見つける",
    "シナゴーグにトーラの巻物を持っていく",
    "文書を巻物状に巻く",
    "死海文書の展示を見学する",
    "学校劇の小道具として巻物を作る",
    "古い巻物のラテン語テキストを翻訳する",
    "壊れやすい羊皮紙の巻物を保存する",
    "卒業証書を巻物として額に入れる",
    "結婚式用の巻物招待状を準備する",
    "博物館の巻物展示を撮影する",
    "書道の巻物を注文する",
    "巻物の保存技術を研究する",
    "卒業の巻物を壁に飾る",
    # typos
    "まき物を広げて確認する",
    "古い巻もので歴史を学ぶ",
    "羊皮紙のまきものを保存する",
    "トーラの巻もの",
    "死海文書の展示を見がくする",
],
fr=[
    "parchemin", "rouleau", "document", "décret", "manuscrit",
    "papyrus", "texte ancien", "écriture", "édit", "proclamation",
    "rouleau de la Torah", "scénario", "annonce", "charte", "écrit",
    "vieux document", "papier roulé", "rouleau de parchemin",
    "annonce écrite sur un rouleau de parchemin",
    "annonce royale sur un rouleau scellé à la cire",
    "rouleau de quête fantaisie avec carte à l'intérieur",
    "rouleau de papier déroulé révélant un message",
    "vieux rouleau de papier à l'écriture effacée",
    "érudit lisant un ancien rouleau à la bibliothèque",
    "érudit transcrivant le texte d'un rouleau",
    "scénario écrit sur un rouleau de parchemin",
    "rouleau scellé à la cire attaché par un ruban",
    "rouleau déroulé montrant un décret",
    "ancien rouleau de parchemin noué avec un ruban",
    "rouleau de papier avec sceau de cire",
    "décret royal écrit sur un rouleau officiel",
    "rouleau de la Torah lors d'une cérémonie",
    "rouleau historique découvert dans une grotte",
    "carte au trésor dans un rouleau fantaisie",
    "lire l'ancien rouleau pour le cours d'histoire",
    "dérouler le parchemin et vérifier le texte",
    "acheter un rouleau décoratif pour le salon",
    "écrire un décret médiéval sur un rouleau",
    "trouver le vieux rouleau dans le coffre du grenier",
    "apporter le rouleau de la Torah à la synagogue",
    "enrouler le document en rouleau",
    "visiter l'exposition des manuscrits de la mer Morte",
    "fabriquer un rouleau pour la pièce de théâtre scolaire",
    "traduire le texte latin sur le vieux rouleau",
    "préserver le fragile rouleau de parchemin",
    "encadrer le diplôme sous forme de rouleau",
    "préparer des invitations en rouleau pour le mariage",
    "photographier le rouleau au musée",
    "commander un rouleau de calligraphie personnalisé",
    "étudier les techniques de conservation des rouleaux",
    "accrocher le rouleau de diplôme au mur",
    # typos
    "parchmein ancien avec ruban",
    "roulau de parchemin scellé",
    "décet royal sur un rouleau",
    "érudt lisant un rouleau ancien",
    "rouleua historique découvert dans une grotte",
],
es=[
    "pergamino", "rollo", "documento", "decreto", "manuscrito",
    "papiro", "texto antiguo", "escritura", "edicto", "proclamación",
    "rollo de la Torá", "guion", "anuncio", "carta", "escrito",
    "documento viejo", "papel enrollado", "rollo de pergamino",
    "anuncio escrito en un rollo de pergamino",
    "anuncio real en un rollo sellado con cera",
    "rollo de misión fantástica con mapa dentro",
    "rollo de papel desenrollado mostrando un mensaje",
    "viejo rollo de papel con escritura descolorida",
    "erudito leyendo un antiguo rollo en la biblioteca",
    "erudito transcribiendo el texto de un rollo",
    "guion escrito en un rollo de pergamino",
    "rollo sellado con cera atado con cinta",
    "rollo desenrollado mostrando un decreto",
    "antiguo rollo de pergamino atado con cinta",
    "rollo de papel enrollado con sello de cera",
    "decreto real escrito en un rollo oficial",
    "rollo de la Torá en ceremonia de sinagoga",
    "rollo histórico descubierto en una cueva",
    "mapa del tesoro dentro de un rollo fantástico",
    "leer el antiguo rollo para la clase de historia",
    "desenrollar el pergamino y revisar el texto",
    "comprar un rollo decorativo para la sala",
    "escribir un decreto medieval en un rollo",
    "encontrar el viejo rollo en el baúl del ático",
    "llevar el rollo de la Torá a la sinagoga",
    "enrollar el documento en forma de rollo",
    "visitar la exposición de los rollos del Mar Muerto",
    "hacer un rollo como utilería para la obra escolar",
    "traducir el texto en latín del viejo rollo",
    "preservar el frágil rollo de pergamino",
    "enmarcar el diploma en forma de rollo",
    "preparar invitaciones en rollo para la boda",
    "fotografiar el rollo en la exposición del museo",
    "encargar un rollo de caligrafía personalizado",
    "investigar técnicas de conservación de rollos",
    "colgar el rollo de graduación en la pared",
    # typos
    "pergamnio antiguo con cinta",
    "rollo de pergamno sellado",
    "decreto real en un rolo oficial",
    "erudto leyendo un rollo antiguo",
    "rollo histróico descubierto en una cueva",
],
)

# ── seedling ──────────────────────────────────────────────────────────────────
build("seedling",
en=[
    "seedling", "sprout", "sapling", "plant", "grow", "garden",
    "leaf", "greenery", "herb", "shoot", "bud", "germinate",
    "compost", "soil", "nursery plant", "potting", "transplant", "mulch",
    "watch a tiny plant grow over time",
    "grow your own herbs on the windowsill",
    "small plant emerging from the soil",
    "young sapling planted in the forest",
    "sapling tree growing in spring",
    "seedling sprouting from the ground",
    "seedling planted in a paper cup",
    "young plant just beginning to sprout",
    "young growth in the garden bed",
    "plant sprout just breaking through the ground",
    "seedling growing in a small biodegradable pot",
    "reforestation seedling planted by volunteers",
    "spring gardening with seedlings in a tray",
    "sustainable farming with young plant starts",
    "water the seedlings every morning",
    "transplant seedlings into the garden bed",
    "buy tomato seedlings at the nursery",
    "start seeds indoors for spring planting",
    "repot the sapling into a bigger container",
    "add compost around the young seedlings",
    "label the seedling trays by plant type",
    "protect seedlings from frost overnight",
    "thin out crowded seedlings in the tray",
    "harden off seedlings before moving outside",
    "plant herb seedlings in the kitchen window box",
    "germinate seeds in a damp paper towel",
    "check seedling growth progress this week",
    "order seedlings from the garden catalog",
    "mulch around seedlings to retain moisture",
    "pick up flower seedlings for the front yard",
    "set up grow lights for indoor seedlings",
    "prepare the soil before planting seedlings",
    "bring seedlings to the community garden event",
    "fertilize seedlings with diluted plant food",
    "pot the young sprouts into individual cups",
    "cover seedlings with plastic wrap for humidity",
    "move seedlings to the sunny side of the porch",
    "prune weak seedlings to encourage strong growth",
    # typos
    "small seeedling sprouting from soil",
    "saplign planted in the forest",
    "tiny seedlign with two leaves",
    "grwoing plant in a garden pot",
    "trasplant seedlings into garden bed",
],
ru=[
    "росток", "саженец", "растение", "рост", "сад",
    "лист", "зелень", "трава", "побег", "почка",
    "прорастание", "компост", "почва", "рассада", "пересадка",
    "мульча", "грунт", "всходы",
    "смотреть как маленькое растение растет",
    "вырастить травы на подоконнике",
    "маленькое растение выходит из почвы",
    "молодой саженец посажен в лесу",
    "саженец дерева растет весной",
    "росток пробивается из земли",
    "росток посажен в бумажный стаканчик",
    "молодое растение только начинает всходить",
    "молодой рост в грядке",
    "побег растения пробивает землю",
    "росток растет в маленьком биоразлагаемом горшке",
    "саженец для лесовосстановления посажен волонтерами",
    "весенняя посадка рассады в лотке",
    "устойчивое фермерство с молодыми растениями",
    "поливать рассаду каждое утро",
    "пересадить рассаду в садовую грядку",
    "купить рассаду помидоров в питомнике",
    "начать посев семян дома для весенней посадки",
    "пересадить саженец в горшок побольше",
    "добавить компост вокруг молодых саженцев",
    "подписать лотки с рассадой по типу растений",
    "защитить рассаду от ночных заморозков",
    "проредить густую рассаду в лотке",
    "закалить рассаду перед высадкой на улицу",
    "посадить саженцы трав в оконный ящик на кухне",
    "прорастить семена во влажной салфетке",
    "проверить рост рассады на этой неделе",
    "заказать саженцы из садового каталога",
    "замульчировать саженцы для сохранения влаги",
    "забрать цветочную рассаду для палисадника",
    "установить фитолампу для домашней рассады",
    "подготовить почву перед посадкой саженцев",
    "принести рассаду на мероприятие в общественном саду",
    "удобрить рассаду разбавленным растительным питанием",
    "рассадить молодые ростки по отдельным стаканчикам",
    "накрыть рассаду плёнкой для влажности",
    "переставить рассаду на солнечную сторону веранды",
    # typos
    "маленький росток пробивается из почвы",
    "саженец посажен в лесу",
    "крошечный росток с двумя листьями",
    "растущее растение в садовом горшке",
    "обрзать слабые ростки для роста",
],
de=[
    "Setzling", "Spross", "Sämling", "Pflanze", "wachsen", "Garten",
    "Blatt", "Grünzeug", "Kraut", "Trieb", "Knospe", "keimen",
    "Kompost", "Erde", "Gärtnerei", "Umtopfen", "Umpflanzen", "Mulch",
    "zusehen wie eine kleine Pflanze wächst",
    "eigene Kräuter auf der Fensterbank ziehen",
    "kleine Pflanze kommt aus der Erde",
    "junger Setzling im Wald gepflanzt",
    "Sämling wächst im Frühling",
    "Setzling keimt aus dem Boden",
    "Setzling in einem Pappbecher gepflanzt",
    "junge Pflanze beginnt zu sprießen",
    "junges Wachstum im Gartenbeet",
    "Pflanzentrieb bricht durch die Erde",
    "Setzling wächst in biologisch abbaubarem Topf",
    "Aufforstungs-Setzling von Freiwilligen gepflanzt",
    "Frühlingsgärtnern mit Setzlingen im Tablett",
    "nachhaltige Landwirtschaft mit jungen Pflanzen",
    "Setzlinge jeden Morgen gießen",
    "Setzlinge ins Gartenbeet umpflanzen",
    "Tomatensetzlinge in der Gärtnerei kaufen",
    "Samen drinnen für die Frühjahrsaussaat starten",
    "Sämling in einen größeren Behälter umtopfen",
    "Kompost um die jungen Setzlinge geben",
    "Setzlingstabletts nach Pflanzenart beschriften",
    "Setzlinge über Nacht vor Frost schützen",
    "dichte Setzlinge im Tablett ausdünnen",
    "Setzlinge vor dem Raussetzen abhärten",
    "Kräutersetzlinge in den Fensterkasten pflanzen",
    "Samen in einem feuchten Papiertuch keimen lassen",
    "Setzlingwachstum diese Woche prüfen",
    "Setzlinge aus dem Gartenkatalog bestellen",
    "Setzlinge mulchen um Feuchtigkeit zu halten",
    "Blumensetzlinge für den Vorgarten holen",
    "Pflanzenlampe für Zimmersetzlinge aufstellen",
    "Erde vor dem Pflanzen der Setzlinge vorbereiten",
    "Setzlinge zum Gemeinschaftsgarten-Event bringen",
    "Setzlinge mit verdünntem Pflanzendünger düngen",
    "junge Sprossen in einzelne Becher umtopfen",
    "Setzlinge mit Folie für Feuchtigkeit abdecken",
    "Setzlinge auf die sonnige Seite der Veranda stellen",
    # typos
    "Setzlinge jeden Moregen gießen",
    "Tomatensetlinge in der Gärtnerei kaufen",
    "Setzlinge ins Gartnbeet umpflanzen",
    "Samen in feuchtem Papirtuch keimen",
    "Setzlingwachstm diese Woche prüfen",
],
ja=[
    "苗", "芽", "若木", "植物", "育てる", "庭",
    "葉", "緑", "ハーブ", "新芽", "つぼみ", "発芽",
    "堆肥", "土", "苗木", "植え替え", "移植", "マルチ",
    "小さな植物が育つのを見守る",
    "窓辺で自分のハーブを育てる",
    "土から小さな植物が出てくる",
    "森に若い苗木を植える",
    "春に苗木が育つ",
    "地面から苗が芽を出す",
    "紙コップに苗を植える",
    "若い植物が芽を出し始める",
    "花壇の若い成長",
    "植物の芽が地面を突き破る",
    "生分解性ポットで苗が育つ",
    "ボランティアが植林用の苗を植える",
    "トレイに苗を入れて春の園芸",
    "若い苗で持続可能な農業",
    "毎朝苗に水をやる",
    "苗を庭の花壇に植え替える",
    "園芸店でトマトの苗を買う",
    "春の植え付けのために室内で種まき",
    "苗木を大きな容器に植え替える",
    "若い苗の周りに堆肥を加える",
    "苗トレイに植物の種類別にラベルを貼る",
    "夜の霜から苗を守る",
    "トレイの混み合った苗を間引く",
    "外に出す前に苗を慣らす",
    "台所の窓辺にハーブの苗を植える",
    "湿ったペーパータオルで種を発芽させる",
    "今週の苗の成長を確認する",
    "園芸カタログから苗を注文する",
    "苗の周りにマルチを敷いて水分を保つ",
    "前庭用の花の苗を買いに行く",
    "室内の苗用に育成ライトを設置する",
    "苗を植える前に土を準備する",
    "コミュニティガーデンのイベントに苗を持っていく",
    "薄めた液肥で苗に栄養を与える",
    "若い芽を個別のカップに植え替える",
    "湿度のために苗をラップで覆う",
    "苗をベランダの日当たりのよい場所に移す",
    # typos
    "毎朝なえに水をやる",
    "園芸店でとまとの苗をかう",
    "苗を庭のかだんに植え替える",
    "種をはつがさせる",
    "苗のせいちょうを確認する",
],
fr=[
    "semis", "pousse", "jeune plant", "plante", "pousser", "jardin",
    "feuille", "verdure", "herbe", "bourgeon", "bouton", "germer",
    "compost", "terre", "pépinière", "rempotage", "transplanter", "paillis",
    "regarder une petite plante pousser",
    "cultiver ses propres herbes sur le rebord",
    "petite plante qui sort de la terre",
    "jeune plant planté dans la forêt",
    "jeune arbre qui pousse au printemps",
    "semis qui germe du sol",
    "semis planté dans un gobelet en papier",
    "jeune plante qui commence à pousser",
    "jeune pousse dans le massif du jardin",
    "pousse de plante qui perce la terre",
    "semis qui pousse dans un pot biodégradable",
    "semis de reboisement planté par des bénévoles",
    "jardinage de printemps avec semis dans un plateau",
    "agriculture durable avec de jeunes plants",
    "arroser les semis chaque matin",
    "transplanter les semis dans le massif du jardin",
    "acheter des plants de tomates à la pépinière",
    "semer des graines en intérieur pour le printemps",
    "rempoter le jeune plant dans un pot plus grand",
    "ajouter du compost autour des jeunes semis",
    "étiqueter les plateaux de semis par type",
    "protéger les semis du gel nocturne",
    "éclaircir les semis serrés dans le plateau",
    "endurcir les semis avant de les sortir",
    "planter des herbes dans la jardinière de cuisine",
    "faire germer des graines dans un essuie-tout humide",
    "vérifier la croissance des semis cette semaine",
    "commander des plants depuis le catalogue de jardin",
    "pailler les semis pour garder l'humidité",
    "acheter des plants de fleurs pour le devant",
    "installer une lampe de croissance pour les semis",
    "préparer le sol avant de planter les semis",
    "apporter des semis à l'événement du jardin",
    "fertiliser les semis avec de l'engrais dilué",
    "rempoter les jeunes pousses dans des godets",
    "couvrir les semis de film pour l'humidité",
    "déplacer les semis au soleil sur la véranda",
    # typos
    "arrosr les semis chaque matin",
    "transplaner les semis dans le massif",
    "achter des plants de tomates",
    "semer des granes en intérieur",
    "vérifer la croissance des semis",
],
es=[
    "plántula", "brote", "arbolito", "planta", "crecer", "jardín",
    "hoja", "verdor", "hierba", "retoño", "yema", "germinar",
    "compost", "tierra", "vivero", "trasplante", "trasplantar", "mantillo",
    "ver crecer una pequeña planta con el tiempo",
    "cultivar hierbas propias en el alféizar",
    "pequeña planta que sale de la tierra",
    "arbolito joven plantado en el bosque",
    "arbolito que crece en primavera",
    "plántula que brota del suelo",
    "plántula plantada en un vaso de papel",
    "planta joven que empieza a brotar",
    "crecimiento joven en el cantero del jardín",
    "brote de planta que atraviesa la tierra",
    "plántula creciendo en maceta biodegradable",
    "plántula de reforestación plantada por voluntarios",
    "jardinería de primavera con plántulas en bandeja",
    "agricultura sostenible con plantas jóvenes",
    "regar las plántulas cada mañana",
    "trasplantar plántulas al cantero del jardín",
    "comprar plántulas de tomate en el vivero",
    "sembrar semillas en interior para la primavera",
    "trasplantar el arbolito a una maceta más grande",
    "añadir compost alrededor de las plántulas",
    "etiquetar las bandejas de plántulas por tipo",
    "proteger las plántulas de las heladas nocturnas",
    "aclarar las plántulas apretadas en la bandeja",
    "endurecer las plántulas antes de sacarlas",
    "plantar plántulas de hierbas en la jardinera",
    "germinar semillas en una servilleta húmeda",
    "revisar el crecimiento de las plántulas esta semana",
    "pedir plántulas del catálogo de jardín",
    "cubrir con mantillo para retener la humedad",
    "comprar plántulas de flores para el jardín delantero",
    "instalar luces de cultivo para plántulas de interior",
    "preparar la tierra antes de plantar plántulas",
    "llevar plántulas al evento del huerto comunitario",
    "fertilizar plántulas con alimento diluido",
    "trasplantar brotes jóvenes a vasos individuales",
    "cubrir plántulas con film para la humedad",
    "mover las plántulas al lado soleado del porche",
    # typos
    "regar las plántulas cada mañna",
    "trasplantar plántulas al cantro del jardín",
    "comprar plántulas de tomate en el vivro",
    "germinar semillas en una servileta húmeda",
    "revisar el crecimient de las plántulas",
],
)

print("Part 1 done: scissors, scroll, seedling")
