#!/usr/bin/env python3
"""Task-005 part 1: plane, plug"""
from gen_icons_task_005_common import gen

# ── plane ─────────────────────────────────────────────────────────────────────
gen("plane",
en=[
    # keywords (~18)
    "airplane",
    "flight",
    "fly",
    "travel by air",
    "trip",
    "destination",
    "air travel",
    "airline",
    "airport",
    "boarding pass",
    "airplane mode",
    "round trip",
    "one-way flight",
    "book a flight",
    "international flight",
    "domestic flight",
    "connecting flight",
    "nonstop flight",
    # phrases (~37)
    "check flight status before heading to the airport",
    "pack the carry-on bag for tomorrow's flight",
    "print boarding passes for the whole family",
    "compare flight prices for the holiday trip",
    "set an alarm for the early morning flight",
    "confirm the hotel at the destination",
    "get travel insurance for the international trip",
    "pick up the luggage at the destination airport",
    "arrange airport shuttle for Friday",
    "renew passport before the trip abroad",
    "check baggage weight limit for the airline",
    "download the airline app for mobile check-in",
    "fly to New York next Thursday",
    "book a direct flight to London",
    "find cheap flights for spring break",
    "cancel the flight reservation by midnight",
    "upgrade to business class if seats are available",
    "charge devices before the long flight",
    "buy snacks for the airplane",
    "text mom when the plane lands",
    "turn on airplane mode during takeoff",
    "pick seats with extra legroom",
    "check if the flight is delayed",
    "reserve a window seat on the return flight",
    "grab dinner at the airport before boarding",
    "call the airline about the lost suitcase",
    "apply for TSA precheck before the next trip",
    "check visa requirements for the destination country",
    "drop off rental car before the flight home",
    "arrive at the airport two hours early",
    "fly home for Thanksgiving",
    "plan a weekend trip to Chicago",
    "look into red-eye flights to save money",
    "exchange currency before the trip",
    "the flight got moved to a different gate",
    "remember to pack chargers for the plane ride",
    "need to book flights before prices go up",
    # typos (~5)
    "ariplane travel",
    "flght to Paris",
    "bording pass for the trip",
    "airprot shuttle pickup",
    "desination hotel confirmed",
],
ru=[
    "самолёт",
    "рейс",
    "лететь",
    "авиаперелёт",
    "поездка",
    "пункт назначения",
    "авиапутешествие",
    "авиакомпания",
    "аэропорт",
    "посадочный талон",
    "режим самолёта",
    "туда и обратно",
    "рейс в одну сторону",
    "забронировать рейс",
    "международный рейс",
    "внутренний рейс",
    "пересадочный рейс",
    "прямой рейс",
    "проверить статус рейса перед поездкой в аэропорт",
    "собрать ручную кладь к завтрашнему рейсу",
    "распечатать посадочные на всю семью",
    "сравнить цены на авиабилеты на праздники",
    "поставить будильник на ранний утренний рейс",
    "подтвердить отель в пункте назначения",
    "оформить страховку для международной поездки",
    "забрать багаж в аэропорту прилёта",
    "заказать трансфер из аэропорта на пятницу",
    "обновить загранпаспорт перед поездкой",
    "проверить допустимый вес багажа у авиакомпании",
    "скачать приложение авиакомпании для онлайн-регистрации",
    "лететь в Нью-Йорк в следующий четверг",
    "забронировать прямой рейс в Лондон",
    "найти дешёвые рейсы на весенние каникулы",
    "отменить бронь рейса до полуночи",
    "перейти в бизнес-класс если есть места",
    "зарядить устройства перед долгим перелётом",
    "купить перекус в самолёт",
    "написать маме когда самолёт приземлится",
    "включить режим самолёта при взлёте",
    "выбрать места с увеличенным пространством для ног",
    "проверить не задержан ли рейс",
    "забронировать место у окна на обратный рейс",
    "поужинать в аэропорту перед посадкой",
    "позвонить в авиакомпанию по поводу потерянного чемодана",
    "оформить предварительный досмотр перед следующей поездкой",
    "проверить визовые требования для страны назначения",
    "сдать прокатную машину до рейса домой",
    "приехать в аэропорт за два часа до вылета",
    "лететь домой на День благодарения",
    "спланировать поездку на выходные в Питер",
    "посмотреть ночные рейсы чтобы сэкономить",
    "обменять валюту перед поездкой",
    "рейс перенесли к другому гейту",
    "не забыть зарядки для перелёта",
    "надо забронировать билеты пока цены не выросли",
    "самалёт авиарейс",
    "рес в Париж",
    "пасадочный талон на поездку",
    "аэрпорт трансфер",
    "пунтк назначения подтверждён",
],
de=[
    "Flugzeug",
    "Flug",
    "fliegen",
    "Flugreise",
    "Reise",
    "Reiseziel",
    "Flughafen",
    "Fluggesellschaft",
    "Bordkarte",
    "Flugmodus",
    "Hin- und Rückflug",
    "Direktflug",
    "Inlandsflug",
    "Anschlussflug",
    "Flug buchen",
    "internationaler Flug",
    "Einwegflug",
    "Nonstop-Flug",
    "Flugstatus prüfen bevor ich zum Flughafen fahre",
    "Handgepäck für den morgigen Flug packen",
    "Bordkarten für die ganze Familie ausdrucken",
    "Flugpreise für die Urlaubsreise vergleichen",
    "Wecker für den frühen Morgenflug stellen",
    "Hotel am Reiseziel bestätigen",
    "Reiseversicherung für die Auslandsreise abschließen",
    "Gepäck am Zielflughafen abholen",
    "Flughafentransfer für Freitag organisieren",
    "Reisepass vor der Auslandsreise erneuern",
    "Freigepäckgrenze bei der Fluggesellschaft prüfen",
    "App der Airline für mobiles Einchecken herunterladen",
    "nächsten Donnerstag nach New York fliegen",
    "Direktflug nach London buchen",
    "günstige Flüge für die Frühlingsferien finden",
    "Flugbuchung bis Mitternacht stornieren",
    "auf Business Class upgraden falls Plätze frei sind",
    "Geräte vor dem langen Flug aufladen",
    "Snacks für den Flug kaufen",
    "Mama schreiben wenn das Flugzeug landet",
    "Flugmodus beim Start einschalten",
    "Sitze mit extra Beinfreiheit auswählen",
    "prüfen ob der Flug verspätet ist",
    "Fensterplatz für den Rückflug reservieren",
    "am Flughafen vor dem Boarding zu Abend essen",
    "Airline wegen des verlorenen Koffers anrufen",
    "Visumsanforderungen für das Zielland prüfen",
    "Mietwagen vor dem Rückflug abgeben",
    "zwei Stunden vor Abflug am Flughafen sein",
    "zu Weihnachten nach Hause fliegen",
    "Wochenendtrip nach München planen",
    "nach Nachtflügen schauen um Geld zu sparen",
    "Geld wechseln vor der Reise",
    "der Flug wurde zu einem anderen Gate verlegt",
    "Ladekabel für die Flugreise einpacken",
    "muss Flüge buchen bevor die Preise steigen",
    "Flughfaen Transfer buchen",
    "Flgumodus einschalten",
    "Bordkrate ausdrucken",
    "Reisziel Hotel bestätigen",
    "Fluggesllschaft anrufen",
],
ja=[
    "飛行機",
    "フライト",
    "飛ぶ",
    "空の旅",
    "旅行",
    "目的地",
    "空港",
    "航空会社",
    "搭乗券",
    "機内モード",
    "往復便",
    "直行便",
    "国内線",
    "国際線",
    "乗り継ぎ便",
    "航空券を予約する",
    "片道チケット",
    "格安航空券",
    "空港に向かう前にフライト状況を確認する",
    "明日のフライトのために手荷物をまとめる",
    "家族全員分の搭乗券を印刷する",
    "休暇旅行の航空券の値段を比較する",
    "早朝便のためにアラームをセットする",
    "目的地のホテルを確認する",
    "海外旅行の保険に入る",
    "到着空港で荷物を受け取る",
    "金曜日の空港送迎を手配する",
    "海外旅行の前にパスポートを更新する",
    "航空会社の手荷物制限を確認する",
    "モバイルチェックイン用に航空会社アプリをダウンロードする",
    "来週の木曜日にニューヨークへ飛ぶ",
    "ロンドンへの直行便を予約する",
    "春休みの安いフライトを探す",
    "深夜までにフライト予約をキャンセルする",
    "席が空いていればビジネスクラスにアップグレードする",
    "長時間フライトの前にデバイスを充電する",
    "飛行機用のお菓子を買う",
    "飛行機が着いたらお母さんにメッセージする",
    "離陸時に機内モードをオンにする",
    "足元の広い席を選ぶ",
    "フライトが遅延していないか確認する",
    "帰りの便の窓側席を予約する",
    "搭乗前に空港で夕食をとる",
    "紛失したスーツケースについて航空会社に電話する",
    "目的地の国のビザ要件を確認する",
    "帰りのフライトの前にレンタカーを返却する",
    "出発の2時間前に空港に着く",
    "感謝祭に実家へ飛ぶ",
    "週末のシカゴ旅行を計画する",
    "節約のために深夜便を検討する",
    "旅行前に外貨を両替する",
    "フライトのゲートが変更になった",
    "飛行機の中用に充電器を忘れずに持つ",
    "値段が上がる前にチケットを予約しなきゃ",
    "旅行のために荷造りリストを作る",
    "ひこうき旅行",
    "フラトイの予約",
    "くうこう送迎手配",
    "もくてきちのホテル確認",
    "とうじょう券を印刷",
],
fr=[
    "avion",
    "vol",
    "voler",
    "voyage aérien",
    "voyage",
    "destination",
    "aéroport",
    "compagnie aérienne",
    "carte d'embarquement",
    "mode avion",
    "aller-retour",
    "vol direct",
    "vol intérieur",
    "vol international",
    "correspondance",
    "réserver un vol",
    "vol aller simple",
    "vol sans escale",
    "vérifier le statut du vol avant d'aller à l'aéroport",
    "préparer le bagage à main pour le vol de demain",
    "imprimer les cartes d'embarquement pour toute la famille",
    "comparer les prix des vols pour les vacances",
    "mettre un réveil pour le vol tôt le matin",
    "confirmer l'hôtel à destination",
    "souscrire une assurance voyage pour le voyage international",
    "récupérer les bagages à l'aéroport d'arrivée",
    "organiser le transfert aéroport pour vendredi",
    "renouveler le passeport avant le voyage à l'étranger",
    "vérifier la franchise bagage de la compagnie aérienne",
    "télécharger l'appli de la compagnie pour l'enregistrement",
    "voler vers New York jeudi prochain",
    "réserver un vol direct pour Londres",
    "trouver des vols pas chers pour les vacances de printemps",
    "annuler la réservation de vol avant minuit",
    "passer en classe affaires s'il reste des places",
    "charger les appareils avant le long vol",
    "acheter des snacks pour l'avion",
    "envoyer un message à maman quand l'avion atterrit",
    "activer le mode avion au décollage",
    "choisir des sièges avec plus d'espace pour les jambes",
    "vérifier si le vol est retardé",
    "réserver un siège hublot pour le vol retour",
    "dîner à l'aéroport avant l'embarquement",
    "appeler la compagnie pour la valise perdue",
    "vérifier les conditions de visa pour le pays de destination",
    "rendre la voiture de location avant le vol retour",
    "arriver à l'aéroport deux heures en avance",
    "rentrer en avion pour Noël",
    "planifier un week-end à Marseille",
    "regarder les vols de nuit pour économiser",
    "changer de l'argent avant le voyage",
    "le vol a été déplacé vers une autre porte",
    "ne pas oublier les chargeurs pour le trajet en avion",
    "il faut réserver les vols avant la hausse des prix",
    "faire la liste des bagages pour le voyage",
    "avoin en retard",
    "vlo direct pour Paris",
    "aéroprot transfert vendredi",
    "carte d'embarqument imprimée",
    "destiantion confirmée",
],
es=[
    "avión",
    "vuelo",
    "volar",
    "viaje aéreo",
    "viaje",
    "destino",
    "aeropuerto",
    "aerolínea",
    "tarjeta de embarque",
    "modo avión",
    "ida y vuelta",
    "vuelo directo",
    "vuelo nacional",
    "vuelo internacional",
    "vuelo con escala",
    "reservar un vuelo",
    "vuelo de ida",
    "vuelo sin escalas",
    "revisar el estado del vuelo antes de ir al aeropuerto",
    "preparar el equipaje de mano para el vuelo de mañana",
    "imprimir las tarjetas de embarque para toda la familia",
    "comparar precios de vuelos para las vacaciones",
    "poner alarma para el vuelo temprano por la mañana",
    "confirmar el hotel en el destino",
    "contratar seguro de viaje para el vuelo internacional",
    "recoger el equipaje en el aeropuerto de llegada",
    "organizar el traslado al aeropuerto para el viernes",
    "renovar el pasaporte antes del viaje al extranjero",
    "revisar el límite de equipaje de la aerolínea",
    "descargar la app de la aerolínea para el check-in",
    "volar a Nueva York el próximo jueves",
    "reservar un vuelo directo a Londres",
    "buscar vuelos baratos para vacaciones de primavera",
    "cancelar la reserva del vuelo antes de medianoche",
    "subir a clase ejecutiva si hay asientos disponibles",
    "cargar los dispositivos antes del vuelo largo",
    "comprar snacks para el avión",
    "escribirle a mamá cuando aterrice el avión",
    "activar el modo avión durante el despegue",
    "elegir asientos con más espacio para las piernas",
    "verificar si el vuelo está retrasado",
    "reservar asiento de ventanilla para el vuelo de regreso",
    "cenar en el aeropuerto antes del embarque",
    "llamar a la aerolínea por la maleta perdida",
    "revisar los requisitos de visa para el país de destino",
    "devolver el auto rentado antes del vuelo de regreso",
    "llegar al aeropuerto dos horas antes de la salida",
    "volar a casa para Navidad",
    "planear una escapada de fin de semana a Barcelona",
    "buscar vuelos nocturnos para ahorrar dinero",
    "cambiar dinero antes del viaje",
    "el vuelo fue cambiado a otra puerta de embarque",
    "no olvidar los cargadores para el vuelo",
    "hay que reservar los vuelos antes de que suban los precios",
    "hacer la lista del equipaje para el viaje",
    "avón retrasado",
    "vuleo directo a París",
    "aeropuetro traslado viernes",
    "tarjeta de embarqeu impresa",
    "destno del hotel confirmado",
])


# ── plug ──────────────────────────────────────────────────────────────────────
gen("plug",
en=[
    "plug",
    "power plug",
    "electric plug",
    "plug in",
    "connect",
    "electricity",
    "power",
    "adapter plug",
    "outlet",
    "wall plug",
    "extension cord",
    "power cable",
    "smart plug",
    "travel adapter",
    "charger plug",
    "USB plug",
    "three-prong plug",
    "power strip",
    "plug in the phone charger before bed",
    "buy a travel adapter plug for the Europe trip",
    "the power plug came loose from the wall",
    "plug in the laptop to charge it overnight",
    "replace the broken plug on the extension cord",
    "connect the TV to the power outlet",
    "check if the dryer plug fits the outlet",
    "buy a new power strip for the home office",
    "unplug everything before the thunderstorm",
    "the smart plug keeps disconnecting from WiFi",
    "plug in the Christmas lights tonight",
    "get an adapter plug for the UK outlet",
    "connect the printer to the wall plug",
    "replace the frayed plug on the lamp cord",
    "plug in the slow cooker for dinner tonight",
    "check which outlet the fridge is plugged into",
    "buy a USB plug for the car charger",
    "the outlet in the kitchen stopped working",
    "plug the router back in after the power outage",
    "get a three-prong adapter for the old outlet",
    "connect the electric heater to the plug",
    "move the power strip behind the desk",
    "plug in the vacuum before cleaning",
    "check the plug wiring in the garage",
    "buy outdoor extension cord with weatherproof plug",
    "the electric plug sparked when I plugged it in",
    "unplug the toaster when not in use",
    "set up the smart plug with the app",
    "connect the monitor to the power cable",
    "the plug adapter doesn't fit this outlet",
    "rewire the broken power plug",
    "plug in the air purifier in the bedroom",
    "check if the outlet is grounded properly",
    "buy a surge protector for the computer plug",
    "connect the washing machine to the outlet",
    "the plug fell out of the socket again",
    "need to buy new plugs for the workshop",
    "plgu in charger",
    "electrc plug broken",
    "powre strip for office",
    "conect the printer plug",
    "adaptor plg for travel",
],
ru=[
    "вилка",
    "электрическая вилка",
    "штепсель",
    "подключить",
    "электричество",
    "питание",
    "адаптер",
    "розетка",
    "удлинитель",
    "кабель питания",
    "умная розетка",
    "переходник",
    "зарядная вилка",
    "USB вилка",
    "трёхштырьковая вилка",
    "сетевой фильтр",
    "вилка зарядки",
    "силовой кабель",
    "воткнуть зарядку телефона перед сном",
    "купить переходник для поездки в Европу",
    "вилка питания расшаталась в стене",
    "подключить ноутбук к зарядке на ночь",
    "заменить сломанную вилку на удлинителе",
    "подключить телевизор к розетке",
    "проверить подходит ли вилка сушилки к розетке",
    "купить новый сетевой фильтр для домашнего офиса",
    "выдернуть всё из розеток перед грозой",
    "умная розетка постоянно отключается от WiFi",
    "воткнуть гирлянду сегодня вечером",
    "взять адаптер для британской розетки",
    "подключить принтер к розетке",
    "заменить потёртую вилку на проводе лампы",
    "включить мультиварку на ужин",
    "проверить в какую розетку включён холодильник",
    "купить USB вилку для автомобильной зарядки",
    "розетка на кухне перестала работать",
    "воткнуть роутер обратно после отключения электричества",
    "взять переходник для старой розетки",
    "подключить обогреватель к розетке",
    "переставить сетевой фильтр за стол",
    "включить пылесос перед уборкой",
    "проверить проводку вилки в гараже",
    "купить уличный удлинитель с влагозащитной вилкой",
    "вилка искрила когда воткнул в розетку",
    "выдёргивать тостер когда не используется",
    "настроить умную розетку через приложение",
    "подключить монитор к кабелю питания",
    "адаптер не подходит к этой розетке",
    "перепаять сломанную вилку",
    "включить очиститель воздуха в спальне",
    "проверить заземлена ли розетка",
    "купить сетевой фильтр для компьютера",
    "подключить стиральную машину к розетке",
    "вилка опять выпала из розетки",
    "надо купить новые вилки для мастерской",
    "вилак зарядки",
    "электрческая вилка сломалась",
    "подклчить принтер",
    "розтека на кухне",
    "удлиннитель для офиса",
],
de=[
    "Stecker",
    "Netzstecker",
    "Stromstecker",
    "einstecken",
    "anschließen",
    "Strom",
    "Stromversorgung",
    "Adapter",
    "Steckdose",
    "Verlängerungskabel",
    "Netzkabel",
    "Smartstecker",
    "Reiseadapter",
    "Ladestecker",
    "USB-Stecker",
    "Schutzkontaktstecker",
    "Mehrfachsteckdose",
    "Stromkabel",
    "das Handy-Ladegerät vor dem Schlafen einstecken",
    "einen Reiseadapter für die Europareise kaufen",
    "der Stecker ist aus der Wand gerutscht",
    "den Laptop über Nacht zum Laden einstecken",
    "den kaputten Stecker am Verlängerungskabel ersetzen",
    "den Fernseher an die Steckdose anschließen",
    "prüfen ob der Trockner-Stecker in die Steckdose passt",
    "eine neue Mehrfachsteckdose fürs Homeoffice kaufen",
    "alles ausstecken vor dem Gewitter",
    "der Smartstecker verliert ständig die WLAN-Verbindung",
    "die Weihnachtsbeleuchtung heute Abend einstecken",
    "einen Adapter für die britische Steckdose besorgen",
    "den Drucker an die Wandsteckdose anschließen",
    "den ausgefransten Stecker an der Lampe ersetzen",
    "den Slow Cooker fürs Abendessen einstecken",
    "prüfen in welcher Steckdose der Kühlschrank steckt",
    "einen USB-Stecker für das Autoladegerät kaufen",
    "die Steckdose in der Küche funktioniert nicht mehr",
    "den Router nach dem Stromausfall wieder einstecken",
    "einen Adapter für die alte Steckdose holen",
    "die Heizung an die Steckdose anschließen",
    "die Mehrfachsteckdose hinter den Schreibtisch legen",
    "den Staubsauger vor dem Putzen einstecken",
    "die Stecker-Verkabelung in der Garage prüfen",
    "ein wetterfestes Verlängerungskabel für draußen kaufen",
    "der Stecker hat gefunkt beim Einstecken",
    "den Toaster ausstecken wenn er nicht benutzt wird",
    "den Smartstecker mit der App einrichten",
    "den Monitor an das Netzkabel anschließen",
    "der Adapter passt nicht in diese Steckdose",
    "den kaputten Netzstecker neu verdrahten",
    "den Luftreiniger im Schlafzimmer einstecken",
    "prüfen ob die Steckdose richtig geerdet ist",
    "einen Überspannungsschutz für den Computer kaufen",
    "die Waschmaschine an die Steckdose anschließen",
    "der Stecker ist wieder aus der Dose gefallen",
    "muss neue Stecker für die Werkstatt kaufen",
    "Steker einstecken",
    "Verlängerunskabel kaufen",
    "Steckdse in der Küche",
    "Netzsecker kaputt",
    "Ladegerät anschießen",
],
ja=[
    "プラグ",
    "電源プラグ",
    "コンセント",
    "差し込む",
    "接続する",
    "電気",
    "電源",
    "変換アダプター",
    "壁のコンセント",
    "延長コード",
    "電源ケーブル",
    "スマートプラグ",
    "旅行用アダプター",
    "充電プラグ",
    "USBプラグ",
    "三芯プラグ",
    "電源タップ",
    "ACアダプター",
    "寝る前にスマホの充電器をコンセントに差す",
    "ヨーロッパ旅行用の変換プラグを買う",
    "電源プラグが壁から抜けかけている",
    "ノートパソコンを一晩充電するために差し込む",
    "延長コードの壊れたプラグを交換する",
    "テレビをコンセントに接続する",
    "乾燥機のプラグがコンセントに合うか確認する",
    "ホームオフィス用に新しい電源タップを買う",
    "雷の前にすべてのプラグを抜く",
    "スマートプラグがWiFiから切断され続ける",
    "今夜クリスマスのイルミネーションを差し込む",
    "イギリスのコンセント用アダプターを手に入れる",
    "プリンターを壁のコンセントに接続する",
    "ランプのコードの傷んだプラグを交換する",
    "夕食のためにスロークッカーのプラグを差す",
    "冷蔵庫がどのコンセントに繋がっているか確認する",
    "車の充電器用にUSBプラグを買う",
    "キッチンのコンセントが動かなくなった",
    "停電後にルーターを差し直す",
    "古いコンセント用の変換アダプターを買う",
    "ヒーターをコンセントに接続する",
    "電源タップを机の後ろに移動する",
    "掃除の前に掃除機のプラグを差す",
    "ガレージのプラグの配線を確認する",
    "屋外用の防水延長コードを買う",
    "プラグを差したら火花が出た",
    "使わないときはトースターのプラグを抜く",
    "アプリでスマートプラグを設定する",
    "モニターを電源ケーブルに接続する",
    "アダプターがこのコンセントに合わない",
    "壊れた電源プラグを修理する",
    "寝室で空気清浄機のプラグを差す",
    "コンセントが正しく接地されているか確認する",
    "パソコン用のサージプロテクターを買う",
    "洗濯機をコンセントに繋ぐ",
    "プラグがまたコンセントから抜け落ちた",
    "作業場用に新しいプラグを買わないと",
    "プラグをさしこむ",
    "でんげんケーブル接続",
    "コンセトに差す",
    "じゅうでんプラグ購入",
    "えんちょうコード買う",
],
fr=[
    "prise",
    "fiche électrique",
    "brancher",
    "connecter",
    "électricité",
    "alimentation",
    "adaptateur",
    "prise murale",
    "rallonge",
    "câble d'alimentation",
    "prise connectée",
    "adaptateur de voyage",
    "fiche de charge",
    "prise USB",
    "prise à trois broches",
    "multiprise",
    "fiche secteur",
    "câble secteur",
    "brancher le chargeur du téléphone avant de dormir",
    "acheter un adaptateur de voyage pour l'Europe",
    "la fiche est sortie du mur",
    "brancher le portable pour le charger cette nuit",
    "remplacer la fiche cassée de la rallonge",
    "connecter la télé à la prise murale",
    "vérifier si la fiche du sèche-linge entre dans la prise",
    "acheter une nouvelle multiprise pour le bureau",
    "tout débrancher avant l'orage",
    "la prise connectée se déconnecte du WiFi",
    "brancher les guirlandes de Noël ce soir",
    "prendre un adaptateur pour la prise britannique",
    "connecter l'imprimante à la prise murale",
    "remplacer la fiche abîmée du câble de lampe",
    "brancher la mijoteuse pour le dîner de ce soir",
    "vérifier sur quelle prise le frigo est branché",
    "acheter une fiche USB pour le chargeur de voiture",
    "la prise de la cuisine ne marche plus",
    "rebrancher le routeur après la coupure de courant",
    "prendre un adaptateur pour la vieille prise",
    "connecter le chauffage à la prise",
    "déplacer la multiprise derrière le bureau",
    "brancher l'aspirateur avant de nettoyer",
    "vérifier le câblage de la prise dans le garage",
    "acheter une rallonge extérieure étanche",
    "la fiche a fait des étincelles en la branchant",
    "débrancher le grille-pain quand on ne l'utilise pas",
    "configurer la prise connectée avec l'application",
    "connecter l'écran au câble d'alimentation",
    "l'adaptateur ne rentre pas dans cette prise",
    "recâbler la fiche cassée",
    "brancher le purificateur d'air dans la chambre",
    "vérifier si la prise est bien mise à la terre",
    "acheter un parasurtenseur pour l'ordinateur",
    "connecter le lave-linge à la prise",
    "la fiche est encore tombée de la prise",
    "il faut acheter de nouvelles fiches pour l'atelier",
    "bracher le chargeur",
    "prsie murale cassée",
    "adaptaeur de voyage",
    "multiprse pour bureau",
    "câble d'alimentaiton",
],
es=[
    "enchufe",
    "clavija",
    "enchufar",
    "conectar",
    "electricidad",
    "corriente",
    "adaptador",
    "tomacorriente",
    "extensión eléctrica",
    "cable de alimentación",
    "enchufe inteligente",
    "adaptador de viaje",
    "clavija de carga",
    "enchufe USB",
    "enchufe de tres patas",
    "regleta",
    "cable de corriente",
    "enchufe de pared",
    "enchufar el cargador del teléfono antes de dormir",
    "comprar un adaptador de enchufe para el viaje a Europa",
    "el enchufe se soltó de la pared",
    "enchufar la laptop para cargarla en la noche",
    "reemplazar la clavija rota de la extensión",
    "conectar la tele al tomacorriente",
    "revisar si la clavija de la secadora entra en el enchufe",
    "comprar una regleta nueva para la oficina en casa",
    "desenchufar todo antes de la tormenta",
    "el enchufe inteligente se desconecta del WiFi",
    "enchufar las luces de Navidad esta noche",
    "conseguir un adaptador para el enchufe británico",
    "conectar la impresora al enchufe de pared",
    "cambiar la clavija dañada del cable de la lámpara",
    "enchufar la olla de cocción lenta para la cena",
    "revisar en cuál tomacorriente está enchufado el refrigerador",
    "comprar un enchufe USB para el cargador del carro",
    "el tomacorriente de la cocina dejó de funcionar",
    "volver a enchufar el router después del apagón",
    "conseguir un adaptador para el enchufe viejo",
    "conectar el calentador al enchufe",
    "mover la regleta detrás del escritorio",
    "enchufar la aspiradora antes de limpiar",
    "revisar el cableado del enchufe en el garaje",
    "comprar una extensión para exteriores resistente al agua",
    "el enchufe hizo chispas al enchufarlo",
    "desenchufar la tostadora cuando no se use",
    "configurar el enchufe inteligente con la app",
    "conectar el monitor al cable de alimentación",
    "el adaptador no entra en este tomacorriente",
    "reparar la clavija de corriente rota",
    "enchufar el purificador de aire en el dormitorio",
    "revisar si el tomacorriente tiene buena tierra",
    "comprar un protector de voltaje para la computadora",
    "conectar la lavadora al tomacorriente",
    "la clavija se salió del enchufe otra vez",
    "necesito comprar enchufes nuevos para el taller",
    "enchufr el cargador",
    "toma corrente de la cocina",
    "adapatdor de viaje",
    "reglta para oficina",
    "cable de alimnetación",
])

print("\n=== Part 1 done (plane, plug) ===")
